### ISSUE TITLE
XSS on OpenEMR

### ISSUE THREAD

**Issue by f1re-w1re** [openemr/openemr#1011]
Hello, 

I found a cross site scripting flaw on my latest copy of OpenEMR, is this the proper place to post it? Seems like it would be public disclose if I do. 

Please let me know, thanks!

**Comment by bradymiller** [comment]
hi @f1re-w1re ,
Thanks for reporting this. Best to email it to me at brady.g.miller@gmail.com . I'd prefer email encrypted via PGP, if possible, and my public key is here: https://pgp.mit.edu/pks/lookup?op=get&search=0x27DEF05B1A8A6D4F

**Comment by ASC** [comment]
Hi,
Sorry to hijack this thread but I've also got an XSS which I'll put in an email to you if that's alright.

Cheers

ASC

**Comment by priya-anand** [comment]
Hi Brady, 

We were working on this XSS issues reported in 'gacl' module, as we mentioned in our early communications, we are developing a tool to identify the potential XSS in OpenEMR. We would like to discuss about it and share our analysis, with possible fixes. I will send a separate email about it.

- Priya

**Comment by ASC** [comment]
Priya,

I believe tools like this already exist e.g. this one: 
https://github.com/bugbountyforum/XSS-Radar
You may find it helpful in your quest!

ASC

**Comment by priya-anand** [comment]
ASC, Thanks for sharing this one.... Actually, we are working on developing a tool to implement security patterns, and as an extension of our tool features, we are trying to detect possible XSS vulnerabilities. XSS - radar is a nice one as well, and we are focusing on identifying stored-XSS as well. I will compare our results with XSS-radar, and see how it works.

**Comment by f1re-w1re** [comment]
Hi @bradymiller,

I sent you an encrypted email, thank you for the pub key.

Cheers!

**Comment by bradymiller** [comment]
Confirming receipt of both encrypted emails from @f1re-w1re and @ASC .
After doing a bit of analysis, I'll get back to both of you.
And looking forward to your email @priya-anand .
thanks!
-brady

(btw, if there are any developers that are interested in working on security fixes and want to get these messages, just send me your PGP public key and I'll forward you this stuff)

**Comment by attritionorg** [comment]
@priya-anand You say the 'gacl' module, can you confirm that is the third-party phpGACL module, as documented here: https://github.com/openemr/openemr/blob/master/gacl/README

If so, has it been reported upstream?

**Comment by bradymiller** [comment]
Hi @f1re-w1re ,
I wasn't able to confirm the issue you emailed on either 5.0.0(with patch 3) or on the most recent codebase. What version were you testing?
thanks,
-brady

**Comment by bradymiller** [comment]
Disregard my above post.

I Just confirmed it on most recent codebase.

Interestingly, this doesn't happen in 5.0.0(3) secondary to aggressive conversion of any non latin character 1 underscore.

**Comment by bradymiller** [comment]
@f1re-w1re,
Just committed the fix for this to the codebase. Using this strategy in the rest of the smarty code: https://github.com/openemr/openemr/issues/799

**Comment by f1re-w1re** [comment]
Thank you, Brady, for the speedy patch and update. Closing this thread for now. Godspeed!

**Comment by ASC** [comment]
Hi,
Not sure that the issue I raised via email has been resolved yet so will open a separate issue in order to track.  see  #1018
ASC

**Comment by sharonco-matrix** [comment]
I have a security report, with some vulnerabilities. Maybe we can work together to fix them? let me know to whom send the report

**Comment by bradymiller** [comment]
hi @sharonco-matrix ,

Ideally, best to send me a PGP encrypted email to brady.g.miller@gmail.com. My public PGP key is here:
https://pgp.mit.edu/pks/lookup?op=get&search=0x27DEF05B1A8A6D4F

-brady

**Comment by bradymiller** [comment]
(btw, offer still stands; if there are any developers that are interested in working on security fixes and want to get these messages, just send me your PGP public key and I'll forward you this stuff)

**Comment by ASC** [comment]
@bradymiller - Happy to take on the work of investigating and patching sec issues. You have my key already :-)

**Comment by priya-anand** [comment]
@attritionorg : It is not the third-party 'gacl' module, as documented here: https://github.com/openemr/openemr/blob/master/gacl/README
but this one https://github.com/openemr/openemr/tree/master/gacl

**Comment by bradymiller** [comment]
Note this did originate from the third-party gacl module. However, that project has been stale since 2006, so we (openemr) are now responsible for the code inside openemr (we've had to make significant changes in it over the years for modernization, bug fixes, etc.).

**Comment by priya-anand** [comment]
Hi Sharon,

Not sure how I missed this message, if it is not too late, can you please send me the report? I got list of some XSS vulnerabilities (mainly stored XSS) and I would like to compare my vulnerability analysis with your report.

- Priya
