### ISSUE TITLE
Autoloader Optimization

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#1013]
[Composer documentation](https://getcomposer.org/doc/articles/autoloader-optimization.md#autoloader-optimization) recommends 3 options to optimize/speed up autoloading process.

Since config key option is currently not implemented, can someone confirm that release scripts use the recommended run-time options?

**Comment by bradymiller** [comment]
@mdsupport ,
Here's the current command used to prep autoloader:
``````
composer dump-autoload -o
``````
So, we already do the first option discussed in above link. Do you have thoughts on the other 2 (looks like that we can only choose 1 of those options).
(btw, here's openemr composer info on wiki: http://www.open-emr.org/wiki/index.php/Composer )
-brady

**Comment by mdsupport** [comment]
Perfect.
We are tracing performance issues so going through the checklists to find root cause.
Thx.
