### ISSUE TITLE
XSS in Patient Record

### ISSUE THREAD

**Issue by ASC** [openemr/openemr#1018]
As per email to @bradymiller

**Comment by bradymiller** [comment]
hi @ASC ,
This is next in my queue.
thanks, -brady

**Comment by ASC** [comment]
Hi Brady, 

I'm happy to work on a fix in fork and submit a pull request if that helps? Could save you some time?

ASC

**Comment by bradymiller** [comment]
Hi @ASC ,
Always very happy to have others contribute and would be awesome if you would submit a PR for this. And looking forward to seeing the PR. (Just let me know if need guidance or if need to hand it back to me.)
thanks! -brady

**Comment by bradymiller** [comment]
looks good and thanks for the contribution!
Will also include in the next 5.0.0 patch.
