### ISSUE TITLE
move globals->appearance->default encounter view to user setting

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#1022]
it probably makes sense to make this be a user choice clinical or billing for this setting

**Comment by bradymiller** [comment]
Sounds good. This is easy to do by adding the setting here:
https://github.com/openemr/openemr/blob/master/library/globals.inc.php#L102-L122

**Comment by stephenwaite** [comment]
nice, that's pretty obvious now that I see it :)
thanks for the quick pointer
