### ISSUE TITLE
click to view document opens blank tab

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#1029]
the document loads inside the openemr tab but a blank tab is created which becomes active with this url:

http://demo.open-emr.org:2089/openemr/ccr/display.php?type=CCD&doc_id=2

**Comment by stephenwaite** [comment]
guess this is the culprit

https://github.com/openemr/openemr/blob/master/controllers/C_Document.class.php#L1167

**Comment by bradymiller** [comment]
@stephenwaite ,
See my post on the above PR.

**Comment by bradymiller** [comment]
placed a improved solution here:
https://github.com/openemr/openemr/pull/1048

**Comment by stephenwaite** [comment]
thanks for the contribution @bradymiller ;)
