### ISSUE TITLE
Sepsis Screening Tool

### ISSUE THREAD

**Issue by ASC** [openemr/openemr#1035]
Hi Community,
Looking for some questions answered with regards to this...
I will try and explain the best I can.

**Background**
One of the main clinical systems we use in the UK is called SystmOne - it has the ability to create custom protocols (similar to macros) which are triggered by certain events in the patient record. 
One of the protocols which someone has written for it is a Sepsis Screening Tool. Sepsis kills over 40,000 people in the UK every year.

My aim is to build a similar tool for OpenEMR which takes into account ICD9 and 10 codes, keywords and vital measurements e.g. temperature to assess a patient for Sepsis and if necessary flag a warning up to the doctor.

Image: An example of the popup we get in SystmOne. In this case I typed in the history that the patient had a fever and increased heart rate and this popup was triggered.
![screenshot 2017-08-20 21 50 38](https://user-images.githubusercontent.com/4623934/29591051-b9592df6-8794-11e7-91f6-7d58059e5631.png)

PDF File: An example of the protocol which would be followed for diagnosis
https://www.nuh.nhs.uk/media/1725749/newsstforobs_chart.pdf

**Questions**

Developers - how would you best integrate this feature into OpenEMR? I am aware that there are clinical reminders in each patient - but this is more for routine items and only loads when the record is refreshed. 

I have had a quick play with some code and have some code sitting in the `save.php`code which saves the encounter. If the word 'fever' is seen in the consultation notes, it presents a javascript alert. Obviously in the production version it would be a bit more complex - we would look at ICD9/10 codes and vitals measurements as well (and even the age of the patient is a factor) to get a better picture. 
I would probably put the main bulk of the code in /library and then php require it in to `save.php` so it acts as a middleware of sorts. 

This brings me neatly on to my second question... in my brief example I have entered data only into the main brief description field.

![screenshot 2017-08-22 23 57 53](https://user-images.githubusercontent.com/4623934/29591332-fd097ce4-8795-11e7-9e7f-1c7e7e1e726d.png)
 
As we all know, OpenEMR has so many various forms (SOAP, Treatment Plan etc) where this info could be written that my mind is spinning working just how to handle all these different sources! Advice appreciated. Maybe we need to poll some of the users of OpenEMR where they enter the most of their information. Do they code everything such as 'fever', and enter temperature into the right form, or are they lazy and just free-text it all into one box? 

If this is the case, I also have some code in the works which would take the phrase...
"patient has a temperature of 39" and extract the 39 so we can perform operations on it. Obviously this wouldn't be perfect and I haven't worked out how to handle people using fahrenheit or celsius. I don't want so many false positives that users start ignoring the alerts.

**Disclaimer**

Obviously this goes without saying but this would be a tool to aid, not replace clinical judgement. In an ideal scenario a popup will be generated explaining WHY the system thinks the patient is a sespsis risk along with a pathway for the doctor to follow to further screen patient. 

I would LIKE the feature to be on by default, with the option of turning it off... purely because of the amount of lives claimed by Sepsis. However, if we need to turn it off by default I will oblige!

**Comment by ASC** [comment]
Another useful source document http://sepsistrust.org/wp-content/uploads/2016/07/PH-adult-NICE-Final.pdf

**Comment by robertdown** [comment]
Sepsis tools are pretty common; I know at my facility they are automatically triggered based on clinical rules. My guess is this is exactly what you're talking about now. @bradymiller I don't have much experience with the Clinical Decision Rules Engine, but is this a good fit? I'm going to reach out to a professor who also heads a Sepsis team locally to get some clinical feedback on this feature. This will be a great feature for our Inpatient Model.

**Comment by ASC** [comment]
@robertdown I agree this feature would be useful in an Inpatient but I'm also keen for it to be available in primary care to catch to early signs.

**Comment by ASC** [comment]
Around 3 mins 30 secs in this video shows an example of a similar tool in primary care. 
https://www.youtube.com/watch?v=h7YpHgK6YiQ

**Comment by MatthewVita** [comment]
@ASC would you be interested in implementing a Sepsis protocol that a Dr. at the WONCA SAR conference presented on? He is excited to digitalize it (it is paper based) and spread it around the world so that it can be improved.

BTW, nice to meet you. I'm one of the admins of OpenEMR.
