### ISSUE TITLE
composer with xdebug

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#1036]
looking at Travis details and found this:
>You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug

is this something that we can configure?

**Comment by MatthewVita** [comment]
Hmm, I would assume this is something that we can't change because it's up to Travis to configure PHP.

There appears to be an issue here about the subject: https://github.com/travis-ci/travis-ci/issues/5780

Interesting

**Comment by stephenwaite** [comment]
thanks for the research @MatthewVita since this is upstream maybe i should close this issue and hope to see some progress down the road from the travis folks?

**Comment by MatthewVita** [comment]
Sounds like a plan!
