### ISSUE TITLE
Define "Quality Reporting" project

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#1041]
![image](https://user-images.githubusercontent.com/1715206/29746550-a19d8954-8aab-11e7-8fc1-a8ae870a0411.png)

Need to work with Lou to describe this project. The project should have:

- Github issues in a kanban board
- Chat room for live conversations
- Teammates
- Leader of the team
- Mockups/Diagrams

**Comment by MatthewVita** [comment]
(I'm going to invite Joyce to our Github. She has offered to help with project management work, so I'll assign her to this if she is able to work on it!)

**Comment by MatthewVita** [comment]
The key to this ticket is talking with Lou :)

**Comment by stephenwaite** [comment]
thanks for outlining the core roadmap

another main part of this issue is using openemr to produce the qrda files that can be directly submitted to [cms](https://www.cms.gov/Regulations-and-Guidance/Legislation/EHRIncentivePrograms/Downloads/eCQM_QRDA_EC.pdf)

**Comment by stephenwaite** [comment]
subcategories of the quality reporting could include "advancing care information", https://qpp.cms.gov/mips/advancing-care-information, and "improvement activities", https://qpp.cms.gov/mips/improvement-activities
