### ISSUE TITLE
Understand the state of the UB04/CMS-1450 claims project

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#1045]
https://community.open-emr.org/t/proposed-ub04-cms-1450-claims/8747

**Comment by stephenwaite** [comment]
helping @sjpadgett will be testing the x12 837**I** after completing 837**P**

**Comment by sjpadgett** [comment]
Committed
https://github.com/openemr/openemr/commit/e387e222fd9bca41ce27c4b93f3d0e4418e751cf
