### ISSUE TITLE
Put together some funds for the Affordable Medical Devices Connectivity project

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#1046]
https://community.open-emr.org/t/affordable-medical-devices-connectivity/8865

In order to work on this project, volunteers will need RaspPis and USB devices. Need to put identify which parts need to be purchased for testing and integration. Maybe OEMR and community members can help with putting together some funds for this. My estimate is that we'll need ~$200-500 for purchases/shipping.

**Comment by MatthewVita** [comment]
(I'm going to invite Joyce to our Github. She has offered to help with project management work, so I'll assign her to this if she is able to work on it!)

**Comment by bradymiller** [comment]
This falls within OEMR's priorities, so OEMR can cover this(can formally discuss it at the next board meeting). -brady

**Comment by MatthewVita** [comment]
Wonderful :)
