### ISSUE TITLE
Remove perl dependencies from ubuntu packages, demos, and installation guides

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1065]
Remove perl dependencies from ubuntu packages, demos, and installation guides

**Comment by sunsetsystems** [comment]
Seems like a good idea. As best I know the perl utilities are not used any more.

**Comment by bradymiller** [comment]
done. when the newer docker demo farm reset tonight, they'll be using images without the perl dependencies, so should get good testing.
