### ISSUE TITLE
Multiple Improvements for Layout Based Forms

### ISSUE THREAD

**Issue by sunsetsystems** [openemr/openemr#1067]
Here's a heads-up that I'll be submitting this as a PR very soon. We're still testing and debugging right now.

https://github.com/sunsetsystems/openemr/commits/lbf

A high level summary of the new features:

o Layout groups may be nested, i.e. each group can have sub-groups.
o Layouts and their groups have properties that may be edited in the layout editor. This applies to all layouts and deprecates the "Layout Based Visit Forms" list.
o Encounter LBFs may specify sections for direct entry of services, products and diagnoses.
o "Case Management" feature including the ability to link encounter forms to issues,
  and in the issue window a tab for each related encounter form.
o New layout edit option to specify initially-open groups.
o Implemented design-time ACO for LBF encounter forms.
o Improved printing of encounter LBFs.
o Feature to print a demographics profile with data filled in for a specified patient.
o Improvements to printed referrals.
o Provider attribute and selector for LBF encounter forms.
o New layout option for a single checkbox.
o Support for demographics/history values in LBF static text fields.
o Auto-delete of shared_attributes not used by any other form when a form is deleted.
o Assorted layout editor improvements.
o Added "Save and Continue" button to LBF visit forms.
o Added sorting to export of lists and layouts.
o Condition tests in LBF fields now support setting a value instead of just skipping the field.
o Added field condition support to demographics and history.
o Assorted bug fixes.

I also have a version of this commit for the rel-500 release because that's what the client is currently using. It could also be submitted if desired.

**Comment by bradymiller** [comment]
extensive and nice! looking forward to the PR.

**Comment by sunsetsystems** [comment]
PR created. Prior to that there were some fixes and rebasing to one commit.

**Comment by bradymiller** [comment]
This is now in codebase, so closing.
