### ISSUE TITLE
Want to contribute, website down?

### ISSUE THREAD

**Issue by irco** [openemr/openemr#1097]
Hi! 
I am a developer I'd love to contribute to this effort but the website is down http://www.open-emr.org/  so I cant even read how to start contributing or look at the documenttion.

looking forward to contribute!

**Comment by bradymiller** [comment]
hi @irco,

Weclome to the project!

The OpenEMR website and wiki are served from sourceforge which has been down for several hours. Can follow their status on their twitter page(usually when this happens, it is only several hours; but we do have a plan in place to temporarily serve the website somewhere else if this is a prolonged issue): 
https://twitter.com/sfnet_ops

Note the forum is still going here:
https://community.open-emr.org/

And the chat is still going here:
https://chat.open-emr.org/channel/general

-brady

**Comment by irco** [comment]
Thank you Brady, I appreciate the info.

**Comment by MatthewVita** [comment]
Hi @irco, please check out http://www.open-emr.org/wiki/index.php/Roadmaps#OpenEMR_Project_Roadmap :)

Welcome!
