### ISSUE TITLE
Layout Based Forms 'Save' and 'Save and Continue' confusing

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1100]
hi @sunsetsystems ,

Seeing odd behavior here. If click 'Save', then it Saves and closes (the standard old way it used to happen).
The behavior of the 'Save and Continue' is really odd. If I click this then the form information is basically cleared and behind the scenes it appears all the information is then saved to a separate form. This is basically 'Save and Start a New Form'. Is this the behavior you are meaning to get? Or were you just giving the option of Saving and continuing to work on the note (this is a very good option btw, since we like to Save note numerous times while charting to avoid losing work if computer craps out etc).

thanks, -brady

**Comment by sunsetsystems** [comment]
Hi Brady, it's supposed to do the same thing as Save but leave the form open. I'll look into it and see what's up. Thanks for testing and reporting this.

**Comment by sunsetsystems** [comment]
I have pushed a fix for this. It seems to be a case of cherry-pick gone awry.

**Comment by bradymiller** [comment]
thanks for the quick fix!
-brady
