### ISSUE TITLE
insufficient data sent appears in log after successful login

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#1101]
think there's something funny going on after pulling up the login page

core.css has `@import themebuilder.php` which requires globals.php which is somehow getting around this https://github.com/openemr/openemr/blob/master/interface/globals.php#L550-L563

**Comment by bradymiller** [comment]
Is this still an issue?

**Comment by stephenwaite** [comment]
i'll check it out, thanks for the reminder

**Comment by stephenwaite** [comment]
yeah, still there 🤒 , saw this on eleven.openemr.io

`2018-03-29 23:09 | login | login |   |   |   |   | 0 | insufficient data sent`

**Comment by stephenwaite** [comment]
after a successful login

`2018-03-29 23:09 | other-insert | other |   |   |   | 0 | 1 | INSERT INTO product_registration (registration_id, email, opt_out) VALUES (?, ?, ?) ('null','','1')
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by stephenwaite** [comment]
`2018-03-29 23:09 | login | login | admin |   | Default |   | 1 | success: 172.18.0.16
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by stephenwaite** [comment]
so maybe there should be a coreLogin.css?

**Comment by stephenwaite** [comment]
was kind of asking seriously but realize it's a pretty juvenile question

**Comment by bradymiller** [comment]
I think I fixed this issue here (also buttoned up the auth stuff a bit more):
https://github.com/openemr/openemr/pull/2796/files
(the script is being called from the login where user is not yet logged in, so it was failing the auth code)

**Comment by stephenwaite** [comment]
wow, an `$ignoreAuth = true;` was all it took :)

**Comment by bradymiller** [comment]
yep, but doing that always makes me nervous since it opens the script up to be used without auth. that script is benign though, so won't be an issue (I still in my paranoia added some more validation stuff to it, though :) ).

**Comment by bradymiller** [comment]
https://github.com/openemr/openemr/pull/2796
