### ISSUE TITLE
Adding calendar categories

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1105]
This function is broken in master branch (unable to add calendar categories). See here for more details:
https://community.open-emr.org/t/adding-calendar-categories/9076

bug reported by @juggernautsei

**Comment by bradymiller** [comment]
Main bug has been fixed and is in the codebase. Here's the commit with this issue along with several more potential issues:
https://github.com/openemr/openemr/commit/cefeee03632fef9f5a601cc610954a94ba81eddd

@matrix-amiel , check out my comments in above commit

thanks, -brady

**Comment by juggernautsei** [comment]
thanks for such swift actions!
