### ISSUE TITLE
SQL UPGRADE FAILS

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#1107]
When I try to upgrade the database..I see this error on the upgrade screen - 
Query Error

ERROR: query failed: INSERT INTO `layout_options` (`form_id`,`field_id`,`group_name`,`title`,`seq`,`data_type`,`uor`,`fld_length`, `max_length`,`list_id`,`titlecols`,`datacols`,`default_value`,`edit_options`,`description`,`fld_rows`) VALUES ('LBTptreq','body','1','Details',10,3,2,30,0,'',1,3,'','','Content',5)

Error: Unknown column 'group_name' in 'field list'

C:\xampp\htdocs\openemr\library\sql_upgrade_fx.php at 892:sqlStatement
C:\xampp\htdocs\openemr\sql_upgrade.php at 91:upgradeFromSqlFile(4_2_0-to-4_2_1_upgrade.sql)

**Comment by sunsetsystems** [comment]
Hi Arnab, what versions are you upgrading from and to?

**Comment by arnabnaha** [comment]
Hi Rod, actually I am using the 5.0.1 dev version. I downloaded the recent dev tip and tried upgrading my database from 4.2.0 (though I am using 5.0.1) and this error message showed up. I have done these before but such kind of error message was not shown before

**Comment by sunsetsystems** [comment]
Yeah OK, telling it you are upgrading from 4.2.0 when you are really on 5.0.1 will do that. In 5.0.1 the group_name column is removed from the layout_options table.

**Comment by arnabnaha** [comment]
thanks Rod. So its not a issue..It was my fault going back to 4.2.0. Did the upgrade puling it from 5.0.0 and all worked fine

**Comment by arnabnaha** [comment]
I guess this issue can be closed...
