### ISSUE TITLE
Roadmap Project Work (Matthew)

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#1111]
This is a issue to account for the work for organizing and defining the roadmap projects into github projects with detailed issues. Joyce and Matthew are splitting the work in half. This is the half that will be taken care of in this issue:

• Affordable Medical Devices Connectivity
• Units Support
• Team Tasks Management
• Advanced Billing
• Fast Healthcare Interoperability Resources (FHIR) Integration
• Modern Cloud Solutions
• Quality Reporting
• Realistic Test Data Generation

```
Joyce and I agreed the following is the best workflow:

1. When visiting http://www.open-emr.org/wiki/index.php/Roadmaps#OpenEMR_Project_Roadmap, each link should go to the Github Project
2. The Github Project is named after the roadmap project and has fully detailed issues for anyone to work on
3. On the Github project, there is a link to the Forum post which is for brainstorming and updates (make sure to relevant people are subscribed to the thread to get updates)

Notes:
- It would be useful to announce the projects as they are ready for volunteers and specify exactly how the work will be tracked (this will include a sentence about how each issue will define the requirements)
```

**Comment by danehrlich1** [comment]
@MatthewVita please provide update

**Comment by MatthewVita** [comment]
@danehrlich1 So much has happened/changed since Oct 4 2017. I'm still getting caught up with what I've missed over the past many months. I've written roadmaps in the past and while some of the projects take off, others do not. It's usually based around interest.

At this point, I'm still getting caught up and am waiting for Robert's report so that we can position ourselves to continue with your and his efforts on the wiki.

Please don't read this as we don't need a roadmap.
