### ISSUE TITLE
Support couchdb connection encryption

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1114]
Need to research this.

**Comment by bradymiller** [comment]
See this related issue:
https://github.com/openemr/openemr/issues/1113

**Comment by bradymiller** [comment]
some helpful info:
https://github.com/dready92/PHP-on-Couch/issues/56

**Comment by bradymiller** [comment]
Am now actively working on this.

**Comment by bradymiller** [comment]
@jesdynf ,
As is obvious, never got to around to completing this. I noted that there were discussions that we may not need this (ie. aws supporting encryption over line). Just confirming this (would then make this very low priority).
thanks,
-brady

**Comment by jesdynf** [comment]
Well, yes and no.

1) Although EFS is now technically compliant, it isn't legally compliant -- Amazon hasn't made EFS a HIPAA-eligible service (one for which they will sign a BAA), and they're so closed-mouthed about their roadmap we'll never know when or if that'll change. Sure, it /should/, but...
2) Even assuming Amazon changes their tune tomorrow, this is still critical for anybody who wants to use a document store domestically.

**Comment by bradymiller** [comment]
thanks for the info. will prioritize this (hopefully get it done after the 5.0.1 release).

**Comment by bradymiller** [comment]
Ongoing work on this is in this PR:
https://github.com/openemr/openemr/pull/1655
( @jesdynf ; the code in this PR is still not working yet, but I think I am getting close :) )

**Comment by danehrlich1** [comment]
Help wanted. Feel free to drop a comment so @bradymiller can give you more context if needed. Not the easiest issue, but maybe intermediate let's say.

**Comment by jesdynf** [comment]
It's relevant for HIPAA too, if we have a tag for that.

-- 
Asher Densmore-Lynn <jesdynf@gmail.com>

**Comment by mdsupport** [comment]
@bradymiller 
For emr where tracking changes is crucial, couchdb is _the_ perfect datastore.  Specially with their docker, it deserves to be a standard requirement for this project.  If connectivity is holding up its wider use throughout the application, here are some steps -

```
cd /opt/couchdb/etc/local.d
openssl genrsa > couchdb_key.pem
openssl req -new -x509 -key couchdb_key.pem -out couchdb_cert.pem -days 1095
```
Enter information that will be incorporated into certificate request.
```
chmod 600 couchdb_key.pem couchdb_cert.pem
chown couchdb:couchdb couchdb_key.pem couchdb_cert.pem
gedit ../local.ini
```
Add/edit following 4 lines
```
[ssl]
enable = true
cert_file = /opt/couchdb/etc/local.d/couchdb_cert.pem
key_file = /opt/couchdb/etc/local.d/couchdb_key.pem
```
Trust self signed certificate locally to eliminate authentication errors.  For ubuntu
```
sudo cp ./couchdb_cert.pem /usr/local/share/ca-certificates/couchdb.crt
sudo update-ca-certificates
```
Look for "1 added" in response.  If ok, test as 
```
curl https://localhost:6984/`
```
