### ISSUE TITLE
patient find by relocating to new/search

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#1117]

**Comment by bradymiller** [comment]
Is this broken or missing?

**Comment by sunsetsystems** [comment]
Stephen can you be more specific? What action is broken?

**Comment by stephenwaite** [comment]
think it's broken because it was never converted to tabs?

**Comment by stephenwaite** [comment]
hi @bradymiller , saw your post on the forum, you're right it's missing too :) 

so i followed your advice and you can see how i'm trying to add it on this pr https://github.com/openemr/openemr/pull/1118

**Comment by stephenwaite** [comment]
that sounds great, thanks, going to close this issue and abandon my fix because it's not testing well

**Comment by stephenwaite** [comment]
the forum user tried the dynamic finder but replied that the Find by Any is much more handy so i'll try to follow your advice and a search field by the search button

**Comment by sjpadgett** [comment]
Yep, this one just won't go away:) This is how i'm doing it. With patient:
![image](https://user-images.githubusercontent.com/1859985/57182766-243f5180-6e71-11e9-8982-c810c76f846b.png)

And without:
![image](https://user-images.githubusercontent.com/1859985/57182748-df1b1f80-6e70-11e9-9982-98a840b96062.png)
Logic is if search box is populated then will be a Any search else opens normal finder on icon click. Any search will bring up normal finder except populated with the any search. /n will also start search.

Now'd be a good time if there are any objections!

**Comment by sjpadgett** [comment]
Here's my solution: https://github.com/openemr/openemr/pull/2413
@stephenwaite FYI
