### ISSUE TITLE
Select All in Billing Manager broken on dev tip

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#1133]
hi @sjpadgett , helping @bradymiller with php7.1 warnings/errors at http://www.open-emr.org/wiki/index.php/Development_Demo#Alternate_Demo_.28Ubuntu_17.10_-_uses_php_7.1.29

and found the aforementioned, it selects the claims for a second and then they're cleared

also verified the bug at https://one.openemr.io/a/openemr/index.php

**Comment by sjpadgett** [comment]
Okay, will look.

**Comment by sjpadgett** [comment]
@stephenwaite Okay I don't know if I changed select all to a button or another but it is submitting the form on select(buttons inside a form will auto submit regardless if type=submit where an input type button won't). So do you want me to submit a fix now or wait for your adventure into billing to conclude?

**Comment by sjpadgett** [comment]
see PR https://github.com/openemr/openemr/pull/1134

**Comment by stephenwaite** [comment]
now it works! nicely done @sjpadgett , thanks for the explanation and thanks for bringing it in @bradymiller
