### ISSUE TITLE
GIT Issue - Cant update my openemr

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#1141]
Hi..
I will be really thankful if this anybody can help me solve this issue. Whenever I am trying to push changes to my local and remote origin directory..it shows me bad file number 22 error. I have attached the pic below. Kindly see. I am on windows 10.
![git error](https://user-images.githubusercontent.com/1074948/31834479-b75b0134-b5eb-11e7-8a8c-f41400f70b51.png)

**Comment by bradymiller** [comment]
what does your section for upstream repo look like in your .git/config file ?

**Comment by arnabnaha** [comment]
Hi Brady
In my .gitconfig file, I can only find my name and email

**Comment by arnabnaha** [comment]
sorry brady my Bad...I looked at the wrong file

here what it looks like - 

[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
	hideDotFiles = dotGitOnly
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
	url = git@github.com:arnabnaha/openemr.git
[branch "master"]
	remote = origin
	merge = refs/heads/master
[remote "upstream"]
	url = git://github.com/openemr/openemr.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
[branch "my_emr"]
	remote = origin
	merge = refs/heads/my_emr
[branch "openemrtest"]
	remote = origin
	merge = refs/heads/openemrtest
[gui]
	wmstate = zoomed
	geometry = 1348x685+5+0 171 192
[branch "prescription_mod"]
	remote = origin
	merge = refs/heads/prescription_mod

**Comment by bradymiller** [comment]
@arnabnaha ,
Try this:
git remote set-url origin https://github.com/arnabnaha/openemr.git

**Comment by bradymiller** [comment]
if doesn't work, then can revert it back by:
git remote set-url origin git@github.com:arnabnaha/openemr.git

**Comment by arnabnaha** [comment]
Thanks Brady
The https worked. All set. I am closing this issue.
