### ISSUE TITLE
Thoughts on Tabs?

### ISSUE THREAD

**Issue by sunsetsystems** [openemr/openemr#1142]
We have what I presume is some home-grown tabs code with the tabbify() function in library/js/common.js. It's not very capable, for example doesn't support dynamic adding and removing of tabs.

The Tabs layout is based on Knockout JS, not my cup of tea.

I noticed the [jQuery UI Tabs widget](https://jqueryui.com/tabs/). That looks pretty good. Anyone have experience with it? Other ideas?

My immediate interest here is turning the encounter frame into a tabbed area with each form that you open in its own tab.

**Comment by bradymiller** [comment]
Would be nice to stick with bootstrap, if possible. Thoughts @robertdown ?

**Comment by sunsetsystems** [comment]
Not seeing examples of dynamic add/removal of tabs with bootstrap. Perhaps there's a widget somewhere for that. Another nice feature of jQuery UI is you can drag the tabs to re-order them. Mainly looking for a polished component to avoid re-inventing wheels.

I'm good with adding a 3rd solution for tabs if there is some consensus that is the preferred one, so eventually we'd migrate to it.

**Comment by MatthewVita** [comment]
Don't believe I have see anything as interactive in Bootstrap, though I am not familiar with the latest version. jQuery UI supports this but it's not as stylish :)

**Comment by matrix-amiel** [comment]
I didn't work with this but maybe it can help.. style of Bootstrap for Jquery UI.
http://jquery-ui-bootstrap.github.io/jquery-ui-bootstrap/index.html

**Comment by MatthewVita** [comment]
Ah, looks like it's not actively maintained :(

**Comment by sunsetsystems** [comment]
Might put it in a wrapper if the choices are all flawed. Making it easier to replace later.

**Comment by bradymiller** [comment]
Sounds like a good plan.

**Comment by mdsupport** [comment]
@sunsetsystems You can use [this](http://www.jqueryscript.net/demo/jQuery-Plugin-For-Dynamic-Bootstrap-Tabs-Component/) as a reference if _draggable_ is important.  Otherwise try [this](http://jsfiddle.net/happysmiles/F33Av/22/) fiddle.

For encounters have you explored collapsible sidebar that could retain continuous layout that is easy to read yet with ability to jump to a specific section?

**Comment by sunsetsystems** [comment]
Thanks @mdsupport . I was hoping for a component that's actively maintained. Continuous layout is interesting but I think users will do better with clear separation between forms.

**Comment by sunsetsystems** [comment]
Wrapper class is in progress. It has some interesting aspects. Initially doing this with the client's older version of openemr, and will port it to current code when stable.

**Comment by bradymiller** [comment]
Looking forward to seeing the code. -brady

**Comment by robertdown** [comment]
Bootstrap handles the styling of various components. If we wanted to use if for the tab interface we'd have to do some heavy lifting (But this will be true no matter the framework).

Kevin wrote the tabs in KnockoutJS but it's not very pretty and think we should move to AngularJS for our frontend stuff. I know @MatthewVita will say use React, but Angular is a framework, which is more comprehensive - React is just a library. Our codebase needs a LOT, Angular can take care of that.

If we're talking about tabs inside of a page (i.e. _not_ the main tab interface) use Bootstrap. You should be able to dynamically add and remove tabs, just have to write some javascript.

Tabbify is slowly dying in our infrastructure and being replaced with bootstrap tabs. We should stick to Bootstrap as often as possible.

**Comment by sunsetsystems** [comment]
I've already made and tested the wrapper class for jQuery UI Tabs. So we'll have a lot of flexibility. Am partial to modules over frameworks for that reason.

**Comment by robertdown** [comment]
So we now have 2 types of tabs? Bootstrap and jQuery UI?

**Comment by sunsetsystems** [comment]
Three, as previously noted (I think you mean Knockout rather than Bootstrap?). My work is a vote for one, with the wrapper approach allowing moving forward without having to commit yet. I'll put up a PR after we've done a bit more testing and I can take a break to port it to current dev code.

For what it's worth, having some experience with jQuery UI Tabs now, I'm not very impressed with it either. But when something better is settled on it should just be a matter of changing one script.

**Comment by sunsetsystems** [comment]
I have created PR  #1263 which includes a TabsWrapper class. It would be great if anyone wants to improve it later.

**Comment by bradymiller** [comment]
This code has been delivered to codebase, so closing this issue.
