### ISSUE TITLE
Eye Form - javascript error

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1161]
tested in following demo:
http://www.open-emr.org/wiki/index.php/Development_Demo#Alternate_Demo_.28Alpine_3.5.29

Getting a javascript error when open the Eye Form. I think this is my fault since I incremented 1 of the jquery versions in this form (from following https://github.com/openemr/openemr/issues/842 : "it appears the eye module may have bug from the jquery-min-1-11-1 to jquery-min-1-11-3 migration.").

**Comment by sjpadgett** [comment]
@bradymiller The bigger issue here is that it broke completely in PHP7.1. Want to leave for author or want me to take a whack?

**Comment by bradymiller** [comment]
Confirmed above fix.
Fixed by @sjpadgett

**Comment by bradymiller** [comment]
@ophthal ,
Just letting you know of the following fix on your eye form by @sjpadgett :
https://github.com/openemr/openemr/pull/1215
(fixes both a jquery issue and also a php7.1 errors)
