### ISSUE TITLE
Bad Bug at patient-encounter->Administrative->New Encounter Form

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1184]
Tested on following demo: http://www.open-emr.org/wiki/index.php/Development_Demo#Alternate_Demo_.28Alpine_3.6_-_uses_php_7.1.29

If go to 'patient-encounter->Administrative->New Encounter Form', it breaks openemr (the entire window gets overrided by the new encounter form).

**Comment by sunsetsystems** [comment]
I think this would be fixed by changing line 372 of interface/patient_file/encounter/forms.php from:

`parent.location.href = sel;`

to:

`location.href = sel;`

... sorry can't test this right now.

**Comment by bradymiller** [comment]
Thanks @sunsetsystems for pointing me to the right spot. Fix is here and is working well:
https://github.com/openemr/openemr/pull/1187

**Comment by bradymiller** [comment]
Brought fix into codebase. whoohooo, just 50 or so more issues to go until release version 5.0.1!! :)
