### ISSUE TITLE
Patient Portal (Medication List) Issue

### ISSUE THREAD

**Issue by eshiet** [openemr/openemr#1188]
If one logs into the demo patient portal at https://demo.openemr.io/openemr/patients 
In the Medication List section one would see that there is no start date and end date with referrer recorded.

![screenshot from 2017-11-01 07 07 34](https://user-images.githubusercontent.com/13769435/32262182-851cabb4-bed3-11e7-83da-d494486eed3e.png)

**Comment by stephenwaite** [comment]
hi @eshiet , was able to see the other fields display data after entering it

maybe if the person logs out and then back in the new data will show?

**Comment by bradymiller** [comment]
This is regarding the old patient portal, which was recently removed. So closing this issue.
