### ISSUE TITLE
Eye Form - Print as PDF not working

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1233]
In Eye form, when do File->Print as PDF, it is not working. Nothing happens and get following error in the php error log:
``````
[17-Nov-2017 08:49:06 UTC] PHP Fatal error:  Uncaught <span style="color: #AA0000; font-weight: bold;">
ERROR nÂ°4</span><br>
File : /var/www/html/a/openemr/library/html2pdf/_class/parsingHtml.class.php<br>
Line : 118<br>
<br>
HTML code invalid, the tags are not closed in an orderly fashion.<br>Status : <pre>Array
(
    [0] => page
    [1] => div
    [2] => table
    [3] => tr
    [4] => td
)
</pre>
<br><br>HTML : ...Round and Reactive&lt;br /&gt;      &lt;/tr&gt;
    &lt;/table&gt;
        &lt;br /&gt;...
  thrown in /var/www/html/a/openemr/library/html2pdf/_class/parsingHtml.class.php on line 118
``````

**Comment by sjpadgett** [comment]
If okay with author, I'll fix this and maybe convert pdf to mPDF.

**Comment by bradymiller** [comment]
I am pretty sure Ray ( @ophthal ) would be happy to get the help on this.

**Comment by ophthal** [comment]
https://github.com/ophthal/openEMR_2/commit/d3ad26d64a0fdb69cfc8b4bbf9ec761f052822d6

There is a fix in the last commit in my repo Reminders_6.27.17-rebase-4 which is running at https://two.openemr.io/openemr/.   Two small tweaks.  Will test it to be sure when the demo recycles tomorrow.

**Comment by ophthal** [comment]
@sjpadgett feel free to convert it to mPDF if that makes a difference to the project.  Consistency is a good thing.

**Comment by sjpadgett** [comment]
@ophthal Still an issue at L826
`<?php
                    if (($PUPIL_NORMAL =='1')&&(!$ODPUPILSIZE1||!$OSPUPILSIZE1)) { ?>
                      <b class="underline"><?php echo xlt('Pupils'); ?></b>&nbsp;&nbsp;
<b class="underline"><?php echo xlt('Pupils'); ?></b>&nbsp;&nbsp;
                        <?php echo xlt('Round and Reactive')."<br />";
                    }`
I have this fixed and tested. Do you want to get off my git or can I do a PR?

**Comment by ophthal** [comment]
Jerry, I am nearly as old as you are...  Whatever has the fewest steps and is the easiest for Brady works for me.  I assume Brady would like the PR...  Thanks Jerry.

**Comment by sjpadgett** [comment]
Sooo, age before beauty, you say! Will put up PR with a few style issues I've spotted. Also, mPDF will spit out the pdf enforcing the inline and stylesheet css where HTML2PDF tends to miss more styles such as inline font sizes so, the pdf will look different than current.

**Comment by bradymiller** [comment]
fixed by @sjpadgett

**Comment by bradymiller** [comment]
@ophthal ,
Fix is here: https://github.com/openemr/openemr/pull/1238
(note the font size issues were also fixed and a bug in the category name when saving the note as a pdf)
