### ISSUE TITLE
What is the form_id ??

### ISSUE THREAD

**Issue by A1Gard** [openemr/openemr#1242]
Hi dear developers

I try to understand what is `form_id` in the `forms` table, bot result is noting :-|

`form_id` is a key of this table but I can't found any rule to assign this.

Any one can help me?

**Comment by stephenwaite** [comment]
form_id auto increments from the sequences table and is used to reference the id of a child form like vitals

**Comment by stephenwaite** [comment]
glad that helped, feel free to follow up when it's convenient or close the issue before grimreaper @bradymiller comes calling :)

**Comment by bradymiller** [comment]
:)

![kvbg5_s-200x150](https://user-images.githubusercontent.com/278968/33104135-6f1bb946-cedb-11e7-828e-aaa5234861b6.gif)
