### ISSUE TITLE
Database upgrade error

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#1266]
Hi...
I was upgarding my databases (have multisite)...and I found this error - 

Query Error

ERROR: query failed: UPDATE `layout_options` SET group_name='8Guardian',title='Name',seq='10' WHERE form_id='DEM' AND field_id='guardiansname' AND group_name LIKE '%Contact'

Error: Unknown column 'group_name' in 'where clause'

C:\xampp\htdocs\openemr\library\sql_upgrade_fx.php at 892:sqlStatement
C:\xampp\htdocs\openemr\sql_upgrade.php at 91:upgradeFromSqlFile(4_2_2-to-5_0_0_upgrade.sql)

Please fix this!
Thanks and regards
Arnab

**Comment by bradymiller** [comment]
hi @arnabnaha ,
Hasn't something like this come up before if try to run upgrade from version 4.2.0 when the instance is already on 5.0.1-dev?
-brady

**Comment by bradymiller** [comment]
To clarify, what OpenEMR version are you upgrading from?
And what version did you select to upgrade from on the sql upgrade script?

**Comment by arnabnaha** [comment]
Hi Brady..
true...it came up earlier too. I tried upgrading from 4.2.0 though I am on 5.0.1 -dev. Once I did it from 5.0.0, everything was fine and working well.

**Comment by mdsupport** [comment]
Just created #1268 before coming across this.  This is related to missing group_name conversion process that breaks code in various places.  On first glance this is critical.

**Comment by mdsupport** [comment]
@arnabnaha, as pointed out in #1268 discussion, critical update steps are skipped if table layout_group_properties exists in your database.  We renamed that table and repeated the upgrade which produced the following : 

> CREATE TABLE `layout_group_properties` ... 
> ALTER TABLE layout_options ADD COLUMN group_id VARCHAR(31) NOT NULL default '' AFTER group_name
> Converting layout properties ...
> ALTER TABLE layout_options DROP COLUMN group_name

If you have any local code that uses group_name, you can retain that column to prevent SQL errors until you fix that code.

**Comment by arnabnaha** [comment]
Hi @mdsupport 
Should I run the SQL statement as stated above directly in my phpmyadmin SQL commands??

**Comment by mdsupport** [comment]
You can run updates from any mySQL client - phpmyadmin or whatever.  Important to notice 

> ... you can add that column to prevent SQL errors. 

This is done by running the following command before update : 

`ALTER TABLE layout_options ADD group_name VARCHAR(255) NOT NULL AFTER group_id;`

Once the original column `group_name` is available in the table, the update statement should be available for pre 5.0.1 statements.

If you plan to repeat this update in future, you can comment out the statement in 5.0.0 to 5.0.1 upgrade script which deletes `group_name` column and save yourself some time.

Take care.
