### ISSUE TITLE
New tabbed encounter not supports RTL

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr#1272]
Hi.
We pulled the latest version of master, The new feature of tabbed encounter not supports RTL languages. 
It also doesn't include a general css file so I can't customize a page (I think it's important regardless a RTL's problem).

@sunsetsystems , @bradymiller 
Could you help us with that? 

Thanks
Amiel

**Comment by sunsetsystems** [comment]
I don't know what changes would have affected RTL. Are we talking about the text in the tab labels? Might help if you explain in some detail what's broken that used to work. Thanks.

**Comment by matrix-amiel** [comment]
Yes. the problem is a side of tabs.
![image](https://user-images.githubusercontent.com/17809866/33672353-b53475f2-dab2-11e7-8e12-b5df44c6ea09.png)
Should be -
![image](https://user-images.githubusercontent.com/17809866/33672418-cf9a0146-dab2-11e7-937c-fee18945aa15.png)
The solution is to put 'float:right' to 'li.ui-tabs-tab' elenemt.
But I don't know how to merge it right in the new code.. 
Thanks

**Comment by bradymiller** [comment]
fixed by @matrix-amiel
