### ISSUE TITLE
Groups ->Participants ->Participant's name : Error when trying to add Participants 

### ISSUE THREAD

**Issue by eyalvo-matrix** [openemr/openemr#1287]
When trying to add a participant to a group dialog.js 
causing an error that preventing to complete the action 

![image](https://user-images.githubusercontent.com/20621444/33982138-14bdc496-e0b8-11e7-991e-14517a5d02f9.png)

**Comment by eyalvo-matrix** [comment]
Added a pull request at 
https://github.com/openemr/openemr/pull/1288

**Comment by bradymiller** [comment]
Is this issue resolved?
(if so, then will close this issue)

**Comment by bradymiller** [comment]
No reply, so assuming this issue is fixed and closing it.
