### ISSUE TITLE
Remote Patient Vitals Module - Patient List View

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#1294]
![openemr remote patient vitals module - patient list view](https://user-images.githubusercontent.com/1715206/34192740-c688b87a-e504-11e7-8e76-6d7beeb7c703.png)

**Comment by pelgay** [comment]
Could you kindly add a patient cid no which is unique nos. for individual and which does not change once they have it. phone number may change.

**Comment by MatthewVita** [comment]
Hi @pelgay, sorry for my delay. I just updated the mockup to have a unique ID column! Good thought.

- Matthew
