### ISSUE TITLE
Remote Patient Vitals Module - Editable Patient Detail View

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#1296]
![openemr remote patient vitals module - editable patient detail view](https://user-images.githubusercontent.com/1715206/34028186-31f75078-e116-11e7-94be-7aaa48b258bb.png)

**Comment by pelgay** [comment]
this view is fantastic as it reveals trend over period.which the patient can review himself or herself , only we need to set a upper and lower goal for the patient i mean the normal limits

**Comment by MatthewVita** [comment]
@pelgay I actually was thinking this would be the physician's view. However, maybe in a v2 of the software we can add a login for the patient so they can observe their graphs?
