### ISSUE TITLE
Remote Patient Vitals Module - Limited EHR View

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#1298]
We need to expose only auth, patients, and this module in the EHR. The Bhutan providers don't want an EHR:

![openemr remote patient vitals module - context 1](https://user-images.githubusercontent.com/1715206/34028247-81d01e72-e116-11e7-8bab-6f688807c85f.png)

**Comment by pelgay** [comment]
i think we start with just blood pressure and may be weight gain and blood sugar levels

**Comment by MatthewVita** [comment]
@pelgay I believe that is the best path forward! :)
