### ISSUE TITLE
Fee Sheet Saving Issue

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#1299]
Hi..
I am on openemr 5.0.1 with windows 10. while working, I found that the fee sheet is not saving and throwing errors after save button is clicked. Although, by clicking the "SAVE CURRENT" button, I could save it and do off my work. 

I have attached a pic below showing the error. It only occurs when I click the SAVE button. I have cleared the cache and cookies but it still shows.
I tried  it on chrome - it doesnot save the feesheet but doesnot throw any errors in the screen (but does nothing) and on firefox - it shows "CORRUPTED CONTENT ERROR"

PHP ERROR LOG - 
[Fri Dec 15 19:08:59.825020 2017] [:error] [pid 6716:tid 1996] [client 117.194.219.11:53009] PHP Deprecated:  Function split() is deprecated in C:\\xampp\\htdocs\\openemr\\interface\\forms\\history\\report.php on line 209, referer: http://nahahealthclinic.no-ip.org/openemr/interface/patient_file/encounter/encounter_top.php

![corrupted_content_feesheet](https://user-images.githubusercontent.com/1074948/34044651-d2aee976-e1cb-11e7-830e-3902b034a6b8.png)

Thanks and regards
Arnab

**Comment by sunsetsystems** [comment]
I'll look into this. Thanks for the report.

**Comment by sunsetsystems** [comment]
This is fixed:
https://github.com/openemr/openemr/commit/cdec7c4fb1a0eb18e6c9f29edb4bf7e8b4210a59
