### ISSUE TITLE
facility taxonomy

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#1301]
from the forum, will need to add field to facility table and support in the x12, hcfa, ub04 scripts

also need to spruce up and enlarge the facility dialog

**Comment by sjpadgett** [comment]
where is it called?

**Comment by stephenwaite** [comment]
hi, interface/usergroup/facility_admin.php

**Comment by stephenwaite** [comment]
user discovered that the rendering provider taxo was getting pulled from line 150 in library/gen_x12_837.inc.php

**Comment by stephenwaite** [comment]
https://github.com/openemr/openemr/pull/1310
