### ISSUE TITLE
load_fda_drugs.plx not working

### ISSUE THREAD

**Issue by HITECHPR** [openemr/openemr#1309]
Downloaded current EOB Zip file
ran ./load_fda_drug.plx < Products.txt as per instructions.
This is the error displayed on screen.
DBD::mysql::db do failed: Incorrect date value: '0000-00-00' for column 'last_notify' at row 1 at ./load_fda_drugs.plx line 80, <STDIN> line 1.
INSERT INTO drugs( name ) VALUES ( 'Trade_Name' ) at ./load_fda_drugs.plx line 80, <STDIN> line 1.

**Comment by sunsetsystems** [comment]
Oh I see. This utility should really be ported into the Native Data Loads page. There might be other problems, but for this one try adding the following line in the "Startup" section of the script:

`    $dbh->do("SET sql_mode = ''");`
