### ISSUE TITLE
add_edit_event.php dialog Jquery 

### ISSUE THREAD

**Issue by scorpions786** [openemr/openemr#1325]
the old version of the dialog on can support new library of jquery
(jquery-min-3-1-1)
in 
interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html
(jquery-min-1-7-2) now

but the new update cannot support (jquery-min-3-1-1)

**Comment by sjpadgett** [comment]
I don't understand. What is the issue? New dialog will dynamically replace v1-7-2 with v1-9-1 so dialog can run. This is until can go through calendar to update jquery for compatibility. I haven't seen any issues as yet with all the testing we have done. Are you just pointing out v1-7-2 is incompatible with bootstrap? Note: you should see a message in console if jquery is replaced on dialog run.

**Comment by scorpions786** [comment]
my point is when you have new feature(js library) that doesn't work with the old version of the JQuery
so you can't add them when the dialog or the click on calendar to add event will not work

**Comment by scorpions786** [comment]
while the older version of the system you can update the librarry of jquery without any issue

**Comment by bradymiller** [comment]
Is this still an issue?
