### ISSUE TITLE
Cancel button donot work in payment

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#1340]
Hi..
The "cancel" button in Fees->Payment donot seem to work. Clicking it, doesnt cancel anything. Simply nothing happens. i guess, the payment form should close on clicking it..but it doesnot happen. I am getting this in the php error log - 

[Fri Dec 29 17:40:06.313875 2017] [:error] [pid 6044:tid 2012] [client 117.194.216.152:52176] PHP Warning:  Invalid argument supplied for foreach() in C:\\xampp\\htdocs\\openemr\\interface\\patient_file\\reminder\\active_reminder_popup.php on line 65, referer: http://nahahealthclinic.no-ip.org/openemr/interface/patient_file/summary/demographics.php?set_pid=2

(might not be related to this)

Thanks
Arnab

**Comment by stephenwaite** [comment]
https://github.com/openemr/openemr/blob/master/interface/patient_file/front_payment.php#L1249

could this be window.close?

**Comment by arnabnaha** [comment]
@sjpadgett  Please take a look here.

**Comment by sjpadgett** [comment]
@stephenwaite This script doesn't include opener because, in this case, is called from menu. However the same script is called elsewhere as a popup so I need to add logic to handle where i'm at so to speak. When in a tab there really is not a window to close and would have to close the tab. Also, window.close is already defined as a global thus we are just reassigning (or monkey'ed) existing function.

**Comment by stephenwaite** [comment]
oh, thank you and thanks to your many contributions as of late

**Comment by sjpadgett** [comment]
You're welcome and thanks. Do you remember if originally front payment was a popup that got turn into a tab? Seems to me it was..

**Comment by arnabnaha** [comment]
Yes @sjpadgett  it was a popup initially which was later turned into tab and put under fees menu

**Comment by stephenwaite** [comment]
yes, sounds familiar

**Comment by sjpadgett** [comment]
So we need to close the tab or frame or go to the encounter or anything other than nothing because there is nothing to really close for a window. Suggestions!

**Comment by stephenwaite** [comment]
sure, close the tab and return to main pt screen with billing expanded ;)

**Comment by sjpadgett** [comment]
lol, just had to ask, didn't I......................

**Comment by stephenwaite** [comment]
yeah, never ending ui/workflow improveemnts to billing in openEMR

**Comment by sjpadgett** [comment]
Okay, I get the jest and will come up with something. Thanks

**Comment by sjpadgett** [comment]
Here is how I want to handle if agree.
If tab, then will close tab and focus demographics tab.
If frames, will return to previous frame before calling payment.
In both cases will turn receipt into a dialog.

**Comment by sjpadgett** [comment]
Question? Do we always want to force a print receipt or have option to save payment or save and print?

**Comment by arnabnaha** [comment]
After creating a fee sheet, we can go to payments and bill the patient by generating an invoice through the payment screen. Payment screen is mainly for cash/self pay patients (non-insurance) but insurance patients can also pay. After clicking generate invoice, it shows a dialogue box asking to save. If saved it shows the option to print.

**Comment by sjpadgett** [comment]
Thanks, I misspoke, I meant force to receipt screen. No matter, the dialog will take care of those decisions.

**Comment by arnabnaha** [comment]
it always forces the receipt screen after saving and then gives an option to print.

**Comment by sjpadgett** [comment]
Here is PR for this issue with some additions.
https://github.com/openemr/openemr/pull/1343

**Comment by arnabnaha** [comment]
Thanks @sjpadgett. its working fine, but I have reported a new issue for the receipt (after generating it) #1345
