### ISSUE TITLE
Payment receipt on printing showing wrong info

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#1345]
Hi..
I applied the latest dev-tip from codebase to my server and now the cancel button in payment is working fine. Thanks to @sjpadgett for the fix. New issue which creeped up was after generating invoice, it was shoing the invoice to be printed, but the info was either wrong in the receipt or was missing from it. I have attached an image below to illustrate that - 

![receipt_issue](https://user-images.githubusercontent.com/1074948/34468154-edd9580c-ef28-11e7-87c8-b853a6857689.jpg)

N.B. Even the facility/clinic address is missing from the receipt.
Thanks
Arnab

**Comment by sjpadgett** [comment]
@arnabnaha Working okay for me but one never knows:). Can you give me some details how you get there i.e : is it a new encounter? posting on existing and so on...

**Comment by arnabnaha** [comment]
It was an exixting encounter. Selected a patient first..went to
fees->payment. It displayed the list of payments. I clicked on generate
invoice and showed me that receipt.

**Comment by sjpadgett** [comment]
Okay, front payment is for making a payment and should not allow you to print a receipt if a payment is not made so, this is a bug because, in this case, a blank payment gets posted, a no no for sure. For printing an already posted payment receipt you can use Reports->Front Rec. Thanks for pointing out and i'll address.

**Comment by arnabnaha** [comment]
Thanks Jerry

**Comment by sjpadgett** [comment]
@arnabnaha I'm thinking this PR get's you there... https://github.com/openemr/openemr/pull/1348

**Comment by arnabnaha** [comment]
@sjpadgett Thank you so much Jerry. Its a very good fix. Thank you so much. Much needed.

**Comment by arnabnaha** [comment]
@sjpadgett  I am reopening this because, if I go to Fees->posting, I can post an empty payment through posting. If someone clicks save, it just does that.

**Comment by sjpadgett** [comment]
The good thing about testing is to find bugs. The bad thing about testing is, we find bugs :)

**Comment by arnabnaha** [comment]
:)

**Comment by sjpadgett** [comment]
New PR https://github.com/openemr/openemr/pull/1351

**Comment by arnabnaha** [comment]
Thanks for the PR @sjpadgett . Tested checkout mode of payment and this also allows posting of zero payment. Fees->checkout, if the payment is zero, on clicking save, it saves it.

Regarding the above PR, have tested it and it works absolutely good

**Comment by bradymiller** [comment]
This is fixed, so closing this issue.
