### ISSUE TITLE
Document reference isn't stored in the database when a patient has a very large pid

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#1350]
This bug is minor because it can only really happen from the use of another tool connected to the OpenEMR database (patient demo generator, for example, which has been patched), but basically when a patient `pid` is huge (e.g.: 99999999999), certain `foreign_id` fields in tables that point back to the `patient_data` table can't hold the value. This is the case with the `documents` table.

This would be a good first issue for someone looking to explore the code.

**Comment by kacyw** [comment]
@bradymiller Take a look at this, and let me know if it would cover this issue: https://gist.github.com/kacyw/9f73405f17f6ceef05624b522393c2a6

**Comment by bradymiller** [comment]
hi @kacyw ,

To clarify this issue, this is a database issue. For example, the main pid is stored with bigint(20) field in main patient_data table:
https://github.com/openemr/openemr/blob/master/sql/database.sql#L5811

So, it can hold very large numbers. However other tables that also hold this number may not allow very large numbers. For example the foreign_id column in documents table holds pid and is only a a int(11):
https://github.com/openemr/openemr/blob/master/sql/database.sql#L1211

So solution is that all columns that hold a pid should have at least bigint(20)

-brady

**Comment by bradymiller** [comment]
completed
