### ISSUE TITLE
Adding acl group to user on create/edit user

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr#1352]
Hi.
Currently users that don't have the 'Administration ACL' permission can't add/edit user's acl group. 
This means that if a user has permissions to create users but does not have Administration ACL permission he can only create users without any permissions, which is pretty useless.
We think that the ability to add/edit a user's acl group (in the add/edit users screen - not in the acl screen) should not be part of the 'Administration ACL' permission but rather part of the 'Users/Groups/Logs Administration' permission.

**Comment by bradymiller** [comment]
@matrix-amiel , Agreed :)

**Comment by bradymiller** [comment]
This was fixed in above PR, so closing this issue.
