### ISSUE TITLE
Creating a new patient date format does not refer to global date format

### ISSUE THREAD

**Issue by eyalvo-matrix** [openemr/openemr#1359]
![image](https://user-images.githubusercontent.com/20621444/34648760-0e0b7dc4-f3a9-11e7-945e-da716fef9c3a.png)

![image](https://user-images.githubusercontent.com/20621444/34648766-2a396e8e-f3a9-11e7-9ebc-793333633acc.png)

![image](https://user-images.githubusercontent.com/20621444/34648769-3c2532a4-f3a9-11e7-93ae-1be036b6c0da.png)

**Comment by bradymiller** [comment]
Yep, been doing a slow code walk through to support this in the codebase. Sound like we don't yet support this in the layouts engine yet, then. If your interested, I can point you to examples where I have done this and you can take a stab at supporting this in the layout engines.

**Comment by eyalvo-matrix** [comment]
Sure I will have a swing on it , please share the examples

**Comment by bradymiller** [comment]
@eyalvo-matrix ,
Here's a nice simple example:
https://github.com/openemr/openemr/commit/6288a8f0cb112cd432b7da631023a12338be5e61?w=1

Note:
1. The use of DateToYYYYMMDD() when initially process date to convert it to standard format. This then allows use in the code for things like sql queries etc.
2. Setting of `$datetimepicker_formatInput = true` in datetimepicker which will then have it use the custom format when enter in a date via the picker.
3. Use of the oeFormatShortDate() to convert the standard format to he custom format(for example, when output it or set the date in the datetimepicker).

**Comment by bradymiller** [comment]
This was fixed in codebase, so closing this issue.
