### ISSUE TITLE
Support imaging with multiple images (CT or MRI)

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#1360]
The issue is that the current dicom mechanism only supports 1 image. This is great for xrays. However, it sounds like this will get much more complicated for imaging with multiple images (such as a CT or MRI).

**Comment by ivmartel** [comment]
The dwv application 'loadURLs' method used in the launcher ([dicom_launcher.js#L28](https://github.com/openemr/openemr/blob/c11874506437f56bf66f9bb841220c273b6b2c85/library/js/dwv/dicom_launcher.js#L28)) can handle a list of files as in this [fiddle](https://jsfiddle.net/ivmartel/hmetaz6f/).

In the dwv div ([general_view.html#L342](https://github.com/openemr/openemr/blob/c11874506437f56bf66f9bb841220c273b6b2c85/templates/documents/general_view.html#L342)), can the value of the src attribute be a list of files?

**Comment by MatthewVita** [comment]
Hi @ivmartel,

Yup, we can reference multiple files, though we'll have to tweak some things as currently we don't have a way to map things in a bundle.

**Comment by MatthewVita** [comment]
@bradymiller any thoughts on bundling documents for this purpose? Eventually the files will live in Orthanc so this just needs to work. Maybe we can the user mainly label each file with a group identifier so we can query against that and the upload time?

**Comment by bradymiller** [comment]
@MatthewVita ,
Could bundle it as a zip possibly and then go from there.

**Comment by MatthewVita** [comment]
@bradymiller,

I don't think the zip will work. Basically the DWV api for this is like so:

```
app.loadURLs(["https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/bbmri-53323851.dcm","https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/bbmri-53323707.dcm","https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/bbmri-53323563.dcm"]);
```

This may be the first document-related interaction that requires a grouping schema, unless there has been an example of this in years past?

**Comment by sjpadgett** [comment]
Maybe place in sub folders as a group where left tree would have another master group branch containing the group.

**Comment by kofiav** [comment]
Maybe we could do both zip files and groups? 🤔 

With zip files the grouping is implicit. We just need a way to instruct users to only upload images from separate CT and MRI scans in zip files. 

I like @sjpadgett's of creating sub-folders in the left tree that represent a group. The tricky thing will have to be how to implement this in an intuitive way. The whole notion of a 'group' in the left tree will have to be formalized, and this idea has to be applied consistently in other parts of OpenEMR. Also right now we are uploading DICOM images as general `Lab Reports`. If we go the group route we will have to perhaps mention DICOM files briefly in the description, unless there's a way we can generalize the idea of groups to any kind of `Lab Report`.

**Comment by sjpadgett** [comment]
I've got my Java hat on right now but I'll take a look at a thought on this later today..

**Comment by MatthewVita** [comment]
Wow, very cool @ivmartel .

I would say let's just use the zip file approach for now and not add anything else because the next step is to connect to Orthanc PACS server. That will be the source of truth for the DICOM files so it's totally automated.

**Comment by MatthewVita** [comment]
Go team!

**Comment by kofiav** [comment]
Sounds good, I'll try to set up a prototype using the zip file approach.

**Comment by kofiav** [comment]
I'm adding a check for all zip files (like [this](https://stackoverflow.com/questions/9817525/in-php-is-it-possible-to-inspect-content-of-a-zip-file-without-extracting-its-co)) and only passing the zip files to the dicom viewer if it only contain dcm files.

**Comment by sjpadgett** [comment]
I'm curious Victor where the zip come from i.e are they package that way from source provider or does user create them e.t.c

**Comment by MatthewVita** [comment]
@sjpadgett This is a manual process for the version 1. The staff will be responsible for manually transporting the files AND packing them up if they should be grouped. V2 will be using a proper PACS server (Orthanc), which the device(s) will actually interface with (and, in turn, OpenEMR will interface with)

**Comment by sjpadgett** [comment]
Ah, got it. So, as said, probably not worth providing a way to drop files into a zip in the Document interface...

**Comment by kofiav** [comment]
Just did a PR with my work in progress.

**Comment by kofiav** [comment]
I guess this can be closed, or what's the next step PM @MatthewVita

**Comment by MatthewVita** [comment]
Great work. I'd say the next ticket is https://github.com/openemr/openemr/issues/1370
