### ISSUE TITLE
QA DICOM Web Viewer i18nLocalesPath Integration

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#1361]

**Comment by MatthewVita** [comment]
Ha, this is actually not needed because we're using the simple view for DWV. There is no text displayed in the viewer pane itself so this is not needed!!!

**Comment by sjpadgett** [comment]
Hi @MatthewVita , really I believe this file is still called by viewer and if the new wrapper is used from somewhere else for whatever reason then, this will come up again.
