### ISSUE TITLE
Setup Orthanc and associated Docker configurations to point at a Postgres server

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#1366]

**Comment by bradymiller** [comment]
Does orthanc not use mysql?

**Comment by MatthewVita** [comment]
It was SQLite and Postgres only. For most users, SQLite will be fine as it requires no setup. For cloud, we're gonna want to use Postgres for replication purposes.

@bradymiller

**Comment by bradymiller** [comment]
As with openemr/mysql dockers integration, will it make sense to build out orthanc/postgres dockers (nicely postgres docker actually uses alpine btw :) ) integration so install/integration doesn't differ across different platforms?

**Comment by MatthewVita** [comment]
Yup! Docker all the way!
