### ISSUE TITLE
Add helpful tooltips/documentation on what v1 features consistent of

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#1368]
We need to note in the press release, the code itself (via a nice tooltip or modal, which Jerry can help with), and the wiki that v1 of our solution is mainly aimed at Xrays and we will support multi images (CT, MRI) in the next version as well as a proper PACS server (for now, clinicians and staff have to manually upload the images to OpenEMR).

Should probably noop the mouse scrolling too.

**Comment by sjpadgett** [comment]
@MatthewVita If you outline what you need I can take a look. Most likely a one time popup/user informing current limitation on app entry or a help panel.

**Comment by MatthewVita** [comment]
@sjpadgett Thanks for being on top of it. Let me assign this to you and me, but please note that the work cannot start quite yet because the UI is not working on `master`. @kofiav is currently fixing this up. Once done, I'll re-comment here so you can take a look at the popup/user information. I'll give you the text for it too.

Thanks!

**Comment by MatthewVita** [comment]
@sjpadgett, @kofiav,

Do you guys think we even need documentation in the system? I feel like the UI is very intuitive. Doesn't need a modal popup explaining it...

**Comment by MatthewVita** [comment]
(Of course we'll add the feature to the wiki and throw some stuff there)

**Comment by sjpadgett** [comment]
The only potential user issue I see currently will be dealing with mime type for DICOM files. I took a cheap route to determine in windows by using if file is binary then looking at file extension, leaving a possibility user could rename file extension. Also the mime type is determined in two different locations with upload using the depreciated $_FILES for file information. Really need to write a method to peek at file header but agree, viewer is pretty straight forward without a need to explain operation. On the other hand, maybe some input from a clinician concerning this is needed.

**Comment by kofiav** [comment]
@sjpadgett about the mime type, I agree a more elegant solution is needed so that it won't cause further issues down the line. 

I'm assuming $_FILES is returning the wrong mime type on Windows - that's the root cause of the issue right?

Let me know if you need any help with this.

**Comment by sjpadgett** [comment]
Yep, some other ways i've tried of various php methods stick to stream. May be a way to config apache but i'll come up with something more reliable but ,really that upload work flow needs to be redone due to some depreciation's. Who knows, perhaps i'll get inspired(been know to happen) to come up with a grouping method to at least zip on the fly...
