### ISSUE TITLE
OpenEMR- (latest version) - XSS Issues

### ISSUE THREAD

**Issue by priya-anand** [openemr/openemr#1389]
Encountered some issues in the latest version - will send a separate message as an email attachment.

**Comment by bradymiller** [comment]
Confirmed that received above security issues via email.

**Comment by OzairP** [comment]
Should this issue be closed?

**Comment by bradymiller** [comment]
This is still an ongoing project to fix all xss issues in the gacl module. Almost is complete. @priya-anand , just checking if you are still working on this.

**Comment by bradymiller** [comment]
Going to close this issue
