### ISSUE TITLE
Localization/Filipino Translation

### ISSUE THREAD

**Issue by jcpuzs1** [openemr/openemr#1423]
I want to contribute by Localizing and translate it to my native language which is Filipino.

**Comment by MatthewVita** [comment]
Hi @jcpuzs1 - awesome!

Our website is down, but when it's up you'll want to visit http://www.open-emr.org/wiki/index.php/OpenEMR_Internationalization_Translator_Guide

@bradymiller can you invite him to the doc?

**Comment by bradymiller** [comment]
hi @jcpuzs1 ,
Thanks for offering to help with Filipino translations. Send your gmail email address to me at brady.g.miller@gmail.com and then I'll give you some overview/instructions and get you set up to be able to add translations to the translation spreadsheet.
thanks,
-brady

**Comment by jcpuzs1** [comment]
sir I already send my gmail and also my yahoomail. Thank you sir
 

    On Thursday, 15 February 2018, 4:31:08 PM GMT+8, Brady Miller <notifications@github.com> wrote:  
 
 
hi @jcpuzs1 ,
Thanks for offering to help with Filipino translations. Send your gmail email address to me at brady.g.miller@gmail.com and then I'll give you some overview/instructions and get you set up to be able to add translations to the translation spreadsheet.
thanks,
-brady

**Comment by jcpuzs1** [comment]
I already send my gmail through yahoo. My gmail is johncarlsaducas@gmail.com.

**Comment by bradymiller** [comment]
hi @jcpuzs1 ,
Thanks! Got your email also. Had some technical issues on website, but should be getting you access to the translation spreadsheet by tomorrow. Also check out this page to see more details on the internationalization project: https://www.open-emr.org/wiki/index.php/OpenEMR_Internationalization_Translator_Guide#Overview
thanks,
-brady

**Comment by jcpuzs1** [comment]
Okay sir, Thank you and I will wait sir

**Comment by bradymiller** [comment]
hi @jcpuz ,
Just emailed you with instructions and gave you access to the translation spreadsheet. Gonna close this issue, but feel free to reopen it if have any issues.
thanks!
-brady

**Comment by jcpuzs1** [comment]
Sir thank you so much. Is it okay if I translate it by 1000 words or 1000 plus ? I will diveide it into 1000's ?
    On Monday, 19 February 2018, 8:01:09 PM GMT+8, Brady Miller <notifications@github.com> wrote:  
 
 
Closed #1423.

**Comment by bradymiller** [comment]
hi @jcpuzs1 ,
Translate it however is easiest for you. Doing a thousand at a time may cause premature aging, though :)
thanks!
-brady

**Comment by jcpuzs1** [comment]
Im sorry but i have a question if you dont mind. Where can I see the number of words that are translated. Im sorry Im still exploring it. Thanks

**Comment by bradymiller** [comment]
hi @jcpuzs1 ,
The spreadsheet is processed daily and the stats for that can be found here:
https://raw.githubusercontent.com/openemr/translations_development_openemr/master/stats.txt
-brady
