### ISSUE TITLE
openemr merge issue in github

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#1435]
hi..
I am getting this message whenever I am trying to push origin +master - 
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol versionwhile accessing https://github.com/arnabnaha/openemr.git/info/refs fatal:HTTP request failed

Cant merge/update my database..please help

**Comment by bradymiller** [comment]
This seems like a github issue. Are you able to:
1. Create a temporary branch
2. Push that branch to github (ie. origin)

**Comment by arnabnaha** [comment]
Hi Brady...
I am able to create a branch called test, but on pushing using the command git push origin +test, it given me the same error

Can you tell me whether using ssh will help or not?? if yes, plz tell me how to switch to ssh

Thanks and regards
Arnab

**Comment by sjpadgett** [comment]
While not a git virgin(Brady was my first:)) have you upgraded your git client of late? Looks like git thinks you are talking http...

**Comment by arnabnaha** [comment]
No i havent updated my client. I have the same version as before

On 23 Feb 2018 18:33, "Jerry Padgett" <notifications@github.com> wrote:

While not a git virgin(Brady was my first:)) have you upgraded your git
client of late? Looks like git thinks you are talking http...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openemr/openemr/issues/1435#issuecomment-368003441>,
or mute
the thread

**Comment by sjpadgett** [comment]
I think git has done some changes recently with weak encryption. Upgrade your git and client will solve (I think)...

**Comment by arnabnaha** [comment]
I upgraded the client and gui...everything works fine...thanks a lot

**Comment by arnabnaha** [comment]
Thanks all..closing the issue
