### ISSUE TITLE
Need PHP 7.2 testing (ie. call to arms)

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1452]
Just set up a Ubuntu 18.04 (their beta version) demo docker, which uses PHP 7.2 here:
https://www.open-emr.org/wiki/index.php/Development_Demo#Alternate_Demo_.28Ubuntu_18.04_-_uses_php_7.2.29

This needs lots of testing. Just click on everything you can imagine and check the log while doing this. And report broken things or log output.

**Comment by bradymiller** [comment]
Did a quick run through and reported all the Errors, Deprecated, and Warnings in issues. Now we need to fix them :)
(and my run through was pretty superficial; just clicked on every screen I could, but likely missed many in depth things; so feel free to keep testing and reporting other issues on this)

**Comment by bradymiller** [comment]
Everybody -> test, test, test :)

**Comment by bradymiller** [comment]
ping to keep testing, testing, testing the PHP 7.2 demo linked above

**Comment by MatthewVita** [comment]
Okay @bradymiller, I'll do a pass-through now.

**Comment by MatthewVita** [comment]
@bradymiller (Sorry for the delay - DockerHub went down) - is this here https://hub.docker.com/r/openemr/openemr/tags/ ?

**Comment by MatthewVita** [comment]
I'd rather test it on my own box

**Comment by bradymiller** [comment]
@MatthewVita ,
You would need to use a build of alpine:edge (this is using php 7.2 now). Could just place this in the dockerbuild that you do and see what happens. The above demo link uses a docker build of beta ubuntu 18.04 which uses php 7.2,

**Comment by bradymiller** [comment]
btw, the 18.04 demo docker farm build is here, but note it's specially made for the docker farm:
https://hub.docker.com/r/bradymiller/pre-openemr/

**Comment by MatthewVita** [comment]
@bradymiller hmm...

```
matthews-MacBook-Pro% docker run asdf
Cloning into 'demo_farm_openemr'...
 * Stopping Apache httpd web server apache2
 *
Started Build: Sun Apr 15 06:44:19 UTC 2018
Single demo mode
/home/openemr/git/demo_farm_openemr/demo_build.sh: line 161: /sbin/ifconfig: No such file or directory
IP ADDRESS is
git repo is openemr_repo
git repo full name is openemr_repo
git repo name is openemr_repo
git repo local path is /home/openemr/git/openemr_repo
git branch is branch
sdt option is serve_development_translations
udt option is use_development_translations
sp option is serve_packages
lp option is legacy_patching
dd option is demo_data
ds option is demo_ssh
wp option is patient_portals
external link is external_link
mysql p is root_sql_pass
github repo branch/tag is  branch_tag
ddu option is demo_data_upgrade_from
Demo description: descriptionone
Downloading the OpenEMR git repository
fatal: repository 'openemr_repo' does not exist
Copy git OpenEMR to web directory
rsync: change_dir "/home/openemr/git/openemr_repo" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
Configuring OpenEMR
chmod: cannot access '/var/www/html/openemr/sites/default/sqlconf.php': No such file or directory
chown: cannot access '/var/www/html/openemr/sites/default/documents': No such file or directory
chown: cannot access '/var/www/html/openemr/sites/default/edi': No such file or directory
chown: cannot access '/var/www/html/openemr/sites/default/era': No such file or directory
chown: cannot access '/var/www/html/openemr/library/freeb': No such file or directory
chown: cannot access '/var/www/html/openemr/sites/default/letter_templates': No such file or directory
chown: cannot access '/var/www/html/openemr/interface/main/calendar/modules/PostCalendar/pntemplates/cache': No such file or directory
chown: cannot access '/var/www/html/openemr/interface/main/calendar/modules/PostCalendar/pntemplates/compiled': No such file or directory
chown: cannot access '/var/www/html/openemr/gacl/admin/templates_c': No such file or directory
/home/openemr/git/demo_farm_openemr/demo_build.sh: line 407: /var/www/html/openemr/contrib/util/installScripts/InstallerAuto.php: No such file or directory
Using included translation set
Inserting demo data from demo_data
Error, demo_data data does not exist
Upgrading demo data from demo_data_upgrade_from
/home/openemr/git/demo_farm_openemr/demo_build.sh: line 469: /var/www/html/openemr/sql_upgrade.php: No such file or directory
sed: can't read /var/www/html/openemr/sql_upgrade_temp.php: No such file or directory
sed: can't read /var/www/html/openemr/sql_upgrade_temp.php: No such file or directory
Done configuring OpenEMR
chmod: cannot access '/var/www/html/openemr/sites/default/sqlconf.php': No such file or directory
mkdir: cannot create directory '/var/www/html/openemr/sites/default/procedure_results': No such file or directory
chown: cannot access '/var/www/html/openemr/sites/default/procedure_results': No such file or directory
Setting up demo_ssh ssh
Error, demo_ssh data does not exist
Setting up patient portals
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Done setting up patient portals
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
Demo install script is complete
Completed Build: Sun Apr 15 06:44:23 UTC 2018
matthews-MacBook-Pro% echo $?
0
```

('asdf' is the 18.04 image I built with `docker build -t asdf .`

**Comment by MatthewVita** [comment]
Oh, it must be `change_dir "/home/openemr/git/openemr_repo"` because this code doesn't pull down the program

**Comment by bradymiller** [comment]
I would not try to use that docker which is custom made for the demo farm. I do have plans in the future to support local use (have ambitious plans where can run all the dockers at the same time on different ports off same local development environment, but have not done that yet, and it take substantial work in https://github.com/openemr/demo_farm_openemr/blob/master/demo_build.sh )

Are you able to change line https://github.com/openemr/openemr/blob/master/contrib/util/docker/Dockerfile#L1 :
``````
FROM alpine:edge
``````
(this should then build using the most recent alpine development version that is using php 7.2)

**Comment by MatthewVita** [comment]
Building...

<img width="284" alt="screen shot 2018-04-17 at 11 30 30 pm" src="https://user-images.githubusercontent.com/1715206/38915108-5b1a5576-4297-11e8-851d-b928ab2c5549.png">

**Comment by MatthewVita** [comment]
Once done, I'm going to do a smoke test and have `docker exec -it openemr_local_development tail -f /var/log/apache2/error.log` running to see if anything pops up!

**Comment by MatthewVita** [comment]
Ouch...

```
Step 3/21 : RUN npm install -g bower
 ---> Running in 8287a3bde64a
/bin/sh: npm: not found
ERROR: Service 'openemr' failed to build: The command '/bin/sh -c npm install -g bower' returned a non-zero code: 127
```

**Comment by MatthewVita** [comment]
Added

```
RUN apk add --update nodejs nodejs-npm
```

Seems to be running better now..

**Comment by MatthewVita** [comment]
Ouch...

```
Step 19/22 : RUN chmod 500 /var/www/localhost/htdocs/run_openemr.sh /root/unlock_admin.sh     && chmod 000 /var/www/localhost/htdocs/auto_configure.php /root/unlock_admin.php     && ln -s /usr/bin/php7 /usr/bin/php
 ---> Running in 1b39e99209fd
ln: /usr/bin/php: File exists
ERROR: Service 'openemr' failed to build: The command '/bin/sh -c chmod 500 /var/www/localhost/htdocs/run_openemr.sh /root/unlock_admin.sh     && chmod 000 /var/www/localhost/htdocs/auto_configure.php /root/unlock_admin.php     && ln -s /usr/bin/php7 /usr/bin/php' returned a non-zero code: 1
```

**Comment by MatthewVita** [comment]
What could this be?

**Comment by bradymiller** [comment]
Try to remove the ' && ln -s /usr/bin/php7 /usr/bin/php' stuff since newer versions of alpine do not need this and since the file exists maybe trying to create the link is breaking something

**Comment by sjpadgett** [comment]
The default/multi site documents directories permissions are rewritten without write bit on docker restart in version i'm using for Jit(prior to Brady update for xml reader). Why is this? Can this be fixed here?

**Comment by MatthewVita** [comment]
@bradymiller 

Okay, smoke testing is done! Thanks for the support with the Dockerfile.

My smoke test passed - there is a noticeable slowness with the system nowadays, but oh well... (security > all else)

I just ran `docker cp 84350dbe85c2:/var/log/apache2/error.log ~/Desktop` and here is the attachment:

**Comment by MatthewVita** [comment]
(there are some things in there about scalar-whatchamacallits...)

**Comment by bradymiller** [comment]
Thanks @MatthewVita ,

Looks great (already have a ticket for the php warning's in the eye form)
btw, as an aside, I just added a Alpine Edge demo docker to the farm:
https://www.open-emr.org/wiki/index.php/Development_Demo#Alternate_Demo_.28Alpine_Edge_-_uses_php_7.2.29
(the demo farm is now housing a mere 40 demos :) )

-brady
