### ISSUE TITLE
dialog.js rtl support 

### ISSUE THREAD

**Issue by eyalvo-matrix** [openemr/openemr#1456]
dialog.js  loads css without referring to the $_SESSION['language_direction']

![image](https://user-images.githubusercontent.com/20621444/37082780-1b671610-21f6-11e8-99e1-b55fe19d77d4.png)

  it should load public/assets/bootstrap-rtl-3-3-4/dist/css/bootstrap-rtl.min.css

**Comment by bradymiller** [comment]
Sounds like a job for super @sjpadgett 
(with super man music playing in the background)

**Comment by sjpadgett** [comment]
That would be The Doobie Bro's. I've often wondered if at some point in history it was a teenager, just to annoy their parents, that started writing ltr! I've got this...

**Comment by sjpadgett** [comment]
@eyalvo-matrix Take a peek here: https://github.com/openemr/openemr/pull/1457

**Comment by bradymiller** [comment]
@eyalvo-matrix ,
Let me know if this is fixed, so I can close this issue.
thanks,
-brady

**Comment by eyalvo-matrix** [comment]
I did some tests and it looks goods thank you @sjpadgett !
you can close this issue @bradymiller, thanks :)
