### ISSUE TITLE
Warning in TabsWrapper.php

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1477]
PHP Warning:  Use of undefined constant INCLUDED_JQUERY_UI_CSS - assumed 'INCLUDED_JQUERY_UI_CSS' (this will throw an Error in a future version of PHP) in /var/www/html/openemr/library/tabs/src/TabsWrapper.php on line 54
PHP Warning:  Use of undefined constant INCLUDED_TW_ONETIME_CSS - assumed 'INCLUDED_TW_ONETIME_CSS' (this will throw an Error in a future version of PHP) in /var/www/html/openemr/library/tabs/src/TabsWrapper.php on line 61
PHP Warning:  Use of undefined constant INCLUDED_JQUERY_UI - assumed 'INCLUDED_JQUERY_UI' (this will throw an Error in a future version of PHP) in /var/www/html/openemr/library/tabs/src/TabsWrapper.php on line 99
PHP Warning:  Use of undefined constant INCLUDED_TW_ONETIME_JS - assumed 'INCLUDED_TW_ONETIME_JS' (this will throw an Error in a future version of PHP) in /var/www/html/openemr/library/tabs/src/TabsWrapper.php on line 103

**Comment by sunsetsystems** [comment]
I don't get this. Why would defining a constant, or testing if it's defined, be illegal?

**Comment by bradymiller** [comment]
Turns out these warnings are very easy fixes. Just need to surround the  INCLUDED_JQUERY_UI_CSS with single quotes in line 54 (and same in ther lines)
``````
define('INCLUDED_JQUERY_UI_CSS', '1-12-1');
``````

**Comment by sunsetsystems** [comment]
Duh. Thanks. :)

**Comment by bradymiller** [comment]
fixed
