### ISSUE TITLE
PHP 7.2 warnings when open eye form/module

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1481]
It was too big to include here, so placed it in a gist (guessing there are a lot of repeats).
https://gist.github.com/bradymiller/f90324b20fdb3d6009fd22bb0ee0fb50

**Comment by bradymiller** [comment]
Will retest this soon, since there will likely be much less warnings since have recently fixed other related warnings.

**Comment by bradymiller** [comment]
Updated the warnings in above gist which have decreased.

**Comment by bradymiller** [comment]
Fixed some of this in above commit. Will update the gist (or maybe it will be small enough to now fit here :) )

**Comment by ophthal** [comment]
this is closed right?

**Comment by bradymiller** [comment]
hi @ophthal ,
I just reran the eye form on php 7.2 and there are still a couple warnings. I updated the gist link to show them:
https://gist.github.com/bradymiller/f90324b20fdb3d6009fd22bb0ee0fb50
-brady

**Comment by bradymiller** [comment]
closing this since reporting these in a general php 7.3 issue: https://github.com/openemr/openemr/issues/2339
