### ISSUE TITLE
Warning in both onsite patient portals

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1490]
PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/html/a/openemr/interface/globals.php on line 43
PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/html/a/openemr/interface/globals.php on line 92
PHP Warning:  session_name(): Cannot change session name when session is active in /var/www/html/a/openemr/interface/globals.php on line 93

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Looks like PHP 7.2 is showing session issues in both onsite portals. Thoughts?
-brady

**Comment by sjpadgett** [comment]
This probably needs a test for a current session before calling any session init items in Globals. Script's can't fix because Globals still need to be called so, Globals it is...

**Comment by bradymiller** [comment]
fixed
