### ISSUE TITLE
Deactivating patient messages results in white screen

### ISSUE THREAD

**Issue by eyalvo-matrix** [openemr/openemr#1500]
How to repreduce
  Messages -> Edit->uncheck the Active  of one of the messages-> Update Active
 Getting white screen (in Frame mode)
(Also happens when there is no messages and pressing  Update Active)

in screen
![image](https://user-images.githubusercontent.com/20621444/37329565-fdf3e9e0-26a6-11e8-9413-0878764868f9.png)

this is because line 164 in pnotes_full.php
exit(); // add exit for ajax save from pnotes_full_add.php sjp 12/20/2017

**Comment by eyalvo-matrix** [comment]
This is maybe dialog.js issue 
@sjpadgett  can you have a look on it ?

**Comment by sjpadgett** [comment]
Yep, I was a little unsure about doing this so I commented. Can you remove exit and try both a save and  active for me? I think that will work but if not just add a conditional for the active check box to fall through. I'd do it but just reconfig'ed my setup to work on Dicom viewer patch for v5.0.0...

**Comment by eyalvo-matrix** [comment]
Sure

**Comment by eyalvo-matrix** [comment]
Oh i see you add && $mode != "update" I will get the latest pull and recheck it

**Comment by sjpadgett** [comment]
Sometimes my friend, we just get lusky!:)
