### ISSUE TITLE
Administration->Practice->Pharmacies->Default Method

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1501]
In development codebase, this always stays on Print no matter what is actually saved.

**Comment by sssopen** [comment]
Here is my analysis:
general.list.html is displaying the Pharmacies list. To display the "Default Method", it is calling:
$pharmacy->get_transmit_method_display() //in general.list.html

This method get_transmit_method_display() is from Pharmacy.class.php:
    function get_transmit_method_display()
    {
        return $this->transmit_method_array[$this->transmit_method];
    }

The variable $this->transmit_method] is being set in the constructor as 
$this->transmit_method = 1; // This 1 means Print
And I cannot find any code where function set_transmit_method() is called. So the value that set in the constructor is never changed. 

Whenever get_transmit_method_display() is called, it is always going to return "Print" and that's what happening when this method is called from general.list.html.

Also, based on the code, if the email address is empty, the Default Method is going to return as Print.

**Comment by sssopen** [comment]
I don't know if code is somewhere setting Pharmacy object with something like copyProperties to set the transmit_method.
Unfortunately I am not able to run the development codebase to pin point the issue :)

**Comment by bradymiller** [comment]
Nice analysis. We'll get your development environment and testing up in not time :)

**Comment by bradymiller** [comment]
hi @sssopen ,

I looked at your analysis and it hit that this isn't a bug:
"Also, based on the code, if the email address is empty, the Default Method is going to return as Print."

Whenever we choose Email, it basically gets changed to Print on the Save if there is no email address. If I add the email adress to the form then it works. Also, am able to always pick Fax, which then works.

Thanks for looking into this and am going to close this issue.

-brady
