### ISSUE TITLE
New Encounter visit category has "No Show" as a choice

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1502]
Bug in development codebase
No Show should not be an option for a encounter visit category

**Comment by sssopen** [comment]
This seems to be a data issue. The Visit Category drop down is being populated using the below SQL:

SELECT pc_catid, pc_catname, pc_cattype 
FROM openemr_postcalendar_categories
WHERE pc_active = 1  and pc_cattype IN (0,3) ORDER BY pc_seq

The resultset of the SQL is below. If we delete the record with "No Show" pc_catname, it should not populate in the drop down list. Is my understanding correct?

![image](https://user-images.githubusercontent.com/5135725/37498724-3f3e5aac-2896-11e8-91b3-e31e959947e2.png)

**Comment by bradymiller** [comment]
hi @sssopen 
Good analysis, and that would get rid of No show. However, in most cases, we need to show the No Show option other than here. So, in this case, we should filter it out by not to SELECT where the 'pc_constant_id'  sql column is equal to 'no_show'

**Comment by sssopen** [comment]
That make sense. One of the below options should do the trick. One with pc_catid =1 should be good if we know the id is not going to change.

SELECT pc_catid, pc_catname, pc_cattype 
FROM openemr_postcalendar_categories 
WHERE pc_active = 1 and pc_cattype IN (0,3) and pc_catid!=1 ORDER BY pc_seq

OR

SELECT pc_catid, pc_catname, pc_cattype 
FROM openemr_postcalendar_categories 
WHERE pc_active = 1 and pc_cattype IN (0,3) and pc_catname != 'No Show' ORDER BY pc_seq

OR
Filter after retrieving the data:;
common.php: could be at line 239:
  
 if ($catId == "1") {
               continue;
  }

**Comment by bradymiller** [comment]
Since you aren't working in the development code, you aren't seeing the pc_constant_id (this was added and always modifying the title of categories). So, in development codebase, will be:
``````
SELECT pc_catid, pc_catname, pc_cattype
FROM openemr_postcalendar_categories
WHERE pc_active = 1 and pc_cattype IN (0,3) and pc_constant_id  != 'no_show' ORDER BY pc_seq
``````

**Comment by bradymiller** [comment]
Confirmed that this bug has been fixed. Thank you @sssopen !
