### ISSUE TITLE
Vitals tab 'Save Form' 'Dont Save' buttons bugs

### ISSUE THREAD

**Issue by DanielPythonProjects** [openemr/openemr#1510]
Sorry, I have not looked to see if there is an open issue with this, but when I went to OpenEMR 5.0.1 Demo on Ubuntu 16.04, after selecting a Patient, and clicked https://one.openemr.io/c/openemr/interface/patient_file/encounter/trend_form.php?formname=vitals, Clicking Save form opens an 'Unknown' tab. 
The 'Don't Save'  button does not respond.

**Comment by bradymiller** [comment]
hi @DanielPythonProjects ,
Thanks for reporting this bug. Actually, those buttons should not even be showing up on the trending form. That form is only meant for seeing trends when click on it from the patient summary gui (and it will also graph things if click on it). So, bug is confirmed.

**Comment by bradymiller** [comment]
Just placed a fix for this into codebase:
https://github.com/openemr/openemr/pull/1532

Thank you @DanielPythonProjects for reporting this bug!
