### ISSUE TITLE
Unable to save recall records

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#1521]
Has anyone gotten the new recall feature to work?  Neither onsite nor demo save the "New Recall" data in current form.  Quick peek under the hood shows the use of `toJSON` function may be an issue.  Replacing the same by `JSON.stringify` eliminates the error, creates an entry in the table.

Maybe matter of time before the saved entries show up in the report?

Update:
Not sure if `deceased_date` is initialized to `''` as expected by `pat.deceased_date = ''`.
`IFNULL(pat.deceased_date, 0) = 0` may be better check to eliminate deceased pt records.

**Comment by bradymiller** [comment]
tagging @ophthal on this issue

**Comment by bradymiller** [comment]
@mdsupport , thanks for this report and fix!
@ophthal just brought in a commit with your fix here:
https://github.com/openemr/openemr/commit/fe7c0d77e4fc21a090ab26c2ecde84bfcc04581c

Gonna close this issue now :)
