### ISSUE TITLE
Support for MFA login

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1535]
Support for MFA login

**Comment by robertdown** [comment]
Clearing the milestone as I don’t think it’s feasible for 5.0.2. _maybe_ 503 if we get an experienced dev on the task soon

**Comment by bradymiller** [comment]
sounds good; bumped it to 5.0.3

**Comment by danehrlich1** [comment]
I have a guy I want to work on this. He'll get this done in a couple of months and he owes me a favor for a referral :)

Originally he was going to take care of the many SQL injections (back when it was 2000+ lines of code) but so many of those have been done prolly going to ask him to do this.

Features:
1. MFA during installation of OpenEMR for admin (app only)
2. Require MFA default for new users option in Globals
3. When new user signs in for first time register for MFA
3. Ability to reset MFA for user by administrator (removes MFA from user and they have to register MFA again during next login)
4. Determine how superadmin should reset MFA. Perhaps store a reset code in the database? If they get locked out can always log into database.

**Comment by sunsetsystems** [comment]
Nice. You know we already have U2F, right?
https://github.com/openemr/openemr/pull/1869
Note this code also anticipates adding more MFA methods. I'm happy to offer guidance if desired.

**Comment by sjpadgett** [comment]
I've already done the engineering and pseudo code for a custom authentication server for OpenEMR. It is needed for the FHIR Api. So a client will be welcomed.

**Comment by danehrlich1** [comment]
Oh wow didn’t realize this was sitting on a pull request!

1. Can user or at least the admin set multiple keys? I usually set a backup key.
2. How are you handling resets?
3. So I can add App-based MFA to this code? 
4. Do you have screenshots of what the UI looks like?

**Comment by sunsetsystems** [comment]
1. Yes any number of keys can be registered by the user.
2. An admin can reset MFA for a user via the user admin page. Check "Clear 2FA" and Save.
3. Yes you could add more MFA methods leveraging the existing code.
4. Since you have a key, try it out on one of the development demo sites! Create a user, log in, go to Miscellaneous -> MFA Management, register your key, log out and in again.

**Comment by danehrlich1** [comment]
Ok great I am claiming this one.

By March 1st deadline there will be support for app based MFA.

I am also going to add an option for the admin to add this during the
initial setup of OpenEMR.

QUESTION: what happens if the admin loses their MFA key?

**Comment by sunsetsystems** [comment]
What does "app based" mean?

If they lose their key they use their backup key. :)
Or have another admin clear it.
Or go into the database to clear it.

**Comment by danehrlich1** [comment]
Open Source version of Duo I meant: https://www.linotp.org/features.html
