### ISSUE TITLE
user's default facility dropdown

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#1541]
after adding a second facility am unable to select it for the user's default facility

user = physician or clinician (might want to think adding a type of provider or practitioner for those sweet nurses)

**Comment by odra** [comment]
Could I work on this one? :-)

**Comment by stephenwaite** [comment]
hi @odra , it's fixed in 5.0.2, https://community.open-emr.org/t/billing-location-vs-service-location/14805/5

wanna see if you can get it to work in master?

**Comment by odra** [comment]
sure let me give it a shot,  the issue can be closed if so.

**Comment by stephenwaite** [comment]
thank you @odra , will close the issue when fixed in master ok?

**Comment by odra** [comment]
@stephenwaite I can confirm it is working (tested with latest master commit) once a facility has been flagged as a "billing location" - I think this issue can be closed.

**Comment by stephenwaite** [comment]
right but would like to have it as a service location

**Comment by odra** [comment]
Ah, it does not work if it flagged as a service location :-)

I guess I can take work in it then?
