### ISSUE TITLE
Post-installation script error 255

### ISSUE THREAD

**Issue by generosocarbone** [openemr/openemr#1542]
I followed the installation guide for [PHP7](https://www.open-emr.org/wiki/index.php/OpenEMR_5.0.0_Ubuntu-Debian_Package_Installation_with_PHP7)
the error is what I get using the CLI installation.

I've also run the 'sudo apt-get install -f' line in case of error.
Lately, the pair 'admin' 'pass' for the login doesn't work
My environment
Ubuntu 17.10
Php 7.1.15
Mysql 5.7.14
Openemr 5.0.0-2

**Comment by bradymiller** [comment]
hi @generosocarbone ,
Sorry for the delayed reply. My guess here is that Ubuntu 17.10 is using PHP 7.1 which is not compatible with OpenEMR 5.0.0.
(note OpenEMR 5.0.1 will be compatible with PHP 7.1/7.2, which will be released in near future)

**Comment by generosocarbone** [comment]
I though it was this kind of issue so I downgraded my php version and all worked well. I just forgot to close the thread.
