### ISSUE TITLE
LOINC Codes?

### ISSUE THREAD

**Issue by sunsetsystems** [openemr/openemr#1561]
Looks like I need to load LOINC codes for a client. Is a loader for this of interest to the community?

**Comment by sjpadgett** [comment]
CCDA and FHIR use LOINC

**Comment by sunsetsystems** [comment]
OK are they already loading or otherwise implementing a table of them?

**Comment by sjpadgett** [comment]
Mostly embedded in code for various templates and code translations that mostly are not required so, really not needed for above.

**Comment by sunsetsystems** [comment]
Thanks Jerry.
