### ISSUE TITLE
CCM $this when not in object context fatal errors.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#1576]
Still numerous instant's of statically calling non static methods where exceptions are thrown by CCM. Really can't get away with turning off reporting in most cases so, these will need to be resolved on a case by case. Currently a show stopper in CCDA Import Review and Approve.

**Comment by adunsulag** [comment]
@sjpadgett Might as well assign this to me.  I believe I have these all resolved with the other CCM issues I'm fixing but I can double check it.

**Comment by stephenwaite** [comment]
probably still ongoing issue, https://community.open-emr.org/t/ccda/9486/22?u=stephenwaite
[ccm_ccda_import_php_log.txt](https://github.com/openemr/openemr/files/3649272/ccm_ccda_import_php_log.txt)

**Comment by adunsulag** [comment]
@stephenwaite So I fixed all the exceptions being thrown.  I didn't fix all the warnings / notices.

**Comment by sjpadgett** [comment]
You may turn off error reporting ~E_DEPRECATED & ~E_STRICT & ~E_USER_DEPRECATED to have module work until this is fixed.

**Comment by bradymiller** [comment]
All the leftover warnings in zend disappeared after updating the zend package (via composer), so closing this issue.
