### ISSUE TITLE
NewCrop eRx PHP Fatal error:  Uncaught ArgumentCountError PHP 7+

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#1577]
Uncaught ArgumentCountError: Too few arguments to function eRxXMLBuilder::trimData().
Also an issue in other work flows scattered about in other modules.

**Comment by bradymiller** [comment]
hi, Just checking if this is now fixed? -brady

**Comment by sjpadgett** [comment]
believe so.
