### ISSUE TITLE
OpenEMR- (latest version) - SQL Injection Issue

### ISSUE THREAD

**Issue by Gloomywind** [openemr/openemr#1579]
I found a security issue:interface\super\edit_list.php in OpenEMR latest version and
earlier allows remote authenticated users to execute arbitrary SQL
commands via the newlistname parameter

  details:
     Affected code:
            sqlInsert("INSERT INTO list_options ( " .
            "list_id, option_id, title, seq, is_default, option_value " .
             ") VALUES ( " .
             "'lists'," . // the master list-of-lists
             "'" . $newlistID . "'," .
             "'" . $_POST['newlistname'] . "', " .
             "'" . ($row['maxseq'] + 1) . "'," .
             "'1', '0')");
             $list_id = $newlistID;
     because $_POST['newlistname'] is not filtered,it can lead to sql lnjection

**Comment by bradymiller** [comment]
fixed here and will be in next 5.0.1 patch (to be released soon):
https://github.com/openemr/openemr/commit/2a5dd0601e1f616251006d7471997ecd7aaf9651
