### ISSUE TITLE
cannot print extension .txt document through patient reports

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#1580]
looks like imagemagick can't convert .txt to .jpg
prob need to add another if here
https://github.com/openemr/openemr/blob/master/interface/patient_file/report/custom_report.php#L659

**Comment by stephenwaite** [comment]
but then how do you safely dump a bunch of text into the viewport or is there a way to use the convert utility?

**Comment by stephenwaite** [comment]
will try readfile()

**Comment by bradymiller** [comment]
Code looks good (and I am assuming it tests well for you). Will bring it into the codebase and also next 5.0.1 patch. thanks for the fix! -brady

**Comment by bradymiller** [comment]
hi @stephen-smith ,
This looks really nice. I recommend incorporating your same method in the document viewer for text files (right now, the user needs to download text files to look at them).
-brady

**Comment by bradymiller** [comment]
yes, i did. but great to hear from you @stephen-smith ! I hope things are going well.

**Comment by stephenwaite** [comment]
ok, will try to push something, thanks @bradymiller , that's the stephen smith from circa v2.x?  cool
