### ISSUE TITLE
Need to update apache syntax

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#1602]
See here for issue and planned fix:
https://community.open-emr.org/t/apache-2-4-directory-security-changes/10041

**Comment by danehrlich1** [comment]
Updating config file, which is going to get further updates, can be found here: https://github.com/openemr/openemr-devops/blob/54be943e9ea55efdb6309b8a892e11603f78fd0f/docker/openemr/5.0.2/openemr.conf
