### ISSUE TITLE
Usernames with dots.

### ISSUE THREAD

**Issue by santiagosemhan** [openemr/openemr#1641]
When you want to edit ACL's in user that have's dots in username, group lists are not showed. 
For example: 
ids generated with "santiago.semhan" cannot be selected with jquery. But, you can use \\ chars escapes. 

Bug: $('#santiago.semhan')
Fix: $('#santiago\\.semhan')

File with bug: adminacl.php
function: generic_click

Regards.

**Comment by bradymiller** [comment]
thanks for the report @santiagosemhan 
I also confirmed this bug.
Guessing just need to leverage the prior solution we did to fix spaces in the usernames:
https://github.com/openemr/openemr/commit/3cdccbd1c12aae1b9d2f4ec013b69872120e1eab

**Comment by santiagosemhan** [comment]
Brady, i fixed bug with following regex:

```javascript
contentPointer = "#" + identity.replace(/([ .])/g,"\\$1");
linkPointer = "#link_" + identity.replace(/([ .])/g,"\\$1");
linkPointerPost ="";
errorPointer = "#error_" + identity.replace(/([ .])/g,"\\$1");
```

**Comment by santiagosemhan** [comment]
Hi @bradymiller, you can commit for me. 
My info: 
`Santiago Semhan <santiagosemhan@gmail.com>`

**Comment by bradymiller** [comment]
Done :)
https://github.com/openemr/openemr/commit/6506078ba4bd851a4c670135657e57eefcaf730b
Thanks for the fix @santiagosemhan !
-brady
