### ISSUE TITLE
Getting abruptly logged out or cross patient data.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#1644]
From forum https://community.open-emr.org/t/others-getting-abruptly-logged-out/10161.
Appears to happen when same UA is used for multiple windows/browser tabs. I suspect session not being restored or a cookie path issue. Hopefully some will help with any patterns this issue seems to show when issue is encountered.

**Comment by sjpadgett** [comment]
Just so all know that this is a bug with session cookies and easily recreated. Just have to figure out how to fix. Not an easy one...

**Comment by sjpadgett** [comment]
If more than one session is created within same UA then when globals is called(in any window/tab), session start will grab whatever is last started session, usually the first session created and writes that session back thus writing wrong session for that OpenEMR instance. Phew. This is also related to PHP7.2 session issues seen via portal and zend. Don't think this is restoreSession issue but globals session handling.
This explains improper timeouts to login screen and seeing different patient data suddenly where it doesn't belong after a refresh/reload or even suddenly getting timeout message white screen that @rmagauran was working.
I think we need to validate a session in globals before recreating and prevent rewriting session if current session is correct, somehow! Orrrr, pretend it never happened!

**Comment by bradymiller** [comment]
Hi @sjpadgett ,
Do you think this a bug that we've had in prior versions or new to 5.0.1?
-brady

**Comment by sjpadgett** [comment]
Not 100% sure but I recall looking at this issue back when Matrix needed to add a cookie path to ensure that cookies aren't shared across domains. Also, I recall scratching my head on this in 4.2. Makes sense that when restore session was added it merely ensured that sessions would refresh however, with the same cookie path for multiple cookies and not validating session, then php will only know to grab the last active session which may or may not be the correct session.
Recreate by opening two tabs and observe cookies in storage tab of console or set $GLOBALS['restore_sessions'] = 2 in globals.php.
Doesn't matter if restore session from timeout_iframe is called or script that loads globals.php as any call to session start., session cookie will toggle. Add a third or fourth window or tab and at least two cookies will be the same at any given time. It's nuts I tell ya! :).
I think we are going to finally have to bite the bullet and develop our own session manager. eeeww...

**Comment by sjpadgett** [comment]
@bradymiller Remember when I added session validation for Portal to prevent Portal sharing session when both OpenEMR/Portal Dashboard and Portal are using the same User Agent. I'm thinking we need to do the same to prevent more than one OpenEMR instance being opened on same UA.
We don't seem to get into as much trouble when a new tab is opened from existing session(New Window flag) as opposed to opening a new instance through login(still troublesome tho).
So i'm saying that for now we allow only one logged in session per User Agent. You may use FF for one and say Chrome for another if need be...

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Have been meaning to start also working on this critical issue, but stuff keeps coming up :)
Hopefully we don't need to do too much. As I recall the last time this sort of issue came up, was able to fix this with minimal code. Although, you may be right, and this time will take more restrictions.

**Comment by sjpadgett** [comment]
Thanks @bradymiller Besides yourself and @sunsetsystems Who else do you know are PHP guru's that maybe could help me out here. I don't know how you keep up with everything you are involved in but i'll see this through if I can get a little guidance from some whom are more experienced with bare knuckled PHP:)
Somehow we have to nail the login to its session.

**Comment by bradymiller** [comment]
when in doubt, make an "expedited" list :)
http://www.bradymd.com/todo/
(my plan is to test and look at this in detail this evening)
(goal is to have a patch this weekend that deals with this and mysql8 support)

**Comment by stephenwaite** [comment]
this was an earlier report of the bug https://community.open-emr.org/t/soap-nation-note-saved-to-other-patient/10049/6?u=stephenwaite

which believe shows it is in 5.0.0(x)

**Comment by bradymiller** [comment]
See here for some fixes:
https://github.com/openemr/openemr/pull/1659

**Comment by bradymiller** [comment]
fixes brought into codebase. hopefully this issue is now resolved (for now; am still discussing with Jerry in the PR regarding other ways we can really safeguard session leaking).

**Comment by sjpadgett** [comment]
@bradymiller I've pulled down your latest fixes and tried hard to break but was unable. Could I be wrong?:) My gut tells me this will come back or I don't understand session as well as I thought. Either case, great work. Thanks.
