### ISSUE TITLE
Undefined index: basePath in Header.php

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#1661]
Did a fresh install and saw this:

```php
Notice: Undefined index: basePath in C:\xampp\htdocs\openemr\Library\core\src\Header.php on line 158
```

Low priority, but I'll take a glance at it

**Comment by petersmm** [comment]
So I just upgraded my PHP as well from 5.4 to 5.6 and then upgraded to 5.0.1 latest from 5.0.0_patch8.

**Comment by robertdown** [comment]
Hi @petersmm this isn't an actual error, just a notice so everything will work as expected. I would recommend upgrading to the latest PHP soon, as PHP5.6 will stop receiving security updates later this year. I'll double check for the error on PHP7 but since it's just a notice, if it is only occurring on PHP5.6 I probably won't address it.

**Comment by petrosmm** [comment]
@robertdown I did upgrade to 7.2 and I still have it along the issues referenced in #1931

**Comment by robertdown** [comment]
Interesting, I'll take a look at it and see what's going on.

**Comment by petersmm** [comment]
Like I said, it's still showing up as notices. But I don't know if that's expected.

**Comment by vashishta** [comment]
@robertdown any update on this issue, as it still persists.
