### ISSUE TITLE
inactivate icd9 for new installs

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#1671]
goal is to make it easy to use icd10 out of the gate instead of accessing lower entries in drop box selections

**Comment by stephenwaite** [comment]
thanks for bringing it in @bradymiller

**Comment by stephenwaite** [comment]
hi @bradymiller , i guess this approach didn't work since the dev demos still show icd9 active and it's the first selection in all of the dropdowns :(

**Comment by bradymiller** [comment]
hi @stephenwaite ,
Is this the dev demos with or without sample data?
(I ask because the demos with sample data will likely not get rid of ICD9 since it's just upgrading an already existent database)

**Comment by stephenwaite** [comment]
yup, thanks @bradymiller , maybe could update the demo data to use icd10 codes and more recent dates of service to make the use of the data more convenient for users

**Comment by bradymiller** [comment]
hi @stephenwaite ,
Just would need the database changes for ICD10 here and we should be good:
https://github.com/openemr/demo_farm_openemr/blob/master/pieces/demo_5_0_0_5.sql
(the date of service issues would be a tougher feat and require running openemr from this database, ugprading to 5.0.1, making changes in openemr, and saving that database)

**Comment by stephenwaite** [comment]
this is fixed
