### ISSUE TITLE
Adding Eye Exam form breaks Encounter Summary page

### ISSUE THREAD

**Issue by zbig01** [openemr/openemr#1700]
When an Eye Exam form is added to an encounter then the form `/interface/patient_file/encounter/forms.php` breaks due to this stylesheet getting added to the page
`<link rel="stylesheet" href="../../forms/eye_mag/css/report.css" type="text/css">`

The following css rule from `report.css` is thus included 
```
span {
    display: block;
    color: white;
}
```
This causes the span elements on the page to break.

With no Eye Exam Form included - Note how **2018-05-31 Encounter** and the word **Collapse** are displayed correctly

![no_eye_form](https://user-images.githubusercontent.com/12654295/41277463-2c1ad3ca-6ddc-11e8-8cb0-f67ab9cfd78f.png)

With Eye Exam form included the span element acquires the above 2 rules and the text becomes invisible and gets displayed as a block element

![with_eye_form](https://user-images.githubusercontent.com/12654295/41277641-a363551a-6ddc-11e8-9fac-6d4e560439e1.png)

**Comment by ophthal** [comment]
This is a good example of where centralized css makes sense...

**Comment by ophthal** [comment]
Sure is.
The latest forms/eye_mag/css/report.css fixes this issue.

**Comment by bradymiller** [comment]
Issue fixed so closing
