### ISSUE TITLE
add capability to the patient merge routine to handle custom fields?

### ISSUE THREAD

**Issue by htuck** [openemr/openemr#1703]
Hi Folks- 
I was curious if anybody thought it'd be worthwhile to add the capability to the pt record merge module, of accommodating custom fields?
I've seen a lot of OpenEMR customers customizing their demographics etc and apparently that content doesn't get included in the new combined record of merged pts.  I'm strictly a support kind of guy not a dev or I'd have at it myself.
Hasta- Harley

**Comment by bradymiller** [comment]
That would definitely be a nice feature :)
