### ISSUE TITLE
Billing Manager "Select all" does not work

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#1705]

**Comment by ophthal** [comment]
Bug confirmed on https://seven.openemr.io/a/openemr/ demo also.

**Comment by zbig01** [comment]
@ophthal

The fix is in.
Check out this demo, will work once demo updates either automatically or if @bradymiller updates it sooner :)

https://www.open-emr.org/wiki/index.php/Development_Demo#Lambda_-_Up_For_Grabs_Demo

**Comment by bradymiller** [comment]
thanks @zbig01 ! I just brought your fix into codebase and will include it in the next 5.0.1 patch
