### ISSUE TITLE
Translation of word "New" in tabs title

### ISSUE THREAD

**Issue by shachar058** [openemr/openemr#1736]
In the "Tabs" openemr mode, when a new tab is opened (for example the encounters tab) the word "New" appears in the tab title for a second until the real title comes up.
The issue is that this word ("New") is hardcoded into the file`openemr/interface/main/tabs/js/tabs_view_model.js`,  and because it is a javascript file the php translation methods  can not be used.
How can we translate this word?

**Comment by bradymiller** [comment]
Strategy here is to create a javascript variable in php before bringing in the openemr/interface/main/tabs/js/tabs_view_model.js script. Here is an example:
https://github.com/openemr/openemr/blob/master/interface/main/tabs/main.php#L123-L128

**Comment by shachar058** [comment]
Ok thanks, understood.
I just sent a PR for this:
https://github.com/openemr/openemr/pull/1746
