### ISSUE TITLE
Select Patient to move document

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#1779]
In documents when trying to move a document to another patient, the select a patient pop-up is not working.
![select_to_move](https://user-images.githubusercontent.com/508784/43143589-065fedc8-8f29-11e8-8a5f-511e05d54aa0.png)

**Comment by bradymiller** [comment]
A fix for this was brought into main codebase which will be in OpenEMR 5.0.2:
https://github.com/openemr/openemr/commit/ea16b369c71ecba3bcece727cdb335648b9624b0
