### ISSUE TITLE
Calendar Patient and Provider times are overlapping if both had same start time

### ISSUE THREAD

**Issue by dorareddys** [openemr/openemr#1785]
Hi All,

How to fix display issue of times overlapping. I'm unable to add the image. Please see over the screenshot here below
[https://community.open-emr.org/t/calendar-patient-and-provider-times-are-overlapping-if-both-had-same-start-time/10544](url)

**Comment by d3sandoval** [comment]
@openemr/admins I'm happy to take this on. Could you please assign it to me?

**Comment by AlexAMCS** [comment]
I still have the exact same issue show in the "before" pic on the #1874 pull, running OpenEMR 6.0.0_1.
