### ISSUE TITLE
Percentage discount should be on total amount not on "Form_amount"

### ISSUE THREAD

**Issue by scorpions786** [openemr/openemr#1805]
https://github.com/openemr/openemr/blob/9e42523c4eaa0c3ff3a420df54d5dc9338391a76/interface/patient_file/pos_checkout.php#L587

**Comment by surfacehazard** [comment]
Still affecting v6.0.0(3) and messes up accounting quite a bit if using percentage discounts.  Not sure how to submit a PR against a stale and closed bug, but line 587 should probably be:

`$amount  = sprintf('%01.2f', trim($_POST['form_discount']) * computeDiscountedTotals(0, false) / 100);`
