### ISSUE TITLE
Asset location: chart.js

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#1817]
On sync with the master, I see a change in interface/forms/eye_mag/eye_mag_functions.php where chart.js is stored, but I do not see chart.js in $GLOBALS['assets_static_relative'] = "$web_root/public/assets";

New code:
```
        </div>
        <script src="<?php echo $GLOBALS['assets_static_relative'] ?>/chart.js/dist/Chart.bundle.min.js"></script>
```

was:
```
        <script src="<?php echo $GLOBALS['assets_static_relative'] ?>/Chart.js-2-1-3/dist/Chart.bundle.min.js"></script>
        <div style="position:relative;float:right; margin: 0px 5px;text-align:center;width:60%;">
            <?php
```

**Comment by bradymiller** [comment]
hi @ophthal ,

Check out this thread on the new building process for OpenEMR:
https://community.open-emr.org/t/openemr-takes-big-development-step-with-composer-and-npm/10654

-brady
