### ISSUE TITLE
Requesting Snyke Integration

### ISSUE THREAD

**Issue by vyas-vinay** [openemr/openemr#1824]
As a developer 
I want to integrate snyke or similar (e.g. Greenkeeper) 
So that vulnerabilities are detected and could be flagged 

Note : Snyke is free for open source projects. 
https://snyk.io/

**Comment by bradymiller** [comment]
hi @vyas-vinay ,

That looks like a great idea! Let us know if you need any help on OpenEMR's admin end to set things up.

Thanks!
-brady

**Comment by bradymiller** [comment]
Hi,
I just looked into this and all it appears to be doing is reporting vulnerabilties that are brought in via packages by npm (ie. already known vulnerabilites). It does not seem to do any original code analysis.
-brady
