### ISSUE TITLE
Therapy groups not working

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr#1841]
Hi.

From the time  we began work with npm and [the assets was changed ](https://community.open-emr.org/t/openemr-takes-big-development-step-with-composer-and-npm/10654) the therapy group is not working (add participant, add appointment etc.)- 
![image](https://user-images.githubusercontent.com/17809866/45156598-5ff12100-b1e7-11e8-86eb-6093f594fcd7.png)

Could you fix it soon?

Thank you
Amiel

**Comment by bradymiller** [comment]
hi @matrix-amiel ,
Thanks for pointing this out. Looks like this slipped through in about 6 or so scripts. Will get in the fixes this evening.
thanks,
-brady
