### ISSUE TITLE
RTL css with sass

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr#1877]
Hi @d3sandoval @bradymiller 

I have thought about the option to improve the style developing and reduce the amount of rtl fixes in the project. I have found very nice way to make it using sass and gulp (now already merged in the project..).
Instead to import additional file in the end of the css that overwrite the ltr settings we can load in the begin of the css file with variables and functions that will change the css according the language direction.

Here very nice example of such file I found in Github - https://github.com/tysonmatanich/directional-scss

What do you think? Is it complicated to integrate it in the project?   

Amiel

**Comment by d3sandoval** [comment]
Not at all! I think that's a great idea :) the only thing you'll have to watch out for are the rtl styles that do not currently live in the scss files. We have a lot of inline styles, style blocks in PHP files, and standalone css files. If there's rtl rules associated with these styles, they'll need to be ported over to scss before applying directional.scss

**Comment by matrix-amiel** [comment]
Hi @d3sandoval .
I agree with the problem of the inline styles. Right now all those styles are overwrote in the rtl.scss file.  
until we will move all the styles to scss files we can put all the css of rtl.scss file into mixin and include it only in rtl files.
Something like -
```
@mixin rtl {
    tr, td, th {
        text-align: right !important;
       ...
       ...
    }
}
@include if-rtl { @include rtl;}
```
What do you say?
I can try to make pull request with the scss changes and you will merge it into the npm build process.

**Comment by d3sandoval** [comment]
@matrix-amiel works for me!

**Comment by matrix-amiel** [comment]
Done. 
PR #1904
