### ISSUE TITLE
PHP Fatal error after patch 6

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#1878]
[Sun Sep 23 20:22:53.891810 2018] [:error] [pid 4320:tid 2032] [client ::1:60680] PHP Fatal error:  require_once(): Failed opening required 'C:\\xampp\\htdocs\\openemr\\interface/../common/compatibility/Checker.php' (include_path='\\xampp\\php\\PEAR') in C:\\xampp\\htdocs\\openemr\\interface\\globals.php on line 4, referer: http://localhost/openemr/admin.php

kindly see

**Comment by bradymiller** [comment]
hi @arnabnaha ,
Was it working before the patch? If so, what version (patch number) were you using before the patch?
-brady

**Comment by arnabnaha** [comment]
Brady,
I was out of touch with my systems for pretty long...can you please tell me..how can I upgrade my database now?? I am not finding the admin.php page which was there earlier...

**Comment by bradymiller** [comment]
The patch doesn't touch admin.php, so something odd seems to be going on. what does your main openemr directory look like?

**Comment by arnabnaha** [comment]
Brady
I am trying to bring in the master from the github...hope it will cure everything..if anything wrong goes...i will ping you.

**Comment by arnabnaha** [comment]
Brady
I pulled in the master files into the openemr directory of my localhost. admin.php shows i am on 5.0.0 and when I click on upgrade database - it gives an error - This page isnt working - HTTP 500

error log is here- 
[Sun Sep 23 21:30:20.693372 2018] [:error] [pid 8132:tid 2028] [client ::1:61425] PHP Fatal error:  require_once(): Failed opening required 'C:/xampp/htdocs/openemr/vendor/autoload.php' (include_path='\\xampp\\php\\PEAR') in C:\\xampp\\htdocs\\openemr\\interface\\globals.php on line 213, referer: http://localhost/openemr/admin.php

**Comment by arnabnaha** [comment]
@bradymiller  please help

**Comment by bradymiller** [comment]
Probably the best option if you are trying to upgrade to most recent development codebase (5.0.2-dev) is:

1. Use the package that is built daily from the master branch (5.0.2-dev):
https://www.open-emr.org/wiki/index.php/OpenEMR_Downloads#Daily_snapshots

And use this with the upgrade instructions:
https://www.open-emr.org/wiki/index.php/Windows_Upgrade_5.0.0_to_5.0.1

(you can also build your own complete openemr package from master, but you need to install composer and npm to do this; if you want to do this, just let me know)

(btw, I am assuming that you are still using windows)
-brady

**Comment by arnabnaha** [comment]
I am still on windows 👍 
Please let me know how to use composer and npm

**Comment by bradymiller** [comment]
Here are instructions to install composer:
https://www.hostinger.com/tutorials/how-to-install-composer#gref
(See Option 3)

Here are instructions to install npm:
https://blog.teamtreehouse.com/install-node-js-npm-windows

Then you go to the main openemr directory and run the following commands:
```
composer install
npm install
npm run build
composer dump-autoload -o
```

**Comment by bradymiller** [comment]
btw, for npm, install the 8.12.0 LTS version (the website offers 2 versions)

**Comment by arnabnaha** [comment]
@bradymiller 
I see that the vendor folder is missing from the recent codebase and without this folder, it is giving an HTTP 500 error on trying to open openemr. When I install the openemr from the recent dev tip - it doesnot work after step 4. I tried upgrading the database, but the whole template is distor.ted and login page looks worst

**Comment by arnabnaha** [comment]
Hi Brady,
I am doing the steps as told by you. Currently composer is building things in my openemr directory. Do i need to install composer each time i bring in the changes from github??

**Comment by bradymiller** [comment]
hi @arnabnaha ,
To clarify installing composer and npm are only done once on the computer.

But the build steps (the 4 commands above), should be done whenever you bring changes from github (since those libraries may get changed or the theme files may of been updated).

-brady

**Comment by arnabnaha** [comment]
Thanks Brady...all done smoothly and working fine

**Comment by infegrevathi** [comment]
Warning: require_once(sites/default/sqlconf.php): failed to open stream: No such file or directory in D:\xampp\htdocs\openemr\index.php on line 21

Fatal error: require_once(): Failed opening required 'sites/default/sqlconf.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\openemr\index.php on line 21
![localhost - Google Chrome 8_17_2020 11_22_08 PM](https://user-images.githubusercontent.com/69343862/90633995-e38d5800-e1db-11ea-9f62-a33bb882b916.png)

**Comment by infegrevathi** [comment]
PHP Fatal error:  require_once(): Failed opening required 'D:\\xampp\\htdocs\\openemr/vendor/autoload.php' (include_path='D:\\xampp\\php\\PEAR') in D:\\xampp\\htdocs\\openemr\\setup.php on line 95
please help me
