### ISSUE TITLE
PostCalendar Module

### ISSUE THREAD

**Issue by scorpions786** [openemr/openemr#1881]
The module need to be optimized
it seems in large data the calendar is having  delay specially in weekly view  
the issue seemed to be from two factors

compiling the view or
 the following SQL query
https://github.com/openemr/openemr/blob/9a7444a23561855929ba1133cfc28ddf881eb6e6/interface/main/calendar/modules/PostCalendar/pnuserapi.php#L1088

is there's any idea how to enhance the query or the speed of the calendar overall ?

try to test the calendar with large data(events)

in - out 
patients
providers

**Comment by scorpions786** [comment]
#Enhancement

**Comment by scorpions786** [comment]
yes the case was with multiple  recurring appointments
there are several solutions in my mind
but it may need some work to change the flow of these appointments

one of them
- is to reduce PHP/JSON use - such as creating database table with the recurrent appointments dates for specific event_id 

or maybe another one is to make confirm button for those recurrent appointments to make suppurate events for specific events

**Comment by mdsupport** [comment]
With current structure you cannot avoid PHP - the fields track exceptions.  This module shows its age - an era when disk was expensive and developers tried to save on repeating columns.  Now disk is cheap and development effort in maintaining two routines for getting a list of appointments throughout the code is expensive.  Have you looked at just creating actual records with a parent_recur_id (probably the first event id) and then allow group maintenance for future appointments by single update statement?  Current functionality of changing all records including past/history is legally troubling.  It will also fix the issue of status applying to all records.  So cancel recent appointment and all future entries show status as 'Cancelled'!!!
