### ISSUE TITLE
Patient file->Prescription->add :  months names are not translated 

### ISSUE THREAD

**Issue by eyalvo-matrix** [openemr/openemr#1889]
Patient file->Prescription->add :  months names are not translated . 

![image](https://user-images.githubusercontent.com/20621444/46352427-6b0e6400-c662-11e8-9157-7da176817894.png)

This is because of smarty functions
file: function.html_select_date.php line: 191 parameter: $month_names

**Comment by bradymiller** [comment]
hi @eyalvo-matrix ,
The best thing to do here would be to convert this to a standard (the one used in openemr) date widget.
(luckily, this mechanism is only used in this 1 place)
-brady

**Comment by dimitristsilis** [comment]
Shouldn't this be marked as closed?

**Comment by bradymiller** [comment]
hi @dimitristsilis , Thanks for pointing this out. Closing this issue.
