### ISSUE TITLE
bug in calendar when there are multiple facilities

### ISSUE THREAD

**Issue by sloboy** [openemr/openemr#1897]
Steps to reproduce:
clone master
docker-compose up (easy developer)
add a second facility, making sure to check service location
navigate to calendar
choose any facility other than all (happens in day, week, month views)

Result:

Query Error
ERROR: query failed: select distinct id, username, lname, fname, authorized, info, facility, suffix from users where username != '' and active = 1 and id like '%' AND authorized = 1 AND calendar = 1 AND facility_id = '4'' ORDER BY lname, fname

Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''4'' ORDER BY lname, fname' at line 1

/var/www/localhost/htdocs/openemr/library/patient.inc at 339:sqlStatement
/var/www/localhost/htdocs/openemr/interface/main/calendar/modules/PostCalendar/pnuserapi.php at 326:getProviderInfo(%,1,4)
/var/www/localhost/htdocs/openemr/interface/main/calendar/includes/pnMod.php at 605:postcalendar_userapi_buildView()
/var/www/localhost/htdocs/openemr/interface/main/calendar/modules/PostCalendar/pnuser.php at 173:pnModAPIFunc(PostCalendar,user,buildView,Array)
/var/www/localhost/htdocs/openemr/interface/main/calendar/modules/PostCalendar/pnuser.php at 93:postcalendar_user_display(Array)
/var/www/localhost/htdocs/openemr/interface/main/calendar/includes/pnMod.php at 637:postcalendar_user_view(Array)
/var/www/localhost/htdocs/openemr/interface/main/calendar/index.php at 162:pnModFunc(PostCalendar,user,view)

Cause: seems to be an extra single quote in the facility_id section of the where clause

**Comment by stephenwaite** [comment]
nice report @sloboy , looks like it's here https://github.com/openemr/openemr/blob/b77fb95af8ef9fc1da58e9e6842520951a61857f/library/patient.inc#L323

**Comment by sloboy** [comment]
Yup that fixes it...I thought it would, but I am so new to this that I needed some external confirmation.  I created a new branch on my project and will create a pull request.

Thanks @stephenwaite
