### ISSUE TITLE
Investigate XRoad as a possible data exchange framework

### ISSUE THREAD

**Issue by gsarma** [openemr/openemr#1906]
_[I'm new to OpenEMR and @MatthewVi suggested that I open some issues with a few ideas I had suggested in a previous conversation.]_

Estonia has launched a joint research institute with Finland called the [Nordic Institute for Interoperability Solutions](https://www.niis.org) to develop [XRoad](https://github.com/nordic-institute/X-Road), an open-source, decentralized, data exchange framework that also happens to be the backbone of their country-wide EHR system. 

Would it be possible to use [XRoad](https://github.com/nordic-institute/X-Road) as a data exchange framework for OpenEMR? What kind of effort would that involve? What are the pros and cons? 

What got my attention is that in Estonia, users own their data and grant access to health care providers, rather than the other way around. I'm wondering if this could be an exciting way to differentiate OpenEMR from other solutions and possibly win allies among the various Nordic countries that are working to advance XRoad.

**Comment by MatthewVi** [comment]
Do we know if XRoad works with REST APIs?

**Comment by gsarma** [comment]
I don't know enough personally about the technical details of the project, but here is an article from earlier in the year discussing X-Road and REST:

https://www.niis.org/blog/2018/4/3/x-road-and-rest
