### ISSUE TITLE
New encounter can be created by user w/o provider(authorize) flag set in Users.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#1913]
Kind of defeats the purpose of the flag. Either should not allow creation or allow the newly created encounter to allow re-save to new provider or after provider flag is set in users.
Is this by design or is this a bug clinicians?

**Comment by sunsetsystems** [comment]
Not a bug, as providers can have another staff person do this as well as entering clinical data. Access control should be checked instead.

**Comment by sjpadgett** [comment]
Yep, I get that but, if the logged in user does not have their provider flag checked, this means the encounter is created with that user as the provider of record for the encounter. Meaning, any future actions against the encounter that require the forms authorized flag set to true will be disregarded.
This becomes problematic when acting on the encounter, CCM comes to mind. Even encounter summary will not display encounter creator in this case.

**Comment by sunsetsystems** [comment]
The Fee Sheet lets you enter rendering and supervising providers. It seems reasonable to put that in the visit summary form as well. In any case it seems wrong to allow a non-provider user to be either of those.
