### ISSUE TITLE
Unresolved merge conflict in `forms/eye_mag/view.php`

### ISSUE THREAD

**Issue by serixscorpio** [openemr/openemr#1940]
While looking to reproduce issue #1481, I came across a merge conflict that somehow made it into `master` branch.  I presume this is done by accident.  This [merge](https://github.com/openemr/openemr/pull/1767/files#diff-8d5faeaf4ceb4e7e2737b4b10908d13cR3902
) introduced the conflict. The current file in master: https://github.com/openemr/openemr/blob/bd4a9958bd64454c2cc3e4c3d9bf2e52de095e38/interface/forms/eye_mag/view.php#L3902

**Comment by bradymiller** [comment]
hi @serixscorpio ,
Thanks for reporting that! Just posted a fix for it here, which is testing well and will bring into codebase soon:
https://github.com/openemr/openemr/pull/1941
-brady

**Comment by serixscorpio** [comment]
fixed in #1941
