### ISSUE TITLE
Demo sites do not function

### ISSUE THREAD

**Issue by abhid** [openemr/openemr#1942]
Just an FYI that the demo site username and password combinations do not work.
Thank you

**Comment by bradymiller** [comment]
hi @abhid ,

Thanks for the report. There have been issues with the main demos (bad actors appear to have automated credential changes on the official demos). We are working on a strategy to stop this. See here for more details:
https://community.open-emr.org/t/openemr-demo-fails/10905

Also note there are other demos (that are using the same version as the official demos) here:
https://www.open-emr.org/wiki/index.php/Development_5.0.1_Demo 4

thanks,
-brady

**Comment by abhid** [comment]
Excellent. Thank you @bradymiller 
I should have looked on the community.
