### ISSUE TITLE
edit or replace file_get_contents()

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#1983]
`file_get_contents()` function has many security concerns, mainly around how it implements old versions of SSL. 

To fix this, we can either add in additional parameters to `file_get_contents()` (see below) or a library like Guzzle HTTP can be used (I believe Laravel uses this).

```
$url = 'https://api.twitter.com/1/statuses/public_timeline.json';
$contextOptions = array(
    'ssl' => array(
        'verify_peer'   => true,
        'cafile'        => '/etc/ssl/certs/ca-certificates.crt',
        'verify_depth'  => 5,
        'CN_match'      => 'api.twitter.com',
        'disable_compression' => true,
        'SNI_enabled'         => true,
        'ciphers'             => 'ALL!EXPORT!EXPORT40!EXPORT56!aNULL!LOW!RC4'
    )
);
$sslContext = stream_context_create($contextOptions);
$result = file_get_contents($url, NULL, $sslContext);
```
https://github.com/guzzle/guzzle

**Comment by sjpadgett** [comment]
I use Guzzle in my phpfhir and my HIE module web services(not in openemr) but php soap for Quest lab module(go figure and have I mentioned before, I hate XML:)). In the end it relies on curls SSL capability. Though, using a plugin, curl can be replaced. Point being, Guzzle is versatile and fairly light weight.
Give me JSON or give me death! hmm, has that already been said...

**Comment by danehrlich1** [comment]
@sjpadgett Thanks for this comment. If everyone hated Guzzle I was going to go with `curl` as it was also highly recommended as a secure implementation but if Guzzle already uses `curl` we are good to go :)

**Comment by sjpadgett** [comment]
@danehrlich1 If you are going to replace a native PHP function, i'd stay with curl. Just cleaner in this use case. IMO..

**Comment by morg0n** [comment]
I can take this one on!

**Comment by bradymiller** [comment]
hi @morg0n ,
Sounds good. Probably good to find a spot in codebase that does this and then we can go from there.
-brady

**Comment by prondubuisi** [comment]
Hello @danehrlich1 I have a curl function that works exactly as get_file_contents() or so i think D:
function file_get_contents_curl($url) {
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_AUTOREFERER, TRUE);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);       

    $data = curl_exec($ch);
    curl_close($ch);

    return $data;
}
for ease of use I would like to add to a file in the codebase where it will be globally accessible, do have a look, Also in which of the .inc files can this function go into?

**Comment by robertdown** [comment]
Again, I would recommend against these kind of functions instead opting for a package like [Guzzle](http://docs.guzzlephp.org/en/stable/) as this functionality already exists and is well-tested in the Wild. By recreating the wheel we risk introducing more security flaws in an effort to actually reduce them.

**Comment by sjpadgett** [comment]
Or one could use the rest http client like 
`$response = oeHttp::usingBaseUri($Base)->get($uri); $file=$response->body;`
or
`$response = oeHttp::get($fileurl);`
etc
The client is easy to use but I do need to document it some. I use it with the FHIR client in the ClientAppController class in phpfhir directory. The client is set up to auto load already....

**Comment by danehrlich1** [comment]
1. @prondubuisi  Use `curl` in the few places where we `file_get_contents` actually goes out and grabs a URL (it's not that many compared to local retrievals). This will involve deleting your helper function sorry buddy :(

2. @danehrlich1 To investigate Robert's handy Symfony link and decide on best path forward for local file retrievals, of which there are TONS in the OpenEMR. Will create a separate issue on this. 

Anyone anything else to add?

**Comment by prondubuisi** [comment]
I would wait for us to reach a consensus on what is to be used. Using curl is ===  using the function [here](https://github.com/openemr/openemr/pull/2200), only that I will now have to introduce its implementation directly in every instance I want to replace file_get_contents(). Maybe I did not fully understand how you want the curl implemented. Also @robertdown @sjpadgett @bradymiller @danehrlich1  can we agree on using one of the suggestions above i.e Guzzle, $response = oeHttp::get($fileurl), curl etc

**Comment by sjpadgett** [comment]
I think what Robert, Dan and me are doing here is giving options. Doesn't mean you have to decide who is right but merely what you think the best approach would be to achieve this task, then defend it if necessary.
Just remember, while cURL is safe, Guzzle is safest. Also the context file_get_content is being used has bearing. Local files will be handled different than URL gets so validation of file paths should be a part of solution. We add new functions to our API's all the time and that most likely is the best route here so I look forward to where you land. Also, thanks for helping with these important issues.

**Comment by bradymiller** [comment]
hi @prondubuisi ,
Lets shoot for guzzle on the PR. Shouldn't be too tough since we already have the guzzle library available in OpenEMR. Check out my related post on the PR. -brady

**Comment by bradymiller** [comment]
done here: https://github.com/openemr/openemr/pull/2263
