### ISSUE TITLE
Version control for patient notes

### ISSUE THREAD

**Issue by gsarma** [openemr/openemr#1997]
One of the biggest complaints healthcare workers have with the current EMRs is the clutter of patient records.  Charts are filled with redundant information that has been copied and pasted from one provider to the next.  In an inpatient setting, patients can literally have _**hundreds**_ of useless tiny notes indicating that a nurse entered a room and performed some small task.  And all of these notes are effectively treated as individual text files.  Finding the information that one needs is often a rather time-consuming process. This has created a culture where trainees are actively taught to not trust the documentation of other providers, leading to an even greater proliferation of difficult to navigate free text.  

I've wondered for a long time if one way to address this problem is to introduce version control into the note-taking system.  How would this look? Many people use git + LaTeX to write scientific papers and this would be no different.  Here are a few principles that I think should inform the design of patient notes:  

1) _**There should be 1 overarching patient history**_: In the current system, every time a patient comes to a clinic or hospital, a healthcare worker writes a new patient history.  Why is this?  There should only be 1 global history.  Version control will allow that singular history to be updated and revised without losing the simplicity of having a single history for providers to navigate to. From a medico-legal standpoint, all of the documentation in the current systems will still be there, but it will be stored and presented in a much more streamlined manner that better reflects the purpose of the documentation to begin with.  

2) _**The EMRs should encourage a culture of consensus building among healthcare workers**_: As I said above, trainees in the medical system are often actively encouraged to not trust other providers' documentation. Incorporating version control should allow for providers to see each others' patient encounters as reliable information that can be revised in a clean way, rather than potentially unreliable information that needs to be re-written from scratch.  

3) _**The free text in EMRs should be useable for data science**_: The proliferation of notes with redundant, useless, or conflicting information in current patient records means that very little of value can be extracted from the free text of these systems.  Moreover, it means that the size of these records is a very misleading figure, because so much of the information is redundant (for example, radiological interpretations are often copied verbatim into every general medicine note).  EMRs of the future should be the data integration platforms which allow data science to be performed on anonymized patient records.  Therefore, a data scientist should be able to access the free text in a granular fashion, and only work with the tip of a commit history for sentiment analysis, entity extraction, or other NLP tasks.

**Comment by robertdown** [comment]
It's an interesting thought, but I'm not sure how we'd go about solving it. While I agree notes can load up _fast_, I'm not sure the EMR is the best domain to fix it; I feel if providers stopped copy/pasting previous notes it'd solve a lot of the problem.

Regarding number one: An overarching patient history would be great, in theory. I think some are looking towards the blockchain as the solution to this. I just have a master health record that anybody writes to no matter where I go. Unfortunately that's unlikely to see the light of day as there's incentive for each healthcare system to hold onto their data. Change doctors and they aren't part of "Acme Healthcare" well, you get a new record. Not saying I like it, but we are a long way from a healthcare-system-agnostic records; we've barely got FHIR worked out as an industry.

Number 2 - it's not that I don't trust what the previous nurse charted, I use it as a guide to drive my care; but when I chart something I'm putting my license on the line, every time; I want to chart everything I do so there's a clear record of the care I provided. I trust my coworkers, just not with my license.

Number 3 - this is where I think there *is* room for growth. We had a team doing some NLP work about a year ago. But I can't expect an NLP engine to determine if that conflicting information in the free text notes should be tossed out or flagged as a potential issue. What does _useless_ really mean in the context of free text notes? These are questions I don't readily have the answer to, but I'm glad to see someone is thinking about how we can leverage NLP with free text notes.

**Comment by gsarma** [comment]
Hi Robert,

Thanks so much for commenting on this thread.  I think I may need to spell out my thinking a bit more, so let me try to clarify by responding to your points/questions.  

> It's an interesting thought, but I'm not sure how we'd go about solving it. While I agree notes can load up _fast_, I'm not sure the EMR is the best domain to fix it; I feel if providers stopped copy/pasting previous notes it'd solve a lot of the problem.
> 
When you say "solving it" do you mean the problem of cluttered records or implementing version control?  My thought was that version control would help us create a workflow that would address the copy/pasting issue.  

> Regarding number one: An overarching patient history would be great, in theory. I think some are looking towards the blockchain as the solution to this. I just have a master health record that anybody writes to no matter where I go. Unfortunately that's unlikely to see the light of day as there's incentive for each healthcare system to hold onto their data. Change doctors and they aren't part of "Acme Healthcare" well, you get a new record. Not saying I like it, but we are a long way from a healthcare-system-agnostic records; we've barely got FHIR worked out as an industry.
> 

I think using version control to address this issue should be compatible with any number of other solutions, including blockchain.  My vision is a much more modest one.  When I say "one overarching patient history," it doesn't actually have to be a single history that is accessed globally by every hospital.  Even in the context of our current siloed systems, a given hospital could have one history for each patient.  

The idea behind using version control is that (see more below under Number 2) making a commit actually documents the user, which means that the situation does not actually change from a medico-legal standpoint.  If you make a commit without modifying another provider's text, then you are giving your seal of approval.  It's the exact same as the copy/paste situation, except that there isn't nearly as much clutter.  

> Number 2 - it's not that I don't trust what the previous nurse charted, I use it as a guide to drive my care; but when I chart something I'm putting my license on the line, every time; I want to chart everything I do so there's a clear record of the care I provided. I trust my coworkers, just not with my license.
> 

Exactly.  Nothing should actually change from a medico-legal standpoint with what I am suggesting.  If you don't agree with a previous provider's note, you can change it or make a new note that will then have its own history.  But because it is using version control rather than with a proliferation of separate notes, the chart will be much less cluttered and easier to access. 

Here is an analogy: when I was in high school, I wrote term papers in Microsoft Word.  Each time I made a substantive change, I would make a new version, so by the time the final version was due, I would have something like gopal_english_term_paper23.doc along with 22 other files.  

Nowadays, I do all my writing in LaTeX + git.  I have *many* more versions than I did before, except now, there is only one text file (i.e. the main LaTeX document) and what would have been a proliferation of files in my old Word-based system, now simply becomes the history of the document.  When I do collaborative writing, you can also see my co-authors' commits in the version history. 

What I am proposing for patient notes is the same.  It doesn't actually change a whole lot from a workflow standpoint, which is one of the virtues of doing it this way.  But the net result is much cleaner and should streamline finding information that a provider needs.  

> Number 3 - this is where I think there _is_ room for growth. We had a team doing some NLP work about a year ago. But I can't expect an NLP engine to determine if that conflicting information in the free text notes should be tossed out or flagged as a potential issue. What does _useless_ really mean in the context of free text notes? These are questions I don't readily have the answer to, but I'm glad to see someone is thinking about how we can leverage NLP with free text notes.

Having a cleaner patient record would definitely make NLP a lot more useful.  As a simple example, with the current systems, because there is so much copy/pasting and each note is a distinct object, simple concordance of words or entities in a patient's chart will be very misleading.  But if instead, you were using version control, you could simply use the most recent commit of any given file in a text processing task, which would likely reduce the overall data footprint of the record (not that data size in this context is necessarily an issue) in a way that is impactful for textual analysis.  

Hope this clarifies the idea a bit more.
