### ISSUE TITLE
Update out-of-date javascript assets

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2011]
There are some JS assets in `interface/modules`, `public`, and `library/js` that seem to be out of date by a couple of years and need to be updated. 

Question: Why don't we just load these libraries via `package.json`?

**Comment by danehrlich1** [comment]
I think the process will be:

1. Update any assets that point to the old versions of jquery hanging around to point to the new jquery that comes from the `package.json`
2. Delete the old assets

**Comment by bradymiller** [comment]
That is a good plan. See here for a related issue regarding the jquery stuff:
https://github.com/openemr/openemr/issues/842

**Comment by bradymiller** [comment]
(note @sjpadgett  had a good strategy that involves using a jquery compatibility module)

**Comment by danehrlich1** [comment]
Here are all the assets they seem to get added/compiled during build. Latest jquery version seems to be from 2016, with the oldest from 2008. Will need to update later / find out which we can delete:
@sjpadgett @bradymiller 
![jquery-openemr](https://user-images.githubusercontent.com/3357202/49606441-0240b200-f959-11e8-9f91-d5dcd4d36376.png)

**Comment by bradymiller** [comment]
hi @danehrlich1 ,

I updates the main summary of this PR with uptodate plan:
https://github.com/openemr/openemr/issues/842

Note I also did a tiny bit of cleanup here (https://github.com/openemr/openemr/commit/7487fc9505b6eb31f079edcd43301b74bad6d9de) just to fix a discrepancy where the actual jquery-1-2-2 is stored at public/assets/manual-added-packages/, so removed the one downloaded in the build.

**Comment by danehrlich1** [comment]
wow ok cool thanks @bradymiller

**Comment by bradymiller** [comment]
completed this in the ongoing bootstrap branch PR
