### ISSUE TITLE
Remove in-line <script></script> tags where possible

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2012]

**Comment by danehrlich1** [comment]
There are many places in the code that have unnecessary or longer needed <script> tags. For instance you'll see things like:

```
<script type="javascript">
</script>
```

This dead code can likely be removed. 

I have created this issue for anyone who wants to get a start with Open Source. I can provide additional instruction on this issue, and also if you want get you more involved in this PHP and Javascript project. Don't be afraid to reach out: dan@ehrlichserver.com

**Comment by harshlele** [comment]
Hey, I'm new to open source. Can I work on this?

**Comment by danehrlich1** [comment]
1. All yours, I’ll reserve it for you for a week.

1b. Can you write a bit about your background. Doesn’t matter if you don’t
have any experience just want to know what further help you may need.

2. Don’t have to do everything, just a good amount of instances. At least
15 edits would be the minimum though for your first pull request.

3. Let me know if you need any help with general coding, getting IDE setup,
github, etc.

4. Also also let me know if you’re trying to transfer into a job as a
software engineer in the US. I try to go to extra lengths to help those
people.


Thanks

**Comment by danehrlich1** [comment]
example in actual codebase: https://github.com/openemr/openemr/blob/bd4a9958bd64454c2cc3e4c3d9bf2e52de095e38/interface/main/tabs/main.php#L37

**Comment by harshlele** [comment]
Hey thanks for giving me this issue. Should i remove just empty inline script tags, or any inline script tag? (is there a way to check for sure that the removed javascript is unnecessary?)

> Can you write a bit about your background. Doesn’t matter if you don’t
have any experience just want to know what further help you may need.

I'm an electronics student from India. I have done software development before, but mostly in java/android. I'm looking to get more experience in web development and open source.

**Comment by danehrlich1** [comment]
1. Just Empty inline script tags

2.  think I posted an example above

3. You’re removing 100% dead code that does
nothing and is left over from a legacy codebase.

4. I’ll check your commits to make sure they don’t do anything

5. Can you fork the OpenEMR repo, do a couple of commits of changes to your
forked repo, and then I can look at it to make sure it’s good / doesn’t
affect anything else? Comment back on this issue when done and I’ll check!





<script type=text/JavaScript>

**Comment by harshlele** [comment]
Hey thanks for clarifying. I was confused, because I think the example you posted DOES have javascript inside the script tag(i think it ends at line 143: https://github.com/openemr/openemr/blob/bd4a9958bd64454c2cc3e4c3d9bf2e52de095e38/interface/main/tabs/main.php#L143)

I'll reply once I've made the commits in my fork.

**Comment by danehrlich1** [comment]
Wow I’m sorry and my mistake. Good catch.

Let me know if you have trouble finding others.

Also I have other issues I can start you with on the front-end later in a
day or two if you’re interested.

**Comment by harshlele** [comment]
Hey, I've committed a change: 
https://github.com/harshlele/openemr/commit/e4dca3ec0d367ea2df5b40287e0be176c4e98c7e

**Comment by danehrlich1** [comment]
Hey wow excellent work. I didn't think this would be all good to go on the first try. Can you open a pull request to the OpenEMR Repo?

We'll confirm the merge, and then congratulations you've just updated code for 30 million people :)

**Comment by danehrlich1** [comment]
NEXT STEPS:

1. Can you look for other spots where this is present in the code base?
2. Do you want other simple issues like this to work on?
3. Is there anything more challenging you'd like to work on long term? Like Javascript coding, PHP coding, etc?

@harshlele

**Comment by harshlele** [comment]
> Is there anything more challenging you'd like to work on long term? Like Javascript coding, PHP coding, etc?

Hey thanks for merging my PR. I'd like to work on javascript code. I'm looking to get more experience in frontend dev.
