### ISSUE TITLE
Random SQL stuff for Dan to Fix

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2035]
https://github.com/openemr/openemr/blob/b65513f601672ca7b9c1f8716277219f193377ae/sites/default/statement.inc.php#L556

https://github.com/openemr/openemr/blob/b65513f601672ca7b9c1f8716277219f193377ae/patients/add_edit_event_user.php#L132

https://github.com/openemr/openemr/blob/b65513f601672ca7b9c1f8716277219f193377ae/patients/add_edit_event_user.php#L139

https://github.com/openemr/openemr/blob/b65513f601672ca7b9c1f8716277219f193377ae/patients/add_edit_event_user.php#L309

https://github.com/openemr/openemr/blob/b65513f601672ca7b9c1f8716277219f193377ae/patients/add_edit_event_user.php#L321

https://github.com/openemr/openemr/blob/b65513f601672ca7b9c1f8716277219f193377ae/patients/add_edit_event_user.php#L330 .... LARGE NEXT 3 SECTIONS

RANDOM: https://github.com/openemr/openemr/blob/b65513f601672ca7b9c1f8716277219f193377ae/library/dicom_frame.php#L22

**Comment by danehrlich1** [comment]
LIBRARY FOLDER

/openemr-main/library/acl.inc, api.inc, billrep.inc, calendar_events.inc.php, clinical_rules.php, create_ssl_certificate.php, formdata.inc.php, lists.inc, log.inc, parse_patient_xml.php, spreadsheet.inc.php

library/classes/installer.class.php

# search for "sql" too next time full directory

**Comment by alejosv** [comment]
Why in some place they using  `sqlStatement` function and in other place `sqlQuery` function?

**Comment by bradymiller** [comment]
hi @alejosv ,

sqlStatement:
https://github.com/openemr/openemr/blob/master/library/sql.inc#L99
(this will return the recordset results handle for the entire query)

sqlQuery:
https://github.com/openemr/openemr/blob/master/library/sql.inc#L265
(this just returns one row in array form, so this is only specifically used when just collecting one row)
