### ISSUE TITLE
Theme stylesheet link href string

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#2040]
Logging a minor issue with user stylesheet href string : the version suffix is getting added twice.

`<link rel="stylesheet" href="/openemr/public/themes/style_powder_blue.css?v=42?v=42" type="text/css">`

**Comment by bradymiller** [comment]
hi @mdsupport ,
Are you seeing this on every script or on specific set of scripts?
-brady

**Comment by mdsupport** [comment]
Here is source of logon screen - `view-source:https://seven.openemr.io/openemr/interface/login/login.php?site=default`

`<link rel="stylesheet" href="/openemr/public/themes/style_forest_green.css?v=42?v=42" type="text/css">
`
Tried quick global search for `?v=` to locate source of the issue without luck.  Anyway browsers will ignore it.

**Comment by mdsupport** [comment]
Missed that one.  Thx.
