### ISSUE TITLE
aquabg.gif

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#2041]
Light theme contains few background urls

```
/* $GLOBALS['style']['HIGHLIGHTCOLOR'] */
.bottom_line {
  background: url("../pic/aquabg.gif") repeat;
}

```

When the themes are invoked from public/themes directory, link to interface/pic files is broken as shown below.

`https://seven.openemr.io/openemr/public/pic/aquabg.gif 404 (Not Found)`

Wouldn't it be better to remove reliance on gif and use standard background from bootstrap (e.g. bg-light)?

**Comment by bradymiller** [comment]
hi @mdsupport ,
Is there a way to get rid of these, but still leave control with the main style themes?
-brady

**Comment by mdsupport** [comment]
Prior to scss, background and repeat was only alternative to hard coded background colors.  Now define a variable in the scss, replace background by background-color attribute thru the definitions with value set to that variable.

Project will save lot of effort and gain maximum flexibility if we actually [start themes by following guide from BS team](https://getbootstrap.com/docs/4.1/getting-started/theming/).

**Comment by robertdown** [comment]
My recommendation is to yank those gifs, I'm upset they got by me when I setup light.
