### ISSUE TITLE
5.0.1 to 5.0.2 Sql Upgrade Fails (form_eye_mag_orders)

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2049]
Consistently fails with:
`ERROR: query failed: ALTER TABLE `form_eye_mag_orders` ADD UNIQUE `VISIT_ID` (`pid`, `ORDER_DETAILS`, `ORDER_DATE_PLACED`)
Error: Duplicate entry '1473--0000-00-00' for key 'VISIT_ID'`

Probably needs to be `ADD UNIQUE INDEX`
@ophthal You got this? I don't want to change unless something different is meant for this.

**Comment by sjpadgett** [comment]
A side note: The way the upgrade is set up if any item fails after form_eye_base is created then another run of sql_upgrade won't have a chance to complete the eye form upgrades because every item is enclosed in a  `#IfNotTable form_eye_base` conditional. I know its a pain but recm testing all items separately.

**Comment by sjpadgett** [comment]
@ophthal I've tested this with ADD UNIQUE INDEX and works as far as completing upgrade. I'm pretty sure KEY and INDEX are just synonyms so this fix should be good.

**Comment by bradymiller** [comment]
There was so much going on here, that I gave the advice (sounds like bad advice :) ) for making this all 1 nuclear step (ie. if form_eye_base is not yet there, then do it all). The upgrade works without data (ie. or else all the dev demos without data will fail), but it sound like it's breaking when there is real data in those forms; is that the issue?

**Comment by sjpadgett** [comment]
In this case, even if upgrade fails there isn't any adverse effect on OpenEMR proper running(although api prob shouldn't work). I too wondered about the demo farm which only brings me back to a concern i've had about our automated script upgrades/installs. Will the entire upgrade or install fail if the sql upgrade fails? I have to stop myself from running down these little mysteries as my energy is waning. :)
This may be a platform/mysql version issue but doubtful (I found on Windows/Maria 10.1.19/PHP7.1) but sure i've seen on Ubuntu. However it turns out why, best to use the proper syntax and not rely on the Unique keyword only(if that should even work).
Concerning entire upgrade enclosed within one test, I most likely would have gone that route too. It's concerning is all i'm saying. Also, i've tested by deleting all eye forms and installing from database.sql from 5.0.1 with same result during upgrade.

**Comment by bradymiller** [comment]
hi @sjpadgett ,

The sql upgrade script basically breaks and stops when there is an error. I know how to cheat a bit when checking this on the demos by looking a their setup log scripts :) Do a search for 'CREATE TABLE `api_token`' here and you will see what I mean:
https://seven.openemr.io/log/logSetup.txt
(the fact that the upgrade script got this far means that it didn't fail at the prior steps)

The demos are using mariadb 10.2, so am guessing may be a sql version issue. Either way, will need to fix this. Let me play around with this a bit (ie. so you can focus your energy on better things :) ).

-brady

**Comment by sjpadgett** [comment]
Okay thanks. My guess is version as well. This kind of stuff certainly keeps one on their toes. Nice logs @bradymiller

**Comment by sjpadgett** [comment]
thanks @bradymiller
