### ISSUE TITLE
Fix SQL Issues in these files

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2053]
sql-injection fixes in library/classes directory

SQL queries in the application need to use binded parameters.

Note, this application uses the ADODB library (basically an ORM): http://adodb.org/dokuwiki/doku.php

Please contact dan@ehrlichserver.com for more information on getting started.

**Comment by danehrlich1** [comment]
Please see this commit for changes that were made just like this to certain parts of the app: https://github.com/openemr/openemr/pull/1890/commits/35b409659b5f73582647f90cd00284c909f03475

Your task will be to find other parts of the app that need this update. Some of the SQL queries you'll find will be bizarre and not worth redoing (Brady Miller will probably need to closely look at the query to decide what to be done), but there should be at least a dozen, if not a few dozen quick wins to find in the code.

@bradymiller I had a request to create an issue for someone to get started on who saw some of the JS issues I posted for first timers which is why I created this issue.

**Comment by danehrlich1** [comment]
NOTE: for the first pull request, start in the `portal/` folder. If you go elsewhere you might end up doing work that has already been done by someone else in another pull request that hasn't been merged. I've checked and there are queries waiting to be fixed: https://github.com/openemr/openemr/tree/master/portal

**Comment by kacyw** [comment]
@danehrlich1 I might be missing something, but I've combed through the whole `portal` directory and can't find any sql queries that aren't using parameter binding, where appropriate.  Perhaps this issue was already resolved by someone else?

**Comment by bradymiller** [comment]
hi @kacyw,

Check out:
library/classes/Address.class.php
And then just start looking through all the scripts in that directory.

-brady

**Comment by kacy-weakley** [comment]
@bradymiller Yeah, I definitely found missing parameter binding in other directories.  I saw other sql parm binding tickets and didn't want to step on others' work.  @danehrlich1 specified `portal/` in this ticket, so that was where I looked for this issue.  If there isn't another ticket to comb through the `library` directory, I am happy take on that instead.

**Comment by kacy-weakley** [comment]
@bradymiller Actually, it does look like https://github.com/openemr/openemr/issues/2096 is specific to the `library` directory and has been assigned already.  Is there another directory I should take on instead?

**Comment by bradymiller** [comment]
hi @kacy-weakley (@kacyw),
At this point, the library directory is where most of the sql-injection action is(and to much for 1 dev). I changed the 2096 ticket to not include the library/classes, so it is all yours. When (and if) if you get sick of doing sql-injection just let me know, and I can find some other cool things to work on.
-brady

**Comment by kacy-weakley** [comment]
Sounds good.  Thanks!

**Comment by danehrlich1** [comment]
Looks Done
