### ISSUE TITLE
Feature-Policy and Other Things

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2064]
@harshlele 

NOTE: being a frontend dev is knowing Javascript, and it's also knowing how browsers work and interact with your code, how they render the DOM javascript manipulates, etc. Following stuff will help you with that. Will also send you a couple of good/quick PDFs to read after you're done with this issue.

1. Download OpenEMR 
2. Fix the follow security vulnerabilites in screenshot below by editing package.json and raising the version numbers. Does this affect the Javascript? Poke around in the application for a few  minutes to see if you get any errors (use Chrome Developer tools to help you spot errors).
2. Add a Feature-Policy header to the Apache Web Server with every option set to none. Does this break anything? Again use Chrome Developer Tools.

***

How to use Chrome Dev Tools: https://developers.google.com/web/tools/chrome-devtools/javascript/

Feature Policy: https://developers.google.com/web/updates/2018/06/feature-policy

Vulns to fix:
![jsgithub](https://user-images.githubusercontent.com/3357202/50388055-1ca4ba80-06d1-11e9-998e-5ab7996b32d0.png)

**Comment by harshlele** [comment]
Hey thanks for assigning me this issue. I'll submit a PR by the end of the week.

**Comment by danehrlich1** [comment]
Yes update it to the highest “minor” release. Going to 4 (“major”) would
100% break things so good you clarified.

https://semver.org/

**Comment by harshlele** [comment]
> Add a Feature-Policy header to the Apache Web Server with every option set to none. Does this break anything? Again use Chrome Developer Tools.

So I read about the Feature-Policy header, but what file do you actually add the headers in? I googled a bit about Apache, but I can't find any ".htaccess" file in the code

**Comment by bradymiller** [comment]
Hi @harshlele and @danehrlich1 ,

For docker and openemr dev environment, would rec this instead:
https://github.com/openemr/openemr/blob/master/CONTRIBUTING.md#code-contributions-local-development

That 5.0.2 docker posted above is only updated manually from most recent codebase every couple weeks. The docker mechanism I linked above will use most recent codebase (or any other github repo/branch of your choosing).

-brady

**Comment by bradymiller** [comment]
btw, agree that docker rocks :)

**Comment by sjpadgett** [comment]
If y'all want a good learning experience then take a look at the many synchronous Ajax functions scattered about and look to convert to asynchronous. Some of these are a bottle neck on through put and especially look at Demographics and widgets within. 
Promises are ideal for this.

**Comment by sjpadgett** [comment]
Another project. Seems the trend is to remove JQuery and use Javascript especially, if the leaning is to ES6 therefore, converting the many JQuery functions to Javascript could be very helpful.

**Comment by sjpadgett** [comment]
I don't know about Javascript as a focus but a good engineering exercise, especially for learning, is that we sorely need to have portions of OpenEMR profiled focusing on finding definitive bottle necks in our through put. Here a concentration on looking at Demographics as a major source of slow downs next to Calendar.
My opinion is that though we want to move towards a truer MVC pattern, inevitably, a major rewrite is going to be required for all our views. Once we can ever agree on what we want to use for view and models(I think Robert is looking into ES6 and web components which may be best route), profiling will be a great resource for new designs so we can avoid the same mistakes. Not glamorous but good practice.

**Comment by danehrlich1** [comment]
Ok super interesting. Just sent you an email Jerry for a couple of follow questions.

**Comment by bradymiller** [comment]
hi @sjpadgett , @danehrlich1 , @harshlele ,

I've been concentrating on migrating to new jquery version for last month or so (have gotten rid of 5 or 6 versions at this point i think):
https://github.com/openemr/openemr/issues/842

And some things I've noted:
1. jquery-ui and jquery related packages are dying (for example, jquery-ui last release was 2 year ago and last commit to their github repo was 18 months ago!)
2. Agree this doesn't bode well for jquery's future (still a commit on their repo several times per month)

Goal at this point is to get all the jquery's to most recent jquery version (then will begin to drop jquery-ui support). On the jquery front, a good very specific js exercise would be to drop use of qtip2 in the following script (it breaks with most recent jquery and qtip2 is a dead project):
https://github.com/openemr/openemr/blob/master/interface/main/display_documents.php#L45

Objective:
1. Create that tooltip with pure js (ES6). Note this will also drop reliance on the jquery-ui in that script and allow use of most recent jquery. And we can then leverage this mechanism for a couple other places that use qtip2.

To see that script at work in OpenEMR:
1. create a patient
2. go to patient dashboard->Documents
3. add a jpg image to the Lab Report category
4. In OpenEMR menu, go to Procedures->Lab Documents
![image](https://user-images.githubusercontent.com/278968/50458141-c1afd500-0915-11e9-855f-4ea0b80730ed.png)
5. Hover over your filename
![image](https://user-images.githubusercontent.com/278968/50458147-cf655a80-0915-11e9-8158-db2422ff6bf4.png)
6. Click on the image in the tooltip (it zooms in):
![image](https://user-images.githubusercontent.com/278968/50458160-ea37cf00-0915-11e9-89fe-cb84f04a0ed6.png)

-brady

**Comment by danehrlich1** [comment]
@harshlele start working on #2071.  Feel free to ask questions on that issue thread if you run into issues. You can commit what you have now regarding updating the `package.json` for this issue and we'll bring it in.

**Comment by harshlele** [comment]
Made a PR for the package.json updates:
https://github.com/openemr/openemr/pull/2073

I'll work on #2071 now

**Comment by robertdown** [comment]
> 
> 
> So for bootstrap, I should update it to 3.3.7, and not bootstrap 4 right? (because afaik bootstrap 4 isn't backwards compatible with 3?)

Correct, as of right now we are locked into Bootstrap 3.
