### ISSUE TITLE
Create Javascript Feature That Replaces qtip2

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2071]
hi @sjpadgett , @danehrlich1 , @harshlele ,

I've been concentrating on migrating to new jquery version for last month or so (have gotten rid of 5 or 6 versions at this point i think):
https://github.com/openemr/openemr/issues/842

And some things I've noted:
1. jquery-ui and jquery related packages are dying (for example, jquery-ui last release was 2 year ago and last commit to their github repo was 18 months ago!)
2. Agree this doesn't bode well for jquery's future (still a commit on their repo several times per month)

Goal at this point is to get all the jquery's to most recent jquery version (then will begin to drop jquery-ui support). On the jquery front, a good very specific js exercise would be to drop use of qtip2 in the following script (it breaks with most recent jquery and qtip2 is a dead project):
https://github.com/openemr/openemr/blob/master/interface/main/display_documents.php#L45

Objective:
1. Create that tooltip with pure js (ES6). Note this will also drop reliance on the jquery-ui in that script and allow use of most recent jquery. And we can then leverage this mechanism for a couple other places that use qtip2.

To see that script at work in OpenEMR:
1. create a patient
2. go to patient dashboard->Documents
3. add a jpg image to the Lab Report category
4. In OpenEMR menu, go to Procedures->Lab Documents
![image](https://user-images.githubusercontent.com/278968/50458141-c1afd500-0915-11e9-855f-4ea0b80730ed.png)
5. Hover over your filename
![image](https://user-images.githubusercontent.com/278968/50458147-cf655a80-0915-11e9-8158-db2422ff6bf4.png)
6. Click on the image in the tooltip (it zooms in):
![image](https://user-images.githubusercontent.com/278968/50458160-ea37cf00-0915-11e9-89fe-cb84f04a0ed6.png)

-brady

_Originally posted by @bradymiller in https://github.com/openemr/openemr/issues/2064#issuecomment-450032073_

**Comment by harshlele** [comment]
Hey thanks for assigning me this issue.

**Comment by sjpadgett** [comment]
@bradymiller What type of lab documents are images these days? I just finished Quest and LabCorp cert and didn't run across any images. Maybe xray or something? I'm just curious.

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Agree not much; pictures of stuff like rashes and skin lesions, though, will be images. Thanks for your question, though, since it reminded me to ensure this feature worked with PDF :)

**Comment by sjpadgett** [comment]
@bradymiller It appears we no longer generated the bootstrap min versions both js and css. Noted today testing portal and then checked on demo farm.

**Comment by sjpadgett** [comment]
I found them. weird
