### ISSUE TITLE
ARO not created during setup

### ISSUE THREAD

**Issue by jackrosenthal** [openemr/openemr#2076]
A phpGACL ARO is not created for the default admin user during setup. I mentioned this in #2075 .

I used the username ``emradmin`` (rather than the default ``admin``) and made a separate group for the default admin. I am not sure if this has to do with it.

**Comment by bradymiller** [comment]
hi @jackrosenthal ,

OpenEMR comes installed with 6 AROs:
https://github.com/openemr/openemr/blob/master/acl_setup.php#L221-L236

And on install, the user should be set as the initial default user, and should be added to the Administrator ARO:
https://github.com/openemr/openemr/blob/master/acl_setup.php#L244-L251

-brady

**Comment by jackrosenthal** [comment]
ARO object for the user -- not groups. Sorry.

Perhaps ``$this`` was not set a few lines below when it creates the admin user ARO. I have not investigated fully...
