### ISSUE TITLE
Cleanse qtip2 from the codebase

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2083]
In order to get OpenEMR to use just a modern jquery package, we need to remove qtip2 from the project(also, qtip2 is no longer maintained, so another reason to move away from it). It's only used in a couple scripts and the use appears minimal. Can find the scripts by searching (recursively) for qtip in the interface/forms/eye_mag directory.

This code here is actually for a really cool modern looking eye form/module, which you can see if:
1. Create a patient
2. Create an encounter
3. On the encounter menu, go to Clinical->Eye Form

**Comment by harshlele** [comment]
I just commented out qtip in some of these files, and it seems the browser tooltip shows the label title by default. So should i create my own tooltip in those places, or just let the browser tooltip be?

**Comment by bradymiller** [comment]
hi @harshlele ,
If it looks fine, then can just go with the browser one. When your PR is up, then we can test it and do more analysis on it.
-brady

**Comment by harshlele** [comment]
@bradymiller 
In this commit i've just commented out all instances of qtip2 use. I tested it a bit and it works fine as far as i can tell, but the UI is pretty complex so i thought just commenting it out would be better instead of completely removing it. Once you've tested it i'll remove it.

**Comment by bradymiller** [comment]
This issue is officially complete. Thank you @harshlele !
