### ISSUE TITLE
Delete Old Code

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2088]
@bradymiller Going to keep this issue open/recurring to ask about non-used old code and if it can be deleted.

**Comment by danehrlich1** [comment]
1st: Can some of these files be deleted? Does any function leverage them? One of them says it is 11 years old (!)

https://github.com/openemr/openemr/tree/88e7957cc479d89bf896df6861743205957890f2/library/classes/smtp

**Comment by robertdown** [comment]
Best way to see would be to go through those files, find the class names (`sasl_interact_class` as an example) and then grep the source code for any instances of that class. None found? Bye! Even 1 usage found? Well, time to investigate.

**Comment by robertdown** [comment]
Whenever grepping, definitely don't forget to ignore the `vendor` directory and `public` directory, no need to even look in those
