### ISSUE TITLE
Strengthen part of username and password creation process

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2090]
This file is called when a user begins setting up OpenEMR for the first time: https://github.com/openemr/openemr/blob/master/setup.php

Make the following happen via HTML5 attributes:
- initial user password min length of 12
- database  password min length of 12

Also:
- the "initial user" of "admin" is too easy to guess
- write a PHP function (or Javascript function, can be on the front end that is fine) that generates 3 random letters  + "-admin-"  + 2 random numbers
- e.g: HLV-admin-87
- then take this functions output and fill in the HTML for "initial user"
- This will make bruteforce attacks against the login page approximately 1,700,000 harder at no real cost to the user (50%  less extra characters than SSN or Phone Number)
- make the username a minimum of 12 characters as well to ensure if they don't go with our randomized suggestion they still pick something with some complexity (enforce with html5)

**Comment by danehrlich1** [comment]
![openemr7](https://user-images.githubusercontent.com/3357202/50577711-aa7c5600-0df3-11e9-84f1-95eedbcacc12.png)

**Comment by alpha-gamma** [comment]
I would like to take this up.

**Comment by danehrlich1** [comment]
reserved for you for the next week.

Thanks @alpha-gamma

**Comment by danehrlich1** [comment]
@alpha-gamma Last thing. After you're done, if you enjoy working on this let us know. Can always create more issues like this that are meant for people new to the project.

**Comment by alpha-gamma** [comment]
@danehrlich1 Should I update the help text message as well against the password fields?

![image](https://user-images.githubusercontent.com/1653101/50587701-ed4a3680-0ea4-11e9-8398-3ee055763b9c.png)

**Comment by bradymiller** [comment]
hi @alpha-gamma ,
Yes, I would do that also (btw @danehrlich1 is out of town for couple days, and I'm happy to answer any questions and review the code).
thanks, -brady

**Comment by alpha-gamma** [comment]
@bradymiller Thanks for your input. I have created the PR.
I really enjoyed working on it and would like to contribute more to the project.

**Comment by bradymiller** [comment]
Hi @alpha-gamma ,

Nice work on the above code, which I just brought into codebase. Since we are here, the following would also make sense:
-Add a duplicate entry for each of the 2 password entries.
-Add realtime js to ensure that 2 passwords are incorporating numbers/letters/more than 12 chars/duplicate match.

If you don't want to work on this, just let me know, and I can point you to other things to work on (just let me know what you are interested in).

-brady

**Comment by alpha-gamma** [comment]
Yep, it totally makes sense. I can work on it.

For validation, do we check for numbers and letters only or should we include checks for uppercase and lowercase letters as well?

**Comment by bradymiller** [comment]
Lets go all out and ensure both uppercase and lowercase letters :)
