### ISSUE TITLE
Tag globals (ie. settings) that should be encrypted

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2094]
We now have a very cool mechanism to encrypt globals (ie. settings) in the Administration->Globals settings (also does the User settings), by making the data type encrypted.

Here is an example (SMTP_PASS setting) that is now in codebase to show how it works:
https://github.com/openemr/openemr/blob/master/library/globals.inc.php#L1998

And then when it is used in codebase, it gets decrypted:
https://github.com/openemr/openemr/blob/master/library/classes/postmaster.php#L45

So this project will consist of 2 steps:
1. Identify which sensitive globbals/settings should be encrypted at Administration->Globals
(note these come from the https://github.com/openemr/openemr/blob/master/library/globals.inc.php script)
2. Then will set the chosen ones to have encrypted data type and ensure they are decrypted where used in codebase.

**Comment by danehrlich1** [comment]
Quick question, why aren’t the Global stored
in the database?

What decides if something goes in globals or the database?

Current code is fine, but I always wondered that.

**Comment by JonathanKoester** [comment]
So, for step 1, I'm assuming I would add the tag the same way as was in the example. Do you have any advice on identifying which globals/settings are considered sensitive?

For step two, I was thinking I could just use grep to search for instances where the globals are used and ensure they are decrypted as in the example.

**Comment by bradymiller** [comment]
hi @JonathanKoester ,

For step 1, rec reading through this and just flagging the obvious items (maybe with word password in it):
https://www.open-emr.org/wiki/index.php/Administration_Globals
(oh my goodness, i just did a quick mental count, and we have about 400 globals :) )
Could even just pick 1 of the password field for now just to go through the process.

And agree with your plan for step 2 (these sensitive globals are likely only used in 1 or 2 places, so shouldn't be too tedious).
-brady

**Comment by JonathanKoester** [comment]
I have one more question! I've noticed that some of the globals have pass or pwd as their data type. Should I change those to encrypted too or have those otherwise been encrypted? From what I can tell, I would assume I need to change it to encrypted I just wanted to make sure. Thanks!

**Comment by bradymiller** [comment]
hi @JonathanKoester ,
I just looked at this.
We should stay away from the 'pwd' entry (this is just 1 entry which actually hashes the value and stores the hash; a bit odd, but can't change since is used for a portal beyond our control).
We can definitely change the 2 `pass` entries to encrypted, though :)
-brady

**Comment by bradymiller** [comment]
Actually, we could even change the pwd one, but that will be more difficult. We'll do that one later after successfully get through the first run of settings.

**Comment by JonathanKoester** [comment]
Okay, thank you for the help. I'll try to finish this up tomorrow.

**Comment by bradymiller** [comment]
Issue completed. Thank you @JonathanKoester !! -brady

**Comment by bradymiller** [comment]
hi @JonathanKoester ,
If you are interested in a nice follow up and related project to work on, then check out this issue:
https://github.com/openemr/openemr/issues/2126
-brady
