### ISSUE TITLE
When typing date for entering DOB or other date values, it must be entered as SQL format (YYYY-MM-DD), if not then it reverts to today’s date.

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2116]
https://community.open-emr.org/t/still-several-issues-after-openemr-upgrade-to-5-0-1/11316?u=stephenwaite

**Comment by sjpadgett** [comment]
Hi @stephenwaite This is really not an issue. The action for the datepicker for manual typed dates is based on how 'Time Display Format' is set in Globals Locale. If display date is xx/xx/xxxx and you enter xxxx-xx-xx it(plug-in) will give up parsing the date to the default format template.

**Comment by bradymiller** [comment]
I'm also a bit confused on this issue. Is it standard to support YYYYMMDD entry when using the YYYY-MM-DD format?

**Comment by stephenwaite** [comment]
ok thanks @sjpadgett
