### ISSUE TITLE
Restore Function

### ISSUE THREAD

**Issue by atifmian** [openemr/openemr#2129]
I am getting the following error using the restore function.

I followed the instructions and copied the emr_backup.tar and Restore in the /home/ubuntu directory.
Using ubuntu 16.4 on AWS

ubuntu@ip-172-31-33-155:~$ sudo ./restore
WARNING: This script is experimental.
It may have serious bugs or omissions.
Use it at your own risk!
Now you will be asked for the backup file.
By default this is named emr_backup.tar, although you may have saved it as something else.

Enter path/name of backup file: /home/ubuntu/emr_backup.tar

Extracting /home/ubuntu/emr_backup.tar …
tar: Substituting `.’ for empty member name
Extracting /tmp/emr_backup/openemr.tar.gz …

Do you want to specify site ID, locations or database names for the restore? [N/y] y
Current values are shown in [brackets]. Just hit Enter to leave them as-is.
Site ID [default]?
OpenEMR database name [openemr]?
OpenEMR database user [openemr]?
OpenEMR database password [xxxxxxxxxx]? xxxxxxxxx
New OpenEMR web directory [/var/www/openemr]?

Error: Site ‘default’ already exists in ‘/var/www/openemr/sites’.

any help

thanks

**Comment by atifmian** [comment]
I changed the name and then it says directory does not exist

**Comment by sunsetsystems** [comment]
The target directory (in your example /var/www/openemr) is not supposed to exist, unless you are restoring a site other than default in a multi-site installation.

**Comment by atifmian** [comment]
Thanks for the help

that WORKED!!

IS there a script that will auto backup at the end of the day and save it to S3?

**Comment by sunsetsystems** [comment]
This might help:

https://www.open-emr.org/wiki/index.php/Automated_Backups_to_an_Alternate_Server

In addition I have used s3cmd to archive backups to Digital Ocean "spaces".

https://www.digitalocean.com/docs/spaces/resources/s3cmd/
https://www.digitalocean.com/docs/spaces/resources/s3cmd-usage/
