### ISSUE TITLE
Harden against XSS 

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2145]
Perfectly hardened example script: https://github.com/openemr/openemr/blob/master/interface/reports/pat_ledger.php

Hardens text - text():
https://github.com/openemr/openemr/blob/master/interface/reports/pat_ledger.php#L680

Hardens code in html tags / attributes - attr():
https://github.com/openemr/openemr/blob/master/interface/reports/pat_ledger.php#L824

Hardens code in text that also is language / location specific - xlt():
https://github.com/openemr/openemr/blob/master/interface/reports/pat_ledger.php#L758

Hardens code in html tags / attributes that also is language / location specific - xla():
https://github.com/openemr/openemr/blob/master/interface/reports/pat_ledger.php#L581

Unknown - js_escape():
https://github.com/openemr/openemr/blob/master/interface/reports/pat_ledger.php#L945

Unknown - xlj():
https://github.com/openemr/openemr/blob/master/interface/reports/pat_ledger.php#L383

Here's the documentation that covers this:
https://www.open-emr.org/wiki/index.php/Codebase_Security#Cross-Scripting_Prevention

Here's the library with these functions:
https://github.com/openemr/openemr/blob/master/library/htmlspecialchars.inc.php

**Comment by danehrlich1** [comment]
@morg0n This is going to be a better issue later on for sure. Need to talk with Brady and give better instructions, but it's about sanitizing code to protect against XSS attacks. There is tons of work here so probably will split this up into at least 5 issues to give them to different people.

For now would just study XSS attacks it's the ultimate security / cyber  thing to know...

**Comment by bradymiller** [comment]
If anybody has interest in this, just let me know, and I'll direct you to some scripts to work on. This is actually a really good way to quickly become a effective "code reviewer" since many of the corrections in the code reviews I do involve these functions to prevent cross scripting attacks.

**Comment by flockclock** [comment]
Hi. I am interested.

**Comment by bradymiller** [comment]
hi @flockclock ,
See here for a good issue to start on this:
https://github.com/openemr/openemr/issues/2157

**Comment by david-vu** [comment]
Hello @bradymiller.  I could work on files too.  Thanks!

**Comment by bradymiller** [comment]
hi @david-vu ,
See here for a good issue to start on this:
https://github.com/openemr/openemr/issues/2161

**Comment by danehrlich1** [comment]
Good additional instructions and examples: https://github.com/openemr/openemr/issues/2169#issuecomment-460129695

**Comment by morg0n** [comment]
@danehrlich1 do I have enough battle XP for this one yet?

**Comment by danehrlich1** [comment]
@bradymiller @morg0n This is a good one. Did we put enough instructions? I can't remember if we detailed the how-to for ppl on how to do this...

**Comment by bradymiller** [comment]
hi @morg0n , @danehrlich1 , We are running low on places that need XSS fixes. Let me see if I can find any.

**Comment by danehrlich1** [comment]
@bradymiller Yeah that's what I'm thinking and I just mentioned in another comment.
