### ISSUE TITLE
Fix online drug lookup

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2156]
This is a drug lookup that scrapes a website, which breaks relatively frequently. If can not get it to work from rxlist website, then may need to change to site that offers api/json (like https://rxnav.nlm.nih.gov/ ). Code is here:
https://github.com/openemr/openemr/blob/master/library/classes/RXList.class.php#L43

Can see in OpenEMR if go to Patient Summary Screen-> Edit prescription -> Add -> Click '(click here to search)'

**Comment by eyalvo-matrix** [comment]
Hi, @bradymiller  would you consider replacing rxlist with truemd ? 
replace the following URL 
http://www.rxlist.com/script/main/srchcont_rxlist.asp?src=metadon
with 
http:/www.truemd.in/api/v2/medicines.json?key=7f556015a882f1e1b70779e35723b182&search=metadon
and do the adaption , I am willing to volonteer

**Comment by caperneoignis** [comment]
Forgive my ignorance, but the price in the response data is in what currency and is there a difference between the two APIs?

**Comment by eyalvo-matrix** [comment]
hi @caperneoignis  "TrueMD started as a search engine to help people search for generic medicines or cheaper branded substitutes of the medicines they are already using. The team then decided to start a full-fledged Online Pharmacy. However, the founders soon realized that a B2B product in this space is better than a B2C product. Hence, TrueMD later morphed into HealthOS — an API based platform for medicine and fitness data." (medium.com) . if I am not mistaken prices are in rupee (India)

**Comment by eyalvo-matrix** [comment]
For US users I think it is better to use 
https://mor.nlm.nih.gov/download/rxnav/RxNormAPIs.html
OR
http://usgovxml.com/DataService.aspx?ds=DMEDWS

**Comment by eyalvo-matrix** [comment]
hi @bradymiller I need a real doctor help here :) 
when I get for the search term  "zocor"
https://rxnav.nlm.nih.gov/REST/approximateTerm?term=zocor&maxEntries=6
I get a list of rxcui (196503,196503,196503,1187974,1187973)
and then if I get the info for one of them 
https://rxnav.nlm.nih.gov/REST/rxcui/196503/allProperties.json?prop=all
I get something that is hard for me to identify the Brand Name,Generic Name,Drug Class 
any ideas?

**Comment by caperneoignis** [comment]
Not a real doctor, however if you are modifiying the code, I'd break down the json statement. 

````
{"propConceptGroup":{"propConcept":[{"propCategory":"ATTRIBUTES","propName":"TTY","propValue":"BN"},
{"propCategory":"ATTRIBUTES","propName":"PRESCRIBABLE","propValue":"Y"},
{"propCategory":"ATTRIBUTES","propName":"BN_CARDINALITY","propValue":"single"},
{"propCategory":"ATTRIBUTES","propName":"GENERAL_CARDINALITY","propValue":"SINGLE"},
{"propCategory":"CODES","propName":"RxCUI","propValue":"196503"},
{"propCategory":"CODES","propName":"UMLSCUI","propValue":"C0678181"},
{"propCategory":"CODES","propName":"MESH","propValue":"D019821"},
{"propCategory":"CODES","propName":"MMSL_CODE","propValue":"BN1546"},
{"propCategory":"NAMES","propName":"RxNorm Name","propValue":"Zocor"},
{"propCategory":"SOURCES","propName":"Source","propValue":"Multum MediSource Lexicon"},
{"propCategory":"SOURCES","propName":"Source","propValue":"Medical Subject Headings"}]}}
````
You have 4 property categories, you have: Attributes, Codes, names, and sources. 

It does not look like this code returns a generic name, it does return Zocor which is the brand name, the drug class, may be in one of those other codes you might have to do an additional look up? 

That is my guess, however, an actual doctor/pharmacist might know through one of the codes. Hopefully that helped and I didn't just restate the obvious.

**Comment by bradymiller** [comment]
hi @eyalvo-matrix ,
I also had a tough time playing around with the https://rxnav.nlm.nih.gov site to get something like what the rxlist site did. Guessing it is in there somewhere.

**Comment by bradymiller** [comment]
The displaynames that "Return the auto suggestion names" looks promising.

**Comment by efleisc** [comment]
rxnav.nlm.nih.gov is definitely the best source for the drug lookup as it is very complete, monthly updated and the REST API is fast and reliable.

We changed the RXList.class.php code to support RXNAV, and it is working great.  Just replace your RXList.class.php code with the php below and then when you search for any drug you will get a list with these elements:
DisplayName == (Synonym / rxcui).

<?php
 // $Id$
 // $Author$
 //
 // $Log$

// Revision 1.6  2019/02/18  Avanss LLC
// replaced rxlist API with rxnav.nlm.nih.gov

 // Revision 1.5  2016/02/016   sherwin gaddis
 // fix broken url

 // Revision 1.4  2008/05/09 20:10:28  cfapress
 // Changes to handle to HTML returned by rxlist.com
 //
 // Revision 1.3  2007/06/19 02:34:45  sunsetsystems
 // drug lookup fix from Sam Rajan
 //
 // Revision 1.2  2005/12/27 00:45:19  sunsetsystems
 // fix broken url
 //
 // Revision 1.1.1.3  2005/06/23 05:25:49  drbowen
 // Initial import.
 //
 // Revision 1.1.1.2  2005/03/28 00:44:54  drbowen
 // Initial import.
 //
 // Revision 1.1.1.1  2005/03/09 19:59:43  wpennington
 // First import of OpenEMR
 //
 // Revision 1.2  2002/08/06 13:49:08  rufustfirefly
 // updated rxlist class for changes in RxList.com
 //
 // Revision 1.1  2002/07/08 14:42:25  rufustfirefly
 // RxList.com prescription "module" for formulary
 //

if (!defined('__CLASS_RXLIST_PHP__')) {
    define('__CLASS_RXLIST_PHP__', true);

    class RxList
    {

        function getPage($query)
        {
            $url = "https://rxnav.nlm.nih.gov/REST/Prescribe/drugs?name=".$query;

            urlencode($query);

            if (!($fp = fopen($url, "r"))) {
                // If we fail to get the page, return false
                return false;
            } else {
                // Get the page
                $buffer = 0;
                while (!feof($fp)) {
                    $buffer .= fgets($fp, 4096);
                }

                fclose($fp);
                return $buffer;
            } // end checking for successful open
        } // end function RxList::getPage

        function get_list($query)
        {
            $page = RxList::getPage($query);
            $tokens = RxList::parse2tokens($page);
            $hash = RxList::tokens2hash($tokens);
            foreach ($hash as $index => $data) {
                unset($my_data);
                foreach ($data as $k => $v) {
                    $my_data[$k] = $v;
                }

                $rxcui = '';

                if (trim($my_data[rxcui]) !== '') {
                    $rxcui = " / ".trim($my_data[rxcui]);
                }

                $synonym = '';
                if (trim($my_data[synonym]) !== '') {
                    $synonym = " == (".trim($my_data[synonym]).$rxcui.")";
                }

                $list[trim($my_data[name]).$synonym] =
                trim($my_data[name]);
            }

            return $list;
        } // end function RxList::get_list

        /* break the web page into a collection of TAGS
         * such as <input ..> or <img ... >
         */
        function parse2tokens($page)
        {
            $pos = 0;
            $token = 0;
            unset($tokens);
            $in_token = false;
            while ($pos < strlen($page)) {
                switch (substr($page, $pos, 1)) {
                    case "<":
                        if ($in_token) {
                            $token++;
                            $in_token = false;
                        }

                        $tokens[$token] .= substr($page, $pos, 1);
                        $in_token = true;
                        break;

                    case ">":
                        $tokens[$token] .= substr($page, $pos, 1);
                        $in_token = false;
                        $token++;
                        break;

                    default:
                        $tokens[$token] .= substr($page, $pos, 1);
                        $in_token = false;
                        break;
                } // end decide what to do
                $pos++;
            } // end looping through string
            return $tokens;
        } // end function RxList::parse2tokens

        function tokens2hash($tokens)
        {
            $record = false;
            $current = 0;
            unset($hash);
            $hash = [];
            unset($all);
            for ($pos=0; $pos<count($tokens); $pos++) {
                if (!(strpos($tokens[$pos], "<name>") === false) && $pos !== 3) {
                            // found a brand line 'token'
                    $type = "name";
                    $record = $pos;
                    $ending = "</name>";
                }

                if (!(strpos($tokens[$pos], "<synonym>") === false)) {
                            // found a generic line 'token'
                    $type = "synonym";
                    //print "generic_name record start at $pos<BR>\n";
                    $ending = "</synonym>";
                    $record = $pos;
                }

                if (!(strpos($tokens[$pos], "<rxcui>") === false)) {
                            // found a drug-class 'token'
                    $type = "rxcui";
                    $ending = "</rxcui>";
                    $record = $pos;
                }

                if (isset($hash["synonym"])) {
                    // Reset record
                    $record = false;
                    // Add hash to all
                    $all[] = $hash;
                    // Unset hash and type
                    unset($hash);
                    $type = "";
                    $ending = "";
                }

                if ($pos === ($record + 1) and ($ending != "")) {
                        $my_pos = strpos(strtoupper($tokens[$pos]), "<");
                        $hash[$type] = substr($tokens[$pos], 0, $my_pos);
                        $hash[$type] = str_replace("&amp;", "&", $hash[$type]);
                        //print "hash[$type] = ".htmlentities($hash[$type])."<BR>\n";
                        $type = "";
                        $ending = "";
                }
            } // end looping
            return $all;
        } // end function RxList::tokens2hash
    } // end class RxList

} // end if not defined

**Comment by efleisc** [comment]
The link above expired. Here is a new one:
https://pastebin.com/gh9GhEqs

Again just copy and paste the file above and replace the contents of /library/classes/RXList.class.php

**Comment by sjpadgett** [comment]
@bradymiller Can we assign this to one of our eager new dev's. Sounds like @efleisc may have a handle on this. I'd do it but lack time however, i'll keep an eye on the integration PR.

**Comment by bradymiller** [comment]
hi @sjpadgett and @efleisc ,

I posted he code on this PR:
https://github.com/openemr/openemr/pull/2255

Plan to test it soon.

Also, @efleisc , let me know what username and email you want me to use for the commit author. thanks, -brady

**Comment by bradymiller** [comment]
just brought the fix by @efleisc into the codebase. thanks @efleisc !

**Comment by sjpadgett** [comment]
@bradymiller lol, well I did keep an eye on the PR as promised! Thanks for doing this it was sorely needed.
Thanks @efleisc also.

**Comment by efleisc** [comment]
No worries. I am glad it helps!
