### ISSUE TITLE
XSS fixes in interface/orders/orders_results.php

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2161]
Related to this issue:
https://github.com/openemr/openemr/issues/2145

**Comment by bradymiller** [comment]
@david-vu is working on this

**Comment by danehrlich1** [comment]
Good additional instructions: https://github.com/openemr/openemr/issues/2169#issuecomment-460129695

**Comment by danehrlich1** [comment]
David Vu are you still working on this?

**Comment by VutifulJoe** [comment]
> David Vu are you still working on this?

Hello Daniel, yes still working on this.  I just noticed there was additional instructions to get me in the general direction.  I should be able to complete it soon.

**Comment by morg0n** [comment]
Should I consider hopping in here?

**Comment by VutifulJoe** [comment]
Hi @morg0n feel free to hop in.  I finished this a while ago on my local machine.  But never been able to push up my code (account/permission issues).  Little busy to figure it out and won't have time.  So feel free to take it!  Thank you!

**Comment by morg0n** [comment]
Thanks heaps, I'll get started :) !

**Comment by david-vu** [comment]
Hi @morg0n feel free to hop in. I finished this a while ago on my local machine. But never been able to push up my code (account/permission issues). Little busy to figure it out and won't have time. So feel free to take it! Thank you!
