### ISSUE TITLE
User Debug Feature

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2166]
I've written a feature to allow users to turn on debugging that will report php and javascript errors to the interface. Php will have options to turn on display_errors(apache) or display in dialog(both errors only). Window errors will be a synchronous alert. A promise alert is too risky due to possible race conditions.
I use this while debugging and it proves very helpful but mainly for IT with/or users that don't know how to use console and/or retrieve php errors from log. If they have an issue then they can turn debug on to report findings. I'm surprised this hasn't been done already but it may have been and abandon for reasons i'm not seeing. Seeking comments.

**Comment by bradymiller** [comment]
sounds good to me :)

**Comment by sjpadgett** [comment]
Implemented here: https://github.com/openemr/openemr/pull/2174
Turned on at `Administration->Globals->Logging->User Debugging Options`
- Option `Display Window Errors Only `  Will alert user on most JavaScript errors in most modules in OpenEMR.
- Option `Display Application Errors Only` Will turn on apache display_errors property to display to screen PHP errors only and still log to error log.
- Option 'All' Well guess :)
I find this feature very handy when trying to work with users whom may not have knowledge of error log locations or use of browser console. Also nice when trouble shooting or in development.
It is not necessary to restart apache but recommended to log out then back in when turning off Window Errors. PHP errors will toggle on/off okay.

**Comment by bradymiller** [comment]
very nice! looking forward to trying this out.
