### ISSUE TITLE
Replace certain instances of document.write and innerHTML

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2172]
Certain instances of document.write and innerHTML can probably better be served by switching to the new textContent method: https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent. This is faster by an order of magnitude and more secure.

For other instances where variables are used along with document.write and innerHTML some kind of purification or sanitization should occur (I think). Will need to study code more. Maybe use a library? https://github.com/cure53/DOMPurify

Will update this issue later (within 2 weeks) with more information and hopefully it can be good beginner issue. If you consider yourself intermediate Javascript ninja then feel free to email me now: dan@ehrlichserver.com

**Comment by joshuaaguilar20** [comment]
Dan, 

I am  a full time software engineer and  RN BSN. I really would love to get enveloped in the project and had actually started building one of my own. Has this issue been solved ? Thanks

**Comment by danehrlich1** [comment]
@joshuaaguilar20 Yes the help here would be great. This will get you involved with the DOM API, which no Javascript, no matter how good, ever seems to know well :)

@bradymiller Can we also create an XSS issue for Joshua? Joshua this is another issue we need help with. This second issue is easier and more fun (will make you feel very productive) but we still need the help :)

**Comment by danehrlich1** [comment]
@joshuaaguilar20 Do you live in San Francisco?? I fly out there for work Monday to Friday currently. I'm about to leave in 9 hours. Want to meet / get lunch or dinner sometime this week?? Sorry for the short notice but cool coincidence. FYI though I'm a little south around Oracle Headquarters / north Santa Clara.

**Comment by joshuaaguilar20** [comment]
Yes near SF. That sounds great. Let me know what time works for you. I will look at  the issues mentioned above, just got the the repo up and running. Whats your email/contact ?   Thanks!

**Comment by bradymiller** [comment]
hi @joshuaaguilar20 ,
Check out this xss issue:
https://github.com/openemr/openemr/issues/2157

**Comment by morg0n** [comment]
Mind if I take a look at this?  It's been a while :)

**Comment by bradymiller** [comment]
hi @morg0n , go for it :)
-brady

**Comment by danehrlich1** [comment]
@morg0n dude no one has been able to solve this issue. if you will be able to solve it omg

**Comment by morg0n** [comment]
No pressure, right? LOL.  I will look at this asap after I wrap up this thingy at work :)
