### ISSUE TITLE
Class 'OpenEMR\\Common\\Logging\\EventAuditLogger' not found

### ISSUE THREAD

**Issue by harshlele** [openemr/openemr#2175]
I recently started getting an HTTP 500 error on loading the website at `http://localhost:8300` after running `docker-compose up`. 
It only seems to happen on the upto date master branch, on an older branch it works fine. 
I checked the error logs at `/var/log/apache2/error.log` inside the `openemr` container, and i found this error:

``` 
[php7:error] [pid 33] [client 172.20.0.1:57510] PHP Fatal error:  Uncaught Error: Class 'OpenEMR\\Common\\Logging\\EventAuditLogger' not found in /var/www/localhost/htdocs/openemr/library/ADODB_mysqli_log.php:42\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/library/sql.inc(52): ADODB_mysqli_log->Execute('SET NAMES 'utf8...')\n#1 /var/www/localhost/htdocs/openemr/interface/globals.php(283): require_once('/var/www/localh...')\n#2 /var/www/localhost/htdocs/openemr/interface/login/login.php(34): require_once('/var/www/localh...')\n#3 {main}\n  thrown in /var/www/localhost/htdocs/openemr/library/ADODB_mysqli_log.php on line 42
```
I'm using Ubuntu 18.04, with the latest version of docker.

**Comment by bradymiller** [comment]
Are you using the easy dev docker?
Is so, do the following:
docker-compose down -v
(the -v will remove the volumes)
then do `docker-compose up`

**Comment by harshlele** [comment]
that solved the problem. Thanks @bradymiller
