### ISSUE TITLE
LBF Needs a Table Data Type

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2176]
A nice  feature for building LBF encounter forms would be ability to create dynamic tables having the following capabilities:
- New data type Table.
- Popup editor to design table header and columns in editor.
- Allow choosing columns data from  existing LBF's or db table data. (think form history)
- Bootstrap or Css html tables
- Some styling.
I see this as very helpful to users wishing to create History reports from other form data or a general LBF report.
Just another hair brain scheme from the man with the cane..... Comments welcomed.

**Comment by bradymiller** [comment]
oh goodness, your avatar is funny!

**Comment by sjpadgett** [comment]
> LBF is more about data entry than reporting

True but once the form data is collected it becomes static with no ability to relate the data anywhere else. One use case could be for MAT(Medication-Assisted Treatment) or Pain Management where history is important in both regulatory reporting and treatment. A table that can be populated with form related  items of past history ie tabular historic data could be used for reporting and possibly display in new LBF as a reference to past form history.
Occupation Health forms have many use cases for historic data reporting.
We just need a way for user to build some reporting out of their LBF's. Tables seemed the easiest route.

**Comment by bradymiller** [comment]
To clarify, are we actually creating a sql table or is this an "abstract" table stored in the LBF data?

**Comment by sjpadgett** [comment]
The table will be a dynamically created BS or CSS styled table consisting of rows of columns selected from LBF form and field id's.. Say you have 5 past visits and 5 LBF eval/questionnaires and you want the history of certain fields from previous visits, you would create a table to be populated with those selected field id's as columns including DOS.
The table template design will be just a json array of the header column names and form/field id's in question.
Granted this is loosely tied to LBF editor but maybe could be used as a report generator elsewhere.
I'll try to give an example screen shot here later. If you guys think this is nuts for the real world, let me know so I can change my avatar to an ego id in a wheelchair:)

**Comment by sunsetsystems** [comment]
Not nuts :) but are you aware of the "Repeats" option in Layout Properties within the layout editor? Put in a small integer and you'll see that number of columns of historical data, like with the Vitals form.

**Comment by sjpadgett** [comment]
Nope Rod, I did not know about Repeats except for Vitals. Very nice and pretty much gets one where they need to be for form history. Thanks for pointing that out.
I probably will shelve this idea for time being however, I still have this desire to give users ability to create tabular style reports where they have control over content.
Different topic: With CMS portal I assume LBF's can be sent, populated in portal. Do those forms end up back in an encounter? I wondering if I shouldn't incorporate LBF in patient portal two.
Still say, LBF is one of our most useful feature to users....
