### ISSUE TITLE
Reopen and merge this pull request for SQL fixes

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2180]
https://github.com/openemr/openemr/pull/1989

**Comment by danehrlich1** [comment]
Still need to fix this: https://github.com/openemr/openemr/pull/1989#issuecomment-443588929

But that can be done in another issue.

**Comment by prondubuisi** [comment]
@danehrlich1 whats the issue here? how can I help?

**Comment by danehrlich1** [comment]
@prondubuisi No this is just fixing an old pull request from a few weeks ago

**Comment by danehrlich1** [comment]
@bradymiller Can you work on merging this? If you can do this in a day or two, I will take over the rest of the XSS fixes and knock them out.

**Comment by bradymiller** [comment]
hi @danehrlich1 , Getting very close! Just 3 more forms to fully secure, then will test, then will bring into codebase:
https://github.com/openemr/openemr/pull/2193
(guessing it will take a couple more days at most)

**Comment by bradymiller** [comment]
@danehrlich1 , just committed this to the codebase. Thanks for doing this! -brady
