### ISSUE TITLE
Understanding each directory

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2207]
documentation - DELETE
apis	- modern rest API stuff...combine with rest controllers folder?
ccdaservice - api server for ccda stuff
ccr- api server for ccr stuff
ci - travis ci stuff
cloud - DELETE	
common	- modern PS4 classes
config - UNKNOWN	
contrib - random stuff...has some things to delete	
controllers - Smart Templating code...upgrade to Smarty 3	
custom - random php files that should be brought into interface or library...also user defined js/css maybe move to public?
entities - unfinished attempt to migrate to Doctrine	
gacl - WHY NOT IN LIBRARY?
images - move to public	
interface - 	
library - 	
modules/sms_email_reminder - move to library or interface	
myportal	- special patient portal used only for Meaningful Use 2
patients - old simple patient portal no longer really used...delete	
phpfhir -	
portal - new patient portal	
public - public css/js/font assets	
repositories - part of unfinished doctrine effort	
rest_controllers - part of modern rest api	
services - new modern PS4 classes...not sure why can't combine with common
sites/default - this is also where all writeable stuff happens	
sql -
templates - 	
tests -

**Comment by danehrlich1** [comment]
Someone asked me a good question about what each directory in OpenEMR is supposed to do. I wasn't sure. I checked the Wiki and found some good resources here and there, but nothing that just said top level Folder A does this, top level Folder B does this, etc. 

Can each of us take a crack at defining in a sentence or two what each top-level folder above does? Just update the comment and we can go slowly. I can then make a nice doc out of this :)

NOTE: if this is already entirely done somewhere else, please drop a link below and will close this issue.

**Comment by prondubuisi** [comment]
good one @danehrlich1 this issue will help new OpenEmr developers like myself find our way around the codebase.

**Comment by danehrlich1** [comment]
What’s your email? Message me back on RocketChat

**Comment by danehrlich1** [comment]
Updated this...will make a documentation thing out of it later
