### ISSUE TITLE
Remove Certain Files After setup.php runs

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2216]
Look at this link: 
https://www.open-emr.org/wiki/index.php/Securing_OpenEMR#OpenEMR

Make sure to remove all the files it lists. See if there is a way to remove `setup.php` as well, although you will be deleting it from the file itself so that might be tricky.

**Comment by jfuad** [comment]
Can I work in this issue?

**Comment by bradymiller** [comment]
hi @jfuad and @danehrlich1 ,
This will likely turn into a very tough OS dependent exercise. Apache will not have the access permissions to do this itself (ie. via the setup.php script), so will require os dependent scripts/instructions. Note this stuff is already done for the ubuntu package and dockers (and there are manual instructions for other os's), so not sure if pursuing this (bunch of os dependent script) would be feasible or fun :)
