### ISSUE TITLE
Restrict scope of OpenEMR MySQL User

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2217]
Check out line 284 or right around there of this file where the GRANT and INSERT USER statements are called: https://github.com/openemr/openemr/blob/master/library/classes/Installer.class.php

This file is called by `setup.php` during installation. It creates the initial OpenEMR database user.

Surely this user can be restricted? Do they really need all these privileges? https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html

**Comment by prondubuisi** [comment]
@bradymiller Am guessing the first timer only tag means that pull request from non first timers won't be accepted Right?

**Comment by danehrlich1** [comment]
@prondubuisi No! Feel free to start on this issue. I just put that tag on there to show that it was an easier than normal tag.

I'm taking it off :)
