### ISSUE TITLE
Prevent SQL Issues During Installation

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2218]
Harden this file and make sure no SQL injection can occur. Parmeterize the statements using ADODB, reference other scripts for easy to find examples on how to do this. 

If you see any other possible security issues, please feel free to fix!

**Comment by prondubuisi** [comment]
@danehrlich1 which file are you talking about D:

**Comment by danehrlich1** [comment]
Wow sorry @prondubuisi 

This file and I believe specifically this line: https://github.com/openemr/openemr/blob/1c0511561b5d408ee52538200fe9d9fccd6406b7/library/classes/Installer.class.php#L234

ADDITIONAL TASK: make sure this file is hardened against SQL injection. Should be just a few lines here and there.

Thanks :)
