### ISSUE TITLE
Run Static Analysis on Codebase

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2219]
https://github.com/psecio/parse

Use the above tool. Let us know the results.

**Comment by prondubuisi** [comment]
@danehrlich1 I have problems installing the https://github.com/psecio/parse package, this is the error when I try to install it on the project folder
https://pastebin.com/avBjYUx8

on the other hand after installing it globally, on running `psecio-parse` I get this is not a command

**Comment by bradymiller** [comment]
hi @prondubuisi ,
Agree with the global install. Note that in that case, you may need to include the full path to the psecio-parse call (ie. something like /home/username/.composer/vendor/bin/psecio-parse)

**Comment by prondubuisi** [comment]
Thanks @bradymiller that works https://pastebin.com/TXVfRMUv
Unfortunately am not able to scroll to the top of my Terminal. Any tips, the error log is just part of the original
