### ISSUE TITLE
Delete Unused Functions

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2220]
Both first-timers and OpenEMR pros welcome :)

Most IDEs have a way to check for functions that are declared but never actually called / used. Download something like PHPStorm, which has a 30 day free trial, and figure out how to use this function.

Then delete all the functions you find and submit a pull request. We'll review them, maybe there will be a couple we actually need and need to save, and then you'll be done.

**Comment by akira202** [comment]
I will do it ;)

**Comment by sjpadgett** [comment]
Hmm, this can be very dangerous. First, IDE's find usage is not 100% reliable. Second, there are many occasions where a function call may be built in a variable and called via a call_user_function or soap calls.
I recm building a list first and posting here before creating a PR and then deciding.

**Comment by danehrlich1** [comment]
AT SJPadjett everything you said is correct. Let's have them get the pull request done so they can get practice (hence first-timers-only tag) and then we'll generate the list off of that. 

I'm going to cheat a little bit here and ask if you have any hints on files that you think should be looked at first (so instead of using the IDE)

**Comment by sjpadgett** [comment]
I guess PR is fine but I don't see off the top of my head how one would approach. Say you start in the library directory. Is one going to go through each source file and search each function/method and even then, if a library function is not currently used, by the inherent nature of a library, in may be in the future.
I hate to be the old fuddy duddy Dan :) But we have many work flows that get turned on and off that hardly ever get tested for releases. A bug introduced by a missing function may not show up until well into production and to trouble shoot such a bug is tedious at best. So those are my concerns and I don't see the import of doing this just now especially en masse.

**Comment by danehrlich1** [comment]
Lol good reply to the issue Jerry and you got me :)

I will close the issue later today.

Thanks a lot for your second reply. Explaining how the codebase works is really helpful for my general learning.

I guess if I need to learn future things I will post potentially highly destructive issues to bait you into replying in order to steal your knowledge that you reveal via comments :D:D

**Comment by sjpadgett** [comment]
I certainly don't try to getcha Dan because I can appreciate what you are trying to do. Keep up the good work.

**Comment by bradymiller** [comment]
hi all,
We definitely have unused functions(even likely a library or 2) that merit
removing. So, making a list or a PR that removes them should be harmless.
Before removing them, we would definitely do our own checking first (via
grep or grep like function).

**Comment by sjpadgett** [comment]
Unused libraries and/or dependencies would be easy enough to find but individual functions, not do much... Remember what I said about how functions can be called where it is not readily obvious.

**Comment by sjpadgett** [comment]
@danehrlich1 Brady thinks this is worthwhile doing and would be good practice for newer contributors so please don't let me stop this.

**Comment by cmccrea23** [comment]
Can I work on this?

**Comment by danehrlich1** [comment]
All yours.

Going off of your Github profile, are you an FCC student? We’ve had some good work from ppl who’ve started there.

Let us know if you need help on this issue. There is more good stuff to work on we can give you later that will really prepare you professionally (assuming that is your goal).


 Thanks.

**Comment by cmccrea23** [comment]
I am! I'll work on this today and let you know if I run into any issues. Would love to do more work if this goes well, thanks for offering!

**Comment by cmccrea23** [comment]
Do you want me to remove functions that are commented out?

**Comment by cmccrea23** [comment]
@danehrlich1 I'm finding several 'reports' files in forms that declare a function and never use it. Do you want me to just delete that function or the entire file? Or are these being used by an outside program I can't see?

**Comment by danehrlich1** [comment]
Claire, yes go ahead and delete it / be aggressive. Most likely they aren’t being used
by an outside program.

When you turn in the pull request, the more senior devs here might be able to tell things that should have been left in, but there is really no way to know until you submit.

Are you using any tools to go through the source code? I don’t have my MacBook in front of me but I believe PHPStorm has some good dead code analysis tools.

**Comment by cmccrea23** [comment]
Sounds good. I'm using the PHP IntelliSense extension with VSCode, I can try PHPStorm if that's what you recommend.

I've also found instances where setter functions aren't being used but the getters are-- should I still delete the unused setters? And what would you like me to do re: typos?

**Comment by danehrlich1** [comment]
1. As long as you have an IDE that has some code analysis functions you are good to go. VSCode is starting to get really popular so definitely stick with that.

2. Can you list a couple of files where getters are used but setters aren’t? First instinct was to keep as is, but for security reasons deleting the setters is tempting. Let me think.

3. I saw above you’ve actually found WHOLE FILES that can be deleted. Please delete them. Whenever we get to delete a whole file that’s a big win.

4. What do you mean “re: typos”?

**Comment by bradymiller** [comment]
hi @danehrlich1 and @cmccrea23 ,
Sounds good except I would rec not touching the getters/setters.
-brady

**Comment by cmccrea23** [comment]
I tried phpStorm, and you were definitely right-- it does a phenomenal job finding unused things. I'll give them both a run through, but phpStorm seems to find the bulk of things very quickly.

Under contrib/forms/evaluation/FormEvaluation.class.php I found several setters that were unused, examples: set_activity, set_date, set_temp, etc... I've deleted some already but will put them back now :)

I've seen 'assessment' spelled 'assesment' a couple of times, nothing big.

**Comment by danehrlich1** [comment]
Definitely fix the typos, that is a great find.

It’s very important the spelling is right (or at least just consistent) because if in the future we are using ctrl+f to find something in the codebase we are going to miss some instances of the word/phrase otherwise. 

Make sure though that later something doesn’t in turn call that misspelled variable, function, etc (and if so you can just fix both)
