### ISSUE TITLE
Secure Email in OpenEMR sent via PHP

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2221]
OpenEMR uses PHPMailer to send email currently. Find where we instantiate a PHPMailer() or MyMailer() object and make sure it sends email securely. Just search for "mailer" in this repo and you should find those instances. There are maybe 30. 

Also here is the MyMailer() class, which extends the PHPMailer() class. Make sure the config is properly secured. Maybe we should be adding other options? Validation checks? https://github.com/openemr/openemr/blob/fa9f0bfcfda78561077861a6481fa3f4bfe1186d/library/classes/postmaster.php

**Comment by simo94445** [comment]
I'd like to contribute, is this issue still open?

**Comment by danehrlich1** [comment]
Yes it is. I can reserve it for you for a week. Let us know if you need any help and it’s all yours now.

**Comment by simo94445** [comment]
I've audited the code and found that every instance of PHPMailer() and MyMailer() has proper validation checks, that it reads from and stores passwords as salted hashes which is secure, and I have but one concern. The function generatePassword() can't be good security. In account.lib.php it's clear that the length of the password is 8, and the pattern is easily readable, which could be used to rather easily bruteforce any password created by this function. I would rather have the user prompted to create their own password, and perhabs link a good resource for password creation, ie: https://www.howtogeek.com/195430/how-to-create-a-strong-password-and-remember-it/ that suggests creating high entropy passwords that are actually memorable. Can I help you with this?

**Comment by danehrlich1** [comment]
Yes absolutely and I think this idea is great. 

#1. Can you include a link to Bitwarden (OS Password Manager) to encourage use of password managers?

#2. The user probably won’t create a good password either. Is there a library you could find that can generate 12+ character passwords that are memorable? Maybe a combo of random words + numbers/symbols? You could have a button that says “generate secure memorable passsword” or something.

Example password:

“kilo$:)dunning”


Again awesome suggestion and let us know if you have any other ideas regarding security stuff would love to hear them

**Comment by simo94445** [comment]
I suggest keeping away from automatically creating passwords based on wordlists and random symbols, because if someone has access to the wordlist and knows how the passwords are created, as in this case with Open-Source software, it would be easy to bruteforce. My suggestion is having a button that says "generate secure password", that prompts the user to pick 6 different words with >n length, that then adds random numbers/symbols/capitalization to increase entropy. To help you achieve this, do I simply just write the code, compile and test it, then create a pull request, or do I need to report an issue and ask to solve it?

**Comment by danehrlich1** [comment]
Sorry I thought I responded to this earlier. 

Yes this sounds ideal. Write the code, put in the pull request, and just make sure to reference this issue we are currently on now.

**Comment by morg0n** [comment]
Has this been handled? (Otherwise I'll jump in!)

**Comment by bradymiller** [comment]
hi @morg0n , Looks like this issue can be closed. @danehrlich1 , can I get confirmation that ok to close this issue? thanks, -brady
