### ISSUE TITLE
Sql escape column names special cases

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr#2228]
The [escape_sql_column_name](https://github.com/openemr/openemr/blob/master/library/formdata.inc.php#L96) function does not cover some use cases, I will be dropping them here for ideas on how to get them covered @bradymiller

**Comment by prondubuisi** [comment]
[First case ](https://github.com/openemr/openemr/blob/master/common/logging/EventAuditLogger.php#L215

**Comment by bradymiller** [comment]
Could consider:
When looping through the items in the array, explode each item by a space delimiter.
If only one subitem, then just proceed.
If two subitems, and DISTINCT is first subitem, then check it by doing escape_sql_column_name on the second subitem
