### ISSUE TITLE
Cant use REST APIs when using .deb to install openemr

### ISSUE THREAD

**Issue by arpitgoyal2008** [openemr/openemr#2230]

**Comment by sjpadgett** [comment]
@arpitgoyal2008 
 Hmm, no clue what this means!

**Comment by arpitgoyal2008** [comment]
Hi,
I am using openemr-php7_5.0.1-4_all.deb on https://www.open-emr.org/wiki/index.php/OpenEMR_Downloads
Looks like APIs are not bundled with this image.

**Comment by bradymiller** [comment]
hi @arpitgoyal2008 ,
API is not in OpenEMR 5.0.1 . It's currently in the development version of OpenEMR and will be in OpenEMR 5.0.2 (likely to be released in several months).

**Comment by adunsulag** [comment]
@bradymiller Can we close this issue then since it's not applicable to Version 5.0.2?

**Comment by bradymiller** [comment]
@adunsulag , Thanks for pointing this out. Agreed and closing this issue.

**Comment by abobwhite** [comment]
@bradymiller Trying to use this in a hackathon this weekend and just now seeing this. Is there a branch we can use to build our own Dockerfile so we can use the API? API shouldn't be in the docs if it's not available :/

**Comment by adunsulag** [comment]
@abobwhite Use the flex docker environment and use the release against master https://hub.docker.com/r/openemr/openemr/

Happy to have your hackathon contributions which can include updating the documentation if there is a discrepancy :)

**Comment by abobwhite** [comment]
Thanks for the quick feedback, @adunsulag, I appreciate it. We'll contribute back anything we do to enhance openemr API. We're specifically needing the prescription API so maybe we can help with that.

**Comment by abobwhite** [comment]
@adunsulag If you're around - we've used the `flex` and pointed to master branch for the moment. After enabling the API, trying to authenticate is causing an error in the apache logs because it's not loading a required php file:
```
[Sat Jul 20 16:52:48.453173 2019] [php7:error] [pid 506] [client 150.201.170.214:56755] PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/../src/Common/Session/SessionUtil.php' (include_path='.:/usr/share/php7') in /var/www/localhost/htdocs/openemr/_rest_config.php on line 14
```

Any help would be appreciated.

**Comment by sjpadgett** [comment]
@abobwhite This path doesn't look right and i'm not where I can test but change to:
`require_once(dirname(__FILE__) . "/src/Common/Session/SessionUtil.php");` as where in root already...

**Comment by sjpadgett** [comment]
Also take a look in openemr/tests/api as there're is api test for using internal though you're not but may give you some insight.

**Comment by abobwhite** [comment]
Thanks @sjpadgett ! That was the issue. I created a PR for the fix: https://github.com/openemr/openemr/pull/2572

**Comment by bradymiller** [comment]
hi,
I just pushed the fix for this to master.

**Comment by abobwhite** [comment]
Thanks @bradymiller . I'll close my PR

**Comment by bradymiller** [comment]
hi @abobwhite ,
I'll revert my fix and bring in yours, so you get credit :)

**Comment by abobwhite** [comment]
@bradymiller no problem. Either way. Up to you
