### ISSUE TITLE
Replace HTTP links with HTTPS when possible

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2247]
There are quite a few http links throughout the codebase. Some have to stay that way, but many can be shifted to https. 

Good example is [this file](https://github.com/openemr/openemr/blob/master/library/globals.inc.php).
- [This line](https://github.com/openemr/openemr/blob/c5649fd9a9dc61b5bf1908f9cafd00c0cb426512/library/globals.inc.php#L616) has to stay http. If it's shifted to https, the link breaks.
- However [this line](https://github.com/openemr/openemr/blob/c5649fd9a9dc61b5bf1908f9cafd00c0cb426512/library/globals.inc.php#L392) can be shifted to https. 

TASK:
- Use an IDE such as PHPStorm to load the code
- Search for all use cases of `http` in [this folder](https://github.com/openemr/openemr/tree/master/library
) to start
- Go through each of them and see if they can be replaced with https
- Make a pull request!

**Comment by marieram** [comment]
Can I work on this ?

**Comment by danehrlich1** [comment]
All yours. I’ll reserve it for you for a week.
