### ISSUE TITLE
Fix PHP warnings

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2274]
This issue can be taken by several devs.

Steps:
1. Get OpenEMR dev environment up and running with PHP 7.2 (PHP 7.3 would be extra credit).
2. Systematically go through as many of the OpenEMR scripts as can possible go through while monitoring the php error log.
3. Fix the PHP Warnings and PHP Deprecated warnings in the php error log.

Recommend just fixing a couple warnings (even fixing just 1 is ok) at a time.

**Comment by JoppeDC** [comment]
Taking a shot at this one! Wish me luck 😅

**Comment by sjpadgett** [comment]
Wouldn't hurt to also fix PHP notices. Sometimes they are little sneaky troublemakers :)

**Comment by JoppeDC** [comment]
Have to get it setup locally first 😅 followed the `CONTRIBUTING.md` but doesn't seem to be 100% correct

**Comment by cmccrea23** [comment]
I'll jump in on this as well!

**Comment by rexsteroxy** [comment]
Let me try this as well

**Comment by prondubuisi** [comment]
Hello @bradymiller I am using a docker installation, how do I access the error log

**Comment by bradymiller** [comment]
hi @prondubuisi ,
What do you see with the following command:
```
docker ps -a
```

**Comment by prondubuisi** [comment]
Hello @bradymiller this is my output from the command
https://pastebin.com/fz30nrHE

**Comment by bradymiller** [comment]
hi @prondubuisi ,
first, go into the docker:
```
docker exec -it openemr_openemr_1 sh
```
then, when inside docker, do following:
```
cat /var/log/apache2/error.log
```

**Comment by litemikx** [comment]
Is this still open? Would also like to explore on this one since I'm not that familiar with PHP. 

Thanks! :)

**Comment by bradymiller** [comment]
hi @litemikx , Definitely still open. Go for it :)  -brady

**Comment by morg0n** [comment]
I'd be willing to take a look at this if it's still open~!

**Comment by bradymiller** [comment]
hi @morg0n ,
Looking for and fixing php warnings is always open. See here for more current issues regarding this (and I am going to close this issue since outdated):
https://github.com/openemr/openemr/issues/2339
https://github.com/openemr/openemr/issues/2499
