### ISSUE TITLE
Encounter Claims, what is it?

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2283]
For some unknown reason Office Ally uses two different Insurance Payer Ids between eligibility and 835/837 billing! I want to use the alt_cms_id ie CMS ID/Payer id For Encounter Claims. I can't find anywhere in code it is used. Anyone know why/what/how as enquiring minds need to know. Perhaps @stephenwaite 

I truly don't want to do an additional field in insurance using the unused table column ins_company_id.

**Comment by stephenwaite** [comment]
hi @sjpadgett , it was waiting patiently all this time for you to come along and complete eligibility to that weirdoffice ally :)

**Comment by sjpadgett** [comment]
Finally have working well on a 501 production and tested on 502 so,  i'm about done and will post up final version. Not sure about 501 patch but will give up with caveat that composer may need to be run at command line. Can't seem to get class autoload to work in a patch ... yet:) 
Once I get 501 patch maybe you could test the batch against VT Medicaid so I can make adjustment there if needed.
