### ISSUE TITLE
Popup window is not generated for edit the existed event when configure at Calendar both Admin Portal

### ISSUE THREAD

**Issue by kamaleshSRI** [openemr/openemr#2290]
Demo openemr 5.0.1
1.Click on Login button
Test procedure :
1. Click on Calendar
2. Initially create any one provider schedule
3. Click on Search appointment icon
4. Set the particular fields 
5. Click on submit button
6. Click on any one resulted event
Actual result :
Popup window not generated
Expected result :
Popup window should be generated

If set tab navigation its working but frame navigation it is not display provider popup window.

**Comment by sjpadgett** [comment]
@kamaleshSRI 
 whats Admin Portal?

**Comment by kamaleshSRI** [comment]
URL for verification:   
![CALENDAR PAGE](https://user-images.githubusercontent.com/47585495/54580035-3fbedc00-4a2c-11e9-82a8-65c6740621f3.png)
![POPUP WINDOW](https://user-images.githubusercontent.com/47585495/54580042-48171700-4a2c-11e9-92c0-b6378c090966.png)

https://demo.openemr.io/c/openemr/interface/login/login.php?site=default

**Comment by sjpadgett** [comment]
yep, verified. The search was missed in 501 upgrade for dialogs. Can fix, just not sure how soon. For sure for patch 8.

**Comment by sjpadgett** [comment]
@kamaleshSRI Okay this is resolved. Dis a quick patch for 501 if ya need it. unzip in openemr root
[calendar-dialog-fix.zip](https://github.com/openemr/openemr/files/2985719/calendar-dialog-fix.zip)

**Comment by kamaleshSRI** [comment]
Thanks for your valuable suggestions...
