### ISSUE TITLE
Billing Manager x12 partner not set to insurance x12 partner for default.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2292]
Got to be a pain for billing folks to have to select partner for each claim. I'll get to eventually but if someone else is in billing_report.php. Take a look.....

**Comment by stephenwaite** [comment]
bump, what also like to see if can select items by ins co and x12 partner in the billing manager before they are billed

**Comment by stephenwaite** [comment]
here's the billing manager with `Unbilled` selected
![Screenshot from 2020-08-26 08-14-34](https://user-images.githubusercontent.com/5618372/91302359-61210d00-e774-11ea-9b42-48fd26eb5e60.png)

here's the shot with `Unbilled` and `Insurance Company`
![Screenshot from 2020-08-26 08-17-12](https://user-images.githubusercontent.com/5618372/91302480-9299d880-e774-11ea-87a9-372cd92545e9.png)

what happened?

**Comment by stephenwaite** [comment]
was prob fixed by recent overhaul, will dbl check

**Comment by stephenwaite** [comment]
still have to check on this

**Comment by stephenwaite** [comment]
bump
