### ISSUE TITLE
Limit main menus tree length

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2301]
Need to create some sub menus in our longer menu trees. Main reason is for portable devices.
Be careful for menu items that menu paths are well documented and pick the lesser used items to throw into another menu tree. 

Test as admin privileges.

**Comment by dimitristsilis** [comment]
Would like to propose the following changes in Administration menu:

1. Clinic

   - Facilities 

   - Calendar

   - Import Holidays

1. Patients

   - Patient Reminders  

   - Merge Patients

   - Chart Tracker (from Miscellaneous)

1. Practice

   - Practice Settings (former "Practice" menu entry)

   - Rules

   - Alerts

1. Coding 

   - Codes

   - Native Data Loads

   - External Data Loads

1. Forms

   - Forms Administration (former "Forms" menu entry)

   - Layouts

1. Documents

   - New Documents (from Miscellaneous)

   - Documents Templates (from Miscellaneous) 

1. System

   - Backup

   - Files (is it ok here? Could stay alone.)

   - Language

   - Certificates

   - Logs

@sjpadgett @bradymiller What do you think? Should I try to make these changes?

**Comment by bradymiller** [comment]
Hi @dimitristsilis ,
Like the idea of organizing this stuff. Couple things:
1. Not seeing Globals
2. `New Documents` and `Chart Tracker` don't really seem like Administration type activities

**Comment by dimitristsilis** [comment]
@bradymiller Anything not mentioned stays as is. Agree, New Documents and Chart Tracker don't fit there, but thought that it is a good opportunity to shorten the tree even more... Of course menus have to be self explanatory, so will follow your recommendation.
