### ISSUE TITLE
New AI Agent - Create API User

### ISSUE THREAD

**Issue by avanss** [openemr/openemr#2305]
We have integrated our AI scheduling system to OpenEMR. Patients can schedule, reschedule, cancel appointments and get reminders texting or talking to our AI agent. Here you can see more details: https://vimeo.com/323285022  (appointments will just show up as regular appointments on OpenEmr calendar)

We are using OpenEMR API to access the system. The API can use a regular user, but for security reasons it makes sense to have a specific user for the API (such as phimail-service user). The API user (api-user) needs a password for remote access, but it can be set to inactive, so it won't be able access the system using the login page. These would be the necessary changes:

official_additional_users.sql
INSERT INTO `users` (username,password,lname,authorized,active) VALUES ('api-user','NoLogin','Patient Portal User',0,0);

For the next upgrade script:
#IfNotRow users username api-service
INSERT INTO `users` (username,password,lname,authorized,active) 
  VALUES ('api-user','NoLogin','API Access',0,0);
#EndIf

We have some other enhancements to the API which will post soon. The implementation of our system doesn't require any changes to OpenEmr core.

If you know any clinic interested in piloting the solution please let us know.

**Comment by bradymiller** [comment]
hi @avanss ,

Very neat stuff! And nice to see it all taking advantage of the API. Looking very forward to seeing your API enhancements.

-brady

**Comment by bradymiller** [comment]
btw, to find folks willing to pilot, recommend asking on the openemr forums since that has many more end users there (mostly just developers monitor github): https://community.open-emr.org/

**Comment by avanss** [comment]
Thanks @bradymiller!  We will ask at the forum
