### ISSUE TITLE
Move images/ under public/

### ISSUE THREAD

**Issue by cmccrea23** [openemr/openemr#2307]
1. Search codebase to see if even used
a. If not used, delete it
b. If used, then migrate it to public/images and 
-change to corresponding path to where it is used (with the goal of using the either one of these variables for the path if possible (note: would not be able to use this if the path is in a styling only script): https://github.com/openemr/openemr/blob/master/interface/globals.php#L194-L198)

**Comment by cmccrea23** [comment]
@bradymiller is the goal for ALL images folders to be moved under /public or only the main openemr/images folder?

**Comment by bradymiller** [comment]
hi @cmccrea23 ,

Here's a listing of all the images folders:
```
[21:18][brady2@brady2-gaz:~/git/openemr(master)]$ find . -type d -name "images"
portal/images
interface/modules/zend_modules/public/images
interface/modules/zend_modules/public/js/carecoordination/images
interface/modules/zend_modules/public/css/images
interface/modules/zend_modules/public/css/jquery.treeview-1.4.1/images
interface/modules/zend_modules/public/css/slider/images
interface/forms/eye_mag/images
interface/main/calendar/modules/PostCalendar/pntemplates/default/images
images
library/js/jquery.treeview-1.4.1/images
library/css/images
gacl/admin/images
gacl/docs/phpdoc/media/images
public/images
sites/default/images
```

I would only migrate over images and library/css/images for now
(would not do the others since they are part of modules)

@sjpadgett , would it make sense to migrate portal/images over?

-brady

**Comment by cmccrea23** [comment]
Thanks @bradymiller! I just moved the library/css/images over now, ran into two different files named favicon.ico. How would you like me to resolve it?

**Comment by cmccrea23** [comment]
Actually, it doesn't look like it's used... want me to delete it?

**Comment by bradymiller** [comment]
PR just brought in for this issue:
https://github.com/openemr/openemr/pull/2310
Thanks @cmccrea23 !
Closing this issue
