### ISSUE TITLE
jQuery .ready Deprecated

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2314]
```
$( document ).ready(function() {
  console.log('*** No no ***');
});
```
Is no longer recommended especially jquery 3+.  Also be aware calling onload bindings inside .ready will cause issues 3+.
Instead use:
```
$(function () {
  console.log('*** Use this instead ***');
 });

window.onload etc.
```

Possible issue for moderate to attack. If someone does take this on remember to not try to consolidate existing event handlers and leave in the same place in scripts workflow ie execution order can be important. 
I've now come across this problem twice when updating jq dependencies to 3.1.1

**Comment by sjpadgett** [comment]
Also href='javascript:void();' needs to be watched. It will break anchors if the function in onclick doesn't return false. Using javascript:void(0) will help but onclick makes it redundant either set up a click event in dom or use the href as meant e.g href="javascript: myWonderfulFunction(); return false;" 
I just wanted to note here because I ran across new bug using divtoggle where href="#" was replaced with above which is probably more correct but needs a false return.
If someone wanted to explore, this would be worthwhile...

**Comment by sjpadgett** [comment]
Another one that we needs to get done is go through code and make globals includes path reliable. Something like
require_once(dirname(__FILE__) . '/../../globals.php'); etc...

**Comment by danehrlich1** [comment]
> Another one that we needs to get done is go through code and make globals includes path reliable. Something like
> `require_once(dirname(__FILE__) . '/../../globals.php');` etc...

What are we currently doing?

Also @sjpadgett use backticks to quote code. Either enclose with a single backtick to do a oneliner `like this` or do 3 on top 3 on bottom to get something like this:
```
hello
three above
three below
hello
```

**Comment by danehrlich1** [comment]
I assume this is for beginners so going to mark accordingly @sjpadgett

**Comment by danehrlich1** [comment]
As always `first-timers-only` tag just means those who are newish to the repo. If you've been here less than 6 weeks and have only done 1 pull request say, feel free to contribute.

**Comment by sjpadgett** [comment]
> backticks to quote code
My Commodore doesn't have a tick :)

**Comment by jillpena** [comment]
Hi! Can I take on this issue?

**Comment by bradymiller** [comment]
hi @jillpena ,
Definitely. There is also another developer working on this, @LightDev777 , but this is a big item and ok for more than 1 dev to work on it. Recommend just doing several scripts at a time until get the hang of it.

**Comment by morg0n** [comment]
Hey if you all have room for another Contributor I can push some things through!

**Comment by sachinmukherjee** [comment]
@sjpadgett  Is this issue open? If open can I take this up?

**Comment by bradymiller** [comment]
hi @sachinmukherjee , It is yours :)

**Comment by sachinmukherjee** [comment]
@bradymiller  Thanks for assigning it to me. Before working on this issue a few points I want to clear

- Remove deprecated jquery.ready to `$(function){}`.

- Do not change the existing event handler. Leave them where they are.

**Comment by bradymiller** [comment]
hi @sachinmukherjee , yep, that's the plan. thanks! -brady

**Comment by bradymiller** [comment]
Still a couple more to go
