### ISSUE TITLE
Remove ability to modify php scripts from the Administration-Files gui

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2319]
Hi,
A lot of serious havoc can be done easily by any admin users if they can modify those php scripts. Is it ok if I remove the ability to modify php scripts on that gui?
Thanks,
-Brady

**Comment by sjpadgett** [comment]
I ran across that again the other day and my first thought was; hmm, I wonder what happens if I do this!. :)
I'd say yes, do....

**Comment by bradymiller** [comment]
fixed
