### ISSUE TITLE
Style Eligibility Reports and Tab. Add Help

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2323]
Hi @zbig01 , Thanks for doing this. The scripts involved:
- interface/reports/edi_270.php
- interface/reports/edi_271.php
- library/edi.php
and tab
- interface/patient_file/summary/demographics.php

For content, I have feature running on a production site where i'm accumulating gotchas from clinical side and this forum thread will give idea of content type: https://community.open-emr.org/t/eligibility-checks-clearinghouses/9742/45 
There are two modes: RealTime and Batch and screenshots on forum.
I'll email tables with some testing data and what content you don't want to fool with just use placeholders and i'll come back to and populate.
Thanks my friend...

**Comment by zbig01** [comment]
will work on it. Thanks
