### ISSUE TITLE
Rest API Fatal Error if site id is invalid

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#2324]
So I ran the CURL API request with basic default data but had no idea what to put for scope so I left it as site id.  It triggers a fatal error because it cannot find the translation text() function on line 133  
```
curl -X POST -H 'Content-Type: application/json' 'http://172.20.0.4/apis/api/auth' \
-d '{
    "grant_type":"password",
    "username": "admin",
    "password": "pass",
    "scope":"site id" 
}'
````
Error log:
```
[Mon Mar 25 21:12:20.252255 2019] [php7:error] [pid 560] [client 172.20.0.1:59780] PHP Fatal error:  Uncaught Error: Call to undefined function text() in /var/www/localhost/htdocs/openemr/interface/globals.php:133\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/apis/dispatch.php(67): require_once()\n#1 {main}\n  thrown in /var/www/localhost/htdocs/openemr/interface/globals.php on line 133
```

I believe its a simple fix of just requiring once the htmlspecialchars.inc.php file.  I will submit a pull request for the fix as well as update the API documentation about the site id information.

**Comment by avanss** [comment]
@adunsulag we use "default" for the scope and it works well:

curl -X POST -H 'Content-Type: application/json' 'http://172.20.0.4/apis/api/auth' \
-d '{
    "grant_type":"password",
    "username": "admin",
    "password": "pass",
    "scope":"default" 
}'

**Comment by adunsulag** [comment]
@avanss Yea I found that out after triggering the fatal error.  However, my lack of knowledge helped execute a code pathway that failed and had a bug in it.  So I've reported it and fixed it in the pull request.
