### ISSUE TITLE
npm dev-docs script fails 'run-p not found'

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#2328]
I'm getting an error in trying to run the theming system by following the [interface README.md](https://github.com/openemr/openemr/tree/master//interface/README.md)  instructions.  I ran the following commands that are in the document.
```
npm install
npm run dev-docs
```
When I did that it throws the following error:
```
> openemr-interface@0.2.0 dev-docs /projects/emr/open-emr/src/openemr
> run-p storybook gulp-docs

sh: 1: run-p: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! openemr-interface@0.2.0 dev-docs: `run-p storybook gulp-docs`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the openemr-interface@0.2.0 dev-docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
So the run-p command is not found.  I believe the run script is assuming that I have the npm [run-all package](https://www.npmjs.com/package/npm-run-all) that has the run-p command installed but its not listed as a dependency in the package.json file of the project.

To fix this my first question is whether the storybook environment still used?  It looks like the `dev` and `dev-sync` run commands will watch and compile the scss so live updates can be seen in the OpenEMR platform and don't rely on anything with storybook.  I can see the value of storybook after looking at its wiki but I've never used it in the past and can't tell if the project still uses it.

I can go ahead and fix this issue by installing the run-all dependency or by removing the storybook run script if we don't use it anymore.

**Comment by danehrlich1** [comment]
Stephen:

We’ve been talking about reducing / cleaning up the codebase.

I was considering taking out .docs and .storybook.

If these can be removed (I can’t think of anything they are currently used for) that would be ideal.

We can preserve them on a legacy branch though so if someone wants to pick up whatever the original goal was with those scripts they can.

**Comment by bradymiller** [comment]
hi @adunsulag and @danehrlich1 ,
Lets have @d3sandoval weigh in on this before making any changes to this.
-brady

**Comment by d3sandoval** [comment]
Happy to cut those folders out and reintroduce them later. I was using storybook to help test the theme consolidation work. Now that that's done, it's not as necessary to keep for now. Happy to reintroduce storybook if we start to build modular components or just want a separate place for UI documentation.

**Comment by d3sandoval** [comment]
Happy to make a PR this weekend that removes storybook and cleans up the package.json. in hindset, I should have kept the dependencies from the bower migration separate from the ones that storybook relies on. When I do reintroduce storybook (or any other frontend documentation framework), I'll be sure to separate those concerns :)

**Comment by danehrlich1** [comment]
Brady:

Can you then merge Daniel’s PR along with my PR which takes out (but still preserves) Matthew’s Doctrine folders?

**Comment by bradymiller** [comment]
thanks @d3sandoval ; Definitely would be great to have those removed if not being used.
(@danehrlich1 ; regarding doctrine stuff, I'll leave a post on the doctrine PR)

**Comment by d3sandoval** [comment]
@bradymiller  @adunsulag I've gone ahead and opened a PR to remove the unused storybook docs + build dependencies from the project: https://github.com/openemr/openemr/pull/2346

I still love how easy it is to use browsersync to implement css/js changes directly on the openEMR UI. I feel like storybook is overkill at this point - unless we really want to lean into react or vue on the frontend :)

**Comment by bradymiller** [comment]
brought in above PR, so closing this issue. thanks @d3sandoval !
