### ISSUE TITLE
Patient name and date of birth is not display when configure at labs in patient page both admin & doctor portal

### ISSUE THREAD

**Issue by kamaleshSRI** [openemr/openemr#2332]
Patient name and date of birth is not display when configure at labs in patient page both admin & doctor portal

Test Configuration:
1.Enter the URL in browser :  https://demo.openemr.io/c/openemr
2.Click on withEMR button
3.Enter the username and password of admin
4.Click on Login button

Test procedure:

1.Procedures | Configurations
2.Click on Add Top Level button
3.Set Procedure Order at Procedure Type drop down list
4.Add details and click on save button
5.Set Discrete Result at Procedure Type drop down list
6.Add details and click on save button
7.Select one patient
8.Create an encounter or else select past encounter
9.In that encounter page , Administrative | Procedure Order
10.Click on Procedure Text box , add procedure
11.Click on Save button
12.Procedures | Pending Review
13.Add details and Click on Sign Result button
14.Procedures | Patient results
15.Click on Save button
16.Procedures | Lab Overview
17.Click on Toggle All
18.Click on Submit button
19.Click on View Printable Version button

Actual Result:
Patient name & DOB is not displayed

Expected Result:
Patient name & DOB should be displayed
(sometimes Patient name is display but some time not display)

**Comment by stephenwaite** [comment]
looks like it works in the development demos, maybe this was the fix, https://github.com/openemr/openemr/commit/b420c4805fce92928f7671fe7a796ea3828a81f5#diff-1ab4de1d0a36b07ac05a1d68323e77f9

**Comment by kamaleshSRI** [comment]
After change id into pid its working ..
