### ISSUE TITLE
Bug on new_comprehensive.php 

### ISSUE THREAD

**Issue by eduardoboca** [openemr/openemr#2336]
I think there`s a bug on new_comprehensive.php file. Line 393 should be: 

 document.location.href = "./../../interface/patient_file/summary/demographics.php?set_pid=" + pid;

**Comment by stephenwaite** [comment]
think @bradymiller added this to prevent pid from tampering

https://github.com/openemr/openemr/commit/d4d3060d685b1d9d4c4ef39f55c29683f0c18222#diff-953e5dd0e0c0e8d55ae1d1b493b7bd0bR394

**Comment by bradymiller** [comment]
hi @eduardoboca ,
Thanks for reporting potential bugs. What is the bug causing?
-brady
