### ISSUE TITLE
OpenEMR SQL Escaping ERROR in forms.inc

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2337]
called by cqm.php through ajax

https://github.com/openemr/openemr/blob/master/library/forms.inc#L95

think escape_table_name function in library/formdata.inc.php can't parse the join

**Comment by bradymiller** [comment]
Yep, the escape_table_name will break that. I'll post a fix for this real quick.

**Comment by stephenwaite** [comment]
ok, nice, think that's the only prob with running cqm 2014 on a dev version so most likely works fine on 5.0.1

**Comment by bradymiller** [comment]
fix is in :)

**Comment by stephenwaite** [comment]
yippee, thank you
