### ISSUE TITLE
Complete testing/reporting of all scripts for php 7.3 warnings/errors

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2339]
After complete the testing/reporting, will then ensure they are all addressed.

**Comment by stephenwaite** [comment]
hi @bradymiller , is the openemr flex-edge docker running php 7.3?

**Comment by bradymiller** [comment]
hi @stephenwaite ,

Alpine edge still is on PHP 7.2:
https://pkgs.alpinelinux.org/packages?name=php7&branch=edge

I use the insane dev environment to test PHP 7.3 (via nginx/php-fpm):
https://github.com/openemr/openemr/tree/master/contrib/util/docker#insane-development-docker-environment
(note you should not run this directly from your repo like the Easy dev environment)

**Comment by bradymiller** [comment]
Also note it loads 29 dockers :)
(so higher performance laptop/pc likely needed)

**Comment by stephenwaite** [comment]
can't get past setup, when does composer run, keep getting this error:

Uncaught Error: Call to undefined function produceRandomString() in /var/www/localhost/htdocs/openemr/setup.php:804\nStack trace:\n#0 {main}\n  thrown in /var/www/localhost/htdocs/openemr/setup.php on line 804, referer: http://localhost:8080/setup.php?site=default

or am i supposed to run composer install before fire up the dockers?

**Comment by bradymiller** [comment]
One of the dockers does the composer/npm stuff, but it does not autoinstall (so need to run setup.php after it is done setting things up). Ensure the docker is done setting things up though before trying to run it. Do the following to ensure it is ready to go:
```
docker logs docker_openemr-7-2_1
```

**Comment by stephenwaite** [comment]
maybe it's the mac os version of docker that's the prob, after trying numerous times finally ran composer install on docker_openemr-7-2_1 to try to get past setup

**Comment by bradymiller** [comment]
hi @stephenwaite ,
try:
```
docker-compose down -v
docker-compose up -d
```
Then wait about 5 minutes or so, and then do:
```
docker logs docker_openemr-7-2_1
```
And paste the log here (or email it to me)

**Comment by bradymiller** [comment]
Here are eye form issues in php 7.3:
```
NOTICE: PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/nginx/html/openemr/interface/forms/eye_mag/php/eye_mag_functions.php on line 4585
NOTICE: PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/nginx/html/openemr/interface/forms/eye_mag/php/eye_mag_functions.php on line 4592
NOTICE: PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/html/openemr/interface/forms/eye_mag/php/eye_mag_functions.php on line 4745
NOTICE: PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/nginx/html/openemr/interface/forms/eye_mag/php/eye_mag_functions.php on line 3612
NOTICE: PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/nginx/html/openemr/interface/forms/eye_mag/view.php on line 3685
NOTICE: PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/nginx/html/openemr/interface/forms/eye_mag/save.php on line 851
NOTICE: PHP message: PHP Warning:  implode(): Invalid arguments passed in /usr/share/nginx/html/openemr/interface/forms/eye_mag/save.php on line 1012
```

**Comment by bradymiller** [comment]
Addressed all above warnings/deprecated in following PR:
https://github.com/openemr/openemr/pull/2445

**Comment by bradymiller** [comment]
Just brought in fixes into codebase. Going to keep this issue up since a in depth test run of OpenEMR (ie. test everything imaginable) on php 7.3 is still needed.

**Comment by bradymiller** [comment]
Hi,
Alpine Edge just incremented their PHP version to 7.3. So now will be easier to test PHP 7.3. Can now use the flex-edge docker, which is now using PHP 7.3. Or even easier, can test from this development demo that is now using PHP 7.3: https://www.open-emr.org/wiki/index.php/Development_Demo#Alternate_Demo_.28Alpine_Edge_-_uses_php_7.3.29

**Comment by stephenwaite** [comment]
thank you @bradymiller , should we attempt to fix the wordpress files?
`20-Jun-2019 14:03:35 UTC] PHP Warning:  Illegal string offset 'output_key' in /var/www/localhost/htdocs/wordpress/wp-includes/nav-menu.php on line 604`

**Comment by bradymiller** [comment]
hi @stephenwaite , I would ignore all the wordpress stuff since not part of OpenEMR.

**Comment by stephenwaite** [comment]
ok, of course, thanks
will start playing with the above demo more since listing the php warnings is really easy with your link
