### ISSUE TITLE
Bug - Apostrophe-name

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#234]
<img width="987" alt="bug-apostrophe_name" src="https://cloud.githubusercontent.com/assets/508784/18412533/e48fa0c8-775e-11e6-834e-38da51a73199.png">

I can't find where Kevin gets the actual patient data for this patient section.
The example used in the picture "Simon O'Grady" is stored correctly in the DB as:
fname | lname =  Simon | O'Grady 

Whereever this data comes from, it needs htmlspecialcharacter work, I think

**Comment by bradymiller** [comment]
Nice catch.
I just committed the fix for this into the main codebase here:
https://github.com/openemr/openemr/commit/87752d6312e6c975524c2595af1e10f602dd6e51
