### ISSUE TITLE
Migrate from Zend2 to Zend3

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2347]
This first needs analysis (ie. how big of a project will this be?).

**Comment by adunsulag** [comment]
@bradymiller Can you assign this to me.  I was going to look into this anyway.

**Comment by adunsulag** [comment]
Here is some relevant documentation on the upgrade path from Zend2 to Zend3.
https://docs.zendframework.com/zend-mvc/migration/to-v3-0/

**Comment by danehrlich1** [comment]
@adunsulag Thanks for this. We are upgrading Smarty 2 to Smarty 3 so this complements that, not least because it also has a 2 and a 3 :)

**Comment by adunsulag** [comment]
So one of the biggest changes to handle for the upgrade to Zend3 is the fact that the dependencies have to be specified explicitly in all the controllers.  Everywhere that getServiceLocator() is called (about 39 places) has to be changed to use an explicit dependency which looks like it involves creating a factory class as part of the work.  I'm still researching more into this but here's a link for relevant information.
https://docs.zendframework.com/zend-mvc/migration/to-v2-7/#servicelocatoraware-initializers

**Comment by bradymiller** [comment]
Sounds like gonna be a whole lot of fun :)
