### ISSUE TITLE
Calendar Time width

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#235]
<img width="1160" alt="cal" src="https://cloud.githubusercontent.com/assets/508784/18410200/4c1ea30a-7729-11e6-8f31-3e7516b16188.png">

Here is the fix:

https://github.com/ophthal/openEMR_2/commit/57afa04daa0f1fae349a4970a678700599eb0ab8

<img width="1038" alt="calendar-time-fix" src="https://cloud.githubusercontent.com/assets/508784/18413219/8de3c50e-776f-11e6-8613-eb69703a32e2.png">

**Comment by bradymiller** [comment]
One of the goals of Matrix's code was to equalize the width of the providers. Note how the width with your changes is more for the first provider and less for the second provider on the calendar.
![image](https://cloud.githubusercontent.com/assets/278968/18415605/2b8cbc6a-77ad-11e6-884f-e5c6e0f19e03.png)

**Comment by bradymiller** [comment]
At least I think that was Matrix was trying to do.

@sharonco-matrix,
To confirm, was this what you were trying to do?

**Comment by bradymiller** [comment]
Here's the related PR(pull request):
https://github.com/openemr/openemr/pull/205

**Comment by sharonco-matrix** [comment]
Yes that'was the goal!

**Comment by ophthal** [comment]
@sharonco-matrix,
Can you see if these small changes negatively impact your changes?

ajax_calendar.css#L190 insert:
   max-width:12px;
and then ajax_calendar.css#L213 insert:
   text-align:center;

This limits the width of the time slot (if at least one provider/location is scheduled) and centers the times in Calendar.
Small thing that really shouldn't bug me, but does...

**Comment by bradymiller** [comment]
@ophthal,
This looks good on testing, so brought it into the codebase. thanks for the contribution.
