### ISSUE TITLE
PSR-4 cannot load classes due to folder name casing

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#2352]
I've been working on getting the unit tests to run on the OpenEMR codebase.  However, the test harness framework when run from the command line can't load some of the PSR-4 classes.   I've verified this on both my Ubuntu 18.04 linux machine as well as from within the docker container install.  The error that gets thrown is:
```
[Wed Apr 03 14:09:42.526738 2019] [php7:error] [pid 18] [client 172.20.0.1:46230] PHP Fatal error:  Uncaught Error: Class 'OpenEMR\\Common\\Logging\\EventAuditLogger' not found in /var/www/localhost/htdocs/openemr/library/ADODB_mysqli_log.php:42\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/library/sql.inc(52): ADODB_mysqli_log->Execute('SET NAMES 'utf8...')\n#1 /var/www/localhost/htdocs/openemr/interface/globals.php(291): require_once('/var/www/localh...')\n#2 /var/www/localhost/htdocs/openemr/interface/login/login.php(34): require_once('/var/www/localh...')\n#3 {main}\n  thrown in /var/www/localhost/htdocs/openemr/library/ADODB_mysqli_log.php on line 42
```
What's weird is the class files load just fine when run from the website.  I verified this by putting logging in the composer class loader and can see the file is loaded fine on Apache.  I'm not sure if there is some weird case insensitivity issues going on here.

The core of the problem is that the `common` folder in OpenEMR violates the PSR-4 naming conventions.  Because the composer.json file is setup as follows:
```
 "psr-4" : {
            "OpenEMR\\Common\\" : "common",
```
Every sub directory below common must follow exactly the namespace naming convention.  In this case to load the  'OpenEMR\\Common\\Logging\\EventAuditLogger' the `logging` folder inside `common` must be uppercased to be `Logging` or we have to specificy the individual namespaces inside the PSR-4 to be spec compliant: https://www.php-fig.org/psr/psr-4/

> When loading a file that corresponds to a fully qualified class name …
> 
> **The contiguous sub-namespace names after the “namespace prefix” correspond to a subdirectory within a “base directory”, in which the namespace separators represent directory separators. The subdirectory name MUST match the case of the sub-namespace names.**
> 
> The terminating class name corresponds to a file name ending in .php. The file name MUST match the case of the terminating class name.

I'm not sure if the directory structure is being read / used for anything else in the codebasebut to fix this problem the easiest fix I can see is just to specify directly the namespaces in the composer.json file.
```
         "psr-4" : {
            "OpenEMR\\Common\\Compatability\\" : "common/compatability",
            "OpenEMR\\Common\\Database\\" : "common/database",
            "OpenEMR\\Common\\Http\\" : "common/http",
            "OpenEMR\\Common\\Logging\\" : "common/logging",
            "OpenEMR\\Common\\Utils\\" : "common/utils",
```
If this looks good to everyone I can submit a pull request to fix the issue.

**Comment by bradymiller** [comment]
hi @adunsulag ,
Thanks for sorting this issue out. I agree with your plan of directly adding the items to the composer.json (this also makes it easier to know where certain classes are by looking at composer.json).
thanks! -brady
