### ISSUE TITLE
Prevent log injection

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2356]
See here for details:
https://www.open-emr.org/wiki/index.php/Codebase_Security#Log_Injection

First item for somebody is to research this and figure out best mechanism to escape stuff that goes to the log.

**Comment by danehrlich1** [comment]
I’ll look into this.

Can you provide some background on how logging is done in OpenEMR at the application code level?

**Comment by bradymiller** [comment]
hi @danehrlich1 ,
Nothing formal, but there are lots of places where error_log() is used to send issues/errors to log. Rec doing grep/search for error_log to get an idea. -brady

**Comment by danehrlich1** [comment]
Got it and good explanation. Thanks.

**Comment by bradymiller** [comment]
Goal would be to have a escaping/sanitizing function (maybe called log_escape) for variables that are sent through error_log available in the library/htmlspecialchars.inc.php library.

**Comment by sjpadgett** [comment]
O'God, please not another escaping function. If you must escape logs, do it in the logging api function. I beg you:)

**Comment by adunsulag** [comment]
@sjpadgett @bradymiller If someone is going to go through the work of sanitizing the error_log I'd recommend also switching error_logs to leverage the Logger class.  I'm already updating the Logger class to be PSR3 compliant as part of the unit tests against the FIHR API.  You can sanitize the entire string instead of just the variables at that level.  

Downside is there's the sanitation overhead, but if the logs are being ignored at the Logger level it will skip over those sanitizing functions.

**Comment by bradymiller** [comment]
hi @adunsulag @sjpadgett ,
The OpenEMR Logger class/code is already complicated and causes real performance issues; prob best to avoid complicating it further. The direct php error logs calls is not done too often in OpenEMR; guessing about 40 places do this where also including a variable in the error_log output. So, will be one of those rarely used escape functions :)

**Comment by morg0n** [comment]
I've been reading up on this and would be absolutely willing to help out!  I might need some guidance / extra advice regarding what to do and how though because I'm pretty unfamiliar with this :)

**Comment by bradymiller** [comment]
hi @morg0n ,
This will be a good project to work on after I get the following PR into the codebase:
https://github.com/openemr/openemr/pull/2426
(currently under code review)

**Comment by bradymiller** [comment]
hi @morg0n , ok, just brought in the above linked PR, so ready for you to work on. For this project, you will wrap variables that are included in error_log command with the errorLogEscape() function. Here are 2 examples:
https://github.com/openemr/openemr/blob/master/library/billing/src/X12_5010_837P.php#L699
https://github.com/openemr/openemr/blob/master/portal/account/account.lib.php#L202

**Comment by sjpadgett** [comment]
Hi @bradymiller , Do ya know the best way to get around having to escape error logging? Don't have any errors!:)
Seriously, aren't we worried about escaping the file writes and not necessarily with passing a string/object in PHP? I don't understand why we can't escape in the logging function. The errors originate outside the UI and wouldn't be any different than passing a variable in any other PHP function.
Or am I being a knucklehead?

**Comment by morg0n** [comment]
Okay, sounds good!  I will start here as directed, and then if the situation changes it will have been good practice haha.

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Not sure how I missed your post; sorry about not responding before bringing in the above commit. This escaping function is only for the php error_log function and not OpenEMR's Logging stuff. The vulnerability is a bit far fetched and is:
1. OpenEMR outputs to the php error log
2. A web based error log reader outputs the php error log to html and is hit with the vulnerable code (my argument is that it should be the error log reader that should be responsible for html escaping, but we live in "super secure" times :) )

**Comment by bradymiller** [comment]
completed here:
https://github.com/openemr/openemr/pull/2469
