### ISSUE TITLE
tab layout - missing the background service logic

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#236]
Need to add the background service logic to the tab layout (this is a mechanism to auto-run background services when users are logged into OpenEMR):
https://github.com/openemr/openemr/blob/master/interface/main/left_nav.php#L393-L411

**Comment by robertdown** [comment]
@bradymiller Should probably get the ball rolling on this. Not something I can tackle right now. @MatthewVita or @Wakie87 or perhaps ViSolve?

**Comment by bradymiller** [comment]
Agreed. I'll add this to my high priority queue.

**Comment by bradymiller** [comment]
Just committed this fix to the codebase:
https://github.com/openemr/openemr/commit/334477ef22bc9861f748e139e5203f08b97aaeed
