### ISSUE TITLE
New UI/UX for patient file (dashboard) screen

### ISSUE THREAD

**Issue by sharonco-matrix** [openemr/openemr#2368]
Hi all, 
We at @matrix are working with professionals in order to have a "new" dashboard.
We want to make it customizable so we can choose which widgets and in which order they appear.
We will be working on this in the next few weeks. If someone wants to help us or contribute to the "technical design" please contact me.

**Comment by adunsulag** [comment]
@sharonco-matrix I've been working through a technical design of how to go about customizing the patient widgets as well as the backend administrative menu system.  My thoughts are centered around the module system and using the EventDispatcher code to create extension points similar to wordpress's hook and filter system.  That said, it is fairly early stage, I'm interested in seeing what your team is thinking for the design / architecture.  What's the best way to reach out?

**Comment by zbig01** [comment]
@sharonco-matrix nice to see interest in UI/UX revamp. I would like to point out that ongoing UI  standardization has been a long and slow process. Please pay attention to the overall styling changes that has already been implemented. Any new changes should be consistent with the overall styling as a tremendous amount of time and effort has already been invested in restyling over a 100 scripts to get to this stage. The Medical dashboard is only a part of the lager redesign.
Thanks and Cheers :)

**Comment by sharonco-matrix** [comment]
@adunsulag if you want you can contact me in mail to schedule a "skype" meeting and talk about it. We are still working on the technical design so i would be very happy to see what you have in mind and we can work together.
@zbig01 we have been working with the community styling all along, if you could be more specific on what we need to pay attention when developing it would be very helpful

**Comment by mdsupport** [comment]
@sharonco-matrix, you could look at our approach detailed on the [community forum](https://community.open-emr.org/t/new-features-improvements/12089).  It provides a generic class that can render various fragments of information about the patient. This permits us to customize number of columns and the contents per role and/or user.  Related code is shared under our contrib branch.

**Comment by sharonco-matrix** [comment]
I just opened a pr not for really integrating it but for everyone to take a look.
I think we are all deriving to the same direction but in different vehicles. Why don't we make an effort to unite forces an finally make this happen? @mdsupport @bradymiller

**Comment by sjpadgett** [comment]
I think serious attention should be paid to this contribution. While I have not looked at in detail, the engineering pattern is proven and solid.
Finally we have a concerted effort in terms of real code addressing this nagging issue and we would be foolish to pass up.
We should look closely here, make a decision and integrate in 5.0.2. No sense waiting another year for 5.0.3 as that release is going to be greatly concerned with MU3, Fhir and continuations of modernization and this would fit nicely with all three.
