### ISSUE TITLE
Syntax error LBF/New.php

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2372]
@bradymiller 
Do ya think you could add a small fix with your next PR for a minor syntax error in forms/LBF/new.php. I'd do it but I have that script staged with a feature add in maybe a week or so.
It's L-688 from
`'&csrf_token_form=' + <?php echo js_url(collectCsrfToken()); ?>));` to
`'&csrf_token_form=' + <?php echo js_url(collectCsrfToken()); ?>);`

Strange it was just that one replace. I haven't seen issue anywhere else thus far but maybe a quick scan by you couldn't hurt.
thanks

**Comment by bradymiller** [comment]
hi @sjpadgett .
Thanks for the report and sorry that got through (I only wish there was some sort of replace function for that stuff :) ). Just committed the fix:
https://github.com/openemr/openemr/commit/d01a6976b6483dcfe45bc095187af26022b6248a
-brady
