### ISSUE TITLE
Medication administration record

### ISSUE THREAD

**Issue by morgankevinj** [openemr/openemr#2373]
Can you add support for a Medication administration record? It would provide the times a medication needs to be administered and record when a medication was administered or withheld.

**Comment by mdsupport** [comment]
If you administer meds in office and use inventory, you can use the 'templates' to set a meaningful name.
e.g. Instead of defining a common shot of Gardasil, define 3 identical dosages for Gardasil#1, Gardasil#2 and Gardasil#3.  Then record appropriate shot when given.

**Comment by robertdown** [comment]
We are currently working on developing a MAR and progress can be followed at [this forum link](https://community.open-emr.org/t/inpatient-the-plan/11309).
