### ISSUE TITLE
Carecoordination Module Send to HIE Broken 

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#2376]
In working on the zend framework upgrade research I've been testing the functionality on the Carecoordination module.  I followed the instructions on the wiki to install the Carecoordination module including enabling the hooks.  That creates the Modules -> Carecoordination -> Send to HIE menu structure.  However, if you click the Send to HIE menu it brings up a 404 frame as it can't find the URL: /openemr/interface/modules/zend_modules/encountermanager

This appears to be a long standing problem as I verified the bug exists in 5.0.1 and in the latest development version.  

It looks like in order to access the care coordination module (https://www.open-emr.org/wiki/index.php/Use_the_Carecoordination_module) you have to disable the send to hie hooks.  My question is the Send to HIE functionality deprecated and we should remove that functionality from the module module altogether?

There's a number of bugs to be fixed in MainMenuRole to get things working but I wanted to verify how critical that is if the Send To HIE is the only thing that uses this sub navigation concept.

**Comment by bradymiller** [comment]
hi @adunsulag ,
That Send to HIE never did anything and appears to be just a placeholder. So, it can go.

**Comment by bradymiller** [comment]
btw, here is what I am referring to:
![image](https://user-images.githubusercontent.com/278968/55896829-16e5be80-5b74-11e9-8b7d-beac331da205.png)
Note the main menu, though should not include a Send to HIE link:
![image](https://user-images.githubusercontent.com/278968/55896887-37157d80-5b74-11e9-8eaa-2ce7d024d644.png)

**Comment by sjpadgett** [comment]
Hi, I'm pretty sure HIE works and you need to configure ccdaservice so a CCDA can be generated to send. Once doc is generated it is then queued and saved to be picked up for sending. The ccda generation originally(and maybe still) was generated on a mirth server managed by ZH. I wrote the ccdaservice as an alternative.
I don't recall seeing any server side code for sending the document and decided to write my own hooks for sending documents (not in codebase custom hie). But, if I recall, i've tested this before I decided to manage documents another way.
Brady, are you sure this was not a requirement for MU2?

**Comment by bradymiller** [comment]
hi @sjpadgett and @adunsulag ,
The CCDA creation/import is a requirement of MU2, but the send to HIE is not. I always assumed it didn't do anything. Probably makes sense then to check out the code to confirm it does nothing. Note the hooks don't always work since the module needs to be configured in certain ways to support certain hooks.

**Comment by sjpadgett** [comment]
I know the encounter hooks don't work but in the end, FHIR will most likely be the goto for this type of functionality and i'm not sure if anyone would be willing to pick this up because, using this hie to report to externals such as state medicaids are diverse and require certification. So, I have no prob if it goes.

**Comment by adunsulag** [comment]
@bradymiller @sjpadgett So I'm trying to verify my zf3 upgrade changes work for the CCDA download/creation piece.  However, I've confirmed what @sjpadgett said about a MIRTH server being required to create the CCDA piece.  How are people typically testing this to make sure it works?  Does ZH offer their mirth server for free access to people?  Or is there somewhere I can go to download the channels that are used for the MIRTH to test this?

If its a paid service to use the ZH Mirth service then how are people meeting MU2 without going through ZH or is that the only possibility, outside of doing what @sjpadgett did and writing their own custom thing. 

I'm also confused by the code.  It looks like we generate all of the XML data for the CCDA but we still send it to the MIRTH server, I'm assuming to transform it to the appropriate format?

**Comment by sjpadgett** [comment]
> I'm also confused by the code. It looks like we generate all of the XML data for the CCDA but we still send it to the MIRTH server, I'm assuming to transform it to the appropriate format?

I wrote the ccdaservice specifically to avoid sending to ZH. Look at the readme in /openemr/ccdaservice directory. It will create ccda as if being sent to ZH. You must make sure you have not pulled the hie hook code that redirects from going to ZH to localhost. This is also config'ed in CCM setup under mirth url where you would put localhost and setup provider etc. Most of this is in readme.

**Comment by adunsulag** [comment]
@sjpadgett I haven't removed any of the HIE hooks.  My intent is to avoid removing any code and focus on  just upgrading the framework.  I've been marking places in the code where I believe classes / functions can be removed as they are unused.  

Now that you've explained things the Readme makes more sense.  The docker images I'm using off the wiki don't have the npm libraries for it installed.  Is that something we need to add as a work item so people can generate these things without having to use ZH?  Or is there a docker image already that does this? @bradymiller

**Comment by sjpadgett** [comment]
Because of a couple os specific dependencies that need to be compiled on windows(Linux are precompiled and downloaded) it would be difficult to precompile the node tree for the project and make part of the npm project I setup for OpenEMR. Plus almost always node would need to be installed but many are using the feature and the install hasn't seem to befuddle anybody too much.
It would be great if you could automate.

**Comment by sjpadgett** [comment]
Closing this because it is just not implemented for the HIE interop to distant however queueing documents worked last I checked. Okay @adunsulag ?

**Comment by adunsulag** [comment]
That works for me.
