### ISSUE TITLE
whitescreen when saving globals

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2399]
> [Sun Apr 28 16:17:48.507231 2019] [php7:notice] [pid 894] [client 172.22.0.1:55346] OpenEMR Error : Decryption failed authentication., referer: http://localhost:8300/interface/super/edit_globals.php

> [Sun Apr 28 16:17:48.507308 2019] [php7:notice] [pid 894] [client 172.22.0.1:55346] OpenEMR Error : Key creation is not working - Exiting., referer: http://localhost:8300/interface/super/edit_globals.php

**Comment by bradymiller** [comment]
Likely means you don't have write permission to:
sites/default/documents/logs_and_misc/methods/

Is this also happening on the dev demos?

**Comment by bradymiller** [comment]
Another possibility is didn't clear the prior docker volume before doing docker-compose up

**Comment by stephenwaite** [comment]
ok, thank you @bradymiller
