### ISSUE TITLE
tab layout - not all menu items are represented

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#241]
Not all menu items are represented in the tab layout(for example, missing the offsite and CMS portal menu items). Need to go through and ensure all the menu items are represented.

**Comment by bradymiller** [comment]
Many of the menu elements are missing acl checks and global checks.

**Comment by bradymiller** [comment]
Following elements are completely missing:
Portal Activity (will make a top-level 'Portal' menu item)
CMS Portal (will make a top-level 'Portal' menu item)
Charges
Inventory
Management
Destroyed
New Crop
Status
e-Rx
e-Rx Renewal
e-Rx EPCS

**Comment by robertdown** [comment]
#280

**Comment by bradymiller** [comment]
Ongoing work is being tracked on this PR:
https://github.com/openemr/openemr/pull/302

**Comment by bradymiller** [comment]
This project is completed and ready for review here:
https://github.com/openemr/openemr/pull/302

**Comment by bradymiller** [comment]
Just brought this into the codebase.
