### ISSUE TITLE
Remove function html_header_show() instances

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2417]
No longer used and while we're at cleaning up code wellll, why not.

**Comment by morg0n** [comment]
I can help!

**Comment by sjpadgett** [comment]
Thanks @morg0n,
Give me a day to maybe add to this. Stuff like adding dirname(__FILE__) or at min './' to requires with relative paths as needed.
Also maybe note jquery version and check back with me to determine if we can update to current version ie 3.1.1.

**Comment by morg0n** [comment]
I got excited and did some things - I hope that wasn't terribly rude

**Comment by sjpadgett** [comment]
Not rude at all my friend. It's good for the soul to contrib to a worthy cause, is it not?

**Comment by morg0n** [comment]
Most definitely :) ~! It's the greatest Paladin playthrough!

**Comment by bradymiller** [comment]
Issue fixed and closing. thanks @morg0n !
