### ISSUE TITLE
tab layout - Zend module feature not working

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#242]
1. The Modules->Manage Modules is buggy
2. After add the modules, then able to see all of them in Modules as menu items which is a bug. Should only see the Care Coordination module menu item.

**Comment by Wakie87** [comment]
To actually get the modules working 
https://github.com/openemr/openemr/blob/master/interface/main/tabs/menu/menu_updates.php#L45
needs to be
`$relative_link ="/interface/modules/".$modulePath."/".$modulerow['mod_relative_link'].$added;`

Still can't get the ACL working.

**Comment by bradymiller** [comment]
I think the disallowed stuff is left_nav specific. Guessing that the following may get it to work:
``````
if (!zh_acl_check($_SESSION['authUserID'],$acl_section)) continue;

**Comment by bradymiller** [comment]
ok, fixed the menu bugs and committed these fixes to the codebase:
https://github.com/openemr/openemr/commit/4705d3ddeb794ef447ba537259d22e1e378919ce

Next, have the following Zend Module bugs to fix:
1. Titles (need this for the tab to get a title) in the Module Installer and Care Coordination scripts.
2. In the Module installer, when click Enable or Disable, the button/script is not updating (need to do a manual refresh to see the change in the button). And with following js error: TypeError: parent.left_nav.location is undefined

**Comment by Wakie87** [comment]
Fixed the title of the tabs with 6e088d5.

**Comment by bradymiller** [comment]
thanks!
How does that translate() function work? I can't see where it is using the current translation engine in OpenEMR?

**Comment by bradymiller** [comment]
Fixed the Zend Module installer with https://github.com/openemr/openemr/commit/27fe946c7e8002beeccb4b06d5be9ca3ad397db9

**Comment by bradymiller** [comment]
I have a plan to fix the translate function titles also. After that is done, will then close this issue.

**Comment by bradymiller** [comment]
Actually. The layout issue is fixed, so will close this.
