### ISSUE TITLE
Appointment persists after editing for recurrtype 3

### ISSUE THREAD

**Issue by epsdky** [openemr/openemr#244]
If a recurrtype 3 (Days of Week) appointment is edited by unchecking a week day that corresponds to an individual appointment with date equal to pc_eventDate, an individual appointment corresponding to that weekday will persist (with date equal to pc_eventDate)

The fix is [here](https://github.com/openemr/openemr/pull/243)

EDIT - added detail to description.

**Comment by bradymiller** [comment]
Thanks for the fix. Just brought this into the codebase.
