### ISSUE TITLE
Add publiccode.yml

### ISSUE THREAD

**Issue by nemobis** [openemr/openemr#2451]
Would you be interested in a patch to add a metadata file like https://github.com/globaleaks/GlobaLeaks/blob/master/publiccode.yml ? It's necessary to be included in https://developers.italia.it/en/software/ , the list of free software which the Italian state will heavily advertise to the public sector in Italy.

**Comment by bradymiller** [comment]
hi @nemobis ,
Definitely would be interested. Just submit a PR.
