### ISSUE TITLE
procedure error

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2452]
If I enter in a procedure order in encounter->Administration->Procedure Order and then go back to the encounter screen, get following sql error:
![image](https://user-images.githubusercontent.com/278968/58450141-83843080-80c2-11e9-948d-dcc6931f0043.png)

**Comment by stephenwaite** [comment]
more picking on @sjpadgett :)
when brought in https://github.com/openemr/openemr/commit/52fb369a2bedb134bc1db3cc634c3d4c2c9eae17

looks like in https://github.com/openemr/openemr/blob/master/interface/orders/single_order_results.inc.php#L328 the po.order_diagnosis field needs to be changed to pc.diagnoses where pc is procedure_order_code

**Comment by sjpadgett** [comment]
nope, I added new feature to procedure order of a auto primary diagnosis field not in codebase yet. they're pulled from problems and issues so you don't have to add a diagnosis to each test. I'll add afix in batch PR i'm trying to put up tonight.

**Comment by sjpadgett** [comment]
Decided to add missing column to table so will be ready when I get around to bringing in improved procedure orders form.
https://github.com/openemr/openemr/pull/2466

**Comment by stephenwaite** [comment]
have you noticed @sjpadgett how the code select is non-intuitive? for instance if you go to select a dx it will add it but doesn't notify you that it's been added and expects you to close the window (before you click on other dxs and bring those in too which you then have to delete but you have no idea of what you're deleting? :) )

guess i should have started a new issue :)

**Comment by sjpadgett** [comment]
I have Stephen. Something i've had thoughts on like adding a selected panel in the finder that allows one to both see what has been selected and/or edit selections in the finder.
It could get dicey to popup finder and put in single select mode and auto close after each selection with the dicey part being delete. Thats why you can't delete one code from a list but all codes are deleted.
I suppose I could look into some.

**Comment by bradymiller** [comment]
confirmed this fix in codebase. thanks @sjpadgett and @stephenwaite !!
Gonna close this issue (trying to close issues to get ready for the release :) ); rec making another issue if plan how to improve code select.

**Comment by stephenwaite** [comment]
thank you @bradymiller, thanks for the nice improvements Jerry :)
