### ISSUE TITLE
Add New Issue / Edit Issue window list box bug

### ISSUE THREAD

**Issue by epsdky** [openemr/openemr#247]
In the Add New Issue / Edit Issue window the Title list box is populated with list IDs instead of list Titles (which are not translated).

[Here](https://github.com/openemr/openemr/pull/246) is the fix.

**Comment by bradymiller** [comment]
https://github.com/openemr/openemr/pull/246

Merged your fix into the codebase(placed some comments on the PR regarding the translation of issue list titles). Thanks for the fix!
-brady
