### ISSUE TITLE
try to remove directories that travis psr2 check ignores

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2483]
See here for the ignored directories. Just try one at a time and see what happens.
https://github.com/openemr/openemr/blob/master/ci/ci.sh#L44-L50

**Comment by stephenwaite** [comment]
when I commented out the .php line resulted only in a ton of smarty errors, like `/var/www/localhost/htdocs/openemr/sites/default/documents/smarty/main/%%61/61F/61F56BD5%%default.html.php` and the sqlconf.php file; also had to set php.ini script memory to 1G

**Comment by bradymiller** [comment]
I think I should of dropped this issue when I did this commit:
https://github.com/openemr/openemr/commit/3dc0f6284da2eb14b59cf04362e60debbbb709a8

I think you found another issue though. What specific line did you remove?

**Comment by stephenwaite** [comment]
commented out https://github.com/openemr/openemr/blob/master/ci/ci.sh#L44 (put a # at the beginning of line)

**Comment by bradymiller** [comment]
Sorry, I led you astray (since have already removed all the special directories from that line). Definitely don't want to remove that line since it basically seeks through all php files and can't remove it.

**Comment by bradymiller** [comment]
If you are looking for a project related to this ci stuff, then a good one would be supporting most recent version of squizlabs/php_codesniffer:
https://github.com/openemr/openemr/blob/master/ci/ci.sh#L31

This is what is used in the psr2 stuff:
https://github.com/openemr/openemr/blob/master/ci/ci.sh#L48

And it now breaks in php 7.3, which is why we have it running for php 7.2 instead of 7.3:
https://github.com/openemr/openemr/blob/master/.travis.yml#L13

Btw, when you do this, the nice thing is you can just push a PR to test it

-brady

**Comment by bradymiller** [comment]
posted a new issue for above here:
https://github.com/openemr/openemr/issues/2518

**Comment by stephenwaite** [comment]
no prob, will check it out, thank you
