### ISSUE TITLE
I mistakenly added a contact information of a patient

### ISSUE THREAD

**Issue by TomHsiung** [openemr/openemr#2486]
Hello, sir

I mistakenly added a wrong address of my patient. How to delete the wrong address from the system? Thank you.

Tom

**Comment by mdsupport** [comment]
[Community forum](https://community.open-emr.org/) is a good resource for this.

**Comment by TomHsiung** [comment]
Got it. The administrator is able to modify these and other information under Administration > Lists.

Tom
