### ISSUE TITLE
reorganize/Caching Client Side

### ISSUE THREAD

**Issue by joshuaaguilar20** [openemr/openemr#2496]
Looking to reorganize the structure of this project. I find the Achilles heel of the entire project is the structure. I would love to seperate the Js from the PHP files, removed a lot of unused functions, updates.

What I generally do is :

    put as much JS as possible in a .js file (for caching on the client-side and all that)
    this JS code uses a JS variable
    that JS variable is declared / initialized from a PHP file ; this is the only part where you need some code executed on the server-side***** 

For instance, I would have something like this, I suppose :

my-file.php :

var thisIsMyJSVar = '<?php echo $test; ?>';

So, in PHP, we declare tha variable and set its value. This is the "dynamic" part.

and, in my-file.js :

//when the DOM is ready  
$(document).ready(function(){  
    //settings on top  
    var domain = 'http://something.name/';  
    var initialPosts = thisIsMyJSVar;  // Use the JS variable declared in the PHP file
    //function that creates posts  
    var postHandler = function(postsJSON) {  
        $.each(postsJSON,function(i,post) {

Here, in the static JS file, we only use the value ; nothing here is dynamic, and this file can be cached by the client -- to not be re-downloaded on each page.

The problem with that idea is the JS file depends on some initialisation done in the PHP file* I find this to be the biggest issue in open emar. 

So, it might be a good idea to have a "default value" in the JS file, just in case...

 it might be a good idea, actually, to put all your "configuration variables" inside a single javascript object, to not pollute the global namespace...

**Comment by joshuaaguilar20** [comment]
So between your server code and your client code, the uniq glue you've to put is the model object in Json format (or whatever format you need). This way, you can develop code in the view that is reusable by any kind of server code, and thus, you can develop your application logic with different server technologies.

**Comment by adunsulag** [comment]
@joshuaaguilar20 What you propose is fairly ambitious recognizing that the codebase is hundreds of thousands of lines of code.  Your more than welcome to start chipping away at this kind of thing by creating pull requests.  Although its probably best to start in an area you are interested in to stick with the refactoring. 

You can look at how other projects do this for example wordpress's localize script functionality for injecting dynamic values into the javascript. https://codex.wordpress.org/Function_Reference/wp_localize_script

Note that as the project moves more towards consuming APIs and leveraging javascript such as in the recent React proposal that @sharonco-matrix put forth this will become less of an issue.
https://github.com/openemr/openemr/pull/2477

You may find that pitching your effort into collaboration on that above referenced pull request will do more to helping you separate the JS in the codebase from the PHP than taking an adhoc approach as you are targeting specific functional replacements.

Just my 2cents.
