### ISSUE TITLE
tab layout - ability to drag and drop the tabs

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#251]
Add ability to be able to drag and drop the tabs (ie. reorganize them) in the tabs layout.

**Comment by rishabhemr** [comment]
We have started working on this issue and will be able to submit code for review by next week. 

Rishabh Software

**Comment by rishabhemr** [comment]
We have made the changes in the above commit regarding closing tab with drag and drop tabs feature.
#251 and #290

Rishabh Software

**Comment by stephenwaite** [comment]
with recent work on `oedraggable` going to bump this
