### ISSUE TITLE
backup.php 7.3 warning

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2515]
six.openemr.io doesn't have Archive/Tar.php class; guess most php installs don't unless PEAR is installed

`[25-Jun-2019 15:38:22 UTC] PHP Warning:  include_once(Archive/Tar.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/a/openemr/interface/main/backup.php on line 63
[25-Jun-2019 15:38:22 UTC] PHP Warning:  include_once(): Failed opening 'Archive/Tar.php' for inclusion (include_path='.:') in /var/www/localhost/htdocs/a/openemr/interface/main/backup.php on line 63`

looks like the only valid reason for this include
https://github.com/stephenwaite/openemr/blob/master/interface/main/backup.php#L63
is to help a windows user make a backup

maybe could add this to composer, https://packagist.org/packages/pear/archive_tar

**Comment by bradymiller** [comment]
hi @stephenwaite , Good catch. Recommend doing this, and then can also remove these blocks of code:
https://github.com/openemr/openemr/blob/master/interface/main/backup.php#L65-L75
https://github.com/openemr/openemr/blob/master/interface/main/backup.php#L713-L715
https://github.com/openemr/openemr/blob/master/interface/main/backup.php#L722-L738
