### ISSUE TITLE
tab layout - Use the 'Main Top Pane Screen' global to populate the first tab when login

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#252]
Use the Administration->Globals->Appearance->'Main Top Pane Screen' to populate the first tab after a user initially logs in to OpenEMR.

**Comment by robertdown** [comment]
Could add the ability to "favorite" a tab which makes it always open upon login. Would need to be user-setting specific.

**Comment by bradymiller** [comment]
@mdsupport has some nice logic for remembering user settings automatically. Could leverage this to open the same tabs on login that were opened when a user logged out.

**Comment by bradymiller** [comment]
Notably, there is logic in tabs that does use Administration->Globals->Appearance->'Main Top Pane Screen' to populate the first tab, but it's odd and not working well. It is placing the url in a GET parameter when it calls the main.php script which doesn't make much sense since the global is always available. Also need to map it to the correct 3 letter window tab mapping (ie. 'pat', 'flb', etc.)

**Comment by bradymiller** [comment]
Actually, the GET parameter mechanism is necessary to keep. So, need to figure out way to map to the 3 letter window tab with the possibilities.

**Comment by bradymiller** [comment]
Just committed a fix for this to the codebase:
https://github.com/openemr/openemr/commit/0444ab2f56ad877e0009aefac6fad7595907ad13
