### ISSUE TITLE
Tabs overflow

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#253]
On testing the new tab approach, new targets for a lot of windows, I am able to open more tabs than there is room to display.

<img width="982" alt="taboverflow" src="https://cloud.githubusercontent.com/assets/508784/18573745/6dde24ce-7b94-11e6-95fc-64defd08ec1b.png">

There may need to be a maximum number of tabs or a maximum width, which whenever this width is reached, maybe auto shorten the large titles to something like 8 characters.  

Maybe this makes sense:
Since this is knockout.js, the fix needs to be located here.  There should be a way in the Model to discern width of each opened tab, based on the length of the Tab’s Title + icons perhaps, add this tab width as an observable item or attribute of a current tabs observable, and whenever a new tab is added, a computed observable which adds up all the open/current tabs widths. If the totals tabs width is > window.width,  then shorten the non-active titles as coded (maybe > 10 shorten to 8) is performed for each tab in the View.  
Now how to write that is a different thing entirely.
Or something else...  Maybe limit the view to a max of 5 tabs?

Ray

**Comment by bradymiller** [comment]
css has a nice way to shorten strings:
https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

I only know this because Matrix has done it in several places in the calendar code recently.

**Comment by bradymiller** [comment]
I like the complicated way you described, but I agree that translating that into code will require significant resource investment. Another mechanism to consider is a scrolling mechanism for the tabs themselves. Having both of these mechanisms at the same time would be ideal. Whoever does take this on will likely become a knockout expert by the time they are done (assuming they are still breathing of course).

**Comment by bradymiller** [comment]
I just brought in fixes by sukhjeet81 that fixes this issue. The solution simply has css create a scrollbar when needed. It works well. Will close this issue for now; if a developer/user still thinks more work is needed on this, then feel free to reopen this issue.

**Comment by rishabhemr** [comment]
Sukhjeet81 is from Rishabh Software has fixed this code with email id sukhjeet.singh@rishabhsoft.com. 
This may be added under rishabhemr. I am not able to add his email id in **rishabhemr** account. Henceforth he will use rishabhemr git repository instead of his. 

Thanks
Srinivasa Rao Challa (Rishabhemr)
Rishabh Software

**Comment by bradymiller** [comment]
Do note that is the email address that is listed in the author information for the commit:
``````
commit 3af334743df79efc64382ee2f6007f25f382e987
Author: sukhjeet81 <sukhjeet.singh@rishabhsoft.com>
Date:   Sat Oct 8 11:10:18 2016 +0530

    Tabs overflow #253. (#307)
    
    Made changes in the css file
    added --  overflow:auto;

**Comment by bradymiller** [comment]
Also, thanks for clarifying this was from Rishabh Software(and thank you for the contribution!). To ensure credit, could also place this information within the github commit in future commits.

**Comment by rishabhemr** [comment]
Brady,

Thanks for this help. From now onwards, we will make sure all commits from Rishabh Software are made from rishabhemr account only.

Thanks
CS Rao
