### ISSUE TITLE
Allow Onsite Patient Ledger setting is not doing what it is supposed to

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2537]

**Comment by sjpadgett** [comment]
hmm, will look. also, new session stuff has wrong path in some places, maybe(found when updating my new features to current codebase). still looking at that.

**Comment by sjpadgett** [comment]
@bradymiller Is the fact when allow ledger in globals is off the Accounting menu item is turned off in portal this issue? ie can't make a payment.

**Comment by bradymiller** [comment]
hi @sjpadgett , the issue is that was not even getting Accounting menu item when the allow ledger globals was on. Turns out just needed to change a `&&` to a `||`  :)
Fixed this issue here:
https://github.com/openemr/openemr/pull/2584
