### ISSUE TITLE
non-numeric value in billing

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2540]
https://github.com/openemr/openemr/blob/master/src/Billing/BillingUtilities.php#L1668

**Comment by stephenwaite** [comment]
leaves a php warning as it has for a while but Rod knew that this needed to be in place for currency context

**Comment by sunsetsystems** [comment]
What's the warning?

**Comment by bradymiller** [comment]
[08-Jul-2019 19:57:29 UTC] PHP Warning:  A non-numeric value encountered in /var/www/localhost/htdocs/a/openemr/src/Billing/BillingUtilities.php on line 1668

**Comment by sunsetsystems** [comment]
So instead of "0 + $tmp['copay']" you probably want "floatval($tmp['copay'])". Seems this started with PHP 7.1.
