### ISSUE TITLE
Internationalization of words with different meanings

### ISSUE THREAD

**Issue by dimitristsilis** [openemr/openemr#2546]
Some words (like "To") have different meanings according to context. For example, "To" can refer to a span of some kind (e.g. "to date"), to a destination (e.g. "send to") etc.
The problem is most obvious with dates and search criteria.

1. It would be great if, from now on, developers keep this in mind and tag their constants using the double curly braces system "{{tag}}", explaining them, since, to date, constants cannot be form specific.
In this case, care should be taken to tag existing constants without altering translations, since there are unaffected languages.

2. To tackle this issue better, perhaps a UI for internationalization could be created, where translators would pick their language, and while using openEMR like normal, they would click on constants and translate them in a popup window. All constants would be automatically highlighted and not shown as regular english words.

**Comment by bradymiller** [comment]
hi @dimitristsilis ,
Agree that many improvements are needed. This stems from the fact that I only added the {{tag}} mechanism about 4 years ago, so it hasn't really been incorporated into much of the codebase. Would be nice to have somebody go through the codebase and address the more obvious ones (like To for example). Regarding item 2, this would be nice, although would definitely require marked amount of development and translation infrastructure work.

**Comment by dimitristsilis** [comment]
Hello @bradymiller,
Will definitely do #1 when I get back to my dev pc. 
Agree that #2 needs time and effort and looks like no developers are interested in working on internationalization :(

**Comment by bradymiller** [comment]
yep @dimitristsilis ,
It is tough to get devs interested in this. Matrix has done a bunch of nice work to support RTL in addition to some internationalization fixes. But internationalization otherwise does not have a dev championing it (we do at least have a robust system to collect constants and maintain translations, but still a whole lot that can be done here).

**Comment by boxlady** [comment]
I would be interested in helping out with internationalization. Not sure how to going about doing number .2 though would have to give it some thought/research.

**Comment by dimitristsilis** [comment]
Hi @boxlady, 
Ideally there would be a "translation mode" version of each xl function, which would make every constant a clickable button bringing up a popup with the clicked constant and a text input for the translation. OpenEMR would know if it should run the standard or "translation mode" version of xl functions via a global setting or a session variable.
If we manage to do that, the next step will be to settle if we want form specific constants(my preferable solution) or keep the current system, in which case there should be a system to automatically create new tagged constants (and change the form's code accordingly) if the same constant was already translated differently.

**Comment by tywrenn** [comment]
Bumped
