### ISSUE TITLE
dlgopen() issue -- “Undo Checkout” sometimes fails to load dialog box

### ISSUE THREAD

**Issue by TheYairDa** [openemr/openemr#2549]
Follow-up from forum post here:
https://community.open-emr.org/t/undo-checkout-sometimes-fails-to-load-dialog-box-dlgopen-issue/12417

I've replaced dlgopen() with the legacy dlgOpenWindow() which resolved the issue, so it's definitely to do with dlgopen().

From the forum post:

**Situation**
In the 'Checkout' submenu under 'Fees' pressing the 'undo checkout' link fails to load the following dialog box:
![image](https://user-images.githubusercontent.com/46237982/61026057-9e91d200-a3dc-11e9-89a6-fe34ee3c9e81.png)

It goes from this:
![image](https://user-images.githubusercontent.com/46237982/61026064-a3568600-a3dc-11e9-9ba0-5f42a959be87.png)

To this:
![image](https://user-images.githubusercontent.com/46237982/61026071-a81b3a00-a3dc-11e9-996b-503cc7845c60.png)

But the dialog box never loads, and thus we can't undo a checkout currently.

Two workarounds that seems to work are:
1. right clicking and selecting 'reload frame' seems to work, but it usually needs to be done more than once. After a few reloads, the dialog box appears upon clicking 'undo checkout'.
2. Without fail, after opening chrome dev tools the dialog box appears upon clicking 'undo checkout'.

My thinking so far is:
- Perhaps this is an issue with the dlgopen() function here, which is located in dialog.js:
```
        function deleteme() {
         dlgopen('deleter.php?billing=' + <?php echo js_url($patient_id.".".$encounter); ?> + '&csrf_token_form=' + <?php echo js_url(CsrfUtils::collectCsrfToken()); ?>, '_blank', 500, 450);
         return false;
        }
```
I've tried remove the console.log calls in the function (thinking that dev tools works because console is open), but that had no effect. Perhaps it is a caching issue with ajax and XMLHttpRequest? Though I'm not sure how to approach that, and clearing cache hasn't seemed to have an effect.

Here is what my dev tool console shows (upon successful loading of the dialog box, because the dialog box always loads when dev tools is open):

![image](https://user-images.githubusercontent.com/46237982/61026151-e7e22180-a3dc-11e9-84b1-7452516b15d4.png)

As you can see, there is a deprecation  error there regarding XMLHttpRequest.

```
dialog.js?v=:130 Needed to load:[ /openemr/public/assets/bootstrap-3-3-4/dist/css/bootstrap.min.css ] For: [ http://medconsultemr.com/openemr/interface/patient_file/pos_checkout.php?framed=1 ]
dialog.js?v=:134 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
includeScript @ dialog.js?v=:134
(anonymous) @ dialog.js?v=:302
j @ index.js:2
k @ index.js:2
setTimeout (async)
(anonymous) @ index.js:2
i @ index.js:2
add @ index.js:2
(anonymous) @ index.js:2
Deferred @ index.js:2
then @ index.js:2
r.fn.ready @ index.js:2
r.fn.init @ index.js:2
r @ index.js:2
dlgopen @ dialog.js?v=:279
deleteme @ pos_checkout.php?framed=1:80
onclick @ pos_checkout.php?framed=1:154
dialog.js?v=:144 Needed to load:[ /openemr/public/assets/bootstrap-3-3-4/dist/js/bootstrap.min.js ] For: [ http://medconsultemr.com/openemr/interface/patient_file/pos_checkout.php?framed=1 ]
dialog.js?v=:144 Needed to load:[ /openemr/public/assets/jquery-ui-1-12-1/jquery-ui.min.js ] For: [ http://medconsultemr.com/openemr/interface/patient_file/pos_checkout.php?framed=1 ]
dialog.js?v=:709 Modal loaded and sized! Content:338 Viewport:338 Modal height:100.0000vh Max height:96vh isHeader:False  isFooter:False
```

Thanks in advance.

**OpenEMR Version**
I'm using OpenEMR version 5.0.1 patch 7 (latest)

**Browser**: 
I'm using: Chrome, latest version.

**Operating System**
I'm using: Windows 10 64bit

**Logs**
No errors showing in the apache error log.

The cache clearing code `<script type="text/javascript" src="../../../library/dialog.js?v=<?php echo $v_js_includes; ?>"></script>`  is [already included](https://github.com/openemr/openemr/pull/411) in pos_checkout.php

**Comment by sjpadgett** [comment]
i'll look at this. not sure if this ever worked.
