### ISSUE TITLE
Use nation notes templates in any encounter text box- out of scope

### ISSUE THREAD

**Issue by eyalvo-matrix** [openemr/openemr#2550]
Hi @sjpadgett this new feature is out of scope and works in any text area in the system and is not limited to the encounter text box. can you please limit it to the encounters and preferably add a global to disable it ?

**Comment by sjpadgett** [comment]
can do...

**Comment by sjpadgett** [comment]
@eyalvo-matrix Are your users still mostly using IE11? Fair warning that ES6 will be much more widely used in next release. Also, I had this feature PR open and advertised for over two weeks for comments prior to bringing in.

**Comment by matrix-amiel** [comment]
Hi @sjpadgett 
Would you know when the fix will be ready? 

Thanks

**Comment by eyalvo-matrix** [comment]
Hi @sjpadgett ,  sorry for the hassle we didn't review this new code deeply until it was too late.
regardless and unrelated to our needs personally I don't think binding an event to every input in the system without a global is a safe idea. In any case, thank you for your wiliness to add the global.
To your question yes some of our users unfortunately still use IE11 we are working to change that but it takes time since IT teams do not love changes :) I raised this flag as high as I can.
I do understand the necessary need to move to ES6 and it is blessed.

**Comment by sjpadgett** [comment]
@matrix-amiel I'll try to get it done today.
@eyalvo-matrix I had actually not intended to have the global scope for the feature until I added a new global var test in header config to include/exclude a dependency. Something i've been wanting to do for a while. Any rate, I am just going to remove the global config dependency until we see how it goes in production and I do some work on nation notes.
Will let you all know here when I merge PR.

**Comment by sjpadgett** [comment]
Okay, PR https://github.com/openemr/openemr/pull/2558 merged.

**Comment by stephenwaite** [comment]
awesome feature, thank you @sjpadgett
