### ISSUE TITLE
Translation spreadsheet not updated

### ISSUE THREAD

**Issue by dimitristsilis** [openemr/openemr#2575]
Translation spreadsheet doesn't contain the new constants created when descriptions were added to some of them. When will we be able to translate them?

**Comment by bradymiller** [comment]
Hi @dimitristsilis,
I generally run the pipeline (several perl scripts and manual pain described here: https://github.com/openemr/openemr/blob/master/contrib/util/language_translations/README) to update the translation spreadsheet several times per year. Will likely run it again in a month or two (will have more time after we release 5.0.2 in a couple weeks). If you need the constants/translations in your local install, you can enter them in at Administration->Other->Language
