### ISSUE TITLE
500 error on API auth request

### ISSUE THREAD

**Issue by emahnovets** [openemr/openemr#2578]
HI guys.

I'm trying to use Rest API, but I've got **500** error during auth request:

**POST** /apis/api/auth
```
{
    "grant_type":"password",
    "username": "admin",
    "password": "pass",
    "scope":"default"
}
```

Logs from apache:
```
[Wed Jul 24 15:37:18.422798 2019] [php7:warn] [pid 28] [client 37.17.65.98:65127] PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/../src/Common/Session/SessionUtil.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/openemr/_rest_config.php on line 14
[Wed Jul 24 15:37:18.422827 2019] [php7:error] [pid 28] [client 37.17.65.98:65127] PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/../src/Common/Session/SessionUtil.php' (include_path='.:/usr/share/php7') in /var/www/localhost/htdocs/openemr/_rest_config.php on line 14
```

I'm using official docker image. 

Any ideas?

Thanks.

**Comment by sjpadgett** [comment]
@emahnovets  Recently fixed here https://github.com/openemr/openemr/pull/2572

**Comment by bradymiller** [comment]
hi @emahnovets , What docker image are you using?

**Comment by emahnovets** [comment]
@bradymiller @sjpadgett Hi guys, currently we are using `openemr/openemr:5.0.3`. When do you expecting next release with fix from #2572 ?

**Comment by bradymiller** [comment]
hi @emahnovets ,
I rebuilt that today, so is now fixed. You'll need to pull it again to get most recent (`docker pull openemr/openemr:5.0.3`). Do note that is basically the development version and usually build that docker once a week or so.

**Comment by emahnovets** [comment]
@bradymiller Thanks a lot.

**Comment by bradymiller** [comment]
btw, if goal is to get most uptodate development codebase, then recommend looking at the flex docker. It basically will download most recent codebase when you bring it up:
https://github.com/openemr/openemr-devops/tree/master/docker/openemr/flex-3.10

**Comment by emahnovets** [comment]
@bradymiller Thanks, thats will be helpful
