### ISSUE TITLE
Tussenvoegsel / Surname-Prefix / Double Surname

### ISSUE THREAD

**Issue by boxlady** [openemr/openemr#2595]
Tussenvoegsel , Surname-Prefix and Double Surname. I know the Dutch use Tussenvoegsel which is a prefix before the last name like Vincent van Gogh. Van is a Tussenvoegsel  are not included when sorting alphabetically. So if you were to sort last names Vincent should be with the G's not V's. I know there are some other countries with similar things. My question is, is it the same? I would like to add this to Openemr.

**Comment by robertdown** [comment]
This can be accomplished by adding a field to the Demographics Layout. Here is an example of the encounter form with that field added. 
![tussenvoegsel](https://user-images.githubusercontent.com/1381170/62913599-c7e6aa80-bd5a-11e9-9f5c-98b1a0ebd79b.PNG)

I left the Label for that field visible but you could easily hide it.

And here is what the backend of that form looks like: 
![tussenvoegsel_backedn](https://user-images.githubusercontent.com/1381170/62913639-ee0c4a80-bd5a-11e9-97cf-7875d6e16fd3.PNG)

**Comment by boxlady** [comment]
Yes I know you can add it there. That doesn't change the name is displayed.
For example in the calendar, billing search etc. It's a major part a name
in counties that use it.

**Comment by robertdown** [comment]
Ah, ok, I see how that could impact other areas, thanks for clarifying. I'll reopen this issue.

I'll take a look at how to solve this, I think I may have a way... just need to try it out.
