### ISSUE TITLE
Remove and migrate Docs folder to Wiki

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2597]
Wiki is on Atlassian currently and where the Docs folder will wind up. @MatthewVita suggested this task. @morg0n handling it I think but might need further instruction.

**Comment by danehrlich1** [comment]
@MatthewVita please provide just a modicum of direction to @morg0n and let me know when you think the wiki is 50% or so done for the first release.

**Comment by morg0n** [comment]
Hey all!  I'm hoping to migrate this today, so if we can determine where
exactly this goes I can go ahead and get started on it! :)

**Comment by MatthewVita** [comment]
I mentioned this because we'll need to sort through all of the docs and then migrate them when we're much closer to the finish line. I'm assuming we're talking about this: https://github.com/openemr/openemr/tree/master/Documentation

We shouldn't delete that until everything is migrated and the wiki is public (and has been migrated to the wiki Robert is working on)

Let me know if I'm missing something

**Comment by danehrlich1** [comment]
@MatthewVita Noted and I will make sure this is mentioned in the Jira

**Comment by morg0n** [comment]
Here is a comment to give me attention because I wanna keep working on this and forgot where we were more or less

**Comment by bradymiller** [comment]
hi @morg0n ,
Just to get an idea of how far along the wiki migration project is, roughly, what percentage of the old wiki has been migrated to the new wiki?
thanks, -brady

**Comment by tywrenn** [comment]
@bradymiller did this ever get done?

**Comment by morg0n** [comment]
Hey @tywrenn !
I had been making progress on Confluence and it was determined that the wiki would be migrated instead to a different platform; I'm currently waiting for things to be finalized with Drupal going live and then documentation will move forward (according to my understanding).

**Comment by morg0n** [comment]
Waiting to complete this through Drupal instead -- my understanding :)
