### ISSUE TITLE
When closing a tab, should automatically open next one

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#260]
If I close a tab, I'm stuck with a blank screen, upon closing a tab, the next tab in the list should be opened automatically. If you closed the last tab, the new last tab should be opened.

**Comment by rishabhemr** [comment]
We have fixed this issue along with the issue #290. Please review the code and let us know the feedback.

Rishabh Software

**Comment by bradymiller** [comment]
Hi,
Can you post the code as a Pull Request?
thanks,
-brady

**Comment by bradymiller** [comment]
Just brought in rishabhemr's fix for this, so closing this issue. Thank you for the contribution!
