### ISSUE TITLE
function loadiframe removed from interface/billing/search_payments.php

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2605]
hi @zbig01, when you updated this script to use the OemrUI class, commit 41f84b65823d5475cdcdc3191a1bd6ae9b8ad027,  it lost the ability to view the detail of the check items with the edit_payment.php script, https://github.com/openemr/openemr/blob/master/interface/billing/search_payments.php#L595

**Comment by zbig01** [comment]
@stephenwaite 

Will post PR with the fix, :)

**Comment by stephenwaite** [comment]
cool, it was greek to me 🇬🇷

**Comment by kylenave** [comment]
I think I'm running into this problem... loadiframe is an unreferenced error.
How would I track down this fix? Sorry - I'm new to collaborative github.
Do I search this issue (#2605)? That didn't seem to identify any PR's but I may not be searching correctly.
Thanks,
Kyle

**Comment by stephenwaite** [comment]
hi @kylenave, please see this https://github.com/openemr/openemr/pull/2656, it will be in the first 5.0.2 patch too

closing this issue
