### ISSUE TITLE
Authentication Error in dated reminders

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2609]
Displays in reminders message count header icon.
Unsure what work flow resets/regens token but it's annoying. Creates hundreds of php log notices.
Not sure we really need CSRF in background timer tasks! Although, this may give an indication/symptom or session corruption causing logout problems, though I haven't seen this so far.

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Unable to recreate this issue (also have nothing going to log):
![image](https://user-images.githubusercontent.com/278968/62819192-cf157a80-bb06-11e9-8e7e-af55fca2728e.png)
What OS and PHP version are you using?

**Comment by sjpadgett** [comment]
@bradymiller Sorry, i'm talking about the separate background timer dated reminders polling.
I've seen on my dev windows 10 and ubuntu 16.04. In this case user was in billing manager.
![image](https://user-images.githubusercontent.com/1859985/62820900-78756400-bb39-11e9-9681-64a58ea1a688.png)

**Comment by sjpadgett** [comment]
I just realized that I have portal turned on in both these instances. Perhaps my portal polling routine is culprit. Suppose I better check though, if true, i'll probably never admit it! :)

**Comment by sjpadgett** [comment]
Since i've added the login session cookie fix, i've not  seen this issue. So will close for now and keep an eye out. I've looked at the reminders code and it looks okay to me.
I still don't understand why we need CSRF tokens for these background tasks.
