### ISSUE TITLE
oeBelowContainerDiv() errors

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2611]
PHP Fatal error:  Uncaught Error: Call to a member function oeBelowContainerDiv() on null in /var/www/openemr/interface/patient_file/front_payment.php:1281\nStack trace:\n#0 {main}\n  thrown in /var/www/openemr/interface/patient_file/front_payment.php on line 1281, referer: https://192.168.1.7/interface/patient_file/front_payment.php

If anything test for null on call....

**Comment by zbig01** [comment]
@sjpadgett 

I tried the the Fees > Payment of both the development demo as well as the 5.0.2 main demo and it seems to be working. I am not getting any errors.  

**Development Demo** 

![front-payment-demo-01-](https://user-images.githubusercontent.com/12654295/62824541-a4521300-bb54-11e9-968f-adbdc9ac3894.png)

![front-payment-demo-02-](https://user-images.githubusercontent.com/12654295/62824543-a7e59a00-bb54-11e9-8a59-8a5faaaa1165.png)

![front-payment-demo-03-](https://user-images.githubusercontent.com/12654295/62824546-acaa4e00-bb54-11e9-857b-6c3c9d816305.png)


**Main 5.0.2 Demo**

![front-payment-main-demo-04-](https://user-images.githubusercontent.com/12654295/62824554-bcc22d80-bb54-11e9-8c3e-a04be401eca9.png)


![front-payment-main-demo-05-](https://user-images.githubusercontent.com/12654295/62824555-c0ee4b00-bb54-11e9-85f8-712f4779b492.png)

![front-payment-main-demo-06-](https://user-images.githubusercontent.com/12654295/62824556-c481d200-bb54-11e9-8f49-2cf53bf2c471.png)

Could you elaborate on how you are getting this error.

Thanks

**Comment by sjpadgett** [comment]
Beats me why it happens but i've been seeing this error random since well before 502 release. New for front payment though, previously was popping up in encounters. Haven't seen that lately.

These random errors can be hard to troubleshoot. Best with these is to try to predict why it could happen and take a look at code. I can't tell if this error causes any negative effect to user, appears not. So, i'd just try to trap cause of error i.e null return(it appears) and handle gracefully in function call...

**Comment by zbig01** [comment]
Does not appear to be theme dependent.  What version of PHP are you using?

**Comment by sjpadgett** [comment]
php 7.1.7 and 7.2 shouldn't matter for this type of error anyway.
I can reproduce on my windows machine and ubuntu 16.04.
Turn on User Debug in globals logging and see if you can see..

**Comment by sjpadgett** [comment]
@zbig01 Here's the problem:
The class is being called outside the forms scope. eg the forms container closing div and thus call to class is outside of form save else. Easy miss....
script front_payment.php should end like this around L-1277

` </div>
    <?php $oemr_ui->oeBelowContainerDiv();} ?>`

I'll add to a PR i'm going to put up soon if ya want..

**Comment by sjpadgett** [comment]
Saw email. Simultaneous solution cool. Were you able to use User Debug(this is my little pet contrib)?

Closing this as @zbig01 solution. Thank you...

**Comment by sjpadgett** [comment]
Fix https://github.com/openemr/openemr/pull/2614
