### ISSUE TITLE
Encryption of Document Templates Upload (Not Portal) Breaks Parse

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2616]
Open Office odt (office document text) is corrupted after parse for download in patient documents.
File appears to decrypt okay but it only take one byte in header so i'm not sure what the issue could be. 
Will take some looking into.

**Comment by bradymiller** [comment]
This still an issue or addressed in recent fixes?

**Comment by sjpadgett** [comment]
This is somewhat strange. Further testing show the encrypt then decrypt are working fine. If you download the decrypted doc from template fetch, then open, works. However, if you try to open the doc from download, ie 
![image](https://user-images.githubusercontent.com/1859985/63216447-7ac05b00-c103-11e9-9a24-f0a56d159dd3.png)

it fails with Libre error General input/output error.
So, not our problem I can see. Closing this issue.
