### ISSUE TITLE
mPDF issue?

### ISSUE THREAD

**Issue by ghost** [openemr/openemr#2631]
Printing statements for Pt Due, select all returns:

`Fatal error: Uncaught Mpdf\MpdfException: The HTML code size is larger than pcre.backtrack_limit 1000000. You should use WriteHTML() with smaller string lengths. in /var/www/openemr/vendor/mpdf/mpdf/src/Mpdf.php:26626 Stack trace: #0 /var/www/openemr/vendor/mpdf/mpdf/src/Mpdf.php(13124): Mpdf\Mpdf->AdjustHTML('<div style="pad...', 8) #1 /var/www/openemr/interface/billing/sl_eob_search.php(317): Mpdf\Mpdf->WriteHTML('<div style="pad...') #2 /var/www/openemr/interface/billing/sl_eob_search.php(581): upload_file_to_client_pdf('/tmp/openemr_st...', '', NULL, false) #3 {main} thrown in /var/www/openemr/vendor/mpdf/mpdf/src/Mpdf.php on line 26626`

**Comment by ophthal** [comment]
Increasing the pcre.backtrack_limit doesn't change the error.  Reducing the number of statements to print however does work...
