### ISSUE TITLE
New style theme to calendar 

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr#2633]
We are checking the option to replace the calendar to newer and modern style.
We have found several javascript libraries that suggests full calendar and they load the events using server API (The most popular is [Full calendar](https://fullcalendar.io/)).   

We want to create new interfaces to Openemr API for fetching events, this will enable to working with new libraries.

Here I suggest a basic structure for the API interfaces. 
https://gist.github.com/matrix-amiel/87d3924c9f0d5502f9e498d70c183ca8

I would happy to know what do you think about this idea? Which problems we may found with this way? 

Thanks

Amiel (Matrix)

**Comment by bradymiller** [comment]
hi @matrix-amiel , Definitely would be nice to upgrade the calendar to a newer, modern style. Using api definitely seem like ideal good direction to go. I guess the main question is which calendar software is best?

**Comment by matrix-amiel** [comment]
What about https://github.com/fullcalendar/fullcalendar ?
It's the most popular library with wide API  (also in the open source option). and it supports a lot of languages.

**Comment by bradymiller** [comment]
hi @matrix-amiel , Do you see any big difference in the open source versus commercial option? We just need to avoid choosing a option that may railroad the project (ie. for example, if the open source option became more restricted or even discontinued over time).

**Comment by matrix-amiel** [comment]
Yes, I know that the open source is limited but still it holds most of the features in this version.
I would like to get your thoughts about my idea-
1.We will create full API for calendar that returns all the data and settings.
2. We will contribute a basic version of a new view with all the functionality that we can create using open source version of 'full calendar' (it's not a bit...).
3. It will also be possible for some organizations to extend their calendar and pay for commercial option and develop special view with more data form API.

**Comment by bradymiller** [comment]
hi @matrix-amiel , We've been burned before on this type of issue (the prior popup framework went from gpl to a licensing model), which required significant effort to get it then out of the codebase. To migrate to a calendar that could potentially do the same seems risky. Aren't there any other more open source friendly options?
-brady

**Comment by matrix-amiel** [comment]
Hi @bradymiller 
I am having difficulties fo find another library with abilities like Full calendar.
The full calendar is used by more than 18,000 projects on GitHub (https://github.com/fullcalendar/fullcalendar/network/dependents), are you realy think they will change their licenses??

**Comment by bradymiller** [comment]
hi @matrix-amiel , More worried about limiting the feature set of the free version; but if they are heavily used and been around awhile, then not as concerning. Regarding your point 3 above; there appear to be limitations for the non-commercial version. Are we safe to assume that all functionality that OpenEMR requires is in the free version?

**Comment by matrix-amiel** [comment]
The single feature we can't do with the limited version is to show the view of all users in the single screen, for implement this with full calender we need "Resources" and it only in the premium version.
But all the other features will be shown well and we can add some new features like drag and drop and view as list.

**Comment by bradymiller** [comment]
Hi @matrix-amiel ,
Can't we develop our own views to show that kind of stuff? I'm assuming customization will be needed, correct? The goal on the calendar conversion is that no functionality is lost.
-brady

**Comment by matrix-amiel** [comment]
Ok, I will check it.
Thank you for the answers!

**Comment by matrix-amiel** [comment]
Hi @bradymiller 
Just to be sure, It's possible to show all the users in a single view (we can paint every user in a different color), what that not possible in the free version is to create view like the following image for the users.
![image](https://user-images.githubusercontent.com/17809866/64240001-dc593580-cf09-11e9-8d95-09d5ff276f12.png)
Is it still problematic?

**Comment by bradymiller** [comment]
hi @matrix-amiel , Since it's open source, can't we customize it and create views as needed?

**Comment by matrix-amiel** [comment]
Hi @bradymiller 
The full calendar comes with full API that can do almost all the actions we need in the calendar without touching in the core of the code. This is the reason I love this library and it so famous.
If we decide to extend the core of this library the development can be long and we lose the ability to upgrade to new versions.

**Comment by bradymiller** [comment]
hi @matrix-amiel , If that is the case, then we should first make a list of all the features that OpenEMR's current calendar supports and then see what will be supported out of box in the Full Calendar.

**Comment by matrix-amiel** [comment]
**Supports features -**
I mention we're talking only on the view, the add/edit event stay as-is with the current popup.

- [x]  view for Daily/weekly/monthly 

- [x] Works days, Holidays.

- [x] Appointment duration

- [x] Color coding

- [x] Filter by Users/Facility

- [x] First day in the week

- [x] Calendar Starting/ending Hour

- [x] Link from event to a patient file 

What do I missing? 

**Not supported feature -**

- [ ] Showing multiple users in split view

My suggestion is to show all the user in this way -
![image](https://user-images.githubusercontent.com/17809866/64486459-36be0300-d236-11e9-849c-350c0642e058.png)
![image](https://user-images.githubusercontent.com/17809866/64486462-3f163e00-d236-11e9-94ad-f8d763a1d3ce.png)
![image](https://user-images.githubusercontent.com/17809866/64486467-4b020000-d236-11e9-8995-e14a23122dcf.png)

**Comment by matrix-amiel** [comment]
And as I mentioned above we will enjoy from a lot of new features like new filters by rooms/facilities/patients  and more in simple developments

**Comment by bradymiller** [comment]
Hi @matrix-amiel ,
Would recommend proceeding, but leave the old calendar around as an option (should be straightforward since just using views) for folks that need the multiuser view (that's an important view for front staff in clinics with more than 1 provider) and any other potential hidden features that we don't know about. Then we can figure out a workaround (or some other solution) to solve the multiuser view that works (they really need their own columns) and work out other surprises that come along the way.
-brady

**Comment by bradymiller** [comment]
Actually, one more issue is to ensure the translations can be done through OpenEMR's translation engine.

**Comment by matrix-amiel** [comment]
Great. hopefully we will begin with that soon..
We have new JS translation function so It's not supposed to be a problem.

**Comment by usama-kabel** [comment]
Another thing, I suggest for provider calendar show only appointments and time off but for Receptionist can show all time on calendar.
Thanks in advance

**Comment by sjpadgett** [comment]
Hi @matrix-amiel 
I hope you haven't abandoned this because of recent calendar updates. I did those so calendar would work somewhat better on mobile but a replacement is still a great idea. 
I hope you guys will reconsider the project and can pull it off.
Thanks

**Comment by tywrenn** [comment]
@matrix-amiel This project is a must after my work is done. I'd like for you to reopen this as the current theming structure I've got going on doesn't work well with the calendar.

**Comment by matrix-amiel** [comment]
@tywrenn 
What is your project? #2881?

**Comment by tywrenn** [comment]
@matrix-amiel #2832

**Comment by matrix-amiel** [comment]
We've changed our plans and we are working on a new Reactjs application that works with OpenEMR API  + new modules.
The change to a new calendar is planned to be a part of this project.
Hopefull the first version will be ready in a few months, of course we'll share the development.
