### ISSUE TITLE
Modular OpenEMR????

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2636]
I wonder how much push back i'm going to get if I create a Packagist account for us to install openemr features/modules via composer require. We can host the module.

@bradymiller @robertdown @sunsetsystems @MatthewVita need thoughts please...

**Comment by MatthewVita** [comment]
I like the idea too (as well as Robert's project). My big concern would be
if Packagist would a) "die" or b) run into the problem that has been
popping up over the last two years with other package hosts: people
hikjacking modules and injecting spyware.

I suppose that's a moot point because we're already using NPM...

-m

**Comment by sjpadgett** [comment]
> Maybe if you help me finish up the event driven architecture

Sorry Robert @robertdown , you're right but, Stephen N. and I got a sponsor for adding FHIR Questionnaire with assessments and reporting. It provides for client applications or requests from OpenEMR. So, i've had to put core work on hold. I'm sure i'll work in dispatcher in fhir.

@MatthewVita True somewhat, may be best to just point to repository and write composer installer(needed either way). Packagist is a little easier to manage for module dev.

Agreed though, event dispatchers need to be implemented and well documented for module developers with strict adherence to use. If made a requirement then most likely module dev's will develop for and contribute.

**Comment by adunsulag** [comment]
@robertdown @MatthewVita So Matrix is already doing this with their zend modules.  When I went down the path of refactoring the zend framework stuff I investigated doing the auto install of modules via composer as part of that (matrix keeps that work in their own codebase) but it was going to be too disruptive at the time.  I like the approach.  Packagist is a good thing as long as whoever owns the account vets the contributors and we implement a 2FA for the packagist account for anyone who does publications on it.

Just some thoughts.  I've been out of the loop for a while and that may continue while we build out some FHIR stuff with a sponsor but I hope to get back into things after that.

**Comment by danehrlich1** [comment]
@sjpadgett Really love the Packagist idea. I looked at their security really quickly. It's...really good. I commented on their twitter a few things they could add but other than that it is way ahead of say https://php.net, which until recently didn't even autoredirect you to TLS.

**Comment by danehrlich1** [comment]
> I suppose that's a moot point because we're already using NPM...

@MatthewVita You're right Matthew about hijacking modules and also lol about NPM being terrible. Security wise they are horrible, but they also treat their workers terribly. I feel like I've seen more things come up lately about their bizarre CEO than their security.

**Comment by adunsulag** [comment]
In trying to get the fax / sms stuff in for our FHIR sponsor Jerry and I went down the route of adding in custom modules installed via composer.  Happy to get all of your feedback on this.  Pull request is here: https://github.com/openemr/openemr/pull/2654

Sample module package is here: https://github.com/openemr/oe-module-faxsms

Composer module installer is here: https://github.com/openemr/oe-module-installer-plugin

**Comment by sjpadgett** [comment]
Just wanted to update this issue then will close.
I've completed the final pieces for my fax and sms module with the addition of using @kchapple Globals support to drop in the Global options and added a Fax button to Patient Documents. So for faxing from core we have button support in patient/custom report, patient documents and a drag and drop to fax in the Fax Modules U.I. Contact list comes from a dialog of the address module. Currently both Ringcentral and Twilio fax accounts are supported with Twilio default on install. Account setup is done via a menu item in fax u.i i.e Actions->Account Credentials. RingCentral authentication is a three leg 2FA and Twilio uses 2 leg api token with secret and account token.

I've ported module support back to v5.0.2 and will be in first patch
You can find the module source and bootstrap code at: https://github.com/openemr/oe-module-faxsms
and Stephen's installer: https://github.com/openemr/oe-module-installer-plugin

So it is Stephen and my hope that while this module may be useful for many in clinical settings, it also serve as an example that others may wish to refer for their own modules.

I will follow up soon with a Readme for various vendor account setups. Meantime, enjoy.
