### ISSUE TITLE
Support more recent SNOMED RF1 packages

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#264]
OpenEMR import does not support the more recent RF1 packages.
(1/2015 SNOMED RF1 package and later no longer imports correctly)

**Comment by bradymiller** [comment]
Hi Roberto,

Here's the core places to understand a bit:
https://github.com/openemr/openemr/blob/master/interface/code_systems/list_staged.php#L129-L151

https://github.com/openemr/openemr/blob/master/library/standard_tables_capture.inc#L146-L236

In the new package, will need to find where the "Terminology/Content/" is.
Which is then figured out here:
https://github.com/openemr/openemr/blob/master/library/standard_tables_capture.inc#L205-L208

Look around a bit, breaks things etc. and feel free to ask any questions.

-brady

**Comment by robertogagliotta** [comment]
Hi Brady
I found this at https://www.nlm.nih.gov/healthit/snomedct/international.html
Current International Releases
Version: July 2016
Reminder: In 2015 IHTSDO announced the deprecation and withdrawal of support for RF1 format. The plan and timeline can be reviewed on the IHTSDO News page.

**Comment by robertogagliotta** [comment]
There are RF1 And RF1 compatible. RF1 is human readable, Terminology/Content is in SnomedCT_RF1Release_INT_20160731 -> Terminology -> Content -> sct1_Concepts_Core_INT_20160731.txt   sct1_Descriptions_en_INT_20160731.txt 
sct1_Relationships_Core_INT_20160731.txt

**Comment by bradymiller** [comment]
What happens when you try to install the SnomedCT_RF1Release_INT_20160731 file?

**Comment by bradymiller** [comment]
If the SnomedCT_RF1Release_INT_20160731 is indeed the title of the package, then can likely be supported by added another else if in the code to support the RF1 in the title of the package:
https://github.com/openemr/openemr/blob/master/interface/code_systems/list_staged.php#L129-L151

**Comment by bradymiller** [comment]
I just committed Roberto's fix for this into the codebase:
https://github.com/openemr/openemr/commit/84706807f46182bef254367462d012c759b37c97

thanks for the fix Roberto!
