### ISSUE TITLE
ApolloLIMS HL7 OBR specimen type required

### ISSUE THREAD

**Issue by DennisonWilliams** [openemr/openemr#2641]
[The ApolloLIMS](http://www.apollolims.com/) requires the OBR-15 field to be filled out.  This value is optional in the procedure type configuration page, but it needs to be set and included for interoperability with this LIMS.

**Comment by DennisonWilliams** [comment]
[pull request for the solution](https://github.com/openemr/openemr/pull/2642)

**Comment by DennisonWilliams** [comment]
See [pull request: 2643](https://github.com/openemr/openemr/pull/2643) for a solution

**Comment by stephenwaite** [comment]
was committed, closing, thank you
