### ISSUE TITLE
Add Doctor's Signature to Procedure Order Summary

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#2645]
This contribution is backed by PEER Technologies, PLLC (or PEERClinic), a practice created by Sohail K. Mirza, MD MPH. The doctor would like a way for procedure orders to have a signature on the order, followed by the doctor's NPI, DEA, and state license number as well as the date. I will be resolving this in a follow-up pull request.

**Comment by sjpadgett** [comment]
@tywrenn There's already a form drop in for signature.
<img class="signature" id="adminSignature" data-type="patient-signature" data-action="fetch_signature" alt="' . xla("Click in signature") . '" data-pid="' . attr((int)$pid) . '" data-user="' . attr((int)$user) . '" src="">

**Comment by tywrenn** [comment]
Where is this triggered? I don't see this anywhere in the order manifest code.

**Comment by sjpadgett** [comment]
check out https://community.open-emr.org/t/adding-patient-portal-document-templates-to-openemr-patient-documents/12141.
The new hooks are in first patch but may be able to use current library to continue your work.
I have to look to see whats in v502 and give you an example...need a few

**Comment by sjpadgett** [comment]
Need to be sure bootstrap is in scope and these dependencies:
`<link href="<?php echo $GLOBALS['web_root']; ?>/portal/sign/css/signer_modal.css?v=<?php echo $GLOBALS['v_js_includes']; ?>" rel="stylesheet" type="text/css" />`
`<script src="<?php echo $GLOBALS['web_root']; ?>/portal/sign/assets/signature_pad.umd.js" type="text/javascript"></script>`
`<script src="<?php echo $GLOBALS['web_root']; ?>/portal/sign/assets/signer_api.js" type="text/javascript"></script>`

add where ya want signature
`<img class="signature" data-type="admin-signature" data-action="fetch_signature" alt="' . xla("Click in signature") . '" data-pid="' . attr((int)$pid) . '" data-user="' . attr((int)$user) . '" src="">`
or for patient:
`<img class="signature"  data-type="patient-signature" data-action="fetch_signature" alt="' . xla("Click in signature") . '" data-pid="' . attr((int)$pid) . '" data-user="' . attr((int)$user) . '" src="">`
add any id you need and signature will auto populate/save.

unzip this into openemr directory from v502 patch not released yet. It's all portal and signer update.
[portal.zip](https://github.com/openemr/openemr/files/3560774/portal.zip)

**Comment by tywrenn** [comment]
Thanks for the clarification. I couldn't find any obvious documentation on this which is why I created this issue, but it looks like this issue has been solved. This should be implemented in #2636 to make this easier but for now i'm closing this issue.
