### ISSUE TITLE
User authentication with 3rd party

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr#2652]
Hi @bradymiller 

We have a requirement from our customers to increase the user authentication in the login to Openemr.
We've thought about connecting to 3rd party of user authentication service.
Those services provide many features for authorization and user management like:
*multi-factor authentication (MFA)
*password protection, forget password
*User directory management
*Social sign-in and more

In the process of login with those services, the user is redirected to the service login page (Federation) and at the end of the authentication redirect back with token to openemr.  

We check the option to implement it with one of these services -
[Amazon Cognito](https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html)
[Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/authentication/)
[Auth0](https://auth0.com/docs/multifactor-authentication)

Would this feature could merge into the community as an optional plugin? 
I believe it could interest more Openemr users. 
Do you have an opinion on which service is best to use? 

Thank.
Amiel (Matrix)

**Comment by adunsulag** [comment]
So I'd just chime in that Amazon Cognito is a good integration for those users already on the Amazon Cloud packages as it will all bill to the same account.  I haven't used Auth0 for a long time but they were comprehensive when I last used them but it was more difficult to setup then my recent experiences with Cognito.  

I'm very biased against microsoft and especially Active Directory but that's my own personal preference.  Do they support HIPAA BAA?  Here in the U.S. that's a big deal.

Also I think someone posted a 3rd party auth integration somewhere else but I can't recall, might want to build on that work.

**Comment by matrix-amiel** [comment]
Hi @bradymiller 
Would you anticipate any problems with bringing of this feature to the community?

**Comment by bradymiller** [comment]
hi @matrix-amiel , nope. the more security options, the better :)

**Comment by yaronbsmtx** [comment]
Just so you know, here is Microsoft's compliance details as far as HIPAA is concerned:
[](https://www.microsoft.com/en-us/trustcenter/Compliance/hipaa).
If you go to the "detailed list" link, you will find a PDF an there you will see that Azure AD is within the scope of HIPAA BAA coverage.

**Comment by yaronbsmtx** [comment]
Just so you know, here is Microsoft's compliance details as far as HIPAA is concerned:
[https://www.microsoft.com/en-us/trustcenter/Compliance/hipaa].
If you go to the "detailed list" link, you will find a PDF an there you will see that Azure AD is within the scope of HIPAA BAA coverage.

**Comment by danehrlich1** [comment]
I agree with Stephen AD is disaster. AWS Cognito, Duo, Okta, and GCP’s new
competitor to Cognito all real possibilities.
