### ISSUE TITLE
MySQL Error while Installation

### ISSUE THREAD

**Issue by konsyr11** [openemr/openemr#2659]
> **Situation**
> OpenEMR` setup starts fine, I enter all the information needed into the form, but once I save the database information and continue, I get an error (posted below, in the Logs section). I have tried changing the query, but then other problems arise. Help needed. Thanks in advance.

> **OpenEMR** Version
> I’m using OpenEMR version 5.0.2

> **Browser:**
> I’m using: Google Chrome

> **Operating** System
> I’m using: CPanel webhosting, Linux based, PHP 7.1, MySQL

> Logs
```ERROR. unable to execute SQL: 'CREATE TABLE `history_data` ( `id` bigint(20) NOT NULL auto_increment, `coffee` longtext, `tobacco` longtext, `alcohol` longtext, `sleep_patterns` longtext, `exercise_patterns` longtext, `seatbelt_use` longtext, `counseling` longtext, `hazardous_activities` longtext, `recreational_drugs` longtext, `last_breast_exam` varchar(255) default NULL, `last_mammogram` varchar(255) default NULL, `last_gynocological_exam` varchar(255) default NULL, `last_rectal_exam` varchar(255) default NULL, `last_prostate_exam` varchar(255) default NULL, `last_physical_exam` varchar(255) default NULL, `last_sigmoidoscopy_colonoscopy` varchar(255) default NULL, `last_ecg` varchar(255) default NULL, `last_cardiac_echo` varchar(255) default NULL, `last_retinal` varchar(255) default NULL, `last_fluvax` varchar(255) default NULL, `last_pneuvax` varchar(255) default NULL, `last_ldl` varchar(255) default NULL, `last_hemoglobin` varchar(255) default NULL, `last_psa` varchar(255) default NULL, `last_exam_results` varchar(255) default NULL, `history_mother` longtext, `dc_mother` text, `history_father` longtext, `dc_father` text, `history_siblings` longtext, `dc_siblings` text, `history_offspring` longtext, `dc_offspring` text, `history_spouse` longtext, `dc_spouse` text, `relatives_cancer` longtext, `relatives_tuberculosis` longtext, `relatives_diabetes` longtext, `relatives_high_blood_pressure` longtext, `relatives_heart_problems` longtext, `relatives_stroke` longtext, `relatives_epilepsy` longtext, `relatives_mental_illness` longtext, `relatives_suicide` longtext, `cataract_surgery` datetime default NULL, `tonsillectomy` datetime default NULL, `cholecystestomy` datetime default NULL, `heart_surgery` datetime default NULL, `hysterectomy` datetime default NULL, `hernia_repair` datetime default NULL, `hip_replacement` datetime default NULL, `knee_replacement` datetime default NULL, `appendectomy` datetime default NULL, `date` datetime default NULL, `pid` bigint(20) NOT NULL default '0', `name_1` varchar(255) default NULL, `value_1` varchar(255) default NULL, `name_2` varchar(255) default NULL, `value_2` varchar(255) default NULL, `additional_history` text, `exams` text, `usertext11` TEXT, `usertext12` varchar(255) NOT NULL DEFAULT '', `usertext13` varchar(255) NOT NULL DEFAULT '', `usertext14` varchar(255) NOT NULL DEFAULT '', `usertext15` varchar(255) NOT NULL DEFAULT '', `usertext16` varchar(255) NOT NULL DEFAULT '', `usertext17` varchar(255) NOT NULL DEFAULT '', `usertext18` varchar(255) NOT NULL DEFAULT '', `usertext19` varchar(255) NOT NULL DEFAULT '', `usertext20` varchar(255) NOT NULL DEFAULT '', `usertext21` varchar(255) NOT NULL DEFAULT '', `usertext22` varchar(255) NOT NULL DEFAULT '', `usertext23` varchar(255) NOT NULL DEFAULT '', `usertext24` varchar(255) NOT NULL DEFAULT '', `usertext25` varchar(255) NOT NULL DEFAULT '', `usertext26` varchar(255) NOT NULL DEFAULT '', `usertext27` varchar(255) NOT NULL DEFAULT '', `usertext28` varchar(255) NOT NULL DEFAULT '', `usertext29` varchar(255) NOT NULL DEFAULT '', `usertext30` varchar(255) NOT NULL DEFAULT '', `userdate11` date DEFAULT NULL, `userdate12` date DEFAULT NULL, `userdate13` date DEFAULT NULL, `userdate14` date DEFAULT NULL, `userdate15` date DEFAULT NULL, `userarea11` text, `userarea12` text, PRIMARY KEY (`id`), KEY `pid` (`pid`)) ENGINE=InnoDB AUTO_INCREMENT=1 ' due to: Row size too large (> 8126). Changing some columns to TEXT or BLOB may help. In current row format, BLOB prefix of 0 bytes is stored inline.```

**Comment by stephenwaite** [comment]
kind offer of assistance by @growlingflea , https://community.open-emr.org/t/error-installing-version-5-0-2/12806/2?

**Comment by stephenwaite** [comment]
hi @konsyr11 , what mysql version are you running? thank you

**Comment by konsyr11** [comment]
I am using 10.3.18-MariaDB - MariaDB Server. But I will close this issue and leave the topic in https://community.open-emr.org/t/error-installing-version-5-0-2/12806/2
