### ISSUE TITLE
Method to auto find_code_popup: enhancement

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#266]
When find_code_popup.php is called, if a search_term passed in, the search is now run on first load, allowing the end user to simply click the desired result. If no search_term is provided, or the term needs refinement, the original functionality remains.

https://github.com/ophthal/openEMR_2/tree/find_code_popup

Commit to cherry-pick:
https://github.com/ophthal/openEMR_2/commit/26b9be5f0548666dfa69faf45c4ced7e27e44927

**Comment by Wakie87** [comment]
Tested and commited this to the codebase. https://github.com/openemr/openemr/commit/ffd0e4c1e8ad3acaa7bb6d610d489e3c851063a0
Thanks again for your amazing contribution (eye form) and these small fixes.

Scott
