### ISSUE TITLE
no close option in appointment popup window

### ISSUE THREAD

**Issue by kamaleshSRI** [openemr/openemr#2665]

**Comment by kamaleshSRI** [comment]
1.Create encounter to the patient or else select existed encounter
2.Fees | Fee Sheet
3.Click on New Appointment button
4. Display one appointment popup window is displaying in that opoup window there is no close option.

**Comment by sjpadgett** [comment]
This works on light theme. Besides the red x out you should have a cancel button in the frame. Plus escape will also knock down the dialog if clicked outside of dialog...
