### ISSUE TITLE
 Calendar bug - parameter 'duration' not working in event 'In office' 

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr#268]
Scenario:
In calendar :
adding an event at 8:00 for the 30 minutes as “In office”  -> but all day long is marked with the “in office” color.

![image](https://cloud.githubusercontent.com/assets/17809866/18739711/2ad89d16-80ae-11e6-9b2b-1caeb50144aa.png)

Is this a bug or an expected behaivior?

**Comment by bradymiller** [comment]
This is expected behavior. The In Office is just the starting point and does not have a duration. The Out Office is what sets the ending point.
-brady
