### ISSUE TITLE
Telemedicine Signalling Server

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2684]
I need to know if this is a worthwhile endeavor. My plan is two phases: 1. Implement a signaling and message(command based) server written using Nodejs/Websockets and 2. Integrate video conference with portal, encounters and front desk/reception. 

For portal and encounter, conference would be appointment based with reception being video call based i.e could accept or reject call.

The server would be command/message based where not only used for STUN/ICE negotiations for video calls but also used for inter device command data channels. Say we run reminders from server and notify application when reminders are available taking those timers out of main application and also messing with sessions(I still believe restore session in dated reminders is an issue). Anyway, you get the point that the server should not be dedicated to just one task that may run once or twice a day. Oh, PHP server events just popped into mind.

I'd probably need some help with how well this would work in our cloud based product. Security being the main concern and yes, i'm aware we could run off public STUN/TURN servers but I think we'd run into hipaa concerns doing such.

**Comment by ophthal** [comment]
@sjpadgett, I can't comment on the backend but the front end should be simple.  Maybe a link to the telemedicine session in the encounter area akin to opening a form, and another way to initiate a session in the messages center (to open a session with a colleague or a patient).  My guess is there will be many use case scenarios we have not imagined but it appears patients are embracing it.  It must be important if [Amazon thinks so](https://www.beckershospitalreview.com/telehealth/will-amazon-s-telemedicine-program-spread-beyond-employees.html).   Now if we could just get Jeff Bezos to call you...
