### ISSUE TITLE
Encryption and the TaskMan

### ISSUE THREAD

**Issue by ghost** [openemr/openemr#2708]
For the eye form, taskman handles one-click faxing of the current note to another provider by sending it via email to a fax server as an attachment. However taskman doesn't decrypt docs for sites using the OpenEMR encryption global.  I'm happy to add this functionality to the taskman but the structure of the backend has changed.  Can someone point me to the code in 5.0.2 to decrypt?  Thanks.

**Comment by bradymiller** [comment]
hi @ophthal,
Are you storing the file on the drive in OpenEMR (ie. in a documents sub directory)? If so, then agree should encrypt it. Encrypt/decrypt on the drive within openemr is straightforward. Example of use in that case would include:
```
use OpenEMR\Common\Crypto\CryptoGen;
$cryptoGen = new CryptoGen();
$encryptedData = $cryptoGen->encryptStandard($data, null, 'database');
$decryptedData = $cryptoGen->decryptStandard($encryptedData, null, 'database');
```
-brady

**Comment by bradymiller** [comment]
Also, check this out for more details on encryption/decryption:
https://github.com/openemr/openemr/blob/master/src/Common/Crypto/CryptoGen.php#L5-L17

**Comment by ophthal** [comment]
Yes, in documents directory.
Thanks for the info/link.
I'll have a PR up soon for you.
