### ISSUE TITLE
Increase Minimum Pass Length From 8 to 14 for GCP

### ISSUE THREAD

**Issue by danehrlich1** [openemr/openemr#2713]
GCP enforces a min length for a custom password of 8 characters. I will look into raising it. Since the username is admin, and every attacker would know that, raising this password length, just for this user, would be really helpful.

@morg0n I will get 70% of the way through this issue and then forget about it for like 4 months I swear. Please keep me on task.

**Comment by morg0n** [comment]
Here is your November reminder 😊

**Comment by morg0n** [comment]
December reminder :)

**Comment by sjpadgett** [comment]
> GCP enforces a min length for a custom password of 8 characters

Somebody tell me what this is and i'll get rid of this issue in two shakes. Does it need to come back to 502 as we are getting ready to release patch 2.

**Comment by sunsetsystems** [comment]
I don't really care, but enforcing a minimum length will just get you passwords like "password123456".

:)

**Comment by bradymiller** [comment]
For 5.0.3 and onwards, this can be set in globals:
https://www.open-emr.org/wiki/index.php/Administration_Globals#Minimum_Password_Length
(is defaulted to 9, which seems to be a reasonable default)
