### ISSUE TITLE
Why doesn't move to use laravel framework ?

### ISSUE THREAD

**Issue by usama-kabel** [openemr/openemr#2724]
I consider all efforts spent to have a huge project like OpenEMR.
But why doesn't use laravel framework. Also Laravel have strong community and more secure and able to implement APIs to use mobile app and also modern design with comfortable design and action with more browsers.

Thanks

**Comment by stephenwaite** [comment]
hi @usama-kabel , here's a recent coversation from the forum, https://community.open-emr.org/t/standardizing-openemr-frontend-development-decision-time/12567

**Comment by usama-kabel** [comment]
Hi @bradymiller 
Why openemr migrate to framework like laravel? 
This migration will fix multiple issue faced openemr in current release openemr have multiple vulnerabilities with critical value and high
Thanks

**Comment by bradymiller** [comment]
hi @usama-kabel , Would likely be a million dollar project and by then there would be a new thing (as frameworks do come and go if you zoom out over the last 20 years; with the goal of OpenEMR still being around for at least 20 more years). -brady

**Comment by zerai** [comment]
Frameworks are no bad if you decouple your application from them.

I'm not an expert but for me is very hard to understand this codebase 
I'd like to contribute, but the lack of tests is holding me back. (see tests folder)
What I miss in my opinion:
  - a good test coverage (new developers can modify add features without risk)

- a good pipeline for CI  phpunit, + static analysis (psalm/phpstan) + quality scanner (SonarQube/Scrutinizer)

- common convention for single file and global architecture.

A framework doesn't solve these 3 problems, we should do.

**Comment by usama-kabel** [comment]
Hi @bradymiller  I agree with you.
@zerai also I missed multiple MVC to mange and classify everything well also basic validation and main way to contact with database also check who do what in framework this implemented easily by middleware and basic security 
Thanks

**Comment by murugappanrm** [comment]
Laravel is an overloaded PHP framework and will complicate a huge application like OpenEMR. The complexity of EMR is already enough to bind developer, we could do without layered rubbish like laravel.
