### ISSUE TITLE
Error in Transition of Care

### ISSUE THREAD

**Issue by MahamadNoor** [openemr/openemr#2725]
Hello,

I wanted to download the patient data in the CCDA format.
So, I followed this procedure:

1. Modules>>carecoordination
2. Select “export”
3. Select “Transition of care”
4. Click send
5. Select “download”
6. Click “send”
![image](https://user-images.githubusercontent.com/54838678/67067021-6a277200-f192-11e9-8c6d-b3e1081cf8b7.png)

This gives me an error.

![image](https://user-images.githubusercontent.com/54838678/67067059-8b885e00-f192-11e9-9eb0-67bf51dd187c.png)

Thank you

**Comment by thesmallstar** [comment]
Hello @MahamadNoor, Are you still facing the issue?
I could not reproduce it, can you help me?

**Comment by sjpadgett** [comment]
fyi This is required if not using ZH mirth server. It a service to intercept and build the CCDA summary of care.
openemr/ccdaservice/README.md
