### ISSUE TITLE
Receipt Issue

### ISSUE THREAD

**Issue by ghost** [openemr/openemr#2730]
On pop-up payment, receipt prints with:

Fatal error: Uncaught Error: Call to a member function oeBelowContainerDiv() on null in /var/www/openemr/interface/patient_file /front_payment.php:1281 Stack trace: #0 {main} thrown in /var/www/openemr/interface/patient_file/front_payment.php on line 1281

![Receipt for Payment copy](https://user-images.githubusercontent.com/508784/67165946-e7044880-f358-11e9-9839-a2cda67e36f4.png)

**Comment by sjpadgett** [comment]
I fixed one of these somewhere and should be in patch. I'm guessing you're on patch 1. Maybe didn't get in patch but it's caused by a missing js function  I believe.
