### ISSUE TITLE
error in including globals.php

### ISSUE THREAD

**Issue by dummys** [openemr/openemr#2732]
hi,

This line of code made error with PHP 7.3

https://github.com/openemr/openemr/blob/1bc02874fc05e2a44a605a6fd6449e22775aa0cd/library/encounter.inc#L2

I patched it like this: `include_once(__DIR__."/../interface/globals.php");` and I get no more error.

**Comment by stephenwaite** [comment]
hi @dummys , thank you, we should probably change it to `require_once` as well, do you want to submit a PR?
https://github.com/openemr/openemr/blob/master/CONTRIBUTING.md

**Comment by dummys** [comment]
ok I can if you want

**Comment by stephenwaite** [comment]
sure, it's great having new contributors, thank you

**Comment by bradymiller** [comment]
hi @dummys and @stephenwaite ,
That is an odd line and should not even be there. Recommend changing those 2 lines to just this line:
```
include_once(__DIR__."/forms.inc");
```

**Comment by bradymiller** [comment]
oops, make it require_once:
```
require_once(__DIR__."/forms.inc");
```

**Comment by dummys** [comment]
@bradymiller you mean deleting the old globals ?

**Comment by bradymiller** [comment]
yes, remove that line. It shouldn't be in library scripts. It's always called in running scripts (it sets everything up and does authorization). Rec searching in codebase where encounter.inc is included and you'll note that globals.php is always included in the scripts that use the encounter.inc library.

**Comment by dummys** [comment]
done see pr

Le mar. 22 oct. 2019 à 09:08, Brady Miller <notifications@github.com> a
écrit :

**Comment by dummys** [comment]
@bradymiller it seems that the global problem is on multi page, see this one:   include_once(): Failed opening '/var/app/current/openemr/interface/billing/../../globals.php
