### ISSUE TITLE
Onsite Documents in Patient Portal Not Using Responsive CSS Design Techniques (iPad Tested)

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#2740]
When i'm in "portal/patient/onsitedocuments", the page fails to load on an iPad. After opening web inspector for iPad, 'adminName' from the Signer API is failing to be recognized as well as some other variables in signer_api.js. I'll post the full console log later in the day but this issue keeps happening.

**Comment by sjpadgett** [comment]
Hi Tyler. Is this from the portal login or from patient documents?

**Comment by tywrenn** [comment]
This is from logging into the portal and clicking Patient Documents.

**Comment by sjpadgett** [comment]
Safari I assume. I've never tested on opera or safari. I'd be interested in what the console JS error is. Is it an undefined var error?

**Comment by tywrenn** [comment]
[Error] SyntaxError: Unexpected identifier 'rqit'
	(anonymous function) (dialog.js:122)
[Error] SyntaxError: Unexpected identifier 'errorMsg'
	(anonymous function) (userDebug.js:18)
[Error] SyntaxError: Unexpected identifier 'adminName'
	(anonymous function) (signer_api.js:96)
[Error] SyntaxError: Unexpected identifier 'type'
	(anonymous function) (onsitedocuments:147)

**Comment by sjpadgett** [comment]
Does this work in other browsers ie FF

**Comment by tywrenn** [comment]
No it doesn't work in other browsers on the iPad for some reason.

**Comment by sjpadgett** [comment]
hmm, something's off. Email me a portal login. Ipad itself should not be an issue. This acts like ES6 is not enforced.

**Comment by sjpadgett** [comment]
Maybe you need to update your ipad browsers!

**Comment by sjpadgett** [comment]
For those watching:
Tyler was testing on a prior version to IOS 10 so not ES6 compatible. I would have though using let declares in ES5 would be okay but I believe some browsers did not support. Anyway he will verify and let us know.

**Comment by tywrenn** [comment]
Turns out the issue isn't errors, it's a responsive styling issue. The sidebar isn't responsive at all nor the top bar that allows you to select different documents.

**Comment by sjpadgett** [comment]
See this Tyler: https://community.open-emr.org/t/mobile-responsive-not-working-5-0-2/13053/4

**Comment by tywrenn** [comment]
Closing issue due to it being moved to community forms

**Comment by sjpadgett** [comment]
Just for folks to know, you may see spotty issues in 5.0.2 if browser does not support ES6.
