### ISSUE TITLE
Only variables should be passed by reference in D:\EMR\Code\openemr-5.0.2\src\Menu\MainMenuRole.php on line 67

### ISSUE THREAD

**Issue by mukeshmuvva** [openemr/openemr#2742]
![Screenshot (8)](https://user-images.githubusercontent.com/29394258/67391071-7c9f1280-f5bb-11e9-883d-fe2e4ddf0e80.png)

Hi Everyone,

I'm new here I have downloaded codebase and followed all the steps mentioned in GitHub but when I run the application I'm getting the error. Please find the screenshot for the errors. 

Kindly help me.

**Comment by stephenwaite** [comment]
hi @mukeshmuvva , please see https://www.open-emr.org/wiki/index.php/FAQ#What_are_the_correct_PHP_settings_.28can_be_found_in_the_php.ini_file.29.3F

**Comment by sjpadgett** [comment]
yep, xampps php.ini default for display_errors is On for some weird #(&% reason. Didn't use to be.

**Comment by mukeshmuvva** [comment]
Thanks, everyone

**Comment by mukeshmuvva** [comment]
Hi is it ok to have those errors in the project? will that affect the project flow?

**Comment by stephenwaite** [comment]
hi @mukeshmuvva , my understanding is that while it's ok for the notices to exist it would be ideal to correct them and adhere to php best practices

**Comment by sjpadgett** [comment]
Of course I have to add my nickel(inflation). :)
I highly recommend users turn off notices in php.ini. Warnings too. All they do is clutter logs and the end user does not gain any useful debugging info.
Notices generally tell the developer that while the PHP interpreter may not like what it is seeing, it'll handle it anyway. This is common on every new PHP version release.
Generally on every openemr release we try to clear all warning and if time, notices.
