### ISSUE TITLE
Logging Audit Logging SELECT Query needs to go.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2744]
Either we go through code and change all unneeded recording sql select queries to nolog or we simply do not allow the selection in Globals.
User are all the time turning on and even I would think; "the more logging the better", right!
Anyone know if this is a requirement somewhere?

**Comment by bradymiller** [comment]
Hi,
This is a requirement for Meaningful Use. Pretty much every sql query needs
to be logged unless it contains login/token credential information. Crazy,
but that is the world of MU :)
(the good news is 5.0.2 can do this and even the encryption of all log
entries with good performance(MU also requires encryption of the log
entries, which is also off by default); 5.0.1 is abysmal with both of these
on though)
-brady

**Comment by bradymiller** [comment]
To follow up on my previous post, here are the MU requirement that user
needs to do after install OpenEMR:
https://www.open-emr.org/wiki/index.php/OpenEMR_5.0.2_MU2_Install_Instructions

**Comment by sjpadgett** [comment]
Okay, agreed 502 is much better however still a performance killer. Last time I reviewed MU logging my takeaway was very different with how we've implemented. But it is what it is. Would bet though a review of our logging of select queries would show overkill. But that's a can of worms i'll gladly leave the can opener in the drawer....
closing
