### ISSUE TITLE
Develope Global depends validator and/or warning alerts

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2745]
Example. Portal password reset feature requires email.

portal_two_pass_reset' => array(
            depends('patient_reminder_sender_email', 'text'),
            xl('Allow Onsite Patients to Reset Credentials'),
            'bool', 
            '0',
            xl('Patient may change their logon from portal login dialog.')
        ),

Either warn or disable. We treat Globals as setup so adding a few functions could be helpful.
This could be a fun project for an intermediate developer.

**Comment by stephenwaite** [comment]
sp in develope :slightly_smiling_face:  Global Developer Depends :older_man: :jeans:

**Comment by sjpadgett** [comment]
develope is an obsolete spelling of develop, much as I am!
