### ISSUE TITLE
ERROR connecting to database, are you sure you specified the proper host, user name, password, and database in admin/gacl_admin.inc.php? Did you create the database, and give read/write permissions to "openemr" already?

### ISSUE THREAD

**Issue by mukeshmuvva** [openemr/openemr#2747]
hi

I am trying to deploy the openemr in IIS server. but after step 4 getting this  below error.

**ERROR connecting to database,
are you sure you specified the proper host, user name, password, and database in admin/gacl_admin.inc.php?
Did you create the database, and give read/write permissions to "openemr" already?**

Kindly help me!!!

**Comment by stephenwaite** [comment]
hi @mukeshmuvva , good place to post is the forum, https://community.open-emr.org/, where likely will be seen by more folks

**Comment by stephenwaite** [comment]
oh, you closed this, nice, hope you're all set
