### ISSUE TITLE
Add Recently Used Diagnosis Codes when creating a Procedure Order

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#2750]
In the clinic, the doctor has complained that since he has multiple procedures with the same diagnosis code, he has to repetitively search up the same exact diagnosis code for each procedure. If we added in the diagnosis codes lookup area a "recently used" option, then it would make this process much more simpler and faster to complete.

**Comment by sjpadgett** [comment]
Actually best to grab the ICD's from patient problems rather than a favorite/recent list for at least one good reason, where to store or retrieve recents. I believe however, in my recent update to compendium(procedures configuration) I added to Favorites the ability to add a linked ICD or other code with favorite. You might look there.

**Comment by tywrenn** [comment]
@sjpadgett Link? Can't seem to find it

**Comment by sjpadgett** [comment]
It's part of favorite setup in procedure->configuration. For favorites you setup top group as custom panel the add tests. Can add any codes for tests but I never used anywhere but added this for future so, some coding needed.
![image](https://user-images.githubusercontent.com/1859985/68252086-8af52180-fff2-11e9-94af-d9ae340dc87b.png)

In my custom procedure order encounter form, I do it like this:
![image](https://user-images.githubusercontent.com/1859985/68251668-a3187100-fff1-11e9-8577-a2fa5504a8ed.png)

Note the Primary Diagnosis field.  These come from issues/problems and will get included with lab order if procedure diagnosis is empty.
Just some thoughts. Whichever you'll be doing some coding.

**Comment by tywrenn** [comment]
Closed as this solves this issue

**Comment by sjpadgett** [comment]
@tywrenn How about reopen this issue. I think this is a very good idea and don't think it would take me long to do. Except I think using current primary diagnoses from problems is the way to go. Maybe a new category in popup for codes.
I'll get it started if you want to put the finishing touches and do the PR..

**Comment by tywrenn** [comment]
I just realized even if we had a custom favorite group there are gonna be different ICD's for different orders so creating a ton of favorite groups seems too much - imma reopen this issue.

**Comment by sjpadgett** [comment]
I'm thinking a new popup for past procedure diagnosis and current problems diagnosis. Just need to figure out where I want to instigate this new popup search.

**Comment by sjpadgett** [comment]
Anyone know of any current issues with procedure orders form while i'm diddling around?

**Comment by sjpadgett** [comment]
Decided on new search button in fprm:
![image](https://user-images.githubusercontent.com/1859985/68260296-a3713600-000a-11ea-8e26-2403bc6582f5.png)

**Comment by sjpadgett** [comment]
Here is what I ended up with PR #2772
- Restyle form
![image](https://user-images.githubusercontent.com/1859985/68360865-a4c85e80-00ef-11ea-9440-e5dc06ae1766.png)
- New dx from problems and past procedures picker
![image](https://user-images.githubusercontent.com/1859985/68360990-199b9880-00f0-11ea-9ae3-bc4833772caa.png)
- Help
![image](https://user-images.githubusercontent.com/1859985/68361085-7e56f300-00f0-11ea-8952-33f67101fe5c.png)
- And so forth. Basically just add and remove from dx list.
