### ISSUE TITLE
tab layout - automatic logout on timeout not working

### ISSUE THREAD

**Issue by sunsetsystems** [openemr/openemr#276]
With current dev code, if I set Idle Session Timeout Seconds to 300, turn on tabs, log out and log in again, and let the browser sit for 5 minutes it fails to auto-logout after 5 minutes.  If instead I use the sliding menu it works.

**Comment by bradymiller** [comment]
Placed a fix for this here:
https://github.com/openemr/openemr/pull/278

What is happening was the repeating background_services ajax call was killing the connection via timeout, but since the javascript in auth never made it to the browser and auto-logout was not done. To fix this, set it so these repeating calls can not cause the logout to happen.

This may not be an ideal solution.

**Comment by bradymiller** [comment]
Perhaps skipping it whenever an ajax call is done would be more ideal?
http://www.pontikis.net/tip/?id=30

**Comment by sunsetsystems** [comment]
I have used a GET parameter "running_as_ajax=1" in the fee sheet logic to detect that case.  No idea how fragile or browser-dependent this other method would be.  Anyway if your commit works I'm happy.

**Comment by bradymiller** [comment]
Note it does not do an auto logout, however (if try to do something after the timeout, it will logout). I think to get the auto logout really working will require a simple hidden iframe based on interface/main/daemon_frame.php script (interface/main/tabs/daemon_frame_tabs.php) that simply just keeps refreshing every 120 seconds. Thus on a timeout, it will then do a auto-logout without any user input.

**Comment by bradymiller** [comment]
If got above working, then would likely migrate the background services check and the future messages check to that script.

**Comment by sunsetsystems** [comment]
That makes sense to me.  I guess an ajax success handler could do that too?  I would look at how the browser reacts in each case... i.e. it's best if the browser does not show a "busy indicator" when these events happen.

**Comment by bradymiller** [comment]
Just committed the above fix to fix the site id is missing bug when the user tries to do something after a timeout; it will now instead logout.

Will now work on the fix to support auto-logout without any user insteraction.

**Comment by bradymiller** [comment]
@sunsetsystems ,

Placed a PR for this:
https://github.com/openemr/openemr/pull/285

It is working, but notably the browser does show a very brief "busy indicator" when this script is reloaded. Not sure how to avoid this while also ensuring the auth.inc javascript is rendered correctly.

**Comment by sunsetsystems** [comment]
Awesome, thanks!

**Comment by bradymiller** [comment]
Committed above PR.
