### ISSUE TITLE
Notice : Only variables should be passed by reference in C:\xampp\htdocs\open\src\Menu\MainMenuRole.php on line 67

### ISSUE THREAD

**Issue by Gixy1** [openemr/openemr#2775]
I am facing these errors. i tried re installing it hundred times but still the same. i am trying to run it on my XAMPP locally. please help
![Screenshot (27)](https://user-images.githubusercontent.com/20395705/68396586-793e8600-017a-11ea-81e4-3199d22d6bf1.png)

**Comment by sjpadgett** [comment]
@Gixy1 
This happens because the PHP ini property to display_errors to screen is set to On.
Set to Off.
check out https://www.open-emr.org/wiki/index.php/OpenEMR_5.0.2_Windows_Installation
On windows php.ini file is usually at \xampp\php\php.ini
Change setting and restart apache.

**Comment by Gixy1** [comment]
> 
> 
> @Gixy1
> This happens because the PHP ini property to display_errors to screen is set to On.
> Set to Off.
> check out https://www.open-emr.org/wiki/index.php/OpenEMR_5.0.2_Windows_Installation
> On windows php.ini file is usually at \xampp\php\php.ini
> Change setting and restart apache.

thanks its solved the issue, and one more thing, can the system be used for multiple hospitals, i.e they both login into the system but see different things and only see patients data registered under their respective hospitals etc? And if yes, how do i accomplish this?
