### ISSUE TITLE
Add additional notifications to the EMR

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#2777]
When someone creates an appointment in the Patient Portal, there is no notification sent to the doctor or the staff that an appointment was even created. So basically everyone is left in the dark on what's happening in the Patient Portal. This needs to be fixed.

Also, there is no concrete setup for patient reminders (the doctor can't specify how often and when the patient gets reminded either via SMS or Email). This might just be on my end of things but it needs to be fixed as well.

**Comment by sjpadgett** [comment]
Sure there is!
Appointment notify:
![image](https://user-images.githubusercontent.com/1859985/68548013-58627480-03b6-11ea-8ce5-842f6d20dfa0.png)
And for Appointment SMS notification use Fax Module ie
https://community.open-emr.org/t/another-new-feature-for-v5-0-2-1-fax-with-sms-notification-module/13041

**Comment by tywrenn** [comment]
Closed
