### ISSUE TITLE
Error Running Quick Setup With Docker Compose Flex Configuration

### ISSUE THREAD

**Issue by dixonwhitmire** [openemr/openemr#2783]
Hello,

I have forked the OpenEMR repository and am working through the steps outlined in [Contributing.MD](https://github.com/openemr/openemr/blob/master/CONTRIBUTING.md). I am unable to complete the provisioning/quick-setup process due to what looks like a missing class/library (I apologize PHP isn't my primary development language). To be more specific I am encountering errors when using the "flex-edge" image with the master and rel-502 branches. I have found that I am able to complete the quick setup if I used the openemr:5.0.2 image, however it appears that the openemr:5.0.2 image hasn't been updated in about a month.

The docker-compose configurations I have tested are attached. The only "successful" config is docker-compose.yml which is configured to use the openemr:5.0.2 image.

[docker-compose.zip](https://github.com/openemr/openemr/files/3848080/docker-compose.zip)

Should I use a different branch with the flex-edge image?

Additionally does anyone know which "commit" corresponds to the current openemr:5.0.2 image?

Thank you very much! If this isn't the appropriate place to ask this question, I will be happy to post over in the "Support Forum".

Thanks,

Dixon

**Comment by bradymiller** [comment]
hi @dixonwhitmire ,

The `flex-edge` tag is a bit on the experimental side since it is using Alpine Edge(this is Alpine's ongoing development branch) and would recommend instead using the `flex` tag which will use the most current production alpine version (now 3.10).

To `flex`* series dockers are different from the production dockers (`5.0.3`(openemr-dev-version), `5.0.2`(current openemr production version), `5.0.1`). The `flex`* series dockers do not include openemr codebase in the dockers so that makes them much more flexible for development/testing purposes. The production dockers include the static codebase(for example 5.0.2 includes codebase for production 5.0.2 from the rel-502 branch). Can see more on this in text here:
https://hub.docker.com/r/openemr/openemr/

Don't see any real issues with your .yml's. A very common issue is folks do not clear out their shared volumes when shutting down the dockers, which can mess things up horribly. What do you see for:
docker volume ls
(if that's not the issue, then I can quickly try out one of your yml's to see if any issues; just let me know)

-brady

**Comment by bradymiller** [comment]
Another quick thing on the current `5.0.2` docker, it is now using patch 1, which is the v5_0_2_1 tag in the rel-502 branch.

**Comment by dixonwhitmire** [comment]
Hi @bradymiller - thanks for the response!

I did verify that all things in 🐳 land are cleaned out prior to firing up the openemr compose file. Unfortunately I'm still bumping into the same issue

```
docker-compose down -v
Stopping fabric-emr-demo_openemr_1 ... done
Stopping fabric-emr-demo_mysql_1   ... done
Removing fabric-emr-demo_openemr_1 ... done
Removing fabric-emr-demo_mysql_1   ... done
Removing network fabric-emr-demo_default
Removing volume fabric-emr-demo_logvolume01
Removing volume fabric-emr-demo_sitevolume
Removing volume fabric-emr-demo_databasevolume
```

```
docker volume ls
DRIVER              VOLUME NAME
```

```
docker-compose up 
....
openemr_1  | PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/library/authentication/password_hashing.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/auto_configure.php on line 3
openemr_1  | PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/library/authentication/password_hashing.php' (include_path='.:/usr/share/php7') in /var/www/localhost/htdocs/auto_configure.php on line 3
openemr_1  | Couldn't set up. Any of these reasons could be what's wrong:
openemr_1  |  - You didn't spin up a MySQL container or connect your OpenEMR container to a mysql instance
openemr_1  |  - MySQL is still starting up and wasn't ready for connection yet
openemr_1  |  - The Mysql credentials were incorrect
openemr_1  | PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/library/authentication/password_hashing.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/auto_configure.php on line 3
openemr_1  | PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/library/authentication/password_hashing.php' (include_path='.:/usr/share/php7') in /var/www/localhost/htdocs/auto_configure.php on line 3
openemr_1  | Couldn't set up. Any of these reasons could be what's wrong:
openemr_1  |  - You didn't spin up a MySQL container or connect your OpenEMR container to a mysql instance
openemr_1  |  - MySQL is still starting up and wasn't ready for connection yet
openemr_1  |  - The Mysql credentials were incorrect
openemr_1  | PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/library/authentication/password_hashing.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/auto_configure.php on line 3
openemr_1  | PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/library/authentication/password_hashing.php' (include_path='.:/usr/share/php7') in /var/www/localhost/htdocs/auto_configure.php on line 3
openemr_1  | Couldn't set up. Any of these reasons could be what's wrong:
openemr_1  |  - You didn't spin up a MySQL container or connect your OpenEMR container to a mysql instance
openemr_1  |  - MySQL is still starting up and wasn't ready for connection yet
openemr_1  |  - The Mysql credentials were incorrect
```
It looks like another user has encountered the issue as well in https://github.com/openemr/openemr/issues/2785

[docker-compose.yml.zip](https://github.com/openemr/openemr/files/3852574/docker-compose.yml.zip)

I will take a look at trying again with the v5_0_2_1 tag and will see what happens .

**Comment by dixonwhitmire** [comment]
@bradymiller - one more note for you. I have confirmed that the flex-edge image works like a charm with the rel-502 v5_0_2_1 tag
```
dixonwh$ git fetch --all --tags --prune
Fetching origin
Fetching upstream
dixonwh$ git checkout tags/v5_0_2_1 -b rel-502
Switched to a new branch 'rel-502'

# I created a branch for the tag so that I could use it in the docker compose config
dixonwh$ git checkout -b rel-502-tag-5_0_2_1
Switched to a new branch 'rel-502-tag-5_0_2_1'
ixonwh$ git push origin rel-502-tag-5_0_2_1
Total 0 (delta 0), reused 0 (delta 0)
remote: 
remote: Create a pull request for 'rel-502-tag-5_0_2_1' on GitHub by visiting:
remote:      https://github.com/dixonwhitmire/openemr/pull/new/rel-502-tag-5_0_2_1
remote: 
To https://github.com/dixonwhitmire/openemr.git
 * [new branch]          rel-502-tag-5_0_2_1 -> rel-502-tag-5_0_2_1
```

```
docker-compose up -d
# few minutes later . . .
openemr_1  | OpenEMR configured.
openemr_1  | Setup Complete!
openemr_1  | Setting user 'www' as owner of openemr/ and setting file/dir permissions to 400/500
openemr_1  | Default file permissions and ownership set, allowing writing to specific directories
openemr_1  | Removing remaining setup scripts
openemr_1  | Setup scripts removed, we should be ready to go now!
openemr_1  | 
openemr_1  | Love OpenEMR? You can now support the project via the open collective:
openemr_1  |  > https://opencollective.com/openemr/donate
openemr_1  | 
```

**Comment by bradymiller** [comment]
hi @dixonwhitmire ,

Thanks for the reports.

ok, just updated the flex series dockers with fixes and and tested them to work on the new and older codebase (master, rel-502, and v5_0_2_1 all working well). So, we should be all good now on the flex dockers:
https://community.open-emr.org/t/openemr-flex-docker-updated/12051/11

**Comment by dixonwhitmire** [comment]
Hi @bradymiller,

Thanks for the quick turn-around. I confirmed that I am able to use the flex-3.9 image with the rel-502 branch with no issues. The quick setup completes and I am able to log into the portal using the admin credentials.

Thanks!
Dixon
