### ISSUE TITLE
Error during composer build

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#2785]
This file isn't in the master branch anymore and composer wants to load it for some reason.

openemr_1     | PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/library/authentication/password_hashing.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/auto_configure.php on line 3
openemr_1     | PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/library/authentication/password_hashing.php' (include_path='.:/usr/share/php7') in /var/www/localhost/htdocs/auto_configure.php on line 3
openemr_1     | Couldn't set up. Any of these reasons could be what's wrong:
openemr_1     |  - You didn't spin up a MySQL container or connect your OpenEMR container to a mysql instance
openemr_1     |  - MySQL is still starting up and wasn't ready for connection yet
openemr_1     |  - The Mysql credentials were incorrect

**Comment by dixonwhitmire** [comment]
I think I'm encountering the same issue running the "quick setup" with docker compose.

**Comment by stephenwaite** [comment]
Have you checked that the vendor dir does not exist before you spin up?

**Comment by tywrenn** [comment]
Yeah composer isn't the issue here

**Comment by stephenwaite** [comment]
since Brady just did some cool work with the passwords try removing the require in `https://github.com/openemr/openemr-devops/blob/master/docker/openemr/5.0.2/auto_configure.php#L3`
hopefully will build without it

**Comment by bradymiller** [comment]
yep, looks like i need to fix a few things on the docker side of things that the recent password hashing updates broke
https://github.com/openemr/openemr/pull/2770
looking into now :)

**Comment by bradymiller** [comment]
ok, got the 5.0.3 (uses dev codebase that includes new password hashing changes) docker updated and running:
https://github.com/openemr/openemr-devops/commit/50257b5d97b953091ef6d50bacf4e73996b1761e

@stephenwaite , @tywrenn , and @dixonwhitmire ,
Only the changes in the docker/openemr/5.0.3/auto_configure.php are pertinent. I am going to do the same thing in the flex dockers (hopefully tonight), although need to support both the old and new code in the flex dockers (will simply check to see if the password_hashing.php exists to decide which way to go).

@jesdynf ,
Just letting you know I updated the docker/openemr/5.0.3/utilities/unlock_admin.php to work with the new password hashing code changes for when we release 5.0.3 in the future (I tested these changes and they work). This script is what creates the password on the aws cloud stuff.

**Comment by bradymiller** [comment]
ok, just updated the flex series dockers with fixes (also updated all the dockers on dockerhub):
https://github.com/openemr/openemr-devops/commit/98b1f01cc5fc95cc7e0e822c1b49218c28a11489

And tested them to work on the new and older codebase. So, we should be all good now on the flex dockers:
https://community.open-emr.org/t/openemr-flex-docker-updated/12051/11

**Comment by stephenwaite** [comment]
thank you @bradymiller , nice to be able to use older code too

**Comment by tywrenn** [comment]
Closed & fixed
