### ISSUE TITLE
All tabs don't render 100% height IOS 13+ Mobile

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2788]
Beats me. I haven't been able to figure this out. Same issue with FF on same phone! Again, befuddled!
Works on IOS 12+.

**Comment by sjpadgett** [comment]
I found the issue and it's a weird(@bradymiller i before e huh!...inside joke) one. 
IOS 13 will not honor flex column in a div container for iframe. 
In our case it's the style `#framesDisplay > div` which is the container for all our tab iframes `#framesDisplay > div > iframe`.
Current style:
#framesDisplay > div
{
    flex: 1 0 auto;
    align-items: stretch;
    align-content:stretch;
    display: flex;
    flex-direction: column;
    margin: 0;
    padding: 0;
    border-left: 1pt solid black;
    border-right: 1pt solid black;
}
Now one would think; "Okay Jerry, just give the darn div a 100% height like we had to do for Microsoft" but nooooooo, not Apple. They want it to be a viewport height 100vh.... Some may know using viewports on desktop can be tricky as in our case, it reduces overall iframe heights. (some of this is because many of our scripts leave open tags or too many tag closures forcing browser to decide.) 

Here's the weird part(more scary than weird). This occurs whether Safari, FF 20.1 or Chrome but only on IOS 13 as far as I can tell. Leads me to believe the mobile o.s is intervening somehow.

Maybe some more knowledgeable dev's can look into. Just grab an iPhone with IOS 13+ and try out openemr on it. I see nothing in @zbig01 or others restyles that could predict this issue but we need to find a permanent solution if ever we're serious about running on mobile.

My fix is to add  media queries to tab_style_*.css. Really is backwards as normally would style app for mobile and add media queries for screen but, backwards is my thing. :)

Some input from styling guru's would be helpful as I may be missing something....

**Comment by zbig01** [comment]
Jerry

I too came to this conclusion. iOS12 did not have this issue.
I am trying to find a solution for this vexing issue.
Meanwhile mobile on Android and fireOS works fine🙂

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sjpadgett** [comment]
Thanks @zbig01 for getting back to me.
I have a work around solution but this will affect us in future for desktop as well. I'ne noted that even for the calendar's iframe(replaced frameset here) i've needed to give a viewport height.

How about once I get my update into my PR #2781 for restyle, i'll bring PR in, then you can check me or maybe add to what i've done. I'll do this later tonight for sure.

Maybe between the two of us we'll straighten this out.

**Comment by zbig01** [comment]
Sounds like a plan

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zbig01** [comment]
Jerry 
Pl replace `tabs_style_full.css` in both `/public/themes` and` interface/themes`  with this file and test
[tabs_style_full.zip](https://github.com/openemr/openemr/files/3856806/tabs_style_full.zip)

Media query added to set vh to 100% for  ` #framesDisplay > div > iframe ` only for tablets and below. My quick testing seems to be working. 
Thoughts?
 Thanks

**Comment by sjpadgett** [comment]
Yep already did that. I'm getting ready to put my latest up then we can take from there.

**Comment by sjpadgett** [comment]
@zbig01 Just brought PR in. I'm hoping you can go through it and improve it where needed.
thanks
closing issue
