### ISSUE TITLE
Create new encounter & New Validation

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#279]
If the Global->Security->New form validation is not checked, a new encounter can not be created via the New Encounter Form.

**Comment by bradymiller** [comment]
Thanks for this bug report.

This setting is only supposed to turn on/off the new validation method in the forms driven by the layouts engine.

It is not supposed to turn on/off the new validation method in the separate forms (such as the new encounter that Ray pointed out), which are instead controlled by their associated entry in list_options.

(I have confirmed that this global new_validate is being used within the core validation functions, which is what is causing the bug)

@sharonco-matrix , Can your group look at this?

**Comment by sharonco-matrix** [comment]
We will fix it!

**Comment by bradymiller** [comment]
Hi @sharonco-matrix ,

There appear to be 2 related PR's for this now:
https://github.com/openemr/openemr/pull/287
https://github.com/openemr/openemr/pull/288

I don't think this it is necessary to try and support 2 separate validation mechanisms in these forms, which will just be confusing; and your group's validation method is much more modern and flexible. If the entry is missing in list_options or it is turned off in list_options, then this is an error on the user's part.

The bug that needs to be fixed, though, is that all these forms(with entries in list_options) are breaking if the Administration->Globals->Security->'New Form Validation' is turned off. This flag should not affect these forms at all and should only be used to turn off/on the validation in the layout based forms.

thanks,
-brady

**Comment by bradymiller** [comment]
Fix for this has been posted here and is under review:
https://github.com/openemr/openemr/pull/294

**Comment by bradymiller** [comment]
I just committed the above linked PR which fixes this issue(thank you @sharonco-matrix for the fix). There is still a minor clean up issue in library/validation/validate_core.php, so will leave this issue open until that is addressed.

**Comment by bradymiller** [comment]
Minor fix has been addressed, so closing this issue.
