### ISSUE TITLE
Patient Portal Login/Register Page Needs Responsive Redesign

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#2793]
The patient portal login/register page does not have a fluid/responsive design and needs to be updated. I've heard many patients calling to our clinic saying that they cannot navigate the patient portal at all due to this issue.

**Comment by sjpadgett** [comment]
Umm, don't you have classes or something instead of finding things for me to do?:)
However, you're right.

**Comment by sjpadgett** [comment]
Wow, I didn't realize just how bad portal login on mobile renders. Wonder why no complains in past. Anyway will add to my other portal changes for patch 2.

**Comment by sjpadgett** [comment]
Picture worth a bunch of words:
![image](https://user-images.githubusercontent.com/1859985/69111549-e04a1d80-0a4b-11ea-870b-733a46325851.png)
![image](https://user-images.githubusercontent.com/1859985/69111687-5058a380-0a4c-11ea-8850-8b96a9f34078.png)
Register 
![image](https://user-images.githubusercontent.com/1859985/69111978-22279380-0a4d-11ea-98d7-482df09b7d12.png)

![image](https://user-images.githubusercontent.com/1859985/69111833-c1985680-0a4c-11ea-820b-36647e5ccf27.png)

**Comment by tywrenn** [comment]
Imma add a few CSS tweaks to this tomorrow involving padding & stuff. Will pull request it here so you can critique it

**Comment by sjpadgett** [comment]
@tywrenn That'd be great. I was more interested in making it functional quickly so patient can use. Also, i've not tested on ios 13+. 
If you can this does not expand correctly on small screen
![image](https://user-images.githubusercontent.com/1859985/69164449-09a39180-0abe-11ea-9b12-89cc41b942b9.png)

**Comment by tywrenn** [comment]
Closed :)
