### ISSUE TITLE
loss of frames means no split screen for billers

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2810]
hey @sjpadgett  , how difficile do you think it would be to split screen the fee sheet with the visit summary? A biller I know would really like to be able to view the notes from the newpatient form while she codes.

**Comment by stephenwaite** [comment]
hi @sunsetsystems , pretty sure you've done a lot of work to the fee sheet, is that something you're still up for looking into? just wondering with all of @sjpadgett 's irons in the :fire

**Comment by sjpadgett** [comment]
First thought is to add a collapsible div with iframe below or above items.

**Comment by sunsetsystems** [comment]
Not sure what that should look like, now that frames have been deemed evil. :)

Just a thought... layouts now let you specify sections for Services, Products and Diagnoses - so basically you can have a LBF that you can do coding in. Thus you might create a LBF like that for patient notes.

**Comment by sjpadgett** [comment]
I gleaned that we just need to display existing notes against existing encounter.
@stephenwaite can you give me uri or screenshot of what frame for newpatient you are talking about.

**Comment by stephenwaite** [comment]
:), ok, thanks guys, was wondering if it's possible to have an option for the fee sheet to open underneath the encounter. Basically what's going on is the provider is dictating into the reason for visit text box including the cpts and dxs and since the upgrade the biller has to switch back and forth btw the tabs.

**Comment by bradymiller** [comment]
hi,
Can't they lock the tab (the lock/unlock button at right of tab) to always
show it and then look at the other tab?
-brady

**Comment by stephenwaite** [comment]
think so but they have to toggle back and forth btw tabs

**Comment by sjpadgett** [comment]
Be nice to be able to stack tabs!

**Comment by stephenwaite** [comment]
think the encounter based aren't treated/don't behave like the others

**Comment by sjpadgett** [comment]
They behave the way we tell them to behave lol

**Comment by stephenwaite** [comment]
maybe for you obiwan :)

**Comment by sjpadgett** [comment]
Interesting stuff. I'll just take a quick look see at the possibilities. A Quick look mind ya:)

**Comment by sjpadgett** [comment]
@stephenwaite 
is this what is wanted to view with feesheet. if not what
![image](https://user-images.githubusercontent.com/1859985/69466075-0a078b00-0d51-11ea-8f37-98ca2c90c118.png)

**Comment by stephenwaite** [comment]
![Screen Shot 2019-11-23 at 8 08 57 AM](https://user-images.githubusercontent.com/5618372/69479194-9a34e700-0dc8-11ea-9fa2-f37975f94752.png)
looks like the select code div should be collapsible too

**Comment by stephenwaite** [comment]
brady and i chatted about it today on the call and thought if it was possible to make the sub tabs lock like the main tabs do it would be pretty nice

**Comment by stephenwaite** [comment]
bump

**Comment by stephenwaite** [comment]
bump

**Comment by stephenwaite** [comment]
bump

**Comment by stephenwaite** [comment]
bump

**Comment by stephenwaite** [comment]
hacked a workaround using generate report from the dashboard

![Screenshot from 2021-06-02 08-07-14](https://user-images.githubusercontent.com/5618372/120477620-fc858500-c379-11eb-92bc-2199a2667237.png)
