### ISSUE TITLE
Onsite Patient Portal 2 cannot handle recurrtype 3 events

### ISSUE THREAD

**Issue by epsdky** [openemr/openemr#2817]
(Fix pending)

**Comment by tywrenn** [comment]
Put on hold due to pending #2807 substantial changes

**Comment by sjpadgett** [comment]
Hi @epsdky 
The appointments module in portal is the result of original author pulling add_edit_event from core and reworking for portal so, probably not the best solution. 
I restyled our main core appointments with an eye on sharing that script with portal for obvious maintainability reasons then ridding the portal of the custom add/edit. However, I don't think we should allow patient to create recurring appt's and only allow soft deletes for same. I've never been sure I like the idea of recurring in portal except for display only.

I'd be grateful if you want to tackle this where, after the work you did with recurring in core, you'd be a logical choice to get it right. lol, a little buttering up has never failed.

**Comment by epsdky** [comment]
Hello Jerry ( @sjpadgett  ),

I will speak to you about this soon.

**Comment by epsdky** [comment]
Original issue fixed so closing.

**Comment by epsdky** [comment]
(The title to this issue was not specific enough since I opened it in relation to the Onsite Patient
 Portal appointment finder module not handling recurrtype 3 events (now fixed) however my current
 PR is partly to do with recurrtype 3 appointments so title is possibly still relevant but I will leave issue
 closed)
