### ISSUE TITLE
No folders are copied to public/assets on CentOS 7 Minimal

### ISSUE THREAD

**Issue by MadMaxMangos** [openemr/openemr#2818]
After running:
composer install
npm install
npm run build
composer dump-autoload -o

No folders / files are being copied/installed into the public/assets folder.
System is a clean CentOS 7 minimal install with PHP 7.2.

Manually copying all folders from folder node_modules to ./public/assets does seem to work as a workaround. But still missing a jquery-ui which is generating a 404 error when inspecting any page.

**Comment by tywrenn** [comment]
The node_modules files are supposed to be moved to public/assets after running those commands as those commands by themselves do not move the files into that directory. I'd reccomend using the `mv` command to move these folders in without needing to move every single one of them. If you are dev testing this though it is highly recommended to use a docker-compose environment instead as the master branch can contain errors and should not be used for production purposes.

**Comment by sjpadgett** [comment]
composer install
npm install
npm run build
composer dump-autoload -o

Is all you should need.

**Comment by stephenwaite** [comment]
hi @MadMaxMangos , looks like there's some options for you to test with in the package.json, like `gulp-watch` thanks to @d3sandoval

**Comment by MadMaxMangos** [comment]
Will have to wait on someone else to investigate this as i'm not a dev sadly, just really wanted to report it was not working so it's logged and can be looked at.
