### ISSUE TITLE
Billing Manager Links broken in tabs version

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#282]
When Using Fees->Billing, The Billing Manager is displayed in a tab.
After filtering, the results are displayed.  Linking out to an encounter or demographics does not work in the tabbed/menu environment.

<img width="804" alt="billing_issues" src="https://cloud.githubusercontent.com/assets/508784/18847190/3d4ecb54-83f7-11e6-9714-90ffba327b18.png">

**Comment by bradymiller** [comment]
Just committed a fix for this to the codebase.
