### ISSUE TITLE
LBF - Checkboxes with text - Not all displayed / missing in patient reports

### ISSUE THREAD

**Issue by MadMaxMangos** [openemr/openemr#2820]
Having an issue with LBF and getting data inputted into them to display on a report. I have tried versions 5.0.1 and the latest GitHub and the issue still remains.

What gets generated on the report is just 2 checkboxes / text at random. It does not matter what I set in the layout for Label Cols or Data Cols, the result is the same each time.

As you can see from the screenshots I have multiple entries for the checkboxes with text but the report is only showing the same two in the patient report.

I have topic open on this on the forums - https://community.open-emr.org/t/lbf-checkboxes-with-text-not-all-displayed-missing-in-patient-reports/13207

**Comment by sjpadgett** [comment]
closing as fixed in patch and 503
