### ISSUE TITLE
Medical_problem subtype not logged in list table.

### ISSUE THREAD

**Issue by REEllison** [openemr/openemr#2826]
I added a few medical problems with the list editor and assigned them to a subtype I created.  The medical issues then show up in the add/edit issue window.  However the subtypes are not saved to the table when submitted.

![image](https://user-images.githubusercontent.com/7035884/69895444-925fd000-12fd-11ea-9173-0a58e4d07202.png)

![image](https://user-images.githubusercontent.com/7035884/69895453-bae7ca00-12fd-11ea-8916-1d2cc09a209d.png)

**Comment by bradymiller** [comment]
Hi @REEllison ,
I would consider this a bug. We need to update the add/edit issue window to update the subtype sql column. That subtype feature was added for the eye form (save mechanism for that is form is at: interface/forms/eye_mag/save.php ) and was not incorporated in the main add/edit issue window.
