### ISSUE TITLE
Query Error: Your password does not satisfy the current policy requirements

### ISSUE THREAD

**Issue by usama-kabel** [openemr/openemr#2827]
when I open Administration -> Rules and click any rule git this error 
![2](https://user-images.githubusercontent.com/7693823/69911339-c680e100-1422-11ea-8993-6dfa9cddadb7.png)

**Comment by usama-kabel** [comment]
This issue related to mysql library called validate_password uninstall this or modify it to low

**Comment by bradymiller** [comment]
hi @usama-kabel ,
Thanks for posting this issue. Re-opened this issue and started discussion of this issue on related forum thread:
https://community.open-emr.org/t/rules-engine-query-fail-but-not-on-all/13257/4

**Comment by juggernautsei** [comment]
After reviewing the code and researching the purpose. It can be used to increase security. But the question becomes, what is being secured? Rules? Why are the rules being hashed in this manner? I thought about taking it out but then would it be more damage? If there were only a couple, yes but there seems to be too many right now. Also, why on this one system and not all did this happen. I have multiple systems that are similar and this is the only one that this is occurring on. I will keep digging.

**Comment by juggernautsei** [comment]
@bradymiller is there anyone working on the rules engine?

**Comment by bradymiller** [comment]
Hi Sherwin,

Sorry for late reply. No ongoing work on the rules engine. Ray about a 
year or so ago did some work on it, but it was never completed. So, it 
is all yours :)

thanks,
-brady
