### ISSUE TITLE
Register Time Based One Time Password Key - TOTP

### ISSUE THREAD

**Issue by usama-kabel** [openemr/openemr#2828]
When I want to enable TOTP on openemr in the last step when I press register button nothing done and give me blank page 
after check error log I have this error 
[php7:notice] [pid 22148] OpenEMR Error : Decryption failed authentication., referer: openemr/interface/usergroup/mfa_totp.php
[php7:notice] [pid 22148] OpenEMR Error : Key creation is not working - Exiting., referer: openemr/interface/usergroup/mfa_totp.php
 
Thanks in advance

**Comment by bradymiller** [comment]
hi @usama-kabel ,
I suspect you don't have write privileges in all of your site/<likely default>/documents subdirectories. Was this a new install or upgrade and which openemr version and package are you using (also what is your os)?

**Comment by usama-kabel** [comment]
HI @bradymiller 
This is new version of openemr with the last patch 5.0.2(1) and OS ubuntu 18.04 LTS server edition 
Thanks
