### ISSUE TITLE
Canvas drawing uploads fails if thumbnail checked

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#283]
When storing canvas drawings, the drawings are sent to the server as $_POST['imgBase64'] in base64 encoding (at least the Eye Form works this way).  The images are processed by the addNewDocument function, called in save.php.
forms/eye_mag/save.php around line 912:
`$return = addNewDocument($filename,$type,$_POST["imgBase64"],0,$size,$_SESSION['authUserID'],$pid,$category_id);
`
If the Global->Document->Generate thumbnail is checked, the addNewDocument fails and throws an error.  It works without this checked.

**Comment by ophthal** [comment]
Yes

**Comment by bradymiller** [comment]
thanks. added it to 5.0.1 milestone to ensure this gets addressed before 5.0.1 release.
