### ISSUE TITLE
[Proposal] CI improvments

### ISSUE THREAD

**Issue by zerai** [openemr/openemr#2838]
- add phpunit/phpunit to composer (backend tests)
- add [symfony/panther](https://github.com/symfony/panther) or other testing lib/fw (frontend tests)
- update travis configuration

Is possible?

**Comment by bradymiller** [comment]
hi @zerai , Automated testing improvements would be very nice things to have. Are you interested in working on this? -brady

**Comment by pMononoke** [comment]
hi @bradymiller, yes I can work on this, especially on backend/server side tests.
Can I provide a PR with phpunit/travis setup?

**Comment by bradymiller** [comment]
This proposal is complete. Next step is building out the e2e and api testing.

**Comment by sjpadgett** [comment]
sorry
