### ISSUE TITLE
SIte ID missing enhancement

### ISSUE THREAD

**Issue by ghost** [openemr/openemr#284]
Instead of line 90 in globals.php: 
`if (!$ignoreAuth) die("Site ID is missing from session data!");`

redirect the user to the login screen and display the error message, 
"Site ID is missing.  Please login again."

https://github.com/ophthal/openEMR_2/tree/siteID-relogin

https://github.com/ophthal/openEMR_2/commit/35f7021cf2c8721b8a908ead7ece654ebc4e3445

**Comment by bradymiller** [comment]
I think the issue, though, is that with multisite, a user will then be directed to the default site; ideally, we should attack the bugs that are causing the error message. Was this to fix the bug in the tab layouts after a timeout or is the "Site ID is missing from session data!" showing up in other places?

**Comment by ophthal** [comment]
I believe I am seeing it after session timeouts: going from room to room, browser to browser, window to window or machine to machine…  
I’ll pay closer attention.  I’ll test it
Ray

**Comment by bradymiller** [comment]
Sounds good. Ensure test most recent codebase. We've checked in some commits into the codebase over the last couple days to fix the timeout issues.

**Comment by bradymiller** [comment]
@ophthal , Just checking if this is still an issue in the most recent codebase?

**Comment by ophthal** [comment]
I presume it is.  IMHO, what really should happen here is logic to look at the $_SERVER[‘HTTP_REFERER’] or something similar to extract the correct site for this user, so it works in a multisite environment and displays the correct login page with this error.  The bland “Site id is missing” is not very professional looking.  Kinda like it is not finished.  If there is no way to get back to the correct login screen for the user, then there could be a splash page using the openEMR logos, with this error message.

**Comment by sunsetsystems** [comment]
Sounds like what is happening is the PHP session is timing out before OpenEMR does.  I would consider that a configuration error, not something a user should normally encounter.  So yes, a more informative message would be good.

**Comment by bradymiller** [comment]
hi @ophthal ,
Are you still seeing this error message frequently in the most recent codebase?
thanks, -brady

**Comment by ophthal** [comment]
When appropriate, yes. I realize it is not an error but it is truly annoying. It’s like a stick 404 page when it could be so much more...  The answer I understood was we can’t change it because of mult-site iinstallations. I would think if you analyze the url calling it, there should be an easy way to show the correct site login splash page?

**Comment by ophthal** [comment]
Not sure 5.0.1 still has this issue.  I see it on mine production server but that is somewhere in limbo between 4.3 and 5.0.1.  I did a PR for a fix that'll work in solo-site installations, if it is needed. Otherwise you can close this.

**Comment by ophthal** [comment]
I'm on the latest codebase.  I never really restart my computer or browser.  After waking it from a sleep, with the browser window opened to a working session of openEMR that has presumably timed out, I get this “Site id is missing” white page.  It is supposed to kick me to the login screen right,  maybe with a message "Your session timed out"?

**Comment by ophthal** [comment]
I put up a PR which I am testing. 

https://github.com/openemr/openemr/pull/1605 

I'm not sure why @MDSupport limited the scope of this redirect leaving the die() message for the rest.
Again I need sage advice from the programmers to know if this is going to work.
I'll see how it works over time in my practice and let you know.

**Comment by ophthal** [comment]
Will  need to check this in frames version first. It works in tabs.

**Comment by tywrenn** [comment]
Coming back to this issue -- we need to find a fix for this somehow. The issue is when it happens inside an iframe (if i were to re-code it to direct to the login page it would do nothing correctly). I could see us coding something like we did I believe in the opener script with full page popups and that technically could work.
