### ISSUE TITLE
More flexible API

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr#2847]
Hi.

During work with the API we've found that the services of the data working with a limited amount of values, for example, ProviderService contains only 5 fields from the database (id, fname, mname,lname,username) there are a lot of other fields with info about user why we not return all of them?

Especially, the problem is with PatientService, the LBF enables to add custom files about patient dynamically, every customer can decide which fields be in "patient_data" table... why not fetching the data using `select * from` ?

If we want API will be available and helpful for new developers, I think it's important to return the maximum information as it possible (except security values). 

I'll be happy to hear your opinion about this issue.

Thank you.

Amiel (Matrix)

**Comment by sjpadgett** [comment]
Hi @matrix-amiel ,
Any improvements to our API is not only welcomed but, appreciated. 
We all know that the initial API's could be lacking in areas but, was/is a good starting point so, please by all means, improve.
