### ISSUE TITLE
Problem with Case Sessitivity

### ISSUE THREAD

**Issue by kchapple** [openemr/openemr#2851]
@bradymiller On a fresh clone of master, my git command line client is showing a modified file. It is possible that someone with a case-sensitive Linux workstation has checked in this file, with an upper-case 'U' in unit. My Mac sees this file, and the one with a lower-case 'u' in unit as the same file, so that it appears to have been modified. Can you fix to make sure this directory is checked-in as having a lower-case 'u'? 

I'm trying to submit critical fixes for NewCrop erx, and this is a blocker. Thanks!

```
[~/Dev/openemr/openemr] Thu Dec 19, 10:47:26 (master) $ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   tests/Unit/NumberToTextTest.php

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by kchapple** [comment]
It appears that @zerai broke this, and committed two directories, one with an upper-case 'U' in unit and one with a lower-case 'u' in unit.

**Comment by kchapple** [comment]
@stephenwaite @sjpadgett or @bradymiller can you please move the NumberToTextTest.php file into the lower-case 'unit' directory, and delete the upper-case 'Unit' directory? Thanks!

**Comment by sjpadgett** [comment]
Hi Ken, I just saw this on recent commit. Thanks for letting know the issue and i'll fix now.

**Comment by kchapple** [comment]
Thanks @sjpadgett you're the man!

**Comment by sjpadgett** [comment]
No coal in my stocking this year. :)

**Comment by sjpadgett** [comment]
@kchapple My git client(windows) will not even create the uppercase dir so unable to remove.
I did fix conflicts with lowercase dir file which is where it belongs so, pull master and let me know if you can continue to work until Brady can fix where we really want this test file.

**Comment by kchapple** [comment]
@sjpadgett whatever you did seemed to work, not there's only the lower-case dir. Thanks!

**Comment by sjpadgett** [comment]
You're welcome.
