### ISSUE TITLE
sl_eob_patient_note not working

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2860]
hi @sjpadgett :) why is it that when sl_eob_search opens sl_eob_patient_note with too small width 
https://github.com/openemr/openemr/blob/master/interface/billing/sl_eob_search.php#L641
it inactivates the text input
https://github.com/openemr/openemr/blob/master/interface/billing/sl_eob_patient_note.php#L66-L87
(noticed that when you inspect the element it thinks it's in the form-group below)

**Comment by stephenwaite** [comment]
sjp has this handled in bs4 project

**Comment by sjpadgett** [comment]
@stephenwaite 
Where is the Post Panel used? When should it show, perhaps on the upload. How does this work ie era upload? Thats where we want post for payment right?

**Comment by stephenwaite** [comment]
hi @sjpadgett , right, this is just for searching and displaying invoices (also for selecting the invoices to be printed on the statement) and the era upload should show the items that are in the era file after it's uploaded

**Comment by stephenwaite** [comment]
hey @sjpadgett , https://github.com/stephenwaite/openemr/commit/28b366201ee23e0c84144c5af45edadcdbb4977d, trying to fix that done with ins thing, could you take a look

if this was legit should I have run
`git push tywrenn:bootstrap-updates ins_done`

**Comment by sjpadgett** [comment]
@stephenwaite I'm sorry but that post bar makes no sense anymore. It's like the guts are gone for it and moved to invoice. This screen just no longer works the way I remember! So....what!
![image](https://user-images.githubusercontent.com/1859985/71385710-146aae00-25b7-11ea-8d73-9999bcab72e0.png)

**Comment by stephenwaite** [comment]
hi @sjpadgett , happy new year :confetti_ball: hope you're feeling better too
here's a little tweak or 2, https://github.com/stephenwaite/openemr/commit/0d4831777cb3049347c047d761ca20d70252ac2b and it's parent
