### ISSUE TITLE
Fee Sheet does not find any CPT codes when they are all loaded in

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#2886]
Original Thread: https://community.open-emr.org/t/fee-sheet-does-not-find-any-cpt-codes-when-they-are-all-loaded-in/13474

Not really sure how to fix this issue unfortunately.

**Comment by stephenwaite** [comment]
hi @tywrenn, unable to reproduce, have you tweaked your install of rel-502?

**Comment by tywrenn** [comment]
@stephenwaite Haven't tweaked it at all unfortunately.

**Comment by stephenwaite** [comment]
hi @tywrenn, it's just a bad sql table :)

**Comment by tywrenn** [comment]
Figured it out lol 😂 closing now
