### ISSUE TITLE
change button name during setup if already created database

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2889]
try creating a database before install and choosing the appropriate option in setup before proceeding to credentials screen

the button shouldn't say create db and user since you've already set those up

**Comment by prondubuisi** [comment]
Hello @stephenwaite what type of installation does one need to see this in action? A link will be nice cc @bradymiller

**Comment by stephenwaite** [comment]
hi @prondubuisi , sometimes one has already created the database and mysql user to get around some difficulty on their host. Please see [this url](https://github.com/openemr/openemr/blob/master/setup.php#L951)

**Comment by prondubuisi** [comment]
Hello @stephenwaite I am just seeing your reply Now. I am guessing that once the radio button `I have already created the database` is clicked there should be Javascript code that updates `Create DB and User` to something else, If this is the case; 

1. What do I update it to?
2. Looks like I need to add a Jquery Script [here](https://github.com/openemr/openemr/blob/master/setup.php#L1593) to update the button on radio button select?

**Comment by stephenwaite** [comment]
hi @prondubuisi , yes, you could update it to `Load database` and would emulate this block
https://github.com/openemr/openemr/blob/master/setup.php#L1652-L1665

**Comment by prondubuisi** [comment]
Okay @stephenwaite , when I am done with this fix, how do I test it to see if it is working as expected? I am guessing I have to attempt a new Openemr install? If so how do I do that manually, I normally use the docker install
 
Please do assign this issue to me

**Comment by stephenwaite** [comment]
hi @prondubuisi , you can follow the [multi-site setup guide ](https://www.open-emr.org/wiki/index.php/OpenEMR_Multiple_Sites_Module).

**Comment by bradymiller** [comment]
hi @prondubuisi ,
For the easy docker dev environment, I am willing to bet that using the following setting in that docker-compose.yml file will prevent the auto install:
https://github.com/openemr/openemr/blob/master/contrib/util/docker/docker-compose.yml#L104

**Comment by sachinmukherjee** [comment]
@stephenwaite Is this open? If open can I work on this issue?

**Comment by bradymiller** [comment]
@prondubuisi , are you ok if I assign this to @sachinmukherjee ?

**Comment by prondubuisi** [comment]
> @prondubuisi , are you ok if I assign this to @sachinmukherjee ?
Sure @bradymiller @sachinmukherjee you can go for it, looking forwrd to your PR

**Comment by sachinmukherjee** [comment]
![screencapture-172-20-0-4-setup-php-2020-03-23-20_55_29](https://user-images.githubusercontent.com/19318218/77332964-c8134380-6d48-11ea-8ffa-8251d123bedd.png)

I have tried to install a new site and have reached Step 1(Select Database Setup). What should I do next?

**Comment by stephenwaite** [comment]
hi @sachinmukherjee , have you already created the database?

**Comment by sachinmukherjee** [comment]
For a new installation, I haven't created the database

**Comment by stephenwaite** [comment]
go ahead and create a new database at the mysql command prompt or phpmyadmin;
`create database openemr;`
then go to the setup screen and choose "Have already created database" and proceed.
The install screen should update the button name to something appropriate instead of create database...

**Comment by sachinmukherjee** [comment]
@stephenwaite Sorry for the delayed response. Will do the same as mentioned above.

**Comment by stu01509** [comment]
Hello @sachinmukherjee 

Are you still working on this issue?

**Comment by sachinmukherjee** [comment]
@stu01509 Yes I have pinged @stephenwaite for some help.

**Comment by stephenwaite** [comment]
hi @sachinmukherjee how can i help?

**Comment by sachinmukherjee** [comment]
Hi @stephenwaite I have pinged you in slack. Got stuck while solving this.

**Comment by bradymiller** [comment]
hi @sachinmukherjee , will have more luck finding @stephenwaite in the openemr telegram chat: https://t.me/openemr
(posting on github is generally the best way to get help since others can also jump in and help out)

**Comment by stephenwaite** [comment]
yeah, there's just no such thing as privacy on slack, here either, or zoom video i guess
https://theintercept.com/2020/03/31/zoom-meeting-encryption/

**Comment by sachinmukherjee** [comment]
@stephenwaite @bradymiller  What should I used to change the button name PHP or Jquery. I have to check which radio button is checked out of the two(Have setup create the database or I have already created the database). I have tried using Jquery but I'm not getting the radio button value which is being checked.

**Comment by sjpadgett** [comment]
anytime dependencies scope is iffy, use javascript. anything in setup should be javascript and not jquery!

**Comment by bradymiller** [comment]
bump

**Comment by tywrenn** [comment]
You could make an invisible button that gets clicked to create the database...........

**Comment by stu01509** [comment]
Is the issue still need to fix? currently, I am working on the OpenEMR setup page, If is it required I will fix it

**Comment by bradymiller** [comment]
bump

**Comment by stephenwaite** [comment]
will fix soon

**Comment by stephenwaite** [comment]
weird my comment 7 days ago wasn't considered recent activity

**Comment by stephenwaite** [comment]
going to take another look and see why we even have the prompt `i created the database already` since it seems the installer is able to handle both situations just fine without needing to know what was selected from that radio input

may end up removing the selection altogether and do some rewording on the subsequent screens for a very seldom used choice anyways am guessing
