### ISSUE TITLE
billing report: generate x12 with continue not setting last_level_billed

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2895]
see @juggernautsei 's [post on the forum](https://community.open-emr.org/t/bug-report-billing-manager-marked-as-cleared-not-working-as-designed/12470/85?u=stephenwaite)

validate and clear is setting last_level_billed so shouldn't be too hard to play like @sjpadgett on github :)

**Comment by stephenwaite** [comment]
to begin we should set status to 2 [here](https://github.com/stephenwaite/openemr/blob/master/interface/billing/billing_process.php#L242)
```
                    $tmp = BillingUtilities::updateClaim(true, $patient_id, $encounter, $payer_id, $payer_type, 2, 1, '', $target, $claim_array['partner']);
```

**Comment by sjpadgett** [comment]
> shouldn't be too hard to play like @sjpadgett on github :)

I don't understand what this means.

**Comment by stephenwaite** [comment]
just meaning maybe could figure it out from your validation section

**Comment by stephenwaite** [comment]
made the change https://github.com/openemr/openemr/pull/2832, testing fine

**Comment by juggernautsei** [comment]
I will pull these down tonight and let you know once the system has been tested.
