### ISSUE TITLE
NPM install Error

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#2900]
Hi,

While trying to install a new openemr instance in windows, I run into the following NPM error. (I have already installed composer and NPM). 
![npm error](https://user-images.githubusercontent.com/1074948/73218672-7010f400-4180-11ea-81a2-3791aacbaefd.jpg)

Kindly help with the issue

Regards
Arnab

**Comment by bradymiller** [comment]
hi @arnabnaha ,
What versions of npm and nodejs are you using?

**Comment by arnabnaha** [comment]
npm version - 6.13.4
node js version - 12.14.1

**Comment by bradymiller** [comment]
hi @arnabnaha ,
jsnode 12.* doesn't work on the build (note it will work when we get the ongoing bootstrap PR into the codebase in the future. For now, need to stay on jsnode 10.* .

**Comment by im-Amitto** [comment]
@arnabnaha you can try `NVM` it allows you to use multiple node version in your system.

**Comment by bradymiller** [comment]
This issue is resolved in dev codebase which now works with jsnode 12.* . So, closing this.
