### ISSUE TITLE
Upgrade AngularJS to Angular

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#2901]
This issue will immediately follow the upcoming BS4 pull request. In order to update Angular to be BS4 compliant, we have to update Angular itself. (That is unless someone gets it to work with BS4)

[Upgrade guidelines on how to do this here](https://angular.io/guide/upgrade)

Unfortunately i'm not proficient in Angular so I won't be much help on this case.

**This issue is on hold until Bootstrap 4 is merged with the codebase to prevent merge issues**

**Comment by sjpadgett** [comment]
My issue and will bring appropriate portal features up to coding standards and implement for BS4. Angular to my knowledge was only used by me in portal chat and message/mail.
Closing as bookmark no longer needed but thanks for participating :)
