### ISSUE TITLE
(white) Empty tab on "Manage Modules"

### ISSUE THREAD

**Issue by zerai** [openemr/openemr#2902]
From menu when I click on MODULES->MANAGE MODULES I have an empty tab (title: "Unknown").
if I remember correctly should it be possible to see the module list?

Same behavior on [development demo](https://six.openemr.io/a/openemr/index.php) ("with demo data" version)

Screenshot from the online demo page
![Screenshot_2020-01-31 OpenEMR](https://user-images.githubusercontent.com/2405279/73525751-16bef400-4410-11ea-8994-9b78d01ba25a.png)

**Comment by zerai** [comment]
From apache log:
'
[Fri Jan 31 09:09:03.824380 2020] [php7:error] [pid 21] [client 192.168.32.1:34188] PHP Fatal error:  Cannot use Zend\\Db\\Adapter\\Adapter as Adapter because the name is already in use in /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php on line 24, referer: http://127.0.0.1:8300/interface/main/tabs/main.php?token_main=1unVEecKfF7xKaO2awShPYBuaxvaY1ALYckZCItx
'

**Comment by zerai** [comment]
If I comment [the line 24](https://github.com/openemr/openemr/blob/master/interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php#L24) it works,
I have the desired behavior, but I don't know the consequences, my knowledge about Zend is null, and i have no idea how modules works

Some Zend expert should see this issue.

**Comment by stephenwaite** [comment]
there was a [commit 4 hours ago](https://github.com/openemr/openemr/commit/6e228ee21c6d7fdd6c5b9ffb13fce118593077a4) and it looks to be addressing this issue. The demos will reset at midnight pacific time tomorrow and pick up this fix.

**Comment by bradymiller** [comment]
hi @zerai and @stephenwaite ,
Sorry about that; I must of had enough coffee when I rebased/merged that work. Thanks for the super quick fix! -brady
