### ISSUE TITLE
form_bronchitis

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#2909]
[form_bronchitis](https://github.com/openemr/openemr/tree/master/interface/forms/bronchitis) which is currently included as a standard form (activated as needed) seems to be an orphan in need of some redesign.  Current issues are :

1. [Table definition](https://github.com/openemr/openemr/blob/master/interface/forms/bronchitis/table.sql) uses varchar(255) to store 10s of checkboxes making the record exceed standard rowsize (> 8126) limit in Mariadb.
2. More importantly, since the hardcoded content uses ICD9, chances are it is not being used productively in its current state.
3. Applying BS4 will take some effort.

Suggest this be moved to contrib/forms-obsolete directory until someone really needs it and brings it up to current standards.

**Comment by mdsupport** [comment]
On a related note, noticed that ICD9 is still present in setup script.  It would be nice to update that part to kick off automatic load for ICD10 files if they are included in standard install package.

**Comment by sjpadgett** [comment]
Thanks @mdsupport , Attention of recent has been paid to our standard forms for BS4 but not sure if this one was included.  However, i'm sure it will be attended to regarding BS4.
Regarding recm to move to contrib forms. I feel there's a reason it was placed where it is and would hate to break any legacy involved. Anyway you could contrib a fix for sql and we'll take care of BS4?
Please don't feel obligated or feel like if you make recommends you'll be put on the spot as I just did.:) The ICD9 issue is also available:) We always appreciate input...

**Comment by mdsupport** [comment]
Thanks @sjpadgett - have gotten used to being put on spot.

This was just to put a marker since anyone trying to activate the form would encounter the error and raise the issue and/or fix the code.  

Submitting a database patch without going thru and researching the ICD9 to ICD10 mappings and fixing the code would just lay a trap for some unsuspecting MD to start using the form and later have to clean up the mess!!

**Comment by sjpadgett** [comment]
Okay. Bronchitis  is pretty common. Whether the form is useful, i'll need to take a look.
