### ISSUE TITLE
Address Book error on INSERT

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#291]
SQL error when inserting a new "lab service" record - here is SQL from error message
`
 INSERT INTO users ( username, password, authorized, info, source, title, fname, lname, mname, suffix, federaltaxid, federaldrugid, upin, facility, see_auth, active, npi, taxonomy, cpoe, specialty, organization, valedictory, assistant, billname, email, email_direct, url, street, streetb, city, state, zip, street2, streetb2, city2, state2, zip2, phone, phonew1, phonew2, phonecell, fax, notes, abook_type ) VALUES ( '', '', 0, '', NULL, 'Mr.', '5', '4', '6', , '29', '', '27', '', 0, 1, '28', '30', '1', '', '1', '7', '13', '', '14', '15', '16', '17', '18', '19', '20', '21', '21', '23', '24', '25', '26', '8', '10', '11', '9', '12', '31', 'ord_lab' )`

If `suffix` field is hidden, the insert value is set to `nothing` which causes the error.  You can add the records when suffix is shown.  If the user type is changed, the update fails.

**Comment by mdsupport** [comment]
This script needs rework to use binding but inserting one line after current line 122 of interface/usergroup/addrbook_edit.php will fix it for the time being -

`  $form_suffix = "''";
`

**Comment by Wakie87** [comment]
Rays eye form added suffix to "person centric" updated so "company centric" also includes suffix for the directors name.
