### ISSUE TITLE
Change 'composer install' to 'composer install --no-dev' at places in infrastructure where production use happens

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2910]
Reminder for me to do this at some point, so can then use the require-dev section in OpenEMR's composer.json.
Places (work in progress):
build script
dockers
demo farm (both build there and where it builds packages)

**Comment by tywrenn** [comment]
@bradymiller here's a reminder 😂

**Comment by bradymiller** [comment]
this is done :)
