### ISSUE TITLE
Patient Validation module

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#2912]
If patient validation module is turned on, you are presented with list of likely matches during save.  The popup issues are
1. It does not show any options to continue
2. The Cancel button clicks are ignored
3. Lookup results include the patient record being changed

Is there any documentation link for this module?

**Comment by stephenwaite** [comment]
hi @mdsupport since the readme only has a couple of lines regarding how to turn on for new and modify guess the only instructions are the [code](https://github.com/openemr/openemr/blob/master/interface/patient_file/summary/demographics_full.php#L849-L938)

**Comment by mdsupport** [comment]
That's what I did to find the settings in Globals.  But the buttons are not working because of parent document object is not valid for popup.  So I was wondering if anyone had a fix or this thing is specific to Matrix.

**Comment by sjpadgett** [comment]
I believe validate params are controlled in Lists->Page Validation. They use json. I've always have said this should reside with the appropriate code to be validated but was dismissed. There was and probably still an issue here. May not be your issue but one never knows.
That module was a contrib to openemr and there are folks that use and love it.
Also we moved Zend to it's replacement laminas. Maybe something there.
