### ISSUE TITLE
Problem with "add user" capability

### ISSUE THREAD

**Issue by zerai** [openemr/openemr#2913]
**Goal**:
Try to add a new administrator or physician

**Data for the new account**
username|firstname|lastname:   johndoe
password:   johndoejohndoeA23!    
(note: this should be a valid strong password)

**result**: in all case...
![Schermata del 2020-02-07 14-47-07](https://user-images.githubusercontent.com/2405279/74035642-ec92a680-49ba-11ea-8147-53128e139823.png)

In my local envionment after a fresh install (git clone http://......   and docker-compose up -d)
and default security settings in globals ( Require Strong Passwords: on,  Minimum Password Length 9) user creation fail .

even with minimum security requirements   ( Require Strong Passwords: off,  Minimum Password Length: 0) user creation fail.
It fail with the above password and with not strong passwords like   aaaa | hello | foobar

The same thing happens in the demo farm v.5.0.2
here [https://six.openemr.io/b/openemr/interface/login/login.php?site=default](https://six.openemr.io/b/openemr/interface/login/login.php?site=default)

Note: from file **usergroup_admin_add.php**

This piece of js code should be executed with Strong Passwords: on I think, but the modal message doesn't change.

```
    if(document.new_user.secure_pwd.value == 1){
        var password = trim(document.new_user.stiltskin.value);
        if(password != "") {
            var pwdresult = passwordvalidate(password);
            if(pwdresult === 0){
                alert(
                    <?php echo xlj('The password must be at least eight characters, and should'); ?> +
                    '\n' +
                    <?php echo xlj('contain at least three of the four following items:'); ?> +
                    '\n' +
                    <?php echo xlj('A number'); ?> +
                    '\n' +
                    <?php echo xlj('A lowercase letter'); ?> +
                    '\n' +
                    <?php echo xlj('An uppercase letter'); ?> +
                    '\n' +
                    <?php echo xlj('A special character'); ?> +
                    '\n' +
                    '(' +
                    <?php echo xlj('not a letter or number'); ?> +
                    ').' +
                    '\n' +
                    <?php echo xlj('For example:'); ?> +
                    ' healthCare@09'
                );
                return false;
            }
        }
    } //secure_pwd if ends here

```

**Comment by sjpadgett** [comment]
If using the default Your password,: ie ******** retype

**Comment by zerai** [comment]
Same result

Login in https://six.openemr.io/b/openemr/interface/login/login.php?site=default
actual configuration
![Schermata del 2020-02-07 17-29-23](https://user-images.githubusercontent.com/2405279/74047221-48b3f580-49d0-11ea-9a5a-d8dbc10483e0.png)

string "Clinton" for all fields

![Schermata del 2020-02-07 17-31-29](https://user-images.githubusercontent.com/2405279/74047436-9e889d80-49d0-11ea-9e92-9eec6863af5d.png)

**Comment by sjpadgett** [comment]
umm, this all works the way intended on demo. Make sure if changing another user's password to use the password of the logged in user for Your Password: *********. Otherwise if changing logged in user then of course use current password for Your Password.

**Comment by zerai** [comment]
oohhh god!!! 
Solved..... GDPR habit

**Comment by sjpadgett** [comment]
acknowledging the habit is the first step to recovery.:)
