### ISSUE TITLE
list editor title textbox not large enough for mime types

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2914]
error:
```The system does not permit uploading files with MIME content type - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.
list title not long enough to handle application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
```
so with whitelist enabled can't add long mime types to files type white list

looks like text size needs to be enlarged for the interface/super/edit_list.php gui

**Comment by adrijshikhar** [comment]
@stephenwaite i would like to work on this issue, can you please assign it to me?
PS: i have already setup the repo.

**Comment by stephenwaite** [comment]
:sunglasses: thank you

**Comment by ShubhamBansal1997** [comment]
@stephenwaite There is no update on this for a long time, let me pick this up

**Comment by bradymiller** [comment]
hi @ShubhamBansal1997 , it's yours :)

**Comment by ShubhamBansal1997** [comment]
@stephenwaite Is this issue due to DB or is it restricted over the GUI, if it's restricted over the GUI can you point out which page it is?

**Comment by stephenwaite** [comment]
hi @ShubhamBansal1997 , it's in lists, Admin->Forms->Lists->Files type white list
![Screenshot from 2020-03-24 19-21-13](https://user-images.githubusercontent.com/5618372/77485887-b7c09e80-6e04-11ea-96b3-1e6eb56b0480.png)

**Comment by ShubhamBansal1997** [comment]
@stephenwaite Please review the PR https://github.com/openemr/openemr/pull/3237
