### ISSUE TITLE
problems starting up open emr

### ISSUE THREAD

**Issue by PRINCE-MOSE** [openemr/openemr#2918]
gives me this error
localhost is currently unable to handle this request.
HTTP ERROR 500

**Comment by PRINCE-MOSE** [comment]
mosejnr.biz@gmail.com is my contact

**Comment by thesmallstar** [comment]
@PRINCE-MOSE 
Are you still facing the problem?
Can you please give your system specifications so we can help?

**Comment by stu01509** [comment]
Hi @bradymiller 

This problem seems to be solved?

**Comment by bradymiller** [comment]
hi @stu01509 , Thanks for pointing this out and gonna close this issue.
