### ISSUE TITLE
Error Email or SMS Notifications for User Debug.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#2919]
One could use our User Debug turned on via Globals Logging that reports just PHP errors and/or console errors to the display by adding an option like Notify Administrators Only and then intercept errors in utility.js, qualify error for where to report then do an ajax to send email/sms (using our email facilities) to a list from users or created lists(notify on errors email/sms etc) in Lists. 

Could also include server side logs if necessary.

Would actually be a nice feature add where administrators could be aware of issues w/o user having to report from display notifications.

**Comment by tywrenn** [comment]
Seems like a straight-forward enhancement that I could take up.

**Comment by sjpadgett** [comment]
Let me know if I can be of assistance. This could be very useful for folks that do remote admin.

**Comment by tywrenn** [comment]
Update: Can someone work on this for me?
