### ISSUE TITLE
tab layout - menu does not collapse after click

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#292]
Currently menu item list stays active after clicking (selecting) an item.  It collapses only after mouse is exits the area.  
Not a show stopper but certainly unusual UI behavior.

**Comment by robertdown** [comment]
I think given that we've got tabs, this should be considered expected behavior. This way it's easy to multiple tabs without having to go back and re-hover the menu.

**Comment by bradymiller** [comment]
@mdsupport , @robertdown ;
Sounds like we are good on the current functionality. If so, will close this issue (just let me know if I shouldn't close this issue).

**Comment by mdsupport** [comment]
Whether tabs or not, this is non-standard user interface.  We created a one-liner that takes care of it in our code.  Thx.

**Comment by bradymiller** [comment]
Sounds like we should keep this open for now.
@mdsupport , can you share the one-liner code, so we can test this out.

**Comment by mdsupport** [comment]
#423 brings in one of the functions.

**Comment by ophthal** [comment]
This is a nice fix to add to the codebase.

**Comment by bradymiller** [comment]
Agree is very nice! Just brought this into the codebase (will also bring it into rel-500 branch).
