### ISSUE TITLE
Remove jQuery UI

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#2924]
After some careful thought of what to do next, it's about time to remove jQuery UI. This has been a dead project for awhile now and hasn't received any updates. This change should allow us to keep theming consistent and improve responsiveness.

Here is the unofficial to-do list:
- [ ] Remove jQuery UI
- [ ] Replace old jQuery UI theming structure
- [ ] Adapt to current theming system

**Comment by sjpadgett** [comment]
umm, I removed all dependencies for resize and drag. We just went through core and removed BS3 popovers for jquery-ui but should be simple refactor.
Brady and I removed all jquery-ui modals awhile back so I don't think there are anymore but if so, let me know as I have an easy trick to replace.

**Comment by tywrenn** [comment]
@sjpadgett @mdsupport recommended me to tackle this issue. Apparently there is more to the story here.

**Comment by sjpadgett** [comment]
> Apparently there is more to the story here.

lol, yep could be.

**Comment by mdsupport** [comment]
@sjpadgett  Tabs in several areas - encounters, proc orders, billing, documents etc use jq-ui.  

Encounter summary uses tabs through [TabsWrapper](https://github.com/openemr/openemr/blob/master/src/Tabs/TabsWrapper.php).  At one point we internally spent serious time to convert that to BS nav but it has links in various forms.  Hopefully we can use events in new structure.

I think main layout also relies on jq-ui for tabs.  As such lot of 'unresponsive' behavior of the overall application leads to jq-ui.

**Comment by bradymiller** [comment]
This is a mandatory item as jq-ui is a dead project and only a matter of time before it starts breaking with other assets (such as jquery and bootstrap). So, I say, go for it :)

**Comment by bradymiller** [comment]
Couple places it's used includes:
1. registration modal in login screen and about screen
2. the EDI history modal
3. Encounter tabs
4. And some other random places

**Comment by mdsupport** [comment]
@sjpadgett's comment in other issue caused a bit of soul searching on knockout.js.  [First google hit](https://stackoverflow.blog/2018/01/11/brutal-lifecycle-javascript-frameworks/) has [this chart](https://149351115.v2.pressablecdn.com/wp-content/uploads/2018/01/trends-minor.png) that illustrates where it is in its life cycle.  It is a challenge for openemr as well as other opensource projects to avoid similar fate.

**Comment by sjpadgett** [comment]
@mdsupport Thanks for the research. I'm trying to be better at having an open mind to modernization  so some of this takes me a minute to get use to.
I do like knockout and off top of my head don't see an easy path there. An example would be helpful.

**Comment by mdsupport** [comment]
@sjpadgett To be clear, wasn't trying to knock that package ;-)  But because of #2608 may be it is time to revisit interface/main/tabs. Since we use / could use navbars in 10s of other places as well, project needs a generic oe-ui-navbar class based on one of the php framework utility classes ([zend](https://docs.laminas.dev/laminas-navigation/helpers/menu/) / [symfony](https://symfony.com/doc/current/bundles/KnpMenuBundle/index.html) / ..).  On the client side bootstrap has probably the same functionality as knockout for manipulating the dom objects.

**Comment by bradymiller** [comment]
Here's most recent issue breaking this issue down into many more issues:
https://github.com/openemr/openemr/issues/2999

**Comment by sjpadgett** [comment]
Probably should keep open if for anything, eyeing knockout.js
Although, while we are doing a lot of code mods, wouldn't hurt if run across an ajax convert to fetch.

**Comment by bradymiller** [comment]
bump

**Comment by bradymiller** [comment]
bump

**Comment by bradymiller** [comment]
bump

**Comment by stephenwaite** [comment]
bump
