### ISSUE TITLE
Unable to Run Using Docker: Getting "Could not reliably determine the server's fully qualified domain name"

### ISSUE THREAD

**Issue by litemikx** [openemr/openemr#2926]
Hi,

Unable to run openemr using docker, I'm getting:

> httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message

Any tips on how to resolve this? Tried to edit the actual httpd.conf file and uncomment the "ServerName", I then set it to localhost and/or 127.0.0.1. I presume this doesn't work since the container ID changes whenever I do the "docker-compose up"? 

Thanks!

**Comment by stephenwaite** [comment]
hi @litemikx think that's just an apache warning and the trouble lies elsewhere

what steps are you taking to spin up docker?

**Comment by litemikx** [comment]
> hi @litemikx think that's just an apache warning and the trouble lies elsewhere
> 
> what steps are you taking to spin up docker?

There seems to be a changed in the docker-compose.yml since I don't see the additional setting that was previously there. I just run it by using "docker-compose up". Can't run the application when I visit 127.0.0.1:8300 or localhost:8300. I can open phpmyadmin and mysql.

**Comment by stephenwaite** [comment]
yep, trying a new way thanks to @bradymiller 's [commit](https://github.com/openemr/openemr-devops/commit/ac9d91c76eeb1346bb41b1f280f040ce2efde6c6)

did you pull down the new docker?

**Comment by litemikx** [comment]
> yep, trying a new way thanks to @bradymiller 's [commit](https://github.com/openemr/openemr-devops/commit/ac9d91c76eeb1346bb41b1f280f040ce2efde6c6)
> 
> did you pull down the new docker?

So far local repo is updated, I see the changes made by @bradymiller in the docker-compose.yml. I'll try to troubleshoot, been this for a few weeks now for me. I guess I'll just work on running it locally without the docker containers.

**Comment by stephenwaite** [comment]
hi @litemikx , meant `docker pull openemr/openemr:flex`
https://community.open-emr.org/t/openemr-flex-docker-updated/12051/12

**Comment by litemikx** [comment]
> hi @litemikx , meant `docker pull openemr/openemr:flex`
> https://community.open-emr.org/t/openemr-flex-docker-updated/12051/12

Great! It works now, didn't now that I needed to update docker for that.
