### ISSUE TITLE
X12_5010_837P prints both the billing and service facility even if they are the same

### ISSUE THREAD

**Issue by growlingflea** [openemr/openemr#2929]
The x12 5010 837P file will print both the service and billing facility even if they are the same.  Clearing houses may accept this but BCBS and other insurance companies will throw an error. 

I have the fix for this.  So I will make a pull request for it.

**Comment by stephenwaite** [comment]
thanks for #2930

**Comment by stephenwaite** [comment]
brought in fix so closing
