### ISSUE TITLE
Report AMC 2014 stage 2 bugs

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2933]
hi @bradymiller , will email @jit to direct him here

starting to look at numerator not populating for
>Secure Electronic Messaging( AMC-2014:170.314(g)(1)/(2)-19 )

it looks like there is a :bug: [here](https://github.com/openemr/openemr/blob/master/library/classes/rulesets/Amc/reports/AMC_314g_1_2_19/Numerator.php#L34-L35)

think the sql query should be `pid` not `user` even though that might not meet the intent of the measure since won't check for the EP actually receiving a message but couldn't find `$patient->provID` in the library for the rulesets so probably would have to be added

**Comment by bradymiller** [comment]
The certification was done for the offsite portal which uses the pnotes for messages between providers/patients. So, this query is checking to see if any pnotes were sent by the patient (the user in this scenario).

**Comment by stephenwaite** [comment]
hi @jitchawla, was an offsite portal was used for secure messaging?

**Comment by jitchawla** [comment]
Yes believe it was offsite.

**Comment by stephenwaite** [comment]
ok, please search your pnotes table looking for an entry for a patient that should have been picked up in the numerator
>SELECT  * FROM `pnotes` WHERE `user` = ? AND `date` >= ? AND `date` <= ?;
