### ISSUE TITLE
multi site install permissions checking

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#2943]
instead of having to change permissions on already existing sites to proceed with multi-site setup tried to disable $checkpermissions in setup.php but it needs some :love_hotel:

**Comment by prondubuisi** [comment]
Hello @stephenwaite what is going on here. Lol. Is something I can work on my docker install?

**Comment by stephenwaite** [comment]
hi @prondubuisi , say you were going to setup another site from your multi-site install but and were fine with turning off permissions checking because your server would have to scan through all of your files in the `OE_SITE_DIR`, which could be tens maybe hundreds of thousands for all of the folders for patient documents in each site
https://github.com/openemr/openemr/blob/master/setup.php#L201-L226
so you manually set `$checkPermissions` to false per the comment instructions but the script is not handling that currently:
https://github.com/openemr/openemr/blob/master/setup.php#L1556
not a clickable link

**Comment by prondubuisi** [comment]
> hi @prondubuisi , say you were going to setup another site from your multi-site install and were fine with turning off permissions checking because your server would have to scan through all of your files in the `OE_SITE_DIR`, which could be tens maybe hundreds of thousands for all of the folders for patient documents in each site
> https://github.com/openemr/openemr/blob/master/setup.php#L201-L226
> so you manually set `$checkPermissions` to false per the comment instructions but the script is not handling that currently:
> https://github.com/openemr/openemr/blob/master/setup.php#L1556
> not a clickable link

I am guessing this set $checkPermissions to false will be for development environments right?

**Comment by stephenwaite** [comment]
it's ok to leave it to be hard coded to true for everyone and we could update the multi-site guide to help somebody from having to go into the code

https://www.open-emr.org/wiki/index.php/OpenEMR_Multiple_Sites_Module

**Comment by prondubuisi** [comment]
> it's ok to leave it to be hard coded to true for everyone and we could update the multi-site guide to help somebody from having to go into the code
> 
> https://www.open-emr.org/wiki/index.php/OpenEMR_Multiple_Sites_Module

This should solve it. Looks like there is an actual check for $checkPermissions here https://github.com/openemr/openemr/blob/master/setup.php#L1491 

I guess a Wiki Account is needed to update the docs?

**Comment by stephenwaite** [comment]
hi @prondubuisi , yes there's a check but if we advise to go in and set it to false to avoid checking there should be a clickable link around line 1556

**Comment by prondubuisi** [comment]
Oh I see. There  is no link or button there  
 https://github.com/openemr/openemr/blob/master/setup.php#L1556

**Comment by stephenwaite** [comment]
@bradymiller can get you hooked up with wiki

**Comment by bradymiller** [comment]
hi @prondubuisi ,
Request a wiki account here:
https://www.open-emr.org/wiki/index.php/Special:RequestAccount
(just let me know after you submit the request, and then I'll confirm it)

**Comment by prondubuisi** [comment]
> hi @prondubuisi ,
> Request a wiki account here:
> https://www.open-emr.org/wiki/index.php/Special:RequestAccount
> (just let me know after you submit the request, and then I'll confirm it)

Hello @bradymiller account has been requested. Thanks.

**Comment by bradymiller** [comment]
hi @prondubuisi , done. let me know if not working.

**Comment by prondubuisi** [comment]
> hi @prondubuisi , done. let me know if not working.

Did not get any message regarding the wiki account in my inbox.

**Comment by bradymiller** [comment]
I did think it was odd that you weren't confirmed (ie. email wasn'd verified). Anything in your junk mail?

**Comment by prondubuisi** [comment]
> I did think it was odd that you weren't confirmed (ie. email wasn'd verified). Anything in your junk mail?

Seen in Spam Folder

**Comment by prondubuisi** [comment]
Hello @bradymiller @stephenwaite , I added the instructions discussed here to the docs https://www.open-emr.org/wiki/index.php/OpenEMR_Multiple_Sites_Module#Installation_of_a_new_site, please let me know if it passes the message

**Comment by prondubuisi** [comment]
Hello @stephenwaite I think this patch https://github.com/openemr/openemr/pull/2944/files is related to this issue, any idea why it is yet to be merged?

**Comment by stephenwaite** [comment]
thanks @prondubuisi , one add'l instruction would be to manually create the site directory, say 'mysite' for example under `sites\` and give it writable permission for the webserver so that it can create the add'l directories needed

think that PR just hasn't been reviewed yet, what do you think?

**Comment by prondubuisi** [comment]
Hello @stephenwaite , I could add this extra information to the docs, Would also want to see how multisite install works with the $checkpermissions turned off , first hand. Can also review your PR while doing so.

How do I proceed with a multi-site install using the docker setup @stephenwaite @bradymiller

**Comment by prondubuisi** [comment]
Hello @stephenwaite , I could add this extra information to the docs, Would also want to see how multisite install works with the $checkpermissions turned off , first hand. Can also review your PR while doing so.

How do I proceed with a multi-site install using the docker setup  @bradymiller

**Comment by stephenwaite** [comment]
hi @prondubuisi, thank you but there is no multi-site install for docker currently, you'd have to incorporate the admin.php page and some how script it in

**Comment by bradymiller** [comment]
hi @prondubuisi ,
I think we can get there via the dev docker tools in some steps.
1. The api on feature will provide an example of modifying the database in docker. This is not a dev tool command, but after figure out how to do that, can mimick same process for modifying database via other dev tool command.
2. Then we can do a command that does a `empty-openemr`, which then drops the openemr database, changes `$config = 1;` to `$config = 0;` in `sites/default/sqlconf.php`, and restores an empty `sites/default/` from `/openemr/sites/default`. What this setting will do is basically clear the current install of OpenEMR, which means the dev will get to go through the manual install process (via setup.php), thus making development in installation scripts super easy.
3. Then we can do a command that does a `reset-openemr`, which does everything above, but also does a auto install (ie. bypasses the manual setup.php script like is done when start up the docker).
4. Then can bring in a command that does the changes required to use the multi site install (and also a command to revert the changes).

**Comment by prondubuisi** [comment]
> hi @prondubuisi, thank you but there is no multi-site install for docker currently, you'd have to incorporate the admin.php page and some how script it in

@stephenwaite with your guide, I will go ahead and add the extra instructions to the documentation. Looks like @bradymiller has a possible incorporation that can help bring multi site install to docker. Sure that will take some time though

**Comment by prondubuisi** [comment]
> hi @prondubuisi ,
> I think we can get there via the dev docker tools in some steps.
> 
> 1. The api on feature will provide an example of modifying the database in docker. This is not a dev tool command, but after figure out how to do that, can mimick same process for modifying database via other dev tool command.
> 2. Then we can do a command that does a `empty-openemr`, which then drops the openemr database, changes `$config = 1;` to `$config = 0;` in `sites/default/sqlconf.php`, and restores an empty `sites/default/` from `/openemr/sites/default`. What this setting will do is basically clear the current install of OpenEMR, which means the dev will get to go through the manual install process (via setup.php), thus making development in installation scripts super easy.
> 3. Then we can do a command that does a `reset-openemr`, which does everything above, but also does a auto install (ie. bypasses the manual setup.php script like is done when start up the docker).
> 4. Then can bring in a command that does the changes required to use the multi site install (and also a command to revert the changes). This would then make it super easy to do development work on this feature.

Hello @bradymiller this looks like something that requires a breakout issue. Also looks like it would be a huge WIP. If you think it would be a good one, I will go ahead and create a Support multi-site setup for Docker issue. I am here for the fun and long ride.

**Comment by bradymiller** [comment]
hi @prondubuisi , Feel free to make the multi-component issue (1 will be straightforward, 2 will be almost straightforward, 3 will get tougher, and 4 will get even tougher). The reason I ordered them that way, is they build on each other (ie. can leverage what was done in earlier steps to complete the later steps). This would deal with some of the easy dev docker env weaknesses:
1. Can't test/dev the installation very easily
2. Can't do a quick OpenEMR reset without needing to do a full docker down/up
3. Can't test/dev multisite

**Comment by prondubuisi** [comment]
> permission for the webserver so that it can create the add'l directories

Hello @bradymiller, I tried logging in to OpenEMR wiki to make add this additional information, I am getting the error below 
![Login error](https://user-images.githubusercontent.com/22311928/79415364-211b7380-7fa5-11ea-9046-1e0c59020b7d.png)

**Comment by bradymiller** [comment]
hi @prondubuisi , The server ran out of storage. I just fixed this, so it should be working for you now.

**Comment by prondubuisi** [comment]
> give it writable permission for the webserver so that it can create the add'l directories needed

Hello @stephenwaite, I added the additional information as recommended https://www.open-emr.org/wiki/index.php/OpenEMR_Multiple_Sites_Module#Installation_of_a_new_site

**Comment by stephenwaite** [comment]
looks great @prondubuisi , think you got everything

**Comment by tywrenn** [comment]
Closed due to it being resolved

**Comment by stephenwaite** [comment]
stalebot won't meet his quota :smiley:
