### ISSUE TITLE
Step 3 in setup.php with non-green "OK"

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2946]
Need to make all the "OK" labels green (note 3 in the middle are black)

![image](https://user-images.githubusercontent.com/278968/75088992-067ad000-5509-11ea-83e3-451c8be0d300.png)

**Comment by thesmallstar** [comment]
Hello @bradymiller sir, Can I work on this?

**Comment by bradymiller** [comment]
hi @thesmallstar ,
Go for it!
-brady
