### ISSUE TITLE
Step 7 in setup.php need to add selections for the 2 new themes

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2947]
Need to add selections for two recently added themes:
Dark
Superhero

![image](https://user-images.githubusercontent.com/278968/75089047-a46e9a80-5509-11ea-9eb4-9d2f2d74b60c.png)

**Comment by stu01509** [comment]
@bradymiller Hi
I would like to try this work, Are Dark and Superhero theme have design guide?

**Comment by stephenwaite** [comment]
hi @stu01509 , yes, they are already loaded into the project thanks to some super, recent work by @tywrenn 

https://github.com/openemr/openemr/tree/master/interface/themes/oe-styles

would you like to be assigned this issue?

**Comment by stu01509** [comment]
@stephenwaite Yes, Please assign me, Thank you.

**Comment by tywrenn** [comment]
The way selecting themes are displayed is pretty odd. Probably needs a redo.

**Comment by stu01509** [comment]
@bradymiller  @stephenwaite @tywrenn 
Hi all, Excuse me I have a question,
The theme use **listThemes()** function to count the theme, 
So I just put Dark and Superhero screenshot to **public/images/stylesheets** folder,
 Am I right?

**Comment by bradymiller** [comment]
That looks right. Basically adding a style_dark.png and style_superhero.png should get what you need . That looks like a very neat mechanism, which was added by @zbig01 in past.

**Comment by stu01509** [comment]
@bradymiller 
Hi sir, I've been added dark and superhero theme screenshot, 
Please review it, If have any change request, Please let me know :)
