### ISSUE TITLE
Fix search in the Globals settings screen

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2948]
This feature is no longer working well. OpenEMR->Administration->Globals is where there are literally hundreds of settings. And the search feature at top right is very helpful to find settings. Currently, if I search for something like 'Default' it only highlights the categories, but does not highlight the actual items (ie. it is half working).

Note below when search for 'Default' it highlights left menu (categories) Appearance, Locale, Features, etc. But note it is not highlighting the actual settings (for example, Default Second Tab, Default Font should be highlighted).

![image](https://user-images.githubusercontent.com/278968/75089156-e21ff300-550a-11ea-8d7c-ce50a8c765e3.png)

**Comment by thesmallstar** [comment]
Sir, I would like to work on this.

**Comment by bradymiller** [comment]
hi @thesmallstar , It's yours. Thanks! -brady
