### ISSUE TITLE
Create a Administration->System->Diagnostics gui

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2949]
Migrate the stuff from Administration->Clinic->Calendar->'Test System'
to a new nicer looking gui at:
Administration->System->Diagnostics

**Comment by aryaman-titan** [comment]
@bradymiller i would like to take this issue, can you please assign it to me?

**Comment by stephenwaite** [comment]
hi @aryaman-titan , here you go :)

**Comment by thesmallstar** [comment]
@stephenwaite  can I try this?

**Comment by im-Amitto** [comment]
@thesmallstar 
last row of the Diagnostics gui is leaking secret html information. take care of it while moving it.
![Screenshot from 2020-02-29 02-19-11](https://user-images.githubusercontent.com/29653282/75586232-e82d4b00-5a99-11ea-80c9-d414137a8f71.png)

**Comment by bradymiller** [comment]
hi @thesmallstar , it is yours :)

**Comment by stu01509** [comment]
Hi @thesmallstar 

Are you working on this issue?

**Comment by thesmallstar** [comment]
@stu01509 you can take this, I am currently involved into something. Cannot postpone this longer 😄

**Comment by stu01509** [comment]
Hi @bradymiller 

Please assign this issue to me.

**Comment by bradymiller** [comment]
hi @stu01509 , the baton has been passed to you :)

**Comment by stu01509** [comment]
Hi @bradymiller 

Is this issue would like to add Diagnostics in Administration->System navbar?
Like this?

![image](https://user-images.githubusercontent.com/22230889/77219457-e9b9d280-6b70-11ea-8241-c59fcbee5f2d.png)

**Comment by bradymiller** [comment]
hi @stu01509 , yep, that looks good

**Comment by stu01509** [comment]
Hi @bradymiller 

I created a PR, Please review it :)
