### ISSUE TITLE
js error when creating new patient

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2950]
Nothing appears to be broken (ie. am able to create new patients), however am seeing a js error in the browser console:

![image](https://user-images.githubusercontent.com/278968/75089478-06c99a00-550e-11ea-8acf-72564c375879.png)

**Comment by sjpadgett** [comment]
L-301 of interface/new/new_search_popup.php
 `f.create.value = <?php echo xlj('Confirm Create New Patient'); ?>;`
needs to be deleted.

This must go back several versions!

**Comment by thesmallstar** [comment]
@sjpadgett are you working on this?

**Comment by sjpadgett** [comment]
It's done in PR #2954 Was just going to close.

**Comment by thesmallstar** [comment]
@sjpadgett Glad this is fixed :D

**Comment by sjpadgett** [comment]
I woke up in a problem solving sort of mood this a.m.:)
