### ISSUE TITLE
Patient history gui is broken

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2951]
Patient summary screen->History is broken (2 errors are displayed in the web console and nothing happens when click on the category tabs):

![image](https://user-images.githubusercontent.com/278968/75089516-73449900-550e-11ea-942f-6a55c2d87f56.png)

**Comment by thesmallstar** [comment]
Sir, can I work on this?

**Comment by bradymiller** [comment]
hi @thesmallstar , Sure thing. thanks! -brady

**Comment by sjpadgett** [comment]
Umm, @thesmallstar I already fixed this when I was fixing another issue. Sorry, i'm sure we'll find others for ya to work.

P.R #2954 if interested.
Closing as fixed.

**Comment by thesmallstar** [comment]
Glad this is already fixed! 
I will find other issue.
