### ISSUE TITLE
Improve README.md document link

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#2955]
I would like to modify the content below list

1. Change http link to https.
2. Fix Chat link https://chat.open-emr.org/ to https://openemr.herokuapp.com/, It seems 502 bad gateway error.

![](https://i.imgur.com/Bw0Db6Q.png)

**Comment by bradymiller** [comment]
hi @stu01509 ,
Thanks for noting that. Please fix and rec changing the chat link to:
https://www.open-emr.org/chat/

**Comment by stu01509** [comment]
@bradymiller  OK, Please assign me, I will create PR.

**Comment by bradymiller** [comment]
done and thanks!
