### ISSUE TITLE
Install from branch issue

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#2956]
Recently I tried cloning the openemr repo, moving it to a folder in apache, and running the install script stated in README.md. Turns out, a lot of stuff is broken on this type of install. The most notable one is that the node_modules fail to move to /public/assets. It also failed at editing select2 for some reason. I'm running the latest Ubuntu and this happens every single time. After I fixed both of these, jquery-ui wasn't installed and I had to fix that too. Dunno why this hasn't been fixed yet, maybe its time to update the readme.

**Comment by bradymiller** [comment]
hi @tywrenn ,
I haven't experienced this issue. What ubuntu version are you using? And what nodejs version are you using?
-brady

**Comment by bradymiller** [comment]
btw, pretty typical that the standard nodejs version for ubuntu is outdated. Ensure you are using either 10.* or 12.* .

**Comment by tywrenn** [comment]
We should have that in the readme then 😂 Devs will just assume it works with whatever they're using. I'm using the preinstalled version.

**Comment by bradymiller** [comment]
Agreed. I am going to do that now.

**Comment by bradymiller** [comment]
Just brought in the updated README.
