### ISSUE TITLE
Close button not working in two modals

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2957]
In Popups->Export and Popups->Import, clicking on the Close button at bottom right does not do anything.

![image](https://user-images.githubusercontent.com/278968/75102083-77b69380-559a-11ea-82b1-bf483d79e680.png)

**Comment by sjpadgett** [comment]
probably need to change from window.close to dlgclose().

**Comment by thesmallstar** [comment]
@spadgett are you working on this?

**Comment by bradymiller** [comment]
hi @thesmallstar , pretty sure @sjpadgett is just providing guidance on this. we have a custom function, dlgclose() for closing modals.

**Comment by thesmallstar** [comment]
Thank you, please assign this to me :)

**Comment by bradymiller** [comment]
It's yours :)
