### ISSUE TITLE
Log viewer looks odd

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2958]
gui at Administration->System->Logs looks odd

![image](https://user-images.githubusercontent.com/278968/75102146-e0524000-559b-11ea-8109-753cfdd79d78.png)

<br>

Note that the Main Log and Other Logs are combined in a odd way. Would be better to have pills at top to choose either Main Log or Other Log (or any other way that you can think of improving the log gui).

**Comment by stu01509** [comment]
@bradymiller
I would like to try this work, If ok please assigns me, Thank you.

**Comment by bradymiller** [comment]
hi @stu01509 , sure thing! thanks, -brady

**Comment by stu01509** [comment]
Hi, @bradymiller  Can you close this issue?

**Comment by bradymiller** [comment]
thanks for the ping on this. closing.
