### ISSUE TITLE
Modernize language editor gui

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2959]
Change the top menu at Administration->System->Language to use pills.

![image](https://user-images.githubusercontent.com/278968/75102208-9ddd3300-559c-11ea-868a-a30dd1be545d.png)

**Comment by stu01509** [comment]
@bradymiller 
I would like to try this work, Please assign me, Thank you.

**Comment by bradymiller** [comment]
hi @stu01509 , sure thing! thanks, -brady
