### ISSUE TITLE
Test OpenEMR and report any issues

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2960]
This is an open ended issue for folks to test OpenEMR and report any issues, which can be:
php error log entries
js console error entries
bugs
work flow doesn't make sense
label doesn't make sense
just doesn't look right
could look better

(To clarify, if you find something to report, then create a separate issue for it)

**Comment by thesmallstar** [comment]
Sir, I had a general suggestion- should we add PR and issue template to this repo?

Also, I saw that 5.0.2 dev is facing notice issues with xampp, can we work on that?

**Comment by bradymiller** [comment]
hi @thesmallstar , The PR/issue template sounds like a great idea. Regarding xampp with 5.0.2, that is specific to windows and it should be working; it's just tougher to install than linux at this time.
-brady

**Comment by thesmallstar** [comment]
@bradymiller  Should I add the PR/issue template then?
Also, what is the correct approach to submitting issues? Should be directly created them or suggest them in comments below? 
I am commenting one for now,
UI bug in Edit global setting(The header is cut):
![image](https://user-images.githubusercontent.com/42006277/75106475-23b3b980-5643-11ea-90be-f185de947472.png)

**Comment by bradymiller** [comment]
hi @thesmallstar ,
Yes, it's a go on the PR/issue template
And definitely directly create issues for these and future issues
(or else this issue will become very long :) )
