### ISSUE TITLE
Improve gui at Patient Summary - Edit Clinical Reminder - Admin

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2961]
Guessing that several small code changes can drastically improve gui at Patient Summary screen -> Edit Clinical Reminder -> Admin
(there are 2 tables on top of each other with different number of columns without any shading etc.)

![image](https://user-images.githubusercontent.com/278968/75102351-daaa2980-559e-11ea-8b7a-0b87de1d7d78.png)

**Comment by thesmallstar** [comment]
Sir, can I try this?

**Comment by bradymiller** [comment]
hi @thesmallstar , Go for it. Thanks! -brady
