### ISSUE TITLE
Bad UI: Hidden header in edit Global setting page

### ISSUE THREAD

**Issue by thesmallstar** [openemr/openemr#2970]
**Screenshot:**
![image](https://user-images.githubusercontent.com/42006277/75117132-c7798580-5694-11ea-834e-33f6b70fa529.png)

I would like to work on this

**Comment by im-Amitto** [comment]
@thesmallstar 
I didn't know you will be creating this issue so I have created the same in #2971 and already dropped a PR #2972.
@bradymiller should I delete my issue and PR? 
Sorry for the inconvenience caused.

**Comment by thesmallstar** [comment]
@im-Amitto hey! (just noticed too many things happened :) )
We both ended up doing the same thing, at the same time :P 
It is not a problem, the main purpose was to solve the issue.
@bradymiller  can merge any one of the PR, let's leave it to him.
