### ISSUE TITLE
Missing button style/class in issue popup

### ISSUE THREAD

**Issue by thesmallstar** [openemr/openemr#2974]
Screenshot:
![image](https://user-images.githubusercontent.com/42006277/75118091-debc7100-569c-11ea-80aa-cb57a5eaf222.png)

I would like to work on this.

**Comment by bradymiller** [comment]
:+1:

**Comment by thesmallstar** [comment]
Closed by #2980

**Comment by stephenwaite** [comment]
ok, very nice, thank you
