### ISSUE TITLE
Finding issues

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#2975]
If you are looking for issues to work on, here are some issues organized by priority:
* [High Priority](https://github.com/openemr/openemr/milestone/5)
* [Normal Priority](https://github.com/openemr/openemr/milestone/6)
* [Low Priority](https://github.com/openemr/openemr/milestone/7)

(most of these are not simple straightforward issues; there are some nice small, but more complicated issues in Normal Priority)

**Comment by akhillllldev** [comment]
So, while creating a new patient -

Once you enter the patient details and click "Create Patient" -> you get a new pop up window with the option to confirm new patient, 

but the details are not getting printed.

**Comment by im-Amitto** [comment]
@akhi

> So, while creating a new patient -
> 
> Once you enter the patient details and click "Create Patient" -> you get a new pop up window with the option to confirm new patient,
> 
> but the details are not getting printed.

Most probably because of #2984

**Comment by stephenwaite** [comment]
hi @akhillllldev , good point but think that is a popup that would have any potential duplicate checks, maybe it needs to be titled better? or actually have a title :)

**Comment by tywrenn** [comment]
Bump

**Comment by jackzulaa** [comment]
ERROR : 
 Exception: Connect Error: SQLSTATE[HY000] [1044] Access denied for user 'openemr'@'localhost' to database 'aioprod'
 Exception: SQLSTATE[HY000] [1044] Access denied for user 'openemr'@'localhost' to database 'aioprod'
SQL statement : SELECT * FROM modules ORDER BY mod_ui_order ASC

#0 C:\xampp\htdocs\aioprod\vendor\zendframework\zend-db\src\Adapter\Driver\Pdo\Pdo.php(255): Zend\Db\Adapter\Driver\Pdo\Connection->connect()
#1 C:\xampp\htdocs\aioprod\vendor\zendframework\zend-db\src\Adapter\Adapter.php(192): Zend\Db\Adapter\Driver\Pdo\Pdo->createStatement('SELECT * FROM m...')
#2 C:\xampp\htdocs\aioprod\interface\modules\zend_modules\module\Application\src\Application\Model\ApplicationTable.php(60): Zend\Db\Adapter\Adapter->query('SELECT * FROM m...')
#3 C:\xampp\htdocs\aioprod\interface\modules\zend_modules\module\Installer\src\Installer\Model\InstModuleTable.php(227): Application\Model\ApplicationTable->zQuery('SELECT * FROM m...', Array)
#4 C:\xampp\htdocs\aioprod\interface\modules\zend_modules\module\Installer\src\Installer\Controller\InstallerController.php(58): Installer\Model\InstModuleTable->allModules()
#5 C:\xampp\htdocs\aioprod\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(78): Installer\Controller\InstallerController->indexAction()
#6 C:\xampp\htdocs\aioprod\vendor\zendframework\zend-eventmanager\src\EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 C:\xampp\htdocs\aioprod\vendor\zendframework\zend-eventmanager\src\EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 C:\xampp\htdocs\aioprod\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#9 C:\xampp\htdocs\aioprod\vendor\zendframework\zend-mvc\src\DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#10 C:\xampp\htdocs\aioprod\vendor\zendframework\zend-eventmanager\src\EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 C:\xampp\htdocs\aioprod\vendor\zendframework\zend-eventmanager\src\EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 C:\xampp\htdocs\aioprod\vendor\zendframework\zend-mvc\src\Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#13 C:\xampp\htdocs\aioprod\src\Core\ModulesApplication.php(99): Zend\Mvc\Application->run()
#14 C:\xampp\htdocs\aioprod\interface\modules\zend_modules\public\index.php(52): OpenEMR\Core\ModulesApplication->run()

**Comment by bradymiller** [comment]
bump
