### ISSUE TITLE
No validation on Patient DOB

### ISSUE THREAD

**Issue by im-Amitto** [openemr/openemr#2976]
### Describe the bug

A patient can have any desired DOB which should not be a case as a patient shouldn't have age in negative.
![Screenshot from 2020-02-24 04-54-12](https://user-images.githubusercontent.com/29653282/75122346-86986580-56c2-11ea-84db-3b0fc7ef1344.png)

### Expected behavior
Patient DOB should always be smaller than the current date.

### Client configuration

- Browser: Chrome Version 80.0.3987.106 (Official Build) (64-bit)
- Operating system: Windows 10

**Comment by im-Amitto** [comment]
@bradymiller 
can I pick this one?

**Comment by bradymiller** [comment]
hi @im-Amitto , Agreed and it's yours :)

**Comment by im-Amitto** [comment]
@bradymiller It took me quite a time to realize that all fields validation is directly coming from database.
Now, i know that adding a `past_date` validation to DOB will solve the problem but i am not sure which database file should i update.

**Comment by thesmallstar** [comment]
@im-Amitto, can we not go for the front end validation using on change function?
On change of the date of birth field, verify if the date selected is not after today, if it is change the value to today and give a alert. 

Am I missing something?

**Comment by im-Amitto** [comment]
@thesmallstar yeah, that's one easy way to implement that but after going through the repo i found out that validator is already present and all the validation/constraints are directly generated from database wherever necessary and i think it's a pretty good idea as it encapsulate the validation part so i guess sticking to that is a better idea.

Edit: I deleted the previous comment as i found the solution while reading a recent pr

**Comment by thesmallstar** [comment]
I agree, that is the better way to encapsulate the validation.
Thank you for the explanation 😄
