### ISSUE TITLE
Problem appears when you try to add a patient after reject him once

### ISSUE THREAD

**Issue by im-Amitto** [openemr/openemr#2983]
### Describe the bug

write a concise description of what the bug is.

### To Reproduce

https://www.loom.com/share/e4f7ce4823d34bd9bfe45d014e4e2c15

### Expected behavior
OpenEMR - problem with adding a patient

### Client configuration

- Browser: Chrome Version 80.0.3987.106 (Official Build) (64-bit)
- Operating system: Windows 10

**Comment by sjpadgett** [comment]
var scope is lost.
checkout new_comprehensive.php
around L-864
either refresh form after dialog closes or move where f is set to where it is used.

**Comment by im-Amitto** [comment]
@sjpadgett Thanks for the heads up!
