### ISSUE TITLE
Encapsulate the empty datetime/date checks

### ISSUE THREAD

**Issue by im-Amitto** [openemr/openemr#2984]
### Describe the bug

MySQL8 Latest patch release does not take `''` as a valid DateTime input hence all such checks should be updated. 

### Expected behavior
SQL queries shouldn't break; 

### Client configuration

- Browser: Chrome Version 80.0.3987.106 (Official Build) (64-bit)
- Operating system: Windows 10

Reference:- https://community.open-emr.org/t/cannot-choose-patient-from-list-due-to-mysql-8/13717

**Comment by im-Amitto** [comment]
@bradymiller where should I place the `dateEmptySql` method? As it's going to be used in multiple files, currently I placed it in `clinical_rules.php`.

**Comment by bradymiller** [comment]
hi @im-Amitto ,

We've got several options to make this function ubiquitous:
https://github.com/openemr/openemr/blob/master/composer.json#L88-L94

My vote is to place it in:
library/sanitize.inc.php

If you put it there, then it will always be available.

-brady
