### ISSUE TITLE
Database spell mistake

### ISSUE THREAD

**Issue by im-Amitto** [openemr/openemr#2987]
### Describe the bug

Technical term mistake, I am not sure though.

In database `history_data.cholecystestomy`, i guess it should be `history_data.cholecystostomy`.

If it's a bug, I would like to work on it.

**Comment by stephenwaite** [comment]
nice catch @im-Amitto , probably was meant to be the more common, Cholecystectomy
>Cholecystectomy is the surgical removal of the gallbladder. Cholecystectomy is a common treatment of symptomatic gallstones and other gallbladder conditions.

**Comment by bradymiller** [comment]
I'd rec avoiding this rabbit hole (mispelled sql columns) especially in forms which are not always
 loaded in database (makes incorporating into upgrade very tough). Most of these issues have been mitigated and fixed on the front end (would check in that form to ensure that happens) so it's just us developers that have to see it :) .

**Comment by im-Amitto** [comment]
@bradymiller  let's close this one then?

**Comment by bradymiller** [comment]
hi @im-Amitto , yep, lets close this (it's a good catch; just not worth the pain to fix).
