### ISSUE TITLE
UI Issue: Message Center add new form table

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#2989]
### Describe the bug

Message Center add new form table, The table field didn't alignment each one, And Button color may create identification problems.

I will fix this issue, Please assign me.

### To Reproduce

1. Click Message
2. Click Add New Button
3. See Add form

![Untitled](https://user-images.githubusercontent.com/22230889/75248939-21528a80-5810-11ea-91e2-98593cb339a4.png)

### Client configuration

- Browser: Google Chrome 79.0.3945.130 (Official Build) (64-bit)
- Operating system: Windows 10

**Comment by stephenwaite** [comment]
sounds like a plan :), thank you @stu01509

**Comment by stu01509** [comment]
Hi @stephenwaite @bradymiller, 

This issue has been resolved, Can I close the issue by myself?

**Comment by bradymiller** [comment]
Hi @stu01509 , Definitely feel free to close resolved issues. If github doesn't let you, just let us know and we'll then close it. thanks, -brady
