### ISSUE TITLE
ISSUE_TEMPLATE issue

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#2992]
### Describe the bug
ISSUE_TEMPLATE  has duplicate order number issue.

### To Reproduce

![Untitled](https://user-images.githubusercontent.com/22230889/75251328-59100100-5815-11ea-8cb8-42d2b1ddd012.png)

**Comment by thesmallstar** [comment]
Thank you for pointing, I had been working on this :) do you mind if I correct it in next PR?

**Comment by thesmallstar** [comment]
Also, your review on PR template would help me :) , I have just made a PR.

**Comment by stu01509** [comment]
@thesmallstar  Welcome

Also, I think we can add Screenshots and add php, web server version
and runtime in Client configuration field, What do you think?

**Comment by thesmallstar** [comment]
I am a bit confused why will we need the client configuration while reviewing PR, can you please explain?

**Comment by stu01509** [comment]
Oops! I mean will can add more client configuration in ISSUE_TEMPLATE.

Also,  PR template, I think we can discuss with mentors, What 's field can help them to review code  easily and clearly.

**Comment by thesmallstar** [comment]
Yes I agree with the PHP version, thank you😄

**Comment by stu01509** [comment]
Hi @thesmallstar,

Are you fixed ISSUE_TEMPLATE duplicate order number issue?
The problem still exists.

**Comment by thesmallstar** [comment]
I have made the changes, will add it in the next pr.

**Comment by stu01509** [comment]
> I have made the changes, will add it in the next pr.

OK :)
