### ISSUE TITLE
DOB problem still persists.

### ISSUE THREAD

**Issue by adad20** [openemr/openemr#2998]
### Describe the bug
Problem of DOB validation still persists after successfully merging  #2982 

### Expected behavior

Patient shouldn't be allowed to select future DOB.

### Current behaviour

After merging PR. Patient can still choose future DOB.
![Screenshot (67)](https://user-images.githubusercontent.com/55142272/75312215-4500e980-587f-11ea-98e8-533bcad9475c.png)

### System Information
PHP Version : 7.4.1
Browser : Chrome Version 79.0.3945.130

**Comment by im-Amitto** [comment]
Have you updated your db?

**Comment by im-Amitto** [comment]
@adad20  There are a few cases where a cross-browser error appears but still, it's a good practice to put system info along with the issue ｡◕‿◕｡.

**Comment by adad20** [comment]
@im-Amitto Yes I have updated the system information and can you elaborate how to update db?

**Comment by im-Amitto** [comment]
@adad20 
A simple way would be, you just drop your tables and source the `database.sql` or you can set `$config = 1;` in `sqlconf.php`. 

Note: If you use the second method choose `already have database setup` during setup.

**Comment by mdsupport** [comment]
Every date(time) field is supposed to be handled by datetimepicker which will do the [date validation](https://xdsoft.net/jqplugins/datetimepicker/#mindate) reliably by disabling future dates and fixing manual input.  This should be in addition to the validation of POST data.

**Comment by im-Amitto** [comment]
@mdsupport Thanks for the heads up! I will add the desired validation.

**Comment by bradymiller** [comment]
Confirmed that fix is working on my system (ubuntu 16.04; Firefox 72.0.2)
![image](https://user-images.githubusercontent.com/278968/75325909-81f0c000-582e-11ea-9f36-495060c15ae9.png)
After click 'Create New Patient' it show 'Date of Birth is not valid' and does not proceed with submit

**Comment by bradymiller** [comment]
keep in mind datetimepicker has a limited lifespan in the codebase (it is not mobile friendly), so feel free to throw in the towel on that if it gets to time consuming

**Comment by adad20** [comment]
If its working on your system means it is the cross platform error I guess.
Should I close this issue?

**Comment by bradymiller** [comment]
hi @adad20 ,
If it's still not working on your machine, lets sort it out. What do you see at Administration->Forms->Layout->Demographics->(in DOB row, click on the `?` at the far right)

![image](https://user-images.githubusercontent.com/278968/75330010-7b197b80-5835-11ea-889d-f0d373425284.png)

**Comment by adad20** [comment]
@bradymiller Should I check the validation rules?

It looks something like this.
![Screenshot (68)](https://user-images.githubusercontent.com/55142272/75330467-27477a80-58a7-11ea-8030-817fbd24ad93.png)

**Comment by bradymiller** [comment]
In the box, change Validation Rule to 'Past Date' and see if it works. (if it works, this prob means your database was not built from most recent codebase)

**Comment by adad20** [comment]
@bradymiller yes now the validation is working

**Comment by im-Amitto** [comment]
@bradymiller adding the maxDate in the datepicker is quite easy but it's global for the entire page so will affect all datepickers present.
one way i can think of is do a `each` over the `datepicker` and read the `maxDate` attribute and based on that i can decide the `jquery selector` and required configuration for datepicker and then will connect datepicker to all the generated `jquery selector`.

**Comment by sjpadgett** [comment]
Just give the date input element an unique id or new class then init a new datepicker in page for that element.
$('.#specialoptions').datetimepicker({
                <?php $datetimepicker_timepicker = false; ?>
                <?php $datetimepicker_showseconds = false; ?>
                <?php $datetimepicker_formatInput = false; ?>
                <?php require($GLOBALS['srcdir'] . '/js/xl/jquery-datetimepicker-2-5-4.js.php'); ?>
            });

**Comment by im-Amitto** [comment]
@sjpadgett i thought a generic solution would be better.
