### ISSUE TITLE
Change encounter tabs from jquery-ui to bootstrap

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3002]

**Comment by stu01509** [comment]
Hi @bradymiller 

Please assign this issue to me, Thank you.

**Comment by bradymiller** [comment]
hi @stu01509 , done :)

**Comment by stu01509** [comment]
Hi @bradymiller,
Is this page?

![Untitled](https://user-images.githubusercontent.com/22230889/75600061-e4271a80-5ae5-11ea-9bb8-4edbb0b1b080.png)

**Comment by bradymiller** [comment]
hi @stu01509 , Not that page; it's the page when you open an encounter. And then there is a tabs menu showing the forms that are opened:

![image](https://user-images.githubusercontent.com/278968/75600186-4d187f00-5a61-11ea-81b9-ef8dd675eeb3.png)

![image](https://user-images.githubusercontent.com/278968/75600190-54d82380-5a61-11ea-8e8d-dfbc41c8267a.png)

![image](https://user-images.githubusercontent.com/278968/75600195-628da900-5a61-11ea-9786-993715a1429c.png)

![image](https://user-images.githubusercontent.com/278968/75600198-6c171100-5a61-11ea-934b-7d33b0cb39ce.png)

**Comment by stu01509** [comment]
Hi @bradymiller 

I've changed to Bootstrap Tab, How it looks like?
If ok, I will create a PR.
![Untitled](https://user-images.githubusercontent.com/22230889/75602026-4db22380-5afc-11ea-87ab-de008701127d.png)

**Comment by bradymiller** [comment]
looks great. did you also get the tabs at top (that Summary tab and also when open a form it creates new tabs near the Summary tab)?

**Comment by stu01509** [comment]
Do you mean, when I open other tabs, such as Fee Sheet,
The Administrative and Clinical they should show on top?

**Comment by bradymiller** [comment]
![image](https://user-images.githubusercontent.com/278968/75602173-a390b800-5a77-11ea-8407-a72f7158747f.png)

Meant to point towards the tabs at the top when open lots of patient forms. In pic above, opened to the SOAP tab (which can close if click on X) and can go to the other tabs by clicking on them.

**Comment by stu01509** [comment]
This is my change to the Fee Sheet page.
I need to add  Administrative and Clinical they show on top?
![Untitled](https://user-images.githubusercontent.com/22230889/75602249-5b68a880-5afe-11ea-8b30-c3a6ee5d1116.png)

**Comment by bradymiller** [comment]
Don't need to do that. The workflow is that people go to the Summary page to open a new form.

**Comment by bradymiller** [comment]
otherwise folks will likely lose track of what forms they are editing :)

**Comment by stu01509** [comment]
Ok, So can I create the PR?

**Comment by bradymiller** [comment]
definitely. looking forward to seeing it.
