### ISSUE TITLE
Remove jquery-ui from interface/clickmap/template/general_new.html script (and related library/js/clickmap.js)

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3003]
Remove jquery-ui from interface/clickmap/template/general_new.html script (and related library/js/clickmap.js)

**Comment by stu01509** [comment]
Hi @bradymiller 

Is Anyone working on this issue? If not, please assign this issue to me.

**Comment by bradymiller** [comment]
hi @stu01509 , it's yours :)

**Comment by stu01509** [comment]
> hi @stu01509 , it's yours :)

Thank you.

**Comment by stu01509** [comment]
Hi @bradymiller 

Can you tell me How to go to this page?
Thanks.

**Comment by bradymiller** [comment]
hi @stu01509 ,

That is used by the pain form.
In Administration->Forms->Forms Administration
Graphic Pain Map->Register then Install DB then click disabled

Then in patient encounter, can found the form in Miscellaneous category.
