### ISSUE TITLE
Change jquery-ui tooltip to bootstrap tooltip for 3 scripts

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3004]
Change jquery-ui tooltip to bootstrap tooltip for the following scripts:
interface/billing/sl_eob_search.php
interface/orders/types.php
interface/usergroup/adminacl.php

**Comment by stu01509** [comment]
Hi @bradymiller 

I am starting to change jquery-UI tooltip to bootstrap tooltip,
But I have some question, The style still looks the same jquery-UI, Is correct?

![1](https://user-images.githubusercontent.com/22230889/75409127-cbd2c680-5952-11ea-991c-97e378efcb36.png)

This is my modify code.

```javascript
$('#advanced-tooltip').attr({"title": <?php echo xlj('Click to manually configure access control, recommended for advanced users'); ?>, "data-toggle": "tooltip", "data-placement": "bottom"}).tooltip();
$('#user-tooltip').attr({"title": <?php echo xlj('Click the pencil icon to grant and remove access privileges to the selected user'); ?>, "data-toggle": "tooltip", "data-placement": "bottom"}).tooltip();
$('#group-tooltip').attr("title", groupTitle).tooltip();
$('#new-group-tooltip').attr({"title": <?php echo xlj('Enter values in this section to create a new group also known as Access Request Object (ARO)'); ?>, "data-toggle": "tooltip", "data-placement": "bottom"}).tooltip();
$('#remove-group-tooltip').attr({"title": <?php echo xlj('Use this section to delete existing groups or Access Request Objects (AROs)'); ?>, "data-toggle": "tooltip", "data-placement": "bottom" }).tooltip();
$("#membership_show").click();
```

**Comment by bradymiller** [comment]
hi @stu01509 , Yep, no need to change styling (unless you feel the need to). Goal is to remove dependency on jquery-ui. If that code is working, then I am all for it :)

**Comment by stu01509** [comment]
Hi @bradymiller 
I has been changed jquery-UI tooltip to bootstrap tooltip,
Please check is correct, If have any requested change, please ping me :)
