### ISSUE TITLE
Remove jquery-ui from the Fees->'EDI History' module

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3005]
Remove jquery-ui from the Fees->'EDI History' module

**Comment by im-Amitto** [comment]
@bradymiller can i work on this one?

**Comment by tywrenn** [comment]
This one will require a lot of work since it uses JQUI autocomplete and themes as well as outdated dialog methods.

**Comment by im-Amitto** [comment]
sounds like something I should go for 🐺 .

**Comment by bradymiller** [comment]
hi @im-Amitto , go for it :)

**Comment by stu01509** [comment]
Hello @bradymiller 

Please reassign this issue to me, Thank you.

**Comment by stephenwaite** [comment]
there you are @stu01509 , good luck :diamond_shape_with_a_dot_inside:
