### ISSUE TITLE
Collapse/expand are not working on the Encounter gui

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3017]
### Describe the bug

Collapse/expand are not working on the Encounter gui

### To Reproduce

1. Go to the patient encounter gui
1. Create a SOAP note there and save it
1. Note that the expand/collapse is not working correctly (the labels change but the data fields are not expanding or collapsing)

![image](https://user-images.githubusercontent.com/278968/75399293-bc9b3c80-58b0-11ea-9606-d978cfaceb06.png)

Nothing is showing up in the js console.

### Expected behavior

The data fields should collapse/expand. I am willing to bet there is a simple js hide/show issue going on.

### Client configuration

- Browser: Firefox 72.0.2
- Operating system: Ubuntu 16.04

**Comment by adad20** [comment]
@bradymiller  I want to work on this issue. Please assign it to me.

**Comment by bradymiller** [comment]
hi @adad20 , it is yours :)

**Comment by tywrenn** [comment]
@bradymiller @adad20 We should be trying to use BS4 accordions/collapses in this fix. That might take more work to do but it's worth it.

**Comment by adad20** [comment]
@tywrenn yeah sure.
