### ISSUE TITLE
(Low Priority) Documentation Does not have closing </p> tags

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3029]
### Describe the bug

`help_files` documentation doesn't have closing `</p>` tags in [this entire folder](https://github.com/openemr/openemr/tree/master/Documentation/help_files). These tags need to be there to comply with W3C guidelines.

This is a pretty simple fix that should be quick to solve.

**Comment by stu01509** [comment]
@tywrenn 
I would like to fix it, Please assign me.

**Comment by stu01509** [comment]
Hi @tywrenn, @bradymiller 

I has been created PR, Please review it,
If have any change requested, Please let me know :)

**Comment by tywrenn** [comment]
@stu01509 So happy you did this -- this has been hanging over my head for a few months now. Thanks for contributing!

**Comment by stu01509** [comment]
Hi @tywrenn 

I also appreciate @bradymiller quickly review and merged it.
In addition, I found the same issue and kind messy in other pages.
