### ISSUE TITLE
Layout editor is being mean

### ISSUE THREAD

**Issue by im-Amitto** [openemr/openemr#3032]
### Describe the bug

If you try to edit layout using layout editor it make validation field to 1 for all fields.

### To Reproduce
https://www.loom.com/share/a50a090720ee4cfaa15b1a78003e33da

### Expected behavior
Validation should be granted based on the user selection

### Client configuration

- Browser: Chrome 80.0.3987.106 (Official Build) (64-bit)
- Operating system: Ubuntu 18.04.4

**Comment by tywrenn** [comment]
@im-Amitto This file isn't BS4 compliant at all so it might need even more fixes down the road. Some notable things include the fact certain inputs don't have the `form-control` class and the fact that popup areas don't really look too great. Most of this will be done in GSoC yet if you're up for the challenge you can certainly try fixing those other issues in the file.

**Comment by im-Amitto** [comment]
@tywrenn I guess I will go with it :)

**Comment by bradymiller** [comment]
hi @im-Amitto ,
Unable to verify this (btw, this loom thing is great!) :
https://www.loom.com/share/6fda04aa767c4edfa481096c91a968fa

**Comment by im-Amitto** [comment]
@im-Amitto Still the same for me, whenever i try to update a validation it set all validation for that form to 1.
I even did a re-setup.

**Comment by im-Amitto** [comment]
This scary stuff happens when i click on save changes button. I will try to debug it tomorrow.
![Screenshot from 2020-03-01 07-01-09](https://user-images.githubusercontent.com/29653282/75617827-7f71cb80-5b8a-11ea-9764-3faa8d783ff1.png)

**Comment by bradymiller** [comment]
Notices shouldn't be a problem. I'd have your php logging not even logs those to avoid the noise when debugging.

Because of the sheer number of POST variables in this form, ensure your max_input_vars in php.ini is set very high (3000 is the recommendation, but try to bump it up to even 5000 if that isn't working).

**Comment by im-Amitto** [comment]
Thanks! It worked.
