### ISSUE TITLE
Patient information is not coming while confirming

### ISSUE THREAD

**Issue by adad20** [openemr/openemr#3038]
### Describe the bug
When we try to add new patient the information we entered for the patient is not showing while confirming.

### To Reproduce
![Screenshot (72)](https://user-images.githubusercontent.com/55142272/75597894-0e64e200-5abe-11ea-8969-b9ab6653dde6.png)

### Steps to reproduce the behavior:
1. Add a patient
2. Click on create new patient

### Expected behavior
Information we entered must show on.

**Comment by im-Amitto** [comment]
It shows a list of patients who are matching the patient you are trying to
add not the patient himself.

**Comment by adad20** [comment]
Ohh my bad 😅
