### ISSUE TITLE
Ofc Notes add empty note content.

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3040]
### Describe the bug

Ofc Notes can add empty note content.

### To Reproduce

1. Go to miscellaneous.
2. Select Ofc Notes.
3. Click Office Notes (More)
4. Click Add New Note button.
5. See the empty note.

![Untitled](https://user-images.githubusercontent.com/22230889/75608165-1c574900-5b38-11ea-99ce-8eb9e9f9e4e6.png)

### Client configuration

- Browser: Google Chrome 79.0.3945.130 (Official Build) (64-bit)
- Operating system: Windows 10

**Comment by im-Amitto** [comment]
@stu01509 lol i read the `Ofc` as Of course and i was like what :laughing:

**Comment by bradymiller** [comment]
It's sort of like sending a ping. Like I am here for you , but have nothing to say :)

**Comment by stu01509** [comment]
@im-Amitto  It's very fun XDD
