### ISSUE TITLE
Remove jquery-ui dependency from TabsWrapper.php

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3042]
### Describe the problem

jquery-ui is used in src/Tabs/TabsWrapper.php

### Describe the solution you'd like

We are removing jquery-ui from codebase, so need to remove this dependency on jquery-ui.

This code is used for the tabs in the encounter gui:

![image](https://user-images.githubusercontent.com/278968/75613169-65c77a00-5adf-11ea-9103-d3132175a2b5.png)

**Comment by im-Amitto** [comment]
@bradymiller i would like to work on this one.

**Comment by bradymiller** [comment]
hi @im-Amitto , it is yours :)
