### ISSUE TITLE
Merge Patient

### ISSUE THREAD

**Issue by usama-kabel** [openemr/openemr#3052]
when I go to merge patient page and select patients to merge I have sql error in below screenshoot 

![image](https://user-images.githubusercontent.com/7693823/75624586-5cf9a580-5bbe-11ea-985b-bf9b957cf892.png)

**Comment by im-Amitto** [comment]
@usama-kabel  can you please specify the software version you are using.

**Comment by usama-kabel** [comment]
OpenEMR v5.0.2(1)

**Comment by stu01509** [comment]
Hi @usama-kabel,

I think you can listing Database, Web Server and runtime environment,
It will help to find the problem.

**Comment by TychoDickerson** [comment]
@stu01509 It is also not working in the appliance/.ova pre-package build

**Comment by stephenwaite** [comment]
hi @usama-kabel  since `keys` is a reserved word in mysql it needs to be escaped with back ticks like the below
```
sqlQuery("SHOW COLUMNS FROM `" . escape_table_name($tblname) . "` WHERE " .
            "`Field` LIKE 'pid' OR `Field` LIKE 'patient_id'");
