### ISSUE TITLE
Lag time between OpenEMR and TOTP mobile apps 

### ISSUE THREAD

**Issue by usama-kabel** [openemr/openemr#3053]
I install TOTP successfully and it works fine but now the mobile app generate code when I enter it within the time in mobile screen show not valid code

When I keep the code until the new one generated and enter the old one. the old one works fine and the new one generated already  

How I can fix it ?!

**Comment by sunsetsystems** [comment]
TOTP requires accurate timekeeping on the server. Assuming Linux, make sure ntp is installed and working.

**Comment by usama-kabel** [comment]
@sunsetsystems  thanks for your support.
