### ISSUE TITLE
Edit Global Setting expand button overflow

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3060]
### Describe the bug

Edit Global Setting expand button overflow.
Expand and Go to top button lost cursor pointer property.

### To Reproduce

1. Go Administrator
2. Click Globals
3. See expand button

![1](https://user-images.githubusercontent.com/22230889/75719896-8a566880-5d10-11ea-91ff-b6b89699b43b.png)

![2](https://user-images.githubusercontent.com/22230889/75719901-8de9ef80-5d10-11ea-882e-5480f48a4499.png)

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

**Comment by im-Amitto** [comment]
@stu01509 can't reproduce the overflow one but they do need a hand cursor.

**Comment by stu01509** [comment]
Hi @im-Amitto 

I see you have been fixed overflow issue 10 days ago,
So I just add a hand cursor.

Thank you :)
