### ISSUE TITLE
Calendar text link change to Bootstrap tabs.

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3062]
### Describe the bug

Calendar text link change to Bootstrap tabs.

### To Reproduce

1. Go to Administrator > Clinic
2. Click Calendar 
3. See all text links

![1](https://user-images.githubusercontent.com/22230889/75722348-018dfb80-5d15-11ea-9275-044a67c463ca.png)

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

**Comment by skshahnawaz** [comment]
Hello, I am Sk Shahnawaz , CSE UG Student from Jadavpur University, India. I have been working with bootstrap ui and css design for the past 3 years. I would like to take up this issue and solve it. Would you please assign me this?

**Comment by bradymiller** [comment]
hi @stu01509 , Let me know if you are working on this Issue (and in future to avoid this, may be best t state you will be working on an issue that you start, so I can assign it to you; I don't want to assume this though and assign you every issue you create :) )

hi @skshahnawaz and welcome to OpenEMR on github! I think @stu01509 is probably already working on this, but will see. I'll do a quick test on OpenEMR today and post some good starter issues regarding ui/css. Also recommend testing OpenEMR out and identifying places that don't look right or could look better or need responsive fixing.

**Comment by skshahnawaz** [comment]
okay @bradymiller  I am also planning on taking up OpenEMR as my GSoC Organisation for 2020. Expecting more collaboration on the way

**Comment by stu01509** [comment]
Hi @bradymiller, @skshahnawaz 

I am working on this issue.
