### ISSUE TITLE
Toggle elements in Facility Add/Edit not consistent

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3065]
### Describe the bug

Different toggle elements being used in Facility Add and Facility Edit gui

### To Reproduce
![image](https://user-images.githubusercontent.com/278968/75807106-ad494280-5d39-11ea-92c1-69fb4c95b709.png)

![image](https://user-images.githubusercontent.com/278968/75807140-bb975e80-5d39-11ea-90f6-2f7bf3db6ca5.png)

1. Go to Administration->Clinic->Facilities
2. Click on Add Facility to see new facility gui
3. Click on the 'You Clinic Name Here' facility to see the edit facility gui

### Expected behavior

Note that old toggle elements are used in the new facility gui and new toggle elements are used in the edit facility gui. So, lets change it to the new toggle elements also in the new facility guii

### Client configuration

- Browser: Firefox 73.0.1
- Operating system: Ubuntu 16.04

**Comment by bradymiller** [comment]
hi @skshahnawaz , you want this issue?

**Comment by skshahnawaz** [comment]
Yes , glad to take this up

**Comment by skshahnawaz** [comment]
Thanks for assigning this to me. Can I get a bit more details about this issue?

**Comment by bradymiller** [comment]
The Edit Facility modal is using the shiny nice looking toggles for the Billing Location and 3 other toggles below it, where the Add Facility modal is using just simple checkboxes for those elements.

**Comment by bradymiller** [comment]
Let me know if you need a Loom video for details. @im-Amitto has converted me into a [Loom](https://www.loom.com/) fanatic :)

**Comment by skshahnawaz** [comment]
I'm reviewing the codebase first. If any confusion arises, will let you know

**Comment by skshahnawaz** [comment]
Please review my PR
https://github.com/openemr/openemr/pull/3066

**Comment by skshahnawaz** [comment]
Please close this issue now since it has been already fixed @bradymiller

**Comment by im-Amitto** [comment]
Adding info for future reference.
Fixed in d5059f7954d5a1a425bd279d4d0db625b8fa6995 related to #3066 :smile: 
Note: `.DS_Store` has also been added to `.gitignore` along with the fix
