### ISSUE TITLE
Test table refine to use Bootstrap

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3070]
### Describe the bug

Test table still used legacy style and outdated syntax.

### To Reproduce

1. Go to the Administrator > Clinic 
2. Click the Calendar
3. Choose Test system
4. See the table.

![1](https://user-images.githubusercontent.com/22230889/75885679-e7adff00-5e61-11ea-87ea-1ea5ab8d4f78.png)

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

**Comment by stu01509** [comment]
Hi @bradymiller,

Please assign this issue for me.

**Comment by sjpadgett** [comment]
@stu01509 
I went ahead and gave to ya.
Also, thanks for all the excellent works you guys are doing. Makes a difference.

**Comment by im-Amitto** [comment]
@bradymiller @sjpadgett 
I'm not sure but i think this issue is simliar to #2949

**Comment by bradymiller** [comment]
#2949 will be more extensive since will involve migrating it outside smarty into it's own script (which can then be a building block to place other Diagnostics like stuff).
