### ISSUE TITLE
Make the Add Facility modal and Edit Facility modal consistent

### ISSUE THREAD

**Issue by skshahnawaz** [openemr/openemr#3075]
### Describe the bug

Make the Add Facility modal and Edit Facility modal responsive and consistent.

**Comment by skshahnawaz** [comment]
@bradymiller  Please assign this issue to me and suggest if any edits is/are needed or not

**Comment by bradymiller** [comment]
hi @skshahnawaz , it is yours :)

**Comment by skshahnawaz** [comment]
Thanks, I'll fix it soon. Working on it

**Comment by skshahnawaz** [comment]
@bradymiller please check
