### ISSUE TITLE
Remove jquery-ui from External Import gui

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3077]
### Describe the problem

jquery-ui is being removed from codebase

### Describe the solution you'd like

The External Import gui at Administration->Coding->'External Data Loads' has a gui based on jquery-ui. Need to remove the reliance of jquery-ui from this gui. Script is at interface/code_systems/dataloads_ajax.php

**Comment by stu01509** [comment]
Hi @bradymiller,

I want to work on this issue, Please assign me.
Thanks.

**Comment by im-Amitto** [comment]
@stu01509 Actually, i am working on this one but i have't done much changes so if you want to pick it, go with it.

**Comment by stu01509** [comment]
Hi @im-Amitto 

I didn't notice you are working on this issue, Sorry.

**Comment by im-Amitto** [comment]
@stu01509 I haven't done much changes to it so you can pick this one :smile: . Anyway i am planning to work on something else.

**Comment by bradymiller** [comment]
sounds like @stu01509 wins the award of getting to work on this issue :)

**Comment by stu01509** [comment]
Hi @bradymiller,

This jquery-UI modal, I will use the Bootstrap modal to replace it.
Is this a good idea?

![image](https://user-images.githubusercontent.com/22230889/76140484-d64d3880-6095-11ea-991f-18992850d459.png)

**Comment by bradymiller** [comment]
hi @stu01509 , For the modal, rec considering using the dlgopen() way of making a modal in OpenEMR; search the codebase for the multitude of ways that it is used.

**Comment by stu01509** [comment]
> hi @stu01509 , For the modal, rec considering using the dlgopen() way of making a modal in OpenEMR; search the codebase for the multitude of ways that it is used.

OK, Thanks for your tips, I will try to use dlgopen to making a modal.
