### ISSUE TITLE
Categories Details Button and Confirm form

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3081]
### Describe the bug

Categories Details button style.
Confirm form not used Bootstrap theme.

### To Reproduce

1. Go to the Administrator > Clinic
2. Click the Calendar
3. Choose Categories 
4. See the go button and click it.
5. See the confirm form.

![1](https://user-images.githubusercontent.com/22230889/75973343-f357ff00-5f0f-11ea-88f8-674f6c74c7c9.png)

![2](https://user-images.githubusercontent.com/22230889/75973347-f521c280-5f0f-11ea-9a44-6d1a5705ed49.png)

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system:  Windows 10

**Comment by stu01509** [comment]
Hi @bradymiller, @sjpadgett

Please assign this issue for me.

**Comment by bradymiller** [comment]
@stu01509 , it's yours :)
