### ISSUE TITLE
Replace Facility form alerts by Bootstrap Alerts

### ISSUE THREAD

**Issue by skshahnawaz** [openemr/openemr#3083]
### Describe the bug

In general popups interrupt the flow but JS alerts in a popup make it worse

Replace the normal js alerts by Bootstrap Alerts on Facilities forms

**Comment by skshahnawaz** [comment]
Please assign this issue to me @sjpadgett

**Comment by skshahnawaz** [comment]
@sjpadgett can you please provide with a Loom video of the current alerts?

**Comment by tywrenn** [comment]
@sjpadgett @skshahnawaz Any updates on this?

**Comment by skshahnawaz** [comment]
@tywrenn I was actually working on the Patient MAR one, so kept this on hold for a while. Will complete this soon

**Comment by tywrenn** [comment]
Bump
