### ISSUE TITLE
BS4 Fixes Needed

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3085]
### Describe the bug

After multiple revisions to the encounter tab, I believe there still are improvements that need to be addressed here. Also some BS4 code fixes are needed.

Current Issues Found:
- Encounter top isn't using BS4 colors (also it looks like it needs a little padding).
- Encounter top isn't sizing correctly and is showing a scrollbar on my end
- The encounter page has buttons that aren't sized correctly in it
- It seems like we need to add more colors to the encounter page as it is looking kinda bland
- There isn't any body padding in the encounter page for some reason
- BS4 fixes are needed from prior commits

I'll be fixing these in a pull request @bradymiller @sjpadgett please assign me.

**Comment by sjpadgett** [comment]
go for it tyler..

**Comment by tywrenn** [comment]
This issue is being expanded to do some code cleanup as well. Improvements are needed in the following areas:
- interface/super/manage_document_templates.php
- interface/billing/sl_receipts_report.php
- interface/reports/destroyed_drugs_report.php
- interface/drugs/add_edit_lot.php
- interface/forms_admin/forms_admin.php
- interface/patient_file/encounter/encounter_top.php
- interface/drugs/drug_inventory.php
