### ISSUE TITLE
Search icon dislocated from it's place (minor UI issue)

### ISSUE THREAD

**Issue by sraghuvanshi** [openemr/openemr#3091]
### Describe the bug

A very minor but considerable UI issue in the search bar. The search icon is a little dislocated from its place.

### To Reproduce
It is clearly noticeable on the top right corner of the UI.
![Screenshot from 2020-03-06 19-10-22](https://user-images.githubusercontent.com/48951339/76088713-819ab680-5fde-11ea-9813-b9d9e784bf4f.png)

### Expected behavior
The icon should be present at the right end the search bar.

### Client configuration

- Browser: Chrome
- Operating system: Ubuntu 18.04

### Would you like to work on the issue?
Yes, I would like to work on this.

**Comment by yashrajbothra** [comment]
Pretty Unsure why i cant see that in my system.
![image](https://user-images.githubusercontent.com/47683556/76092071-c88baa80-5fe4-11ea-859e-8c1e96375dfc.png)

Did you run all the scripts well ?

**Comment by sjpadgett** [comment]
Hi guys.
My PR fixed for FF but breaks on Chrome!! 
Take a look at PR #3086 as it prob has something to do with margin class or converting to rem in style class.
I never understood why that input needs to expand or has rounded corners. So, do what you want with it,.
Will assign to ya @sraghuvanshi and thanks.

**Comment by sraghuvanshi** [comment]
@sjpadgett Sure, sir, I'm working on it.

**Comment by im-Amitto** [comment]
@sjpadgett The search icon is not that big in size so i think we can place them like shown below, that way it will simplify the things and i don't think this type of placement will break in any browser.
![Screenshot from 2020-03-06 21-30-07](https://user-images.githubusercontent.com/29653282/76099829-b9f7c000-5ff1-11ea-8189-a245257cad78.png)

**Comment by sjpadgett** [comment]
That's fine but need to be sure that the button stays with the input on sm breakpoints. ie Don't want button separated/new line from input on small viewports...

Then again while we are doing this why not just make it a normal search, lose expand and give it a min-width.
Unless someone can give a good reason the darn thing needs to expand. Even on mobile,

**Comment by sjpadgett** [comment]
thanks for issue and fix.

**Comment by surendrap720** [comment]
I would like to confirm if this issue is fixed for chrome ? Because for me it is still showing the dislocated search bar.

**Comment by sraghuvanshi** [comment]
Hi @surendrap720 

Thank you for reporting the problem. I was assigned this issue and I've recently worked on it. According to the requirements of the UI, I've placed the search icon at the right end of the search bar. For complete info please see #3093 
> Because for me it is still showing the dislocated search bar.

Is it a dislocated search bar or search icon? it will be great if you could share your system configuration and screenshots.  
And, surely the UI can be improved as you've mentioned in #3140. 
Thanks

**Comment by surendrap720** [comment]
Hi Saksham,

Actually the icon is on the right side of the search bar. But it does not
look good. The borders of the icon is not aligned with the search bar.

**Comment by sraghuvanshi** [comment]
@surendrap720 Alright then, I think it's not an issue but an improvement. UI improvements are always welcome, you can proceed with that. 
Thanks
