### ISSUE TITLE
Eye exam creates problem for other innocent forms

### ISSUE THREAD

**Issue by im-Amitto** [openemr/openemr#3092]
### Describe the bug
All functionalities on encounter summary page will stop working if you add an eye exam form.

Most probably the dialog.js is being included twice in the same page. 
I did a little debug and `interface/forms/eye_mag/report.php:255` `SetupHeader()` is responsible of the behaviour.

### To Reproduce
1. Add a eye exam report on patient encounter

![Screenshot from 2020-03-06 21-21-30](https://user-images.githubusercontent.com/29653282/76099025-7fd9ee80-5ff0-11ea-83d3-6631ae96ccc9.png)

### Client configuration

- Browser: Linux
- Operating system: Chrome

tag: `Good first issue`

**Comment by sjpadgett** [comment]
Hint: Header::setupHeader(['no_dialog'])
Also, wouldn't hurt to wrapper function dlgopen() with conditional to test if function is already in scope.

**Comment by yashrajbothra** [comment]
I also saw this one and was just about to open the issue. I would like to work on it if you are not working on this one.😀

**Comment by sjpadgett** [comment]
@yashrajbothra Yours my friend.
