### ISSUE TITLE
Remove tab not Working

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3095]
### Describe the bug

When remove tab button is pressed it throws error

### To Reproduce

1. Hover on  'Fees'
2. Click on 'Payment'
3. DO step-1 -> Click on 'Fees Sheet'
4. Click on 'Remove Tab'
5. See error

![image](https://user-images.githubusercontent.com/47683556/76117336-a3616100-6011-11ea-8464-573fcd1a5041.png)

### Expected behavior

IMO there should not be any button like 'Remove Tab' instead there can be 'X' like we have normally.
![image](https://user-images.githubusercontent.com/47683556/76117249-77de7680-6011-11ea-848e-bc85e2d949c9.png)

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

### Additional Context 
I would like to fix this bug 🐛

**Comment by sjpadgett** [comment]
Somebody just worked on this form I think. Anyway it's yours.

**Comment by im-Amitto** [comment]
@yashrajbothra 

File `/home/heisenbrerg/Documents/openemr/src/Tabs/TabsWrapper.php:202`
```diff
-          $s .= "<li class='tabs-tabs' ><a data-toggle='tab' class='tabs-anchor active' href='#{$this->tabsid}-$i'>" . text($val['title']) . "</a>";
+          $s .= "<li class='tabs-tabs' ><a data-toggle='tab' class='tabs-anchor active' href='#{$this->tabsid}-$i'>" . text($val['title']);
            if ($val['closeable']) {
-               $s .= " <span class='icon icon-close' role='presentation'>" . xlt('Remove Tab') . "</span>";
+               $s .= " <span aria-label='close' class='icon-close' role='close'>X</span>";
            }
-           $s .= "</li>\n";
+           $s .= "</a></li>\n";
        }
```

**Comment by im-Amitto** [comment]
I fixed it day before yesterday and then forgot about o create a PR/ssue :laughing:

**Comment by sjpadgett** [comment]
@im-Amitto umm, that's no excuse! :)

**Comment by im-Amitto** [comment]
@sjpadgett I will work with more active mind from now.
Thanks @yashrajbothra  :)
