### ISSUE TITLE
Incorrect Heading

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3097]
### Describe the bug

Incorrect heading should be Add mode instead edit

### To Reproduce
![image](https://user-images.githubusercontent.com/47683556/76123672-263ce880-601f-11ea-94d1-1cbd0f0a0149.png)

1. Hove on  'Procedures'
2. Click on 'Configuration'
3. Click on 'Add Top Level'

### Expected behavior

![image](https://user-images.githubusercontent.com/47683556/76123857-85026200-601f-11ea-99b3-dc623e69692c.png)

### Client configuration

- Browser: Chrome
- Operating system: Win 10

### Additional Context 
I would like to open a Quick Fix 😉

**Comment by sjpadgett** [comment]
Sure..
