### ISSUE TITLE
Refine Forms Administration table

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3099]
### Describe the bug

Forms Administration used legacy style and outdated syntax.

### To Reproduce

1. Choose Administrator > Forms 
2. Click Forms Administration
3. See the table

![Untitled](https://user-images.githubusercontent.com/22230889/76136150-6d4fcb80-6069-11ea-88f2-e5ebb56433d4.png)

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

**Comment by bradymiller** [comment]
I'm not going to miss that gui :)

**Comment by im-Amitto** [comment]
Finally someone who see that GUI as an issue :wink:

**Comment by stu01509** [comment]
I think after during this summer,
The OpenEMR UI will be very Beautiful XDD

**Comment by stu01509** [comment]
Hi @bradymiller,

Please assign this issue to me.

**Comment by im-Amitto** [comment]
With that speed of yours we wont be needing the entire summer ✌️.

**Comment by bradymiller** [comment]
hi @stu01509 , it is yours :)
