### ISSUE TITLE
PHP8 Planning

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3102]
The issue will be to track planning for PHP8. Here is the most up to date place with the PHP8 Upgrading doc comes from:
https://github.com/php/php-src/blob/master/UPGRADING

**Comment by bradymiller** [comment]
Oh goodness, get ready for log craziness:
https://github.com/php/php-src/blob/master/UPGRADING#L111
(this issue is what fills up the log when notices are on; now it will be a warning!!)

**Comment by bradymiller** [comment]
Made an issue to start the long road of removing php notices:
https://github.com/openemr/openemr/issues/3118

**Comment by adunsulag** [comment]
We support php8 now, can close this issue.
