### ISSUE TITLE
Refine install code set table form

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3104]
### Describe the bug

Install code set table form used legacy style and outdated syntax.

### To Reproduce

1. Choose the Administrator > Coding
2. Click Native Data Loads
3. See the table form

![image](https://user-images.githubusercontent.com/22230889/76145667-88045d80-60c6-11ea-856d-56672d300b7b.png)

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

**Comment by stu01509** [comment]
Hi @bradymiller sir

Please assign this issue to me, Thanks.

**Comment by sjpadgett** [comment]
Thank you.
