### ISSUE TITLE
UI: Add Facility popup button size and positions

### ISSUE THREAD

**Issue by thesmallstar** [openemr/openemr#3105]
The Size can be reduced, and position should be at the bottom.
![image](https://user-images.githubusercontent.com/42006277/76147686-03fda600-60c5-11ea-8f79-1030a0bca2fb.png)

Can I work on this?

**Comment by bradymiller** [comment]
hi @thesmallstar , It's yours :)
Also suggest that should make the Edit Facility modal consistent with the changes.

I'm not sure why for some forms we have buttons at the top and some at the bottom.
@tywrenn , should we be choosing one or the other in the future for consistency?

**Comment by sjpadgett** [comment]
> should we be choosing one or the other

This is going to depend on the form imo. Sometimes it is easier for them to be at top. My preference is long forms has both.
