### ISSUE TITLE
UI: Document template page missing BS

### ISSUE THREAD

**Issue by thesmallstar** [openemr/openemr#3106]
BS tags are missing on the document template page.
![image](https://user-images.githubusercontent.com/42006277/76147741-62c31f80-60c5-11ea-837e-58bc4749e132.png)

Can I work on this?

**Comment by bradymiller** [comment]
hi @thesmallstar , It's yours :)

**Comment by stu01509** [comment]
Hi @thesmallstar 

Are you still working on this issue?

**Comment by thesmallstar** [comment]
@stu01509 yes, I had been bust with college things, will get back to work tomorrow :) Sorry for the delay
