### ISSUE TITLE
UI: Missing styles in Multi language tool

### ISSUE THREAD

**Issue by thesmallstar** [openemr/openemr#3107]
All tabs have missing style:
![image](https://user-images.githubusercontent.com/42006277/76147842-5e4b3680-60c6-11ea-8d70-702afa8cb623.png)

Can I work on this?

**Comment by bradymiller** [comment]
hi @thesmallstar , It's yours :)

**Comment by stu01509** [comment]
Hi @thesmallstar 

Are you still working on this issue? If not
@bradymiller Please assign this issue to me.

**Comment by thesmallstar** [comment]
@stu01509 please go ahead, I am having some health issues, cannot work rn. 

It is yours.

**Comment by bradymiller** [comment]
hi, assigned @stu01509 
@thesmallstar , sorry to hear about health issues. Health is priority here, so please focus on your health and get better soon

**Comment by stu01509** [comment]
> @stu01509 please go ahead, I am having some health issues, cannot work rn.
> 
> It is yours.

Take care, bro.
