### ISSUE TITLE
Tab Layout Compact theme issues with menu hovering with the legacy themes

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#311]
This appears to be secondary to the fonts being used (and the size is thus smaller making a gap between the menu and the sub-menus). This will be an easy fix and will involve likely standardizing the fonts among all the legacy themes(or perhaps using em rather than px for the font size will also fix this).

**Comment by ophthal** [comment]
I have a simple fix that works on Windows machines.  I did not find this problem on Mac.  On the Windows machine the bug drove me nuts.  Here is the simple fix in tabs_compact_style.css
Change .menuLabel
{
...
from -->    padding: 5px 12px 3px;
to     -->    padding: 5px 12px 5px;
...
}
Seems to correct the "jumpy" menu problem across different General Themes.
https://github.com/ophthal/openemr_2/tree/compact_fixes

This fix also makes the tabs for the main iframe a little more spacious without distracting from the middle patient segment above it, allowing the drop-shadows to display nicely.

**Comment by bradymiller** [comment]
@ophthal ,
Thanks for this fix.
Works well on linux also. Just brought this fix into the codebase:
https://github.com/openemr/openemr/commit/2ffdaa3a0252b29172f7acf45a3fedfdcf592471
