### ISSUE TITLE
Drug Inventory UI

### ISSUE THREAD

**Issue by im-Amitto** [openemr/openemr#3113]
### Describe the bug

write concise description of what the bug is.
![Screenshot from 2020-03-08 03-32-16](https://user-images.githubusercontent.com/29653282/76153115-8f8b2d00-60ed-11ea-8aea-5bb9a752a317.png)

### Client configuration

- Browser: Chrome
- Operating system: Linux Ubuntu 18.04

**Tags:** `good first issue`, `UI`

**Comment by im-Amitto** [comment]
@bradymiller I was't planning of picking this up but i guess gonna do it now :smile:

**Comment by bradymiller** [comment]
lol, saw the blank drug names and assumed it was related to the PR

**Comment by bradymiller** [comment]
@im-Amitto , just let me know if you want me to unassign you since you got lots of other stuff going on.

**Comment by im-Amitto** [comment]
It's just a table so will not take much effort :).
