### ISSUE TITLE
On tab layout Full theme, the tabs vertical size causes some scrolling of the tabs themselves

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#312]
This is pretty odd and creates a blue border at bottom of tab because of it. Looks like it is only a couple pixels too large vertically. Guessing the fix will be easy.

**Comment by robertdown** [comment]
That blue border is intentional, with the active tab dropping down  a pixel to make it look connected. Will investivate

________________________________

**Comment by bradymiller** [comment]
This is a tough one. The source of this bug is here:
https://github.com/openemr/openemr/blob/master/interface/themes/tabs_style_full.css#L105

Note this setting is needed however to nicely show numerous tabs. The compact tabs style does not have this issue, so appears will need to mimick that styling (to remove the line on the active tab) to fix this issue.

**Comment by bradymiller** [comment]
Placed a PR to fix this here:
https://github.com/openemr/openemr/pull/407

**Comment by bradymiller** [comment]
Above fix tested well, so brought it into the codebase.
