### ISSUE TITLE
UI issues in some areas

### ISSUE THREAD

**Issue by adad20** [openemr/openemr#3122]
### Describe the bug
Text color is not fit as per the background which make the alert difficult to read.
write concise description of what the bug is.

### To Reproduce
While logging in type wrong password.
While creating new payment.

### Actual behavior
![Screenshot (79)](https://user-images.githubusercontent.com/55142272/76165055-d6266900-6179-11ea-8f98-65767b8fa148.png)

![Screenshot (80)](https://user-images.githubusercontent.com/55142272/76165057-de7ea400-6179-11ea-984e-12cafbf44d07.png)

### Expected behavior

![Screenshot (81)](https://user-images.githubusercontent.com/55142272/76165046-c6a72000-6179-11ea-9386-36089041bea3.png)

**Comment by im-Amitto** [comment]
Please don't ignore the client configuration part, at least the browser part. Also, login page seems to be browser specific issue.

**Comment by bradymiller** [comment]
hi @adad20 , Good point. Part of converting to bs4 is fixing color clashing; @tywrenn did a lot of this during the prior bs4 conversion, but there's still lots left to do :)

**Comment by adad20** [comment]
hi @bradymiller please assign me in this I will work on it.
And also for issue #3001 there was some issue in my PR I will open the new one.

**Comment by bradymiller** [comment]
hi @adad20 , it's yours :)

**Comment by adad20** [comment]
@bradymiller I think this issue is in some theme only, I recently changed the theme and everything is fine now.
Should I add default values so it may work in all themes such as `alert-danger` will always have `text-light` class?
