### ISSUE TITLE
UI Issue Report - Cash Receipts by Provider

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3129]
### Describe the bug

UI Issue Report Cash Receipts by Provider form field alignment.

### To Reproduce

1. Choose Report > Financial
2. Click Cash Rec
3. See the form field

![image](https://user-images.githubusercontent.com/22230889/76205075-7e990380-6234-11ea-9137-94f7f75a7930.png)

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

**Comment by stu01509** [comment]
Hi @bradymiller, @sjpadgett 

Please assign this issue to me.

**Comment by bradymiller** [comment]
hi @stu01509 , it's yours :)
