### ISSUE TITLE
Procedures Load Compendium lost title

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3130]
### Describe the bug

Procedures Load Compendium lost the title.

### To Reproduce

1. Choose the procedures 
2. Click Load Compendium

![image](https://user-images.githubusercontent.com/22230889/76205904-1519f480-6236-11ea-82c0-dbe823555256.png)

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

**Comment by yashrajbothra** [comment]
> 2. Click Lab Documents

Are you sure or it should `Load Compendium`

**Comment by stu01509** [comment]
> > 1. Click Lab Documents
> 
> Are you sure about it? I think its `Load Compendium`

Thanks for your noticed :)

**Comment by stu01509** [comment]
Hi @bradymiller, @sjpadgett 

Please assign this issue to me.

**Comment by im-Amitto** [comment]
Everyone is quite active :)

**Comment by bradymiller** [comment]
hi @stu01509 , done :)
