### ISSUE TITLE
Multiple Fee Sheet tabs for encounter 

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#3135]
### Problem
Selecting Fees -> Fee Sheet multiple times opens multiple tabs of Fee Sheet in encounter tab.

### Expected behavior
Unlike other `forms`, an encounter should have one and only one fee sheet tab open at any given time.  Options:
1. `Fee Sheet` selection should be disabled/hidden if the tab is already open.
OR
2. Subsequent clicks on `Fee Sheet` should result in focus on active `Fee Sheet` tab.  If that is difficult, an warning message (not an alert) will help users.

**Comment by im-Amitto** [comment]
@mdsupport if no-one wants to work on this, I can happily pick this one.

**Comment by mdsupport** [comment]
My preference would be for you to concentrate on app development thru to some state of community testing.  Since no one has complained about this issue for years, I would think it is not a high priority.  But project managers set the priorities.

**Comment by bradymiller** [comment]
This issue arose when the tabs were added to the encounter gui and has been mentioned previously:
https://github.com/openemr/openemr/issues/1511
https://github.com/openemr/openemr/issues/1804
https://github.com/openemr/openemr/issues/1311

So fixing this issue will get rid of a record 4 issues! :)
Note that the https://github.com/openemr/openemr/issues/1311 has most recent discussion on this along with another form (Miscellaneous Billing Option form) that should only be limited to one form per encounter. @thesmallstar was working on that, but guessing he'll be happy to have somebody else take a stab at it. If so, then go for it @im-Amitto :)

**Comment by bradymiller** [comment]
By the way, I vote for option 2 above:
Subsequent clicks on Fee Sheet should result in focus on active Fee Sheet tab.

**Comment by adad20** [comment]
hi @mdsupport In my case fee sheet option is disabled not able to reproduce this bug.

**Comment by stephenwaite** [comment]
hi @adad20 , you're not seeing something like this from https://seven.openemr.io/a/openemr/index.php?
![Screenshot from 2020-03-29 13-36-47](https://user-images.githubusercontent.com/5618372/77856020-66c4f780-71c2-11ea-976f-a53b323c5391.png)

**Comment by adad20** [comment]
hi @stephenwaite thank you successfully reproduced the bug. If @thesmallstar is not working I will happily take this.

**Comment by im-Amitto** [comment]
@adad20 I don't remember it well but I guess you can find the solution in `tabs_view_model.js`. it should have a function `menuActionClick`/`menuClickAction` which is responsible for adding frames(fees sheet etc.) to the encounter tab. you can add a check to it, so multiple tabs can't be spawned and use the same to disable the click on the desired option.
Sorry for not pinpointing it as I don't have my laptop and it's quite hard to do that on mobile.

**Comment by adad20** [comment]
hi @im-Amitto thanks it helped me a lot :)

**Comment by adad20** [comment]
hi @mdsupport Is this to be implemented only for `fee-sheet`

**Comment by mdsupport** [comment]
@stephenwaite, @bradymiller :  More I think about it, fee sheet is really another section of encounter summary. It could be "included" in an div if authorized - specially since that is the only place billing relevant issues are shown.
@adad20: I think fee sheet is already treated separately in the logic.  So it makes sense to apply change only to fee sheet.  For all other forms there are legit circumstances when multiple instances may be needed.
