### ISSUE TITLE
Latest Build Has Title Bar Styling issues

### ISSUE THREAD

**Issue by kchapple** [openemr/openemr#3137]
### Describe the bug

On my latest build (I could have missed something) there are some styling issues on the header. The SVG for the logo appears in Inspector to have a 287px by 287px height and width. 

### To Reproduce
Install OpenEMR master from source, build composer and npm.

![Screen Shot 2020-03-10 at 1 33 10 PM](https://user-images.githubusercontent.com/271809/76342233-a3dd4e80-62d4-11ea-902e-917243530ce1.png)

1. Log in and see above issue

### Expected behavior

Logo should be in top left corner
Search button/icon should be totally to the right of search input box

### Client configuration

- Browser: Appears on Firefox and Chrome
- Operating system: MacOS 10.12

**Comment by bradymiller** [comment]
Ensure you clear cache (if 5.0.2 and dev are used in same browser without clear cache, some weird things can happen)
Are you seeing same thing on the online dev demos:
https://www.open-emr.org/wiki/index.php/Development_Demo#Daily_Build_Development_Demos

**Comment by sjpadgett** [comment]
any search has been fixed. maybe need to npm run build.

**Comment by kchapple** [comment]
I swear I did, but just did it again and the issue disappearance. I think @bradymiller explanation makes sense. I'm running a bunch of different versions.

Thanks, can close this.
