### ISSUE TITLE
dated reminders

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#3139]
### Suggestion
All timer based background executions from Main frame should be consolidated into background services that can be managed from single screen.

Ideally dated reminders can be isolated into an optional module and managed from modules configuration.

**Comment by bradymiller** [comment]
Something to consider here:
Background Services was built as a poor man method for cron (ie. allows users to run background php scripts/methods without needing to set up cron; ie. just needs a user to be logged in), so not really meant for front-end integration like the reminders stuff. That being said, integration/consolidation is usually a good thing.

**Comment by mdsupport** [comment]
Two types of background candidates - scheduled/periodic and on demand.  A good use case for later would be cdr that should run as cron for all patients but spawn check for current patient in background without causing 20 second spinner that frustrates the users.  If someone is happy to wait or certification requires it, allow for background check option to be disabled.
