### ISSUE TITLE
Reloading Tabs

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3142]
### Describe the problem

When we Select a tab which is already open it should not reload 

### Describe the solution you'd like
https://www.loom.com/share/5474b42b98584b29959d7b6a148c29e4

I was expecting something like this 🤔 

Maybe my expectations are lil high

**Comment by stu01509** [comment]
Hi @yashrajbothra 

Are you sure about it?
I think the video didn't contain any issues about OpenEMR.

**Comment by yashrajbothra** [comment]
> Hi @yashrajbothra
> 
> Are you sure about it?
> I think the video didn't contain any issues about OpenEMR.

Video is just an exmple for explanation
Its Feature request if we can have this on board.

**Comment by yashrajbothra** [comment]
Hii @bradymiller Sir, Is it a good feature to have on OpenEMR ?

**Comment by bradymiller** [comment]
hi @yashrajbothra ,
High expectations are generally always a good thing. Is the goal to make OpenEMR's tabs like the one in the video? (something to note is I don't think the tabs reload on click in OpenEMR, unless click the reload indication on the tab)

**Comment by yashrajbothra** [comment]
Yea, Somewhat like that if we can implement then i think it will be nice.
https://www.loom.com/share/8e46941d03fc4a7898aa190d2c34aeb5

If you can see there is another problem if the link is clicked that is already open then it delays in shifting its focus which is not so good User Exp. Both could be fixed by same PR.

I think the idea could be like if clicked menu_url matches with any open tab_url then it should not load again and shift focus immediately.

**Comment by bradymiller** [comment]
hi @yashrajbothra , that sounds very reasonable.
