### ISSUE TITLE
OpenEMR pages not working after I pull in latest code in docker install

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr#3143]
### Describe the bug

Hello, I pulled the latest code for OpenEMR on my docker install and the web pages have been broken ever since 

![Broken](https://user-images.githubusercontent.com/22311928/76421759-71028b80-63a4-11ea-942c-5b0fa8ee2df8.png)

After I do

`docker-compose down -v`

and then 

`docker-compose up`

the web pages start working as normal, but get broken again when I Pull in latest changes
what do I do to fix this, Here is what my error log looks like 

`bash-5.0# tail -f /var/log/apache2/error.log
[Wed Mar 11 13:01:24.859510 2020] [php7:warn] [pid 40] [client 172.21.0.1:55706] PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/openemr/interface/globals.php on line 232, referer: http://localhost:8300/interface/main/tabs/timeout_iframe.php
[Wed Mar 11 13:01:24.859551 2020] [php7:error] [pid 40] [client 172.21.0.1:55706] PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/vendor/autoload.php' (include_path='.:/usr/share/php7') in /var/www/localhost/htdocs/openemr/interface/globals.php on line 232, referer: http://localhost:8300/interface/main/tabs/timeout_iframe.php
[Wed Mar 11 13:01:28.857235 2020] [php7:warn] [pid 23] [client 172.21.0.1:55716] PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/openemr/interface/globals.php on line 232, referer: http://localhost:8300/interface/main/messages/messages.php?form_active=1
[Wed Mar 11 13:01:28.857285 2020] [php7:error] [pid 23] [client 172.21.0.1:55716] PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/vendor/autoload.php' (include_path='.:/usr/share/php7') in /var/www/localhost/htdocs/openemr/interface/globals.php on line 232, referer: http://localhost:8300/interface/main/messages/messages.php?form_active=1
[Wed Mar 11 13:02:15.718000 2020] [php7:warn] [pid 32] [client 172.21.0.1:55728] PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/openemr/interface/globals.php on line 232
[Wed Mar 11 13:02:15.718033 2020] [php7:error] [pid 32] [client 172.21.0.1:55728] PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/vendor/autoload.php' (include_path='.:/usr/share/php7') in /var/www/localhost/htdocs/openemr/interface/globals.php on line 232
[Wed Mar 11 13:02:16.514019 2020] [php7:warn] [pid 35] [client 172.21.0.1:55726] PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/openemr/interface/globals.php on line 232
[Wed Mar 11 13:02:16.514090 2020] [php7:error] [pid 35] [client 172.21.0.1:55726] PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/vendor/autoload.php' (include_path='.:/usr/share/php7') in /var/www/localhost/htdocs/openemr/interface/globals.php on line 232
[Wed Mar 11 13:02:24.453259 2020] [php7:warn] [pid 36] [client 172.21.0.1:55736] PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/openemr/setup.php on line 97, referer: http://localhost:8300/setup.php
[Wed Mar 11 13:02:24.453315 2020] [php7:error] [pid 36] [client 172.21.0.1:55736] PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/vendor/autoload.php' (include_path='.:/usr/share/php7') in /var/www/localhost/htdocs/openemr/setup.php on line 97, referer: http://localhost:8300/setup.php
[Wed Mar 11 13:22:45.737040 2020] [php7:warn] [pid 26] [client 172.21.0.1:56002] PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/openemr/interface/globals.php on line 232, referer: http://localhost:8300/interface/login/login.php?site=default
[Wed Mar 11 13:22:45.737085 2020] [php7:error] [pid 26] [client 172.21.0.1:56002] PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/vendor/autoload.php' (include_path='.:/usr/share/php7') in /var/www/localhost/htdocs/openemr/interface/globals.php on line 232, referer: http://localhost:8300/interface/login/login.php?site=default
[Wed Mar 11 13:23:48.301360 2020] [php7:warn] [pid 32] [client 172.21.0.1:56052] PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/localhost/htdocs/openemr/setup.php on line 97, referer: http://localhost:8300/setup.php
[Wed Mar 11 13:23:48.301419 2020] [php7:error] [pid 32] [client 172.21.0.1:56052] PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/vendor/autoload.php' (include_path='.:/usr/share/php7') in /var/www/localhost/htdocs/openemr/setup.php on line 97, referer: http://localhost:8300/setup.php
`

**Comment by prondubuisi** [comment]
Edit, the pages are back after I did the following 

```
composer update

npm install

npm run build

composer dump-autoload -o
```

But the UI looks out of place is anybody having the same UI problem? Screenshot below

![UI issue](https://user-images.githubusercontent.com/22311928/76424713-e53f2e00-63a8-11ea-99b1-be272c3798e3.png)

**Comment by stu01509** [comment]
Hi @prondubuisi 

I also use a docker But didn't happen this problem.

**Comment by prondubuisi** [comment]
> Hi @prondubuisi
> 
> I also use a docker But didn't happen this problem.

Thanks @stu01509 I think its from my install. I will check it out thanks

**Comment by prondubuisi** [comment]
@stu01509 What Operating System are you running on?

**Comment by stephenwaite** [comment]
hi @prondubuisi , how about

1. docker-compose down -v
2. docker volume prune
3. docker pull openemr/openemr:flex
4. docker-compose up -d

**Comment by prondubuisi** [comment]
Okay. Will try that out thanks!

**Comment by stu01509** [comment]
> @stu01509 What Operating System are you running on?

I am running xampp on windows and docker on Linux, they are didn't happen this problem.

**Comment by bradymiller** [comment]
hi @prondubuisi ,

The easy development docker uses docker black magic to allow testing and development from the same place (ie. directly in your repository). From outside the docker, you and the repo will not be able to see any of the build or testing artifacts inside the docker. Because of this, though, you shouldn't run the build commands outside the docker. You need to run them inside the docker. After doing steps 1-3 above in @stephenwaite 's above post, you'll need to clean up your repository by:
1. remove the vendor directory
2. remove the node_modules directory
3. run the following git command to remove the other stuff that shouldn't be there:
git clean -dfX
4. make sure you see nothing with the following command:
git ls-files . --ignored --exclude-standard --others

**Comment by prondubuisi** [comment]
Hello @stephenwaite @bradymiller I followed the above instructions and my OpenEMR UI still looks cluttered like above, is there any other thing I can do?
Here is what my error log looks like

```
prondubuisi@prondubuisi:~/gitrepos/openemr$ docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'cat /var/log/apache2/error.log'
[Thu Mar 12 05:02:18.007280 2020] [ssl:warn] [pid 448] AH01906: 172.21.0.4:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Mar 12 05:02:18.007322 2020] [ssl:warn] [pid 448] AH01909: 172.21.0.4:443:0 server certificate does NOT include an ID which matches the server name
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.21.0.4. Set the 'ServerName' directive globally to suppress this message
[Thu Mar 12 05:02:18.062541 2020] [ssl:warn] [pid 448] AH01906: 172.21.0.4:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Mar 12 05:02:18.062563 2020] [ssl:warn] [pid 448] AH01909: 172.21.0.4:443:0 server certificate does NOT include an ID which matches the server name
[Thu Mar 12 05:02:18.065269 2020] [mpm_prefork:notice] [pid 448] AH00163: Apache/2.4.41 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Thu Mar 12 05:02:18.065300 2020] [core:notice] [pid 448] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu Mar 12 05:16:04.192913 2020] [ssl:warn] [pid 18] AH01906: 172.21.0.4:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Mar 12 05:16:04.193210 2020] [ssl:warn] [pid 18] AH01909: 172.21.0.4:443:0 server certificate does NOT include an ID which matches the server name
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.21.0.4. Set the 'ServerName' directive globally to suppress this message
[Thu Mar 12 05:16:04.210462 2020] [ssl:warn] [pid 18] AH01906: 172.21.0.4:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Mar 12 05:16:04.210484 2020] [ssl:warn] [pid 18] AH01909: 172.21.0.4:443:0 server certificate does NOT include an ID which matches the server name
[Thu Mar 12 05:16:04.210637 2020] [core:warn] [pid 18] AH00098: pid file /run/apache2/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Mar 12 05:16:04.213379 2020] [mpm_prefork:notice] [pid 18] AH00163: Apache/2.4.41 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Thu Mar 12 05:16:04.213419 2020] [core:notice] [pid 18] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu Mar 12 05:38:26.884877 2020] [ssl:warn] [pid 18] AH01906: 172.21.0.4:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Mar 12 05:38:26.920889 2020] [ssl:warn] [pid 18] AH01909: 172.21.0.4:443:0 server certificate does NOT include an ID which matches the server name
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.21.0.4. Set the 'ServerName' directive globally to suppress this message
[Thu Mar 12 05:38:27.809712 2020] [ssl:warn] [pid 18] AH01906: 172.21.0.4:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Mar 12 05:38:27.809758 2020] [ssl:warn] [pid 18] AH01909: 172.21.0.4:443:0 server certificate does NOT include an ID which matches the server name
[Thu Mar 12 05:38:27.810088 2020] [core:warn] [pid 18] AH00098: pid file /run/apache2/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Mar 12 05:38:27.813051 2020] [mpm_prefork:notice] [pid 18] AH00163: Apache/2.4.41 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Thu Mar 12 05:38:27.813079 2020] [core:notice] [pid 18] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu Mar 12 06:48:13.968682 2020] [ssl:warn] [pid 18] AH01906: 172.21.0.4:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Mar 12 06:48:13.969125 2020] [ssl:warn] [pid 18] AH01909: 172.21.0.4:443:0 server certificate does NOT include an ID which matches the server name
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.21.0.4. Set the 'ServerName' directive globally to suppress this message
[Thu Mar 12 06:48:14.062549 2020] [ssl:warn] [pid 18] AH01906: 172.21.0.4:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Mar 12 06:48:14.062565 2020] [ssl:warn] [pid 18] AH01909: 172.21.0.4:443:0 server certificate does NOT include an ID which matches the server name
[Thu Mar 12 06:48:14.062683 2020] [core:warn] [pid 18] AH00098: pid file /run/apache2/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Mar 12 06:48:14.064852 2020] [mpm_prefork:notice] [pid 18] AH00163: Apache/2.4.41 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Thu Mar 12 06:48:14.064887 2020] [core:notice] [pid 18] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

```

**Comment by stephenwaite** [comment]
> composer update
npm install
npm run build
composer dump-autoload -o

hi @prondubuisi , saw this above, the `docker-compose update -d` takes care of this for you so all you need to do is follow Brady's advice above to rebuild

**Comment by prondubuisi** [comment]
Hello @stephenwaite @bradymiller, Everything has been fine all this while, it turns out my browser cache has been messing with me. I don't even know how to react this, lol. Thanks for the help. I am closing this now.
