### ISSUE TITLE
Add how to View error logs as part of OpenEMR Docker documentation

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr#3144]
### Describe the problem

The OpenEMR [contribution guide](https://github.com/openemr/openemr/blob/master/CONTRIBUTING.md) does not have a section on how to view error logs with a docker install, I think this will be a necessary addition as developers will see themselves in situations where they have to check the logs, I was able to get a solution for seeing the logs here https://community.open-emr.org/t/docker-php-error-logs/11764/8

### Describe the solution you'd like

Would be happy to add the docker commands to see the PHP logs to the contribution guide if it is okay

**Comment by bradymiller** [comment]
hi @prondubuisi ,
Go for it, and this line would be even better:
```
docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'cat /var/log/apache2/error.log'
```

**Comment by yashrajbothra** [comment]
Can anyone tell me how can i edit php.ini from docker ?

**Comment by stephenwaite** [comment]
hi @yashrajbothra , you've got to exec into the docker and use vi
something like
```
docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") /bin/sh
vi /etc/php7/php.ini
