### ISSUE TITLE
UI Issue: Patient Finder previous and next button

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3147]
### Describe the bug

Patient Finder previous and next button style.

### To Reproduce

1. Choose the Patient/Client
2. Click Patient
3. See the previous and next button

![image](https://user-images.githubusercontent.com/22230889/76471171-ec0f8480-642c-11ea-828b-9806dddfd9b9.png)

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

**Comment by stu01509** [comment]
Hi @bradymiller 

Please assign this issue to me, Thanks.

**Comment by bradymiller** [comment]
it's yours :)
