### ISSUE TITLE
Add Database login credentials to Contributing.md

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr#3159]
### Describe the problem

I tried logging into OpenEMR development database, and I realized the database login credentials were not specified in the contributing guide. But I did find the credentials after greping for password in the [.travis.yml](https://github.com/openemr/openemr/blob/master/.travis.yml#L118) file

### Describe the solution you'd like

Write concise description of what feature you want
Add login credential to the part of contributing.md where DB login address is specified

**Comment by bradymiller** [comment]
hi @prondubuisi ,

These are set here in the docker-composer.yml:
https://github.com/openemr/openemr/blob/master/docker-compose.yml#L43-L44

Agree would be good idea to show them in step 6 of CONTRIBUTING.md

**Comment by sachinmukherjee** [comment]
@bradymiller Can I work on this?

**Comment by bradymiller** [comment]
hi @sachinmukherjee. it is yours :)

**Comment by prondubuisi** [comment]
Hello @sachinmukherjee  If you are super busy at the moment, then we can tag this as beginner friendly , or first timers only. We can then get willing first timers from our Slack or Telegram chat to work on it. cc @bradymiller

**Comment by sachinmukherjee** [comment]
Yes go ahead. I have another issue(https://github.com/openemr/openemr/issues/2889) to work on.

**Comment by ShubhamBansal1997** [comment]
@prondubuisi  @bradymiller Shall I pick this one?

**Comment by prondubuisi** [comment]
> @prondubuisi @bradymiller Shall I pick this one?

Yes please! Go for it

**Comment by stephenwaite** [comment]
just assigned you @ShubhamBansal1997 , thank you

**Comment by ShubhamBansal1997** [comment]
Raised the PR https://github.com/openemr/openemr/pull/3235 @stephenwaite @prondubuisi Next Steps?

**Comment by prondubuisi** [comment]
> Raised the PR #3235 @stephenwaite @prondubuisi Next Steps?

Approved already! You can pick any other issues you want to work on thanks.

**Comment by ShubhamBansal1997** [comment]
Let's catch up over slack, have few doubts over a issue @prondubuisi
