### ISSUE TITLE
UI Issue: EOB Posting - Search expand button

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3164]
### Describe the bug

EOB Posting - Search expand button lost cursor pointer

### To Reproduce

1. Choose Fees > Posting Payment.
2. See the expand button

![image](https://user-images.githubusercontent.com/22230889/76702654-5747a800-6706-11ea-93f2-6798e20f8ed2.png)

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

**Comment by stu01509** [comment]
Please assign this issue to me.

**Comment by stephenwaite** [comment]
sure, thanks @stu01509
