### ISSUE TITLE
eob invoice needs bs4 updates

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3166]
### Describe the bug

eob invoice isn't behaving

### To Reproduce
go to past encounters for a patient and click billing view and then click on the green code link
![Screenshot from 2020-03-15 11-38-47](https://user-images.githubusercontent.com/5618372/76704761-9697d980-66b1-11ea-85aa-7ffa009c599c.png)
and you'll view 
![Screenshot from 2020-03-15 11-26-47](https://user-images.githubusercontent.com/5618372/76704770-9ef01480-66b1-11ea-9e31-a482a2ecd4c5.png)

### Expected behavior

should be able to work the form as expected

### Client configuration

- Browser:
- Operating system:

**Comment by stu01509** [comment]
Please assign this issues to me.

**Comment by stephenwaite** [comment]
really? cool @stu01509 !

**Comment by stu01509** [comment]
Hi @stephenwaite 

I am working on this issue, But I have a question, 
How should I do add Code field, My code field is empty now.

![image](https://user-images.githubusercontent.com/22230889/76855229-ab2fc980-688b-11ea-8ec8-3608728e9abf.png)

**Comment by yashrajbothra** [comment]
https://www.open-emr.org/wiki/index.php/New_Encounters_%26_Coding_4.1

this should clear your problem :)

**Comment by stu01509** [comment]
Hi @yashrajbothra 

Thanks for your information, I will try to follow the documentation step.
