### ISSUE TITLE
Update FontAwesome to FontAwesome 5

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3179]
### Describe the problem

FontAwesome 4.7 (a version made back in 2016) is no longer being maintained and needs to be replaced with FontAwesome 5. This will be a very annoying process as basically all the icons and classes have changed.

### Describe the solution you'd like

- [ ] First, update FontAwesome (This will break all icons more than likely)
- [ ] Fully replace all icons with the new classes

**Comment by tywrenn** [comment]
This will definitely be an 'awesome' upgrade yet i'd like to see someone else do this :)

**Comment by stu01509** [comment]
I would like participate this issue 🙂

**Comment by surendrap720** [comment]
I would like to work on this

**Comment by bradymiller** [comment]
@stu01509 , Since you got to this first (by several minutes it appears), this is yours.
@surendrap720 , guessing there will be testing and related fixes needed on this (since will be seeking out all the broken icons with lots of testing in the near future).

**Comment by stu01509** [comment]
Hi @bradymiller 



> @stu01509 , Since you got to this first (by several minutes it appears), this is yours.
> @surendrap720 , guessing there will be testing and related fixes needed on this (since will be seeking out all the broken icons with lots of testing in the near future).

Thanks for your assigned.
