### ISSUE TITLE
Certain buttons impossible to read 

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#318]
I noticed this with the latest tab/design code. It affects my product registration buttons so I have a temporary override in place (forces the buttons to have a specific background/foreground color as opposed to using jQueryUI theme styles).

Anyway, on to the bug at hand. Please note the 3 buttons to the left (I highlighted the bottom one):
![image](https://cloud.githubusercontent.com/assets/1715206/19421793/0e1a956c-93d7-11e6-8757-d7dee48c4443.png)

I wonder if there are other areas are affected as well.

OPENEMR: Version Number: v5.0.0-dev (which I am developing on top of)
SYSTEM: Chromium Version 50.0.2661.102 Built on Ubuntu 14.04, running on LinuxMint 17.3

**Comment by MatthewVita** [comment]
@bradymiller can I have permissions to assign labels to tickets? ` Bug` `Tab Layout` are probably the right items here.

-m

**Comment by bradymiller** [comment]
@MatthewVita ,
Sure things. Will assign the permissions when get to computer this evening. Also, if this is not a new instance of OpenEMR(ie. upgrading), ensure empty the browser cache and run sql_upgrade.php script to bring in the new globals (or, the poor man method to do this is to just do Save on Administration->Globals). Guessing the issue is related to missing some of the new globals which above will fix.
-brady

**Comment by bradymiller** [comment]
@MatthewVita ,
If the above steps don't help with blank buttons issue, what theme are you using at:
Administration->Appearance->'General Theme (need to logout/login after change this setting)'

**Comment by bradymiller** [comment]
@MatthewVita ,
You have access to write and admin labels. Note I needed to give you write access to the repo to be able to do this, so just need to ensure you don't add any branches to the openemr repo.
thanks, -brady

**Comment by MatthewVita** [comment]
Brady, no cigar (cleared cache, updated db, toggled theme, apply globals, etc)

**Comment by MatthewVita** [comment]
@robertdown is the `css_button` class supposed to have the follow actively applied:

```
background: #2672EC none repeat scroll 0% 0%;
```

?

**Comment by bradymiller** [comment]
Try out most recent codebase and see if still an issue (note I basically did work arounds; there definitely seems to be some css clashing happening in some places, especially with the Radiant theme).

**Comment by bradymiller** [comment]
@MatthewVita , Just checking if this is still an issue?

**Comment by MatthewVita** [comment]
@bradymiller this appears to be fixed:

![image](https://cloud.githubusercontent.com/assets/1715206/21583879/6e1f7a74-d061-11e6-95d1-592f7c0208be.png)

Please close the issue.
