### ISSUE TITLE
Object not found in Miscellaneous/authorizations

### ISSUE THREAD

**Issue by adad20** [openemr/openemr#3191]
### Describe the bug
Something needs to be rendered in the authorizations page but console is showing err 404 not found.

### To Reproduce
Go to Miscellaneous/authorizations 

### Actual behavior
 
![Screenshot (87)](https://user-images.githubusercontent.com/55142272/77089795-4790d200-6a2c-11ea-8711-fd603a6d5154.png)

- Browser: Chrome

**Comment by adad20** [comment]
hi @bradymiller Can you tell me what's there and also Can I work on this issue?

**Comment by stephenwaite** [comment]
hi @adad20 , it should be trying to load from the [menu json](https://github.com/openemr/openemr/blob/master/interface/main/tabs/menu/menus/standard.json#L1971-L1988)

**Comment by bradymiller** [comment]
fixed by @harshbawari
