### ISSUE TITLE
Add "developer-tools" to the docker development environment

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3193]
### Describe the feature you'd like

Provide developers with testing tools out of the gate in the developer docker environment.

### Describe the solution you'd like

Add support to the development docker to allow the developer to do the following in the docker:
1. php syntax checking
2. psr2 checking
3. unit tests
4. e2e tests
5. api tests

Note that only need to actually bring in the required libraries/packages into the docker, because it's easy to then run the needed commands from outside the docker.

Would add a "developer-tools" setting in the docker that could then add to the docker-compose.yml:
https://github.com/openemr/openemr/blob/master/docker-compose.yml#L48
Then would use the setting here to bring in the packages needed to support the developer-tools:
https://github.com/openemr/openemr-devops/blob/master/docker/openemr/flex-3.10/autoconfig.sh#L170

Then the user can run the developer-tools from outside the docker. For example phpcs run would look something like:
```
docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'php /pathsomething/PHP_CodeSniffer/bin/phpcbf -n --extensions=php,inc --standard=ci/phpcs.xml .'
```

**Comment by bradymiller** [comment]
btw, travis does all the above, so that is the best place to find out which packages to bring in to support this:
https://github.com/openemr/openemr/blob/master/.travis.yml

**Comment by prondubuisi** [comment]
Hello @bradymiller is this something anyone other than yourself could work on, lol. If so I would love to jump on this.

How would I be able to test this? A new docker install?

**Comment by bradymiller** [comment]
hi @prondubuisi , go for it!

you will basically build the docker in https://github.com/openemr/openemr-devops/blob/master/docker/openemr/flex-3.10/
When you build it, use the following command:
```
docker build --no-cache -t openemr/openemr:flex-3.10 -t openemr/openemr:flex .
```
Then this will now be the docker that the main docker-compose.yml will use locally for you:
https://github.com/openemr/openemr/blob/master/docker-compose.yml#L23

And if you dig a really big hole and want the official dockers back, then just do:
```
docker pull openemr/openemr:flex
docker pull openemr/openemr:flex-3.10
```
