### ISSUE TITLE
Create update Encounter API

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr#3194]
### Describe the problem

Write an endpoint for uploading patient encounter 

### Write concise description of what feature you want
create a
PUT /api/patient/:pid/encounter/:eid API endpoint
for updating inserted patient encounter

**Comment by prondubuisi** [comment]
Hello @bradymiller in addition to this are there any other API endpoints that one can work on? thanks

**Comment by bradymiller** [comment]
The encounter PUT would be good. And a couple TODO as bottom of the API doc(https://github.com/openemr/openemr/blob/master/API_README.md); immunizations and prescriptions would be high impact on that list. Also looks like History, Transactions, Disclosures, and Amendments are miss.

Labs/procedures are missing, but this is going to be complicated.

Encryption/decryption support would also be neat, but that is pretty involved. see my last to posts on this thread and disregard the backup stuff https://github.com/openemr/openemr/issues/2024
(this would be more in line would somebody that wanted to learn ins and outs of encryption/decryption)
