### ISSUE TITLE
No Error Response in FHIR

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3195]
### Describe the bug

There is no error response in FHIR api.
Extension of https://community.open-emr.org/t/project-fhir-integration/13701/13?u=yashrajbothra
### Expected behavior
Something like this would be nice.
![image](https://user-images.githubusercontent.com/47683556/77150623-4c9c6280-6aba-11ea-81c9-321fff469738.png)

Additional Context : Currently working on it. Feel Free to assign me 😄

**Comment by sjpadgett** [comment]
glad to have ya
