### ISSUE TITLE
Ability to have ICD codes assigned to patient & stay on patient's record

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3199]
### Describe the problem

The doctor I'm working with wants the ability to have ICD codes tagged to a patient and stay on the patient's record (unless deleted) and stay in the fee sheet regardless if you add another encounter. This doctor is an Orthopedic Surgeon and consistently uses the same ICD's for multiple patients. 

### Describe the solution you'd like

Since this is a situation-based scenario where only some doctors might want this, this should be able to be toggled in Globals. The ICD's probably will need to be stored in SQL for each patient.

**Comment by tywrenn** [comment]
I'm not too good in dealing with this one so if anyone wants to solve it go ahead

**Comment by stephenwaite** [comment]
this is supported fairly well already with the link/add issues section on the visit summar which will also poplulate the most common dx in the cpt4 on click popup 

![Screenshot from 2020-03-21 20-02-59](https://user-images.githubusercontent.com/5618372/77239264-0117b080-6baf-11ea-81ac-db56dc1031e2.png)

there's also a review button above which will bring in the last billed svc for the pt

**Comment by tywrenn** [comment]
@stephenwaite This is why I wish we had better documentation!!! Closing.

**Comment by sjpadgett** [comment]
First @tywrenn I turned on the dark theme and wow! my friend, great job! You might say i've come out of the light and into the darkness. No worries, i'll pray for myself at church tomorrow:)
Was that theme based on light?

More to the documentation point. As most know a big part of any engineering program core is technical writing. Maybe we have a student who would take it on.

Personally, i'm above such things and always had my interns/associate engineers do it :) We all had to pay these dues so get it out of the way sooner than later.

**Comment by tywrenn** [comment]
@sjpadgett The dark theme is based on the light theme -- The way I did it was first convert the light theme to BS4 and then invert the colors to make the dark theme which took awhile.

We definitely need someone to take this on with GSoC. I don't know half the functions in this EMR which is why documentation should be priority number 1. We should also make it a system that is required when adding new things and is in one centralized area (that means closing old areas).

**Comment by sjpadgett** [comment]
Yep you're right. I'm guilty mostly but, we have to be careful about requirements like this because it is hard enough getting folks to contribute new features much less try to treat them as employees. If a developer knows they have to do a bunch of strict requirements, they'll most likely pass.

**Comment by tywrenn** [comment]
@sjpadgett There has to be an easier way for documentation....

**Comment by sjpadgett** [comment]
Maybe a template that outlines the basics.

**Comment by bradymiller** [comment]
GSoC isn't meant for pure documentation projects and is meant to be coding based. The projects that will be worked on definitely should be documented, though.

For documentation, here's something to look into that is documentation specific: https://developers.google.com/season-of-docs

**Comment by bradymiller** [comment]
@robertdown is working on migrating the old wiki to something much more modern which will hopefully help on this front also

**Comment by sjpadgett** [comment]
Thats fine but maybe we should put a little more emphasis on in app helps.
