### ISSUE TITLE
patient_data_template.php not using responsive design

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3203]
### Describe the bug

In `/interface/main/tabs/templates/patient_data_template.php`, the current design isn't really responsive. 

### To Reproduce
https://prnt.sc/rka8gq

### Expected behavior

Some things should be collapsing here. My recommended solution is to replace the flex columns with BS4 grid classes instead to fix this issue.

I'm not too keen on how to fix this so if anyone wants to fix this please do.

**Comment by sjpadgett** [comment]
Ideally we want the tree columns to stack on each other and not necessarily inside columns responsive.
Any search can stand on its own and doesn't have to be inline.
Or redesign the whole bar if that's what it takes.

**Comment by sjpadgett** [comment]
Hey @tywrenn ,
This works nicely. What do you think? I was almost there with keeping flex which i'm dogged to do :)
goes in interface/main/tabs/templates/patient_data_template.php
[patient_data_template.zip](https://github.com/openemr/openemr/files/4363725/patient_data_template.zip)

**Comment by sjpadgett** [comment]
![image](https://user-images.githubusercontent.com/1859985/77234626-4ecbf300-6b86-11ea-83da-e92aa6c99d7a.png)

**Comment by sjpadgett** [comment]
PR: https://github.com/openemr/openemr/pull/3206
I hope fixes this. I'm happy compared to previous but feel free to modify.
Bringing in PR and leaving issue open in case:)

**Comment by tywrenn** [comment]
@sjpadgett Looks a lot better

**Comment by sjpadgett** [comment]
I think this will work for now so close this issue if author agrees.
