### ISSUE TITLE
Improve Diagnostics gui

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3205]
### Describe the problem

Improve Diagnostics gui at Administration->System->Diagnostics

### Describe the solution you'd like

1. Remove the links at top and only show the information that you see in the `Test System` category.
2. Migrate it out of smarty on to its own script (this will allow easy addition of other Diagnostic tests in the future)
3. Remove the `Test System` link from Administration->Clinic->Calendar and all related calendar/smarty elements/code

**Comment by stu01509** [comment]
Hi @bradymiller 

Please assign this issue to me.
Thank you :)

**Comment by bradymiller** [comment]
hi @stu01509 , it is yours :)
