### ISSUE TITLE
Openemr not logging in on chrome

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#3209]
Hi,
I am working on windows 10 with xampp 7.3.15 and running openemr 5.0.3 dev version. There are 2 issues - 
1. Using chrome whenever I am trying to log in, it just keeps authenticating and nothing happens. Using Firefox, there is no issues.

2. while working in openemr, when trying to change anything in globals and hit save, it just shows a white page but changes are saved in database. I found the following errors in the error log - 

[Sun Mar 22 08:13:08.359586 2020] [php7:notice] [pid 15964:tid 1896] [client ::1:60255] OpenEMR Error : Decryption failed authentication., referer: http://localhost/openemr/interface/super/edit_globals.php
[Sun Mar 22 08:13:08.359586 2020] [php7:notice] [pid 15964:tid 1896] [client ::1:60255] OpenEMR Error : Key creation is not working - Exiting., referer: http://localhost/openemr/interface/super/edit_globals.php

Kindly help for these two issues.

Dr. Arnab Naha

**Comment by bradymiller** [comment]
hi @arnabnaha ,
Sounds like either missing critical directories or permission issues with these directories. Ensure you have the following directories/subdirectory structure in documents directory:
https://github.com/openemr/openemr/tree/master/sites/default/documents
