### ISSUE TITLE
Fee Sheet: modifier

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#322]
I am unable to add a modifier "57" to a visit code.
To bill it out I have to manually add it into the DB table billing.

<img width="1083" alt="modifier" src="https://cloud.githubusercontent.com/assets/508784/19542027/1f0b9970-9639-11e6-9aa6-3a4ce8401532.png">

Working off 5.0.0-dev

**Comment by ophthal** [comment]
This bug may be peculiar to how the Eye Form auto-populates the Fee Sheet but the fix is simple:
I believe the one line change is here:
https://github.com/ophthal/openEMR_2/pull/2/files
but if not, it is line 707 in library/FeeSheet.Class.php changes 
from:
          $tmp = sqlQuery("SELECT * FROM billing WHERE id = ? AND _billed = 0_ AND activity = 1"...
to:
         $tmp = sqlQuery("SELECT * FROM billing WHERE id = ? AND **(billed = 0 or billed is NULL)** AND activity = 1"...

**Comment by bradymiller** [comment]
I brought your commit into the main codebase. thanks for the fix!
