### ISSUE TITLE
Fix curly brace style in RestContoller methods

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr#3220]
### Describe the problem

Hello @bradymiller @stu01509 as discussed [here](https://github.com/openemr/openemr/pull/3211) there is need to change the style of curly braces in most of the RestController methods 

### Describe the solution you'd like

Most braces for If conditions look like this
```
if (is_array($validationHandlerResult)) {
            return $validationHandlerResult; }
```
Should be changed to look like this
```
if (is_array($validationHandlerResult)) {
    return $validationHandlerResult;
}
```

as this improves readability

I also think this will a good issue for first time contributors, so we can add the label. then encourage new contributors in the slack/telegram group to give it a try

**Comment by prondubuisi** [comment]
Classes Affected are found here https://github.com/openemr/openemr/tree/master/src/RestControllers
Pick up to 3 classes at a time.

**Comment by stu01509** [comment]
Nice, It sounds good ideas. 👍👍
