### ISSUE TITLE
DOB field in Add Patient form should limit date latest by the current date

### ISSUE THREAD

**Issue by skshahnawaz** [openemr/openemr#3222]
The Date of Birth (DOB) form field in Add Patient Form has a datepicker with options to select date greater than current date. This needs to be limited to the current date.

**Comment by skshahnawaz** [comment]
@bradymiller Please assign this issue to me. I want to fix this

**Comment by stephenwaite** [comment]
thanks for taking this on @skshahnawaz

**Comment by bradymiller** [comment]
I am pretty sure this was fixed recently:
https://github.com/openemr/openemr/pull/3023

Is this still in issue in most recent codebase?

**Comment by adad20** [comment]
hi @bradymiller I have checked this issue is does not exist. DOB is already limit by the current date.

**Comment by skshahnawaz** [comment]
I mean the options for selecting year is available upto 2047, though selections beyond current date are disabled. What I was trying to focus is to limit the options of the Year to current year


<img width="1319" alt="Screenshot 2020-03-24 at 10 28 13 PM" src="https://user-images.githubusercontent.com/52563824/77454759-fbc09d00-6e1e-11ea-9b81-f1a12e178fd1.png">

**Comment by adad20** [comment]
@skshahnawaz Ohk you mentioned date that's why we got confused.😅
