### ISSUE TITLE
Add update/insert to FHIR encounter resource

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3226]
As soon as the standard encounter api endpoint PR #3211 is merged you can leverage it for your transaction.

**Comment by sjpadgett** [comment]
@wisdommatthew or @wisdommatt
I can't find your handle in lookups so I can't assign you. Go ahead and work it.

**Comment by bradymiller** [comment]
@wisdommatt will need to post a message on this PR, then can Assign

**Comment by prondubuisi** [comment]
@sjpadgett any sample lookups as to how this works? I am looking to do some FHIR work

**Comment by sjpadgett** [comment]
take a look at now merge PR# 3212 @silvistershebin did a very nice job at catching on and implementing same pattern for patient resource.
I'm so happy some folks want to help with FHIR. Next thing ya know, kids will start eating their vegetable!!!!

**Comment by silvistershebin** [comment]
I can take this up @sjpadgett

**Comment by prondubuisi** [comment]
Hello @silvistershebin how were you able to test your fix? postman?

**Comment by prondubuisi** [comment]
> Hello @silvistershebin how were you able to test your fix? postman?

Confirmed it can work with postman, Is there a Documantation for FHIR in terms of endpoints and JSON accepted? @bradymiller @sjpadgett @silvistershebin

**Comment by yashrajbothra** [comment]
> > Hello @silvistershebin how were you able to test your fix? postman?
> 
> Confirmed it can work with postman, Is there a Documantation for FHIR in terms of endpoints and JSON accepted? @bradymiller @sjpadgett @silvistershebin

https://www.hl7.org/fhir Every Resource with Example is here in this Docs. Further you can compare it with HAPI Test server.

**Comment by prondubuisi** [comment]
> > > Hello @silvistershebin how were you able to test your fix? postman?
> > 
> > 
> > Confirmed it can work with postman, Is there a Documantation for FHIR in terms of endpoints and JSON accepted? @bradymiller @sjpadgett @silvistershebin
> 
> https://www.hl7.org/fhir Every Resource with Example is here in this Docs. Further you can compare it with HAPI Test server.

 thanks @yashrajbothra , Was wondering why we don't have our own docs to specify what we have done, how you can test it, and what we still want to do(Todos)

**Comment by yashrajbothra** [comment]
> > > > Hello @silvistershebin how were you able to test your fix? postman?
> > > 
> > > 
> > > Confirmed it can work with postman, Is there a Documantation for FHIR in terms of endpoints and JSON accepted? @bradymiller @sjpadgett @silvistershebin
> > 
> > 
> > https://www.hl7.org/fhir Every Resource with Example is here in this Docs. Further you can compare it with HAPI Test server.
> 
> thanks @yashrajbothra , Was wondering why we don't have our own docs to specify what we have done, how you can test it, and what we still want to do(Todos)

I guess there were less contributors intrested in FHIR so far. But now we are here 😃

**Comment by wisdommatt** [comment]
> @wisdommatthew or @wisdommatt
> I can't find your handle in lookups so I can't assign you. Go ahead and work it.

Y can't you find my handle

**Comment by wisdommatt** [comment]
@bradymiller  I would like to work on this

**Comment by sjpadgett** [comment]
> I would like to work on this

At the time I could not assign to you because you hadn't posted a post yet. Now that you have I can assign.

**Comment by sjpadgett** [comment]
@prondubuisi 

> Was wondering why we don't have our own docs to specify what we have done, how you can test it, and what we still want to do(Todos)

Hi @prondubuisi That's on me. However, I've posted numerous pleas for help with FHIR over last three years where i've indicated the goal of getting required resources in place.

With the current codes intent being an example of patterns, it is by no means the end all. Sooo, you guys can improve or offer suggestion on implementation if you feel a better solution is warranted.
Nobody is going to hurt my feelings or anger the mentor gods in anyway.:)

Would you like to pick up developing a new resource?

**Comment by sjpadgett** [comment]
@silvistershebin and @yashrajbothra 
Same with you guys. How about taking a shot at a resource?

**Comment by yashrajbothra** [comment]
Yea @sjpadgett Sir ,Sure trying to implement Validation but in parallel i can take any clinical module resource.

Can I start with AllergyIntolerance resource or something is more prior?

**Comment by prondubuisi** [comment]
So many persons want to work on this. Time to create the documentation with todos! lol

> @prondubuisi
> 
> > Was wondering why we don't have our own docs to specify what we have done, how you can test it, and what we still want to do(Todos)
> 
> Hi @prondubuisi That's on me. However, I've posted numerous pleas for help with FHIR over last three years where i've indicated the goal of getting required resources in place.
> 
> With the current codes intent being an example of patterns, it is by no means the end all. Sooo, you guys can improve or offer suggestion on implementation if you feel a better solution is warranted.
> Nobody is going to hurt my feelings or anger the mentor gods in anyway.:)
> 
> Would you like to pick up developing a new resource?

That would be nice. How about we create  a document say FHIR_README.md to start with this?

**Comment by sjpadgett** [comment]
> Can I start with Allergy Intolerance resource

Hi @yashrajbothra Actually both validation and ValeSets are very important along with resources however, whatever you take on, be sure it falls into goalset you've offered for your project proposal.
We(mentors) will try to make adjustments to overall FHIR project to accommodate meeting your project goals. So if we start moving in a direction away from where you're at or blows the scope of what you're trying to achieve then, speak up.

If Allergy Intolerance is your passion at the moment then by all means, go:)

**Comment by sjpadgett** [comment]
> How about we create a document say FHIR_README.md to start with this?

And what do you propose I put in this doc?

**Comment by prondubuisi** [comment]
> > How about we create a document say FHIR_README.md to start with this?
> 
> And what do you propose I put in this doc?

I don't really have experience with this ,but am thinking it should contain things like what we have done, how you can test it, and what we still want to do(Todos). Something like API_README.md. Since we are looking to engage contributors here is would be nice to get a guide docs I think.

**Comment by bradymiller** [comment]
hi @prondubuisi ,
Could possibly just use the API_README.md for this since we don't need to list FHIR endpoints (since standardized). What about this as a starting point:
https://github.com/openemr/openemr/pull/3234/files
(then could place FHIR TODO along with API and even a FHIR specific section)
(note I removed team section since the team is getting too big to list :) )

**Comment by prondubuisi** [comment]
> hi @prondubuisi ,
> Could possibly just use the API_README.md for this since we don't need to list FHIR endpoints (since standardized). What about this as a starting point:
> #3234
> (then could place FHIR TODO along with API and even a FHIR specific section)
> (note I removed team section since the team is getting too big to list :) )

@yashrajbothra @silvistershebin can we collaborate to make this happen?

**Comment by bradymiller** [comment]
go for it on the doc stuff. I'll bring in the PR.

**Comment by yashrajbothra** [comment]
Hey @sjpadgett Sir, So I was testing create in a patient resource and found a use case. What if something is not a `Required` as per FHIR spec but our `SQL query` is designed that way that it throws an error because of its `Required` there. Whom should we follow?

Side Note: Same Data I am posting in test server goes well.

**Comment by sjpadgett** [comment]
If it is not a part/element of the resource then that could be an issue. However, if the resource includes the element we can still require as part of our capability.

**Comment by yashrajbothra** [comment]
{
        "resourceType" : "Patient",
        // from Resource: id, meta, implicitRules, and language
        // from DomainResource: text, contained, extension, and modifierExtension
        "identifier" : [{ Identifier }], // An identifier for this patient
        "active" : <boolean>, // Whether this patient's record is in active use
        "name" : [{ HumanName }], // A name associated with the patient
        "telecom" : [{ ContactPoint }], // A contact detail for the individual
        "gender" : "<code>", // male | female | other | unknown
        "birthDate" : "<date>", // The date of birth for the individual
        // deceased[x]: Indicates if the individual is deceased or not. One of these 2:
        "deceasedBoolean" : <boolean>,
        "deceasedDateTime" : "<dateTime>",
        "address" : [{ Address }], // An address for the individual
        "maritalStatus" : { CodeableConcept }, // Marital (civil) status of a patient
        // multipleBirth[x]: Whether patient is part of a multiple birth. One of these 2:
        "multipleBirthBoolean" : <boolean>,
        "multipleBirthInteger" : <integer>,
        "photo" : [{ Attachment }], // Image of the patient
        "contact" : [{ // A contact party (e.g. guardian, partner, friend) for the patient
            "relationship" : [{ CodeableConcept }], // The kind of relationship
            "name" : { HumanName }, // A name associated with the contact person
            "telecom" : [{ ContactPoint }], // A contact detail for the person
            "address" : { Address }, // Address for the contact person
            "gender" : "<code>", // male | female | other | unknown
            "organization" : { Reference(Organization) }, // C? Organization that is associated with the contact
            "period" : { Period } // The period during which this contact person or organization is valid to be contacted relating to this patient
        }],
        "communication" : [{ // A language which may be used to communicate with the patient about his or her health
            "language" : { CodeableConcept }, // R!  The language which can be used to communicate with the patient about his or her health
            "preferred" : <boolean> // Language preference indicator
        }],
        "generalPractitioner" : [{ Reference(Organization|Practitioner|
            PractitionerRole) }], // Patient's nominated primary care provider
        "managingOrganization" : { Reference(Organization) }, // Organization that is the custodian of the patient record
        "link" : [{ // Link to another patient resource that concerns the same actual person
            "other" : { Reference(Patient|RelatedPerson) }, // R!  The other patient or related person resource that the link refers to
            "type" : "<code>" // R!  replaced-by | replaces | refer | seealso
        }]
        }

This is Patient Resouce. Right now Create Function does have some of the things but not all.
What if someone post out of our Capability.
Is it necessary to support all of this?

**Comment by sjpadgett** [comment]
@yashrajbothra @silvistershebin @prondubuisi 
Very good pickup Yash. Yes it is true that our standard patient service will not provide everything needed in the patient resource, we still have to deal with other referenced elements. Take:

> "generalPractitioner"

Normally you'd expect this person to be an openemr provider however, just like a ccda import, this will mostly be a provider from another clinic. To us he is an external provider, to patient he is the current provider.(i've got to stop using the he pronoun, the gals are going to get mad at me!:)). So we still have to deal with this. How?
This is why during resource parse we need to check these reference. Basically two ways you can encounter. One; as a canonical url to the reference or two; the content of the referenced element. 
The latter is easier because all we have to do is call the user service and add as an external provider or it may be the provider is supplied as an organization so then its a facility. CCDA import can provide some insight into how openemr handles this type of data. Fhir come out of the same spec that governs xml CCDA!

Here's the gotcha and where we need to make an engineering decision. How do we handle a canonical url? Want to try an answer? Hint: could involve infrastructure.

**Comment by yashrajbothra** [comment]
Hii @sjpadgett Sir, I was trying to find the answer but ended with another question. In test server (HAPI) the canonical URL should in a format but they don't check if it exists or not. Do we have to check the reference exists or just the format which is defined by FHIR?

**Comment by sjpadgett** [comment]
Hi Yash,
This is because they opted to save the url rather than resolve and pull in the content the url ref points to. On the public fhir server i'm guessing it could generate a lot of traffic.

We in the end will probably need to resolve the end point resource especially for importing transactions like transfer of care etc.

**Comment by sjpadgett** [comment]
> Hi Yash,
> This is because they opted to save the url rather than resolve and pull in the content the url ref points to. On the public fhir server i'm guessing it could generate a lot of traffic.
> 
> We in the end will probably need to resolve the end point resource especially for importing transactions like transfer of care etc.
