### ISSUE TITLE
Search Engine

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3231]
### Describe the problem
OpenEMR is desperate for a search engine. To many features require search. Reports comes to mind but, generalLy APIs would benefit immediately.

By having  a central search engine we can pull much sql from core and have it in one place. 
Now I get that the more granular search requirements by some scripts will need to remain with scripts but generally, how can we go wrong!

I propose an abstract or interface class for specific search terms followed. Then individual classes to implement. ie basic pattern

I'd like to get opinions @bradymiller @robertdown @stephenwaite @adunsulag

**Comment by adunsulag** [comment]
@sjpadgett I'm mostly familiar with the CCDA and module parts of the codebase.  What does the data look like for the rest of the codebase in terms of searching on categorical data versus full text searching.  Do we need to search on documents or encrypted columns at all?

**Comment by sjpadgett** [comment]
Maybe a more apt name would be a query engine. I know of no document text type search and for doing full text search on tables, not sure but, I seem to recall one or two somewhere. Most are lookups where they are duplicated in various versions achieving the same results throughout codebase. These can be moved.

I bring this up mainly for API search say, with FHIR. I used integrating with codebase as a weak attempt as more justification for the engine.:)

**Comment by sjpadgett** [comment]
Okay, i'll just do it!

**Comment by adunsulag** [comment]
Sorry @sjpadgett I wish I had more time in the day to do all that I want to do.  I asked about the full text search because I was wondering if we wanted/needed to use something like sphinx for full document / text search.

Categorical search is a much easier problem to solve than full text parsing or partial search matches, branching etc.

I think we had a student that was going to work on the FHIR search as part of their proposal.  Have you had a chance to evaluate it / offer comments?  You might be able to guide them through it, allowing you to focus on other efforts.

**Comment by sjpadgett** [comment]
No problem @adunsulag , I know you're busy and try not to include you directly in discussions. But, most times I can count on you to participate.

The only reason I put up these issues to prompt a discussion is that most times I develop infrastructure and nobody uses or get pissy about the way it was done.
Also, feedback is nice where someone may have experienced a similar situation that could make life easier.

Just easier for me to do it but, once in awhile, I try.

**Comment by sjpadgett** [comment]
btw: conical search would be just one of the implemented class. Then there'd be a search string parse class and so forth...

For students, i'm still trying to figure out if you want to be engineers or coders!

**Comment by sjpadgett** [comment]
> and nobody uses or get pissy about the way it was done.

oh my, did I say that out loud:)

**Comment by adunsulag** [comment]
I just finished a 6 month effort that part of it included encrypted search using blind indexes in order to keep the data encrypted using non-deterministic encryption (to avoid dictionary / rainbow table attacks) on the database columns but also be able to search on it.  However, I treated each search entity separately with no cross-entity searching as the use case doesn't need it right now.  

I don't think we do in in-table encryption in Open-EMR, just have the database encrypted at rest.  If any of the data you are going to search on is encrypted at the column level I'm happy to offer my experiences there.

I've written systems to interface into sphynx which followed off a tag model and overall document search.  In searching systems everything is based off of 'documents' and 'tags' and all of the research papers talk in those mechanisms.

I think you are just wanting more of the architecture that entities can extend / hook into to be part of the search system right?

**Comment by prondubuisi** [comment]
> btw: conical search would be just one of the implemented class. Then there'd be a search string parse class and so forth...
> 
> For students, i'm still trying to figure out if you want to be engineers or coders!

Whats the --diff ? Definitely love to be an Engineer. Until someone changes my mind.

**Comment by sjpadgett** [comment]
> I don't think we do in in-table encryption

We don't however, it's been discussed. If anything, for the specific reason to secure transactional data.

> extend / hook

That's the gist however, you did remind me of security which moves me to lean more towards an abstract class.  Even hooking into dispatcher to validate search terms before hitting handling classes.

**Comment by sjpadgett** [comment]
> Whats the --diff ?

To be blunt, for one thing, if I had one of my interns/jr. engineers come to me and ask for a todo, i'd send them to engineering support or the coding group.
I'm sorry but, i'm an old school(I guess) engineer/engineering manager. I though our students are from engineering programs but I realize that may not be true. So I need to lighten up and be more supportive. Which I will.

If I was to sum up an engineer vs a coder in couple sentences here it is: An engineer is forward thinking, adaptable, creative and tends toward finding paths to solutions. Then perhaps offer alternatives.
A coder, well, wants todo's.

**Comment by bradymiller** [comment]
But that may be the definition from the perspective of an engineer :)

From a coder, the definition may be that engineers dream and coders do
Or maybe it is coders dream and engineers do

Dang, now I'm confused. I'll search for the answer in OpenEMR's search api:
```
curl -X GET 'http://localhost:8300/apis/api/search/difference/coder/engineer'
```
It didn't work :(

**Comment by sjpadgett** [comment]
I'm impressed doctor. The years i've known you I finally get to see the lightened up side of you. 
Or is this your way of tactfully telling me i'm being to much of a hard???:)

**Comment by bradymiller** [comment]
lol, I think Jerry should keep on being Jerry
The telegram chatter/antics must just be expanding to github (shameless plug for OpenEMR telegram chat channel that @stephenwaite set up at: https://t.me/openemr )

**Comment by yashrajbothra** [comment]
> > Whats the --diff ?
> 
> To be blunt, for one thing, if I had one of my interns/jr. engineers come to me and ask for a todo, i'd send them to engineering support or the coding group.
> I'm sorry but, i'm an old school(I guess) engineer/engineering manager. I though our students are from engineering programs but I realize that may not be true. So I need to lighten up and be more supportive. Which I will.
> 
> If I was to sum up an engineer vs a coder in couple sentences here it is: An engineer is forward thinking, adaptable, creative and tends toward finding paths to solutions. Then perhaps offer alternatives.
> A coder, well, wants todo's.

Woohoo, then I am Just trying to be a Good Engineer.

So far I am multi-tasking a lot and my git stash is gone messy but I would like to contribute to this one. As per my understanding here we want a class or something which can be used everywhere for searching in a database so we don't need to write SQL for search again n again. Please Correct me if I misunderstood.

**Comment by prondubuisi** [comment]
> > Whats the --diff ?
> 
> To be blunt, for one thing, if I had one of my interns/jr. engineers come to me and ask for a todo, i'd send them to engineering support or the coding group.
> I'm sorry but, i'm an old school(I guess) engineer/engineering manager. I though our students are from engineering programs but I realize that may not be true. So I need to lighten up and be more supportive. Which I will.
> 
> If I was to sum up an engineer vs a coder in couple sentences here it is: An engineer is forward thinking, adaptable, creative and tends toward finding paths to solutions. Then perhaps offer alternatives.
> A coder, well, wants todo's.

Well It turns out I am partly a coder and partly an Engineer!

**Comment by bradymiller** [comment]
a hybrid
I think that's a Enginoder :)

**Comment by prondubuisi** [comment]
> a hybrid
> I think that's a Enginoder :)

Thankfully you don't apply this concatenation when naming Identifiers.

**Comment by sjpadgett** [comment]
All right, All right. Make fun if you will but, think about it a minute.

It's true, an engineer needs some coding skills however, not in just one language but all the languages of his discipline. More than coding skills, he needs to understand  these various language architectures so they can make an informed decision as to if it best applies to their task at hand.
After that an engineer makes decision on how best to structure the application of the language and so forth.
This is when they will select the coder that may specialize, and is very good, in that language.
I'm not saying a coder is not just as valuable to the team but, just different discipline.

Take me for example. My degree is in Electrical Engineering. Back then we had to certify and sub disciplines like computer science was just coming around. I chose electronic design which I did for eight years using the first microcontrollers during which having to pick up firmware programming in assembly because I got tired of firmware engineers that didn't understand hardware. Anyway, to the point. I always had several engineering technicians that was very good at building prototypes and interfacing with manufacturing.

Get the difference.?  I'm not trying to belittle any student and while I don't make a very good mentor, I was a very good trainer of young engineers that went on to good careers.
Just saying!

**Comment by prondubuisi** [comment]
> All right, All right. Make fun if you will but, think about it a minute.
> 
> It's true, an engineer needs some coding skills however, not in just one language but all the languages of his discipline. More than coding skills, he needs to understand these various language architectures so they can make an informed decision as to if it best applies to their task at hand.
> After that an engineer makes decision on how best to structure the application of the language and so forth.
> This is when they will select the coder that may specialize, and is very good, in that language.
> I'm not saying a coder is not just as valuable to the team but, just different discipline.
> 
> Take me for example. My degree is in Electrical Engineering. Back then we had to certify and sub disciplines like computer science was just coming around. I chose electronic design which I did for eight years using the first microcontrollers during which having to pick up firmware programming in assembly because I got tired of firmware engineers that didn't understand hardware. Anyway, to the point. I always had several engineering technicians that was very good at building prototypes and interfacing with manufacturing.
> 
> Get the difference.? I'm not trying to belittle any student and while I don't make a very good mentor, I was a very good trainer of young engineers that went on to good careers.
> Just saying!

Points taken @sjpadgett. FWIW I think you are doing pretty well as a mentor on here!

**Comment by robertdown** [comment]
Let’s stick to the topic at hand and try to avoid rabbit holes that only cause schisms between different types of contributors. Engineers, coders, hybrids all have a place in the community and all bring valuable skills to the codebase.

**Comment by sjpadgett** [comment]
@robertdown 
I'm talking to students and will skew topic how I see fit. It's my topic.

I don't see you contributing to topic title!

**Comment by sjpadgett** [comment]
I can play this game....

**Comment by bradymiller** [comment]
ok, nothing to see hear :)

![image](https://user-images.githubusercontent.com/278968/77589294-a3ce7880-6ea8-11ea-81d0-357e1ae772da.png)

Gonna try to say something somewhat intelligent regarding search api to keep things positive:
Regarding search engine and api in general, an overriding goal is that Services take over the functionality in the myriad of other places where these functions exist.

**Comment by bradymiller** [comment]
dang, I like the gif, but my comment wasn't smart enough :(

Anyways, keep discussing whatever you feel like discussing whether it be search api or the evolution patterns of Enginoders :)

**Comment by yashrajbothra** [comment]
GIFKing @bradymiller , I wanna learn how you pick so amazing GIFs every time😍

**Comment by mdsupport** [comment]
Going back to original question, I got lost at 

> Reports comes to mind

So I will skip that and go with the assumption that you are proposing response to plain text in google styled single textbox like `'jon doe'` will display links for everything on patient dashboard for `'jon doe'` and encounter details and lab results `'jon doe'` etc. with minimal details.  If the mechanism is good it will also show `'john doe'`, `'jane doe' `and whatever the algorithms come up with.  Turn it around by entering 'HTN' to get list of patients, documents, messages related to hypertension.

If so, rather than on demand solution consider offloading this to couchdb.  As entities get updated, they can dump a document.  Couch will index them and [be ready to respond](https://docs.couchdb.org/en/master/ddocs/search.html) for really complex Lucene queries.

FHIR explore specifications seemed way more daunting to implement and (even more to so) to maintain because of codeset contexts.  There must be a broker service out there for that.

**Comment by sjpadgett** [comment]
> There must be a broker service out there for that.

I've been looking. My trouble is we are the only project I know of that is developing FHIR in PHP. There just aren't any libraries we can pop in so with everything we do, we have to get creative.
We may need to get into document search, with FHIR at least, if we decide to support that capability.
