### ISSUE TITLE
Navbar Broken

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3238]
### Describe the bug
The navbar is broken as shown below.

### To Reproduce
https://prnt.sc/rm8hf7

### Expected behavior
No broken navbar

### Client configuration

- Browser: Google Chrome 80.0.3987.149
- Operating system: Ubuntu LTS

**Comment by tywrenn** [comment]
Anyone wanna fix this?

**Comment by tywrenn** [comment]
I think I should take this up cuz it's complex

**Comment by sjpadgett** [comment]
What broken?

**Comment by tywrenn** [comment]
Logo is misaligned

**Comment by tywrenn** [comment]
Also the profile area might be too yet i'm not sure

**Comment by sjpadgett** [comment]
okay, just wondering.

**Comment by sjpadgett** [comment]
> yet the dropdown is wrong for it

yep, alignment is wrong. don't know if there's an easy fix for that...
