### ISSUE TITLE
Facilities does not show at the Facility dropdown list

### ISSUE THREAD

**Issue by robertogagliotta** [openemr/openemr#324]
I just install a fresh openemr from git. After I add my facilty on Administration -> Facilities and them I add a office visit the Clinic Name does not show in Facility dropdown list

**Comment by bradymiller** [comment]
Ensure you toggle on the Service Location in Administration->Facilities entry. Then it should show up. Let us know if that works or still not working. thanks, -brady

**Comment by robertogagliotta** [comment]
It works. Brady Thanks
