### ISSUE TITLE
COVID-19 Forms

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#3242]
This will be a place to find related COVID-19 forms that we are trying to create.

#3241 CDC PUI and Case Report Form

**Comment by dtobi59** [comment]
@robertdown Hope, I can proceed with this.

**Comment by dtobi59** [comment]
I am working on this...

**Comment by dtobi59** [comment]
Hello @robertdown,  kindly suggest. checkbox or a Select Option.

![ji](https://user-images.githubusercontent.com/13191454/77837026-18a7e980-7119-11ea-9de5-d4d5c43c0850.JPG)

**Comment by robertdown** [comment]
Hi @dtobi59 I would recommend a select box as the selections for each of those questions are mutually exclusive

**Comment by 0silverback0** [comment]
hi I'm new to coding and PHP but I'm very interested in this project how can I help

**Comment by imakshat47** [comment]
Hey @robertdown, I have a good experience in this technology stack and would be glad to work on this technology. Can you assign me this task?

**Comment by bradymiller** [comment]
bump
