### ISSUE TITLE
Appointment Search in Calendar Needs BS4

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3248]
### Describe the bug

When you click search in calendar, the search for appointments area hasn't gotten any BS4 improvements.

### To Reproduce
https://prnt.sc/rmwvq5
![image](https://user-images.githubusercontent.com/46497068/77607066-a0aaab00-6eef-11ea-9b3e-9591211b6875.png)
https://prnt.sc/rmwuyg
![image](https://user-images.githubusercontent.com/46497068/77607088-aa341300-6eef-11ea-91d1-77d3e175ce67.png)

**Comment by tywrenn** [comment]
Anyone wanna fix this?

**Comment by stu01509** [comment]
Please assign this issues to me.

**Comment by bradymiller** [comment]
hi @stu01509 , it's yours :)
