### ISSUE TITLE
Font Awesome icon issue.

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3251]
### Describe the bug

In the input submit button, Add `btn btn-primary btn-save` style, But font awesome icon
didn't display.

![image](https://user-images.githubusercontent.com/22230889/77763255-c2359f00-7075-11ea-976e-13dec7a1dbc8.png)

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

**Comment by adad20** [comment]
@stu01509 I have faced the same issue but when I used `<button>` instead of `<input>` it worked.

**Comment by stu01509** [comment]
Hello @adad20 

I know it can use <button> instead of <input>, But in OpenEMR have a lot of input submit button, If we can solve it that will be great!

**Comment by bradymiller** [comment]
hi @stu01509 and @adad20 , May not be a solution for the input issue: https://stackoverflow.com/questions/2587669/can-i-use-a-before-or-after-pseudo-element-on-an-input-field

**Comment by bradymiller** [comment]
so appears pseudo-elements (etc ::before) can not act upon replaced elements (etc input): https://developer.mozilla.org/en-US/docs/Web/CSS/::after
https://codebond.co/tutorial/css/all-about-before-and-after-pseudo-element

(i hope i am wrong :) )

**Comment by adad20** [comment]
hi @bradymiller @stu01509 I noticed in different places of codebase button is coded in different styles. Some have used `<input>`, `<button>` and `<a>`. So, we need a standard here also.

![Screenshot (111)](https://user-images.githubusercontent.com/55142272/77819335-1d13d880-7100-11ea-9b71-9767c7edcc7f.png)

**Comment by stu01509** [comment]
Hi @bradymiller and @adad20 

Thanks for your information, It would help me to try to fix this issue.

**Comment by bradymiller** [comment]
hi @stu01509 , will assign this to you looking forward to the solution you come up with :)

**Comment by stu01509** [comment]
Hello @bradymiller @tywrenn and @adad20 

Finally, I didn't found any result to solve the pseudo-elements in the input.
Maybe we need to change the input to the button tag or definition a standard, Is it a good idea?

**Comment by tywrenn** [comment]
@stu01509 Does the file have the fontawesome library in the assets? If not that's definitely the reason.

**Comment by bradymiller** [comment]
I think this is basically because pseudo-elements (etc ::before) can not act upon replaced elements (etc input). Is it feasible to convert from input elements to buttons?

**Comment by tywrenn** [comment]
@bradymiller In this case it is feasible to convert this to a `<button>` element as it's using an onClick method which is supported in buttons

**Comment by tywrenn** [comment]
My case for buttons and hyperlinks is if you're using an onClick method and aren't using the href attribute at all (and you don't want it to display as a hyperlink and are using the btn classes), you should replace it with the `<button>` element.

**Comment by stu01509** [comment]
Hi @bradymiller and @tywrenn 

I will start to rplace the input to button tag, Thanks for your explain :)

**Comment by stu01509** [comment]
Hi @bradymiller 

Should I have to close this issue?

**Comment by bradymiller** [comment]
hi @stu01509 , I'll close this. Sounds like may need to add blurbs to the styling guide issue regarding this problem and advice given above by @tywrenn.
