### ISSUE TITLE
Attack of Errors

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3255]
### Describe the bug

I was trying to install OpenEMR with XAMPP. Php ver - 7.2.9

![image](https://user-images.githubusercontent.com/47683556/77804631-0b9de280-70a6-11ea-92c3-3ce9853b9ae1.png)
 
AM I  MISSING SOMETHING??

**Comment by stephenwaite** [comment]
hi @yashrajbothra , look out :)
common xampp issue to turn off notices, https://www.open-emr.org/wiki/index.php/FAQ#What_are_the_correct_PHP_settings_.28can_be_found_in_the_php.ini_file.29.3F

**Comment by stu01509** [comment]
Hello @yashrajbothra 

Configure the php.ini file that the problem will be fixed.

**Comment by yashrajbothra** [comment]
Thanks, @stephenwaite  @stu01509 I turned off display errors and its gone now. But shouldn't we solve the errors rather than stop displaying ??

**Comment by stephenwaite** [comment]
hi @yashrajbothra , yes, believe that's a huge project that is in the works https://github.com/openemr/openemr/issues/3118

**Comment by yashrajbothra** [comment]
Ohh, how can I forget that. Thanks for the reference @stephenwaite .
