### ISSUE TITLE
Installing OpenEMR on Window

### ISSUE THREAD

**Issue by dtobi59** [openemr/openemr#3260]
### After cloning the OpenEMR to my local machine, when I tried accessing it on my browser I keep getting an error as shown below:

![slack1](https://user-images.githubusercontent.com/13191454/77838147-f23c7b00-7125-11ea-9567-3735b9a6bd4e.JPG)

### I'm currently using:
Window OS
Xampp

**Comment by adad20** [comment]
hi @dtobi59  Which php version are you using?

**Comment by stu01509** [comment]
Hello @dtobi59 

Do you configure your php.ini file as well? If not maybe will facing this issue.

**Comment by dtobi59** [comment]
> hi @dtobi59 Which php version are you using?

PHP 7.2.28

**Comment by dtobi59** [comment]
> Hello @dtobi59
> 
> Do you configure your php.ini file as well? If not maybe will facing this issue.

Yes I have configured my php.ini  to:

```
short_open_tag = Off
max_execution_time = 60
max_input_time = -1
max_input_vars = 3000
memory_limit = 512M
display_errors = Off
log_errors = On
post_max_size = 30M
file_uploads = On
upload_max_filesize = 30M
error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT
mysqli.allow_local_infile = On
```

**Comment by adad20** [comment]
hi @dtobi59  after configuring have u restarted your XAMPP server

**Comment by dtobi59** [comment]
> hi @dtobi59 after configuring have u restarted your XAMPP server

Yes, I have.

![git](https://user-images.githubusercontent.com/13191454/77853001-6f073d80-7196-11ea-8fe1-07b6568acb26.JPG)

**Comment by stephenwaite** [comment]
hi @dtobi59 , what does the php error log show?

**Comment by adad20** [comment]
hi @dtobi59 , I am not sure then what's happening maybe @stu01509 will tell something. From my side try to reinstall it.

**Comment by dtobi59** [comment]
> hi @dtobi59 , I am not sure then what's happening maybe @stu01509 will tell something. From my side try to reinstall it.

Okay, I will try

> hi @dtobi59 , what does the php error log show?

```
[Sun Mar 29 17:49:32.790252 2020] [php7:warn] [pid 9204:tid 1948] [client ::1:51957] PHP Warning:  require_once(C:\\xampp\\htdocs\\openemr/vendor/autoload.php): failed to open stream: No such file or directory in C:\\xampp\\htdocs\\openemr\\setup.php on line 97

[Sun Mar 29 17:49:32.794243 2020] [php7:error] [pid 9204:tid 1948] [client ::1:51957] PHP Fatal error:  require_once(): Failed opening required 'C:\\xampp\\htdocs\\openemr/vendor/autoload.php' (include_path='C:\\xampp\\php\\PEAR') in C:\\xampp\\htdocs\\openemr\\setup.php on line 97
```

**Comment by adad20** [comment]
hi @dtobi59 Have you configured your active php.ini file. I think problem is there only, any other comments @stephenwaite

**Comment by dtobi59** [comment]
> hi @dtobi59 Have you configured your active php.ini file. I think problem is there only. Close all the server, restart your machine, start all servers, delete the database if there exist with same name, do the installation process again.
> Any other comments @stephenwaite

I have tried it, still not working...

**Comment by dtobi59** [comment]
Thanks @adad20  @stephenwaite @stu01509, your contributions were indeed useful. I have to be able to find a solution to the bug.

Solutions:
1. Install Composer
2. Run The Command   `composer dump-autoload -o`

**Comment by sjpadgett** [comment]
> After cloning the OpenEMR

umm are you pulling from master or downloading released zip?

**Comment by dtobi59** [comment]
> > After cloning the OpenEMR
> 
> umm are you pulling from master or downloading released zip?

@sjpadgett. I'm currently Pulling from the master.

**Comment by sjpadgett** [comment]
Are you building the dependencies? Is this for development or production site?

**Comment by dtobi59** [comment]
> Are you building the dependencies? Is this for development or production site?

It's for Development.  I guess I'm missing something vital. could you please tell me. Thank you.

**Comment by sjpadgett** [comment]
Sure.
I assume you have a git client installed plus I think you've installed composer but you'll also need npm/node so get it installed.
Then in openemr folder open a git bash(or whatever bash you've installed) and run:

composer install &&
npm install &&
npm run build &&
composer dump-autoload -o

I wouldn't try to develop using windows command prompt. Get a git bash for windows if one is not installed.
