### ISSUE TITLE
Style Buttons in New Appointment Modal 

### ISSUE THREAD

**Issue by surendrap720** [openemr/openemr#3262]
### Describe the problem
According to the styling guidelines mentioned in #3160 , the buttons at the bottom in the new appointment modal should have proper classes.

Write a concise description of the problem 
The buttons should have btn-group class and a button like delete should have class btn-danger.

![2020-03-29](https://user-images.githubusercontent.com/15845220/77842670-2e420100-7163-11ea-8e79-4b8009eb416b.png)

### Describe the solution you'd like
The buttons should have proper classes as mentioned in #3160

**Comment by stu01509** [comment]
Are you working on this issue?

**Comment by nkyriakoulis** [comment]
I have created a pull request that resolves that issue #3264
