### ISSUE TITLE
UI of labs tabs is not upto standards

### ISSUE THREAD

**Issue by adad20** [openemr/openemr#3267]
### Describe the bug
UI is not upto the standards.

1. Go to Procedures -> Lab overview

### Actual  behavior
![Screenshot (114)](https://user-images.githubusercontent.com/55142272/77856025-0f4e7800-7212-11ea-9216-6c6ca93ac05f.png)

PS: I wanna work on this issue :)

**Comment by adad20** [comment]
Also there is one unexpected behavior when I select any of the radio button and hit submit it always results in no parameter selected.

**Comment by adad20** [comment]
hi @stephenwaite @bradymiller how can I add the data(lab record) in order to get the output. I tried some but it always says no parameters selected?

**Comment by im-Amitto** [comment]
@adad20 As I can see the screenshot that you uploaded at the beginning there are no procedure_results available to be selected for the current patient.
Add a few and option will appear below the select items :smile:

**Comment by adad20** [comment]
hi @im-Amitto yeah that I figured out but the real query is how can I add them😅

**Comment by im-Amitto** [comment]
@adad20 
Check this out: https://www.open-emr.org/wiki/index.php/Procedure_configuration_%26_order_process

**Comment by im-Amitto** [comment]
@adad20 Also,
Old Location: Miscellaneous => Addr Book 
New Location: Administration => Addr Book
Old Location: Administration => Lists 
New Location: Administration => Forums => List

**Comment by adad20** [comment]
hi @im-Amitto Thanks I am working on it :)

**Comment by adad20** [comment]
hi @bradymiller while I was trying to solve this issue there was something I noticed
here it says
![Screenshot (118)](https://user-images.githubusercontent.com/55142272/77924177-0072ce80-72c1-11ea-8f1b-f7e43d46cf9f.png)

but there is no pencil icon 
![Screenshot (117)](https://user-images.githubusercontent.com/55142272/77924217-0b2d6380-72c1-11ea-870e-29025357c08e.png)

Is there some problem in my local installation or this is a bug?

**Comment by tywrenn** [comment]
Wow this definitely was a good catch

**Comment by adad20** [comment]
hi @im-Amitto @bradymiller I have added the lab data ye nothing is showing up

![Screenshot (126)](https://user-images.githubusercontent.com/55142272/78049602-e3a9ca00-7398-11ea-9625-07db3d10fbdc.png)

![Screenshot (128)](https://user-images.githubusercontent.com/55142272/78049615-e60c2400-7398-11ea-9445-aae9322eb42b.png)

I am figuring out the possible reason for this in the interface -> patient_file -> summary -> labdata.php file but can't find the possible reason if anyone have idea of this behavior do let me know :)

**Comment by stephenwaite** [comment]
hi @adad20 , always tedious to add lab data but wanna try to load through some dummy labs?

you will have to create a procedure provider and then import the attached hl7, there are a few other steps so let me know if interested
[steve.zip](https://github.com/openemr/openemr/files/4411138/steve.zip)

**Comment by adad20** [comment]
hi @stephenwaite yes I have created the procedure provider and do I need to import in the procedure_type table?

**Comment by stephenwaite** [comment]
if you've set it up correctly you can extract the zip to a local folder and then use Procedures-> Electronic Reports

you'll want to set up the provider in admin->users with npi 1548374382

**Comment by adad20** [comment]
hi @stephenwaite Sorry I was not active. I have started working on this issue :)

**Comment by adad20** [comment]
hi @stephenwaite  I have set some data it is showing like this

![Screenshot (133)](https://user-images.githubusercontent.com/55142272/78552524-4aaa0180-7825-11ea-9755-a76497030d88.png)

**Comment by stephenwaite** [comment]
nice work @adad20 , any luck getting the labs graph to display on the dashboard?

**Comment by adad20** [comment]
hi @stephenwaite No nothing is showing up

**Comment by stephenwaite** [comment]
and when you `Click here to view and graph all labdata.` ?

**Comment by adad20** [comment]
Nothing is showing up

**Comment by stephenwaite** [comment]
looks like there still aren't any results
there should be items listed here if you've entered results

**Comment by stu01509** [comment]
Hello @adad20 

Oops, I'm not noticed you have mentioned to me,
Does this problem seem like about SQL query?

**Comment by adad20** [comment]
Hi @stu01509 SQL query seems fine to me, data is in the reports_type table yet it is not rendering to the page. I think I am missing something 🤔

**Comment by stephenwaite** [comment]
hi @adad20 @stu01509 , think it's easier to import hl7 with my steve.zip file above although there's a few steps, want me to outline them again?

**Comment by adad20** [comment]
Yes please I want data 😅

**Comment by sjpadgett** [comment]
@stephenwaite If I remember correctly, wasn't these reports written against self entered results. Electronic resulting has/had issues with some of these reports. Same issue in portal lab reporting.

**Comment by stephenwaite** [comment]
1. change the npi of the admin user in Admin->Users to 1548374382
2. go to the addr book and setup a test lab service so it will appear in
3. Procedures->Providers, the test will autopopulate and then choose
4. results-only, extract the steve.zip to a directory that's specified like below
![Screenshot from 2020-04-07 10-52-24](https://user-images.githubusercontent.com/5618372/78685783-3c5cf380-78c0-11ea-9d22-c768996ee2e3.png)

**Comment by stephenwaite** [comment]
> @stephenwaite If I remember correctly, wasn't these reports written against self entered results. Electronic resulting has/had issues with some of these reports. Same issue in portal lab reporting.

no, see below for 5.0.2 view

![Screenshot from 2020-04-07 16-13-11](https://user-images.githubusercontent.com/5618372/78714975-b99d5e00-78ea-11ea-8e7b-6c06b2fa3f51.png)
![Screenshot from 2020-04-07 16-13-45](https://user-images.githubusercontent.com/5618372/78715016-c457f300-78ea-11ea-9f6d-a435bf1199d1.png)

**Comment by stephenwaite** [comment]
5. docker cp steve.zip 7ae3196908b6:/tmp/.
6. docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c 'unzip /tmp/steve.zip -d /tmp/hl7'

**Comment by stu01509** [comment]
Hi @adad20  @stephenwaite 
Thanks for your data and information, I will in-depth study it after I fix my PR and issue.

**Comment by stephenwaite** [comment]
bump, maybe @stu01509 is planning to return to this

**Comment by stu01509** [comment]
Hi @stephenwaite 

Ok, Please assign this issue to me, I will plan to fix it :)
