### ISSUE TITLE
Refine Background Services page

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3276]
### Describe the bug

Refine Background Services page
Miss responsive table.

### To Reproduce

1. Choose Reports > Services
2. Click Background Services
3. See the table

![image](https://user-images.githubusercontent.com/22230889/77913347-ab39bb80-72c6-11ea-9123-8137c69ee58b.png)

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

**Comment by gayatri-patil** [comment]
Hi @stu01509 
On my browser the table is responsive. Can you send a pic and dimensions after which the table isn't responsive?
Browser: Firefox 74.0 (64 bit)
Operating System: Ubuntu

**Comment by stu01509** [comment]
Hello @gayatri-patil 

My means is this page has a section that needs to refine, e,g. title position and table style.

**Comment by gayatri-patil** [comment]
Ohk. I'll have a look at it.

**Comment by mdsupport** [comment]
Many of the reports are a dump of single recordset.  The datatables component already in the system does that more consistently.  Perhaps you should look at that option.

**Comment by stu01509** [comment]
Hi @gayatri-patil 

Are you working on this issue? If not @bradymiller sir, Please reassign this issue to me.

**Comment by gayatri-patil** [comment]
Hi @stu01509 
I'm working on it. My laptop had a major issue, as a result I had to uninstall Ubuntu, hence my entire work got deleted. I'm working on it again. Sorry for the delay.

**Comment by stu01509** [comment]
Hello @gayatri-patil 

Ok, If you have any question welcome to discuss with us 😃

**Comment by stu01509** [comment]
Hi @bradymiller @stephenwaite 

Please reassign this issue to me.
Thanks.

**Comment by bradymiller** [comment]
hi @stu01509 , it is yours :)

**Comment by tywrenn** [comment]
bump
