### ISSUE TITLE
warning when closing an encounter form

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3279]
### Describe the problem
you've entered dictation into the SOAP note in an encounter and mistakenly click the `x` in the tab and close it or mistakenly click `Cancel` at the bottom and close it thus losing all of your work
![Screenshot from 2020-03-30 12-56-29](https://user-images.githubusercontent.com/5618372/77940112-32b30a80-7286-11ea-824f-ece4d5e1d749.png)

### Describe the solution you'd like

should be warned you are about to lose data entered but not saved

**Comment by yashrajbothra** [comment]
I am getting bored of same stuff. Can i pick this up?

**Comment by sjpadgett** [comment]
@yashrajbothra I have a FHIR issue you could address if you want. I'll put up the issue shortly.

Concerning this issue. What about our other core forms. This issue is very much needing resolution. Sorry @stephenwaite if I potentially stole Yash! :)

**Comment by stu01509** [comment]
I would like to try this,
Please assign this issue to me.

**Comment by sjpadgett** [comment]
@stu01509 it's yours
