### ISSUE TITLE
REST API Write Access

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3281]
I can't imagine allowing third party or any client application insert/update of patient data. Maybe it's just me but, I consider this a huge security concern. So at minimum, it would be limited to transactions like imports etc. Something that would require an audit before adding to chart or specifically requested by an OpenEMR work flow.
Now this restriction makes API dynamic exchanges difficult. I always intended that the FHIR API be restricted to read only. Currently the requirement for ONC. Same for standard API.

This needs to be addressed for policy so I need all Admins to comment on this.

This decision will affect how we authorize applications where that workflow development needs to happen soon.

Also we need to start audit trails for all REST API's where we can maybe leverage how i've done it in portal.

**Comment by bradymiller** [comment]
hi @sjpadgett ,
I think the api has already made that decision for us (Can add/edit a bunch of things already). As long as we keep an eye on the permission of the user via the RestConfig::authorization_check calls, I think will be ok.

**Comment by sjpadgett** [comment]
yep I get we have acl control. maybe if we had an api group that a practice would knowingly have to select to allow api write access above the more granular permissions. Still I don't get how allowing unmonitored writes to patient data as acceptable.

**Comment by bradymiller** [comment]
I wouldn't call it unmonitored, since it will get captured by the log engine. If a user has login credentials, they can do all the same stuff without the api. Isn't having a token considered the same thing for that user?

**Comment by sjpadgett** [comment]
I suppose this is true for client applications written specifically for a singular providers use.
What about applications that want to modify chart data with a general access ie practice assigns a user specific to an application. Who is going to save the practice from themselves?

**Comment by sjpadgett** [comment]
maybe I over thinks this just doesn't feel right...

**Comment by bradymiller** [comment]
When we are just thinking about standard users, then it makes sense to just limit use by the acl. This is all I've thought about, so never got me nervous.

But agree thought needs to go into other ways that the api will be called via applications or other ways we haven't thought about. Will be helpful to have specific use cases of this so can begin to figure out ways to confine access to only what the app should be having access to.

**Comment by sjpadgett** [comment]
I'll put up some examples but i need to get to getting some dev done on PROMIS and Fhir. The students keep me on my toes.
Questionnaire Response will be an example of possible unsolicited transactions where an outside app would want to create patients, encounters even procedure results. It gets complicated quick...

**Comment by rhausam** [comment]
I think that having properly controlled API write access capability is going to be important, especially in decision support scenarios.  Has anyone done (even very preliminary) investigation into the possibilities of leveraging SMART on FHIR and CDS Hooks in OpenEMR?

**Comment by sjpadgett** [comment]
> Has anyone done

Not recently. Do you have a general example?
