### ISSUE TITLE
Improving styles in user interface

### ISSUE THREAD

**Issue by dheero** [openemr/openemr#3282]
there are many update needs in the design of the front end of the various pages such as index(home), login, logout, help and about pages, to make it more interactive and user friendly.

To solve these conflicts there is a need for modernizing styles In the user interface to make it more interactive by CSS files
and there is a need for improving bootstrap design according to the new version of it.

there is a need for the feature to make users up to date when some important event organizes or new news updated to the server by email.
and also increase some tools of javascript in the OpenEMR to make it more friendly to use.

**Comment by tywrenn** [comment]
This project is already being sought after in Google Summer of Code:
https://community.open-emr.org/t/project-modernize-styling-and-user-interface/13777

**Comment by dheero** [comment]
yeah, Sir, I am interested in Gsoc 2020 and want to more explore it and I can as you can see on my repositories, I have work on that all skills which is needed in this project
https://community.open-emr.org/t/project-modernize-styling-and-user-interface/13777

my GitHub repositories: https://github.com/dheero?tab=repositories

**Comment by adad20** [comment]
hi @dheero Welcome start working on the small issues(bugs) and familiarize yourself with the codebase.

**Comment by dheero** [comment]
here are some pr's
https://github.com/openemr/openemr/pull/3291
https://github.com/openemr/openemr/pull/3292
https://github.com/openemr/openemr/pull/3293
