### ISSUE TITLE
unexpected required data in Update patient [fhir]

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3299]
### Describe the bug

https://github.com/openemr/openemr/pull/3298#issuecomment-606736136

cc @prondubuisi

**Comment by sjpadgett** [comment]
@yashrajbothra  umm, why not change in your PR while you're there. We admins only have so many machine cycles!

**Comment by yashrajbothra** [comment]
I think opening new PR will be a better idea as it is more on the standard API side and different purpose then that PR.

No problem though if u say 🤷‍♂

**Comment by sjpadgett** [comment]
> I think opening new PR will be a better idea as it is more on the standard API side

Just make a separate commit by itself in your PR. It's minor change and will still be searchable.

**Comment by bradymiller** [comment]
hi @yashrajbothra , Note the validation stuff for api is very "rough" and there is still work to do there. As is currently being done there, we definitely should not be requiring elements on a PUT as is done for the POST. @sjpadgett , this could get involved/complicated :)

**Comment by sjpadgett** [comment]
> this could get involved/complicated :)

So, tell me, what's new:)
Each service has a validation array where you can validate interested items as optional or required. It's just a matter of changing the required flag.

**Comment by yashrajbothra** [comment]
> hi @yashrajbothra , Note the validation stuff for api is very "rough" and there is still work to do there. As is currently being done there, we definitely should not be requiring elements on a PUT as is done for the POST. @sjpadgett , this could get involved/complicated :)

Sorry but which API validation are we referring here FHIR or standard?

**Comment by bradymiller** [comment]
i think we need the following different validates for patient:
PUT:
just need to require a valid pid
and could validate the items that are sent if wish (optional stuff)
POST:
require the other stuff

So need to break out different validate functions and/or parameters for them (I think)

**Comment by bradymiller** [comment]
so maybe put a second parameter in validate function (to set if an insert or update)?

**Comment by sjpadgett** [comment]
Yep I think you're right. Doesn't work the way I thought. Don't know, will look into

**Comment by bradymiller** [comment]
@yashrajbothra , the validate should be able to cover both api/fhir as it does now. Meaning, the same fix here is required both the api/fhir.

**Comment by yashrajbothra** [comment]
> PUT:
> just need to require a valid pid
This should be done in standard API validation function as this should be for both.

> and could validate the items that are sent if wish (optional stuff)
This should be in FHIR Validation

> POST:
> require the other stuff
Already in Standard one just need FHIR Validation here.

Although looks like little big should open this issue and new PR?
Because that might get delayed just because of this

**Comment by sjpadgett** [comment]
Insert and update will have same requirement whether for fhir or standard. I say just give the PatientService validate function a context parameter and then do the appropriate validation base on passed in context of update or whatever.

**Comment by yashrajbothra** [comment]
Now we can put this to the end 😉

**Comment by sjpadgett** [comment]
> we

umm, whose we? You meant Now I can, right? :)

**Comment by yashrajbothra** [comment]
> > we
> 
> umm, whose we? You meant Now I can, right? :)

After all, you are the one to review all the mess. So that way it's together we 😄

**Comment by sjpadgett** [comment]
got me there. okay, we'll get ur done!

**Comment by yashrajbothra** [comment]
the `parsePatientResource()` initialize all array element even if the client has not passed it due to which it overwrites all the data while updating. So I thought to just init those elements which we received from the client.
But I am not so confident with this line 
`$fhirJson["address"][0]["postalCode"] ? $data["postal_code"] = $fhirJson["address"][0]["postalCode"] : null;`

Is this okay?

**Comment by sjpadgett** [comment]
good point. I need a minute to think over anyway doesn't an uninitiated fhir element/object return null?

**Comment by yashrajbothra** [comment]
> good point. I need a minute to think over anyway doesn't an uninitiated fhir element/object return null?

No, I was talking about parsing user data and passing it to SQL query.

**Comment by yashrajbothra** [comment]
One more 
Can we use methods from this file for manipulating Patient data.
https://github.com/openemr/openemr/blob/master/library/patient.inc

Instead of writing all these queries again

**Comment by sjpadgett** [comment]
> Can we use methods from this file for manipulating Patient data.

sure, use any current tool you need..


> $fhirJson["address"][0]["postalCode"]

I'm thinking a null should have been passed.

**Comment by sjpadgett** [comment]
yep, this is issue with both apis. take a look at the Validate class. it's pretty extensive and may be of some help....

**Comment by yashrajbothra** [comment]
> yep, this is issue with both apis. take a look at the Validate class. it's pretty extensive and may be of some help....

Yeah, Thanks:) I read the Particle Validator Docs and it is very good will make our lives much better.
But right now we also have a problem with parsing which I think should be addressed in PR.

**Comment by yashrajbothra** [comment]
> i think we need the following different validates for patient:
> PUT:
> just need to require a valid pid
> and could validate the items that are sent if wish (optional stuff)
> POST:
> require the other stuff
> 
> So need to break out different validate functions and/or parameters for them (I think)

Hey Little misunderstanding here 

PUT should require the same stuff as POST
https://www.hl7.org/fhir/http.html#update
PATCH will be the one which requires only id with itself.
https://www.hl7.org/fhir/http.html#update

**Comment by sjpadgett** [comment]
again, we are not trying to be a full fhir server. we can't do versions.
also, all of this needs to be fixed in the sql builder for the updates/inserts etc imo at this moment. we need to only update those values passed in from the interface because sometimes you want to set a null or empty etc.

No, this is going to require some thought!
No this requires some thought because our standard api is broken too.

**Comment by yashrajbothra** [comment]
> p

Then what will be difference btw PUT and PATCH

Or we are ignoring PATCH and just using PUT as PUT+PATCH

**Comment by sjpadgett** [comment]
any updates we do will appear as a patch regardless. we'll only require pid then parse and only update record with requested update fields passed in. Patch can then still be implemented in routes.

**Comment by yashrajbothra** [comment]
I did some changes in the related PR. That can resolve the issue here. 

Please Review.
