### ISSUE TITLE
Buttons at bottom of add_edit_event.php are unacceptable

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3300]
### Describe the bug

The current buttons displayed at the bottom of add_edit_event.php aren't acceptable by any means in terms of design.

### To Reproduce
Create a new event in the calendar and look at the bottom of the page
![image](https://user-images.githubusercontent.com/46497068/78069016-674ac300-7367-11ea-97b5-12f97ac152c4.png)

### Expected behavior

There shouldn't be a `btn-group` in this as it makes it look awkward. This issue will revert #3271

**Comment by bradymiller** [comment]
hi @tywrenn,

Sounds like need to work out button guidelines in the styling guide:
https://github.com/openemr/openemr/issues/3160

Folks are using these "dynamic" guidelines and the btn-group comes from following post there:
"
To make the themes consistent, here's how the buttons should work:
- If you have a group of two or more buttons, be sure to use the `btn-group` class
- Anything that is going to delete something or remove something should be using the `btn-danger` class
- Anything that is trying to submit something or is a primary action should use the `btn-primary` class.
- Anything else, e.g. cancel button, can use the `btn-secondary` class.
- The `btn-link` class should be refrained from use as it doesn't really look too good with buttons/button groups. Please replace it with the `btn-secondary` class whenever possible.
- Most things can be used with all of the above classes. Sometimes using button outlines and the success, warning, info, light, and dark are needed yet generally they don't need to be used.
- If you would like the button to be smaller, you can use the `btn-sm` class with your button to make it smaller.
- If you would like a centered button, do not use the `<center>` element as CSS can do this for you. Just wrap your button in a `text-center` div element to center the button.
"
