### ISSUE TITLE
Discussion on Body Element Margins/Padding

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3302]
As I flip through OpenEMR, I've noticed a lot that our body element margins/padding are not really consistent. In this issue there will be subissues that we'll need to fix.

Subissues:
- [ ] First we should fix the `body_top` margins
Current Output:
![image](https://user-images.githubusercontent.com/46497068/78076390-53f22480-7374-11ea-8a15-18b3bc33cf0b.png)
Expected Output:
![image](https://user-images.githubusercontent.com/46497068/78076437-65d3c780-7374-11ea-9902-80af7798ec98.png)
- [ ] We should remove the `body_top` class and instead use it as the default for the `<body>` element
- [ ] We will need to remove the `body_top` class from everywhere when we remove it from the SCSS
- [ ] We need to evaluate the ones that aren't using the `body_top` class and see which ones need to be overridden
- [ ] For ones that don't need margins/padding, we should change the body class to `m-0 p-0`
More issues will be needed to fix in discussion

**Comment by stu01509** [comment]
Nice ideas, Can remove all body_top class as the default for the <body> element is the best way.

Link to Styling Guide in OpenEMR https://github.com/openemr/openemr/issues/3160

**Comment by tywrenn** [comment]
Closed. Read pull #3338 for explanation.
