### ISSUE TITLE
Fix body_top margins/padding and Remove body_top class (Sub-issue to #3302)

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3307]
This is a sub-issue to #3302.

The goal is to fix the `body_top` class margin/padding.
Current Output:
![image](https://user-images.githubusercontent.com/46497068/78192374-05ad5600-7446-11ea-9bbb-aeaa833d5257.png)

Expected Output:
![image](https://user-images.githubusercontent.com/46497068/78192398-1067eb00-7446-11ea-8455-e46ff7dcc7e4.png)

Also, this issue will remove the `body_top` class as we shouldn't be using it.

**Comment by tywrenn** [comment]
Anyone wanna fix this?

**Comment by stu01509** [comment]
Please assign this issue to me.

**Comment by bradymiller** [comment]
hi @stu01509 , it is yours :)

**Comment by sjpadgett** [comment]
> Expected Output:

To much. Just how much top margin do we need. As little as possible. Viewing area is at a premium. Do we really need that much title prominence

**Comment by tywrenn** [comment]
> As little as possible. 

If you make it as little as possible it's gonna make the entire viewport look like a giant table cell in my opinion due to it running really close with the navigation's border.

**Comment by stu01509** [comment]
Hi @tywrenn 

Should I remove body_top  class? According to this https://github.com/openemr/openemr/issues/3302 issue item1 description, use the default for the `<body>` element.

**Comment by sjpadgett** [comment]
> like a giant table cell in my opinion due to it running really close with the navigation's border.

lol, oops. I promised myself after liking the new themes(i'm a light theme guy) to stay out of styling with my more conservative approaches. I slipped and will leave it with you guys.

**Comment by tywrenn** [comment]
@stu01509 Now that you mentioned it you can also remove that too

**Comment by stu01509** [comment]
Hello @tywrenn @sjpadgett and @bradymiller 

I removed `body_top ` class in `body` tag, and added `mt-5` class to adjust margin, It looks like this.
Any suggestions or feedback? If not I will replace all `body_top` to `mt-5` class.

![image](https://user-images.githubusercontent.com/22230889/78340958-86488f80-75c9-11ea-9d26-17d3cd4e1374.png)


![image](https://user-images.githubusercontent.com/22230889/78341157-ce67b200-75c9-11ea-8bb2-9359cfd0f535.png)

**Comment by tywrenn** [comment]
What I wanted was to have no classes specified for the body element and use pure CSS to have that defined -- I'll tell you how to do this once I get the time today

**Comment by surendrap720** [comment]
@stu01509 I think something like this would work

body {
margin-top: 20px;
}

and this gets applied to body tag EVERYWHERE .

@tywrenn  Correct me if I am wrong.

**Comment by tywrenn** [comment]
@surendrap720 ur correct

**Comment by stu01509** [comment]
Hi @tywrenn 

Ok, I will start to remove `body_top ` and add `margin-top: 20px;` in `theme-defaults.scss`
Thanks for your explanation :)

**Comment by tywrenn** [comment]
Closed. Read pull #3338 for explanation.
