### ISSUE TITLE
Duplicate summary tabs

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3309]
### Describe the bug

Duplicate summary tabs when I close the Graphic Pain Map page.

### To Reproduce

1. Go to the Graphic Pain Map page
2. Click cancel button
3. See the duplicate summary tabs.

![image](https://user-images.githubusercontent.com/22230889/78253308-c3a81100-7526-11ea-9c3e-ed1381a3fe64.png)

https://i.imgur.com/VPyW9Kq.mp4

### Client configuration

- Browser: Chrome 80.0.3987.162 (Official Build) (64-bit)
- Operating system: Windows 10

**Comment by stu01509** [comment]
Hi @bradymiller 

Please assign this issue to me.
Thanks.

**Comment by bradymiller** [comment]
hi @stu01509 , it is yours :)

**Comment by stu01509** [comment]
I will send a PR as soon as possible :)

**Comment by bradymiller** [comment]
please also get rid of the background color of that form which infects the encounter screen also. It is flaring up my legacy OpenEMR flashbacks medical condition :)

![image](https://user-images.githubusercontent.com/278968/78422473-67231f80-7614-11ea-8052-5bdc8b06b1bc.png)

![image](https://user-images.githubusercontent.com/278968/78422484-7ace8600-7614-11ea-91a4-cec4edcce606.png)

These are not a horror movie scenes, but actual OpenEMR screenshots from the past :)

**Comment by stu01509** [comment]
Oh my! I can't imagine seeing the little bit OpenEMR's legacy UI in 2020.
Please hurry to merge it 😉.
