### ISSUE TITLE
Styling buttons in Message Center section

### ISSUE THREAD

**Issue by surendrap720** [openemr/openemr#3313]
### Describe the problem
The buttons in the message center section is not styled according to the styling guidelines.

![messageframeprevious](https://user-images.githubusercontent.com/15845220/78316359-70858c80-752d-11ea-8aa4-e9c27bccee1f.png)

Write a concise description of the problem 
The buttons in the message center should have bootstrap classes as described in styling guidelines. For example: The delete button should have btn-danger class. 

### Describe the solution you'd like
Giving appropriate bootstrap classes to all the buttons in the message center section.

![messageframe](https://user-images.githubusercontent.com/15845220/78316370-78ddc780-752d-11ea-98f6-f824d486aaef.png)

Please assign this to me.

**Comment by bradymiller** [comment]
hi @surendrap720 , it is yours :)

**Comment by surendrap720** [comment]
Thank you Brady !
