### ISSUE TITLE
Align use of OSI logo with guidelines.

### ISSUE THREAD

**Issue by massonpj** [openemr/openemr#332]
Hi OpenEMR,

The use of OSI logo on the OpenEMR site (http://www.open-emr.org/) does not comply with the OSI guidelines (https://opensource.org/trademark-guidelines). We are very happy to allow continued use of the logo to highlight that OpenEMR is distributed with an OSI Approved Open Source License, but do ask that your use comply with our guidelines. Can you please:

1. create a link from the logo to the OSI website, "the design logo hyperlinks to the OSI website, http://opensource.org/, or if that is not possible, the site includes a prominent link to the OSI website at http://opensource.org/" (OSI Trademark Guidelines §2.1.)
2. include the text "This site is not affiliated with or endorsed by the Open Source Initiative" prominently on any page that includes the OSI Trademarks," (OSI Trademark Guidelines §2.1.)

Finally should OpenEMR use the logo elsewhere, please provide a copy of its use to the Trademark Supervisor (trademarks(a)opensource.org) within seven (7) days of its initial use, for example by sending a URL or other copy of such use.

Thanks so much,
Patrick

**Comment by ophthal** [comment]
I am usually a quiet bystander, but if I have a vote, based only on the tone of this OSI request, I believe we should just remove the logo entirely.  Maybe even remove any reference to OSI so as not to unwittingly impose any further damage?

**Comment by massonpj** [comment]
Hmm, sorry if my tone came off poorly, I apologize, I just tried to be direct/brief. Again we are happy for the project uses the logo, and no damage has been done. We simply need to ensure constant use, in part to continue to protect our marks, so when people see the logo they can trust that the project does guarantee software freedom (there are many examples where the logo is used but not for open source software).

Again, my bad for being curt.

**Comment by bradymiller** [comment]
Hi @massonpj and @ophthal ,

Thanks for the comments.

Have a ongoing PR request going for this now:
https://github.com/openemr/website-openemr/pull/16

Just need to test it to ensure it doesn't detract from the website. The required "This site is not affiliated with or endorsed by the Open Source Initiative" statement may negate the positive presence of the logo in the end (many of the new users whom are new to open source may get skeptical upon seeing this kind of disclaimer). 

Timeline to complete will be a week or so.

thanks,
-brady

**Comment by robertdown** [comment]
See https://github.com/openemr/website-openemr/issues/16 for continued discussion regarding this issue.
