### ISSUE TITLE
Support multi site install with docker

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr#3327]
### Describe the problem
There is need to support the OpenEMR Multi-site install with docker, as there are issues related to the multi-site install which developers usually need to replicate before fixing.
https://www.open-emr.org/wiki/index.php/OpenEMR_Multiple_Sites_Module

### Describe the solution you'd like
As @bradymiller highlights, this can be achieved in the following steps

 1. The api on feature will provide an example of modifying the database in docker. This is not a dev tool command, but after figure out how to do that, can mimick same process for modifying database via other dev tool command. (DONE)
 2. Then we can do a command that does a `empty-openemr`, which then drops the openemr database, and restores an empty `sites/default/` from `/openemr/sites/default`. What this setting will do is basically clear the current install of OpenEMR, which means the dev will get to go through the manual install process (via setup.php), thus making development in installation scripts super easy.
 3. Then we can do a command that does a `reset-openemr`, which does everything above, but also does a auto install (ie. bypasses the manual setup.php script like is done when start up the docker).
 4. Then can bring in a command that does the changes required to use the multi site install (and also a command to revert the changes). This would then make it super easy to do development work on this feature.

Discussion can be seen here https://github.com/openemr/openemr/issues/2943

**Comment by prondubuisi** [comment]
As an asides @bradymiller also outlines the possible difficulty level as follows , as well as some other potential benefits

 1 will be straightforward, 2 will be almost straightforward, 3 will get tougher, and 4 will get even tougher). The reason I ordered them that way, is they build on each other (ie. can leverage what was done in earlier steps to complete the later steps). This would deal with some of the easy dev docker env weaknesses:
 
 1. Can't test/dev the installation very easily
 2. Can't do a quick OpenEMR reset without needing to do a full docker down/up

**Comment by bradymiller** [comment]
Just brought in the changes and updated the dockers:
https://github.com/openemr/openemr-devops/commit/ac83e541d359249a89bbd3122c131a0dc2458ae3
https://github.com/openemr/openemr/commit/4d6a4925198e16aeb7c6b1b4d45ab4c4068efefc

As a bonus, also added support for multisite :)
