### ISSUE TITLE
Error calling API auth

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3339]
### Describe the bug

write concise description of what the bug is.

Trying to connect API Auth.

Error Log
[Tue Apr 07 15:38:33.321124 2020] [php7:notice] [pid 10996:tid 1960] [client ::1:63965] OpenEMR Error : Decryption failed authentication.
[Tue Apr 07 15:38:33.322122 2020] [php7:notice] [pid 10996:tid 1960] [client ::1:63965] OpenEMR Error : Key creation is not working - Exiting.

System Config
Windows 10
Apache Server
Installation Type : Xampp
php : 7.2.9

**Comment by sjpadgett** [comment]
I use all day long on windows 10 xampp apache. no issues. I also test occasionally on my linux box between the two os....

**Comment by yashrajbothra** [comment]
IDK why but it happens sometimes and if I restart error goes away 😕

**Comment by sjpadgett** [comment]
I'll see this sometimes on openemr log in after I make a lot of changes or upgrade but I can explain those occasions. Intermittent on API Auth should be watched. See if you see a pattern etc.
I've never seen this issue on API but I can imagine it could happen.

**Comment by yashrajbothra** [comment]
> I'll see this sometimes on openemr log in after I make a lot of changes or upgrade but I can explain those occasions. Intermittent on API Auth should be watched. See if you see a pattern etc.
> I've never seen this issue on API but I can imagine it could happen.

I will try to run debugger next time I see something like this.
Should I close the issue for now?

**Comment by sjpadgett** [comment]
> Should I close the issue for now?

I'd leave open in case someone else comes across. However, in a testing environment where you might have other openemr sessions open, strange things may happen.

**Comment by dmasog** [comment]
I have a new install of latest code - single environment.

I got "Authentication Error" when trying to add a Code in Chrome after success setting up other aspects from scratch using both interface and API.
Added a new user and try again - auth fails
Try adding code using new user in Edge - auth succeeds
Come back to Chrome and add another Code - auth succeeds


System Config
Windows 10
Apache Server
Installation Type : Xampp
php : 7.4.3

**Comment by sjpadgett** [comment]
Thanks for reporting.
Maybe @bradymiller would have some insight. I don't think browser is really the issue and possibly if first attempt was made with Edge, would have failed.
