### ISSUE TITLE
How to set Expiry time of session in API Auth?

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3340]
Is there any way to set/Modify the Expiry time of API auth session.

**Comment by sjpadgett** [comment]
Go to table api_token and set there. I have one set for 2 years. I figure by then i'll be done with API:)

**Comment by yashrajbothra** [comment]
Should we give such option while calling auth Or in our portal?

**Comment by sjpadgett** [comment]
No, I still have more to do with Auth for the API!
