### ISSUE TITLE
UI Issue: Available appointments calendar misses the bootstrap

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3341]
### Describe the bug

Available appointments calendar misses the Bootstrap style.

### To Reproduce

1. Click the new appointments button.
2. Click the find available button.
3.  See the available appointments calendar.

![image](https://user-images.githubusercontent.com/22230889/78792216-6d821480-79e3-11ea-896d-b0ed48a03172.png)

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

**Comment by stu01509** [comment]
Please assign this issue to me.

**Comment by bradymiller** [comment]
hi @stu01509 , it is yours :)
