### ISSUE TITLE
Portal RTL layout broken

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3342]
### Describe the bug
Side bars disappear etc. 
Going to need a BS expert here. Not sure if asides can be used and absolute positioning is prob a no no.
### To Reproduce
Set a RTL language on login.

 Note: There was never an interest in portal by international so, hopefully can be addressed without to much fuss.

**Comment by stu01509** [comment]
Hi @sjpadgett 

Have any screenshot?

**Comment by sjpadgett** [comment]
Hi Cliff @stu01509 
![image](https://user-images.githubusercontent.com/1859985/78905703-65aa8a80-7a4c-11ea-84a1-34c1626fdd9d.png)

While sidebar will move to right, it ends up off screen after page renders. May just need a missing class. Or left(old right) content does not move as should. I may have hard coded it to the right.

Normal pages seem to render okay. Side bars may no longer be appropriate. I'll leave that to you younger guys.
![image](https://user-images.githubusercontent.com/1859985/78907004-19604a00-7a4e-11ea-8d78-f13c67bb4ab9.png)

**Comment by tywrenn** [comment]
I don't think we have a great RTL system setup for the patient portal tbh -- it isn't like the regular RTL setup we have cause that's separate. It'll probably take a bit to fix this

**Comment by sjpadgett** [comment]
Who fixed up the appointments. Very nice whomever did the final version. umm, maybe the trick was keeping me out of it!:)
Should have seen in v4.0.0 compared to now!

![image](https://user-images.githubusercontent.com/1859985/78966997-3d17a480-7acf-11ea-973b-cb9ea8353c32.png)

**Comment by tywrenn** [comment]
@sjpadgett That one was me 🙂 It was painful to do cause of margin issues yet it works lol

**Comment by tywrenn** [comment]
Here's how to fix RTL:
- Refactor/rename `patientportal-base.css`, `patientportal-style.css`, and `patientportal-register.css` to use the `scss` extension.
- Add the line to the bottom of each `@import "directional";`
- Add RTL methods to the gulpfile for the patient portal

**Comment by sjpadgett** [comment]
> yet it works lol

yep, that's the layout I was striving for. it's perfect so thanks....

**Comment by tywrenn** [comment]
@sjpadgett Figured out it isn't RTL actually, it's the hard-coded sidebar that's messing everything up. I need to find one that works better than that and has RTL support.
