### ISSUE TITLE
Add Procedure Resource

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3347]
### Describe the problem
resource: http://hl7.org/fhir/R4/procedure.html
profile: https://build.fhir.org/ig/HL7/US-Core-R4/StructureDefinition-us-core-procedure.html

Who wants?

**Comment by silvistershebin** [comment]
Hi @sjpadgett Sir, I can take this up :)

**Comment by sjpadgett** [comment]
Yours
