### ISSUE TITLE
FHIR Core Observation Profile

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3348]
### Describe the problem
Once the core Observation resource is developed then can be used for other observable profiles such as vitals.
http://hl7.org/fhir/R4/observation-vitalsigns.html
https://build.fhir.org/ig/HL7/US-Core-R4/StructureDefinition-us-core-observation-lab.html

This one could be fun and challenging.

**Comment by yashrajbothra** [comment]
Is it really soo challenging 🤔

**Comment by yashrajbothra** [comment]
But its fun too. So I would like to take this :)

**Comment by sjpadgett** [comment]
> Is it really soo challenging

Maybe not sooo much for you smart youngsters but, for us ole timers, very much sooo:)

It's yours and thanks

**Comment by yashrajbothra** [comment]
Hii @sjpadgett Sir, I was going through Observation Form thought we can use that but I couldn't understand the purpose of the observation form and how we can use that form?

Can you help me understand?

**Comment by sjpadgett** [comment]
Observation covers many different scopes. This is where Observation Profiles come in. Same with patient profiles etc
For our purposes let's profile vitals.
http://hl7.org/fhir/R4/observation-vitalsigns.html
