### ISSUE TITLE
Patient Publishing to HAPI FHIR R4 Returns A 400 Bad Request

### ISSUE THREAD

**Issue by dixonwhitmire** [openemr/openemr#3353]
### Describe the bug
When I publish a patient record to an external FHIR Server, http://hapi.fhir.org/baseR4, the publishing process returns the following message
```json
Transaction Status: 400 Bad Request
Server: nginx/1.14.0 (Ubuntu)
Date: Fri, 10 Apr 2020 18:45:21 GMT
Content-Type: application/fhir+json;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: HAPI FHIR 5.0.0-SNAPSHOT REST Server (FHIR Server; FHIR 4.0.1/R4)
X-Request-ID: 1FQXukAFxTu8sQrX
Replied Resource:
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": <omitted for brevity>,
 "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "No Content-Type header was provided in the request. This is required for \"UPDATE\" operation"
  } ]
}    
```

It appears that the request to the FHIR Server is malformed.

### To Reproduce
- Open a Patient Record
- Click the Publishing Tab
- Select the Publishing Option in the modal which appears

<img width="826" alt="openemr-publish" src="https://user-images.githubusercontent.com/39178401/79015945-d8466380-7b3b-11ea-8ed9-95e4a8c92086.png">

<img width="825" alt="openemr-publish-error" src="https://user-images.githubusercontent.com/39178401/79016370-c74a2200-7b3c-11ea-9d1c-75de2a7db511.png">

### Expected behavior
The FHIR Server Returns a 200 or 201 status code.

### Client configuration

- Browser: FireFox 74
- Operating system: OS X (10.15.3)

Based on your feedback, I am happy to look into this further and will submit a PR if necessary from my fork.

**Comment by sjpadgett** [comment]
This client is in transition. Originally our API prefixed id's so we could use put to create resources. We've since removed those. I've gotten as far as updating the UI to work with BS4. The version I have not pushed yet will use post and search to retrieve resources. It also uses a switch to use our API or public server. 

I'm still searching for a defined mission for Publish where we may just restrict to communicating to public/private servers.

**Comment by dixonwhitmire** [comment]
@sjpadgett thank you for the response.

I did see the issue with "patient-id" vs just the id.

I was able to get things working after adding in a constant in the "ClientController" to define the required headers. That's may be a bit heavy handed, but I was just getting a feel for how things are working.
```
    private const FHIR_HEADERS = array(
        "Content-Type" => "application/fhir+json",
        "Accept" => "application/fhir+json; fhirVersion=4.0",
        "Prefer" => "return=OperationOutcome"
    );
```

If the client is in "transition" do you think it would be open for additional contributions? Also, have there been any discussions regarding "auto-publishing" patient resources to a FHIR server, when a patient record is saved? I'm interested more in the latter for the use-case I'm working on.

Thank you for your time!

**Comment by sjpadgett** [comment]
@dixonwhitmire 


> If the client is in "transition" do you think it would be open for additional contributions?

Absolutely. You may do what you need and is the ideal direction. I may even leave it in 5.0.3:)
It is true we'd need to do data sync between app and server plus we have to have a review process for changed patient data. The user needs to be in that loop somehow.

My latest version is setup for our API. Including authentication. I could push and merge this version giving you a better starting point. You could then use the provided UI switch to redirect to public servers.

**Comment by dixonwhitmire** [comment]
@sjpadgett that sounds great! If you wouldn’t mind pushing your branch up I think that would accelerate things a bit. 

I believe you touched on this but ideally I would like to publish by
- searching for an existing resource
- send a POST or PUT based on if we have a “result”

This should ensure better integration with a variety of FHIR servers as a “create with a PUT request” is not defined as a “must support” operation in the spec.

Additionally we can map the “open emr id” whether that’s the internal or external id to the patient.identifiers array so that we can support a correlation between systems.

Thank you again for your feedback and assistance! Once I have something working I will tag you for review.

**Comment by sjpadgett** [comment]
> * searching for an existing resource
> * send a POST or PUT based on if we have a “result”

I'm thinking that is the way it pretty much has to go.
I merged what I had so far. Currently it is using our custom HTTP client but you may wish to use another. We have symfony dependencies as well as Zend.
I've been mainly using Publish to demo workflows so you may configure how you see fit to make it viable. For now our API credentials are hardcoded but we have it to do yet for public server authentications etc.
 
The PR is #3351 and is already merged.
Thanks for taking this on and let me know how how can help

**Comment by sjpadgett** [comment]
>  private const FHIR_HEADERS = array(
>         "Content-Type" => "application/fhir+json",
>         "Accept" => "application/fhir+json; fhirVersion=4.0",
>         "Prefer" => "return=OperationOutcome"
>     );

I passed over this but, with the oeHTTP client as you can see from client I just merged,  adding asJson() to request will include correct header. However, asJson() builds application/json so if we stay with oeHTTP client, i'll add necessary correct headers as maybe asFhirJson() etc..
This is just easier than defining headers for each use case in code.

**Comment by dixonwhitmire** [comment]
The attached document is a proposal I put together to enhance Open EMR's FHIR publishing feature. We discussed this a bit on the [forum](https://community.open-emr.org/t/project-fhir-integration/13701/32?u=dixonwhitmire).

I'll be submitting PRs against the issue shortly.

**Comment by sjpadgett** [comment]
> I'll be submitting PRs against this as things progress.

Great, anytime.

**Comment by vibinernesto** [comment]
I'm testing the same thing with the open EMR. But getting the same issue mentioned by @dixonwhitmire attached the screenshot
![image](https://user-images.githubusercontent.com/11159009/102206113-1fb69800-3ef2-11eb-8a8e-dcef9efcf23b.png)

Ideally Im expecting OPEN EMR to send a bundle to base FHIR URL with the list of items I've added for the patient and internal ID to be one of the identifier in each resource been sent as a bundle to the FHIR server. Kindly let me know if my understanding is wrong. Or im doing some mistake here
