### ISSUE TITLE
Query Error in Observation Form

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3354]
### Describe the bug

Just confronted a query error in find_code_popup.php

### To Reproduce

1. Open any Encounter 
2. Open 'Observation Form'
3. Click input field 'Code'
4. A popup will showup Select Code type blank (dont select LONIC)
4. Now search blank or sanything & See error

![image](https://user-images.githubusercontent.com/47683556/79018914-9eed1280-7b92-11ea-8380-e554f0db2788.png)

**Comment by adad20** [comment]
hi @yashrajbothra maybe it's because u leave the query blank. Mysql requires return value to insert into the db but it got nothing :)

**Comment by yashrajbothra** [comment]
Yea but that's what bug is :) And as I saw last night I think it should have two code_types and its showing one only. Kindly check this if u are interested.

Thanks :)

**Comment by adad20** [comment]
@yashrajbothra Yes I reproduced it Sorry was working on some other stuff...
@bradymiller If nobody is taking this I wanna dig into it 🙂

**Comment by yashrajbothra** [comment]
Nice :) Green Flag from my side 👍

**Comment by bradymiller** [comment]
hi @adad20 , it is yours :)
