### ISSUE TITLE
Add FHIR Guide to API_README.md

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr#3357]
### Describe the problem
I tried using the OpenEMR FHIR endpoints, and I noticed that even though FHIR  is mentioned in the API docs, there is no instruction on how to turn it on, get an API token, or a list of available resources

### Describe the solution you'd like
Create an FHIR Section, with instruction on how to turn the feature on, Get API token, Plus add resources currently available and their endpoints.
This is really important as FHIR has been gaining interest from Developers within the past weeks.

**Comment by sjpadgett** [comment]
Or create a separate readme.
Are you saying you want this issue?

**Comment by prondubuisi** [comment]
> Or create a separate readme.
> Are you saying you want this issue?

Lol, I need the Issue. Yes.

**Comment by yashrajbothra** [comment]
Yeah, Man! We need this :))

**Comment by prondubuisi** [comment]
On it @yashrajbothra , Long overview.
