### ISSUE TITLE
Determine if there’s anything salvageable in Medmasterpro API

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#336]
http://www.open-emr.org/wiki/index.php/Medmasterpro_API_Review

**Comment by girauch** [comment]
Hello- Do you need a tech writer to help you with documentation? I'm entering the field of tech writing, coming from a user experience background. It would be great to get a few projects under my belt to start a portfolio. Let me know! I'm on LinkedIn (https://www.linkedin.com/in/christinefgiraud/) and my website with resume: www.christinefgiraud.com.
