### ISSUE TITLE
Docs Issue: FHIR_README.md broken

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3366]
### Describe the bug

The FHIR_README.md dev notes and license links seem broken.

https://github.com/openemr/openemr/tree/master/services
https://github.com/openemr/openemr/tree/master/rest_controllers
https://github.com/openemr/openemr/blob/LICENSE

**Comment by bradymiller** [comment]
hi @stu01509 . Good catch. Also need to fix them up for the API_README.md document
The services and rest_controllers can now be found in src/Services and src/RestControllers
And the license section should just be removed completely (all the code is already licensed properly)

**Comment by prondubuisi** [comment]
Hello @bradymiller, Created an issue for the API readme links here https://github.com/openemr/openemr/issues/3361. I wonder how I missed that for FHIR lol. Will be happy to fix both

**Comment by stu01509** [comment]
> Hello @bradymiller, Created an issue for the API readme links here #3361. I wonder how I missed that for FHIR lol. Will be happy to fix both

Go for it, bro 😁

**Comment by bradymiller** [comment]
![tenor (9)](https://user-images.githubusercontent.com/278968/79203211-8af21c80-7def-11ea-9bd3-6b6ef345121b.gif)
