### ISSUE TITLE
Speech Dictation 

### ISSUE THREAD

**Issue by usama-kabel** [openemr/openemr#3369]
### Describe the bug

I read about this feature in openemr community But I didn't have any idea when I test it on openemr demo how it woks?

### Expected behavior
open Speech Dictation
talk
openemr detect what i say

### Client configuration

- Browser: chrome
- Operating system: win 8.1

**Comment by tywrenn** [comment]
Correct me if i'm wrong @sjpadgett @bradymiller , I don't think we have this function. This is something that the clinic I work for actually keeps asking me if we can implement in OpenEMR.

**Comment by sjpadgett** [comment]
I believe all the form does is house the speech to text from an external application like natural speech etc.
There should be some topics on this in forum I believe. Maybe even old issues.

**Comment by bradymiller** [comment]
At this point, external speech applications can be used to transcribe into any text field or document (ie. meaning it can be integrated into anything (including OpenEMR) that has text fields in it). Never been clear why there is a "specific" speech form, since any form can be used.

**Comment by sjpadgett** [comment]
True. maybe at the time, apps were limited to recording into a known flagged location but now we prob should retire it.  unless it was made to take a voice recording for transcription latter. lpn's need something to do don't they?

**Comment by tywrenn** [comment]
bump
