### ISSUE TITLE
add COVID-19 diagnosis code to next patch for production, rel-502

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3377]
### Describe the problem

with the recent addition of the COVID-19 code we should add it to rel-502

### Describe the solution you'd like

add the correct logic to `sql/patch.sql` something like

```
#IfRow icd10dx_order_code dx_id 1
INSERT INTO `icd10_dx_order_code`(`dx_code`, `formatted_dx_code`, `valid_for_coding`, `short_desc`, `long_desc`, `active`, `revision`) select 'U071', 'U07.1', '1', 'COVID-19', 'COVID-19', '1', MAX(`revision`) from icd10_dx_order_code
#EndIf
```

**Comment by bradymiller** [comment]
Problem with above solution is will likely end up in many duplicate active entries for that code (every time the upgrade script is run). May want to consider something like
```
#IfNotRow2D icd10dx_order_code dx_code U071 active 1
```

**Comment by stephenwaite** [comment]
another draft of COVID-18 addition to `sql/patch.sql`
```
#IfNotRow2D icd10dx_order_code dx_code U071 active 1
INSERT INTO `icd10_dx_order_code` (`dx_code`, `formatted_dx_code`, `valid_for_coding`, `short_desc`, `long_desc`, `active`) VALUES ('U071', 'U07.1', '1', 'COVID-19', 'COVID-19', '1')
#EndIf

#IfRow2D icd10dx_order_code dx_code U071 active 1
INSERT INTO `icd10_dx_order_code` (`dx_code`, `formatted_dx_code`, `valid_for_coding`, `short_desc`, `long_desc`, `active`, `revision`) SELECT 'U071', 'U07.1', '1', 'COVID-19', 'COVID-19', '1', MAX(`revision`) from icd10_dx_order_code
#EndIf

**Comment by bradymiller** [comment]
hi @stephenwaite , I think that should work well since it does 2 things.
1. Adds the code if it does not yet exist.
2. If the code already exists (or was added in step 1), it gets assigned the current revision.
Go for placing it in the sql/patch.sql of rel-502 and then I'll include it in patch 2 (am hopefully going to release patch 2 over the weekend)
