### ISSUE TITLE
UI Issue: Register modal button different style.

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3380]
### Describe the bug

Register modal buttons are of different styles.

![image](https://user-images.githubusercontent.com/22230889/79274092-9ec47e00-7ed6-11ea-996c-c465f36328f0.png)

![image](https://user-images.githubusercontent.com/22230889/79274123-abe16d00-7ed6-11ea-9ff3-1bcde4c1b0ac.png)

### Client configuration
- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

**Comment by stu01509** [comment]
Hello @bradymiller 

Follow this comment https://github.com/openemr/openemr/pull/3275, Please assign this issue to me, I will fix it. Thanks 😃

**Comment by bradymiller** [comment]
hi @stu01509 , it's yours :)
