### ISSUE TITLE
using forms in encounters

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3382]
### Describe the problem
there are probably going to be few other issues that pop up due to the current action involved here, see @adad20's [nice work with the fee sheet](https://github.com/openemr/openemr/commit/0ff72b771e192fb98811c69d7f61660085e0d232) that got the ball rolling :basecampy: 

if you choose a form from the forms menu in the encounter, either admininstrative or clinical it opens a new form (except for the fee sheet now !)

![Screenshot from 2020-04-15 11-50-12](https://user-images.githubusercontent.com/5618372/79358507-48276600-7f0f-11ea-96c4-176232d7fcd9.png)

there's probably only a few forms (like procedure order) that are ever created more than once per encounter and could set this up as a global for unique situations that a clinic may have
### Describe the solution you'd like
if one is already open it could either go directly to that form or prompt if you'd like a new one instead

**Comment by adad20** [comment]
hi @stephenwaite When we try to open new form, there should be a prompt for asking a new one for the forms like procedure order.
Or have I did something stupid? 😅

**Comment by stephenwaite** [comment]
hi @adad20, if you click on one of the selections and it's already opened it should open it instead based on a global variable i think. If the global variable is set to ask for opening a new form then it should prompt the alert asking if you'd really like to create another form.

**Comment by adad20** [comment]
hi @stephenwaite Okay now I got it and it will be for every selection other than fee sheet or fee sheet too

**Comment by stephenwaite** [comment]
i also noticed that the a previously selected form retains it's selection prior selection highlight
![Screenshot from 2020-04-15 14-26-05](https://user-images.githubusercontent.com/5618372/79374021-14efd180-7f25-11ea-83d8-1d9cbd5174f6.png)
so i guess the attributes are not getting cleared when clicking on the dropdowns

should i start a separate issue for this?

**Comment by adad20** [comment]
@silvistershebin Yeah we may go for it but I was not able to reproduce it on my system

**Comment by adad20** [comment]
@stephenwaite  Yeah we may go for it but I was not able to reproduce it on my system

**Comment by stu01509** [comment]
Hello @stephenwaite and @adad20 

Do you want to work on this issue? If not I would like to pick this.
Thanks.

**Comment by stephenwaite** [comment]
hi @stu01509 , thank you, are you talking about the main issue in the title? `ease use of forms in encounters` ? or the sub issue that i've noticed with vestigial highlights around previously clicked form?

**Comment by adad20** [comment]
HI @stephenwaite Yeah I was going for the main issue @stu01509 you may go for the second issue of highlights, I will surely ask if I need any help 😊

**Comment by stu01509** [comment]
Hi @stephenwaite 

OK, Please create a new issue and assign to me.
Thank you :)

**Comment by adad20** [comment]
hi @stephenwaite @stu01509 Any idea how can I approach this problem?

**Comment by stu01509** [comment]
Hi @stephenwaite 

Please reassign this issue to me, Thanks.

**Comment by stephenwaite** [comment]
thank you @stu01509

**Comment by stephenwaite** [comment]
bump

**Comment by stephenwaite** [comment]
bump

**Comment by stephenwaite** [comment]
bump
