### ISSUE TITLE
Update jQuery to 3.5.0

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3387]
### Describe the problem

jQuery just got updated. This fixes a vulnerability described here:
https://www.infoq.com/news/2020/04/jquery-35-xss-vulnerability-fix/

### Describe the solution you'd like

Update to 3.5.0

**Comment by tywrenn** [comment]
Anyone wanna take on this issue?

**Comment by stu01509** [comment]
Hello @tywrenn 

Are you working on this issue?
If not I would like to fix it.

**Comment by tywrenn** [comment]
@stu01509 please fix 🙂

**Comment by stu01509** [comment]
Hi @bradymiller sir

Please assign this issue to me, Thanks :)
