### ISSUE TITLE
Warning in the sql_upgrade script 

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr#339]
I've found new error in the sql_upgrade.php..
Here the screenshot -
![image](https://cloud.githubusercontent.com/assets/17809866/20038304/d8fa539a-a439-11e6-90fb-cea0ee3c78f6.png)

Does somebody know what happen?

**Comment by stephenwaite** [comment]
maybe because of the use of the list function https://github.com/openemr/openemr/blob/master/sql_upgrade.php#L75

looks like there's been a change to http://php.net/manual/en/function.list.php moving from php5 to php7

**Comment by stephenwaite** [comment]
it looks like for the global's settings that are nested arrays, substr issues the warning.  here's a fix:
[https://github.com/stephenwaite/openemr/compare/sql_upgr_warn]

**Comment by bradymiller** [comment]
@stephenwaite 
Recommend making the above code a PR (pull request). Let me know if need instructions on doing this.

**Comment by bradymiller** [comment]
Just committed the fix for this to the codebase.
