### ISSUE TITLE
Bump PHPCS standards to PSR12

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr#3394]
### Describe the problem

@stephenwaite  

Write concise description of what feature you want

@stephenwaite

**Comment by sjpadgett** [comment]
@prondubuisi
How much of an impact will this have on current core code i.e Will current source pass PSR12?

**Comment by stephenwaite** [comment]
just changing `ci/phpcs.xml` to
`<rule ref="PSR12">`
results in a huge list of automatic fixes attached
[errors.txt](https://github.com/openemr/openemr/files/4499331/errors.txt)

**Comment by sjpadgett** [comment]
yep what I thought. Don't know if v5.0.3 is where we want to do maybe beginning of v5.0.4 but up to you guys I guess.
Maybe an overnight batch run wouldn't be to bad!

**Comment by bradymiller** [comment]
Looks like minor stuff. Rec pushing a PR with the autocorrections.

**Comment by stephenwaite** [comment]
https://github.com/openemr/openemr/pull/3399
