### ISSUE TITLE
Up-for-grabs Demos Breaking More Often

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3398]
### Describe the bug

I've been seeing more often on the up-for-grabs demos and the dev demos that they aren't responding or not displaying anything.

### To Reproduce
[https://prnt.sc/s2dtg4](https://prnt.sc/s2dtg4)
![image](https://user-images.githubusercontent.com/46497068/79695502-36163200-8245-11ea-92f3-5b09c0e88fb6.png)

Click on any dev demos and most of them aren't working.

### Expected behavior

For it to work correctly

### Client configuration

- Browser: Google Chrome 81.0.4044.113
- Operating system: Windows 10

**Comment by bradymiller** [comment]
Yep, looks like the demo farm blew up on overnight demo resets. Will plan to look into this today.

**Comment by bradymiller** [comment]
demos are back up :)

![tenor (4)](https://user-images.githubusercontent.com/278968/79704646-30314880-8267-11ea-9e25-7789b33347f3.gif)
