### ISSUE TITLE
after completing setup, firefox prompts to save mysql username/pass vs openemr login creds

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3402]
### Describe the bug

https://github.com/openemr/openemr/issues/2870#issuecomment-616227762

### To Reproduce

run a setup locally but not the easy dev :)

complete the setup fields, click next, browser prompts to save wrong credentials (not the app creds)

### Expected behavior

prompts you to save your new login pass for openemr

### Client configuration

- Browser: Firefox 75.0 (64 bit)
- Operating system: Ubuntu 19

**Comment by stephenwaite** [comment]
Here it is @stu01509 , let me know if doesn't capture what I think we were discussing in the link above

**Comment by stu01509** [comment]
Thank you, I will fix it.

**Comment by stu01509** [comment]
Hello @stephenwaite and @bradymiller 

I have an idea ,If we disable remember login info in the setup page, We can prevent browser remember wrong field login info, What do you think, let me know your thought :)

**Comment by stephenwaite** [comment]
sounds fine, thank you @stu01509

**Comment by stu01509** [comment]
Hi @stephenwaite 

Although disable password remember sounds great, Unfortunately, In the modern browser e.g. IE, Edge, Chrome and Chrome will ignore the `autocomplete="off"` config, and then the browser will still offer to remember this login.

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

So, I think we need to change the `setup.php` Database and OpenEMR login input field their's name, It can provide the browser's password manager save correctly account and password. What do you think?

**Comment by stephenwaite** [comment]
even better, thanks @stu01509

**Comment by stephenwaite** [comment]
Fixed
