### ISSUE TITLE
Multiple fee-sheet bug

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3409]
### Describe the bug

Multiple fee-sheet bugs, 

![image](https://user-images.githubusercontent.com/22230889/80035967-80d4ca00-8523-11ea-9ca4-d602760f957c.png)

https://i.imgur.com/DJER21F.mp4

### To Reproduce

1. Open Encounter tab
2. Click Navbar Fees > Payment
3. Click Navbar Fees > Fee Sheet
4. Go to the summary tab
5. Click Click Administrative > Fee Sheet
6. See the two Fee Sheet

### Client configuration

- Browser: Firefox 75
- Operating system: Windows 10

**Comment by stu01509** [comment]
Hello @adad20 

I already created the issue, Do you wanna pick up this issue? If not I will fix it, let me know your thoughts. 

Thank you :)

**Comment by tywrenn** [comment]
To solve this we could just create an entirely new method that gets called before the act of opening a fee sheet is even processed

**Comment by stu01509** [comment]
Hello @bradymiller and @stephenwaite 

Please assign this issue to me, I would like to try to fix it :)

**Comment by adad20** [comment]
hi @stu01509 Maybe the problem lies in `menuActionClick()` in `main -> tabs -> js -> tabs_view_model.js`. Maybe this can help you. 😊

**Comment by bradymiller** [comment]
hi @stu01509 , it is yours :)

**Comment by stu01509** [comment]
> To solve this we could just create an entirely new method that gets called before the act of opening a fee sheet is even processed

**Comment by stu01509** [comment]
Hello @tywrenn 

Thanks for your suggestion, create an entirely new way to handle the encounters tabs sounds like a good idea, I think this way may easy to set the parameters of the tab, such as allow more tabs, or show prompt.

**Comment by stu01509** [comment]
> hi @stu01509 , it is yours :)

Thank you, sir.

**Comment by stu01509** [comment]
Hi @adad20 

Thank you share your experience with me, It would be very useful to me.
Also, Do you mind I fix #3382 this issue, I think #3382 may be related to this issue.
Let me know your thoughts :)

**Comment by adad20** [comment]
hi @stu01509 Yeah you may go for it. I have no issue.

**Comment by adad20** [comment]
Also all the best waiting for some awesome solution🐱‍🏍

**Comment by tywrenn** [comment]
Closed due to this issue being already resolved.
