### ISSUE TITLE
PHP 500 error with the setup.php

### ISSUE THREAD

**Issue by cyriltw** [openemr/openemr#3410]
### Describe the bug

I'm trying to setup the dev version on this repo from scratch and I get an error with a 500 code and the error logs say the following; 

```
[Thu Apr 23 02:44:14.272222 2020] [fcgid:warn] [pid 4564] mod_fcgid: stderr: PHP Warning:  require_once(/home/public_html/vendor/autoload.php): failed to open stream: No such file or directory in /home/public_html/setup.php on line 98
[Thu Apr 23 02:44:14.272258 2020] [fcgid:warn] [pid 4564] mod_fcgid: stderr: PHP Fatal error:  require_once(): Failed opening required '/home/public_html/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/public_html/setup.php on line 98

```

This is the codebase on this branch and on an Ubuntu 16.04 setup. PHP 7.2

**Comment by im-Amitto** [comment]
```
composer install --no-dev
npm install
npm run build
composer dump-autoload -o
```
Have you followed these?

**Comment by tywrenn** [comment]
@cyriltw Ubuntu 16.04 is a dead Operating System at this point as Canonical has stopped it's support and is now vulnerable to attacks. Please update to the new Ubuntu 18.04.4 LTS if you can and see what happens.

**Comment by stephenwaite** [comment]
don't stick a fork in it yet @tywrenn :) it's just not getting hardware updates, it should receive security updates until 2024

![Screenshot from 2020-04-24 18-20-52](https://user-images.githubusercontent.com/5618372/80261460-7536ef80-8658-11ea-8c05-9947f41af764.png)

**Comment by im-Amitto** [comment]
Updated Travis
![Screenshot from 2020-04-25 16-28-23](https://user-images.githubusercontent.com/29653282/80278183-d8d12380-8711-11ea-860e-e9fb8b651ffe.png)

**Comment by tywrenn** [comment]
@stephenwaite I don't trust ESM that's why I stick a fork in it lol
