### ISSUE TITLE
Bring in PHPCBF fixes for OpenEMR

### ISSUE THREAD

**Issue by prondubuisi** [openemr/openemr#3412]
### Describe the bug

The Current OpenEMR codebase with PSR-12 check upgrades leaves some errors that PHPCBF can fix

### To Reproduce
Run PHPCS in current codebase

`docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c '/root/devtools psr2-report'`

### Possible Solution
run 
`docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c '/root/devtools psr2-fix'`

Bring in PHPCBF changes to codebase

**Comment by bradymiller** [comment]
couple more devtools things to consider updating:
-allow both `psr2-report` and `psr12-report` to do the same thing
-allow both `psr2-fix` and `psr12-fix` to do the same thing

**Comment by prondubuisi** [comment]
Hello @bradymiller, I am trying to understand this, how do we support both at the same time, was thinking I should replace  `psr2-report` and `psr2-fix` with  `psr12-report` and `psr12-fix`

**Comment by bradymiller** [comment]
hi @prondubuisi , just being nice to users that still use old command.
Just meaning in the bash conditional to accept either psr2-report or psr12-report

**Comment by bradymiller** [comment]
so this:
https://github.com/openemr/openemr-devops/blob/master/docker/openemr/flex-3.11/utilities/devtools#L15
would turn into this:
```
if [ "$1" == "psr2-report"  ] || [ "$1" == "psr12-report"  ]; then
```

**Comment by bradymiller** [comment]
for the src stuff that Stephen added (lots of work to go on this, so travis is not checking it). could add a block for that:
```
if [ "$1" == "psr12-src-report"  ]; then
    echo "Generating PSR12 code styling error report for src directory "
    cd /var/www/localhost/htdocs/openemr
    php -d memory_limit=640M /root/.composer/vendor/squizlabs/php_codesniffer/bin/phpcs -n --extensions=php,inc --standard=ci/phpcs_src.xml --report=full src/
fi
```
(this is very strict PSR2 checking on the src directory, where goal is for that to be PSR12 fully compliant at some point)
