### ISSUE TITLE
Setup.php - suggestion

### ISSUE THREAD

**Issue by im-Amitto** [openemr/openemr#3414]
### Describe the bug

write a concise description of what the bug is.

### To Reproduce
Initiate the openemr setup

I think we should highlight the current value with red when they are not meeting the required criteria.
![Screenshot from 2020-04-23 18-28-45](https://user-images.githubusercontent.com/29653282/80102507-71d83100-8590-11ea-831b-297652d2f8ab.png)

- Browser: Chrome
- Operating system: Ubuntu 18.04
Tags: goodFirstIssue

**Comment by im-Amitto** [comment]
This little buddy can also use some bootstrap or selected theme-based style
![Screenshot from 2020-04-23 18-32-28](https://user-images.githubusercontent.com/29653282/80102736-d3989b00-8590-11ea-9a8e-744b1c04e661.png)

**Comment by stu01509** [comment]
Hello @bradymiller 

I would like to improve it, Please assign this issue to me.

**Comment by bradymiller** [comment]
hi @stu01509 , go for it :) -brady
