### ISSUE TITLE
Abandoned package in use

### ISSUE THREAD

**Issue by im-Amitto** [openemr/openemr#3418]
It's not my area of expertise but this gives an unsettling feel.
 ![Screenshot from 2020-04-25 00-13-51](https://user-images.githubusercontent.com/29653282/80246252-b85d8680-8689-11ea-9777-3da566500a24.png)

![Screenshot from 2020-04-25 00-20-16](https://user-images.githubusercontent.com/29653282/80246774-9b758300-868a-11ea-91e8-06e7a5531b0a.png)

**Comment by tywrenn** [comment]
I've got a fix for this -- leave it to me :)

**Comment by tywrenn** [comment]
Nevermind -- even after updating composer some of the packages we use are still using it (about 3 or so), so we can't really avoid this.

**Comment by tywrenn** [comment]
Closed as is currently unavoidable at this time and/or was already resolved.
