### ISSUE TITLE
jquery 3.5.0 temp revert to 3.4.1 until 3.5.1 is released

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3425]
I noted that the Adminstration->Coding->External Data Loads was completely broken, which is secondary to following issue:
https://github.com/jquery/jquery/issues/4665

At this point only option is to downgrade jquery version to 3.4.1 and then wait for 3.5.1 to get released.

**Comment by tywrenn** [comment]
Yeah if hasOwnProperty is used at all you should just downgrade until it's fixed

**Comment by bradymiller** [comment]
Done. Now just gotta wait for 3.5.1 to be released.

**Comment by tywrenn** [comment]
@bradymiller 3.5.1 has released now
https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/
