### ISSUE TITLE
Use of stylelint in SCSS and CSS

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3426]
### Describe the problem

Our CSS/SCSS code has issues relating to having two of the same declaration, not being formatted well, or just being coded incorrectly.

### Describe the solution you'd like

In a new effort to curb these issues and to help us out with GSoC, I'm proposing the addition of stylelint to our SCSS and CSS classes. Stylelint is a lot like php codesniffer in that it checks for syntax issues under a rule standard that you specify. This can also be executed in Travis CI and run in the [Atom IO Editor](https://atom.io/packages/linter-stylelint). 

For the base of editing the SCSS and CSS files, we must use both the standard rule config and the `stylelint-config-sass-guidelines` rule config to allow SCSS fixes to run.

Docs: [https://stylelint.io/user-guide/get-started](https://stylelint.io/user-guide/get-started)

Steps to implementing:

1. Install stylelint
2. Run auto-fix on all CSS/SCSS files
3. Fix any code-breaking issues after the auto-fix
4. Turn off rules that aren't gonna work for the code in the config file
5. Enable in Travis CI (after merging pull)

**Comment by stephenwaite** [comment]
nice @tywrenn, looks like here's a setup article for folks with the openemr licensed phpstorm
https://www.jetbrains.com/help/webstorm/using-stylelint-code-quality-tool.html#
