### ISSUE TITLE
Snackbar

### ISSUE THREAD

**Issue by im-Amitto** [openemr/openemr#3430]
Adding a snack bar/toast message is a great idea to show notifications.
Currently, the only way one gets to know that the operation is done is by seeing a page redirect/reload or a alert.
![](https://user-images.githubusercontent.com/311619/41921075-50bd6026-7962-11e8-9360-8cecbd5ebde5.gif)

**Comment by tywrenn** [comment]
This seems like a project that will take awhile (i don't even know how many alerts we have implemented in the system). If we were to do this it would have to be something uniformly added to the system.

**Comment by im-Amitto** [comment]
@tywrenn It's easy to add and can be converted into a single method which can be added in utility for people to use but getting the uniformity is gonna be a tough task.

**Comment by bradymiller** [comment]
Quick point on provider flow (not sure if helpful on this). Provider's generally see patient's and do clinical work most of day. Then when have downtime, check messages(ie. alerts), throughout the day and work on those. It's nice to know how many there are on a quick glance, but don't need to really need to know anything else. If there is an urgent issue, then a live person will track down and find the provider.

**Comment by tywrenn** [comment]
Since this feature doesn't seem like it will do much, i'm closing this.
