### ISSUE TITLE
wkhtmltopdf (UB04 in billing) doesn't work in docker

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3435]
### Describe the bug

after enabling `Activate UB04/837I Claim Support` in Globals, when you goto generate the UB04 form from billing manager an error is generated, caught, and displayed to the user
```
The exit status code `127` says something went wrong: stderr: `sh: /var/www/localhost/htdocs/openemr/vendor/openemr/wkhtmltopdf-openemr/bin/linux/wkhtmltopdf64-linux: not found ` stdout: `` command: /var/www/localhost/htdocs/openemr/vendor/openemr/wkhtmltopdf-openemr/bin/linux/wkhtmltopdf64-linux --grayscale --lowquality --margin-bottom `0in` --margin-left `0.19in` --margin-right `0.19in` --margin-top `0.15in` --orientation `Portrait` --page-size `Letter` --no-outline --keep-relative-links --print-media-type --zoom `1.045` `/var/www/localhost/htdocs/openemr/sites/default/documents/temp/knp_snappy5ea600bddfb748.19100293.html` `/var/www/localhost/htdocs/openemr/sites/default/documents/temp/knp_snappy5ea600bddfbce7.12955920.pdf`
```
error log has this
```
[Sun Apr 26 21:44:29.915387 2020] [php7:warn] [pid 610] [client 172.18.0.1:35882] PHP Warning:  chmod(): No such file or directory in /var/www/localhost/htdocs/openemr/src/Pdf/PdfCreator.php on line 48, referer: http://localhost:8300/interface/billing/billing_report.php
```

### To Reproduce
1. Add a user, encounter and put an item on the fee sheet and save
2. Click on Fees->Billing Manager
3. Delete all filters and Update list
4. Select encounter and generate UB04 form

### Expected behavior

succesfully download UB04 form

**Comment by stephenwaite** [comment]
for the pull request can envision adding the wkhtmltopdf to the docker

if it's done with composer may be able to remove 
```
   "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/openemr/wkhtmltopdf-openemr"
        }
    ],
```
and replace with `composer require mikehaertl/phpwkhtmltopdf`
https://github.com/mikehaertl/phpwkhtmltopdf

**Comment by bradymiller** [comment]
The problem with wkhtmltopdf package is it needs binaries to run (thus each OS needs it's own binaries, for example alpine is different from ubuntu), for example:
https://github.com/mikehaertl/phpwkhtmltopdf#installation-of-wkhtmltopdf

I think the end conclusion is we need to migrate this to mPDF:
https://community.open-emr.org/t/project-standardize-pdf-tools/13705/9
(@sjpadgett felt this would be tough in a post in that thread, but as I recall in a subsequent correspondence he felt it made sense to try to get away from wkhtmltopdf)

**Comment by boxlady** [comment]
I went down this rabbit hole. Wkhtmltopdf is no longer being updated... I
think I posted about it on the forms

**Comment by boxlady** [comment]
Hit enter to soon.  Sorry . Here is a link

https://community.open-emr.org/t/ub04-support-wkhtmltopdf-not-working/13119/3?u=julie_b

**Comment by sjpadgett** [comment]
I updated the binaries for linux. Alpine support was never considered to be supported. If somebody wants it, they can compile a version for Alpine.
For mPDF well nuts:) When I brought mPDF into openemr, I had high hopes because they claimed to to be working on absolute positioning. Turns out, not so true. They only support block and not nested elements.

The UB04 form itself is a Pdf representation (html) which uses absolute positioning overlaid over a svg image. mPdf will not work unless someone wants to modify mPdf to convert absolute to relative poisoning on the fly. Still, if somebody had the mind, the form could possibly be converted.

**Comment by bradymiller** [comment]
bump

**Comment by bradymiller** [comment]
bump

**Comment by bradymiller** [comment]
bump

**Comment by bradymiller** [comment]
bump

**Comment by stephenwaite** [comment]
bump
