### ISSUE TITLE
Facility Information is not saving

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#3437]
Hi..
I am on windows 10, using xampp 7.4 version php. I have the development version of openemr 5.0.3 running. I tried creating a seperate database for another clinic using the multisite function and all went well. 

In the fresh database, I was trying to change the facility name from "Your Clinic Name Here" to something else and trying to save the data, but everytime nothing was saving in the database. Finally i had to insert it into the database directly to show up the data.

This is happening in both chrome and firefox.

The error log is here - 

[Mon Apr 27 19:36:30.285203 2020] [php7:notice] [pid 5348:tid 1868] [client ::1:58988] PHP Notice:  Undefined variable: facility in C:\\xampp\\htdocs\\openemr\\interface\\usergroup\\facilities_add.php on line 245, referer: http://localhost/openemr/interface/main/tabs/main.php?token_main=z8Cz7z2ssbpD14nGE6Uqn2qWHwyJbNxXHDRYLtHE

Kindly help

Dr. Arnab Naha

**Comment by bradymiller** [comment]
I confirmed this bug. Basically, nothing is being saved when trying to Edit Facilities. It appears the Save button just closing the modal and nothing else:

![image](https://user-images.githubusercontent.com/278968/80442542-f80eb300-88c1-11ea-962d-d4b85c34346b.png)

**Comment by arnabnaha** [comment]
Thanks Brady

**Comment by yashrajbothra** [comment]
@bradymiller  Can I Pick it up?

**Comment by arnabnaha** [comment]
please take it and fix it please..thanks

**Comment by yashrajbothra** [comment]
_GIT Blame - https://github.com/openemr/openemr/commit/4458e4a70979f4dd6db9dc6554dd49b437150f05_

I guess while Extending `BaseService` class in FacilityService Jerry Sir forgot to push id to the query.
I will push the Quick Fix in Couple of minutes 👍

**Comment by stephenwaite** [comment]
you got it @yashrajbothra , nice find and fix, thank you
