### ISSUE TITLE
SQL error when try to create a duplicate list

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3445]
### Describe the bug

SQL error when try to create a duplicate list

### To Reproduce

Administration > Lists > New List

Create a list with a name that already exists

In OpenEMR:
"Query Error
ERROR: query failed: INSERT INTO list_options ( list_id, option_id, title, seq, is_default, option_value ) VALUES ( 'lists', ?, ?, ?, '1', '0')
Error: Duplicate entry 'lists-Payment_Type' for key 'PRIMARY'
.../interface/super/edit_list.php at 241:sqlStatement

In Apache error log:

"SQL Error with statement:query failed: INSERT INTO list_options ( list_id, option_id, title, seq, is_default, option_value ) VALUES ( &#039;lists&#039;, ?, ?, ?, &#039;1&#039;, &#039;0&#039;)--Duplicate entry &#039;lists-Payment_Type&#039; for key &#039;PRIMARY&#039;==&gt;.../interface/super/edit_list.php at 241:sqlStatement, referer: .../interface/super/edit_list.php"

### Expected behavior
Error dialog

### Client configuration

OpenEMR 5.0.2.1 on Debian

**Comment by consolticaemr** [comment]
Yes It is the default behavior in my opinion. The table you are trying to refer and insert the data has a constraint for your entry and cant be duplicated, you might want to rename it. If you still want this to be done then you need to drop the primary constraint for the ```list_options``` table which will give you unexpected results.

**Comment by pete-boyd** [comment]
@consolticaemr I think you miss my point, the issue I am reporting is not that I cannot add a list with the same name, but that there is no human readable error message when I try to do so.

**Comment by sjpadgett** [comment]
i'll look this over

**Comment by sjpadgett** [comment]
@pete-boyd This will be in patch 4
