### ISSUE TITLE
Upgrade EncounterService

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3454]
### Describe the feature

Upgrade `EncounterService` class to support New Validator and Create Unit Test for the same.

**Write a concise description of the problem**

My further goal is to support unit tests for our FHIR resources services so that the development process becomes easier

**Comment by yashrajbothra** [comment]
Hey, Ser @sjpadgett I was working on this and saw something strange!
https://github.com/openemr/openemr/blob/d6afe5bb574a3a7d97659467a9068b48222c59b4/src/Services/EncounterService.php#L324
`aclCheckCore` is not working for API call.
I think it related to auth which we had discussed earlier but right now its causing issue in this particular function.

**Comment by sjpadgett** [comment]
> I think it related to auth

Nothing wrong with Authentication. PatientServices however, broken! Encounters works for me...

**Comment by yashrajbothra** [comment]
I was using `PUT http://localhost:8081/openemr/apis/api/patient/:pid/encounter/:eid` and it returned
**"You are not authorized to see this encounter."**

![image](https://user-images.githubusercontent.com/47683556/80909010-4993c380-8d42-11ea-8b9a-ea7974957e18.png)

Am I missing something here?

**Comment by sjpadgett** [comment]
hmm, ensure you have correct user permissions set. including the provider flag.
i'm trying to test some more today and have portal login to look at. also ensure correct acl set in route.

**Comment by sjpadgett** [comment]
@yashrajbothra 
![image](https://user-images.githubusercontent.com/1859985/80914588-6a482300-8d1a-11ea-9348-abab49e68f52.png)

**Comment by sjpadgett** [comment]
Did you verify the User settings you are using for api?
Note Provider and Active flags. Also ACL permissions.
![image](https://user-images.githubusercontent.com/1859985/80915857-d6c72000-8d22-11ea-8bfc-1983d6e591f2.png)

**Comment by yashrajbothra** [comment]
![image](https://user-images.githubusercontent.com/47683556/80915990-71e7e600-8d73-11ea-8705-460ab02b451e.png)

Looks Fine from here 🤔  ?

**Comment by sjpadgett** [comment]
How is it you haven't a last name unless you removed for posting?

**Comment by yashrajbothra** [comment]
Don't you think it's strange not have this setting here ⬇️ 
![image](https://user-images.githubusercontent.com/47683556/80916068-0a7e6600-8d74-11ea-9658-b227d0a8971c.png)

Before this point, I just thought we don't have something to change a user details😅

**Comment by yashrajbothra** [comment]
> How is it you haven't a last name unless you removed for posting?

Yea I was trying to change that but some red words are coming my way :)

**Comment by sjpadgett** [comment]
> Don't you think it's strange not have this setting here

I don't understand what you mean here!

**Comment by yashrajbothra** [comment]
> > Don't you think it's strange not have this setting here
> 
> I don't understand what you mean here!

![image](https://user-images.githubusercontent.com/47683556/80916273-48c85500-8d75-11ea-894f-ebc1fa02152f.png)

I can't see those user setting inside this Setting tab 
Because it also says **Edit User Setting** so in general user will expect to have something to edit name and stuff here too :(

**Comment by sjpadgett** [comment]
@yashrajbothra I've recreated. ARO for sensitivity is not working. You can change encounters sensitivity to None to get to work.

Since when do we not allow super for admin. this makes no sense to me:

// Superuser always gets access to everything.
        if (($section != 'admin' || $value != 'super') && self::aclCheckCore('admin', 'super', $user)) {
            return true;
        }

**Comment by yashrajbothra** [comment]
@sjpadgett  Did you mean `NULL` because that worked :)
AND its just workaround and not a solution right?

**Comment by sjpadgett** [comment]
NULL or "". Setting in encounter to None results in "".
I don't know why Normal or High sensitivity doesn't work. @bradymiller any idea. In encounters High requires Admin and/or Patient. It is prob implemented wrong in API so you might want to look encounter form over to see how it implemented there!

**Comment by bradymiller** [comment]
It appears to be testing well in non-API mode (all sensitivities work for the admin user). It appears api is not setting $_SESSION['authUser'] which is needed for the standard acl calls to work. so any code that does standard acl checks after the initial RestConfig::authorization_check will not work.

**Comment by bradymiller** [comment]
ie. we have a systemic bug that needs fixing :)

**Comment by yashrajbothra** [comment]
> It appears to be testing well in non-API mode (all sensitivities work for the admin user). It appears api is not setting $_SESSION['authUser'] which is needed for the standard acl calls to work. so any code that does standard acl checks after the initial RestConfig::authorization_check will not work.


Ya, That's where I thought its a problem with authorization :)

**Comment by bradymiller** [comment]
Things to consider for this solution:
1. After the token is authenticated, then consider populating $_SESSION['authUser'] with username
2. Consider removing the else part of the code in _rest_config.php authorization_check function and then removing not needed aclCheck function in AuthRestController function

**Comment by yashrajbothra** [comment]
Sorry, but this issue wasn't meant to go on that direction is it okay to discuss here or open a new issue?

**Comment by bradymiller** [comment]
rec a new issue

**Comment by sjpadgett** [comment]
> 1. After the token is authenticated, then consider populating $_SESSION['authUser'] with username

At one time these were set. Need to prob do both $_SESSION['authUser'] and $_SESSION['authUserID']
They will come up somewhere else i'm sure.
