### ISSUE TITLE
Layout Issue 

### ISSUE THREAD

**Issue by tammbamm5** [openemr/openemr#3455]
With this new EMR update, I cannot keep my layout as the "Frame" layout that I like. It doesn't let me click on the calendar unless I change it to the "Tabs" setting for the layout. 
Is there a way to fix this???

**Comment by stu01509** [comment]
Hello @tammbamm5 

Can you take a screenshot or screen recording? I need more detail to approach this issue.
Thank you.

**Comment by stephenwaite** [comment]
sorry frames were [dropped last year](https://community.open-emr.org/t/drop-frames-support/11768/30?u=stephenwaite) so need to incorporate old functionality in tabs by starting an issue and hope a developer picks it up as worthwhile addition to the community

like was done for #2810

**Comment by tammbamm5** [comment]
Also another account will not let me change from frame to tabs on the settings. There's absolutely no layout settings when I click on settings.

**Comment by tammbamm5** [comment]
![Uploading Screen Shot 2020-05-01 at 10.52.43 AM.png…]()
