### ISSUE TITLE
Suggestion : Dropdown item should open while hovering 

### ISSUE THREAD

**Issue by adad20** [openemr/openemr#3456]
### Describe the bug
In the `View past encounter` button the drop-down item should pop up while hovering over the button for better UI experience.

### To Reproduce
![Screenshot (156)](https://user-images.githubusercontent.com/55142272/80795605-8e8cee00-8bba-11ea-842b-a58c9786ace6.png)

### Expected behavior

No overlap of items

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

**Comment by adad20** [comment]
I want to work on this. 😊

**Comment by stephenwaite** [comment]
nice spot, it's yours @adad20, thank you

**Comment by adad20** [comment]
hey @stephenwaite  where should I place the css file, seeing all the css files is overwhelming 😅

**Comment by sjpadgett** [comment]
> where should I place the css file
rec interface/themes/core

**Comment by sjpadgett** [comment]
Sorry @adad20 
Above perhaps not best place maybe interface/themes/ with other css's. Also patient data should have some styles somewhere in existing scss or css file. take a look.

**Comment by adad20** [comment]
@sjpadgett Sure I will take a look actually I have put the css inside the php file itself which may not be the best practice
