### ISSUE TITLE
"Create New Patient" button should be at bottom not top

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3458]
On the "Search or Add Patient" screen, "Create New Patient" should be at the bottom of the screen, not at the top, because it is the button you select having gone through the screen from top to bottom completing the form.

OpenEMR 5.0.2.1

**Comment by stu01509** [comment]
Hello @pete-boyd 

Can you take a screenshot? I would like to fix this issue.

**Comment by sjpadgett** [comment]
he prob means:
![image](https://user-images.githubusercontent.com/1859985/80806972-fbd45b00-8b89-11ea-8ea4-b1a813d4b7af.png)

It's yours

**Comment by pete-boyd** [comment]
Yeah that's the one, thanks.

**Comment by stu01509** [comment]
Hello @bradymiller, @sjpadgett, @tywrenn, and @pete-boyd 

I also change the **Create New Patient** button's color to `btn-primary`.
What do you think?

![image](https://user-images.githubusercontent.com/22230889/80807813-b5661700-8bf0-11ea-9739-92a938eb3e34.png)

**Comment by pete-boyd** [comment]
I think ideally that page shouldn't even include a search feature, it's confusing that it provides for two different functions. Search can be achieved using the Patient Finder at Patient/Client > Patients. But that's another bug, wider in scope than this bug.

**Comment by stephenwaite** [comment]
hi @pete-boyd
>Search can be achieved using the Patient Finder at Patient/Client > Patients.

the search in the `Search or Add Patient` is a more thorough search though since it can look at any of the fields displayed

**Comment by mdsupport** [comment]
Key hallmark of good user interface is consistency.  That means after performing 2-3 transactions every user realizes the pattern without going through training or documentation for each screen.

@stu01509, please do a favor to future developers and implement this as a ui class.  One option would be a fixed navbar with form title on left and allow model part of the script to insert specific elements - e.g. buttons, dropdowns for settings etc.  Finally view/html part of the script can call the render method to place the code.

**Comment by stu01509** [comment]
Hello @mdsupport 

I think it is a good idea, But OpenEMR has a lot of buttons and buttons style.
e.g. some button used `btn-group`, `btn-link` CSS style, and each button have their style, It is not easy to implement completely function or class. I suggest doing later after we refine all pages.
