### ISSUE TITLE
Settings issue 

### ISSUE THREAD

**Issue by tammbamm5** [openemr/openemr#3460]
My account needs to be switched from the "Frame" layout to the "Tabs" layout since the Frame layout doesn't work anymore but when I click settings, there are no layout settings. 
![Screen Shot 2020-05-01 at 10 55 08 AM](https://user-images.githubusercontent.com/64621231/80823665-4958c400-8b9a-11ea-9e0d-3a5d7eb4d458.png)

**Comment by stephenwaite** [comment]
try chome or firefox instead of safari please

**Comment by tammbamm5** [comment]
We have tried different browsers and it hasn't worked.

**Comment by stephenwaite** [comment]
ok, did you click on the cog in the upper right and changed to `Tabs`, clicked save and logged out and back in?

**Comment by tammbamm5** [comment]
The settings button doesn't work at all. It's like the home button and settings button are the same screen.

**Comment by stephenwaite** [comment]
might be the cache, would def use Chrome or Firefox and clear the cache

btw what if you changed it globally, ie all users to `Tabs`? `Administration->Globals->Appearance`

**Comment by tammbamm5** [comment]
I've tried it on different computers and different browsers.

**Comment by sjpadgett** [comment]
I'd like to help but this is to weird!
Did your upgrade complete okay?
Did you run sql_upgrade.php from browser?

**Comment by tammbamm5** [comment]
I have no idea when the system updated. I'm not sure how to even upgrade it. I'm an administration for an agency that uses EMR. But if you tell me how to trouble shoot it, I will do it.

**Comment by sjpadgett** [comment]
Can you get to About ie ? I believe?

**Comment by tammbamm5** [comment]
I can click on the about tab but the settings doesn't pop up

**Comment by stephenwaite** [comment]
what's the version # in the about tab?
![Screenshot from 2020-05-01 16-49-43](https://user-images.githubusercontent.com/5618372/80840674-c6506180-8bcb-11ea-9b7b-8ab4547362c9.png)

**Comment by tammbamm5** [comment]
It is the same version. We are still having issues and cannot access the settings

**Comment by sjpadgett** [comment]
@tammbamm5 
I fear the last upgrade is corrupt. Do you know if the sql_upgrade.php script was run after file upgrade?

i.e https://yourdomian/openemr/sql_upgrade.php?site=default

**Comment by tammbamm5** [comment]
I'm not sure what that means. 
I tried to click on that link you send me but it says that it cannot be reached.

**Comment by sjpadgett** [comment]
Recommend you contact the person that did your upgrade and speak with them. Must have been done within past few days if you are showing from About
![image](https://user-images.githubusercontent.com/1859985/80997935-1ae41e80-8e10-11ea-86b1-8009972d8ea1.png)

**Comment by sjpadgett** [comment]
@tammbamm5 Is this still an issue?
