### ISSUE TITLE
UI Issue: Navbar dropdown item arrow

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3466]
### Describe the bug

Navbar dropdown item has two style arrows(down, right)
It looks very strange.

![image](https://user-images.githubusercontent.com/22230889/80853488-fa776100-8c63-11ea-96e8-2fea46c443a7.png)

### To Reproduce

1. Hover on navbar item.

### Expected behavior
Only one arrow style.

### Client configuration

- Browser: Firefox 75
- Operating system: Windows 10

**Comment by adad20** [comment]
Hi @stu01509 Are you working on this? If not I want to take this

**Comment by stu01509** [comment]
> Hi @stu01509 Are you working on this? If not I want to take this

Yes, I am working on this.

**Comment by yashrajbothra** [comment]
Wow, I was just about to post this issue😃.
Anyways Thanks @stu01509  👍

**Comment by tywrenn** [comment]
@stu01509 This happens when you don't clear ur browser cache as I've figured out

**Comment by stu01509** [comment]
Hi @tywrenn 

Is it a browser cache issue? I try to clean the cache but it still has two arrows.

**Comment by tywrenn** [comment]
@stu01509 Hmm. In order to fix this, you would have to remove the `dropdown-toggle` class as it is used there. Then you have to find the CSS that overrode that code originally.

**Comment by stu01509** [comment]
@tywrenn Thanks for your explanation, I found the file.

**Comment by stephenwaite** [comment]
hi @stu01509 , am not seeing this on the dev demos
https://www.open-emr.org/wiki/index.php/Development_Demo#With_demo_data

**Comment by stu01509** [comment]
Hello @stephenwaite 

Aren't you seeing this issue?

**Comment by stephenwaite** [comment]
hi @stu01509 , no, do you see it on the demos?

**Comment by stu01509** [comment]
Hello @stephenwaite 

No, I'm not seeing in the demo site, But @yashrajbothra  and @adad20  they also faced the same problem, I will try to clone the new project and reproduce it.
