### ISSUE TITLE
Sponsor Button in this Repository

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3471]
### Describe the problem

I think we are missing a sponsor button in this repo

### Describe the solution you'd like

Adding a sponsor button in this repository
https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

**Comment by stephenwaite** [comment]
thanks @yashrajbothra , can probably start with https://opencollective.com/openemr

**Comment by yashrajbothra** [comment]
https://github.com/yashrajbothra/openemr/commit/99fdc823dee61c3637c747b175d00f5dfe5de0ba
I tried this in my fork but it seems it will only work in the original repo 👍

**Comment by stephenwaite** [comment]
right @yashrajbothra , something admins have to do, sorry for confusion, thank you

**Comment by bradymiller** [comment]
done :)
