### ISSUE TITLE
Encounters Summary not scroll

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3472]
Counts document as encounter. e.g 7 encounters but displays first seven documents if available!
![image](https://user-images.githubusercontent.com/1859985/80892520-cc604400-8c98-11ea-9b3d-ce3fbe3446ff.png)

**Comment by bradymiller** [comment]
I wonder if the changes here caused this:
https://github.com/openemr/openemr/pull/3400/files

**Comment by sjpadgett** [comment]
> I wonder if the changes here caused this:

Yeah that'd do it.

**Comment by stu01509** [comment]
Oops! I didn't notice add the `style="overflow-y: hidden;"` will cause this problem.
Should I create another PR to fix #2892?

**Comment by bradymiller** [comment]
hi @stu01509 , Go for it. I'll do a quick revert in the codebase to fix this issue.
