### ISSUE TITLE
Unexpected response from ACL in Encounter API 

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3474]
Hey, Ser @sjpadgett I was working on this and saw something strange!
https://github.com/openemr/openemr/blob/d6afe5bb574a3a7d97659467a9068b48222c59b4/src/Services/EncounterService.php#L324
`aclCheckCore` is not working for API call.
I think it related to auth which we had discussed earlier but right now its causing issue in this particular function.

_Originally posted by @yashrajbothra in https://github.com/openemr/openemr/issues/3454#issuecomment-623004390_

**Comment by yashrajbothra** [comment]
ie. we have a systemic api bug that needs fixing :)

Originally posted by @bradymiller in #3454 (comment)

**Comment by yashrajbothra** [comment]
Things to consider for this solution:
1. After the token is authenticated, then consider populating $_SESSION['authUser'] with username
2. Consider removing the else part of the code in _rest_config.php authorization_check function and then removing not needed aclCheck function in AuthRestController function

_Originally posted by @bradymiller in https://github.com/openemr/openemr/issues/3454#issuecomment-623153506_

**Comment by yashrajbothra** [comment]
> 1. After the token is authenticated, then consider populating $_SESSION['authUser'] with username

At one time these were set. Need to prob do both $_SESSION['authUser'] and $_SESSION['authUserID']
They will come up somewhere else i'm sure.

_Originally posted by @sjpadgett in https://github.com/openemr/openemr/issues/3454#issuecomment-623154789_

**Comment by sjpadgett** [comment]
It may be time to develop new authentication/authorization scheme for applications. Needed for mobile os's anyway so, maybe i'll bite the bullet and get it done.
Yash go ahead and fix the session cookie as we're going to support two credential modes. I'll assign us to this and i'll work new auth.

**Comment by bradymiller** [comment]
I'm also happy to do the quick fix needed for this specific issues, which will allow us to get rid of a unnecessary function (and potentially make the new auth scheme easier to sort out).

**Comment by sjpadgett** [comment]
Sure @bradymiller , do your magic.

**Comment by yashrajbothra** [comment]
> Yash go ahead and fix the session cookie as we're going to support two credential modes. I'll assign us to this and i'll work new auth.

Hey, @bradymiller your PR include session cookie fix?

**Comment by bradymiller** [comment]
hi @yashrajbothra , hopefully I didn't miss anything. what is the session cookie bug?

**Comment by bradymiller** [comment]
This autoclosed with the fix I just brought in. Let me know if it needs to be reopened.
