### ISSUE TITLE
EOB Posting issue

### ISSUE THREAD

**Issue by tammbamm5** [openemr/openemr#3478]
I cannot search for an invoice under the EOB posting option. 
I need to be able to send these to clients who need to pay their bills or who need to get reimbursed from their insurance company. 
Please help! There's been so many bugs since the last update. 
Also, if anyone can look at my last post and help me figure out that as well. 
Thank you

**Comment by stephenwaite** [comment]
hi @tammbamm5 , can't confirm this on the demo at https://seven.openemr.io/f/openemr/interface/login/login.php?site=default
