### ISSUE TITLE
Cannot switch off employer section in patient demographics

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3480]
### Describe the bug
In OpenEMR 5.0.2.1 on Debian, Administration > Globals > Omit Employers ("Omit employer information in patient demographics") doesn't have any effect

### Expected behavior
Search or Add Patient should no longer contain an "[ ] Employer" section.

There's nothing in the Apache error log

**Comment by stephenwaite** [comment]
good pt @pete-boyd , it's only been implemented when editing patient demographics so far.
