### ISSUE TITLE
Add Test Data Easy Docker Dev Tool

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3485]
### Describe the problem

As a developer, there are multiple features of OpenEMR that are available. Only one small problem -- i'm not a doctor. So when it comes to testing essential functionality such as NationNotes and other features, I don't have a dedicated checklist to go over to make sure everything is working.

### Describe the solution you'd like

The up-for-grabs environments have this feature where it installs test data into the EMR so people can test functionality. I was wondering if that can be implemented as an easy docker dev tool as a functionality checker. I was also wondering if we could make a "checklist for functionality" so when we do create pull requests we can be certain that they won't break the EMR.

**Comment by sjpadgett** [comment]
Also expand the datasets

**Comment by tywrenn** [comment]
@bradymiller dunno how to do this and don't wanna mess anything up -- can u or someone fix this issue?

**Comment by bradymiller** [comment]
The up for grabs mechanism of sample data does the following:
1. Wipes the database and brings in schema from 5.0.0 with sample data in it
2. Then runs the sql upgrade scripts

To get to a solution that bodes well for development probably means first getting this issue completed (then would have the "pieces" necessary to bring in sample data either via the up for grabs scorched earth approach or via a more directed approach using api/synthea):
https://github.com/openemr/openemr-devops/issues/243

**Comment by bradymiller** [comment]
@tywrenn , The easy dev docker now can bring in the same demo data that is used on the online demos :)
https://community.open-emr.org/t/openemr-flex-docker-updated/12051/59

**Comment by tywrenn** [comment]
@bradymiller Yayyyyy 🙂🙂🙂 closing this now

**Comment by bradymiller** [comment]
btw, another nice thing about the demodata feature on the dev docker is it allows developers to test their changes in the sql upgrade script.

**Comment by tywrenn** [comment]
@bradymiller reopening this as the script fails in docker compose

**Comment by tywrenn** [comment]
@bradymiller Never mind, you do however need to remove the flex docker image in order to update the flex docker.
