### ISSUE TITLE
Portal ACL broken 5.0.3 and 5.0.2

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3486]
- Rest URI such as patient/10 refers to Id and not pid.
https://github.com/openemr/openemr/blob/78bf091db7aa3e4e7dbc9cc1f3897874132e0e70/portal/patient/fwk/libs/verysimple/Phreeze/GenericRouter.php#L132
- api/onsiteportalactivities is how templates are stored/retrieved needs p_all
https://github.com/openemr/openemr/blob/78bf091db7aa3e4e7dbc9cc1f3897874132e0e70/portal/patient/fwk/libs/verysimple/Phreeze/GenericRouter.php#L97

**Comment by bradymiller** [comment]
Looks like we are heading for patch 3 soon :)

**Comment by bradymiller** [comment]
Just to help with org of this fix, the pertinent commit is here:
https://github.com/openemr/openemr/commit/093777d2a9543381b0f36e5a96b6ec8f559275d6

**Comment by sjpadgett** [comment]
I don't know Brady, sometimes we just can't catch a break!

**Comment by sjpadgett** [comment]
@bradymiller Are you working this or am I?
If you're not then i'll take a stab. I just don't want to dup efforts.

**Comment by bradymiller** [comment]
I've been analyzing it and think have a quick potential solution for item 1
(the id/pid issue). Also have a plan for item 2, but will require more
time/work. Plan to try out plans this evening and hopefully have initial PR
this evening.

**Comment by sjpadgett** [comment]
I have a fix. We really don't need to parse uri's for routes and pid. Pid will be query strings and not embedded in rest calls. You had it in index.php.

**Comment by bradymiller** [comment]
Don't we still need to account for a patient that tries to run a patient
endpoint with an id in it that is not the patient's though?

**Comment by sjpadgett** [comment]
id is unique to pid
![image](https://user-images.githubusercontent.com/1859985/81339967-048eca80-907d-11ea-9000-58419c26cd0e.png)

Unless i'm missing a point somewhere.

**Comment by sjpadgett** [comment]
Don't get me wrong. I think adding the acl to json routes is clever and may still prove useful.
