### ISSUE TITLE
UI Issue: Navbar dropdown error

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3490]
### Describe the bug

Navbar dropdown toggle error.

### To Reproduce

1. Click the navbar dropdown.

![](https://imgur.com/JT07sJR.gif)

![image](https://user-images.githubusercontent.com/22230889/81475202-4e261380-923d-11ea-8d7a-b33763ee658f.png)

### Client configuration

- Browser: Firefox 75
- Operating system: Windows 10

**Comment by adad20** [comment]
@stu01509 Is this problem due to recent commits because I can't reproduce it

**Comment by stu01509** [comment]
Hello @adad20 

Ok, Thanks for your mention, I will clone the new project and reproduce it.

**Comment by yashrajbothra** [comment]
Hey Cliff, 
See, there is a class assigned for dropdown IDK why it isn't loading in DEMO's but my local always show me which I don't like :(

https://github.com/openemr/openemr/blob/932ade32bca6b28541d5b851b2d79638b3a1e94a/interface/main/tabs/templates/menu_template.php#L25
