### ISSUE TITLE
worng dashboard patient in add event popup from calendar

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3502]
### Describe the bug

https://community.open-emr.org/t/new-appointment-in-calendar-tab-prefills-wrong-patient/14454
### To Reproduce
1. choose a pt in dashboard
2. Click on calendar and make an appt
3. go back to dashboard and choose other pt
4. go back to calendar and make a same day appt as previous, notice the previous patient

### Expected behavior

the dashboard pt should populate the add event editor

### Client configuration

- Browser: any
- OpenEMR version: 5.0.2(2) 5.0.3
- Operating system: any

**Comment by bradymiller** [comment]
In this case, when a new patient is opened, then the calendar tab should be
refreshed (this will then populate needed stuff with the right pid).

**Comment by stephenwaite** [comment]
good thinking @bradymiller  :)

**Comment by sjpadgett** [comment]
> In this case, when a new patient is opened, then the calendar tab should be refreshed (this will then populate needed stuff with the right pid).


That won't be to easy to do. Recommend remove session to patientid assignment in function newEvt:

function newEvt(startampm, starttimeh, starttimem, eventdate, providerid, catid) {
  dlgopen('add_edit_event.php?startampm=' + encodeURIComponent(startampm) +
   '&starttimeh=' + encodeURIComponent(starttimeh) + '&userid=' + encodeURIComponent(providerid) + '&starttimem=' + encodeURIComponent(starttimem) +
   '&date=' + encodeURIComponent(eventdate) + '&catid=' + encodeURIComponent(catid),'_blank', 780, 675, '', '', {onClosed: 'refreshme'});
 }

It doesn't make sense to me to have that anymore. This will also save some time on a chart load.

**Comment by stephenwaite** [comment]
glad to follow your advice @sjpadgett 

looking closer at `dialog.js` :see_no_evil: 
does this seem like a typo
```
    return s4() + s4() + s4() + s4() + s4() + +s4() + s4() + s4();
```
specifically  `+ +s4()`

**Comment by sjpadgett** [comment]
> specifically `+ +s4()`

Nope. It's just a way of creating a random unique id for dialog. Adding eight random numbers.

**Comment by stephenwaite** [comment]
ok, so it's just incrementing s4 before adding it to the return

ok, thanks, will try, gonna need to find some more :horse: power for the :brain:

**Comment by sjpadgett** [comment]
> gonna need to find some more 🐴 power for the 🧠

Eat oats!
