### ISSUE TITLE
patch 3 planning

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3507]
Just making this issue to plan patch 3 since looks likes several more fixes (and ongoing work for fixes). @stephenwaite and @sjpadgett , are there any recent things that need to be brought over to rel-502? (just making sure we don't miss anything)
When we are ready to go, it should only take me 1-2 days to get the patch out.

**Comment by bradymiller** [comment]
@sjpadgett , @stephenwaite ,
Are we ready to pull the trigger on this? If so, just give the word, and will get the patch out (and new packages) within a couple days.

I am confident it will go well :)
![tenor (18)](https://user-images.githubusercontent.com/278968/82134473-2e4a9e80-97ad-11ea-8a35-2c23702316b4.gif)

**Comment by sjpadgett** [comment]
I've been watching close for any forum issues and fixed all I know about.
I'm on to 503 stuff so, i'm good and thanks.

Man, i'd hate to be that guy!!! Give it up man, the hole may take ya someplace better.:)

**Comment by tywrenn** [comment]
@bradymiller Patch 3 released -- time to close this
