### ISSUE TITLE
MariaDB 10.4.13 breaks OpenEMR install

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3516]
MariaDB 10.4.13 that was released a couple days ago (and is the most recent production mariadb version) breaks OpenEMR install:
```
Creating user with permissions for database... ERROR when creating specified user. unable to execute SQL: 'SELECT user FROM mysql.user WHERE user = 'openemr' AND host = '#'' due to: The user specified as a definer ('mariadb.sys'@'localhost') does not exist 
```
![image](https://user-images.githubusercontent.com/278968/82003622-b007c400-9615-11ea-9517-fd0b00d0398b.png)

**Comment by bradymiller** [comment]
This is considered critical. Goal is to get a fix out in patch 3 (and then rebuild install packages).

**Comment by sjpadgett** [comment]
I wonder if user is a reserved keyword and may need to enclose in backticks.

**Comment by bradymiller** [comment]
MariaDB 10.4 retired the mysql.user table and it now runs as a view for the new table mysql.global_priv . So appears something in the 10.4.13 release broke being able to use the mysql.user view. I placed a work around that will directly use the mysql.global_priv table if the query with mysql.user errors out.

**Comment by bradymiller** [comment]
ie. we are back in business :)

![tenor (17)](https://user-images.githubusercontent.com/278968/82013407-1d741e80-962f-11ea-9654-49e2ca1d63cf.gif)
