### ISSUE TITLE
Top Nav doesn't Wrap

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3524]
### Describe the bug
Not sure how much this is a bug. Won't wrap if numerous menu items are turned on.
![image](https://user-images.githubusercontent.com/1859985/82138476-b9985400-97ee-11ea-8343-e60f4f20066d.png)

**Comment by stu01509** [comment]
Hello  @sjpadgett 

Can you guide me your step, I would like to fix it.

**Comment by sjpadgett** [comment]
Hi Cliff @stu01509 
You need to turn on some normally off top menu features (Globals) like Group Therapy/NewCrop etc. or resize browser to just before first breakpoint(lg device).
Then note overflow-x scroll. My screenshot above shows how user name is not fully displayed because of x-scroll.
Instead of wrapping top nav it may be better to shorten item names like Patient/Client to Patient.

Also consider reducing padding between menu items. While you have Groups turn on please take a look at bug: Can't find issue I thought I opened for this.
![image](https://user-images.githubusercontent.com/1859985/82148950-68568780-9823-11ea-8a7a-1dde395e17c5.png)

**Comment by tywrenn** [comment]
This is one of the reasons I was doing #3464 because of this awful wrapping effect. It's either the font being too big causing this effect or due to margins/padding not being correct (or flexbox issues).

**Comment by sjpadgett** [comment]
Okay, I see it's a bugger. Even if it wraps, that in itself will cause other formatting issues.
We may need to revisit what items are primary on topnav.
Maybe Calendar can move to Administration as it is usually a default tab or opened once by user.
New Crop will prob need to be primary but I don't know how often it is used by user or how moving would interrupt user workflow. @kchapple little help.

**Comment by kchapple** [comment]
NewCrop only needs to be there if the system is using NewCrop for ERX. Maybe you could shift things around in your menu JSON file and move some menu items to sub-menus?

**Comment by sjpadgett** [comment]
> system is using NewCrop for ERX

Yep get that. Guessing NewCrop to send rx is sent from that UI and can't be moved(or shouldn't)

**Comment by kchapple** [comment]
It can be launched from the patient record also. You can move the menu item and it shouldn’t  break anything. Maybe under Misc? Seems like “About” would be a good candidate to be moved or removed.

**Comment by kchapple** [comment]
It’s really depends the user’s workflow, I think.

**Comment by sjpadgett** [comment]
okay we'll try to leave it be. I always thought it'd be a neat feature to add some keystroke shortcuts.
anyway, thanks

**Comment by sjpadgett** [comment]
> I was doing #3464 because of this awful wrapping effect

Closing in lieu of above.
