### ISSUE TITLE
patient portal minor display and usability issues

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3538]
### Describe the bug

query error
and unable to use features like chat messaging logout

### To Reproduce
![Screenshot from 2020-05-21 06-32-25](https://user-images.githubusercontent.com/5618372/82550963-592a4f00-9b2d-11ea-9a43-34ebe3076841.png)
![Screenshot from 2020-05-21 06-32-03](https://user-images.githubusercontent.com/5618372/82550967-5af41280-9b2d-11ea-92f6-cb08b13fd4b4.png)

1. query error seen on login

1. modal pops up when click on patient in top right corner but entries aren't selectable and
looks like messages aren't flowing as well

### Client configuration
- Browser: chromium Version 81.0.4044.138 (Official Build) snap (64-bit)
- Browser: Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)

- OpenEMR version: dev demo

**Comment by stephenwaite** [comment]
closing since someone must have messed with the demographics layout

**Comment by stephenwaite** [comment]
ok, reopening for a real issue! there's a display issue with some background text
![Screenshot from 2020-05-21 09-00-46](https://user-images.githubusercontent.com/5618372/82561712-d52e9200-9b41-11ea-945b-25ff759a739b.png)

and it does appear that the dropdown items are not clickable
![Screenshot from 2020-05-21 06-32-25](https://user-images.githubusercontent.com/5618372/82561838-11fa8900-9b42-11ea-9509-4f96cd585f72.png)

**Comment by tywrenn** [comment]
@stephenwaite Can you go into the inspect screen in chrome and hover over the `<html>` element and tell me the width and height you are experiencing this under

**Comment by sjpadgett** [comment]
Need to add more top container margin to match sidebar. I added mt-5 to sidebar I believe so right should match left.

**Comment by stephenwaite** [comment]
@bradymiller was saying on the call yesterday that my original issue here is related to the dev demos being broken

@tywrenn looks like it happens on the transition from 767 to 768 width

**Comment by tywrenn** [comment]
@stephenwaite Damnit that's what I was afraid of -- this is when it's supposed to collapse

**Comment by sjpadgett** [comment]
> Damnit that's what I was afraid of -- this is when it's supposed to collapse

That damn portal. I think we ought to ban the guy who created! umm, please.:)

**Comment by bradymiller** [comment]
The portal author is now officially banned for 1 minute.

**Comment by bradymiller** [comment]
ok, the ban is over :)

**Comment by sjpadgett** [comment]
nuts

**Comment by sjpadgett** [comment]
![image](https://user-images.githubusercontent.com/1859985/83348814-df008400-a2fd-11ea-8cc1-72e8e8389bdc.png)
