### ISSUE TITLE
Remove outdated tag code.

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3542]
### Describe the bug

According to this comment https://github.com/openemr/openemr/pull/3497#discussion_r424760810, In our codebase  have a lot of outdated code.

### Expected behavior
Remove and replace it.

Please assign this issue to me.

**Comment by bradymiller** [comment]
hi @stu01509 , it's yours. search and destroy the outdated code :)

**Comment by bradymiller** [comment]
@stu01509 , Just let me know if you want me to reopen this issue (it autoclosed when brought in related PR)

**Comment by stu01509** [comment]
Thank you, sir, I guess it is last part of the outdated tag remove :)
