### ISSUE TITLE
Add Temporary JavaScript File That Detects Bad HTML Elements/Tags/Classes

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3543]
### Describe the problem

A lot of the problems with tags/elements/classes in OpenEMR aren't really noticeable unless a script finds them.

### Describe the solution you'd like

I'm proposing adding a temporary JavaScript file that will be removed upon removing all the bad tags/classes/elements that debugs these sort of issues for all pages. Here's how I plan to do this:
- I plan to add a globals flag that allows devs to toggle the file on and off. This file upon toggling it is then going to be auto-loaded through the core header (since this is a globals switch, the config.yaml will be overridden to auto-load this file into all pages until you toggle it off).
- The created file will have to be put somewhere, I'm proposing to create a folder for it in manually_added_packages in /public/assets to make it easy for me to run it through the core header.
- The JavaScript file will detect the tags/elements/classes that are bad for each page upon it loading up. If it happens to find one, it will log it to the JavaScript console with (possibly) the file name and line number of where the offending code is.

This is a great tool that we can use for testing and definitely should be implemented to make it easier for debugging.

**Comment by mdsupport** [comment]
Any examples of offending objects?

**Comment by tywrenn** [comment]
@mdsupport Offending objects such as `<table>` elements (yet some might not need replacing), replacing the old `bold` class in favor of BS4's equivalent, and anything mentioned in #3160

**Comment by bradymiller** [comment]
Sounds neat if meant for development purposes. I would avoid manually_added_packages since goal if for that to not exist at some point in future :)
Maybe library/js would be good since sure some of the scripts called from core header are there

**Comment by bradymiller** [comment]
I also should of added that there is a very cool mechanism now in the dockers to set globals within the docker-compose.yml. So, we could turn this on for all devs using the easy dev docker environment very easily. For example, here are some globals that are already set there:
https://github.com/openemr/openemr/blob/master/docker-compose.yml#L48-L52

**Comment by zerai** [comment]
There are tools for this job:
[here a list of offending object, deprecated object, and noncompliant HTML5 Code](https://sonarcloud.io/project/issues?id=TestAnalyser_openemr&languages=web&resolved=false)

![Schermata del 2020-05-25 10-09-34](https://user-images.githubusercontent.com/2405279/82792641-fa880c80-9e6f-11ea-875c-32383da1e698.png)

**Comment by tywrenn** [comment]
bump
