### ISSUE TITLE
Ensure support for null in subscriber_DOB field in insurance_data

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3547]
Plan to switch this to null rather than the 0000-00-00 (just need to search codebase to ensure won't cause any untoward effects):
https://github.com/openemr/openemr/blob/master/library/patient.inc#L1208

**Comment by stephenwaite** [comment]
hi @bradymiller , am not seeing any issues with changing this but can continue testing. 

would it be ok for me to create a PR for this?

**Comment by bradymiller** [comment]
@stephenwaite , go for it :)
(disclaimer, you have now unknowingly joined the database modernization project :) )

**Comment by stephenwaite** [comment]
unwittingly vs unknowingly, un-hashed secret to life :)
