### ISSUE TITLE
Patient add/view not working

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#3550]
Hello,

I am onwindows 10, using php 7.3 and running development version 5.0.3 of openemr. whenever I try to add a new patient or view the patient, it allows me to enter the patient details but while saving, it shows a white page. The data are saved in the databae but they are not displayed. 

The php error log shows this - 

[Sun May 24 18:44:08.230389 2020] [php7:error] [pid 3796:tid 1900] [client ::1:51322] PHP Fatal error:  Uncaught TypeError: Argument 5 passed to exist_procedure_item() must be an instance of stirng or null, string given, called in C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php on line 1784 and defined in C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php:2001\nStack trace:\n#0 C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php(1784): exist_procedure_item(2, 'INR', 'CPT4:85610', '', '', 'ge', '1', '', '', '2020-06-07 18:4...')\n#1 C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php(1260): procedure_check(2, Array, Array, '2020-06-07 18:4...')\n#2 C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php(832): test_targets(2, 'rule_inr_measur...', '', '2020-06-07 18:4...')\n#3 C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php(222): test_rules_clinic('', 'active_alert', '2020-05-24 18:4...', 'reminders-due', 2, '', 'default', Array, 'primary', NULL, NULL, 'arnabnaha6885')\n#4 C:\\xampp\\htdocs\\openemr\\interface\\patient_file\\summary\\demographics.php(60): active_alert_summary(2, 'reminders-due', '2020-05-24 18:4...', 'default' in C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php on line 2001, referer: http://localhost/openemr/interface/main/tabs/main.php?token_main=YYbJruGqHoTHGk5SvIeatAokVFMQjhKqXhigm2MN

**Comment by arnabnaha** [comment]
any take on this??

**Comment by sjpadgett** [comment]
i'll take a look at...

**Comment by arnabnaha** [comment]
Thanks Jerry

**Comment by sjpadgett** [comment]
Found the issue.
param misspelled in library/clinical_rules.php L-2001
function exist_procedure_item($patient_id, $proc_title, $proc_code, $result_comp, stirng $result_data = null, $num_items_comp, $num_items_thres, $intervalType = '', $intervalValue = '', $dateTarget = '')

@arnabnaha you can patch on your local and i'll put up a quick PR if this works for you.

**Comment by arnabnaha** [comment]
Sure...i can test it out...can u tell me which file and what to change?

**Comment by arnabnaha** [comment]
Sorry i got it

**Comment by sjpadgett** [comment]
It's the string in param 5 that is misspelled. PHP 7.3 says thats a no no...

**Comment by arnabnaha** [comment]
I will be able to do the change tomorrow morning IST.

**Comment by sjpadgett** [comment]
No problem, i'm going to clean up that script to try and speed it up. Look for a PR before then.

**Comment by arnabnaha** [comment]
thanks jerry

*          Dr. Arnab Naha*
*          MBBS (Cal)*

**Comment by arnabnaha** [comment]
Hi Jerry,

I made the change (corrected the spelling of string) and everything works
well.

Kindly push it to master

Thanks a lot

**Comment by sjpadgett** [comment]
Great, an easy fix. I'm working on calendar issue now.

**Comment by arnabnaha** [comment]
Thanks Jerry
