### ISSUE TITLE
Calendar of a different facility donot work

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#3551]
Hello

I have added a new facility in openemr 5.0.3 and tried to add my timings into the calendar of that facility. It just dont work. After saving the timings, just nothing happens.

I checked the error log and found this- 
[Sun May 24 18:55:03.326757 2020] [php7:warn] [pid 3796:tid 1876] [client ::1:51619] PHP Warning:  Invalid argument supplied for foreach() in C:\\xampp\\htdocs\\openemr\\sites\\default\\documents\\smarty\\main\\%%1E\\1EA\\1EA5C8E9%%ajax_template.html.php on line 424, referer: http://localhost/openemr/interface/main/calendar/index.php?module=PostCalendar&func=view&tplview=default&pc_category=&pc_topic=

**Comment by stephenwaite** [comment]
hi @arnabnaha , is the new facility set up as a service location?

**Comment by tywrenn** [comment]
@stephenwaite wow that link you sent is so outdated XD

**Comment by stephenwaite** [comment]
![external-content duckduckgo com](https://user-images.githubusercontent.com/5618372/82768668-75b0da80-9dfe-11ea-9dd8-f67686cea6b2.gif)

**Comment by arnabnaha** [comment]
Yes..its selected as a service location.

**Comment by stephenwaite** [comment]
here's my test facility page
![Screenshot from 2020-05-25 11-17-30](https://user-images.githubusercontent.com/5618372/82825500-5c993f80-9e79-11ea-8231-098c0b77cb64.png)

is this what you're referring to @arnabnaha ?

**Comment by arnabnaha** [comment]
Yes...i am refering to this only

**Comment by arnabnaha** [comment]
Any take on this plz????

**Comment by sjpadgett** [comment]
Correct if i'm wrong but issue is if facility is selected then events for providers of the selected facility is suppose to show in calendar, is this correct?

**Comment by arnabnaha** [comment]
Yes jerry..i cannot add the provider timings as well as the patient
appointments

**Comment by stephenwaite** [comment]
right @arnabnaha , no one has been able to view these on the selected facility page for at least 10 years?

:cricket:

**Comment by sjpadgett** [comment]
@stephenwaite So besides the facility colors, do we have an issue here?

**Comment by stephenwaite** [comment]
yes, should be able to view the facility specific appointments when you select an individual facility.

**Comment by sjpadgett** [comment]
Seem on new facilities or any facility that doesn't have a user then smarty can't display new appointment. Fortunately, add appointment defaults to logged in provider. So should calendar!

**Comment by sjpadgett** [comment]
@arnabnaha @stephenwaite 
I've modified calendar to where if a facility does not have an associated provider in users, I use the logged in user. Okay?
![image](https://user-images.githubusercontent.com/1859985/83174622-a89deb80-a0e8-11ea-8204-677589e45bdf.png)

**Comment by sjpadgett** [comment]
I finally fixed this error:
![image](https://user-images.githubusercontent.com/1859985/83274315-a0eb4f00-a19b-11ea-944b-6d49dd9dad4e.png)

It's been driving me crazy for couple years.

![image](https://user-images.githubusercontent.com/1859985/83274471-dee87300-a19b-11ea-8c23-1088d6a9a774.png)

Careful what gets escaped!

**Comment by stephenwaite** [comment]
![external-content duckduckgo com](https://user-images.githubusercontent.com/5618372/83278961-60db9a80-a1a2-11ea-8eba-93258d2afea4.gif)
