### ISSUE TITLE
Move Address Book into separate SQL Table & Make it easier to lookup this data

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3561]
### Describe the problem

Currently address book entries reside in the `users` SQL table. While this seems fine, it also can be a vulnerability since this table lists all the admins that are using OpenEMR. This also makes it even more difficult to import and export address book data.

Another issue occurs when you are attempting to search the address book. We currently have it set to have a dropdown list, yet if you add a ton of entries into the address book, this basically is a way to crash the browser.

### Describe the solution you'd like

I'm proposing to move the address book data into a separate SQL table. This will allow more control over it and allow importing and exporting of this data to be so much easier. I'm also proposing to add a new address book search function that allows easy searching of the address book. This will be implemented in the demographics area as well as any other area where this could be beneficial.

Address Book Search Popup:
![image](https://user-images.githubusercontent.com/46497068/82933551-14048380-9f58-11ea-9737-653e0ea33d57.png)

Issue with this feature that we'll need to take care of:
- We will need to migrate this data to the new address book table when the user upgrades (shouldn't be difficult)

Expected order of events:
- Create the new address book table
- Figure out differences between the users table and address book table and figure out where we want to separate the two
- Add migration to address book table during setup
- Add new lookup function

**Comment by stephenwaite** [comment]
hi @tywrenn , a lot of the addr book contents are providers with NPIs so might be advantageous to use the nppes api for new adds?
https://npiregistry.cms.hhs.gov/registry/help-api

**Comment by tywrenn** [comment]
@stephenwaite This looks like an API that can lookup providers? If so, this could theoretically completely eliminate the need to even store them

**Comment by stephenwaite** [comment]
yep, looks up anyone with an NPI but still need to store for things like billing and more reliable access

**Comment by mdsupport** [comment]
Let's not forget international users.

A db centric approach is generic address table and adding its primary key as foreign key to current addressbook as well patient_data and any other place where addresses are needed. That makes it easier to maintain central address for all patients in same household.

**Comment by ophthal** [comment]
and the eye form pulls PCP and referring doc information for reports, referral letters, fax production, etc.  Maybe other places use these address book entries too.  Please make sure before your replace this code you find other places pulling address book info and integrate them with your changes.

**Comment by eyalvo-matrix** [comment]
I would just note that some external modules (for example ours :) )  relay on that data placed in that users table

**Comment by tywrenn** [comment]
Bump
