### ISSUE TITLE
If a user's Provider field is blank then "%nbsp;" is displayed in Past Encounters and Documents

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3565]
### Describe the bug
With OpenEMR 5.0.2.1, it appears that if the Provider field is not checked for a user account (a physician), then in the Past Encounters and Documents list the "Provider" column uses "%nbsp;" for their name.

It appears that if a user is an admin then the user's name appears.

### Expected behavior
Not "%nbsp;". Even nothing would be better than this.

**Comment by stephenwaite** [comment]
hi @pete-boyd , went to test this and have found that a "Clinician" can't even create an encounter on 5.0.2
![Untitled](https://user-images.githubusercontent.com/5618372/83016144-7f4d6480-9fef-11ea-934b-05a5ff7e0d15.png)

**Comment by pete-boyd** [comment]
I've seen this with Clinicians too and assumed it was by design, that I had to create a new ACL mid-way between the two (which I hadn't yet done).

**Comment by stephenwaite** [comment]
looks like it's Notes->My encounters that disables the dropdown
![Screenshot from 2020-05-27 08-19-34](https://user-images.githubusercontent.com/5618372/83018175-d99bf480-9ff2-11ea-92f4-d42c23c1f831.png)
should display an unauthorized
also by default should prob be enabled

**Comment by stephenwaite** [comment]
>  then in the Past Encounters and Documents list the "Provider" column uses "%nbsp;" for their name.

could you share a screenshot @pete-boyd please?

**Comment by pete-boyd** [comment]
![nbsp-provider](https://user-images.githubusercontent.com/63448973/83021489-fac80980-a021-11ea-85f0-2c87f81b9660.png)

**Comment by sjpadgett** [comment]
I might have fixed this in patch 3. I remember cleaning up some syntax but don't remember submitting.

**Comment by pete-boyd** [comment]
@stephenwaite Thanks for the Encounters ACL advice too.

**Comment by stephenwaite** [comment]
no prob, thanks jerry, not seeing it on patch 3 :)

**Comment by sjpadgett** [comment]
Going to fix this for a quick turn around patch 4. @stephenwaite Do you know of some other issues of import?

**Comment by sjpadgett** [comment]
> went to test this and have found that a "Clinician" can't even create an encounter on 5.0.2.3

The defaults for Clinician always were as in 5.0.2-3 so I don't know if I should touch this!

**Comment by stephenwaite** [comment]
hi @sjpadgett , here's a couple https://community.open-emr.org/t/loss-of-convenient-features/14557
