### ISSUE TITLE
Clinical Rules very inefficient

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3566]
### Describe the bug

This module if very resource intensive and a major contributor to slow chart loads.
Patterns like array_merge in a loop and array_push are resource hogs.

### To Reproduce

Take a look.:) library/clinical_rules.php

### Expected behavior
Faster of course!
I'll make a sweep at this if someone will test....

**Comment by arnabnaha** [comment]
I am ready to test....but not before thursday (Indian Standard Time)

**Comment by sjpadgett** [comment]
After reviewing these scripts I concluded there were only some minor changes I could make to speed chart loads. My concern with using array_merges in loops mainly deal with reports and editing. Besides, these loop merges are used to help order the final result arrays thus requiring careful thought.

Closing as good intentioned.:)
