### ISSUE TITLE
New user accounts to follow principle of least privilege and not default to Administrators

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3582]
New user accounts created using Administration > Users > Add User have Access Control of Administrators. I suggest following a principle of least privilege and instead use a default access control with less privilege.

**Comment by tywrenn** [comment]
Or we can just code it so that it doesn't select any of the options listed when it first loads up lol.

**Comment by bradymiller** [comment]
bump

**Comment by bradymiller** [comment]
bump

**Comment by sunsetsystems** [comment]
I have a commit that I can port over for this. It restricts you from creating a user that has any greater permissions than you have. Stay tuned.

**Comment by pete-boyd** [comment]
@sunsetsystems please note that that wouldn't completely fulfil the subject of this issue. I am administrator; there are very few administrators; I create user accounts and it is extremely rare for me to want to create another administrator. If I happen to forget to check the role of a new account then it defaults to the administrators role. Forgetting to check the role needn't have such a dramatic consequence, it should instead default to giving less privileges than may be what's required, rather than giving more.

**Comment by sunsetsystems** [comment]
Thanks for clarifying. I guess there should be no default role, and that validation should force you to choose at least one. My fix is not that, but what you want should not be difficult.
