### ISSUE TITLE
Patient summary menu disappears when select Documents menu option

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3583]
When select "Documents" under the patient summary menu (did I get that name right?), the patient summary menu disappears, requiring the user to select the "go back" icon to go back to the Medical Record Dashboard and regain the menu. All other options under the patient summary menu (Dashboard, History, Report, Transactions, Issues, Ledger, External Data) retain the menu when selected.

Seen in OpenEMR 5.0.2.1, sorry I haven't the ability to test in 5.0.2.3 yet.

**Comment by tywrenn** [comment]
This is actually an intentional thing that was done as I believe it was planned to have a navbar in the Documents area -- yet the documents area is a really complex structure that leaves devs frustrated if they dare try to code with it which was why it was never done.
