### ISSUE TITLE
Graphic Pain Map's OK/Cancel buttons are not visible

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3584]
In a new encounter > Clinical > Graphic Pain Map > select something > the popup has OK/Cancel buttons that are not visible. The buttons have white text on a white background (not visible), and when hovered over have white text on a very light yellow background, still not visible. I see this at least in mustard green, cadmium yellow and ash blue themes. OpenEMR 5.0.2.1.

**Comment by tywrenn** [comment]
The Graphic Pain Map in general just seems broken to be honest... @bradymiller

**Comment by tywrenn** [comment]
This was fixed as of v6. Closing.
