### ISSUE TITLE
phpGACL - The time has come to replace it

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3585]
phpGACL is a dead project. It has been for awhile (last rev I saw was 5 years ago). As much as it is useful, this can be a big security flaw sooner or later. The time has come to replace it now. This issue thread serves as discussion on what we can replace it with and the painful transition that we will have to endure to replace it.

**Comment by mdsupport** [comment]
[PHP-RBAC](http://phprbac.net/)

**Comment by bradymiller** [comment]
hi @tywrenn , This would break upgrade path for a significant amount of users, which would be much more detrimental for security. Note OpenEMR basically took ownership of this code and has secured it (things like sql injection and cross scripting) and fixed bugs and added support features within. Note haven't received security vulnerabilities regarding this code. I'd rec going the other direction here and completing the integration process:
1. Migrating the tables into database.sql and having the setup.php install this with OpenEMR in one step
2. Modernizing the classes (the underlying code for php-gacl is actually rather minimal) to psr4 and placing in src.
3. Upgrading gui to smarty 3 (along with the rest of the smarty 2 stuff).

**Comment by sjpadgett** [comment]
I too look at replacing this back a couple years ago and concluded just as Brady suggests.

Just because something is old doesn't mean it is not still relevant! I need to live by that adage or not bother getting up in the A.M.:)
