### ISSUE TITLE
latest openemr/openemr:flex docker not responding

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3605]
### Describe the bug

easy dev docker environment broken
looks like install completes successfully in the log
```
OpenEMR configured.
Set rest_portal_api to 1
Set rest_fhir_api to 1
Set rest_portal_fhir_api to 1
Set portal_onsite_two_enable to 1
Set rest_api to 1
Setup Complete!
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
v3.12.0-45-g0e4d4e3558 [http://dl-cdn.alpinelinux.org/alpine/v3.12/main]
v3.12.0-49-gb46aa4543e [http://dl-cdn.alpinelinux.org/alpine/v3.12/community]
OK: 12729 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/1) Installing php7-pecl-xdebug (2.9.6-r0)
OK: 955 MiB in 268 packages

Love OpenEMR? You can now support the project via the open collective:
 > https://opencollective.com/openemr/donate

Starting cron daemon!
Starting apache!
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.22.0.4. Set the 'ServerName' directive globally to suppress this message

Love OpenEMR? You can now support the project via the open collective:
 > https://opencollective.com/openemr/donate

Starting cron daemon!
Starting apache!
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.22.0.4. Set the 'ServerName' directive globally to suppress this message
```
### To Reproduce

follow [contributing guide](https://github.com/openemr/openemr/blob/master/CONTRIBUTING.md)

### Expected behavior

step 4 should be able to login with `admin` and `pass` but the browser just spins trying to load login page

**Comment by bradymiller** [comment]
Do you have xdebug set up to work on phpstorm? If so, then any breakpoints in there will stop the code. But that should show up in phpstorm when it happens.

**Comment by bradymiller** [comment]
If above not case, anything in the error log?

**Comment by bradymiller** [comment]
I just realized that the following setting in xdebug is prob not good:
```
xdebug.remote_autostart=1
```
I think i need to make it 0 or else it will always try to connect to phpstorm (in this case I bet it's hitting breakpoints you have in the code by mistake (in phpstorm can search for all breakpoints and remove them).

**Comment by bradymiller** [comment]
yep, my bad:
https://xdebug.org/docs/all_settings
(see xdebug.remote_autostart)
Again, thought, on your end, getting rid of the phpstorm breakpoints or turning off the listener in phpstorm should fix things for now.
I'll fix up the flex docker so it doesn't do this (and will require the firefox addon to work)

**Comment by bradymiller** [comment]
I just pushed a new `flex` docker without the xdebug.remote_autostart setting, so should work (and xdebug only clicks in if turn on the firefox add on).
Let me know how it goes.

**Comment by stephenwaite** [comment]
well it was my bad originally :), my old failed setup in phpstorm must have been interfering along with some random breakpoints from accidentally clicking in the gutter :bowling:

**Comment by stephenwaite** [comment]
back in business 

![external-content duckduckgo com](https://user-images.githubusercontent.com/5618372/84083658-159a6680-a9b0-11ea-935b-7d6bfed6bfd5.gif)
