### ISSUE TITLE
The message that a file upload has been blocked is hard to notice

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3609]
When a user tries to upload a file with a MIME type that is blacklisted, an error appears, e.g.:
"The system does not permit uploading files with MIME content type - image/tiff."
This error message appears below the bottom of the screen and so people don't see the error message and they think nothing has happened.

The text of the message is merely of larger type, it isn't otherwise trying to draw attention to itself by using a typeface in a colour that stands out, such as red. It's very easy for users to miss.

Depending on the setup it can even be hard to figure out how to scroll down.

A popup error message would be ideal.

OpenEMR 5.0.2.1.

**Comment by tywrenn** [comment]
@bradymiller this is a buggggggg lemme squish ittttt

**Comment by bradymiller** [comment]
@tywrenn , take the bug down :)

**Comment by tywrenn** [comment]
Since this has been fixed I'm closing this
