### ISSUE TITLE
Messages Feature is cumbersome to use

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3612]
### Describe the problem

After getting feedback from people using OpenEMR, the messages feature has been a pretty cumbersome thing to use. The to and from area doesn't make sense at all and when using it to confirm patient portal appointments it seems to be an uneasy task to manage when using OpenEMR.

### Describe the solution you'd like

A few things we can do:
1. Make messages templated to fit doctor's needs
2. Make it easier to understand for people who have trouble with technology

**Comment by stephenwaite** [comment]
hi @tywrenn , please see https://github.com/openemr/openemr/issues/2677

**Comment by tywrenn** [comment]
@stephenwaite This is an entirely different issue than that -- seems like these sad states of affairs just keep coming for messages.php :(

**Comment by sjpadgett** [comment]
umm, Tyler you're right that this needs some work. The underlying framework is fine where we need to give a little tlc to the UX. This could mostly be done in pnotes_full.php and wouldn't be to difficult.

**Comment by tywrenn** [comment]
@sjpadgett tacking this issue on the issue mentioned
