### ISSUE TITLE
Cursor is a caret not a pointer when selecting codes

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3617]
In a patient summary menu, Edit medical problems > Add medical problems > Coding.
Click on the blank area to enter a code. When hover over Code / Description, the cursor is a caret when hovering over the text to select, rather than being a pointer. (It is a pointer when hovering _between_ the options.)

OpenEMR 5.0.2.3

**Comment by pete-boyd** [comment]
To be more precise, when hovering exactly over the text itself, the cursor is a caret where it should be a pointer. However when hovering over the area outside of the text, then the cursor is correctly a pointer. With the OpenEMR default font size set to higher figures, e.g. 18px, this area at which the cursor is a caret is reduced (to the extent it appears to not even be available as a selecting tool) compared with when the default font size is set to lower figures, e.g. 14 px.

**Comment by stephenwaite** [comment]
ok, not really a good first issue but who doesn't love a challenge :trophy:

**Comment by stephenwaite** [comment]
can also see this in various places throughout the `UI` like when you hover over the `?` in clinical reminders, so maybe rooted in a top level build `scss`?
