### ISSUE TITLE
The process for deselecting codes that have just been selected is unintuitive

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3618]
In a patient summary menu, Edit medical problems > Add medical problems > Coding.
Click on the blank area to enter a code.

Codes are selected in an intuitive way such as by clicking on them, at which point they become bold. To deselect them, you have to use the "Delete" button at the top, which is not intuitive. It would instead be intuitive if they could be clicked on / selected again to deselect them.

This may be as a result of my having changed font sizes, but currently exacerbating the issue for me is that the text of the Delete button is smaller than the text of the codes.

OpenEMR 5.0.2.3

**Comment by sjpadgett** [comment]
Hi Pete,
Thanks for bringing these user issues up

**Comment by sjpadgett** [comment]
Quick question, do you change font size in browser or through the Globals font selections?

**Comment by pete-boyd** [comment]
@sjpadgett 
Browser text size is set to default.
OS text size is set to default / 100%.

Administration > Globals > Appearance > 
Default font: Use Theme Font
Default font size: 18px -- this explains why the text of the Delete button is smaller than the text of the Codes, as changing "Default font size" doesn't change the size of the Delete button but does change the size of the Codes. Changing "Default font size" back to 14px appears to make them both the same size.

**Comment by sjpadgett** [comment]
hmm so that control must be setting font size instead of using globals.
@tywrenn ya might put this on your list.

**Comment by tywrenn** [comment]
@sjpadgett This is why the `!important` tag will go away this summer because it can't be overridden and since the globals option overrides the fonts, an override + override doesn't work.
