### ISSUE TITLE
Removing a saved code from a patient medical problem is unintuitive

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3619]
Add a code:
In a patient's Medical Issues, select the title for a medical problem > Coding > select a code > close > Save

Remove a code:
Go back into Coding > the chosen code is not selected in the list, which is unintuitive and is one side to this issue. 
You then have to press Delete, sort of blindly, which is another side to this issue; You could select the particular code, but that isn't necessary, so would be a redundant thing to do.
Nothing happens other than an all-too-brief "Processing..." that is hard to discern, which is yet another side to this issue.
Close.
The code has gone.
Save.

OpenEMR 5.0.2.3

**Comment by tpantelis** [comment]
I work for Red Hat and new to project and looking for a reasonable first issue to work on (part time).  I played around with the Issues dialog/workflow and agree that it has usability issues.  In addition to the ones outlined above, some other observations related to code selection/display:

- the **Coding** field allows for multiple codes and displays them separated by a semi-colon. You can also select multiple codes in the pop-up list. This is fine however you can't delete/remove individual codes from the field - you can only delete/clear them all. 
- the **Active Issues Code** list is present when editing an issue but not when initially creating an issue. This seems inconsistent. It is also not updated when a new code is selected via the pop-up list. TBH, I'm not really clear as to the purpose of this list. When editing an issue, it is populated with the codes from ALL issues, not just the one being edited. So it would seem its purpose is to show the user all codes currently in use. But when a code in the list is clicked, it appends it to the **Coding** field which seems odd to me. Also it appends w/o checking if it's already contained in the string so the user can append it multiple times.
- The **Select Codes** dialog has a **Close** button which is used to save the selection(s). However **Close** usually means to dismiss the dialog w/o any action.  It should be an **OK** button.

Some other unrelated observations:

- When editing an issue, the dialog has a **Delete** button to delete the issue. This is a bit unusual. To follow standard practices, the **Medical Problems** table should allow row selection with a **Delete** button. 
- To edit an issue one selects its **Title** in the table. This is fine except there's no visual indication of this - it took me some time to figure it out.  The title string should appear as a hyper-link.

As a first step and to address this issue, I propose that the **Coding** and **Active Issues Code** fields by replaced by a **Codes** field which would be a selectable list with associated **Add** and **Remove** buttons. The **Add** button would launch the existing **Select Codes** dialog with **OK** and **Cancel** buttons (replacing the existing **Delete** and **Close** buttons). The selected code(s) would be added to the **Codes** list (with de-duplication). The **Remove** button would remove the selected code(s) from the list.

If my proposal seems reasonable, I can take a crack at it. It would be helpful if someone could point me to the related code.

@bradymiller

**Comment by bradymiller** [comment]
hi @tpantelis ,

Welcome to the project!

I just tested out the Code selector there and agree with both @pete-boyd and yourself that there are some real issues with that.

Agree with all of your suggestions. The active issues codes is meant to be a shortcut for folks, but agree it is not well integrated. Looking forward to seeing your improvements.

This script is here: interface/patient_file/summary/add_edit_issue.php

Just let us know if need more guidance

**Comment by tpantelis** [comment]
> hi @tpantelis ,
> 
> Welcome to the project!
> 
> I just tested out the Code selector there and agree with both @pete-boyd and yourself that there are some real issues with that.
> 
> Agree with all of your suggestions. The active issues codes is meant to be a shortcut for folks, but agree it is not well integrated. Looking forward to seeing your improvements.
> 
> This script is here: interface/patient_file/summary/add_edit_issue.php
> 
> Just let us know if need more guidance

Thanks. I did find the file and read thru some of the code. I haven't worked with HTML and javascript in over 10 years and never worked with PHP so there's a bit of a learning curve.

**Comment by bradymiller** [comment]
@tpantelis , Sounds like a crash course in PHP and javascript in the near future :) That script can be challenging since there's quite a bit of javascript in it.
