### ISSUE TITLE
5.0.2 Bug: Patient Portal Secure Mail Reply Function is Broken

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3620]
### Describe the bug

When you hit the reply button in Secure Mail for the Patient Portal, it doesn't automatically default to the person you are replying to. This happens on both the patient side and the doctor's side. There's also a glitch where only doctors can be replied to with Secure Mail and not other admins who run the clinic (as also shown in below video).

### To Reproduce
[https://www.loom.com/share/f192c49db188434e967c70b736789794](https://www.loom.com/share/f192c49db188434e967c70b736789794)

### Expected behavior
For the reply button to actually work.

### Client configuration
- Browser: Google Chrome Latest
- OpenEMR version: 5.0.2 Latest Patch
- Operating system: 18.04 LTS

**Comment by sjpadgett** [comment]
First you need to setup providers as only auth providers show in list. we could possibly relax dropdown to all users.
![image](https://user-images.githubusercontent.com/1859985/84404531-f16b9f00-abd4-11ea-8228-b281e9983fc0.png)
and default on  reply:
![image](https://user-images.githubusercontent.com/1859985/84404602-0e07d700-abd5-11ea-8d9f-af0c68fb0902.png)

**Comment by tywrenn** [comment]
@sjpadgett Also I don't get why this is a drop-down -- that could crash the browser if you had a lot of patients. It should be a search for patient sorta thing.

**Comment by sjpadgett** [comment]
that's a good point. so take a whack a it.

**Comment by tywrenn** [comment]
Bump
