### ISSUE TITLE
fees->batch payments : can't edit and save the edited payment

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3621]
### Describe the bug

fees->batch payments : can't edit and save the edited payment 

### To Reproduce

add a payment with fees->batch payments, then search for it and edit it by clicking somewhere on the payment
![Screenshot from 2020-06-13 19-45-17](https://user-images.githubusercontent.com/5618372/84581395-6fcf6900-adae-11ea-81eb-b087cbdaef79.png)

![Screenshot from 2020-06-13 19-46-03](https://user-images.githubusercontent.com/5618372/84581412-8a094700-adae-11ea-84e6-76a1c86c569b.png)

### Expected behavior

edit a payment and have it save the new details

**Comment by stephenwaite** [comment]
think [this code](https://github.com/openemr/openemr/blob/master/interface/billing/edit_payment.php#L753-L756) is the culprit

**Comment by sjpadgett** [comment]
> think [this code](https://github.com/openemr/openemr/blob/master/interface/billing/edit_payment.php#L753-L756) is the culprit

Hi @stephenwaite 
Looking at the 5.0.1 version of this script, the same logic is used accept it drops into php for the substitution.

Are we sure that after users modified their php.ini this issue wasn't fixed?
I can't recreate and it may be because I have my php config'ed to 4000 input vars leading me to believe that users with very many payments the problem shows where testing against one or two it won't.

**Comment by stephenwaite** [comment]
thanks for checking @sjpadgett , i think i'll be able to show you on a dev demo for starters then will look at `502`

**Comment by stephenwaite** [comment]
hi @sjpadgett , same story on 502
![Screenshot from 2020-06-15 17-25-43](https://user-images.githubusercontent.com/5618372/84707768-4d178e80-af2d-11ea-81c9-fd627e5746ec.png)

**Comment by sjpadgett** [comment]
@stephenwaite Are you clicking finish payments?

**Comment by sjpadgett** [comment]
weird!!!

**Comment by sjpadgett** [comment]
Looks like the forms logic was changed when restyle in 502. Heres 501(7)
![image](https://user-images.githubusercontent.com/1859985/84714237-16487500-af3b-11ea-9f2a-96e5a6cf8ed2.png)

Note there is not a Save Changes button like 502/600
![image](https://user-images.githubusercontent.com/1859985/84714342-61fb1e80-af3b-11ea-9ad8-2a82a5557d4d.png)

Also dialogs were replaced with a modal. no no no. This needs to be changed back to a dialog to get entire viewport and not confined inside the Iframe window!!!

Also though saved with Modify Payment the change is not reflected on popup form after save. Looks like need a refresh.

**Comment by sjpadgett** [comment]
@stephenwaite These scripts are messed up! It's going to take some untangling going back to 501!
v6.0 restyle is horrible and needs to be fixed. The way now is not usable imo...
Haven't I been here before? gesh

**Comment by sjpadgett** [comment]
Having to restyle all these forms but replacing modal with dialog makes life better for UX
![image](https://user-images.githubusercontent.com/1859985/85211788-99dadb00-b31a-11ea-8bb8-1fd780846b02.png)

**Comment by sjpadgett** [comment]
@stephenwaite Found the reason it works in v501 and not v502/6.0 umm, validation was broken in 501. lol. Wonder what kind of problems that caused?
Why would the distribution table show if payment hasn't been distributed/posted? If empty, should we still allow payment save?

**Comment by stephenwaite** [comment]
oh really, wow
doesn't make sense that we should allow payment save then unless the user wanted to come back to it at a later time?

**Comment by sjpadgett** [comment]
So if empty then we'd want them to distrib before saving, right?

**Comment by sjpadgett** [comment]
lol, so it works as designed!! I could add a prompt to allow user to decide.

**Comment by stephenwaite** [comment]
:), not neccessary then since why would you ever want an unapplied payment floating in the system to be forgotten about?

**Comment by sjpadgett** [comment]
okay, i'll fixup some exception in javascript and I'll be done. I fixed the tables refresh so transactions are updated.
See you in PR

**Comment by sjpadgett** [comment]
I can't see how this ever worked correctly. Seeing stuff like remainder was never taken into account on posting, always null/0!

**Comment by sjpadgett** [comment]
@stephenwaite I can't find the forum issue for this. Is there one?

**Comment by stephenwaite** [comment]
this was my spin off from the thread where everyone was ganging up on us :)

**Comment by sjpadgett** [comment]
I found one i'll use. Posting there now so, fingers crossed and hopefully somebody will cooperate and test for us as i'd really like to get on with DICOM viewer and put this to bed....
https://community.open-emr.org/t/error-in-edit-batch-payments-in-5-0-2-1/14542/13

**Comment by stephenwaite** [comment]
edited my post above with the :baby:

**Comment by sjpadgett** [comment]
oh okay. Ill ref both...
