### ISSUE TITLE
Add Button in Edit Demographics donot work

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#3632]
Hi,

The "Add" button for the state, country etc in edit demographics page donot work. Clicking them doesnot bring out the popup to add the state/country as previously.

Please fix this

Regards,
Dr. Arnab Naha

**Comment by tywrenn** [comment]
@bradymiller Confirmed this -- it's a pretty horrible bug

**Comment by bradymiller** [comment]
Looks like the layout engine is adding to 2 classes in those entries

**Comment by bradymiller** [comment]
Will post a fix soon, but looks like there is some UI clean up that will also be needed :)
![image](https://user-images.githubusercontent.com/278968/84609981-d10a4180-ae6d-11ea-83f5-3141ff5b9a9f.png)

**Comment by bradymiller** [comment]
Just brought in the main fix for this issue.

I re-opened it though since still cosmetic issues to address, which are in @tywrenn 's area of expertise :)

**Comment by bradymiller** [comment]
btw, the code for this element can be found here:
library/options_listadd.inc

**Comment by arnabnaha** [comment]
Thanks Brady for the fix...working nicely

**Comment by tywrenn** [comment]
@bradymiller will do some cleanup :)
