### ISSUE TITLE
Portal Drop-down Showing when it shouldn't

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3637]
### Describe the bug

The portal notifications drop-down is now showing all the time when it should be hidden.

![image](https://user-images.githubusercontent.com/46497068/84616170-345d9900-ae99-11ea-935e-4300a5d5c049.png)

**Comment by tywrenn** [comment]
@bradymiller I can't figure out how this is being shown/hidden...

**Comment by bradymiller** [comment]
@tywrenn ,
Need to turn off the portal in Globals (and logout/login). The easy dev docker now turns on the portal by default:
https://github.com/openemr/openemr/blob/master/docker-compose.yml#L55
Next planned feature for the easy dev docker is world dominance. Almost there :)

**Comment by bradymiller** [comment]
Although it does seem odd that it is showing with no messages. @sjpadgett , is it meant to show all the time even when no messages?

**Comment by tywrenn** [comment]
@bradymiller it isn't supposed to when no messages are shown... It usually hides itself

**Comment by tywrenn** [comment]
This also appears to be happening in rel 5.0.2 in some cases -- dunno why this is happening...
