### ISSUE TITLE
Use an easy API that lists insurance companies instead of manual entry

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3653]
### Describe the problem

Currently if you want to submit an eligibility insurance request in OpenEMR, you have to manually enter the insurance provider information into the system.

### Describe the solution you'd like

I dunno if there is one, yet if there's a widely available API that we can use to query a list of insurance companies, then we should implement this :)

**Comment by stephenwaite** [comment]
hi @tywrenn , pretty sure there isn't an API for that but the industry is moving in that direction

there's @sjpadgett 's real time elig that works per patient through office ally i believe

plus heard mention of a group that implemented their own with availity

@bradymiller , do you know of Brent's contact info from the call last week? thank you
