### ISSUE TITLE
Login Page Overhaul

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3654]
As pointed out by @juggernautsei - the landing page is in need of an update. Once #3626 is merged I plan to do a huge task: unifying the login page design for every theme and redesigning it from the ground up. The main thing i'll do is shrink the size of the box and then possibly do a really cool gradient or something of that nature. This is gonna be awesome. 🙂

All credit for this design change will go to @juggernautsei even though i'm coding this part.

**Comment by bradymiller** [comment]
![2DV](https://user-images.githubusercontent.com/278968/84979525-79294000-b0e4-11ea-9c14-1b4ebd1773a9.gif)

**Comment by juggernautsei** [comment]
@tywrenn you are too kind.

**Comment by mdsupport** [comment]
@tywrenn Have you considered making the landing page into a dashboard? Without showing any specific private information, it should be possible to display cards (implemented as optional plugins) that each practice/specialty could choose. Some examples would be:

- Appointments for next 7 days
- If lab module is activated - summary of overdue, unreviewed and open results.
- Summary of open messages by category
- Summary of various reminders from CDRs
- onotes (office notes) records that practices can create to remind staff about action items

Clicking on any of the links on the page could popup simple login dialog before proceeding to details.

**Comment by tywrenn** [comment]
@mdsupport This is in regards to the login page. The actual 'landing' page is currently the calendar screen yet I think a dashboard would be nice as this goes along well with my Systems Analysis and Design class that I took.

**Comment by juggernautsei** [comment]
@mdsupport I referred to the login form as the landing page because it is the first thing anyone sees. Or the first place anyone lands is on the login screen. So, the word landing page can be relative to what is being considered before or after login. =^)8

**Comment by mdsupport** [comment]
@tywrenn I was also referring to login form. We have found users/MDs like it when targeted information is displayed without them asking for it. For retail sites where aesthetics is as important as content. In business applications where users are captive, content becomes more important if it saves time or system owners can ensure delivery of specific information to everyone. E.g. if an MD is shown that there are no open appointments for today, it could save them having to login and look at the calendar. Not that it will happen for everyone all the time, but the software needs to provide enough hooks for different developers to leverage.

**Comment by juggernautsei** [comment]
I like the idea of having business information upfront. @mdsupport where are you taking classes?

**Comment by tywrenn** [comment]
@juggernautsei Behold, the new login page that changes everything
