### ISSUE TITLE
Immunization codes are display each entry twice

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#3655]
### Describe the bug
On the codes page when selecting CVX Immunization, each code is displayed twice on the screen.
![image](https://user-images.githubusercontent.com/834958/85023632-ff746f00-b142-11ea-9266-4413c87c0656.png)

### To Reproduce

Go to Codes from the administration menu
Select CVX Immunization
Select Search

### Expected behavior
Show each code only once

### Client configuration

- Browser: All
- OpenEMR version: 5.0.2(1)
- Operating system: Windows and Linux

**Comment by juggernautsei** [comment]
I have been working on this for a few days. When I dump the main_code_set_search line ~754. 
The query returned is 
SELECT '0' as code_external, codes.code as code, codes.code_text as code_text, codes.code_text_short as code_text_short,  codes.id, codes.code_type, codes.modifier, codes.units, codes.fee, codes.superbill, codes.related_code, codes.taxrates, codes.cyp_factor, codes.active, codes.reportable, codes.financial_reporting, codes.revenue_code, 'CVX' as code_type_name   FROM codes  WHERE codes.code like 'dtp%'  AND codes.code_type=100 ORDER BY codes.code+0,codes.code LIMIT 0, 4 ' (length=475)

The limit should be set to 2 for this query.

**Comment by juggernautsei** [comment]
Line 804
Returns both results and query

C:\oerm_dev\www\dev\future5_2\custom\code_types.inc.php:813:
object(ADORecordSet_mysqli)[461]
  public 'databaseType' => string 'mysqli' (length=6)
  public 'canSeek' => boolean true
  public 'dataProvider' => string 'native' (length=6)
  public 'fields' => 
    array (size=18)
      'code_external' => string '0' (length=1)
      'code' => string '22' (length=2)
      'code_text' => string 'DTP-Haemophilus influenzae type b conjugate vaccine' (length=51)
      'code_text_short' => string 'DTP-Hib' (length=7)
      'id' => string '22' (length=2)
      'code_type' => string '100' (length=3)
      'modifier' => string '' (length=0)
      'units' => string '0' (length=1)
      'fee' => string '0.00' (length=4)
      'superbill' => string '' (length=0)
      'related_code' => string '' (length=0)
      'taxrates' => string '' (length=0)
      'cyp_factor' => string '0' (length=1)
      'active' => string '1' (length=1)
      'reportable' => string '0' (length=1)
      'financial_reporting' => string '0' (length=1)
      'revenue_code' => string '' (length=0)
      'code_type_name' => string 'CVX' (length=3)
  public 'blobSize' => int 100
  public 'sql' => string 'SELECT '0' as code_external, codes.code as code, codes.code_text as code_text, codes.code_text_short as code_text_short,  codes.id, codes.code_type, codes.modifier, codes.units, codes.fee, codes.superbill, codes.related_code, codes.taxrates, codes.cyp_factor, codes.active, codes.reportable, codes.financial_reporting, codes.revenue_code, 'CVX' as code_type_name   FROM codes  WHERE (1=1  AND codes.code_text LIKE '%dtp%' ) AND codes.code_type=100 ORDER BY codes.code+0,codes.code LIMIT 0, 4 ' (length=492)
  public 'EOF' => boolean false
  public 'emptyTimeStamp' => string '&nbsp;' (length=6)
  public 'emptyDate' => string '&nbsp;' (length=6)
  public 'debug' => boolean false
  public 'timeCreated' => int 0
  public 'bind' => boolean false
  public 'fetchMode' => int 1
  public 'connection' => 
    object(ADODB_mysqli_log)[3]
      public 'databaseType' => string 'mysqli' (length=6)
      public 'dataProvider' => string 'mysql' (length=5)
      public 'hasInsertID' => boolean true
      public 'hasAffectedRows' => boolean true
      public 'metaTablesSQL' => string 'SELECT
			TABLE_NAME,
			CASE WHEN TABLE_TYPE = 'VIEW' THEN 'V' ELSE 'T' END
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_SCHEMA=' (length=131)
      public 'metaColumnsSQL' => string 'SHOW COLUMNS FROM `%s`' (length=22)
      public 'fmtTimeStamp' => string ''Y-m-d H:i:s'' (length=13)
      public 'hasLimit' => boolean true
      public 'hasMoveFirst' => boolean true
      public 'hasGenID' => boolean true
      public 'isoDates' => boolean true
      public 'sysDate' => string 'CURDATE()' (length=9)
      public 'sysTimeStamp' => string 'NOW()' (length=5)
      public 'hasTransactions' => boolean true
      public 'forceNewConnect' => boolean false
      public 'poorAffectedRows' => boolean true
      public 'clientFlags' => int 0
      public 'substr' => string 'substring' (length=9)
      public 'port' => string '3306' (length=4)
      public 'socket' => string '' (length=0)
      public '_bindInputArray' => boolean false
      public 'nameQuote' => string '`' (length=1)
      public 'optionFlags' => 
        array (size=2)
          0 => 
            array (size=2)
              ...
          1 => 
            array (size=2)
              ...
      public 'arrayClass' => string 'ADORecordSet_array_mysqli' (length=25)
      public 'multiQuery' => boolean false
      public '_genIDSQL' => string 'update %s set id=LAST_INSERT_ID(id+1);' (length=38)
      public '_genSeqSQL' => string 'create table if not exists %s (id int not null)' (length=47)
      public '_genSeqCountSQL' => string 'select count(*) from %s' (length=23)
      public '_genSeq2SQL' => string 'insert into %s values (%s)' (length=26)
      public '_dropSeqSQL' => string 'drop table if exists %s' (length=23)
      public 'database' => string 'future-5-2' (length=10)
      public 'host' => string 'localhost' (length=9)
      public 'user' => string 'root' (length=4)
      public 'password' => string 'not stored' (length=10)
      public 'debug' => boolean false
      public 'maxblobsize' => int 262144
      public 'concat_operator' => string '+' (length=1)
      public 'length' => string 'length' (length=6)
      public 'random' => string 'rand()' (length=6)
      public 'upperCase' => string 'upper' (length=5)
      public 'fmtDate' => string ''Y-m-d'' (length=7)
      public 'true' => string '1' (length=1)
      public 'false' => string '0' (length=1)
      public 'replaceQuote' => string '\'' (length=2)
      public 'charSet' => boolean false
      public 'metaDatabasesSQL' => string '' (length=0)
      public 'uniqueOrderBy' => boolean false
      public 'emptyDate' => string '&nbsp;' (length=6)
      public 'emptyTimeStamp' => string '&nbsp;' (length=6)
      public 'lastInsID' => boolean false
      public 'hasTop' => boolean false
      public 'readOnly' => boolean false
      public 'genID' => int 0
      public 'raiseErrorFn' => boolean false
      public 'cacheSecs' => int 3600
      public 'memCache' => boolean false
      public 'memCacheHost' => null
      public 'memCachePort' => int 11211
      public 'memCacheCompress' => boolean false
      public 'sysUTimeStamp' => boolean false
      public 'noNullStrings' => boolean false
      public 'numCacheHits' => int 0
      public 'numCacheMisses' => int 0
      public 'pageExecuteCountRows' => boolean true
      public 'uniqueSort' => boolean false
      public 'leftOuter' => boolean false
      public 'rightOuter' => boolean false
      public 'ansiOuter' => boolean false
      public 'autoRollback' => boolean false
      public 'fnExecute' => boolean false
      public 'fnCacheExecute' => boolean false
      public 'blobEncodeType' => boolean false
      public 'rsPrefix' => string 'ADORecordSet_' (length=13)
      public 'autoCommit' => boolean true
      public 'transOff' => int 0
      public 'transCnt' => int 0
      public 'fetchMode' => int 2
      public 'null2null' => string 'null' (length=4)
      public 'bulkBind' => boolean false
      public '_oldRaiseFn' => boolean false
      public '_transOK' => null
      public '_connectionID' => 
        object(mysqli)[2]
          public 'affected_rows' => int 4
          public 'client_info' => string 'mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $' (length=79)
          public 'client_version' => int 50012
          public 'connect_errno' => int 0
          public 'connect_error' => null
          public 'errno' => int 0
          public 'error' => string '' (length=0)
          public 'error_list' => 
            array (size=0)
              ...
          public 'field_count' => int 18
          public 'host_info' => string 'localhost via TCP/IP' (length=20)
          public 'info' => null
          public 'insert_id' => int 0
          public 'server_info' => string '5.7.14' (length=6)
          public 'server_version' => int 50714
          public 'stat' => string 'Uptime: 171358  Threads: 41  Questions: 182248  Slow queries: 0  Opens: 4159  Flush tables: 1  Open tables: 1991  Queries per second avg: 1.063' (length=143)
          public 'sqlstate' => string '00000' (length=5)
          public 'protocol_version' => int 10
          public 'thread_id' => int 5654
          public 'warning_count' => int 0
      public '_errorMsg' => boolean false
      public '_errorCode' => boolean false
      public '_queryID' => 
        object(mysqli_result)[462]
          public 'current_field' => int 0
          public 'field_count' => int 18
          public 'lengths' => 
            array (size=18)
              ...
          public 'num_rows' => int 4
          public 'type' => int 0
      public '_isPersistentConnection' => boolean true
      public '_evalAll' => boolean false
      public '_affected' => boolean false
      public '_logsql' => boolean false
      public '_transmode' => string '' (length=0)
      protected 'connectionParameters' => 
        array (size=0)
          empty
      public 'databaseName' => string 'future-5-2' (length=10)
  public '_numOfRows' => int 4
  public '_numOfFields' => int 18
  public '_queryID' => 
    object(mysqli_result)[462]
      public 'current_field' => int 0
      public 'field_count' => int 18
      public 'lengths' => 
        array (size=18)
          0 => int 1
          1 => int 2
          2 => int 51
          3 => int 7
          4 => int 2
          5 => int 3
          6 => int 0
          7 => int 1
          8 => int 4
          9 => int 0
          10 => int 0
          11 => int 0
          12 => int 1
          13 => int 1
          14 => int 1
          15 => int 1
          16 => int 0
          17 => int 3
      public 'num_rows' => int 4
      public 'type' => int 0
  public '_currentRow' => int 0
  public '_closed' => boolean false
  public '_inited' => boolean true
  public '_obj' => null
  public '_names' => null
  public '_currentPage' => int -1
  public '_atFirstPage' => boolean false
  public '_atLastPage' => boolean false
  public '_lastPageNo' => int -1
  public '_maxRecordCount' => int 0
  public 'datetime' => boolean false
  public 'adodbFetchMode' => int 2

**Comment by juggernautsei** [comment]
If I manually set the LIMIT to 2. I get one result back twice. Limit set at line 933

**Comment by juggernautsei** [comment]
Line 662

        array (size=0)
          empty
      public 'databaseName' => string 'future-5-2' (length=10)
  public '_numOfRows' => int 1
  public '_numOfFields' => int 1
  public '_queryID' => 
    object(mysqli_result)[454]
      public 'current_field' => int 0
      public 'field_count' => int 1
      public 'lengths' => 
        array (size=1)
          0 => int 1
      public 'num_rows' => int 1
      public 'type' => int 0
  public '_currentRow' => int 0
  public '_closed' => boolean false
  public '_inited' => boolean true
  public '_obj' => null
  public '_names' => null
  public '_currentPage' => int -1
  public '_atFirstPage' => boolean false
  public '_atLastPage' => boolean false
  public '_lastPageNo' => int -1
  public '_maxRecordCount' => int 0
  public 'datetime' => boolean false
  public 'adodbFetchMode' => int 2
C:\oerm_dev\www\dev\future5_2\custom\code_types.inc.php:662:
object(ADORecordSet_mysqli)[375]
  public 'databaseType' => string 'mysqli' (length=6)
  public 'canSeek' => boolean true
  public 'dataProvider' => string 'native' (length=6)
  public 'fields' => 
    array (size=1)
      **'count' => string '4' (length=1)**
  public 'blobSize' => int 100
  public 'sql' => string 'SELECT count(codes.code) as count  FROM codes  WHERE (1=1  AND codes.code_text LIKE '%dtp%' ) AND codes.code_type=100 ORDER BY codes.code+0,codes.code' (length=150)
  public 'EOF' => boolean false
  public 'emptyTimeStamp' => string '&nbsp;' (length=6)
  public 'emptyDate' => string '&nbsp;' (length=6)
  public 'debug' => boolean false
  public 'timeCreated' => int 0
  public 'bind' => boolean false
  public 'fetchMode' => int 1
  public 'connection' =>

**Comment by juggernautsei** [comment]
The query is being run twice, in my opinion.

C:\oerm_dev\www\dev\future5_2\custom\code_types.inc.php:651:string 'SELECT '0' as code_external, codes.code as code, codes.code_text as code_text, codes.code_text_short as code_text_short,  codes.id, codes.code_type, codes.modifier, codes.units, codes.fee, codes.superbill, codes.related_code, codes.taxrates, codes.cyp_factor, codes.active, codes.reportable, codes.financial_reporting, codes.revenue_code, 'CVX' as code_type_name   FROM codes  WHERE codes.code like ?  AND codes.code_type=100 ORDER BY codes.code+0,codes.code LIMIT 0, 4 ' (length=470)

C:\oerm_dev\www\dev\future5_2\custom\code_types.inc.php:651:string 'SELECT '0' as code_external, codes.code as code, codes.code_text as code_text, codes.code_text_short as code_text_short,  codes.id, codes.code_type, codes.modifier, codes.units, codes.fee, codes.superbill, codes.related_code, codes.taxrates, codes.cyp_factor, codes.active, codes.reportable, codes.financial_reporting, codes.revenue_code, 'CVX' as code_type_name   FROM codes  WHERE (1=1  AND codes.code_text LIKE ? ) AND codes.code_type=100 ORDER BY codes.code+0,codes.code LIMIT 0, 4 ' (length=486)

**Comment by bradymiller** [comment]
@juggernautsei , I wasn't able to confirm this on the online demos (dev and 5.0.2). Can you reproduce this on those demos?
Make me think that maybe you imported the cvx codes twice into your local installation (checkout the codes table)

**Comment by juggernautsei** [comment]
I thought the same thing at first. Here is a screenshot of my table. 
I have three installs that are like this. Here is one https://juggernautsystem.com/dev/future5_2
Username Brady password Miller@123. The install for GMU is the same thing. However, I did two installs yesterday and nothing. I have a really old install and it is like this. 
https://juggernautsystem.com/dev/mindfulemr5 same username password. The difference is the ones that don't do this is ubuntu. The ones that do this are Windows and Centos7.  
![image](https://user-images.githubusercontent.com/834958/85124724-6011b380-b1f8-11ea-8b1c-5a32311a0869.png)

This screenshot is from the dev/future5_2 install on windows.  
![image](https://user-images.githubusercontent.com/834958/85125428-a0256600-b1f9-11ea-875a-ae13e3bda106.png)

There is nothing that I can do to make the demo system do this. It is either it will on it won't. This was reported in https://community.open-emr.org/t/immunization-query-double-result-sql-error/4721.
And  I had something similar here
https://community.open-emr.org/t/immunization-saves-twice-on-first-entry-solved/13430
I think I may try adding the distinct here as well. I can't quite see what causing the double loop.

**Comment by juggernautsei** [comment]
This morning, I wanted to test the two ubuntu systems that were not doing this. And to my surprise after running patch 3. Now they are doing the same thing. Install patch 3 on the demo site, please.

**Comment by juggernautsei** [comment]
I fixed it.

**Comment by juggernautsei** [comment]
@bradymiller this is embarrassing but I have to fess up. The codes were doubled in the table. I cleared them with 
delete t1 from codes t1 INNER JOIN codes t2 WHERE t1.id < t2.id AND t1.code = t2.code AND t1.code_text = t2.code_text AND t1.code_text_short = t2.code_text_short. 
No duplication now. Delete this is not a bug.

**Comment by bradymiller** [comment]
no prob @juggernautsei . now your an expert on codes :)

**Comment by sjpadgett** [comment]
@juggernautsei I'm thinking we should not have ability to have dup codes. Maybe an issue is in order.
