### ISSUE TITLE
patient notes  - empty value on user select box

### ISSUE THREAD

**Issue by avi-matrix** [openemr/openemr#366]
when trying to add a new note for a patient, the first option of the users selection is hard-coded and not containing any value, which leaves the addressee empty.
Is the first choice with the empty value is required to the functionality? Or I can feel safe to delete it and enforce select a recipient?
Thanks.

**Comment by bradymiller** [comment]
Hi,

**Comment by bradymiller** [comment]
oops on the above note, hit enter before placing my message :)

I am not able to confirm this. Can you show a quick screenshot?
thanks, -brady

**Comment by avi-matrix** [comment]
hey, sorry for the late response.
go to Patient file -> notes -> new note
you will see that the first selection is "** closed **" with no value at all..
it is hardcoded.
![image](https://cloud.githubusercontent.com/assets/24208045/20957798/9c9daa62-bc5a-11e6-83d5-fbce166de77c.png)

**Comment by bradymiller** [comment]
That is odd, the most recent development demo does not have this issue:
http://www.open-emr.org/wiki/index.php/Development_Demo#Daily_Build_Development_Demo

In the demo it selects 'Administrator' user by default.

**Comment by avi-matrix** [comment]
the Administrator user is really selected by default, but did you tried to open it and take a look at the options? this should be the first option.
for now it looks like this is unnecessary and can be removed.

**Comment by bradymiller** [comment]
I see what you are saying. I agree that it makes sense to enforce an addressee(ie. remove the empty value).

**Comment by bradymiller** [comment]
@avi-matrix ,
Just checking if I missed the fix for this?
thanks,
-brady

**Comment by avi-matrix** [comment]
brady, please check this pull request
https://github.com/openemr/openemr/pull/429

**Comment by bradymiller** [comment]
Looks good. Will bring the fix into the codebase. thanks!
