### ISSUE TITLE
Calendar  - Springs back to today after every appointment 

### ISSUE THREAD

**Issue by boxlady** [openemr/openemr#3660]
### Describe the bug
When you make an apt in the future, after you close the menu the calendar jumps back to today. So when making appointments 2 weeks in the feature every time you make an appointment  you have to go back to the week/day etc. This has only now just cropped up. with the latest code. You can test it out on the demo server. 

### To Reproduce
Open the calendar tab.
Go to some day in the future. 
Take note of which day your own.
Make an appointment.
See that it jumped back to today's date.

### Expected behavior
On 502 and what I recall all previous versions it would stay on the date you chose instead of jumping back every time. For the receptionist who works 2 weeks in advance most - of the time this can be frustrating.  

Sorry for the late update

**Comment by bradymiller** [comment]
Pretty sure I know why this is happening (looks like a mistake I made on use of the new setSession function). Looking at this now.

**Comment by bradymiller** [comment]
Got a fix for this, which will bring in after it passes travis. When I bring in the PR, this issue will then autoclose (@boxlady , please reopen it if the issue still isn't fixed over there).

**Comment by boxlady** [comment]
Thanks @bradymiller
