### ISSUE TITLE
Binary data in mysqldump

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#3666]
With the advent of uuid (stored as binary data) and guessing other places that use binary data, does it make sense to use the `--hex-blob` flag when using mysqldump (in backup in OpenEMR) to avoid weird stuff happening when trying to store binary data in the sql text files (that flag stores outputs in hex rather than binary). Looks like only trade off is that it takes up more space.

**Comment by bradymiller** [comment]
@jesdynf , Just checking if the aws/lightsail stuff will need this in the future (when we release 6.0.0) regarding the automated mysql backups that are happening in those environments.

**Comment by tywrenn** [comment]
We should improve SQL dump as I've had times where areas/modules add rows/tables and other stuff which makes it completely non-importable.

**Comment by jesdynf** [comment]
Automated MySQL backup does not use mysqldump, so it shouldn't care either way.

**Comment by tywrenn** [comment]
@jesdynf We should be advocating for all use case scenarios, not just cloud-based ones which have the functionality you described. It's bad practice to not advocate for all of them.
