### ISSUE TITLE
UI Issue: Search or Add Patient odd input field 

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3683]
### Describe the bug

I am not sure, when I click the input field, it will show the orange background.
Also, the layout of the form looks like it needs to adjust. Please assign this issue to me.

### To Reproduce

1. Go to Patient Finder
2. Click Add new Patient  button
3. See the odd field 

![image](https://user-images.githubusercontent.com/22230889/85922965-b0080e80-b8b9-11ea-960c-31a74ebcaa2e.png)

### Client configuration

- Browser: Firefox 75
- OpenEMR version: OpenEMR 6.0.0-dev
- Operating system: Windows 10

**Comment by sjpadgett** [comment]
these are required fields plus these are LBF and styling can get tricky. Also there is a Zend validation module that goes with these so again, tricky. This form looks fine as is!

**Comment by stu01509** [comment]
Hi @sjpadgett 

Thanks for your explanation, so do you recommend I only adjusted the styling?

cc @tywrenn

**Comment by sjpadgett** [comment]
I don't want to see these form overly large so I don't see anything wrong with existing style. Plus as I mentioned, these are Layout Based and you may find yourself in a mess quick. Messing with these forms scares me:)

**Comment by tywrenn** [comment]
Since these forms are pretty complex and since I wanna change them to BS4 validation i'll be fixing the styling on this
