### ISSUE TITLE
list editor missing header

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3694]
![Screenshot from 2020-06-29 10-09-35](https://user-images.githubusercontent.com/5618372/86016342-ac2ad800-b9f0-11ea-92ce-a98478f6c741.png)

@tywrenn , would `py-1` be ok here?
https://github.com/openemr/openemr/blob/master/interface/super/edit_list.php#L1030

**Comment by tywrenn** [comment]
This shouldn't need any pie wait i mean `py` lemme fix it
