### ISSUE TITLE
Sub Menu display

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#3695]
submenus for Flow Board, Recall Board and messages no longer display correctly when Global for MedEx is enabled - using master branch.

<img width="904" alt="Screen Shot 2020-06-29 at 1 40 10 PM" src="https://user-images.githubusercontent.com/60580695/86037989-39c8f080-ba0e-11ea-8dbc-9c19f002515d.png">

The demos are OK since they use older code.

Here is the Messages::File:MedEx Setup Page.  Note menu is auto-collapsed despite being on a 17" display.  Also note poor alignment of subsequent paragraphs.  

<img width="810" alt="Screen Shot 2020-06-29 at 1 46 58 PM" src="https://user-images.githubusercontent.com/60580695/86038883-a2fd3380-ba0f-11ea-9c68-69892c8ada49.png">

@tywrenn, @bradymiller and @nkyriakoulis

maybe related to these changes too:  https://github.com/openemr/openemr/pull/3674/files

**Comment by stu01509** [comment]
Hi @ophthal 

Can you guide me, how to open the MedEx? I would like to reproduce and fix it.

**Comment by ophthal** [comment]
Globals->Connectors->Enable MedEx.

Interestingly the menus appear correctly with the flex docker but the latest code updates for MedEx are missing so I am not sure where the flex docker is in relation to openemr/master.

For File::Setup MedEx, the sign-up text is off.  

Here is a screen grab of File::Preferences (shown to active users):


The top of the page needs to come down somewhat since when visible, the menu obscures the text/header.

Please remove the dropdown-toggle class - it now adds a carrot to the menu item that clutters the menu and is not present on the main menu.

If you would like a demo username/pass to sign-up / for testing let me know.

Ray

**Comment by stu01509** [comment]
Hi @ophthal 

Sorry for the late reply, Now I reproduce the same issue, only found the Flow Board -> File > Steup MedEX the submenu overflow, Is right?

![image](https://user-images.githubusercontent.com/22230889/87175282-0427df80-c30b-11ea-8118-3ddee9c99a9a.png)
