### ISSUE TITLE
Layout editor's "ID" and "Label" fields are too small to comfortably use

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3699]
Administration >Layouts' "ID" and "Label" fields are too small to work with comfortably, especially ID where you need to be able to see the whole of the text. For me, ID is 6 chars long, and Label 16 chars long. ID is prone to errors (e.g. inserting a space); uncomfortable when you need to work with it closely trying to cram and hone wording into the very minimal maximum spacing; and difficult to scan across the page with the eye when looking for text. Compare the with the Description field which gets a much bigger box and is optional, where as ID is required.

It takes considerably longer to write a form, working against these issues, than it would if there were more space to work in.

**Comment by tywrenn** [comment]
@pete-boyd The issue is there is so much padding and spacing on this form that it really is almost impossible to make these fields any bigger unfortunately.

**Comment by pete-boyd** [comment]
@tywrenn Can you not achieve it be reducing the size of the Description field?

**Comment by tywrenn** [comment]
@pete-boyd Lemme test that theory real quick

**Comment by tywrenn** [comment]
> ID is prone to errors (e.g. inserting a space)

In my testing in v6 and in 5.0.2 there is a mechanism where if you enter a space it enters an underscore on save `_` instead.

As far as this fix goes what i'll be doing is completely removing the barriers of this table and making it responsive. The size of the description field was 30 originally so that will be toned down to 20.

**Comment by pete-boyd** [comment]
Great.

I've witnessed this behaviour with underscores, and yet also in recent days I've debugged one of my forms that had mistakenly had an actual space in the ID field (running OpenEMR 5.0.2.3 but the bug may have been created whilst on 5.0.2.1).

**Comment by tywrenn** [comment]
The ID field issue seems to me like a personal problem 😂 As far as a 5.0.2 fix on this it probably won't happen since we only push bugs that are code-breaking nowadays. Yet I can promise in 6.0 it will be totally fixed.
