### ISSUE TITLE
Lab results processing breaks if any lab is set to use SFTP 

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#371]
Not sure how the SFTP related code in receive_hl7_results.inc.php works.  But adding a lab which requires SFTP transfer now breaks since Net_SFTP class is no longer available.  Script logic then abandons processing of other labs and/or files.

**Comment by bradymiller** [comment]
I am guessing this may be related to the following(that module was upgraded and brought in via composer/auto-loader):
https://github.com/openemr/openemr/commit/60b735ab3676865b72ed2ee2261d39a09b35bf9e

**Comment by bradymiller** [comment]
I am seeing three places in the codebase that call New_SFTP class. If you change these to SFTP instead, does it work?

**Comment by bradymiller** [comment]
My autoloading knowledge isn't strong, so potentially the classes are being autoloaded?
@Wakie87 , hopefully can get some guidance on this?

**Comment by mdsupport** [comment]
Again, could not find any links to old phpseclib so not sure if existing code was broken already.  To make the PHP error go away, how about -

1. Autoload all
`require_once ($GLOBALS['vendor_dir'] . '/autoload.php');`

2. Change class to:
`...= new \phpseclib\Net\SFTP (....)`

Per documentation, class methods have not changed.  So this will restore original functionality.

On a related note, triggering fetch and process remote files in real-time is not a good idea every time any user wants a report is ok during development but not for a mid size clinic with multiple lab links.

**Comment by bradymiller** [comment]
@mdsupport ,
note the autoload is already done here in globals.php :
https://github.com/openemr/openemr/blob/master/interface/globals.php#L195-L196

I am assuming the script brings in globals.php; let me know if that is not the case. If this is the case, can you test the new \phpseclib\Net\SFTP stuff to ensure it works? If so, then will bring that fix into the codebase.

thanks, -brady

**Comment by mdsupport** [comment]
We use updated version of [cli sftp transfer script](https://github.com/mdsupport/openemr/commit/6871138948018984dbffaee73c115e3b682fc1e9) that has been working for months.  Also specified in phpseclib documentation.

**Comment by bradymiller** [comment]
@mdsupport ,
I am unable to test this, and was hoping you could test this fix:
https://github.com/openemr/openemr/pull/374

Also, would it make sense to place your updated cli sftp transfer script in the contrib directory?

**Comment by bradymiller** [comment]
fixed
see comments in above PR request for details.
