### ISSUE TITLE
Big 5.0.2 Bug: Namespaces Fail to Work

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3715]
This bug stems from the discussion here:

[https://community.open-emr.org/t/fatal-error-cannot-declare-class-cpdf-because-the-name-is-already-in-use-in-applications-xampp-xamppfiles-lib-php-cpdf-php/2721/8](https://community.open-emr.org/t/fatal-error-cannot-declare-class-cpdf-because-the-name-is-already-in-use-in-applications-xampp-xamppfiles-lib-php-cpdf-php/2721/8)

Any help is appreciated.

**Comment by tywrenn** [comment]
@sjpadgett @bradymiller

**Comment by sjpadgett** [comment]
see my comment here: https://community.open-emr.org/t/fatal-error-cannot-declare-class-cpdf-because-the-name-is-already-in-use-in-applications-xampp-xamppfiles-lib-php-cpdf-php/2721/10
