### ISSUE TITLE
Checkboxes in layout based forms have misaligned label text

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3722]
In layout based forms, with a data type of Checkbox(es), when using the form itself the label is presented offset down from the checkbox. This makes it harder to read.

As an example of doing it properly, use a data type of "Checkboxes w/text" and the checkboxes and labels are neatly lined up together.

On Chrome 83 there's a subtle horizontal bar perhaps indicating separation between the lines of options. Firefox 68 doesn't have this bar.

OpenEMR 5.0.2 (patch 3). Firefox and Chrome. Windows 10.

**Comment by pete-boyd** [comment]
Sometimes I create issue and straight away they're not visible under my list of issues. If I add a comment like this then they appear, and remain visible when I delete the comment.

**Comment by bradymiller** [comment]
bump

**Comment by sjpadgett** [comment]
I believe I fixed this in v6. someone could test again.

**Comment by stephenwaite** [comment]
looks good on firefox 81 and chrome 86
