### ISSUE TITLE
It is not clear when documents have uploaded succesfully to a patient record

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3723]
Similar to issue #3609 about the placement of an error message when uploading documents, having uploaded a document successfully, depending on your screen resolution (but presumably it's the case for many screens), when the upload completes there can be no indication that it has done so, leaving the user confused. This is the case because if you scroll down past the bottom of the screen there is a very technical-looking "Upload Report" for those that know it is there and to interpret that as a positive.

Something at the top of the screen, saying that the document had uploaded OK, would be a big improvement.

OpenEMR 5.0.2 (patch 3)

**Comment by bradymiller** [comment]
bump

**Comment by stephenwaite** [comment]
bump bump
