### ISSUE TITLE
Rule Detail style issues

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3728]
### Describe the bug

![Screenshot from 2020-07-08 12-43-21](https://user-images.githubusercontent.com/5618372/86947838-53f38480-c11a-11ea-885f-2da7c2e952ae.png)

![Screenshot from 2020-07-08 12-56-08](https://user-images.githubusercontent.com/5618372/86947899-6d94cc00-c11a-11ea-8435-e65825ed4ec7.png)

### To Reproduce

Admin->Practice->Rules
Add New Rule

**Comment by odra** [comment]
Hello, is anyone working on this one? I would like to work on it if possible :-)

**Comment by bradymiller** [comment]
hi @odra , it's yours :)
