### ISSUE TITLE
Sorting Arrow Issue

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3734]
### Describe the bug

Multiple Arrow Colliding with each other

### To Reproduce

![image](https://user-images.githubusercontent.com/47683556/87223461-c5416a80-c39a-11ea-836f-00708a1013ac.png)

Steps to reproduce the behaviour:
1. Goto Patients->Select Any Patient-> Add/Edit Allergy-> Add Coding
2. Now Add/Codes Model  (```interface/patient_file/encounter/find_code_dynamic.php```) will have the following error

**Comment by stu01509** [comment]
Hi @bradymiller, @tywrenn 

I would like to fix it, Please assign this issue to me.

**Comment by bradymiller** [comment]
hi @stu01509 , it's yours :)
