### ISSUE TITLE
UI Issue: dashboard immunizations page.

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3737]
### Describe the bug

Dashboard immunizations page still contains a lot of outdated code,
and it style looks very odd.

### To Reproduce

1. Go to the dashboard.
2. Click the immunizations edit button.
3. See the Immunizations page.

![image](https://user-images.githubusercontent.com/22230889/87242140-9ab7e600-c45c-11ea-8e40-fd83968cd4ff.png)

### Client configuration

- Browser: Firefox 75
- OpenEMR version: OpenEMR 6.0.0-dev
- Operating system: Windows 10

**Comment by tywrenn** [comment]
@stu01509 Seems like it needs updating

**Comment by tywrenn** [comment]
@bradymiller Can we have a tag dedicated to BS4 modernization lol
