### ISSUE TITLE
Logon page strange

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3742]
### Describe the problem

IMO, this is backward. App info(title box) should be on left because UX for most is immediate look to right for fields. Did a lefty do this?:)
![image](https://user-images.githubusercontent.com/1859985/87367276-818c6380-c548-11ea-890b-b3cc63df453b.png)

### Describe the solution you'd like
Swap

**Comment by tywrenn** [comment]
IMO, it's not backward. Yet we could code an option in globals to allow you to switch which way you want it as some might hate it being like this (yet I love this).

**Comment by sjpadgett** [comment]
Don't need an option. Users are use to title on left and use their muscle memory for logging in. No good reason to change.
While pretty, It's aggravating.

**Comment by sunsetsystems** [comment]
Doesn't matter to me. I would not add to the global settings clutter for this.

**Comment by tywrenn** [comment]
I mean this is why styles like these have their drawbacks to them. If you really want this on the left I'd probably revert to making it front and center so no one complains about the position 😂

**Comment by bradymiller** [comment]
yep, modern design makes us old quicker :)

https://search.muz.li/inspiration/login-screen/

(hint: the youngest one whom has commented here appears to be on to something)

**Comment by bradymiller** [comment]
I do recall when researching where buttons should be placed, that the eyes focus on things to the left first, which is probably why there has been a switcheroo in login screens.

**Comment by tywrenn** [comment]
@bradymiller This is true about design - unless you are in a country that uses RTL

**Comment by sjpadgett** [comment]
You people need to always consider user base. Also, I don't know who decided the whole left or right but in reality, people look to center. It's natural so your eyes take in the whole scene and brain can evaluate.

**Comment by bradymiller** [comment]
yes, but as generations get younger, our attentions spans decrease. For example, whatever I am doing, I just look for a submit button and click it. And if that doesn't work, I then fill in the form as minimally as possible and click the submit button again. You add that to the research showing that the eyes see form inputs and buttons quicker on the left, then voila, there you have it. Why look at the middle and try to figure things out when you can just scan from the left and click the first submit button you see :)

**Comment by bradymiller** [comment]
Seriously, though, we should probably bring another more modern designer centric developer into this. @robertdown , any thoughts on this issue?

**Comment by sjpadgett** [comment]
again, i'm looking at this from user base which is what I care about. Existing users will have to retrain their muscle memory for logging in. You can't tell me every time you've logged in after this change, you pause!

**Comment by stephenwaite** [comment]
could be centered and could be a more subtle graphic on top

also why does the page refresh if you just click login?

**Comment by tywrenn** [comment]
I don't like the look of this personally but this is what it would look like centered (probably will need some size refinements but this is just a general idea)
![image](https://user-images.githubusercontent.com/46497068/87373009-d46d1780-c556-11ea-8cd0-6c10827f11a1.png)

**Comment by bradymiller** [comment]
Just so we have a comparison to above, here it what it now looks like o desktop:

![image](https://user-images.githubusercontent.com/278968/87378671-2ad05b00-c543-11ea-8de0-7880f7246aa5.png)

And then on mobile:
![Screenshot from 2020-07-13 19-59-23](https://user-images.githubusercontent.com/278968/87378754-65d28e80-c543-11ea-980c-40cd27a25aef.png)

**Comment by bradymiller** [comment]
@sjpadgett , What styling theme is your screenshot coming from?

**Comment by sjpadgett** [comment]
Doesn't matter. I said what I think it should be.

**Comment by sjpadgett** [comment]
Sorry, had eye surgery yesterday and can't see. Didn't mean to close.

**Comment by tywrenn** [comment]
**Here are my final thoughts**
My goal of the login page was to make it different than it was before. If I were to create it in the center, I would ideally want it to be smaller ([somewhat similar to this design](https://search.muz.li/YWRiNTNkNWM5)). The issue with this approach is that it could make the page overflow vertically if you added custom logos to it which is something that I hate. Sure, I could create SCSS code that dynamically sizes it to fix this, yet it still has potential to do this which most beginner developers will not know how to fix. One of the issues I solved when creating this sort of LTR layout was this overflow issue. You can make the logos really big and it won't destroy the page. That was the goal.

**What I plan to do**
In an effort to allow consumers to customize their EMR installs, I will create a global variable that allows you to change layouts. This way, if we have issues with overflow with a centered layout, the end user can easily switch to the other layout. This also gives more customization to the user.

**Other Things I'll Do**
- Currently the custom logos have to be replaced by the end user in the file system to get it to work. This is unintuitive and requires more work from the end user. I will be adding global variables that allow the user to choose an image from their local machine and upload it to the server. The way I plan to get this to work is convert the image to base64 and insert it into the globals SQL table. That should make it simpler.
- As @stephenwaite mentioned, if you hit login with no values, the page reloads indicating it went through the post method. I will be blocking this and adding JavaScript that makes sure both fields are filled before submitting.

I know it's not ideal to be adding more global variables as we have a lot of them, yet enhancing the end user experience needs to happen here and with these changes, the login page will be 10x better.

**Comment by sjpadgett** [comment]
Please just flip the form to satisfy an old man. No more globals for login.

I keep trying to hold back this idea of styling to single page application. We forget our audience.  Less is more to users where click counts in workflow matter a great deal. Same for scrolling. 
Remembering also that the reason I wanted bootstrap was for responsiveness and not necessarily styling. I envisioned reducing the core bootstrap variables for margins, padding and font size to allow the most viewport for business forms as possible.

For login page, a nice pretty public facing logon for say portal, is appropriate. However, most users know what clinic they work for and what their logos look like etc. where they just want to log in and get on with it. Also, for security, advertising information on a log in is attractive to hackers. Why answer a hackers basic question like hmm, I don't have to guess the purpose of this login. We aren't advertising to the public here however, our logins audience is mostly a small private group.

Back to my original point. I don't want our user base to relearn login. This may seem simple and/or insignificant but I promise, it's not.

**Comment by bradymiller** [comment]
For more comparison, here is the current login in 5.0.2 for light:

![image](https://user-images.githubusercontent.com/278968/87452688-5f312f00-c5b6-11ea-8219-d8782e841c1c.png)

**Comment by bradymiller** [comment]
2 quick points:
1. If goal is to keep things consistent, then seems like putting stuff to the left of form would not do this. Would need to put it on top, correct?
2. Ok to support customization of login screen especially since we support 3 different logos (and now a slogan). If there is marked disagreement even between core developers, then likely even more marked in end user. ie. just make some globals options (should be one, where the login fluff could go to left, top, right, bottom (why not :) ), or don't even show it

**Comment by sjpadgett** [comment]
w/logo login to right:
![image](https://user-images.githubusercontent.com/1859985/87456203-98789780-c5d4-11ea-9035-3cc3ecee31de.png)

Let's just leave globals alone. A practice shouldn't care if options for left, right, top or any of it.  This is purely an employee log in.

**Comment by bradymiller** [comment]
Guessing the logo version of the login screen doesn't get much use (just guessing this, though, since it's not a default setting). For comparison, here's how it looks when on in light in master:

![image](https://user-images.githubusercontent.com/278968/87466026-6eba7300-c5ca-11ea-943a-725791a6e1ae.png)

**Comment by tywrenn** [comment]
Since I want everyone (including myself) to love the login screen, I will be adding globals to this. As much as I want it simple, I also want it to be unique and customizable for any practice that uses it. The default view will be the center view yet if you believe it looks like cancer you can change it to whatever views I end up coding. OpenEMR was created with customization in mind, and we definitely should continue allowing more customization.
