### ISSUE TITLE
Silly Bootstrap Issue

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3744]
### To Reproduce
![image](https://user-images.githubusercontent.com/47683556/87408950-df20be80-c5e1-11ea-9d4f-04bf7cb68d17.png)

1. Adminis.->Coding->External Data Load
2. Click ICD10
3. See error

**Comment by tywrenn** [comment]
Oh wow. Can you fix it or do you need me or @stu01509 to fix it?

**Comment by yashrajbothra** [comment]
Yeah! Will Push a Quick Fix Soon :)
