### ISSUE TITLE
U2F is broken

### ISSUE THREAD

**Issue by sunsetsystems** [openemr/openemr#3751]
I noticed this recently in master code. You can register a hardware key, but when you try to use it after entering your login name and password it just returns you to the login page.

I'll plan to look into this when time permits, but in the meantime if someone has a clue about what changed in this area please post a note here. Thanks.

**Comment by bradymiller** [comment]
confirmed TOTP is also doing same thing. here are log entries (second to last is the good login, and the last is what happens when does the TOTP confirmation). definitely something is awry:

![image](https://user-images.githubusercontent.com/278968/87609392-49eff980-c6b7-11ea-8758-f330fd12fbcd.png)

**Comment by bradymiller** [comment]
there's been lots of session work done relatively recently to speed things up and guessing there is script that needs to be able to write to session that can't. Can't look at this in more detail, but likely can this evening.

**Comment by bradymiller** [comment]
think onto something. think it has to do with clearing the clearPass from memory (then it is not placed on the mfa form). :crossed_fingers:

**Comment by bradymiller** [comment]
just posted fix. testing well on totp. guessing it should fix u2f also.

**Comment by sunsetsystems** [comment]
Yay! Thanks Brady!
