### ISSUE TITLE
Editing existing lab (procedure_provider) records

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#376]
Has anyone tried to edit procedure provider records that were added before [this commit](https://github.com/openemr/openemr/commit/7a26f614e9d8b2ad6bce117dc37d226b777d3149#diff-e81ec873dfa3e15d75a14f567d0bb0d0)?  Unless the users have been set up to match previously entered pp names, you could magically have new lab name in orders module.

**Comment by mdsupport** [comment]
Here are the curious lines (74-78):

>    $org_qry = "SELECT organization FROM users WHERE id = ?";
>    $org_res = sqlQuery($org_qry, array($_POST['form_name']));
>    $org_name = $org_res['organization'];
>    $sets =
>     "name = '"  .add_escape_custom($org_name). "', " .
> 

If syncing the name is important for MU2, it should be done when source (users table) is updated.  EMR cannot assume that an administrator will do this update manually.

If it not important, the name should be a text field to changed manually.

**Comment by bradymiller** [comment]
Sounds like I may of brought in some mapping madness. I'll need to find where that's used downstream in the MU2 stuff.
