### ISSUE TITLE
Allow layout-based forms' groups to be visible by default

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3770]
I am using OpenEMR 5.0.2 (patch 3). When creating Layout-based visit forms at Administration > Layouts, I would like to be able to set groups to be visible by default. Currently each group apart from the first group requires the user to select a checkbox beside each group to make the questions visible.

Even better than an option to enable them, I think it more likely that form designers want the questions to be visible by default (with an option to hide), rather than invisible by default.

I had a situation where 2 users working together say they took 1 hour to try to figure out how to get the rest of the form to appear before asking me how to do it. To my thinking this is a massive UX failure.

**Comment by sunsetsystems** [comment]
You can enter "I" or "Initially Open Group" in the edit options of the first field in the group to accomplish this.
This feature will be moved to group properties in an upcoming PR; that will make it more intuitive.

**Comment by pete-boyd** [comment]
This is really useful for me to learn, so thank you for that @sunsetsystems. I would thus reframe my request to say that placing this in the edit options in this way is unintuitive and would be better located in group properties. I'm pleased this is happening. Thanks

**Comment by pete-boyd** [comment]
I've tried adding Initially Open Group to the first fields of all groups in the Demographics form and it appears to have no effect, is this expected?

**Comment by pete-boyd** [comment]
I've tried adding Initially Open Group to the first fields of all groups in the Demographics form and it appears to have no effect in "Search or Add Patient", is this expected? Am I misunderstanding?

**Comment by sunsetsystems** [comment]
Might not work for demographics, it was mainly intended for LBF visit forms. In any case demographics has moved to a tabbed view in later releases, so "initially open" does not apply there any more.
