### ISSUE TITLE
Button for saving changes to visit categories is "go" when should be "Save"

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3776]
In Administration > Other > Calendar > Categories, when adding a new category or altering an existing category, the button to save is labelled "go" but would be more descriptive and consistent were it labelled "Save."

OpenEMR 5.0.2 (patch 3)

**Comment by pete-boyd** [comment]
Note: this issue isn't showing up in my list of open issues, I'm not sure why. This has happened with other issues I've created too and makes me wonder if occasionally they get lost.

**Comment by bradymiller** [comment]
bump
