### ISSUE TITLE
ID field in layout based forms has different max size when creating a new field, compared with when editing an existing field

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#3778]
In layout based forms in OpenEMR 5.0.2 (patch 3), when I add a new field, the ID field accepts a max of 20 chars. Once saved, I can change the ID field to accommodate a larger number of characters. My expectation is that the limit should be consistent in both circumstances.

**Comment by stu01509** [comment]
Hello @pete-boyd 

Can you guide me, how to approach this issue? I would like to fix it.

**Comment by pete-boyd** [comment]
@stu01509 
Administration > Layouts > Edit Layout: select an existing form

Add field > Source: 
Try to enter: 123456789012345678901
I find that I cannot, until I remove one character, leaving: 12345678901234567890
Complete the other required fields
Save

Go back to the same field
Now edit the ID field, adding the "1! at the end:
123456789012345678901
I find that now I can enter the full number
Save

**Comment by sjpadgett** [comment]
I'd check in with @sunsetsystems as I believe he is working in this module presently. Prevent any toe stepping.
Also Rod, if indeed you are doing updates in Layouts, would you take a look at preventing users from modifying core layout Id's for our hard coded fields that cause some forms to blow up(ka boom)? Demographics add new etc.
