### ISSUE TITLE
Reduce number of menu groups

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#378]
1. Inventory menu split as follows:
- `Inventoy -> Management`  (moved to Administration as Inventory)
- `Inventory -> Destroyed` (moved to Reports -> Inventory as Destroyed)
2. `Modules` menu (`Manage Modules` item moved to Administration as Modules)
3. `Patient/Client` menu (Split into two top menu items as `Patients` and `Visits` with `Patients -> Visits` becoming 'Visits' and `Patients -> Visit Forms` moved to `Visits -> Forms`.
4. `Procedures` menu moved as a sub menu for `Patients -> Procedures`.

This will reduce menu groups appearing in left_nav and more importantly in new menu on top by 2 without loss of clarity,

**Comment by bradymiller** [comment]
@mdsupport ,
Sounds good.
Regarding the modules change, what should happen to the links for the installed modules? For example, CareCoordination after it is installed places the link into Modules section (which would seem odd in the Administration section). I don't think it would would be too tough to separate this out though (Module admin link separate from the actual module links).

**Comment by mdsupport** [comment]
Basic UI principle is to make it natural for end user.  If a module brings in a link related to patient, it should create a new submenu or add itself to predefined menu structure.  If it is truly a new full featured subsystem, it could even create a top menu.  Most importantly, the _top menu label_ should not raise a `what is this` question in new user's mind.

**Comment by bradymiller** [comment]
For reference, active PR by @mdsupport can be found here:
https://github.com/openemr/openemr/pull/380
