### ISSUE TITLE
Import ESLint (GSoC)

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3780]
### Describe the problem

Our JavaScript has outdated code, has some errors that go unchecked, and in general needs some improvement.

### Describe the solution you'd like

In an effort to stop these issues from happening, me and @stu01509 propose adding ESLint which will find and fix problems in our JavaScript code. This will take a lot of work to implement yet it will be really worth doing.

**Comment by bradymiller** [comment]
bump

**Comment by bradymiller** [comment]
bump

**Comment by mdsupport** [comment]
Rather than keeping stale issues alive, I suggest creating an central issue list with some indication of project's priority rating for each issue. The list should also provide newcomers a sense of efforts involved. The last entry in the issue before it is closed would be link to the master list.
