### ISSUE TITLE
Documents being overwritten

### ISSUE THREAD

**Issue by boxlady** [openemr/openemr#3788]
### Describe the bug
I have an old table of 'documents' from 2015. I was encountering weird bugs of doubles with documents once uploaded were placed in two categories etc. deleting one of them removed both.  After some hunting I found out that for some reason its making new ID's in the 3200 range when I have ID's that go up to 44806. When it looks for an ID in the documents table it doesn't look to see what other IDS are there? It is now writing over what is already in the DB

I see it get the ID's from sql.inc
```
function generate_id()
{
    $database = $GLOBALS['adodb']['db'];
    return $database->GenID("sequences");
}

```
I can't figure out how to change this... Or how I messed it up.. 

### To Reproduce
You can reproduce this you can add documents to the database with all the stuff (documents, catergories_to_documents) and then try and upload from openemr. 

### Expected behavior
That it doesn't overwrite what is already in the database?

@bradymiller any advice?

**Comment by bradymiller** [comment]
hi @boxlady ,
In the `sequence` sql table what do you see for the `id`?

**Comment by boxlady** [comment]
3131

**Comment by bradymiller** [comment]
hi @boxlady , Sounds like that id got mangled somehow. it should only be allowed to count up via the GenID function. I'd look into where that function is used in the codebase  (only several tables use it) and then find the highest id in those places and then manually assign it to be higher than those. That being said, figuring out how it happened would be good; any manual changes to that database or backup/restores etc.?

**Comment by bradymiller** [comment]
Actually, did you import the documents table from another database? If so, then that would explain how this happened.

**Comment by boxlady** [comment]
Yea, when we upgraded to 5.02 I moved everything over with 'mysql' from a 'mysql dump'. weird... 

Changing it fixed the problem. 

Is this only a problem for me (and thus I should close the ticket) or is this something that should be changed?

**Comment by bradymiller** [comment]
hi @boxlady ,
It's mainly a fix for you, but it seems like it would be more robust to use a self incrementing id for most of the tables that use this rather than rely on the GenID function. Any folks know of the benefit of using this GenID mechanism over a simply id that counts for a table?
