### ISSUE TITLE
Delete Button not working on Prescription

### ISSUE THREAD

**Issue by yashrajbothra** [openemr/openemr#3791]
### Describe the bug

Delete Button not working

### To Reproduce

![image](https://user-images.githubusercontent.com/47683556/88917465-6c703e00-d285-11ea-8fa6-762808e163a1.png)

1. Goto any patient dashboard
2. Add any prescription
3. Try to delete the prescription

https://github.com/openemr/openemr/blob/e887d18c1670592852c30493007954d10f3ace9d/templates/prescription/general_list.html#L96
This might be the root cause

**Comment by yashrajbothra** [comment]
This might be a priority Blocking

**Comment by tywrenn** [comment]
@yashrajbothra Can u fix it?

**Comment by bradymiller** [comment]
just brought in fix for this (my fault for letting this get through on recent code review of this feature)
