### ISSUE TITLE
Superhero Theme is Dead

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3799]
The Superhero theme is something that I regret creating as it has been a glitchy mess that I haven't been able to resolve. That is why I will be removing the Superhero theme as well as the Bootswatch dependency that it relied upon. This is a sad state of affairs yet I will try to find another theme to replace it in the coming weeks.

**Comment by sjpadgett** [comment]
Sorry to hear but, we'll still have the dark right?

**Comment by tywrenn** [comment]
@sjpadgett yes 👍

**Comment by bradymiller** [comment]
fare thee well superhero theme :)

Here's a good idea I found for the next super hero theme logo:
![tenor (39)](https://user-images.githubusercontent.com/278968/89090203-36e75580-d356-11ea-9aac-db8303674732.gif)
