### ISSUE TITLE
UI Suggestion: Dashboard top visit history icon

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3804]
### Describe the problem

The Dashboard top of the visit history button icon currently uses the refresh icon, but I think it looks a little bit confused.

Maybe we can change to a history icon like this.
### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/22230889/89102968-bb160780-d440-11ea-9568-278da32b4cda.png)

**Comment by bradymiller** [comment]
hi @stu01509 , completely agree :)
