### ISSUE TITLE
Layout top menu not fixed

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#3810]
### Describe the bug
![image](https://user-images.githubusercontent.com/1859985/89154676-538db400-d535-11ea-9384-21fdb38a407e.png)

This action bar is supposed to be fixed. I spent a lot of time in v501 and v502 making this fixed and other changes so user isn't scrolling to top as they design.
Back up to v502 and check out how this form works.

Also the Save Changes button is only supposed to change to red when click where it should also be disabled.

Also, also:) otherwise the form looks great. Please fix fixed action bar...

**Comment by bradymiller** [comment]
fixed this (in addition to a bug where the additional filter (when click the `?` was not showing up) here:
https://github.com/openemr/openemr/pull/3820

**Comment by bradymiller** [comment]
My fix didn't cover the Save Change red thingy though, so will leave this issue as active

**Comment by sjpadgett** [comment]
lol, I just now was getting ready to push a fix. Oh well thanks and don't worry about button disable. I'll close.
