### ISSUE TITLE
ccd import error through modules->care coordination

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3813]
### Describe the bug

appears import of ccd is broken

### To Reproduce
try importing a ccd after setting up care coordination module

import a ccd
[AdamEveryman-ReferralSummary.txt](https://github.com/openemr/openemr/files/5015977/AdamEveryman-ReferralSummary.txt)

here's the php log from one of the open-emr.org demos
[ccd_import_php_error_log.txt](https://github.com/openemr/openemr/files/5015981/ccd_import_php_error_log.txt)

**Comment by sjpadgett** [comment]
@stephenwaite 
Not sure what that attached file is but it's not a CCD. CCD are xml. Looks like a summary/questionnaire of html origin!

Still, i'm working CCM to bring it up to date. Well best I can....

**Comment by sjpadgett** [comment]
Here are a couple sample. I believe these were generated with my CCD export in CCM.
They import okay on v6.0 PHP 7.2

[sample-ccda.zip](https://github.com/openemr/openemr/files/5020209/sample-ccda.zip)

**Comment by stephenwaite** [comment]
thank you @sjpadgett , failed trying to save the ccds from https://github.com/jmandel/sample_ccdas
save link as inserted the html header, funny how github doesn't have a download button, must really want you to :fork_and_knife: 
here's one from that site @stu01509 
[ae.zip](https://github.com/openemr/openemr/files/5021935/ae.zip)
