### ISSUE TITLE
Bug: Care Plan Form code query error.

### ISSUE THREAD

**Issue by stu01509** [openemr/openemr#3824]
### Describe the bug

In the care plan form. the code field query error.

### To Reproduce

1. Go the care plan form.
2. Click code field
3. Didn't enter any value, and click the search button.
4. See the query error.

![image](https://user-images.githubusercontent.com/22230889/89593074-d2aa2180-d880-11ea-925a-6a33da975d3d.png)

https://www.loom.com/share/29ce2a26d3d7430e97ce4ba0fd5f0e16

### Client configuration

- Browser: Firefox 75
- OpenEMR version: OpenEMR 6.0.0-dev
- Operating system: Windows 10

**Comment by sjpadgett** [comment]
is this fixed yet?

**Comment by stu01509** [comment]
HI @sjpadgett 

Not yet

**Comment by sjpadgett** [comment]
have you finished with styles ie will I have conflicts if I put up a PR?

**Comment by sjpadgett** [comment]
Actually this is a form validation issue. Should not allow search past to server from form if empty Code type. Easy fix if you just default the pull down to a code type instead of the empty default.

**Comment by stu01509** [comment]
Hi @sjpadgett 

My PR needs @tywrenn  to review, so I think you can create a PR to fix it. I will solve my  PR's conflict

**Comment by sjpadgett** [comment]
> Actually this is a form validation issue

Why not take a shot at fixing why you're in this code. See if you can't force the select to default to a code type when generating.
Let me know if you have questions.

**Comment by stu01509** [comment]
Hi @sjpadgett 

I try to figure out this issue, and I found the default select it has value, just only not display on the page.
So I guess not form validation issue, it may relate to the backend server.

![image](https://user-images.githubusercontent.com/22230889/89855109-2e99e080-dbc8-11ea-902f-a70e6dc5e14f.png)

**Comment by sjpadgett** [comment]
interesting. i'll take a look.

**Comment by sjpadgett** [comment]
Hi @stu01509 For some reason SNOMED no longer has a label. Not sure where that went south so, just leave this with me. I'll include in PR for CCM. If you're done with this PR just bring in whomever is decider on review and i'll fix this.

btw, did you restyle some of the CCM?

**Comment by sjpadgett** [comment]
SNOMED Clinical Term is turned off by default but still, it shouldn't show in list. Just turn on to fix and i'm still going to add some validation for this and restyle that popup while there....
![image](https://user-images.githubusercontent.com/1859985/89857942-658dd900-db6b-11ea-824e-0c32ff0ef611.png)

**Comment by stu01509** [comment]
Hi @sjpadgett 

OK, but I am not sure what is CCM

**Comment by stephenwaite** [comment]
hi @stu01509 , it's the care coordination module available under `Modules` tab in top navbar. Think you've registered, installed and enabled those before right?

**Comment by stu01509** [comment]
Thanks @stephenwaite , I have been installed

![image](https://user-images.githubusercontent.com/22230889/89905700-10120480-dc1d-11ea-95aa-3e92c5c833b0.png)

**Comment by sjpadgett** [comment]
Hi @stu01509 I just wanted to know how far whoever restyled got in the modules. 
anyway i've fixed the careplan and pulled down your latest from PR. some min conflicts.
Went ahead and restyled the popup so you can mark that off your list.
![image](https://user-images.githubusercontent.com/1859985/89931223-e97eaa00-dbd9-11ea-883f-c89a4c8f1361.png)

**Comment by stephenwaite** [comment]
![88220254-ba0afc00-cc30-11ea-9dd4-503ca1172e0e](https://user-images.githubusercontent.com/5618372/89932873-411e1500-dbdc-11ea-88aa-af3ed850247c.gif)

**Comment by sjpadgett** [comment]
lol, between you Stephen and Brady, i've got a pretty good virtual fan base! Now, if you could get some in my family on board!
I'm closing this as I will forget to reference when I bring in CCM fixes(and there's a bunch). I didn't have to touch careplan new.php so no worries bringing in your fixes in Cliff.

Okay, i'm off to mind my business, well, for a little while. It's been nice social distancing with you folks!
