### ISSUE TITLE
upgrade from 4.1.2 fails on table modules

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3840]
### Describe the bug

See title

### To Reproduce
install 4.1.2, try to upgrade

### Expected behavior

globals.php will handle no `modules` table exists 

https://github.com/openemr/openemr/blob/master/src/Core/ModulesApplication.php#L63

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by stephenwaite** [comment]
hi @sjpadgett , could this fix fit in with your `CCM` work? some people say i'm a schemer ....

**Comment by sjpadgett** [comment]
What is the current os and php version of machine you're trying to upgrade?
The problem with upgrading from so far back in versions is above. Folks update the os/sql/php to meet version they're updating to and forget prior version aren't compatible with the newer versions.

The course of action should be to upgrade to version where os/php capabilities diverse then update os/php for next step.

**Comment by stephenwaite** [comment]
oh, you think this is a php version issue?

**Comment by sjpadgett** [comment]
Well not to be crass but, should be updating regularly. There's just no way we can keep up with evolving support dependencies like php and os and still maintain backwards compatibility.
We prob should document this process somewhere. I think this make/break is upto v4.2.2. This upgrade also needs to strictly  follow version upgrade till 4.2 i.e 4.1 to 4.11 etc. It's a tricky upgrade Stephen and patient is a requirement.:)

Still, I can't be sure if this is your case. Where in process did you encounter issue and any clues in php error log?

**Comment by stephenwaite** [comment]
![Screenshot from 2020-08-11 15-12-30](https://user-images.githubusercontent.com/5618372/89938851-197f7a80-dbe5-11ea-8af9-1370ec3f6a5d.png)

**Comment by sjpadgett** [comment]
Are you running sql_upgrade as you go?

**Comment by stephenwaite** [comment]
no, this is the flex docker running 6.0 and just after clicking the arrow to load the page

**Comment by sjpadgett** [comment]
My guess is even if you do that you'll just hit another gotcha further on. You may be able to get away with this if you start at 4.1.0, upgrade to 4.1.1 and so forth. You may have to drop to command line though. Sorry...

**Comment by sjpadgett** [comment]
Still, I may give this a shot when I get aggravated with CCM...

**Comment by stephenwaite** [comment]
thanks @sjpadgett , all i do is create the table and it flows seamlessly, well except for a couple of quest tables that needed some row sizes reduced

**Comment by sjpadgett** [comment]
It just wanted to make a fibber out of me!:)

**Comment by stephenwaite** [comment]
bump
