### ISSUE TITLE
old bootstrap used in zf2

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#385]
Modules directory is using 2.1 version of bootstrap - 

To bring it up to current standard, we should look for and then replace 
(responsive.css was incorporated in standard bootstrap as of version 3)

> $this->basePath() . '/css/bootstrap-responsive.min.css'
$this->basePath() . '/css/bootstrap.min.css'
$this->basePath() . '/js/lib/bootstrap.min.js'

By

> $GLOBALS['assets_static_relative'] . '/bootstrap-3-3-4/dist/css/bootstrap.min.css'
$GLOBALS['assets_static_relative'] . '/bootstrap-3-3-4/dist/js/bootstrap.min.js'

Also used are -
1.10.3 - jQ UI with contextMenu plugin

**Comment by bradymiller** [comment]
Sounds like a very good things to do. Looks like there are several Zend modules that use them. Would change them all and remove the old library files and see what happens :)
