### ISSUE TITLE
icd10 in rel-502 upgrade script

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#3855]
https://github.com/openemr/openemr/blob/d1cd5f8354c4560a04be21503300bea278d9be9c/sql/5_0_1-to-5_0_2_upgrade.sql#L605-L610

hi @bradymiller , is it okay to replace these lines with the 2020 files and was the previous commit okay without touching the version counter?

thank you

**Comment by bradymiller** [comment]
hi @stephenwaite , I lost track of this. Was your questions answered?

**Comment by stephenwaite** [comment]
hi @bradymiller , yep, you said since `patch.sql` has it should be all set, will reopen when community proves not so :)
