### ISSUE TITLE
activating modules throws access error to the database

### ISSUE THREAD

**Issue by jackzulaa** [openemr/openemr#3858]
### Describe the bug
![image](https://user-images.githubusercontent.com/11044436/90312896-c3764400-df10-11ea-98f3-7d899dc16624.png)

write concise description of what the bug is.

### To Reproduce

1. Add a '....'

### Expected behavior
click add module need to produce no error as all modules connects to the database with same credentials

### Client configuration

- Browser:Chrome,Firefox
- OpenEMR version: 5.0.2(4)
- Operating system: Windows

**Comment by bradymiller** [comment]
hi @jackrosenthal ,

I was unable to reproduce this on the online dev 5.0.2 demo:
https://www.open-emr.org/wiki/index.php/Development_5.0.2_Demo

Let us know if you can reproduce it there.

What php and mysql/mariadb versions are you using?
What are you seeing in the php error log?

-brady

**Comment by tywrenn** [comment]
@jackzulaa It appears that your mysql user under the name of openemr doesn't have access to the aioprod database. You will have to create that database and give the openemr sql user access to read/write to it.
