### ISSUE TITLE
Incorrect API behaviour

### ISSUE THREAD

**Issue by im-Amitto** [openemr/openemr#3860]
### Describe the bug
Wrong API response

1. API endpoint only consider `dob` as valid input whereas readme mentioned `DOB`
2. Getting e-mail address in dob field
![Screenshot from 2020-08-15 21-14-24](https://user-images.githubusercontent.com/29653282/90315885-858f1500-df3c-11ea-8320-ba8d0388de0f.png)

**Comment by bradymiller** [comment]
hi @im-Amitto ,
That demo is using 5.0.2 . Rec instead using most recent codebase demos:
https://www.open-emr.org/wiki/index.php/Development_Demo#Daily_Build_Development_Demos

**Comment by bradymiller** [comment]
That being said, although I doubt this bug is in 6.0.0-dev, will be good to fix in rel-502 branch at some point.
