### ISSUE TITLE
Disable CouchDB by Default

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3864]
I don't really like using CouchDB. Recently it was added to the docker-compose.yml. Unfortunately when I tried disabling it it spat out errors. Since I would like the flex environment to not take 10 minutes to start, I was wondering if we can make it disabled by default and then if you want it you can enable it.

**Comment by tywrenn** [comment]
@bradymiller

**Comment by bradymiller** [comment]
hi @tywrenn , How did you disable it? (it is not used by default)

**Comment by tywrenn** [comment]
@bradymiller I had to roll back to flex 3.11 and use the docker-compose file that that flex environment had

**Comment by bradymiller** [comment]
@tywrenn , something's not right then. couchdb is causing no problems in my environment (except for throwing stuff to the docker log). Is it breaking something in your environment? Note the time to start up the docker is 95% from the OpenEMR build process (ie. the couchdb and ldap dockers shouldn't slow things down at all except for the initial download of the docker).

**Comment by tywrenn** [comment]
@bradymiller CouchDB doesn't break, it just slows the build down quite a bit and is more noticeable when composer is installing dependencies.

**Comment by tywrenn** [comment]
> shouldn't slow things down at all except for the initial download of the docker

This is where it gets really slow lol xD

**Comment by bradymiller** [comment]
Try remove following lines:
https://github.com/openemr/openemr/blob/master/docker-compose.yml#L80-L94

**Comment by bradymiller** [comment]
couchdb is going to be a critical part of OpenEMR in the future, so plan to try to figure out why all the docker log errors in couchdb which I am guessing will speed things up a bit there.

**Comment by bradymiller** [comment]
@tywrenn and others,

Was thinking it may make sense to consolidate the docker stuff a bit to the following paths:
docker->production->docker-compose.yml
docker->development-easy-standard->docker-compose.yml
docker->development-easy-lightweight->docker-compose.yml (without couchdb and ldap dockers; for @tywrenn :) )
docker->development-insane->docker-compose.yml

This would then mean there would be no docker-compose.yml in the main openemr directory, which I guess may make things a bit more complicated when doing things like docker-compose up/down (ie. need to be in the correct path).

Thoughts?

**Comment by tywrenn** [comment]
@bradymiller This is when I wish docker was more dynamic lol xD
I'm assuming OpenEMR flex runs all the scripts so we technically could probably make the user enter in which environment they want on initial launch in CLI. I think your idea might end up being more complicated than it needs to be.

**Comment by tywrenn** [comment]
@bradymiller What I need is a simple one that I can test themes with and without having to deal with CouchDB or anything extra. Anything in my way I consider slowing me down xD

**Comment by bradymiller** [comment]
Addressed this issue here: https://github.com/openemr/openemr/pull/4005
