### ISSUE TITLE
How to create an appointment for a patient in future?

### ISSUE THREAD

**Issue by rajukiran** [openemr/openemr#387]
Hi,

I would like to schedule an appointment for a patient in future which is not already scheduled for the another patient by the same provider.  Because provider is already allotted for another patient at the same time he/she can't service to more than one patient at the same time.

It is working at calendar where as for the current date or if we check in the doctor at that particular date. I would like to do the same for the future appointments, meaning that i would need something like appointment has to be scheduled and if anyone tried to schedule at the same time and same date it must be say that already allotted.

Is there something there like this already anyone suggest me? If not how do i achieve this?

Thanks & Regards.

**Comment by mdsupport** [comment]
Maybe I am getting the question wrong but doesn't calendar already warn when a provider is booked?

**Comment by rajukiran** [comment]
Warning when a provider is booked.

It is working when dealing with current date or when we are going to use any check-in dates. According to my scenario I would like to book a scheduled appointment irrespective of whether provider is check-in or not / whether it is current of future date. 

When i try to do this **_slot is already used_** message is coming. This is irrelevant to what i was trying to do because i don't have an appointments in those days.

eg: I tried to book an appointment on **Jan 1st 2017**
I given the date in calendar and I clicked **Find Availability** it says no openings available. Immediately i clicked save option it says slot is already used.

My question is is there any way to check in the provider on multiple days? In my scenario providers are always available only few days or sometimes few hours only they won't available.

Can i handle this type of case in OpenEMR?

Regards,

**Comment by bradymiller** [comment]
Hi @rajukiran ,

If you set up the provider's schedule with IN/OUT/LUNCH, then Find Availability will work:
http://www.open-emr.org/wiki/index.php/Using_the_Calendar_4.1

-brady

**Comment by rajukiran** [comment]
Hi, @bradymiller ,

So, can't i achieve a functionality like setting up a schedule for a patient to a provider with precondition. Meaning that system has to tell like if already slot is booked for a patient on that date(Not current/Must be future date) then **slot is already booked**.

My question is very simple and straight forward.

I would like to setup a future schedule for a patient to a particular provider. If provider slot is booked then system has to say that "Slot is already booked choose different one"
"The above scenario is working perfectly when provider is check-in. But as per my scenario provider will be available based on schedules"
Regards,

**Comment by mdsupport** [comment]
@rajukiran, I am not sure but it seems like you have a clinic which is not fully busy . So you want to accept appointments and then get provider to check in as needed.
Your options would be:
1. Ignore warning regarding provider not available (those are info messages)  OR
2. Treat concept of provider "Check-In" in calendar as "On Call - Available as needed" and schedule appointments with a specific provider OR 
3. Create a dummy provider for appointments and have reception assign actual provider at the time of patient checking-in at the reception.

Best luck.

**Comment by bradymiller** [comment]
Closing this issue since has become inactive.
@rajukiran , if still have questions/issues, then feel free to re-open this issue.
thanks -brady
