### ISSUE TITLE
Hope for help

### ISSUE THREAD

**Issue by nijel91** [openemr/openemr#3871]
Hello.
I am trying to deploy OpenEMR on a K8s cluster. However, when I run kubectl apply using YAML files provided here https://github.com/nsteblay/openemr_kubernetes I get the following issue.
MySQL deploys fine. But OpenEMR pod does not. I get CrashLoopBackOff.
Logs show the following:

"PHP Warning:  require_once(/var/www/localhost/htdocs/openemr/sites/default/sqlconf.php): failed to open stream: No such file or directory in Command line code on line 1
PHP Fatal error:  require_once(): Failed opening required '/var/www/localhost/htdocs/openemr/sites/default/sqlconf.php' (include_path='.:/usr/share/php7') in Command line code on line 1

Love OpenEMR? You can now support the project via the open collective:
 > https://opencollective.com/openemr/donate

Starting cron daemon!
Starting apache!
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 192.168.199.109. Set the 'ServerName' directive globally to suppress this message
(2)No such file or directory: AH02291: Cannot access directory '/var/log/apache2/' for main error log
(2)No such file or directory: AH02291: Cannot access directory '/var/www/logs/' for error log of vhost defined at /etc/apache2/conf.d/ssl.conf:124
AH00014: Configuration check failed"

I realize that I must have some sort of misconfiguration, but I have no idea where and what it should look like. 
Hope you'd be able to assist!

Thank you in advance for your time!

**Comment by stephenwaite** [comment]
please see https://github.com/openemr/openemr-devops/tree/master/kubernetes/minikube
