### ISSUE TITLE
Billing Manager - toencounter and topatient broken 

### ISSUE THREAD

**Issue by boxlady** [openemr/openemr#3874]
### Describe the bug
Billing manager to encounter or Patient

If you go to Billing Manger and click on either Encounter or Patient, it looks like it loaded fine but it didn't. PID is missing.

The encounter does this "2014-02-01 Encounter for" but as you can see the name is missing (No PID so no name). If you were to make a form (depending on the form) it might work if it doesn't check for a 0 pid, if it doesn't check it will be put in the database with a PID of 0.

For the Patient, it will load the edit screen but when you try and save it will give this error. `Internal error: Attempt to change patient data with PID = '1' when current PID is '0' for id '1'
`
### To Reproduce

Open billing manager
Clear/Delete Criteria Actions
![image](https://user-images.githubusercontent.com/5113077/90790979-f9e50200-e308-11ea-9eea-b3e6006c1410.png)
Click on Either encounter or patient

### Client configuration
You can reproduce this on the demo server
Tried in firefox and chrome

**Comment by boxlady** [comment]
ohh, I did a little debugging and billing report pass the right PID but it gets changed somewhere else.

**Comment by sjpadgett** [comment]
Somewhere somehow encounter pids are being reset to 0! This is worrisome as I have a very many of my older encounters reset to 0 pid from my demos database. No idea when this started or why but i'll try to get to the bottom of.

**Comment by sjpadgett** [comment]
@boxlady Were you using batch payments per chance or when did you notice?

**Comment by sjpadgett** [comment]
pheew, those were from generated encounters by lab modules during testing.

**Comment by boxlady** [comment]
> @boxlady Were you using batch payments per chance or when did you notice?
> 
> btw does the billing manager show patient name or just the invoice number?
No, I was working on an invoice module for Dentists here in the Netherlands. At first, I thought I broke something but after resting everything and it was still not working I tired on the demo server and fond the problem there. From what I can see the encounter is self is fine, its just when you open the encounter through the billing manager the pid is reset to 0.

**Comment by sjpadgett** [comment]
Okay, that works okay on my local 502(4). For some reason demo won't show Fees menu! Still, if broken on demo, I should be able to fix.

I'll look into further. If you come across any info, let me know...

**Comment by sjpadgett** [comment]
https://demo.openemr.io/a/openemr/interface/login/login.php?site=default
Works okay for me. Plus domos are 502(1) what version are you?

**Comment by boxlady** [comment]
The devement demo

https://eight.openemr.io/a/openemr/interface/main/tabs/main.php

**Comment by sjpadgett** [comment]
jesh. fixed in master
