### ISSUE TITLE
No-copay visits

### ISSUE THREAD

**Issue by Mouse55** [openemr/openemr#3877]
In my practice certain types of visits do not have copays applied to them (surgeries, post-op visits, etc.). The following link demonstrates the modifications necessary to the get_patient_balance function in library/patient.inc to prevent the application of copays to these specific services. https://community.open-emr.org/t/post-op-visits-and-co-pay/11495/4

**Comment by stephenwaite** [comment]
bump

**Comment by sjpadgett** [comment]
if I get time i'll try to get this in for v6 release. sounds like something that could come up often.
