### ISSUE TITLE
Speed Up Gulp Build Time

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3886]
### Describe the problem

This is a follow-up issue to the death of superhero and addition of compact themes. When I added compact themes it basically was asking Gulp to compile all the themes one more time, therefore drastically impacting build time.

### Describe the solution you'd like

Bootstrap 4 uses modules to separate different items of itself ([here's the code in where they get separated at](https://github.com/twbs/bootstrap/blob/v4.5.2/scss/bootstrap.scss)). What I plan to do for compact themes is when they are activated that they overlay the regular theme and just override it. There are only a few modules that actually get changed with compact themes and some of them aren't needed (e.g. the BS4 reboot defaults aren't needed). If I can cut some of these modules out of the compact themes, build times could improve.

Another thing I plan on doing is reorganizing the themes in the `oe-styles` folder to have one file that has all the variables needed to be changed (this is similar to the way I did this in the [colored themes with this file](https://github.com/openemr/openemr/blob/master/interface/themes/colors/utilities/default_variables.scss)). This way any changes down the line are easy and any overrides of these variables can just occur in the individual theme files.

I will also be redoing the Manila theme with this issue. The reason for this is that it holds too many code overrides and needs to be simplified a lot. This should help speed up the build time in theory.

Lastly, I will be sweeping through all the colored themes and even removing some of them. I might end up consolidating some into a new theme if that is warranted. The goal of this is to reduce the amount of themes as in my opinion we have WAYYY too many themes which only increases the build time.

**Comment by bradymiller** [comment]
hi @tywrenn , 

Kind of related. @robertdown pointed out something I removed that may help speed up devs working on themes. It was browsersync in https://github.com/openemr/openemr/pull/3261
video showing use in https://github.com/openemr/openemr/blob/master/interface/README.md#getting-started
https://imgur.com/a/C0dVnfq

Sounds like this doesn't require full building while working on themes. If so, then we can being it back in.
