### ISSUE TITLE
Fee sheet select codes overlap

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#3889]
### Describe the bug

After populating code categories, when selecting a category that is rather large and it drops down over the code select below. The code select box still is visible on top of the dropdown menu.

### To Reproduce

![image](https://user-images.githubusercontent.com/834958/91303013-5fa41480-e775-11ea-96da-404dd631d03a.png)

### Expected behavior

The dropdown should be opaque and cover the text box.  

### Client configuration

- Browser: Chrome
- OpenEMR version: 5.0.2(4)
- Operating system: Ubuntu

**Comment by stephenwaite** [comment]
hi @juggernautsei please see https://community.open-emr.org/t/product-screen-overlay-issues/14247/11?u=stephenwaite

**Comment by juggernautsei** [comment]
@stephenwaite yesterday I had an issue with my banking where the site would not let me log in. The tech support asked me to clear my browser cache. I did and the site allowed me to log in. For grins and giggles, I will clear my cache and use a different machine. I will report back in the next 20 minutes.

**Comment by juggernautsei** [comment]
Here is a screenshot from firefox on ubuntu.
![overlaystillhappens](https://user-images.githubusercontent.com/834958/91311080-a77c6900-e780-11ea-90f4-aeaddb4ec852.png)

**Comment by sjpadgett** [comment]
this is probably a z-index issue.

**Comment by juggernautsei** [comment]
It is a z-index issue but I was not quickly able to find it. I check out the code_choices.css file but because the page is using frameset and not divs it is not clear what can be done. 

I cleared the cache in my windows machine and make sure the patch 4 was installed and it is still there. 
![image](https://user-images.githubusercontent.com/834958/91312243-02fb2680-e782-11ea-9030-7e4d17b04ce8.png)

**Comment by juggernautsei** [comment]
`.active-category
{
    position: absolute;
    z-index: 10;
    background-color: white;
	background
    width: 99%;
    border: 1px black solid;
    padding: 14pt;
}`

I tried changing the z-index to 22222 and nothing changed.

**Comment by sjpadgett** [comment]
i'll take a look

**Comment by stephenwaite** [comment]
> hi @juggernautsei please see https://community.open-emr.org/t/product-screen-overlay-issues/14247/11?u=stephenwaite
> 
> [7de81e5](https://github.com/openemr/openemr/commit/7de81e5036ad1f1e2a9e301f1dbde9ad2a3085d8)

hi guys, this change i just committed doesn't work?

**Comment by sjpadgett** [comment]
here is where need to fix interface/forms/fee_sheet/code_choice/css/code_choices.css L-11
div.code-choices
{
    font-size: 10pt;
    position:relative;
    z-index: 0;
}

ya shouldn't need a z-index here! remove

**Comment by stephenwaite** [comment]
are my posts visible lol

**Comment by sjpadgett** [comment]
sorry @stephenwaite I wasn't paying attention. Removing worked for me however, 99 should work. Best to let parser handle the z-index. did ya clear cache?
![image](https://user-images.githubusercontent.com/1859985/91324229-d51cde80-e78f-11ea-9ca3-9e16815a3edf.png)

Still on my instance I get on selection:
![image](https://user-images.githubusercontent.com/1859985/91324378-00073280-e790-11ea-8428-13a4092be694.png)

**Comment by juggernautsei** [comment]
That work! No reload needed.

**Comment by sjpadgett** [comment]
okay so i'm lost! what worked and are you getting an error on code select?

**Comment by sjpadgett** [comment]
The above bug was by my fat fingers. I kicked my dog and he promised to not do it again!
@juggernautsei if you'd do PR i'll add to patch.

**Comment by stephenwaite** [comment]
lol, the above commit was added to `rel-502`

**Comment by sjpadgett** [comment]
Man oh man! I'm such an airhead. I should just go hide in the corner....

**Comment by stephenwaite** [comment]
github needs self destruct timer for these situations :bomb:

**Comment by sjpadgett** [comment]
ha, yesterday I started fixing something in 501 and caught myself.

**Comment by bradymiller** [comment]
I've heard the 4.0.2 has some bugs that needs fixing :)

**Comment by stephenwaite** [comment]
actually 4.1.2 upgrade lol

**Comment by sjpadgett** [comment]
I'm in the corner on timeout so.....

**Comment by stephenwaite** [comment]
![external-content duckduckgo com](https://user-images.githubusercontent.com/5618372/91358310-94898900-e7c0-11ea-9644-ecaa72431a7d.gif)

kind of obtuse :)

**Comment by bradymiller** [comment]
we only for bans/timeout for 1 minute here. ban started. ok, now done :)
