### ISSUE TITLE
Bug When Creating a New Patient

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3891]
Just ran into this bug that happens whenever I create a new patient.
![image](https://user-images.githubusercontent.com/46497068/91353492-563c9b80-e7b9-11ea-8b87-1c3620dbbf3b.png)

**Comment by tywrenn** [comment]
@bradymiller

**Comment by stephenwaite** [comment]
hi @tywrenn , can't reproduce on the demos but this is the easy dev setup?

**Comment by tywrenn** [comment]
@stephenwaite Yep it's using easy dev (as in the stock docker-compose file found in the repo)

**Comment by stephenwaite** [comment]
just spun it up and it added a pt no prob

**Comment by stephenwaite** [comment]
have been seeing a persistent file that has to be checked out with the easy dev before moving on to more important matters lol
`contrib/util/docker/couchdb-config-ssl-cert-keys/local.ini`

**Comment by bradymiller** [comment]
I'm officially banning the person that added couchdb for 1 minute ........ ok, done :)

**Comment by sjpadgett** [comment]
oh, we banned him yesterday!

**Comment by bradymiller** [comment]
I must of forgot. We need a high tech way to track these misbehaviors. Thinking that investing in future technology may help us:
https://www.amazon.com/Yellow-Mountain-Imports-Standard-Abacus/dp/B00SQVXSMM/

**Comment by tywrenn** [comment]
Still happening unfortunately
