### ISSUE TITLE
Dropdown Not visible

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#3898]
Hi,
I am in windows and using chrome. I am using the latest dev tip of openemr 6.0.0.
In my instance, I cannot see the dropdown list in the encounters page as this is too light against the background (see image below).
![openemr](https://user-images.githubusercontent.com/1074948/91679974-6a8ce980-eb67-11ea-8f59-571b08db71bb.png)

This doesnot change with the selection of theme, its same in all themes.
Kindly make is a bit dark so that its visible while working.

Thanks
Dr. Arnab Naha

**Comment by tywrenn** [comment]
Please try using a different theme while I work on this issue.

**Comment by arnabnaha** [comment]
I have tested 3-4 themes..all are same

**Comment by tywrenn** [comment]
The default light theme should work -- if it doesn't it's probably a global theme issue.

**Comment by arnabnaha** [comment]
Its still the same even after the code changes.

**Comment by arnabnaha** [comment]
please reopen this

**Comment by tywrenn** [comment]
@arnabnaha I tested this on one of the up-for-grabs demos and it seems to be resolved...what theme are you using?
![image](https://user-images.githubusercontent.com/46497068/91878796-d0ec3780-ec4d-11ea-9c5e-213906d2fdc0.png)
Did you clear your website cache after updating? Try doing that as the themes typically get cached by your browser. Also be sure the themes have been recompiled as well in your environment as that also might cause issues.

**Comment by arnabnaha** [comment]
Hi..
The dropdown is nicely visible now..Actually i was facing a troubled login isssue and need to solve it...After I removed the cached and by Brady's fix was able to login back...I can see that the dropdowns are good to go..Thanks a lot. I am closing it down.
