### ISSUE TITLE
Cant Login to Openemr

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#3900]
hi
All was working fine...I made the code changes to the themes #3899 and suddenly I got the error SITE ID MISSING... I cleared the cache and tried to log in back, but I am automatically thrown back to the login screen again. This is checked in firefox and microsoft edge also. All three browser shows same activity.

Apache error log is showing this - 
[Tue Sep 01 18:03:33.391086 2020] [php7:notice] [pid 1920:tid 1860] [client ::1:64287] PHP Notice:  Undefined index: db_encoding in C:\\xampp\\htdocs\\openemr\\src\\Common\\Database\\Connector.php on line 120, referer: http://localhost/openemr/interface/login/login.php?site=default
[Tue Sep 01 18:03:33.537993 2020] [php7:notice] [pid 1920:tid 1860] [client ::1:64287] PHP Notice:  Undefined index: db_encoding in C:\\xampp\\htdocs\\openemr\\interface\\modules\\zend_modules\\config\\autoload\\global.php on line 22, referer: http://localhost/openemr/interface/login/login.php?site=default

please help...

Dr. Arnab Naha

**Comment by stephenwaite** [comment]
hi @arnabnaha , if you revert the changes are you able to log back in?

**Comment by arnabnaha** [comment]
I just reverted the changes...no help..still having the same login issue

**Comment by stephenwaite** [comment]
odd, have you tried resetting your password through the sql command line or phpmyadmin?

**Comment by arnabnaha** [comment]
No i have not reset my password anytime soon

**Comment by stephenwaite** [comment]
just thinking it's worth a try since it's a login issue

**Comment by stephenwaite** [comment]
`UPDATE users_secure SET `password` = '$2a$05$MKtnxYsfFPlb2mOW7Qzq2Oz61S26s5E80Yd60lKdX4Wy3PBdEufNu' WHERE `username` = 'admin'`

**Comment by arnabnaha** [comment]
No help..still cant login. Browser is refreshing back to login screen

*          Dr. Arnab Naha*
*          MBBS (Cal), DNB (General Surgery)*

**Comment by stephenwaite** [comment]
ok, and after reverting you cleared the cache?

**Comment by arnabnaha** [comment]
yes I cleared the cache

*          Dr. Arnab Naha*
*          MBBS (Cal), DNB (General Surgery)*

**Comment by arnabnaha** [comment]
I am reinstalling openemr after taking a mysqldump...lets see if this helps

*          Dr. Arnab Naha*
*          MBBS (Cal), DNB (General Surgery)*

**Comment by arnabnaha** [comment]
So I understood where the problem is -
I dropped the database after taking a mysqldump and reinstalled openemr on
a fresh database totally empty from the recent dev tip and it worked fine.
I was able to login and everything.

Next I restored mysqldump file on my fresh database and again I am unable
to login and I am refreshed back to login screen after moments of getting
logged in.

What is the issue???

*          Dr. Arnab Naha*
*          MBBS (Cal), DNB (General Surgery)*

**Comment by arnabnaha** [comment]
PHP error log is now showing this -

[Tue Sep 01 21:24:44.529984 2020] [php7:warn] [pid 5528:tid 1868] [client
47.15.2.42:57934] PHP Warning:  session_destroy(): Trying to destroy
uninitialized session in
C:\\xampp\\htdocs\\openemr\\src\\Common\\Session\\SessionUtil.php on line
204, referer:
http://nahahealthclinic.ddns.net/openemr/interface/main/tabs/main.php?token_main=IzWZhku9oYI3WVeVRJDxaIh5nFrgbOc0NqfXzFQx
[Tue Sep 01 21:24:44.579955 2020] [php7:warn] [pid 5528:tid 1896] [client
47.15.2.42:57935] PHP Warning:  session_destroy(): Trying to destroy
uninitialized session in
C:\\xampp\\htdocs\\openemr\\src\\Common\\Session\\SessionUtil.php on line
204, referer:
http://nahahealthclinic.ddns.net/openemr/interface/main/tabs/main.php?token_main=IzWZhku9oYI3WVeVRJDxaIh5nFrgbOc0NqfXzFQx

*          Dr. Arnab Naha*
*          MBBS (Cal), DNB (General Surgery)*

**Comment by arnabnaha** [comment]
![log openemr](https://user-images.githubusercontent.com/1074948/91881145-aeced580-ec9e-11ea-8934-e1155dbd93bd.jpg)

This is the openemr log from phpmyadmin - shows timeout and forced logout

I donot know why

**Comment by bradymiller** [comment]
hi @arnabnaha ,
Any entries in the session_tracker table. If so:
1. remove them
2. remove all cache/history on browser
3. stop/start browser
4. try to log in

**Comment by bradymiller** [comment]
also, take a screenshot of  the session_tracker entries before removing them

**Comment by sjpadgett** [comment]
> [Tue Sep 01 21:24:44.529984 2020] [php7:warn] [pid 5528:tid 1868] [client 47.15.2.42:57934] PHP Warning: session_destroy(): Trying to destroy uninitialized session in C:\\xampp\\htdocs\\openemr\\src\\Common\\Session\\SessionUtil.php on line 204, referer:

Don't worry about this warning it is not hurting your issue. Thats from session teardown from being redirected to login I believe.
@bradymiller I think this may have to do with encryption keys!

**Comment by bradymiller** [comment]
the "timeout, so force logout" seems to point towards an issues in SessionTracker (i can't see how a bad column in session_tracker could do this since it's just pinned to session, but it is relatively new code)

**Comment by sjpadgett** [comment]
Okay but just for grins @arnabnaha try running sql_upgrade against troubled database. Start at v5.0.1

**Comment by arnabnaha** [comment]
This is the session tracker table. I have removed it. I have removed all cache and browser history. Tried to relogin but all the same.

I even tried sql_upgrade from v5.0.1 but its same.

**Comment by bradymiller** [comment]
can't see your session tracker table.
Try to place the following right before the if block at line 87 in library/auth.inc:
```
$skipSessionExpirationCheck = true;
```
(just a quick fix that should get things working in case needed for your production instance)

**Comment by arnabnaha** [comment]
Hi Brady...Thanks for the quick fix..really saved me...i have all my patient data in the instance and was going mad by thinking how i will get back my data. Anyways..Now I am able to login back but the calendar screen is not working - its showing unknown at the title.

Regarding the session tracker screenshot..there is an issue in github i guess for uploads...i am trying but its constantly failing..i am retrying to upload.

**Comment by bradymiller** [comment]
Wonder if browser is holding on to a bad cookie (which is in turn connecting to a bad php session). Would also ensure you remove all cookies from your browser.

**Comment by bradymiller** [comment]
Also, are you seeing any php errors after logging in successfully?

**Comment by arnabnaha** [comment]
This is my php error log now -

[Wed Sep 02 09:50:29.101926 2020] [php7:warn] [pid 5528:tid 1888] [client 223.223.146.216:59376] PHP Warning:  A non-numeric value encountered in C:\\xampp\\htdocs\\openemr\\interface\\main\\calendar\\modules\\PostCalendar\\pnuserapi.php on line 73, referer: http://nahahealthclinic.ddns.net/openemr/interface/main/tabs/main.php?token_main=VxRy07U01ZFDZ6r1crsj3WmQ

**Comment by arnabnaha** [comment]
![session_tracker](https://user-images.githubusercontent.com/1074948/91932235-36e6c680-ed03-11ea-9500-71b838e51255.png)

**Comment by arnabnaha** [comment]
![calendar](https://user-images.githubusercontent.com/1074948/91932246-3fd79800-ed03-11ea-9608-fe855dddd517.jpg)

This is the calendar currently

**Comment by bradymiller** [comment]
I think something is wrong with your globals table (this is why the timeout is possibly breaking and why getting that warning since the common link is they are both globals). Do you see any odd setting in Administration->Globals (for example the `Calendar Interval` setting and the `Idle Session Timeout Seconds` setting)

**Comment by arnabnaha** [comment]
This is the session tracker table after the fix given by Brady - 



![session_tracker_afterfix](https://user-images.githubusercontent.com/1074948/91932535-179c6900-ed04-11ea-9316-b5e75e525963.jpg)

**Comment by arnabnaha** [comment]
> 
> 
> I think something is wrong with your globals table (this is why the timeout is possibly breaking and why getting that warning since the common link is they are both globals). Do you see any odd setting in Administration->Globals (for example the `Calendar Interval` setting and the `Idle Session Timeout Seconds` setting)

I am checking it right now Brady

**Comment by arnabnaha** [comment]
Brady

The whole globals is completely problematic...please see - 
![globals1](https://user-images.githubusercontent.com/1074948/91933041-9b0a8a00-ed05-11ea-97d6-79d0b2fcbe9c.jpg)
![globals2](https://user-images.githubusercontent.com/1074948/91933054-a1006b00-ed05-11ea-8594-8345c95054e6.jpg)
![globals3](https://user-images.githubusercontent.com/1074948/91933059-a2319800-ed05-11ea-8862-c4aeb72983ad.jpg)

You can see - the pre populated fields are all empty

How can I restore the globals.

**Comment by arnabnaha** [comment]
![global4](https://user-images.githubusercontent.com/1074948/91933349-4ddae800-ed06-11ea-95c1-6e6c03c4029d.jpg)

**Comment by arnabnaha** [comment]
Idle session time out is also empty

**Comment by bradymiller** [comment]
yep, basically empty. I would truncate the current globals table (ie. remove everything thing) and then populate it from a prior database backup that you have. Then run the sql_upgrade.php script.

**Comment by bradymiller** [comment]
(after you do this, then can remove the `$skipSessionExpirationCheck = true;` line you placed in auth.inc)

**Comment by arnabnaha** [comment]
Thanks Brady...It was extremely helpful...Thanks a lot

**Comment by arnabnaha** [comment]
Truncate and repopulation of globals table done...All working nicely now...have removed the library/auth.inc code that Brady gave. Thanks a lot everyone. Closing it down.
