### ISSUE TITLE
Care Coordination multiple bugs/problems

### ISSUE THREAD

**Issue by samarmeena** [openemr/openemr#3902]
### Care Coordination  > Export Issue
No patient data in search result, thus can not export patients record.
![image](https://user-images.githubusercontent.com/23554168/91969004-1df60980-ed33-11ea-914c-bb68af8a3dec.png)

### Care Coordination > Import Issue
It shows data but when creating a new patient from it, it doesn't import everything. Only import 1 allergies for example.
this was also reported at https://community.open-emr.org/t/ccda-import-not-quiet-right/14243
![image](https://user-images.githubusercontent.com/23554168/91969168-55fd4c80-ed33-11ea-91bd-5ce64fc81f88.png)

### Possible Issues
MySQL queries under CarecoordinationTable.php > function insert_patient
``public function insert_patient($audit_master_id, $document_id)``
same issues are could be in merge function.

for allergies and similar insert function, look under 
``public function InsertAllergies($allergy_array, $pid, $revapprove = 1)``
for insert queries.

```
$q_sel_allergies = "SELECT *  FROM lists WHERE external_id=? AND type='allergy' AND pid=?";
$res_q_sel_allergies = $appTable->zQuery($q_sel_allergies, array($value['extension'], $pid));
```
this cause to insert only one allergy because of data. I have fixed by matching the title of newly inserted data. But I prefer more better solution for this.

similar issues is with other import functions.

### CCDA File for testing
[C-CDA_R2-1_CCD.zip](https://github.com/openemr/openemr/files/5161649/C-CDA_R2-1_CCD.zip)

### Client configuration

- Browser:
- OpenEMR version: v6.0.0-dev
- Operating system: Windows 10

**Comment by tywrenn** [comment]
Not surprised at all that this is happening considering we haven't really done much with Care Coordination
