### ISSUE TITLE
Git Ignore Generated Certs (This is Annoying)

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#3910]
### Describe the problem

Currently 3 files get generated every time I do a docker compose:
`/contrib/util/docker/couchdb-config-ssl-cert-keys/local.ini`
`/contrib/util/docker/ldap-ssl-certs-keys/easy/dhparam.pem`
`/contrib/util/docker/ldap-ssl-certs-keys/easy/server-key.pem`

### Describe the solution you'd like

Gitignore these files so we don't have to deal with them ruining pushing changes.

**Comment by tywrenn** [comment]
@bradymiller

**Comment by bradymiller** [comment]
Those files are in the codebase (except for dhparam.pem which I am guessing is a typo). If we gitignore them, they will go away :)
Are you using most recent codebase?
Still got this issue in my queue, which should simplify things for you (a more basic docker setup): https://github.com/openemr/openemr/issues/3864

**Comment by tywrenn** [comment]
@bradymiller Yep using the most recent one

**Comment by bradymiller** [comment]
Can you push the changes you are getting as a PR? Then can figure out what is going on.

**Comment by bradymiller** [comment]
Guessing will go away if do a docker tear down and rebuild on recent codebase also. But if not, then push a PR with the changes.

**Comment by tywrenn** [comment]
Closing since it was fixed
