### ISSUE TITLE
Refresh token interface

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr#3928]
### Describe the problem

The clients who use an  API don't know when the token is expired.

### Describe the solution you'd like

The logic I found in the API mechanism refreshes the token automatic in the final 10 minutes before the token is expired.
This behavior prevent from the client to know when the token is nearing to expired and  to present message or send to login page.
I think the right solution is new to create new interface that enables to client refresh the token yourself and to manage on the token activity.

**Comment by bradymiller** [comment]
@sjpadgett , Will the planned smart auth on FHIR stuff address this issue?

**Comment by sjpadgett** [comment]
@bradymiller @matrix-amiel 
The token shouldn't refresh itself and is an oversight on our API part. I think was done for testing. New Auth server will handle but this could be easily fixed in the meantime.


> Will the planned smart auth on FHIR stuff address this issue?

I plan both Smart on FHIR and two/three legged OAuth. Client and password grant  types.

**Comment by matrix-amiel** [comment]
@sjpadgett the correction needed to regular API and not just for FHIR, are you planning to fix it soon? thanks!

**Comment by sjpadgett** [comment]
hi @matrix-amiel Hope you and yours are well. Yep, both API's need done however, I believe can be done in same place in existing pre dispatcher.
I can't get to this for a week or so but if you want to take a shot at fixing, i'll review and bring in for you. 
Let me know.

**Comment by matrix-amiel** [comment]
Hi @sjpadgett, Good to hear from you.
I'm a bit busy this week but maybe I'll make it too... the solution of new route for refresh-token sounds the right way?

**Comment by sjpadgett** [comment]
> the solution of new route for refresh-token sounds the right way?

I don't believe we actually create refresh tokens to reauth session. You wouldn't want a separate endpoint to refresh but instead refresh in header. We use password grant type where you'd simply auth a new session when token expires.
For now, i'd mod auth code to not auto refresh the token and let expire the reauth on 401 redirect.

**Comment by matrix-amiel** [comment]
@sjpadgett 
Sorry, but I don't understand how to use the API without "refresh token".
Please help me with the basic scenario of client application - 
1. login with username and password
2. get access token with an expiration time of 1 hour
3. after 55 minutes I need to login again for the new token

What is the next step? to ask the password from user again? save the password in the first time in the JS (serious security issue)?

All the protocol I know ([Oauth](https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/) for example), return in the login refresh token that enables to create new access token without a password.

Maybe there are other solutions... 

Best regards 
Amiel

**Comment by sjpadgett** [comment]
@matrix-amiel 
My plan with in the next couple days is to bring in a new authorization/identity server and OpenId Connect authentication.
Initially will support authorization code flow and a password hybrid(resource grant) These will follow the standards set out in: 
https://openid.net/specs/openid-connect-core-1_0.html
Except, I may not enforce a refresh token(many providers don't, Google for one). Instead, say an auth token is issued with a TTL of 2 minutes where client passes requested scope/claims to auth/identity server for validation and issuance of an identity token plus access token with a TTL of 3 to 10 months.

The authorization server will require a registration process and supports discovery for endpoints and scopes etc. For single sign on of patients and users, registration is mostly already in place and prob won't require further registration.

To your refresh point of current password flow: when you removed the auto refresh and didn't change the issued access token TTL from 1 hour to something more reasonable like 1 month, you're in essence requiring a new access token every hour.
You might want to modify the access tokens TTL in code to get ya by until I can get the proper way for api access sorted out.

You might want to review this issue: https://github.com/openemr/openemr/issues/3956

**Comment by matrix-amiel** [comment]
Hi @sjpadgett 

Moving to openID is a big step for OpenEMR and if the mechanism will enable to connect to the authorization services like AWS Cognito it's will be amazing.
I'm not an expert on authentication, and I've bit tried to read about the correct way to save on valid token with SPA, there are a few ways (for example - https://auth0.com/blog/oauth2-implicit-grant-and-spa/ https://auth0.com/blog/securing-single-page-applications-with-refresh-token-rotation/#OAuth2-and-Securing-SPA-Access-to-APIs).
But creating a valid token for a month sounds problematic for health systems. also in the existing UI if the user does not make action duration an hour your session is expired and he needs new login...

**Comment by sjpadgett** [comment]
> But creating a valid token for a month sounds problematic for health systems.

You'd think so huh @matrix-amiel (my thoughts as well)! However, ONC requires a minimum of 3 months. This is why I believe refresh tokens are redundant and unnecessary. My preference is to force a re authentication with identity server after such a long lived token. But, I will bring this up with rest of community and admins for feedback.

As for AWS Cognito(or any third party auth provider): They will not be needed because OpenEMR will be running our own authorization and identity server/service. For me, this is by far more secure. Allowing auth details to be kept with in the confines of the practice. The OIDC layer will however be easy enough for vendors to hook out of if they wish to implement their own providers.


> if the user does not make action duration an hour your session is expired and he needs new login...

As I said, current workflow needs work however it is my plan to support legacy password grant but more securely.

**Comment by matrix-amiel** [comment]
Ok... probably we do not agree on this point. seems to me irresponsible to leave the browser logged in when the user not doing any action on the screen.
At least we need an interface for determining token in the logout process... I can write it.

Regarding Cognito or another provider, they supply a set of tools like forget the password, 2FA, etc. that can benefit the user and reduce responsibility and support from the community

**Comment by zerai** [comment]
> This is why I believe refresh tokens are redundant and unnecessary.

A refresh token mechanism is mandatory for certification.

> ONC requires a minimum of 3 months

The "3 months value" requirement is for the refresh token only.

![ONC_Schermata_2020-10-21 20-10-45](https://user-images.githubusercontent.com/2405279/96762961-cc383a00-13d9-11eb-9541-3e2968e6384a.png)

**Comment by sjpadgett** [comment]
I think we were speaking to current password grant and third party providers but you're right.
Still, I support refresh (authorization code flow and a hybrid password grant is done) I just don't know how i'll handle current password grant. Fix refresh and keep for legacy or force moving everyone to a device/resource/hybrid.

I'm in the middle of refactor for back end authentication and once I get that done i'll bring in so we can ensure i'm correct in peer review. I still don't believe refresh is all that in an enterprise setting and especially don't trust third party identities being passed around. Then again, I still look forward to Santa every year!

Do you vendors really want to support other authorization providers?

**Comment by matrix-amiel** [comment]
Hi @sjpadgett 
First regarding your question, yes we definitely would like to integrate with 3rd party, Would you think it will be simple after you bring your code?
Would you have an estimated date when your feature will be ready? You recommend me to fix the refresh token issue or waiting to new autherization code?

Thanks
Amiel

**Comment by sjpadgett** [comment]
@matrix-amiel I think you can close this issue now if you want. New auth server resolves.
