### ISSUE TITLE
Clinical Rules and Reminders - Errors in determining rule status (not due, due soon, due, past due)

### ISSUE THREAD

**Issue by hanksterr7** [openemr/openemr#3949]
I found two related issues with how rule/reminder status (i.e. not due, due soon, due, past due) is calculated in `clinical_rules.php`. These issues cause it to be very difficult to design new rules and get predictable results.

First issue:

In test_rules_clinic(), the logic tests a rule target against 3 target dates, in this order:

1. today + the warning interval
2. today
3. today - the past due interval

The logic examines the interval
```
target date less target interval -> target date
```
using the three target date values listed above, checking the `rule_patient_data` table to see if a row in the table exists for the patient that matches each of these three intervals, for the specified category/item pair, and frequency (as defined by the rule target)

So, for example, if the target specifies
```
reminder, prostate cancer screening, completed=yes, frequency > 0, interval 12 months
```
and the rule intervals are
```
warning: 1 month, past due: 3 months
```
then a db query is done looking for at least one row in the `rule_patient_data` table, with `completed=yes`, that happened within these intervals, checked in this order:
```
11 months ago -> 1 month from now
12 months ago -> now
15 months ago -> 3 months ago
```
    
The logic *should* be:
If such a row is found in the db for the first interval, the rule status is set to “not due”, and processing stops.
If not, and a row is found within the second interval, the status is set to "soon_due"
if not, and a row is found within the third interval, the status is set to "due"
otherwise, the status is set to "past_due" (both when no row is found, or a row is found older than 15 months ago)

But what seems to be a bug in the code sets the status to "not due" whenever a matching row is found
```
// send to reminder results
if ($mode == "reminders-all") {
// place the completed actions into the reminder return array
  $actionArray = resolve_action_sql($rowRule['id'], '1');
  foreach ($actionArray as $action) {
    $action_plus = $action;
    $action_plus['due_status'] = "not_due";
```
This is found in two places in the function when `$mode == "reminders-all"`

If I change the code to this instead, I get the desired behavior
```
// send to reminder results
if ($mode == "reminders-all") {
// place the completed actions into the reminder return array
  $actionArray = resolve_action_sql($rowRule['id'], '1');
    foreach ($actionArray as $action) {
      $action_plus = $action;
//$action_plus['due_status'] = "not_due"; // no - do next instead
        if ($dateCounter == 1) {
          $action_plus['due_status'] = "not_due";
        } elseif ($dateCounter == 2) {
          $action_plus['due_status'] = "soon_due";
        } else { // $dateCounter == 3
          $action_plus['due_status'] = "due";
        }
```

Second issue:

As mentioned above, three intervals are checked for each rule target, based on each of the three target dates applied to
`   `target date less target interval -> target date

This works fine as long as target interval is greater than past due interval (such as a target that should happen once a year and which becomes past due if it was last due 15 months ago [i.e. past due interval = 3 months])

But if past due interval is greater than target interval, incorrect rule status determinations happen

Example: 
`   `warning: 1 month, past due: 6 months, target interval: 2 months (i.e. the action needs to have been done in the past two months, but the action is not "past due" unless the action was last done more than 6 months ago. The action is "due soon" if last done between 1 and 2 months ago). 
The three intervals are then:
`   `(today + 1 month) - 2 months -> (today + 1 month) ==> not due
`   `today - 2 months -> today ==> due soon
`   `(today - 6 months) - 2 months -> (today - 6 months) ==> due
`   `else ==> past due

If an entry exists in rule_patient_data with a date of 3 months ago, it will not match any of the intervals listed above and the rule will show as "past due", when in fact it should show as "due"

This bug happens because the test intervals are built from
`   `target date less target interval -> target date

The issue is fixed by building the intervals instead from
`   `target date less target interval -> today

In the example above, the test intervals would be
`   `(today + 1 month) - 2 months -> today => not due
`   `today - 2 months -> today ==> due soon
`   `(today - 6 months) - 2 months -> today ==> due
`   `else ==> past due

This is fixed in clinical_rules.php, sql_interval_string()
The current code builds:
`   `$dateSql = "AND (" . add_escape_custom($date_label) .
`   `" BETWEEN DATE_SUB('" . add_escape_custom($dateTarget) .
`   `"', INTERVAL " . escape_limit($intervalValue) .
`   `" YEAR) AND '" . add_escape_custom($dateTarget) . "') ";

The issue is the second occurence of $dateTarget
If instead, I define
`   `$dateTarget1 = date('Y-m-d H:i:s');
and change the code to what is below, I get the desired behavior
`   `$dateSql = "AND (" . add_escape_custom($date_label) .
`   `" BETWEEN DATE_SUB('" . add_escape_custom($dateTarget) .
`   `"', INTERVAL " . escape_limit($intervalValue) .
`   `" YEAR) AND '" . add_escape_custom($dateTarget1) . "') ";

This change is applied all seven expression builds in the function (ie. for year, month, week, day, hour, minute and second). Not sure if it should also be applied to "flu season"

With this change, the desired target/action status is properly calculated

I’m looking at version 5.0.2 patch 4

**Comment by stephenwaite** [comment]
Hi @hanksterr7 , this is great detail thank you! Now the next step is for you to make the code changes and open a pull request :)

**Comment by ophthal** [comment]
I believe these changes are also in https://github.com/openemr/openemr/pull/2928.  Seems the CR functions were added to hit a MU criteria and based on the issues in the PR and what you have found, they may become a truly powerful when updated.

**Comment by bradymiller** [comment]
bump

**Comment by stephenwaite** [comment]
bump
