### ISSUE TITLE
Adding Provenance Resource

### ISSUE THREAD

**Issue by vishnuyar** [openemr/openemr#3957]
I am planning to add Provenance Resource. I have looked at https://www.hl7.org/fhir/provenance.html but unable to get a clear view on how to implement in for OpenEMR, any pointers will be appreciated.

**Comment by bradymiller** [comment]
hi @vishnuyar , Rec focusing on the USCore, which generally simplifies things:
https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-provenance.html

**Comment by sjpadgett** [comment]
Hi @vishnuyar This may help some in understanding the basic why for this profile.https://build.fhir.org/ig/HL7/US-Core-R4/basic-provenance.html

Like much of where the FHIR spec is heading and is now, overly complicated! In the end and for our purposes, our provenance will be the last providers organization for say a problem/issue or allergy/immunization(the two i'd focus) etc.

And thanks so much for taking this on!

**Comment by vishnuyar** [comment]
Implementing the provenance resource for AllergyIntolerance 
some bugs encountered in the AllergyIntoleranceService.php - fixed and did PR for the same

Just wanted to know if this an acceptable data when adding data to Provenance resource

For Agent
Author should be the user adding the issue 
The table lists has the data related to allergy and contains column 'user' -- can this is be used to fill the who in agent
and 'behalf of; can be filled with 'organization'  column from the users table

**Comment by vishnuyar** [comment]
Facility may be a better value instead of organization from the user table to fill the data for 'on behalf of'
agent type will be 'author' since we are taking the user details and I am assuming only practitoner enters the issue details in openemr.

**Comment by bradymiller** [comment]
hi @vishnuyar ,
Agreed that your proposal would definitely be a good working starting point. Note that facility and organization are basically the same thing (the Organization FHIR service is using a Facility service).

**Comment by vishnuyar** [comment]
@bradymiller @sjpadgett . As the AllergyIntolerance Provenance Resource and CapabilityStatement has been approved. 

How can I contribute more towards 
https://www.open-emr.org/wiki/index.php/OpenEMR_Certification_Stage_III_Meaningful_Use

I will continue to add more fixes to the FHIR Resources as and when I find them.
