### ISSUE TITLE
v6.0.0-dev globals dosen't save nor page reload

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#3977]
### Describe the bug
v6.0.0-dev globals don't save nor page reload. When trying to save any value to the globals, upon clicking save. The page hangs. The tab changes title to unknown. When going back into the globals from the menu link. The page does load but the value that was entered is not saved. 

### To Reproduce

![image](https://user-images.githubusercontent.com/834958/96311264-18007300-0fd7-11eb-9d8e-c5a00bbe19fc.png)

1. Select globals from the menu
2. Click save

### Expected behavior
Save value(s) entered. 

### Client configuration

- Browser: All
- OpenEMR version: 6.0.0-dev
- Operating system: ubuntu 18.04

**Comment by stephenwaite** [comment]
hi @juggernautsei, can't confirm this on the demos

did you see this recent conversation with Brady and Daniel?
https://community.open-emr.org/t/getting-a-white-screen-when-saving-demographics-in-502/15277/8

**Comment by juggernautsei** [comment]
Not my issue. I have done server installed of the dev and it happens over and over. I have spoken with another developer that gets the same thing on 5.0.2(4).  This is a clean install, not an upgrade.

**Comment by stephenwaite** [comment]
maybe it's a permissions issue in the `logs_and_misc` subdir of the documents folder under sites?

**Comment by juggernautsei** [comment]
I am checking the values for 
L 130
if (array_key_exists('form_save', $_POST) && $_POST['form_save'] && $userMode) {
var_dump($_POST['form_save']);  NULL
var_dump($userMode); false
should it be NULL and fasles?


When I do a var dump on 

![image](https://user-images.githubusercontent.com/834958/96312305-5008b580-0fd9-11eb-83df-de7e17a60397.png)

**Comment by stephenwaite** [comment]
not sure, might be a windows issue then

**Comment by juggernautsei** [comment]
There is nothing in the error logs and even if debugging is enabled. Nothing shows up. It is not a windows issue because I have a Linux ubuntu 20.14 box and I get the same result.

**Comment by stephenwaite** [comment]
it's working fine at https://eight.openemr.io/a/openemr/interface/login/login.php?site=default
when enable weno

is there a specific global you're having this issue with?

**Comment by juggernautsei** [comment]
I found this 
OpenEMR Error : Decryption failed authentication., referer: http://e.healthbrigade.org/interface/super/edit_globals.php
OpenEMR Error : Key creation is not working - Exiting., referer: http://e.healthbrigade.org/interface/super/edit_globals.php
What causes this?

**Comment by stephenwaite** [comment]
https://github.com/openemr/openemr/blob/master/src/Common/Crypto/CryptoGen.php

**Comment by stephenwaite** [comment]
perms are good above but what about the `methods` subfolder of `logs_and_misc`

**Comment by juggernautsei** [comment]
Here is that folder.
![image](https://user-images.githubusercontent.com/834958/96316349-8bf14a00-0fdc-11eb-8361-20733f887dee.png)

**Comment by stephenwaite** [comment]
that folder looks old, 2018?

**Comment by juggernautsei** [comment]
That is was received in the download.

**Comment by stephenwaite** [comment]
https://community.open-emr.org/t/getting-a-white-screen-when-saving-demographics-in-502/15277/6

**Comment by juggernautsei** [comment]
These installations are on two different machines and both are Linux ubuntu boxes. But you are saying to remove the keys and the system will gen a new key?

**Comment by stephenwaite** [comment]
prob should make a backup of the keys just in case

**Comment by bradymiller** [comment]
Before everybody gets in the habit of removing keys :)
Couple quick things to think about
1. The keys stored on the drive are used to encrypt sensitive data in database and when turn on encryption in logging. When keys are deleted that information will be lost forever.
2. The keys stored in the database in the keys sql table are used to encrypt all data stored on the drive (like patient documents, for example). When those keys are deleted that information will be lost forever.
3. The keys stored on the database and drive are related to each other since they keys on the drive are actually encrypted by the keys on the database. So if you try to take documents directory from a different installation and try to make it work from a different database installation, then will no longer be able to access to the keys stored on the drive, and thus things will break whenever trying to encrypt/decrypt senstive stuff in the database such as passwords in the globals gui.
Hope this helps.

**Comment by juggernautsei** [comment]
In my case, the installation is a new install where I installed the program updated the code then tried to connect it to the old database and it would not work right (didn't know about the encryption stuff). So, I ran the installation again to create a new database. The system came up but the globals would not save. (not knowing the key situation). 
So, what does this mean for doing upgrades? As long as the logs_and_misc/methods/ keys are not disturbed during upgrades. The installation should stay intact? Or make sure that the database and keys stay together.  Now that I am aware of system operations. I will keep this in mind when working with having to code updates with an existing database.

**Comment by bradymiller** [comment]
Basically should consider the database and the documents directory as one singular entity that should never be parted or interchanged. Then upgrading will be just fine. Then would avoid ever needing to remove keys (ie. should never be in a position where keys need to be removed). And if ever do remove keys (again, this should never be needed), always save them somewhere first.
