### ISSUE TITLE
Query Error on Patient Medical Record DashBoard

### ISSUE THREAD

**Issue by vishnuyar** [openemr/openemr#3987]
### Describe the bug

After selecting the patient, dashboard opens and query error is shown

### To Reproduce

 Got to https://eight.openemr.io/a/openemr
Login with 'admin' and 'pass'
Select the patient 'Phil Belford'
The error will be shown on patient dashboard

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by bradymiller** [comment]
my mistake (i messed up on a recent entry in the upgrade script). Fixed it here:
https://github.com/openemr/openemr/commit/b63804755252ffee6ef71d7745348645919ab3f5

Confirmed now working, so will close this issue.

thanks for the report!
