### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by ckahiaku** [openemr/openemr#399]
when I try login after a new openemr installation the attached is the error I get.

ERROR: insert failed: insert into log ( date, event, user, groupname, success, comments, crt_user, patient_id) values ( NOW(), 'login','admin','Default','1','success: ::1',NULL,'NULL')

Error: Incorrect integer value: 'NULL' for column 'patient_id' at row 1

**Comment by MatthewVita** [comment]
Which version of OpenEMR are you running? What is the database version?

Thanks,
Matthew

**Comment by bradymiller** [comment]
As an aside, this is likely a sql_mode issue.

@ckahiaku , let us know if you are still having issues. If no reply, then I plan to close this issue.
thanks,
-brady

**Comment by ckahiaku** [comment]
Thank you Brady,
I have been able to Resolve  However I get this after Login "Table 'openemr.openemr_postcalendar_events' doesn't exist"

**Comment by bradymiller** [comment]
It sounds like issues with sql_mode which can cause table loss. What version of OpenEMR are you using?

**Comment by ckahiaku** [comment]
I am using version 4.1.2

**Comment by bradymiller** [comment]
Is this a new install? If so, why are you not using 4.2.2?

**Comment by bradymiller** [comment]
btw, the fix for 4.1.2 will be to set sql_mode setting for your mysql to blank (sql_mode = '') in the mysql my.cnf config file. And then you will need to reinstall OpenEMR again.

btw, 4.2.2 doesn't have this issue.

**Comment by bradymiller** [comment]
Scheduling this issue for removal. If this issue is still not resolved, then just let us know.
