### ISSUE TITLE
Query Error on opening a patient demographics

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#4010]
Hi,
On opening any patient demographics, its showing a query error like this as shown below - 

![Query_error](https://user-images.githubusercontent.com/1074948/98152236-67abcd80-1ef7-11eb-9471-748dbdf969ed.png)

please fix this error..as none of the appointment side windows/medications/prescription windows on the demographics page is visible

Thanks 
Dr. Arnab Naha

**Comment by stephenwaite** [comment]
hi @arnabnaha , need a space after 0 here
https://github.com/openemr/openemr/blob/master/interface/patient_file/summary/demographics.php#L1456
so should be
```
                                "AND documents.foreign_id=? AND documents.deleted = 0 " .

**Comment by arnabnaha** [comment]
Thanks @stephenwaite 

Its fixed and done
