### ISSUE TITLE
Fix Raspberry Pi Docker Builds

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#4012]
The purpose of this issue is to fix the docker ARM builds to work with Raspberry Pi. Currently they do not work for it which is what I'm planning to fix.

Things Needed To Change To Get It Working:
- [x] Merge in #3892 to help with speed as that is causing a lot of issues
- [x] Change the `phpmyadmin/phpmyadmin` image to just `phpmyadmin` for ARM Docker File
- [x] Disable CouchDB on 32-bit ARM builds as it isn't supported (we might want to create 2 different docker files, one for 32 bit and one for 64 bit)
- [x] Convert from regular node SASS to dart SASS as regular node SASS isn't supported on ARM
- [ ] Fix and/or disable CCDA service

**Comment by bradymiller** [comment]
@tywrenn , 
Just brought in commits based on your work (made you author on the commits). ccda stuff was not breaking the build, so didn't see reason to consider removal of it. I was not able to test the 64bit docker-compose.yml since was unable to get the 64bit beta raspberry pi OS working.

**Comment by tywrenn** [comment]
@bradymiller I'll be testing 64 bit out yet do note the fact that that is beta so support for it is not guaranteed.

**Comment by tywrenn** [comment]
@bradymiller I can confirm 64 bit RPI works using the 64 bit docker.

Closing this now

**Comment by bradymiller** [comment]
![Uploading 2DV.gif…]()
