### ISSUE TITLE
Rest API broken

### ISSUE THREAD

**Issue by benmarte** [openemr/openemr#4016]
### Describe the bug

Rest API returning 500 error when performing authentication

### To Reproduce

- get latest files from repo as of this writing commit is at 7908307
- cd into docker/development-easy
- Run `docker-compose up`
- once app is running make sure Rest API is enabled
- try to auth with postman using the Rest API endpoint as outlined [here](https://github.com/openemr/openemr/blob/master/API_README.md#post-apiauth)
- postman responds with a 500 error

### Expected behavior

Be able to authenticate using the Rest API

### Additional info

Apache error log:

```
[Sun Nov 08 16:47:46.329721 2020] [php7:notice] [pid 31] [client 172.23.0.1:45592] PHP Fatal error:  Uncaught LogicException: Key path "file:///var/www/localhost/htdocs/openemr/sites/api/documents/certificates/public.key" does not exist or is not readable in /var/www/localhost/htdocs/openemr/vendor/league/oauth2-server/src/CryptKey.php:52\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/vendor/league/oauth2-server/src/ResourceServer.php(50): League\\OAuth2\\Server\\CryptKey->__construct('file:///var/www...')\n#1 /var/www/localhost/htdocs/openemr/_rest_config.php(209): League\\OAuth2\\Server\\ResourceServer->__construct(Object(OpenEMR\\Common\\Auth\\OpenIDConnect\\Repositories\\AccessTokenRepository), '/var/www/localh...')\n#2 /var/www/localhost/htdocs/openemr/apis/dispatch.php(31): RestConfig::verifyAccessToken()\n#3 {main}\n  thrown in /var/www/localhost/htdocs/openemr/vendor/league/oauth2-server/src/CryptKey.php on line 52
```

### Client configuration

- Browser: Chrome & Postman
- OpenEMR version: 6.0.0-dev
- Operating system: Windows/OSX

**Comment by sjpadgett** [comment]
https://community.open-emr.org/t/v6-authorization-and-api-changes-afoot/15450

**Comment by benmarte** [comment]
@sjpadgett Awesome just wanted to make sure you guys were aware since I had an older version that was working which I updated to the latest version today and ran into this issue.

Feel free to close this if you deem it's unnecessary, thanks.

**Comment by sjpadgett** [comment]
we'll just leave open for search as other will certainly be looking. thanks
