### ISSUE TITLE
Additional ICD10 code for COVID-19

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#4017]
#3377 added primary ICD10 code for COVID-19.
Based on this [WHO emergency use statement](https://www.who.int/classifications/icd/covid19/en/), looks like we should also include `U07.2 COVID-19, virus not identified`

**Comment by stephenwaite** [comment]
forgot that it's in 502 but can add it to the v6 upgrade script 
https://github.com/stephenwaite/openemr/blob/rel-502/sql/patch.sql#L309-L313
