### ISSUE TITLE
Tabs: Form menu

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#402]
Select a patient visit from the Calendar and the Patient Frame/tab opens as well as the Past Encounters and Documents tab.  In the Past Encounters and Documents tab, select the encounter you wish to open.  The menu to navigate through the forms sits at the top of this frame/tab now. 

    Encounter Summary    Miscellaneous    Administrative    Clinical

 Select the form you want from these - this works fine.  

The bug: If you opt instead to select a form from the new TOP tab menu, Patients->Visit Forms->SELECT ONE, the form opens but the submenus no longer work.  I am getting a "TypeError: parent.Forms is undefined[Learn More]" error.

**Comment by bradymiller** [comment]
I also confirmed this bug and noted an additional likely related bug:

In the submenu, the 'Encounter Summary' link does not work whenever a form is opened and produces the following js error:
TypeError: top.window.parent.left_nav.loadFrame2 is not a function

Note that link should go back to the encounter screen.

**Comment by bradymiller** [comment]
Posted PR for issue reported above by @ophthal

**Comment by bradymiller** [comment]
oops, here's the link to the fix:
https://github.com/openemr/openemr/pull/405

**Comment by bradymiller** [comment]
posted following PR (this is separate issue from the above PR) to fix the issue I reported above with the broken 'Encounter Summary' link:
https://github.com/openemr/openemr/pull/406

**Comment by bradymiller** [comment]
Both above fixes tested well, so brought them into the codebase.
