### ISSUE TITLE
Improve E2E tests

### ISSUE THREAD

**Issue by spyrkob** [openemr/openemr#4023]
I noticed there is setup for running e2e tests in OpenEMR, but there's not many tests. I was wondering if there were any plans to build up that testsuite? Would it be useful to contribute some tests like: https://github.com/openemr/openemr/compare/master...spyrkob:e2e_tests ?

**Comment by bradymiller** [comment]
hi @spyrkob , More e2e tests would be awesome! the more tests, the better :)

**Comment by spyrkob** [comment]
Great :) I linked my initial test and if it looks good, I'll try adding some more.

Are there any areas that testing would be most beneficial?

**Comment by stephenwaite** [comment]
reopening
