### ISSUE TITLE
Patient photo and id after 6.0 upgrade broken

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4025]
### Describe the bug

What the heck
![image](https://user-images.githubusercontent.com/1859985/98761675-f4490680-23a3-11eb-8e5a-899d003269d9.png)

**Comment by tywrenn** [comment]
This should've been overhauled ages ago lol

**Comment by sjpadgett** [comment]
It's tied back to the upload in documents. That's where issue begins as current images in database work. It's any new uploads that fail...

**Comment by bradymiller** [comment]
this is my fault. looks like i missed a spot when converting to using labels rather than filename for documents. Should be a quick fix and will put it on my todo list.

**Comment by sjpadgett** [comment]
![image](https://user-images.githubusercontent.com/1859985/99561933-8305e680-2995-11eb-9ea3-7c610ce411eb.png)
