### ISSUE TITLE
increase varchar size for code_text and code_text_short in codes tables

### ISSUE THREAD

**Issue by lthrhx** [openemr/openemr#4038]
### Describe the problem

Facility bills for ABA therapy and their CPT codes run long compared to space given. Their code_text_short averages 48 characters and their code_text bumps into 441 characters.

code_text_short examples:
`Adaptive Behavior Treatment with Protocol Modification`
`Behavior Identification Supporting Assessment`
`Multiple-family group adaptive behavior treatment guidance`
etc...

code_text example:
`administered by a physician or other qualified healthcare professional, each 15 minutes of the physician’s or other qualified healthcare professional’s time face-to-face with patient and/or guardian(s)/caregiver(s) administering assessments and discussing findings and recommendations, and non face-to-face analyzing past data, scoring/interpreting the assessment, and preparing the report/treatment plan.`

### Describe the solution you'd like

Could the varchar field size for `code_text_short` in `codes` table be increased from 24 to 255 as the default? It shouldn't affect the table size ( I think).
Could the varchar field size for `code_text` in `codes` table be increased from 255 to 1024 as the default? It would add an extra byte of storage space to each record stored in that field ( I think).

Following the steps in this wiki for inputting the data: [https://www.open-emr.org/wiki/index.php/Code_Types](https://www.open-emr.org/wiki/index.php/Code_Types)

**Comment by stephenwaite** [comment]
hi @lthrhx , looks like all we'd have to do is bump `code_text` to `1024`
from `database.sql`
```
CREATE TABLE `codes` (
  `id` int(11) NOT NULL auto_increment,
  `code_text` varchar(255) NOT NULL default '',
  `code_text_short` varchar(255) NOT NULL default '',
  `code` varchar(25) NOT NULL default '',
  `code_type` smallint(6) default NULL,
  `modifier` varchar(12) NOT NULL default '',
  `units` int(11) default NULL,
  `fee` decimal(12,2) default NULL,
  `superbill` varchar(31) NOT NULL default '',
  `related_code` varchar(255) NOT NULL default '',
  `taxrates` varchar(255) NOT NULL default '',
  `cyp_factor` float NOT NULL DEFAULT 0 COMMENT 'quantity representing a years supply',
  `active` TINYINT(1) DEFAULT 1 COMMENT '0 = inactive, 1 = active',
  `reportable` TINYINT(1) DEFAULT 0 COMMENT '0 = non-reportable, 1 = reportable',
  `financial_reporting` TINYINT(1) DEFAULT 0 COMMENT '0 = negative, 1 = considered important code in financial reporting',
  `revenue_code` varchar(6) NOT NULL default '' COMMENT 'Item revenue code',
  PRIMARY KEY  (`id`),
  KEY `code` (`code`),
  KEY `code_type` (`code_type`)
) ENGINE=InnoDB AUTO_INCREMENT=1;

**Comment by bradymiller** [comment]
could just change those both to text (in both codes and codes_history tables)

**Comment by lthrhx** [comment]
Thank you for the prompt response.

@stephenwaite sorry, forgot to mention I am running v5.0.2 (4) 
I did get an email about an v5.0.2 (5) release, but I don't see it on github yet.
Strange, `code_text_short` was set to 255 and then reduced to 24, surprised that didn't break things.

@bradymiller Setting to `text` would certainly allow for some extra descriptive names, but would loose the ability to index if that would ever need to be a thing ( seems unlikely). 

I don't know the historical context as to why those field sizes were selected in the first place. As long as it doesn't break anything, whichever path you all choose is OK with me, as long as there is room to store these ever increasing names and descriptions.

Along similar tracks and possible consistency, should `icd10_dx_order_code` and other code-similar tables be the same?

**Comment by stephenwaite** [comment]
no prob @lthrhx , there's a patch for 5.0.2 on the open-emr.org dowloads, rel-502 is updated on github

good pt about indexing but unlikely as you said

good ? re: `icd10_dx_order_code`, looks like based on below record layout we could lose 23 chars from the long descr :O
![Screenshot from 2020-11-16 11-11-36](https://user-images.githubusercontent.com/5618372/99277988-831eae80-27fc-11eb-955f-506e1c1a4d0c.png)
