### ISSUE TITLE
Be on the lookout. Missing site id

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4041]
### Describe the bug
Unexpected missing site id message.

### To Reproduce
v6.0.0 master as of today. Noted in two areas so far that the session gets lost or stepped on resulting in the missing site id message.
- First noted in an LBF with nation notes. Popup the nation note and leave up for awhile where when returning/closing dialog, session is gone.
- I noted the same issue minus dialog use in Document Templates where presence issue of missing site id in same manner ie a short timeout or lost of session.

Need some more eyes on or testing and please note them here.

**Comment by stephenwaite** [comment]
![Screenshot from 2020-11-16 21-58-27](https://user-images.githubusercontent.com/5618372/99340882-e1787b00-2856-11eb-8c2a-49a83206c280.png)

**Comment by sjpadgett** [comment]
you'd think we'd slip a dog or two in every now and then:)

**Comment by sjpadgett** [comment]
I've removed the blocking on this because it's is an issue that I simply can't easily pinpoint and doesn't prevent overall operation. More of an annoyance. 

While testing and whenever one is in code, take a look for any JS calls or form submits that may be in need of a top.restoreSession() call. More harmful with not being there than a quick refresh.
Thanks

**Comment by stephenwaite** [comment]
hi @sjpadgett , also noticed that if you start from the billing manager and select a patient from there the encounter doesn't load properly, ie no forms

but if you select a patient from the finder first it will load correctly from the billing manager

**Comment by sjpadgett** [comment]
Yep, I looked at this once before and I believe it is a setPid() issue. Something to do with if current session pid is 0.
Prob needs to be a separate issue.

**Comment by sjpadgett** [comment]
@stephenwaite Now I remember. The feature works however if the encounter is missing the pid then you'll get:
![image](https://user-images.githubusercontent.com/1859985/99583362-5eb80300-29b1-11eb-9ea2-e39178b25355.png)
In my case, it came from auto generating encounters from my lab modules for orphaned orders. It was a bug I fixed with the leftover bad encounters left behind to befuddle me once every couple months.:).

So note if there is a patient listed in the billing manager item to tell if you have orphaned encounter for one reason or another.
Could be a bug with auto encounters from appointments check in. Surely worth a retest and/or watching.

**Comment by stephenwaite** [comment]
not sure we're talking about the same thing

**Comment by sjpadgett** [comment]
You're right! I see it now. Back to init of pid

**Comment by sjpadgett** [comment]
Yay, at least I was right about the session pid being set to zero by time it gets to encounter form. So I suspect a session write w/o a session start somewhere.

**Comment by stephenwaite** [comment]
so how tricky is that to find, wouldn't seem like to many files are loaded if go str8 to billing manager?

**Comment by sjpadgett** [comment]
It's happening in setencounter() of encounter_top.php. I should get it spotted here soon.

**Comment by sjpadgett** [comment]
Look what we forgot in globals @bradymiller 
```
if (!empty($_GET['pid']) && empty($_SESSION['pid'])) {
    $_SESSION['pid'] = $_GET['pid'];
} elseif (!empty($_POST['pid']) && empty($_SESSION['pid'])) {
    $_SESSION['pid'] = $_POST['pid'];
}
```
We're in a session write close state here at times. We knew this was worrisome at the time and I forgot about it. Let's blame Tyler:)
Anyway, this is a bug for sure!

**Comment by bradymiller** [comment]
Pretty sure we allow write to session for login though where this session is set (so that session shouldn't ever be empty on other uses of globals during the session).

**Comment by bradymiller** [comment]
oh wait, this is not the site id. agree this needs to be looked into :)

**Comment by sjpadgett** [comment]
The sessions are fine best I can tell but this particular globals call is from encounter top where the pid GET var is meant for opening a new form. So you can see how that blows up session integrity when we have an un-init'ed session but we do have the $_SESSION supers in scope.
You want to fix or me?

**Comment by bradymiller** [comment]
thanks for catching and fixing this! code looks good to me.

will plan a look through interface/globals.php to ensure no other session writes needed (of course, I did this in the past and see how well that worked :) )

**Comment by bradymiller** [comment]
I'm still all for blaming Tyler though :)

![tenor (55)](https://user-images.githubusercontent.com/278968/99621762-891fb580-29dd-11eb-8f7e-1d5ec710b789.gif)

**Comment by sjpadgett** [comment]
Tyler it is! I'll include in my next PR.

**Comment by stephenwaite** [comment]
https://github.com/openemr/openemr/commit/0c109b88a20c34aa6215b03d2a2adf9292593f00

**Comment by stephenwaite** [comment]
there may be other issues down the road but let's close for now :)
