### ISSUE TITLE
Recall Board Table Format 

### ISSUE THREAD

**Issue by kchapple** [openemr/openemr#4046]
### Describe the bug

The recall board table body is shown above the table headers.

### To Reproduce
<img width="1335" alt="Screen Shot 2020-11-19 at 3 34 32 PM" src="https://user-images.githubusercontent.com/271809/99722075-1dd9f000-2a7e-11eb-939e-854d27fa579d.png">

1. Add a Recall board
2. Add a recall
3. See data on top and headers below

### Expected behavior
Headers should be on top

### Client configuration

- Browser: Firefox
- OpenEMR version: master 6.0
- Operating system: Mac

**Comment by sjpadgett** [comment]
Oh No! Just when I finally am able to wrap my head around LTR and RTL we now have UTD and DTU!:)

**Comment by kchapple** [comment]
🤣🤣🤣 Oh, to live in one dimension only.
