### ISSUE TITLE
Clinical Rules and Reminders - Rule continues to be evaluated after targets are deleted

### ISSUE THREAD

**Issue by hanksterr7** [openemr/openemr#4050]
If rule target is deleted, the method = target_interval row in rule_target table persists 

This causes rule to continue, inappropriately, to be evaluated

Repro: create a new rule. Define demographic filter that should evaluate to true for a patient. Also, define rule action. Observe that the rule does not show in Reminders (edit) list. Add a rule target. Rule now shows in Reminders (edit) list. Delete the target. Rule continues to show in Reminders (edit) list.

Fix: ignore the method = target_interval rows when determining if targets exist. Achieved via:
Replace

function returnTargetGroups($rule)
{
    $sql = sqlStatementCdrEngine("SELECT DISTINCT `group_id` FROM `rule_target` " .
    "WHERE `id`=?", array($rule));

with

function returnTargetGroups($rule)
{
    $sql = sqlStatementCdrEngine("SELECT DISTINCT `group_id` FROM `rule_target` " .
    "WHERE method <> 'target_interval' and `id`=?", array($rule));

**Comment by stephenwaite** [comment]
bump
