### ISSUE TITLE
Global Error

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#4052]
Hi,
whenever I am trying to save after making a change in globals - in the Rx page mainly - after saving the changethe page gets blank upto the point of no return. 

The error log shows this - 
[Sun Nov 22 07:58:29.287735 2020] [php7:notice] [pid 3664:tid 1832] [client ::1:51758] OpenEMR Error : Decryption failed authentication., referer: http://localhost/openemr/interface/super/edit_globals.php
[Sun Nov 22 07:58:29.288734 2020] [php7:notice] [pid 3664:tid 1832] [client ::1:51758] OpenEMR Error : Key creation is not working - Exiting., referer: http://localhost/openemr/interface/super/edit_globals.php

kindly help
Dr. Arnab

**Comment by bradymiller** [comment]
hi @arnabnaha ,
Guessing you did something (process of upgrading or back/restoring) that affected your keys in sites/default/documents/logs_and_misc :
https://community.open-emr.org/t/getting-a-white-screen-when-saving-demographics-in-502/15277/5

**Comment by arnabnaha** [comment]
This is fixed
