### ISSUE TITLE
Document Date Error

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#4053]
Hi,
I uploaded 3 documents against my patient in the medical records section of the document uploader. I assigned the documents to the encounter but the date as shown on the encounter summary screen against the documents are as - 00/00/0000 instead of 18/11/2020.

screenshot - 
![document_error](https://user-images.githubusercontent.com/1074948/99892293-851fbc00-2c99-11eb-97e4-34eb0f643a14.jpg)

kindly help with this error and ways to fix it.

Dr. Arnab

**Comment by sjpadgett** [comment]
Worked for me on current master however, we need to get the title back from document file name and not file path. @bradymiller 

![image](https://user-images.githubusercontent.com/1859985/99923999-6a376100-2d06-11eb-8fbd-e6c123268366.png)

I just did the one file so.

**Comment by sjpadgett** [comment]
@bradymiller I fixed this but forgot to bring back for first patch. PR #4222
I'll close from PR then cherry pick.

**Comment by sjpadgett** [comment]
done. 
I like these reminders that was GSoc I believe...

**Comment by stephenwaite** [comment]
think @tywrenn added that stale bot :)

**Comment by sjpadgett** [comment]
yeah, I miss Ty:)

**Comment by bradymiller** [comment]
three minion cheers for @tywrenn !!!
(i still remember the day when my phone beeped/buzzed more than a hundred times straight when he started the stale feature :) )

![2DV](https://user-images.githubusercontent.com/278968/109438447-e95fc380-79de-11eb-8e5c-da59b7fce413.gif)
