### ISSUE TITLE
FHIR Capability Statment giving 401 Error

### ISSUE THREAD

**Issue by vishnuyar** [openemr/openemr#4055]
### Describe the bug

FHIR Capability Statement should be available without any authorization.

### To Reproduce
Go to https://two.openemr.io/openemr/apis/default/fhir/metadata

### Expected behavior

FHIR Capability statment without any authorization

**Comment by bradymiller** [comment]
@vishnuyar , Thanks for reporting this. Looks like something we broke on the api refactoring for oauth. @sjpadgett , I'm happy to take this on (I think i have an idea of how to do this) if your busy with other stuff (i am pretty sure you are busy with other stuff :) ).

**Comment by sjpadgett** [comment]
If you want to fix @bradymiller by all means. I'm just happy we have a capability statement even if nobody can see it!:)
Again thanks @vishnuyar for all your help.

**Comment by vishnuyar** [comment]
@bradymiller ,@sjpadgett
You have thanked me enough for this year and next :))). As always, I am glad that I am contributing to OpenEMR. 
I wanted to add the oauth details to the capability statement and came across the issue.  
Working towards smart of fhir invocation using OAuth
