### ISSUE TITLE
ONC API Testing (Inferno)

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4077]
We probably need to setup a testing server on our Demo network or I can setup on my domain. (Docker is best choice here)

A testing plan synopsis/summary needs to be developed but, I recommend and until I can complete the SMART requirements, we start testing our FHIR U.S core resource endpoints. I'm pretty sure some will have to be touched.

I'm looking for some volunteers.. The main goal is to try and get ahead of any unforeseen major issues with the API so all the folks that are gearing up their FHIR applications and clients supporting OpenEMR can concentrate on their goals and not worry with too many bugs outside their control.(I suppose I could fix my bug of run on sentences in meantime.:)).

For those vendors looking to use the APIs, now'd be a good time to help out where i'll try to be as responsive as possible to your input.

Thanks all.

References: 
- https://inferno.healthit.gov/inferno/
- https://www.healthit.gov/test-method/standardized-api-patient-and-population-services-0

**Comment by adunsulag** [comment]
I missed this issue when I posted my Inferno Test results.  @sjpadgett should I close my issue and merge the results into this one?

**Comment by sjpadgett** [comment]
@adunsulag I'll just close this issue with a reference to yours.
See
https://github.com/openemr/openemr/issues/4120
For follow up to this issue
