### ISSUE TITLE
Various menu wording improvements

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#4078]
Various menu wording improvements for OpenEMR Patch 5:

Miscellaneous > "Ofc Notes" would be clearer as "Office Notes"
	
Miscellaneous > "BatchCom" would be clearer as "Batch Communication Tool"

Administration > "Addr Book" would be clearer as "Address Book"

Popups > "Appts" would be clearer as "Appointments"

**Comment by Chips1234** [comment]
Hello, I would like to work on this issue.
