### ISSUE TITLE
Is there a way to update 'OpenEMR Development With VirtualBox' official video

### ISSUE THREAD

**Issue by viradhanus** [openemr/openemr#4089]
I tried to start contributing to the project referring [CONTRIBUTING.md](https://github.com/openemr/openemr/blob/master/CONTRIBUTING.md#code-contributions-local-development)

Here I'm stuck with the below step since there is no docker-compose.yml file available. 
3. Run `docker-compose up` from your command line

I think we should update the CONTRIBUTING.md file. Yeah?

**Comment by stephenwaite** [comment]
hi @viradhanus , `Step 2. cd openemr/docker/development-easy` ?

**Comment by viradhanus** [comment]
I tried but got this error.
![Screenshot from 2020-12-08 21-33-22](https://user-images.githubusercontent.com/59219626/101507987-2cd90180-399d-11eb-8bde-9aeea49af476.png)
I watched [this video](https://www.youtube.com/watch?v=Gb7PB0c5_pA&ab_channel=OpenEMR) which is on the official OpenEMR Youtube channel. At that time the video recorded, there was docker-compose.yml file in the main repository itself. I think its better to include the new changes in the video description also if possible. :pleading_face:

**Comment by bradymiller** [comment]
hi @viradhanus ,
Looks like you need to get docker and docker-compose working in your environment. There is a really neat script here that sets up a whole bunch of stuff in most popular linux environments:
https://github.com/openemr/openemr-devops/tree/master/utilities/openemr-env-installer

**Comment by viradhanus** [comment]
@bradymiller Sure Sir, I will try with openemr-env-installer. Hence I will close this now. Thanks a lot @bradymiller @stephenwaite :+1:

**Comment by viradhanus** [comment]
@bradymiller Sure Sir, I will try with openemr-env-installer. Hence I will close this now. Thanks a lot @bradymiller @stephenwaite :+1:

**Comment by bradymiller** [comment]
@robertdown , is there a way to modify the description for this video:
https://www.youtube.com/watch?v=Gb7PB0c5_pA&ab_channel=OpenEMR

with something like:
```
Note that the docker-compose.yml file discussed in the video was moved to the docker/development-easy/ directory.
```

**Comment by viradhanus** [comment]
Description is up to date.
