### ISSUE TITLE
Snomed RF2 support

### ISSUE THREAD

**Issue by robertogagliotta** [openemr/openemr#410]
This September 2016 US Edition of SNOMED CT marks the last RF1 release. Going forward the International Health Terminology Standards Development Organisation (IHTSDO) and NLM will only produce the RF2 release files for SNOMED CT. This includes the International and US Editions of SNOMED CT. At this time our External Database Import Utility does not support Snomed RF2.
The solution to this issue is to add a new functionality that will implement the database load processing of Snomed_RF2 files into OpenEmr
I’ll be working in this endeavor, If someone wish to get involved or provide input is very welcome.

**Comment by robertogagliotta** [comment]
I will begin with SnomedCT_RF2_INT new install
- On list_staged.php I will  add ‘SNOMED’ else if
  /SnomedCT_RF2Release_INT
   $version = “RF2International:English”;
  Testing case: put file in contrib directory, see if INPUT button shows at import utility
  -standard_table_manage.php; add a ‘SNOMED’  if ($version == “RF2International:English”)  on 
                   Line 85
                  call new standard_table_capture.inc  functions:
                  SnomedRF2_import(TRUE), tempRF2_dir_cleanup($db).
-	Standard_table_capture.inc; add function snomedRF2_import

**Comment by bradymiller** [comment]
Sounds like a good plan.

**Comment by robertogagliotta** [comment]
The SnomedCT_RF2 has the  data files  in two locations : Full/Terminology and Snapshot/Terminology. Which location should be load in to openemr ?

**Comment by bradymiller** [comment]
Note the Full includes all revisions of codes, while the Snapshot contains only the current revision of codes.

I'd go with the Full for now.

**Comment by robertogagliotta** [comment]
my External Database Import Utility created and loaded tables: sct2_concept, sct2_description, sct2_identifier, sct2_relationship, sct2_statedrelationship, sct2_textdefinition. the tables are BIG, sct2_relationship has 2455945 rows. 
I'm not sure if the Notice about the checksum below needs to be fix ? 
Installed Release
Name: SNOMED
Revision: RF2International:English
Release Date: 2015-01-31
Staged Releases
SnomedCT_RF2Release_INT_20150131.zip

**Notice: Undefined index: checksum in /var/www/html/openemrRF2/interface/code_systems/list_staged.php on line 333**
The installed version and the staged files are the same.
Follow these instructions for installing or upgrading the following database: SNOMED?

**Comment by robertogagliotta** [comment]
Does OpenEMR will continue giving support to RF1?
 If this is true I will add SNOMEDRF2, SNOMEDRF2-CT and SNOMEDRF2-PR to tb code_types

**Comment by bradymiller** [comment]
I wouldn't add new code_types. But will need to add new options for the selector at far right column when look at Administration->Lists->Code Types (I think it is External Tables or something like that). This is what is used to identify the external tables used, and the new options can be added here:
https://github.com/openemr/openemr/blob/master/custom/code_types.inc.php#L176-L185
(will basically add 3 more entries add the end with RF2 in them rather than RF1)(and then the 10,11,12 are used to create the connectors to the new RF2 tables)
Here's how the connectors are done for RF1:
https://github.com/openemr/openemr/blob/master/custom/code_types.inc.php#L142-L164
(will keep this code and then add additional code to support 10,11,12 for RF2)

This will then allow the user to use either RF1 or RF2 by selecting it on the far right column in the Code Type list.

**Comment by robertogagliotta** [comment]
This is a working RF2 prototype
define_external_table($code_external_tables,7,'sct_descriptions','ConceptId','Term','Term',array("Description
 define_external_table($code_external_tables,10,'sct2_description','id','term','term',array("active=1"),"");
 define_external_table($code_external_tables,11,'sct2_description','id','term','term',array("active=1"),"");
define_external_table($code_external_tables,12,'sct2_description','id','term','term',array("active=1"),"");
![rf2](https://cloud.githubusercontent.com/assets/5272336/21959415/d141fece-da7a-11e6-92fa-68c1ca9a3116.JPG)

**Comment by bradymiller** [comment]
Hi @robertogagliotta ,
Looks like you are beginning to crack the "define_external_table" code :)
Is your code posted on github?
-brady

**Comment by robertogagliotta** [comment]
Yes, 
https://github.com/robertogagliotta/openemr/commit/62d7285fdc060c83f70352c2f8ffb7fe3ef10940#diff-8b9035807842a4e4dbe009f3f1478127

**Comment by bradymiller** [comment]
Hi @robertogagliotta ,
Great to see this. Recommend submitting a Pull Request with this code (just let me know if you need guidance on doing this), which makes it easier to review/test/revise (the PR mechanism will keep following your branch even when you make new commits, so can do multiple code revision in one PR request).
-brady

**Comment by robertogagliotta** [comment]
Hi Brady
I did the Pull Request following the " Creating pull request" on Github Help. But it shows all my commits instead the snomed_RF2_support commit, Help need it

**Comment by bradymiller** [comment]
Hi Roberto ,
Don't worry about that. It brings in all commits(even empty merge commits) from your branch that are different from master(the cool thing is that it will continue to track your branch so your changes go to the PR). The important thing is that your Files Changes screen looks fine, so I'd stick with that PR for now:
https://github.com/openemr/openemr/pull/452/files
-brady

**Comment by bradymiller** [comment]
Hi Roberto,
Looking really nice; only a couple things to address. Placed a review on the pull request.
-brady

**Comment by bradymiller** [comment]
Most recent PR for this is here:
https://github.com/openemr/openemr/pull/720

**Comment by bradymiller** [comment]
Gonna close this since have above newer PR for this.

**Comment by bradymiller** [comment]
Actually, gonna leep this open, since it is an Issue (and not a PR)

**Comment by bradymiller** [comment]
See https://github.com/openemr/openemr/pull/2329
