### ISSUE TITLE
Fatal Crash When Editing Patient

### ISSUE THREAD

**Issue by kchapple** [openemr/openemr#4102]
### Describe the bug
PID mix-up causes demographics screen to crash when navigating from Billing Manager. @growlingflea found this while working on a different issue.

### To Reproduce

From the billing manager, click the "Patient" button on a row of the billing manager.
<img width="416" alt="Screen Shot 2020-12-15 at 3 47 14 PM" src="https://user-images.githubusercontent.com/271809/102271085-ddd72300-3eec-11eb-9728-0dda8e5bd25f.png">
This button sets the active patient and opens the past-encounters/documents and the "edit patient" screen. Click "save" on the newly active patient and there's an error displayed:
`Internal error: Attempt to change patient data with pid = '2' when current pid is '0' for id '2'`
<img width="1086" alt="Screen Shot 2020-12-15 at 3 45 25 PM" src="https://user-images.githubusercontent.com/271809/102271223-1e36a100-3eed-11eb-98f0-98296a74d17f.png">

### Expected behavior

Patient should save as usual.

### Client configuration

- Browser: Firefox
- OpenEMR version: latest master
- Operating system: Mac OS

**Comment by sjpadgett** [comment]
I fixed this issue and just tested up and down so, works for me in all scenarios Dan and you have raised!

**Comment by stephenwaite** [comment]
how about https://github.com/openemr/openemr/commit/0c109b88a20c34aa6215b03d2a2adf9292593f00?

**Comment by kchapple** [comment]
@sjpadgett Sorry you're right, I thought I was up-to-date, but I wasn't. Just pulled and tested again and it's all good. @growlingflea

**Comment by sjpadgett** [comment]
Thanks @stephenwaite I don't know why I can't find my own work.  @kchapple no problem.
