### ISSUE TITLE
XML formgen Forms  - help with the error please

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#4103]
Hi..
I created a bunch of forms using xmlformgen form maker. The form registers well and installs well too. It opens in the form window but after saving the form, there are missing informations and on clicking the edit button, a blank page appears. Kindly help me with the error logs so that I can fix this - 

I need those forms for my daily patient assessments.

[Wed Dec 16 12:14:38.756675 2020] [php7:notice] [pid 3752:tid 1840] [client 43.231.240.178:53376] PHP Notice:  Undefined index: id in C:\\xampp\\htdocs\\openemr\\interface\\forms\\history\\save.php on line 129, referer: http://nahahealthclinic.ddns.net/openemr/interface/patient_file/encounter/load_form.php?formname=history
[Wed Dec 16 12:14:40.630569 2020] [php7:error] [pid 3752:tid 1840] [client 43.231.240.178:53376] PHP Fatal error:  Uncaught Error: Call to undefined function split() in C:\\xampp\\htdocs\\openemr\\interface\\forms\\history\\report.php:211\nStack trace:\n#0 C:\\xampp\\htdocs\\openemr\\interface\\patient_file\\encounter\\forms.php(1103): history_report(10, 66, 2, '1')\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\openemr\\interface\\forms\\history\\report.php on line 211, referer: http://nahahealthclinic.ddns.net/openemr/interface/patient_file/encounter/forms.php
[Wed Dec 16 12:14:44.457340 2020] [php7:notice] [pid 3752:tid 1840] [client 43.231.240.178:53376] PHP Notice:  Undefined index: mode in C:\\xampp\\htdocs\\openemr\\interface\\forms\\history\\view.php on line 192, referer: http://nahahealthclinic.ddns.net/openemr/interface/patient_file/encounter/encounter_top.php?set_encounter=66
[Wed Dec 16 12:14:44.457340 2020] [php7:error] [pid 3752:tid 1840] [client 43.231.240.178:53376] PHP Fatal error:  Uncaught Error: Call to undefined function split() in C:\\xampp\\htdocs\\openemr\\interface\\forms\\history\\view.php:205\nStack trace:\n#0 C:\\xampp\\htdocs\\openemr\\interface\\patient_file\\encounter\\view_form.php(26): include_once()\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\openemr\\interface\\forms\\history\\view.php on line 205, referer: http://nahahealthclinic.ddns.net/openemr/interface/patient_file/encounter/encounter_top.php?set_encounter=66

**Comment by sjpadgett** [comment]
Hi @arnabnaha Hope you are well.
split() has been deprecated since PHP5.3 and removed in PHP7.0

Unsure why you're just seeing this now unless a vendor library was aliasing it to maintain compatibility thus, we have updated our vendor dependencies and now the alias could be gone.

Difficult for me to troubleshoot this as I don't have the form so, above is an educated guess.

**Comment by arnabnaha** [comment]
Hi Jerry...
How are u?? I am doing good..if i send u the form via email..xan you please
take a look at it?

Thanks and regards
Dr. Arnab

**Comment by sjpadgett** [comment]
Sure, I can do that for you. Can you send now?

**Comment by arnabnaha** [comment]
Sure...plz send me your email id..

**Comment by sjpadgett** [comment]
sjpadgett@gmail.com

**Comment by arnabnaha** [comment]
done

**Comment by sjpadgett** [comment]
@arnabnaha Sent you hopefully a fix. Let me know.

**Comment by arnabnaha** [comment]
Hi Jerry...sorry I didnt get time to take a look at the form..i will surely
do it over the weekend and let u know...thanks a lot

**Comment by arnabnaha** [comment]
Hi jerry
Thanks for the form input...I am still getting the same error in error log and the form behaves in the same way...after saving data, it is not showing the saved data. The error log is below:

[Tue Dec 22 12:57:22.344044 2020] [php7:error] [pid 3792:tid 1836] [client 43.231.240.178:62823] PHP Fatal error:  Uncaught Error: Call to undefined function split() in C:\\xampp\\htdocs\\openemr\\interface\\forms\\history\\view.php:205\nStack trace:\n#0 C:\\xampp\\htdocs\\openemr\\interface\\patient_file\\encounter\\view_form.php(26): include_once()\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\openemr\\interface\\forms\\history\\view.php on line 205, referer: http://nahahealthclinic.ddns.net/openemr/interface/patient_file/encounter/encounter_top.php?set_encounter=66

**Comment by arnabnaha** [comment]
Hi @sjpadgett @bradymiller 
I found the solution - 
the split function is no longer supported in php 7 and so I replaced it with explode in all the files of the forms and it worked fine. So I am editing the xmlformgen file to automatically use the explode function rather than split function while creating the forms. I am creating a branch. Please merge it if you think its ok.

Thanks
Dr. Arnab Naha
