### ISSUE TITLE
Add "All" to justify on Fee Sheet

### ISSUE THREAD

**Issue by nursejeff** [openemr/openemr#4104]
Would it be possible to add the choice of “All” to the “Justify” drop down list, which would put all diagnoses into the justify box at once?

Jeff Guillory
NP Health Clinic

**Comment by nursejeff** [comment]
I would like to keep this fresh.  I hope my comments make OpenEMR more user-friendly.

**Comment by nursejeff** [comment]
I would like to keep this fresh. I hope my comments make OpenEMR more user-friendly.

**Comment by nursejeff** [comment]
I wish I knew how to program.  Thanks to all those that contribute.

**Comment by sjpadgett** [comment]
I keep meaning to do this as I think it'd benefit the whole community as well. I'll see if I can get to soon @nursejeff

**Comment by nursejeff** [comment]
I would like to keep this fresh. I hope my comments make OpenEMR more user-friendly.

**Comment by stephenwaite** [comment]
Hi @nursejeff. 
![Screenshot from 2022-02-21 10-56-59](https://user-images.githubusercontent.com/5618372/154989534-9a0437d9-cf3d-4af2-8fc4-abb2441b4aad.png)
The `Review` option is a great option if you're not familiar with it.

**Comment by nursejeff** [comment]
Thank you @stephenwaite, yes, I agree, I use it daily.
