### ISSUE TITLE
No need for patient name window to pop up

### ISSUE THREAD

**Issue by nursejeff** [openemr/openemr#4105]
### Describe the bug

When I am in the message center, looking at a message. I click on the blue word “Patient:” which is supposed to open that patient’s chart. Well it does open that patients chart but it also pops up a Patient name: window. I now have to close this window to proceed.

### Expected behavior
 It should go to the patient chart without popping up a Patient Name Window.

### Client configuration

- Browser:  Chrome and Firefox
- OpenEMR version: 5.0.2(5)
- Windows and Ubuntu

**Comment by nursejeff** [comment]
![image](https://user-images.githubusercontent.com/31212040/102424462-c5d8cf80-3fd0-11eb-82a0-fb0e6d0010e9.png)

**Comment by Nimra2212** [comment]
Hello! I wanted to work on this issue, I love to resolve bugs and errors, it's my passion and i am an expert in this. I will appreciate it if you will assign me this issue and guide me a little bit :)

**Comment by Nimra2212** [comment]
@stephenwaite I am also a beginner to open source and might take some time to understand the codebase and clarify if there is any deadline to it?

**Comment by Nimra2212** [comment]
I am also a beginner to open source and might take some time to understand
the codebase and kindly clarify if there is any deadline for it?

**Comment by stephenwaite** [comment]
no deadline thank you @Nimra2212 , have you seen the [contributing guide](https://github.com/openemr/openemr/blob/master/CONTRIBUTING.md)?

**Comment by Nimra2212** [comment]
@stephenwaite yeah, I am looking and reading, Thank you so much for giving me a chance to learn :)

**Comment by Nimra2212** [comment]
yes, I am reading the guidelines, Thank you so much for giving me a chance
to learn :)

**Comment by mdsupport** [comment]
@Nimra2212 - you can check /interface/main/messages/messages.php.

Did not notice that to be issue with 6.0 so just confirmed in demo. But did notice another issue - if the patient box is clicked, patient selection allows adding other patients to the list. @stephenwaite will have to confirm if sending message to a patient list  is supported. In this case, code does throw an error.

**Comment by stephenwaite** [comment]
thank you @mdsupport , confirmed no bug on master and did see the error you mentioned

![Screenshot from 2021-02-27 07-16-59](https://user-images.githubusercontent.com/5618372/109386951-43239900-78cc-11eb-9eb8-2e6fdeaf6e56.png)

**Comment by stephenwaite** [comment]
Fixed

**Comment by nursejeff** [comment]
I wonder what is wrong with my system because it still does it.  About OpenEMR
Version Number: v6.1.0-dev.

**Comment by stephenwaite** [comment]
think it's fixed with above PR, thanks for reporting back @nursejeff, will open a new issue for bug with multi patient select for messages spotted by @mdsupport
