### ISSUE TITLE
User Deprecated Error Lcobucci JWT Builder

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4118]
### Describe the bug
```[21-Dec-2020 17:49:17 America/New_York] PHP Deprecated:  Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead. in C:\xampp\htdocs\openemr\vendor\lcobucci\jwt\src\Builder.php on line 151```

What's frustrating is this will have to be fixed in the leagues OIDC project(steverhoades/oauth2-openid-connect-server/IdTokenResponse.php) where time() is passed in.(Cursory look). Also the trap for the DateTimeImmutable object converts the int but still throws the error.
There is a new release 1.3 out but doesn't address this issue! https://github.com/steverhoades/oauth2-openid-connect-server/pull/29

For sure breaks windows and i'm unsure effect on linux. For windows the work around is turn off `~E_USER_DEPRECATED`

### To Reproduce
During token creates on code flow.

**Comment by sjpadgett** [comment]
I'm going to go ahead and submit a PR to league project. I think I will also see about allowing to pull an encrypted public/private key from database instead of files! I see issues heading our way otherwise!

**Comment by sjpadgett** [comment]
more: https://github.com/steverhoades/oauth2-openid-connect-server/issues/30 thus
https://lcobucci-jwt.readthedocs.io/en/latest/upgrading/#v3x-to-v4x

**Comment by bradymiller** [comment]
@sjpadgett ,
I am pretty sure the I can solve your problem by removing this line in out "custom" jwt package :)
https://github.com/openemr/jwt/blob/34php8/src/Builder.php#L151

**Comment by bradymiller** [comment]
I was gonna do a php8 sweep of oauth2 stuff and mfa testing today anyways. I can make the above change also in my planned work today if that will help.

**Comment by sjpadgett** [comment]
okay, works for me

**Comment by bradymiller** [comment]
fixed this here:
https://github.com/openemr/openemr/pull/4119
(the build will now bring a jwt package that will not report these errors :) )

**Comment by sjpadgett** [comment]
Thanks Brady. Will close and send one atta boy your way:)
