### ISSUE TITLE
Finalize issuers  (smart and claims iss)

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4121]
Need to setup consistent issuer i.e iss attribute.
I use the IdTokenSMARTResponse extends IdTokenResponse @adunsulag set up to modify the id token builder to reflect correct issuer so as not to use the $_SERVER supers for domain references. Also allows including the site in issuer.(this is really only important to the iss claim in id_token matches the published issuer.)
Note also i've bumped the OIDC server to v1.3 that sets us up to be prepared for the JWT library move to v4.0.
```
return (new Builder())
            ->permittedFor($accessToken->getClient()->getIdentifier())
            ->issuedBy($this->urlOauthBaseFull)
            ->issuedAt(new \DateTimeImmutable('@' . time()))
            ->expiresAt(new \DateTimeImmutable('@' . $accessToken->getExpiryDateTime()->getTimestamp()))
            ->relatedTo($userEntity->getIdentifier())
```
There will be two issuers(check me if wrong)
- $GLOBALS['site_addr_oath'] will remain as is https//domain:port
- urlApisBaseFull = $GLOBALS['site_addr_oath'] . $GLOBALS['webroot']  .  "/apis/"  . $_SESSION['site_id']
- urlOauthBaseFull = $GLOBALS['site_addr_oath'] . $GLOBALS['webroot']  . "/oauth2/"  . $_SESSION['site_id']

These will be published somewhere yet to be decided.

**Comment by sjpadgett** [comment]
I'm beginning to wonder if perhaps site should be moved to
$GLOBALS['site_addr_oath'] . $GLOBALS['webroot']  . "/" . $_SESSION['site_id'] 
@bradymiller what do you think?

**Comment by bradymiller** [comment]
@sjpadgett ,
Sounds like it would simplify paths to site_addr_oath/webroot/site/<stuff like apis-oauth2-other/future/stuff>
How extensive would that change be to do?

**Comment by sjpadgett** [comment]
In the light of day not so easy. Won't work after sleeping on it because of our path rewrites.
Why is it we think we're so clever when we're tired!
