### ISSUE TITLE
Move site_id part in endpoint urls.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4126]
### Describe the problem
Currently our apis(FHIR and Standard) URI/URL endpoints requires the site_id(we'll call a tenant) as part of endpoint of the scheme: `https://domain/{ROOT}/SERVER/SITEID/{api}/endpoint` e.g `https://domain/{ROOT}/oauth2/default/endpoint` or `https://domain/{ROOT}/apis/default/api/endpoint`
This seems unnatural/clumsy.

I'm ready to pull the trigger on this and have done some tests where it's looking good. The code refactor isn't too tough with documentation being of the most concern.
If we ever want to change this, now'd be the time. If we wait until a later openemr version, I feel it will cause even more confusion and the number of client app rewrites will be much more numerous. 

Does anyone have an issue with me doing this or see something i'm not?
### Describe the solution you'd like
- Refactor to move SITEID to `https://domain/{ROOT}/SITEID/SERVER/{api}/endpoint.`
- Add a .htaccess to openemr root to redirect to appropriate directories.
- Will also allow shortening our issuer url maybe!

**Comment by sjpadgett** [comment]
Turns out that when doing redirects(login), session is destroyed. Don't see a way around.

**Comment by bradymiller** [comment]
Was worth a try. We can definitely make do with current pathing :)

**Comment by sjpadgett** [comment]
lol I don't know if i'm disappointed or relieved!:)
