### ISSUE TITLE
Update current node CDA server/generator to support v2.1

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4131]
### Describe the problem
Currently CDA document generation mostly supports HL7 Release 1.1. Need to update to a minimum Release 2.1 however while here, will try to bring current to meet 2020 ONC. I believe after rel 2 the Consolidated document is of import and may I say, yuck! 
### Describe the solution you'd like
Need to add several new sections requiring new template leafs and xpaths. Also need to add in all the human readable tables for those missing in rel  1.1(Vitals and Immunizations) and new for rel 2.1+

I'm begging anyone looking to get involved in some interesting engineering and coding to jump on my team. Even if it was to do just the table templates for display. 
This is all JavaScript running on a node server so, come on, it'd be fun, I promise.:)

**Comment by stephenwaite** [comment]
just noticed this
```
Base EHR Removal: § 170.315(b)(6) Data Export

As of the Final Rule effective date, this criterion is removed from the 2015 Edition Base EHR definition. However,
Health IT Developers may still certify to this criterion until December 31, 2023.
```
from https://www.healthit.gov/sites/default/files/page/2020-11/Key_Dates_2020.pdf

**Comment by sjpadgett** [comment]
Thanks, that's the way I read it however, the test hasn't been removed from testing spec so, i'm confused!

**Comment by stephenwaite** [comment]
§ 170.315(b)(10) “EHI export” will replace § 170.315(b)(6) “data export”. ONC–ACBs will be permitted to issue certificates for § 170.315(b)(6) until May 1, 2023 during the transition period to § 170.315(b)(10). We have included a provision in § 170.550(m)(2) to only allow ONC-ACBs to issue certificates for this criterion until May 1, 2023. [see also 80 FR 25720]

**Comment by stephenwaite** [comment]
is `(b)(10)` intentionally vague to open the door to api or fhir export?

**Comment by bradymiller** [comment]
The time-limited stuff always confuses me (I figure it out, then forget it, then figure it out again, then forget it...). see bottom of https://www.healthit.gov/curesrule/final-rule-policy/2015-edition-cures-update :
So, if b6 expires in 36 months from publication, does that means we still need to certify it until then?

**Comment by bradymiller** [comment]
duh, i should of read your link and then would of seen that effective date has been changed to now. woohooo, one more gone :)

**Comment by bradymiller** [comment]
btw, just removed b6 from the barometer

**Comment by sjpadgett** [comment]
What about these:
On June 30, 2020, certain 2015 Edition certification criteria are removed from the ONC Health IT Certification
Program. Removal of the following certification criteria supports burden and cost reductions for Health IT
Developers and health care providers:
» § 170.315(a)(6) Problem List
» § 170.315(a)(7) Medication List
» § 170.315(a)(8) Medication Allergy List 
» § 170.315(a)(11) Smoking Status
» § 170.315(b)(4) CCDS Summary Record – Create
» § 170.315(b)(5) CCDS Summary Record – Receive

Still best I can tell (b)(1) Summary of Care is still required. Now why would you go getting my hope up!:)

**Comment by stephenwaite** [comment]
those aren't on the barometer but agree could clean up detail below or leave a note stating they're removed

**Comment by sjpadgett** [comment]
Sure they are or am I seeing things again?

**Comment by stephenwaite** [comment]
![Screenshot from 2021-01-10 11-43-43](https://user-images.githubusercontent.com/5618372/104129089-1b3a9f00-5339-11eb-9497-29d3ff96d267.png)

**Comment by sjpadgett** [comment]
Forgive me! I'm old.....

**Comment by stephenwaite** [comment]
but hip :)

**Comment by sjpadgett** [comment]
For my generation, i'm cool or groovy. Far out man:)

**Comment by kchapple** [comment]
Hey all, sorry to barge in. We have a customer who (by October 2021) needs to export either CCD or HL7/ADT message types. I am out-of-the-loop here but am I understanding that the CCD generation is JS on a node server? Is that different that what is generated by the Patient Dashboard > Reports > CCD (download)?

**Comment by sjpadgett** [comment]
Yes, it is CCDA Release 1.1 at least for xml content. I'm updating for CCDA Release 2.1 and have to add the missing human readable sections.
I think i'm missing vitals and social for humans to see. However all the xml for import is there.

**Comment by sjpadgett** [comment]
Bumping this with this comment: "Why, Oh Why, Me!"
Have I ever mentioned, I hate xml!:)
Only 69 more errors to go!!!

**Comment by stephenwaite** [comment]
hah, do you have a branch @sjpadgett , be happy to assist if would help

**Comment by sjpadgett** [comment]
Maybe later. I'm reorging project now and have pulled in the templating engine and library. (formerly Blue Button I took over 4 years ago)), from my npm project. All javascript and nodejs.
I'll then do a PR to work from.

**Comment by bradymiller** [comment]
![tenor (52)](https://user-images.githubusercontent.com/278968/110224800-a6489900-7e93-11eb-941b-b3a37e4d28b1.gif)

**Comment by sjpadgett** [comment]
I've now consolidated all source to local. Published npm project no longer needed meaning we can get rid of openemr/oe-blue-button-generate repo. Will be deleting eventually @bradymiller and only adds 1.5MB to my ccdaservice dir...
Will work on converting to an express app or wait to see @kchapple app to see how we can have a common server. Unsure how that's going to work...

**Comment by sjpadgett** [comment]
Oh, thoughts on if we need FHIR to CCDA and visa versa?

**Comment by sjpadgett** [comment]
Can anyone tell me why CCM will not select a problem if link to Medical Problems from an encounter. Doesn't make sense. Is this a bug or is there a clinal reason not to send with a transition of care only non encounter linked problems/issues?

**Comment by sjpadgett** [comment]
Vital Signs, BMI, and Growth Charts Not required for MU3 but required by ONC!

**Comment by stephenwaite** [comment]
where do you see that @sjpadgett ?

**Comment by sjpadgett** [comment]
A couple diff summary sites but I still have to see if ONC has issued a change letter.

**Comment by sjpadgett** [comment]
I get different results from different validators but i'm getting there. I'm still trying to figure out if ONC only requires BMI where MU3 requires no vitals.... Now we're up to normative rel 2.1 2017 so next the Gold Standard and some extensions. Still, I'm seeing light where there was only darkness a week ago!:) Somebody buy me a beer!
![image](https://user-images.githubusercontent.com/1859985/111024547-63b02080-83ad-11eb-9e7e-66933978639b.png)

**Comment by stephenwaite** [comment]
![your_file](https://user-images.githubusercontent.com/5618372/111029699-0b3c4b80-83cc-11eb-8cd8-f5c1080eed21.gif)

**Comment by sjpadgett** [comment]
Status update: Still have some warnings that i'll sort out during scenario testing.
- Meeting ONC 2015 C-CDA validation with no errors.
- One error for MDHT conformance HL7 Rel-2.1 though, I believe it's an invalid error.

![image](https://user-images.githubusercontent.com/1859985/111530060-3e1e7080-8739-11eb-9562-d32b0efd17ab.png)

I haven't implemented Payers yet and i'm not sure I need to.
![image](https://user-images.githubusercontent.com/1859985/111533367-13361b80-873d-11eb-89bc-2b3daf1894bd.png)


Plan:
- Further consolidate project dependencies.
- Commit current source updates.
- Merge as released R2.1 compliant C-CDA.
- Work on CCM HIE import/export.
- Create CCDA hook for FHIR document resource.
- Test and debug ONC 2015 test plan compliance based on scenarios.
- LUNCH
- Save the world!

**Comment by stephenwaite** [comment]
gonna dbl check with Brady but until this is totally compliant then:
![nosoup](https://user-images.githubusercontent.com/5618372/111534441-6066bd00-873e-11eb-9976-d20d70dbd33b.gif)

:)

**Comment by sjpadgett** [comment]
as long as I still get coffee!

**Comment by stephenwaite** [comment]
https://user-images.githubusercontent.com/5618372/111542536-403bfb80-8748-11eb-9150-08e1bf2e912f.mp4
