### ISSUE TITLE
example smart on fhir app to quickly test that it is working for 6.0.0

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#4148]
interface/smart/register-app.php:
![image](https://user-images.githubusercontent.com/278968/103446325-2ef84e00-4c33-11eb-93d0-ce40fe9de5f9.png)

API Clients:
![image](https://user-images.githubusercontent.com/278968/103446344-57804800-4c33-11eb-970c-c2696ee173e8.png)

Deregister client id from the app for complete testing:
https://adunsulag.github.io/growth-chart-app/deregister.html
![image](https://user-images.githubusercontent.com/278968/103446402-06248880-4c34-11eb-8ac6-dfb433ff8c44.png)

Patient summary:
![image](https://user-images.githubusercontent.com/278968/103446355-6d8e0880-4c33-11eb-8181-ae60e7bdb937.png)

Click on Launch (register the client id with the app):
![image](https://user-images.githubusercontent.com/278968/103446409-19cfef00-4c34-11eb-84a9-1d449820a47d.png)

Login:
![image](https://user-images.githubusercontent.com/278968/103453738-f045b080-4c91-11eb-9167-1b83fd6a98d8.png)

Authorize:
![image](https://user-images.githubusercontent.com/278968/103453744-fb004580-4c91-11eb-9789-c17c60c6bfb8.png)

See the magic:
![image](https://user-images.githubusercontent.com/278968/103453754-0d7a7f00-4c92-11eb-99ce-7c9d1669e0ae.png)

**Comment by bradymiller** [comment]
@adunsulag , Getting close on getting this to work. Just wanted to make sure I have the right settings and that perhaps I am missing something simple on the setup.

**Comment by adunsulag** [comment]
@bradymiller Let me look into this, been out all day I'll run through this again and verify.

**Comment by adunsulag** [comment]
@bradymiller It's failing on requesting the patient/Observation.read scope.  Before we did our permission fixes this was allowed.  I'm looking to see what we can do, adding into the portal the patient observation doesn't look too hard.

**Comment by bradymiller** [comment]
Guess I am still confused on the user versus patient. Since the user "logged in" as user userrole, shouldn't all requests go through the user userrole?

**Comment by bradymiller** [comment]
Also, to clarify, isn't the next screen supposed to be a login?

**Comment by bradymiller** [comment]
it looks like we can change the requested scopes in the app itself: https://github.com/smart-on-fhir/growth-chart-app

**Comment by adunsulag** [comment]
@bradymiller So the SMART app is the one that requests the scope permissions. In my case my smart app wasn't sending the api:fhir or the fhirUser role and so the OpenEMR server didn't know how to build any of the validation roles and just left the array blank.  This was causing the scopes to fail.  If an app requests an invalid scope it doesn't show a login screen, OpenEMR redirects back to the app with the error message of invalid scope.

I went ahead and changed the scopes in the app and it should now be working, I tested and verified this, I'm hoping it should work for you now.

**Comment by adunsulag** [comment]
@bradymiller I figured your in working on this, so I tried calling you via phone but you didn't answer :).

**Comment by adunsulag** [comment]
Also I had to change the app to request the user/Patient.read and user/Observation.read.  Apparently my admin user doesn't have the patient portal ACLs.  I think this is going to cause us problems with app compatibility, but I think it will be fine for people to start building their apps against OpenEMR in 6.0.

**Comment by bradymiller** [comment]
getting close. got the login screen, but got following for the Authorized:
![image](https://user-images.githubusercontent.com/278968/103448139-0039a200-4c4a-11eb-97e5-cac54376db6a.png)

with following php error:
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to a member function completeAuthorizationRequest() on null in /usr/share/nginx/html/openemr/vendor/league/oauth2-server/src/AuthorizationServer.php:175
Stack trace:
#0 /usr/share/nginx/html/openemr/src/RestControllers/AuthorizationController.php(797): League\OAuth2\Server\AuthorizationServer->completeAuthorizationRequest(Object(League\OAuth2\Server\RequestTypes\AuthorizationRequest), Object(Nyholm\Psr7\Response))
#1 /usr/share/nginx/html/openemr/oauth2/authorize.php(93): OpenEMR\RestControllers\AuthorizationController->authorizeUser()
#2 {main}
  thrown in /usr/share/nginx/html/openemr/vendor/league/oauth2-server/src/AuthorizationServer.php on line 175
172.22.0.39 -  01/Jan/2021:23:56:04 +0000 "POST /oauth2//authorize.php" 500

**Comment by bradymiller** [comment]
sorry i missed your call. will answer next call :)

**Comment by bradymiller** [comment]
fixed this in the PR linked above. had to do 2 things to get it to work:
1. Isolate API into it's own cookie (I've been wanting to do this anyways)
2. set samesite to None for the oath cookie (unclear why needed, but it's ok since oauth cookie required https and all the endpoints that can change state are protected with csrf mechanism)

**Comment by ahergau** [comment]
Hello,

I am using OpenEMR first time, I just want to test my smart on fhir app launch with openemr, I am using it with docker version 6.0.

I can access openemr on localhost/ with username and password can create a patient and other data as well, but whenever I am trying to hit https://localhost/interface/smart/register-app.php? to register a smart app, this page does not open and gives a blank web page with message "Not Authorized". Can someone help here what I am missing ? 

@bradymiller @adunsulag

**Comment by adunsulag** [comment]
Hi @ahergau I'm guessing something is wrong with how you installed the docker image.  Have you checked the server logs on the docker image to see what may be going wrong?  You can see this [community forum thread for tips on how to see the logs](https://community.open-emr.org/t/docker-php-error-logs/11764/6)

If you are having problems with your local environment you can also try testing your app against the demo instances for example here is the register-app page on one of the demo servers: [https://demo.openemr.io/openemr/interface/smart/register-app.php](https://demo.openemr.io/openemr/interface/smart/register-app.php)

**Comment by sky-code** [comment]
> Hello,
> 
> I am using OpenEMR first time, I just want to test my smart on fhir app launch with openemr, I am using it with docker version 6.0.
> 
> I can access openemr on localhost/ with username and password can create a patient and other data as well, but whenever I am trying to hit https://localhost/interface/smart/register-app.php? to register a smart app, this page does not open and gives a blank web page with message "Not Authorized". Can someone help here what I am missing ?
> 
> @bradymiller @adunsulag

I had the same problem, enabling this checkboxes in Config > Connectors
<img width="1491" alt="image" src="https://github.com/openemr/openemr/assets/5621185/9389f5af-be9f-4bf2-bd0d-f09a9947e773">
After those changes Register New App button works.

**Comment by pratikshabande0440** [comment]
I’m currently working on integrating OpenEMR and facing an issue while trying to fetch prescription and procedure details using Postman.

I’ve successfully configured the API and can retrieve basic patient information. However, when I attempt to access the following endpoints:

/apis/default/api/prescription
/apis/default/api/procedure

…I either receive an empty response or encounter errors (such as 404 or 500). I’ve confirmed that the patient has associated prescriptions and procedures recorded in the system.

I’m using the correct Bearer token and headers, and other endpoints like patient and medical_problem are working fine.
Could anyone guide me on:
Whether any additional configuration or module activation is needed?
The correct format of request (if any special parameters or filters are required)?
Any known limitations or fixes related to these endpoints?
