### ISSUE TITLE
Hi all I need help with the CDR

### ISSUE THREAD

**Issue by eyalvo-matrix** [openemr/openemr#415]
My name is Eyal 
I am trying to do the following functionality

Table A 
id      date               is_done 
1    2017-02-02          0 
1    2017-01-01          0 
1     2016-01-01         0

Table B 
id      date                  data
1     2016-01-01         0
1    2017-01-01          0 

Only when a patient have a record with the daily date in table A 
then he will get an alert  in the patient file 
that will disappear when  an entry in table B with daily date will be inserted

any idea how to do that?

**Comment by mdsupport** [comment]
As noted in other comment, create a database view like : 
SELECT A.* FROM A LEFT JOIN B ON A.id=B.id AND A.date=B.date WHERE A.date=CURDATE() AND B.id IS NULL
If A.id is pid, name it so in the view.
In rules design, the view will appear as a table and rules engine will treat is as such.

No idea why there is aversion to use of database views.  Standard rules should be use standard views for maximum db performance.

**Comment by eyalvo-matrix** [comment]
Joining wont help I think since the functionality I need is only if there is a daily record in A 
I will see an a reminder that will stop if there is a record in B

**Comment by eyalvo-matrix** [comment]
I am not sure that join will work since the functionality that I am trying to achieve is that 
Daily if there is a record in A (that can be entered daily or in a week in advance) 
I will see an alert that will stop when an entry in B is inserted  for that day

**Comment by mdsupport** [comment]
Suggested view would show entries in A for current date where there is no entry in B (B.id IS NULL).  When B is created, there will not be any result.
In any case, not trying to solve your problem based on limited understanding - just providing an approach for using CDR with data from multiple tables.  You will need to figure out the actual view.
Cheers.

**Comment by bradymiller** [comment]
Is this related to the following PR:
https://github.com/openemr/openemr/pull/416

**Comment by bradymiller** [comment]
@eyalvo-matrix ,
Just checking is this issue is resolved (with the above PR link) ?
thanks, -brady

**Comment by EyalNous** [comment]
Hi brady this indeed was solve with the fix in the link above , Thanks !!
