### ISSUE TITLE
Tab switching on patient selection is strange.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4153]
### Describe the bug
Patient Finder refresh after selection.
Why does Patient finder now refresh after new patient selection click?
It causes focus change back and forth between Dashboard tab. Sometimes ends on Patient Finder tab instead of Dashboard.

Also, is it a feature in openemr to auto focus on Encounter tab when opening new patient chart? I can't seem to nail down why this happens sometimes while not other times. I seem to remember this back on v4+ at some point.

This will drive folks nuts!
note: I found this on an upgrade from 5.0.1
@bradymiller we really need to get this fixed before/include in v6.0 release.

**Comment by stephenwaite** [comment]
hi @sjpadgett , think i noticed some strange behavior in https://github.com/openemr/openemr/pull/4067

**Comment by sjpadgett** [comment]
Thanks @stephenwaite Will you test with me? I'll try a couple of my dev installs to see if random or from the upgrade.

**Comment by sjpadgett** [comment]
weird. I appears it has something to do with we how we now refresh Patient Finder on focus and click. Or did we always do this!

**Comment by stephenwaite** [comment]
https://github.com/openemr/openemr/pull/4125 is prob causing recent issue but is there some other datatables weirdness involved with bringing the focus back to the pt finder after going to the patient dashboard? It's like it refocuses as it's waiting for all of the patients to load in the finder.

**Comment by sjpadgett** [comment]
Maybe but doubtful. I suspect the refresh and by fixing one issue you only exacerbated(I wonder if that word would get translated!:)) an existing issue.

**Comment by stephenwaite** [comment]
ok, next guess, clearPatient function in `tabs_view_model.js`

**Comment by sjpadgett** [comment]
Nothing you've done is causing this issue Stephen. Nuts, I hate these types of issue dealing with knockout and tabs.

**Comment by stephenwaite** [comment]
phew, nostalgic as i watch wanda moore grow up before my very eyes :)

**Comment by sjpadgett** [comment]
okay, found it. 
It is, in clearPatient()(ya nailed it Stephen). Evidentially, navigateTab() sets a afterLoadFunction() event that never gets turned off so after a clearPatient, all calls to navigateTab will run the event. Essentially navigating to the Find Patient(fin) tab.

This must have worked at one time as this was done back at least early v5.0.2. So there is a jquery event off somewhere that's no longer called.

Two things here: why is it the responsibility of navigateTag() to host an event that may or may not be managed by calling function and finally, why was it changed in the first place!

Doing PR as this is also broke for Therapy Group. Will cherry pick back to release.
