### ISSUE TITLE
X12 billing file rejection due to missing gs03

### ISSUE THREAD

**Issue by baflynn1** [openemr/openemr#4154]
### Describe the bug"

X12 billing file generated with missing gs03 / receiver ID field, and failed submission to Availity. Previous attempts to add "Application Receiver Code" under Administration->Practice Settings->X12 partners failed to save "030240928      ".  The screen includes a note "(GS03 - If blank ISA08 will be used)" but ISA08 was filled and was not used. 

![image](https://user-images.githubusercontent.com/74113010/103488357-d44d2680-4dd9-11eb-88a4-6eeb32fdeb23.png)
(remainder not pasted)

### To Reproduce

1. Clean install OpenEMR 5.0.2, not upgrading from prior versions (GS03 was added at 4.1, did not make it into database.sql?
2. Attempt to save application receiver code/GS03 under Practice Settings-> X12 partners. Does not save.
3. Generate X12 billing file. 

### Expected behavior

got the following after manually altering table X12_partners to include x12_gs03 column, which allowed saving the receiver code, and resulted in the following output which was accepted by Availity:
![image](https://user-images.githubusercontent.com/74113010/103488383-ff377a80-4dd9-11eb-9835-2eca26d762fe.png)
(remainder not pasted)

### Client configuration

- Browser: Chrome 87.0.4280.88
- OpenEMR version: 5.0.2
- Operating system: Windows 10

**Comment by stephenwaite** [comment]
thanks for the nice issue report @baflynn1 , think this was fixed in a patch since am able to save `GS*03` at https://six.openemr.io/c/openemr/interface/login/login.php?site=default

might want to use @sjpadgett 's [patch 5](https://community.open-emr.org/t/how-to-upload-icd-10-codes/10356/6)
