### ISSUE TITLE
Dated reminders session destroy

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4157]
### Describe the bug
`
PHP Warning:  session_destroy(): Trying to destroy uninitialized session in \src\Common\Session\SessionUtil.php on line 215
Stack trace:
[04-Jan-2021 10:53:28 America/New_York] PHP   1. {main}()  \interface\main\dated_reminders\dated_reminders.php:0
`
This is worrisome to me. I am setting up a trap in code to try to get better context when this occurs. We can add code to prevent the warning in session util however, I believe the warning shouldn't happen in the first place.

**Comment by mdsupport** [comment]
Dated reminders is a runaway train in autopilot mode checking reminders every xx seconds. If session times out, one should expect that warning. Corrective action would be in main frame when the famous 'site id' condition happens, the javascript timer/interval should be reset... until pubsub is adopted.

**Comment by sjpadgett** [comment]
This needs to be rewritten. Either truly make it anonymous and last time I looked, no reason for it to be involved in sessions.
The only reason we run session is to get authUserID and i'm sure we can find a better way to do this.
Or as you say maybe trigger from mains timeout timer and pass in session.

**Comment by mdsupport** [comment]
This is one our pet peeves, so forgive the rant. From functional perspective there should be a single object that handles patient care with time dependency. MU took care of that by bringing in time element in decision rules. If development effort is spent in adding a manual reminder functionality to CDR (similar to exception handling for the rules), the engine will take care of reminders more elegantly. There will be tracking, global visibility if an user is no longer active and a log of actions. Allowing multiple data structures for same functionality is a disservice to the development team to follow.

**Comment by sjpadgett** [comment]
Perhaps best approach then is to develop a stand alone event driven alerts/message/reminders interface that intercepts dispatched events where needed, handles and dispatches to destination.
Or some such!

**Comment by mdsupport** [comment]
Time driven events can be handled as dated reminders, dummy appointment and clinical rule. Currently not handled are expired drugs, rx refills and overdue callbacks like referrals or lab results. What we need is a service that can handle call from object in the form of "ok emr, set reminder to do _xyz_ for _John Doe_ in _nn days_".
But then what will all the clinic staff do???

**Comment by juggernautsei** [comment]
> Dated reminders is a runaway train in autopilot mode checking reminders every xx seconds.

@mdsupport I have a number of users asking me to fix this. Can you point me to where to look?

**Comment by mdsupport** [comment]
@juggernautsei, It depends on what you/your users are looking for. In our case, architectural design of trying to emulate an OS daemon at user session level is counter productive. So easiest route was to rework [hard coded timer](https://github.com/openemr/openemr/blob/22741584a8b1b4077b55943353cce79b7b020138/interface/main/tabs/main.php#L85) to consider installation and then user settings and stop incessant power drain on tablets and small devices.

At minimum consider suppressing these calls when user has moved browser focus / view away from emr tab.

**Comment by juggernautsei** [comment]
The problem we are having is the session is randomly timing out and people are getting the session ID missing message. 
Will the hard-coded timer fix that issue? Thanks as always @mdsupport

**Comment by mdsupport** [comment]
Not sure how you traced random session problem to this feature. But if you are sure, you need to examine that function as well as ajax scripts it calls to find if anything there is incorrectly destroying session.
Best.
