### ISSUE TITLE
Backup LBF export broken

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4158]
### Describe the bug
Really! What happened?
This use to work well which make think something is wrong with my setups however this isn't working in 5.0.2 as well..
I should be able to just export LBF layouts only correct?

Resulting export deletes the layout however doesn't include the layout options to import.

This should block v6 release imo so i'm looking into. Any suggestions are helpful....

**Comment by sjpadgett** [comment]
Looks like a windows issue. We're sending an invalid mysqldump path via usr/bin.

**Comment by sjpadgett** [comment]
Woops, this is on me! $GLOBALS['mysql_bin_dir']
nuts

**Comment by mdsupport** [comment]
How do you backup layouts? We use [this](https://sourceforge.net/p/openemr/discussion/202505/thread/6b30c511/#f01b).

**Comment by sjpadgett** [comment]
Hi @mdsupport I really should wait before putting issues up. I always used the Administration->System->Backup Export then select Layouts from list.
This feature actually is very nice however, being on windows, I forgot to ensure my $GLOBALS['mysql_bin_dir'] was set correctly.
I'm a little embarrassed but, i'm thinking, I must have a complaining mindset today!:)

**Comment by sjpadgett** [comment]
spoke to soon. dump command syntax error
