### ISSUE TITLE
solar theme menus

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#4163]
### Describe the bug

the menus are not displaying properly maybe a background color issue?

### To Reproduce
change theme to solar

### Expected behavior

menu displays like light theme

### Client configuration

Love openemr long time

**Comment by mdsupport** [comment]
If there is no solution for solar theme background color issue, we should at least not make it a default theme for [demo](https://eight.openemr.io/a/openemr). Here is picture - 
![image](https://user-images.githubusercontent.com/399047/129926717-c9ae8e45-98e1-4891-9431-f1b899a11798.png)

**Comment by sjpadgett** [comment]
Somebody needs to go through the themes and fix. Solar, Dark and some Light. It's not to hard but I don't have time just now.
It's be a great project for someone interested in UI/UX

**Comment by mdsupport** [comment]
Just saying the demo should be best foot forward.

**Comment by stephenwaite** [comment]
hi @mdsupport, do you have time to look into the issue? thank you

**Comment by bradymiller** [comment]
Just let me know which demo themes we should not be using for now and I'll make the changes in the demo farm:
https://github.com/openemr/demo_farm_openemr/blob/master/demo_build.sh#L57-L128

**Comment by stephenwaite** [comment]
should be light only imo

**Comment by bradymiller** [comment]
Could make it light for the official demos and then only do the random pick for the development demos. Would that make sense?

**Comment by bradymiller** [comment]
The production demos will now only use light :)
https://github.com/openemr/demo_farm_openemr/commit/faab91201708c2e585fa986915ef99d898c1ae4f
