### ISSUE TITLE
Draggable and droppable replacements post jquery-ui removal?

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#4165]
### Describe the bug

In 6.0.0 Eye Form, the loss of draggable and droppable breaks the Impression/Plan builder.
There is a console error, presumably from removal of jquery-ui.  Not sure what is meant to replace this functionality.
I assume this breaks javascript from working correctly downstream too.

Also there is a problem with the display in all themes with bootstrap and fontawesome.  Not sure how much is from this bug but I'll take a look again when I understand the draggable fix.

**Comment by sjpadgett** [comment]
Hi @ophthal 
We have pulled the jquery-ui because it is a dead project in our eyes. The replacement for the drag and drop is in the library/js/utility.js script.
I'm just not sure how well the eye form was tested because for a novice, it is difficult to understand.

Can you be more specific on errors and bootstrap assertion?

**Comment by tywrenn** [comment]
I'm not surprised that the eye form is broken. There was so much jQuery UI going on with it that it was bound to error somehow.

**Comment by ophthal** [comment]
> library/js/utility.js

Can you show me an example where this drag/drop function is deployed so I can investigate?
When I do a grep 'initDragResize' -R * at the /openemr directory I can find any...

Also what is the replacement for jquery-panelslider?

**Comment by stephenwaite** [comment]
hi @ophthal , will pin a topic to the top of the community forum that until eye form is fixed shouldn't upgrade

**Comment by sjpadgett** [comment]
> to add jquery at the eye form level rather than globally?

I agree. @bradymiller @stephenwaite Lets have this conversation. This was left hanging and need to resolve.
@ophthal 
The replacements for drag and drop is in our `library/js/utility.js`. What other jquery-ui utilities is the eye form using that was missed. Would, as stands now, adding the dependency fix eye-form quickly?
