### ISSUE TITLE
phi mail linked documents not opening patient chart

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#4171]
### Describe the bug

after opening a phi mail message, the attached document link does not take the provider into the patient's chart

### To Reproduce

![image](https://user-images.githubusercontent.com/834958/104225805-ddab4400-5414-11eb-9711-8428f344b7a7.png)
![image](https://user-images.githubusercontent.com/834958/104225986-1c40fe80-5415-11eb-9c0d-8e2a4f9cdb76.png)

Open messages, 
select see all
selected phimail message
select linked message 

### Expected behavior

Open patients' chart to message

### Client configuration

- Browser: Chrome
- OpenEMR version: 6.0.0
- Operating system: Ubuntu

**Comment by juggernautsei** [comment]
This block of code is not producing the correct display.

            if (sqlNumRows($tmp)) {
                                                echo " <tr>\n";
                                                echo "  <td class='text'><b>";
                                                echo xlt('Linked document') . ":</b>\n";
                                                while ($gprow = sqlFetchArray($tmp)) {
                                                    $d = new Document($gprow['id1']);
                                                    $enc_list = sqlStatement("SELECT fe.encounter,fe.date,openemr_postcalendar_categories.pc_catname FROM form_encounter AS fe " .
                                                        " LEFT JOIN openemr_postcalendar_categories ON fe.pc_catid=openemr_postcalendar_categories.pc_catid  WHERE fe.pid = ? ORDER BY fe.date DESC", array($prow['pid']));
                                                    $str_dob = xl("DOB") . ":" . $prow['DOB'] . " " . xl("Age") . ":" . getPatientAge($prow['DOB']);
                                                    $pname = $prow['fname'] . " " . $prow['lname'];
                                                    echo "<a href='javascript:void(0);' ";
                                                    echo "onClick=\"gotoReport(" . attr(addslashes($d->get_id())) . ",'" . attr(addslashes($pname)) . "','" . attr(addslashes($prow['pid'])) . "','" . attr(addslashes($prow['pubpid'])) . "','" . attr(addslashes($str_dob)) . "');\">";
                                                    echo text($d->get_url_file());
                                                    echo "</a>\n";
                                                }
                                                echo "  </td>\n";
                                                echo " </tr>\n";
                                            }

This is what is showing in the browser. Minus the stars.

        <a href="javascript:void(0);" onclick="gotoReport(326590,' ','','','DOB: Age:2021');">dm_G******_Dishinger_190848_000015.xml</a>

**Comment by sjpadgett** [comment]
@juggernautsei 
I'm guessing you're going to do a fix PR for us, right.:)

**Comment by juggernautsei** [comment]
yes @sjpadgett , the report is for others to know we are aware of the issue. I'll work on it later this week.

**Comment by juggernautsei** [comment]
This function is failing to receive pid back from the multi_patient_finder

    function updatePnotePatient($id, $patient_id)
    {
    $row = getPnoteById($id);
    if (! $row) {
        die("updatePnotePatient() did not find id '".text($id)."'");
    }

    $activity = $assigned_to ? '1' : '0';

    /* $pid = $row['pid'];                                     //Commented out these lines of code and the 
    if ($pid != 0 || (int)$patient_id < 1) {             // the system processes the request. However...
        die("updatePnotePatient invalid operation");
    } */

    $pid = (int) $patient_id;
    $newtext = "\n" . date('Y-m-d H:i') . " (patient set by " . $_SESSION['authUser'] .")";
    $body = $row['body'] . $newtext;

    sqlStatement("UPDATE pnotes SET pid = ?, body = ?, update_by = ?, update_date = NOW() WHERE id = ?", array($pid, $body, 
    $_SESSION['authUserID'], $id));
    }

That is the short story and as far as my troubleshooting the code has gotten.  L496 is where it fails. 
Sometimes reading is fundamental. The note says that the patient ID has to be set manually. When we go to set it manually. It fails with the message. update PnotePatient invalid operation.  So, I commented out the lines noted and there is a new issue.

The multi_patient_finder is passing a blank line.

![image](https://user-images.githubusercontent.com/834958/104253956-b61fa000-5443-11eb-9b75-4ccff6a40f4b.png)

**Comment by juggernautsei** [comment]
We found that duing the upgrade the data in the documents/direct folder did not upload. We had to change the permission on the windows folder and subfolders to allow the administrator access to the files. Once the files were uploaded. The code worked fine.
