### ISSUE TITLE
Twice Authorisation for user

### ISSUE THREAD

**Issue by vishnuyar** [openemr/openemr#4172]
### Describe the bug

When Smart App is launched from OpenEMR from Patient DashBoard, the User id and Password are being asked.

### Expected behavior

The User has logged into the OpenEMR after providing the required security credentials and is already logged into the system. When the User launches the SMART App from within the system, the Smart App should be directly launched without further authorization as the user has already provided the same while logging in.

**Comment by sjpadgett** [comment]
@adunsulag 
What do you think? My thought is that because he in a auth user in openemr doesn't mean the app itself has same permissions or any other workflow as to but, sign into the auth server. However, unsure what the spec requires!

**Comment by vishnuyar** [comment]
I am assuming the same check can be done prior to launch rather than asking for the same credentials again.  Would there be possibility that a different user id password is used when the auth server is invoked ?

**Comment by sjpadgett** [comment]
The user has to have a valid, active auth server session in order for client to access api's i.e access_token. Same username/password though.

**Comment by adunsulag** [comment]
@sjpadgett so the SMART spec leaves it up to the EHR on whether to ask for username / password once again when inside the EHR launch context.

The tricky thing is during the oauth2 flow we have a separate session so from the oauth2 endpoint we don't know that the user is logged in.  We can put an encrypted nonce with the logged in user into the SMART EHR launch context param (its where we store the patient id currently), but I'm wondering if we should store in the database (if we aren't already) the currently logged in user or launch context just to safeguard things.  We could also pass the session id as part of the launch if we were saving the sessions to the db (which I don't believe we are).  I might be overthinking that though.

I'm personally in favor of skipping the username/password, but I don't know if there may be reasons why we want to force a re-auth situation, such as requesting highly sensitive information IE HIV status, multiple patient data, etc.

**Comment by sjpadgett** [comment]
For the auth server we have trusted user as active or not sign in. So it'd be a matter for Smart launcher checking if there is a trusted user in database oauth_trusted_user. If so, bypass login. If not, create one.
This assumes user has a client to reference.

**Comment by adunsulag** [comment]
@sjpadgett I'll look into it.

**Comment by adunsulag** [comment]
This shouldn't be closed!

**Comment by bradymiller** [comment]
Stale bot smackdown

![tenor (35)](https://user-images.githubusercontent.com/278968/115819495-cd134e00-a3b3-11eb-8d51-64bde8c769a5.gif)
