### ISSUE TITLE
CMS related Prior Authorisation

### ISSUE THREAD

**Issue by vishnuyar** [openemr/openemr#4180]
### Invoking Prior Authorisation for CMS

Currently CMS asks for Prior Authorization mostly for DMEPOS and HomeHealthCare. 
In OpenEMR,I do not know or don't see a interface to request for a patient either for a DMEPOS or HomeHealthServices

Once these features are implemented in OpenEMR, the data from this can be used to create FHIR Service Request (https://www.hl7.org/fhir/servicerequest.html)

We can then implement CDS Hooks (https://cds-hooks.org/) in OpenEMR and a practitioner and then get a prior authorization request submitted directly to CMS

Implementation of CDS Hooks is to successfully implement the solution as visualized in the scenario No.2 of Da Vinci CRD (http://hl7.org/fhir/us/davinci-crd/2019May/usecases.html)

### Describe the solution you'd like

I would like to implement FHIR Service Request and CDS Hooks for OpenEMR but will need guidance or help in creating the interface for requisition of DMEPOS and HealthCareServices within the existing functionality. 

Significant Questions for such an implementation will be
a) Trigger Point for CDS hook
b) Integration of all types of Order (Lab Order, Service Order,Device Order,Surgery ) for a uniform process

**Comment by vishnuyar** [comment]
Any Inputs please. CMS has it mandatory for the year 2023

**Comment by mdsupport** [comment]
This has been [long requested](https://community.open-emr.org/t/prior-authorizations/3524/2) feature. Most expedient way to store and track would be leveraging the referral process. It will not address the encounter+billing process. But it would be a start.

**Comment by stephenwaite** [comment]
hi @vishnuyar @mdsupport , there's also the [prior auth smarty form](https://github.com/openemr/openemr/tree/master/interface/forms/prior_auth)

**Comment by mdsupport** [comment]
Keep forgetting the optional form, @stephenwaite - that one is more functional for someone to utilize an PA requested by other - e.g. Home Health can use it to document required information for billing a visit.
For someone like primary care to initiate need for homehealth or specific equipment from CMS, closest we have is referral loop  since it already has all codes etc. - just does not have FHIR wrapper. Use case would be - send communication to a third party that Ms. Y needs a service or a thing, actively track the response and if positive, forward it the resulting provider. We have pieces (possibly) but no integrated capability.

**Comment by vishnuyar** [comment]
Maybe the primary thing is to create an interface to let the practitioner order DEMEPOS, HomeHealth services and Prosethectics.  Once the interface is created, creating FHIR Resources and Order Hooks is a secondary stage. 

How do I start creating these interfaces ? Should they be similar to the way a Lab Order is requested ?

**Comment by mdsupport** [comment]
If it is new development, why not make life easier for next step and implement a persistent [ServiceRequest](https://www.hl7.org/fhir/servicerequest.html) object including the standard methods and properties? Although you can limit scope to implementing `requestor=practitioner` and `performer=device`, it will lay the foundation to unify current ad-hoc objects implemented over time.

**Comment by vishnuyar** [comment]
@bradymiller @sjpadgett , can I interface for Ordering DMEPOS similar to the one for Procedure order, will that be acceptable.
@mdsupport SeriveRequest is specific to FHIR, once these interfaces are implemented, in the background those requests can be created for FHIR Specifications.

**Comment by sjpadgett** [comment]
@vishnuyar 
I'm bringing in an updated procedure order form replacing existing. The new form will be easier to hook different procedure type than before. Previously we had a Procedure Type but was never used and didn't persist in database. I've fixed that.

![image](https://user-images.githubusercontent.com/1859985/105706127-2536d300-5edf-11eb-96e8-0eacdb537a05.png)

Based on that field and the selected provider from order providers, you can adjust the form order options to suit your needs for the request plus add equipment hcpcs codes to compendium.

![image](https://user-images.githubusercontent.com/1859985/105706791-0127c180-5ee0-11eb-9b67-99c8a119ea57.png)

For prior auth and any requisitions form, the workflow is already setup and hooking the new forms will be easy.

My new procedure order form is based on existing/current but just refactored with enhancements. I plan to have new in master in day or two. I wrote this 3 years ago and it is taking a bit of an effort to bring it up to current openemr coding standards. 

I think this will work but i'm unclear how the DMEPOS is implemented.

**Comment by mdsupport** [comment]
@sjpadgett As designed in ServiceRequest, encounter is mere reference. Any chance your revisions allow for an order lifecycle without an encounter - e.g. labs ordered as needed for pre-op physical or in many cases original order is from another requester but results are cc:ed by the lab based on patient record? Ideally the form should be accessible as a transaction and in encounter. Unfortunately there were too many bindings to the encounter when we last explored that.

Re. PA workflow, is it a manual process or something new in the system?
