### ISSUE TITLE
Search by any demographics search button disappears.

### ISSUE THREAD

**Issue by WalterConway** [openemr/openemr#4187]
### Describe the bug

When clicking on the search input for Search by any demographic the search button "disappears" and begins to slide back into place when the browser is at full width.
![image](https://user-images.githubusercontent.com/6686369/105549385-e03c5200-5cce-11eb-9a21-14efe0cc727f.png)

If shrinking the width of the browser is down you are able to see the issue more.
![image](https://user-images.githubusercontent.com/6686369/105549534-0530c500-5ccf-11eb-83ad-f2f8092d6a62.png)

### Expected behavior
The search button should stay in place and the search input should expand without affecting the button.

### Client configuration

- Browser:
- OpenEMR version: 6.0
- Operating system: Windows 10

**Comment by ujjwal-batra** [comment]
@tywrenn I want to work on this issue. I am new to openemr development can you please tell me where can I find the code related to this or which file to look into for this fix?

**Comment by fabriziofadigati** [comment]
Hi everyone,
I see that this issue hasn't been updated for a long time.

I tried to replicate the bug without success: it works on my side.

To @WalterConway
Could you give us more details from your browser console?
Are there enabled Javascript blocking extensions in your browser?

P.S I'm a beginner, I'm available to give my humble contribute to OpenEMR

**Comment by WalterConway** [comment]
Hi Fabrizio,

Here is a gif of the replication. Just click on the search box at the top
right and the button disappears for a sec and comes back. The issue is with
the onclick styling of the input box expanding. When the input is clicked,
it expands the input box. The button is pushed off the screen until it is
finished with the styling and then the button appears again.

Thanks,
Walter

**Comment by tywrenn** [comment]
Seems like this issue is still not fixed. The code resides in `interface/main/tabs/templates/patient_data_template.php` btw.

**Comment by WalterConway** [comment]
If this issue is still visible, then it should not be closeable until after
it is fixed. An issue being stale just says that no one wants to work it or
it is not a high priority issue so it goes stale. It should stay open.

Thanks.
