### ISSUE TITLE
Medical Record Dashboard Styling

### ISSUE THREAD

**Issue by WalterConway** [openemr/openemr#4189]
### Describe the bug

When viewing the Medical Record Dashboard page while multiple tabs are being viewed the side options of the MRD are overlapping the main content of the MRD page

### To Reproduce
![image](https://user-images.githubusercontent.com/6686369/105562992-89447600-5cea-11eb-9bcd-aa5aa67c284a.png)

1. View a page that's not the Dashboard and lock it
2. View the Dashboard page

### Expected behavior
Think of a way to style the side options...

### Client configuration

- Browser:
- OpenEMR version: 6
- Operating system: Windows 10

**Comment by tywrenn** [comment]
Does this issue fix itself when you change your theme to the default theme?

**Comment by sjpadgett** [comment]
see #4195 #4200 
i'm still looking at but main prob was using fixed width on demographics tabs.

**Comment by sjpadgett** [comment]
The fixes i'm testing with seem to fix issue involving Dashboard responsiveness. May need more but, what I have will do for now and am bring in for v6 patch(1).

Love this theme btw! iPad landscape
![image](https://user-images.githubusercontent.com/1859985/106319099-eb4b3100-623e-11eb-897f-139b7b41c757.png)
and light:
![image](https://user-images.githubusercontent.com/1859985/106319423-6ca2c380-623f-11eb-8ad5-24969e3a66fc.png)
