### ISSUE TITLE
Login languge selection should use characterset associated with that language

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#4196]
### Describe the problem
Thousand words below
![image](https://user-images.githubusercontent.com/399047/105882254-4ae4da80-5fba-11eb-9e62-d03d82c4be0f.png)

**Comment by tywrenn** [comment]
Are you referring to the dropdown having the charset loaded in that language or the HTML lang tag?

**Comment by mdsupport** [comment]
Yes. Looks like current logic is if installation default language is Japanese, we will display 英語 as the option leaving a non-japanese user to guess. Typically for the language switch you would have the option as : 
**`英語 (English)`**
When English is installation default, Japanese would be displayed as:
**`Japanese (日本人)`**
So the user either recognizes default characterset or translation of itself.

Come to think of it, most of the enterprise applications will have you select the language outside the login form. So the screen has language dropdown as part of the top and set to installation default. If the user changes it, server will send login screen in the selected language.
