### ISSUE TITLE
Bulk FHIR Export / Multiple Patient FHIR API support

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4203]
Tracking issue for Bulk FHIR implementation against ONC requirements.  We need to flesh out the BULK FHIR implementation.  Here's the latest progress report from Inferno against the smart-fhir-bulk pull request. I've attached to this issue.

![image](https://user-images.githubusercontent.com/228117/106326597-bb098f80-624a-11eb-8211-e9517e70901c.png)

**Comment by adunsulag** [comment]
Still working on this so bumping this.

**Comment by adunsulag** [comment]
This should not be closed.  Forgot to bump it.  We are nearing completion with the bulk FHIR export.

**Comment by adunsulag** [comment]
This is completed.

**Comment by bradymiller** [comment]
![2DV-2](https://user-images.githubusercontent.com/278968/140860886-db598145-8d18-4a52-a0e1-ef630de82d6d.gif)
