### ISSUE TITLE
Missing FHIR Resources

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4205]
### Describe the problem
We still have missing resources to complete our core FHIR API. Any help is appreciated and are needed very soon.
- CarePlan https://www.hl7.org/fhir/careplan.html
- Device https://www.hl7.org/fhir/device.html
- DiagnosticReport https://www.hl7.org/fhir/DiagnosticReport.html
- DocumentReference https://www.hl7.org/fhir/DocumentReference.html
- Goal https://www.hl7.org/fhir/Goal.html

@vishnuyar Are any of these in your plans?

**Comment by vishnuyar** [comment]
@sjpadgett Almost done with adding Surgery to Procedures FHIR Resource. 
Started working on Medication.
Can take up these resources next. If there is any importance of order, I can do them accordingly.

**Comment by sjpadgett** [comment]
@vishnuyar thanks
I'd say DiagnosticReport then DocumentReference. Device will need to be last I suppose.

**Comment by rhausam** [comment]
Wondering if there is a status update on where we are with these resources, @vishnuyar?  I'm familiar with them and responsible as an HL7 Orders and Observations Work Group Co-chair for DiagnosticReport and Device.  I'm interested in re-engaging and may be able to help with some of them if that's still needed.

**Comment by vishnuyar** [comment]
@rhausam , I got pulled somewhere else. Haven't made much progress. Currenly working on DiagnosticReport. You can take another FHIR Resource.
