### ISSUE TITLE
Create Multi Calendar Type support  as (jalali | persian | Shamsi Hijri ,Arabic | Hijri , other )

### ISSUE THREAD

**Issue by fardnia** [openemr/openemr#4216]
### Describe the problem

In some countries, such as Iran, the official calendar is defined differently. In these countries, daily work is done with a local calendar. 
In the geographical region of Persia, 300 million people use this type of history.

### Describe the solution you'd like
During the last ten years in Iran, from version 3.2 to 5, this format has been added to the code from the date with the following method.

//This file is created by amin hosseinzade fardnia
//in this file program decide to include wich date type library
//last update 4/8/2010
include_once("/opt/lampp/htdocs/openemr/interface/globals.php");
//fardnia 3/8/2010 : Shamsi date module include
switch ($GLOBALS['fardnia_calendar_type']){
case 0 :
        break;
case 1 :
        include "fardnia_jalali_calendar/jdf.php";
        break;
case 2 :
        //FADNIA:Arabic calendar
}

 function fardnia_multicalendar_j2g($date,$input_pattern='y-m-d')
 {
  if($date=='')
  {
  return $date;
  }
  else
  {
        //FARDNIA 08/08/2010: multi calendar type
        //this function get a text in yyyy-mm-dd and convert to English date
        switch($input_pattern){
        case 'y-m-d':
                $fardnia_date_fragmented=explode("-", $date);
                $fardnia_temp_date= jalali_to_gregorian ((int)$fardnia_date_fragmented[0], (int)$fardnia_date_fragmented[1], (int)$fardnia_date_fragmented[2]);
                return vsprintf('%04d-%02d-%02d',$fardnia_temp_date);
                break;

        case 'y/m/d':
                $fardnia_date_fragmented=explode("/", $date);
                $fardnia_temp_date= jalali_to_gregorian ((int)$fardnia_date_fragmented[0], (int)$fardnia_date_fragmented[1], (int)$fardnia_date_fragmented[2]);
                return vsprintf('%02d/%02d/%04d',$fardnia_temp_date[1],$fardnia_temp_date[2],$fardnia_temp_date[0]);
                break;
                
                              }
  }
 }
 
 function fardnia_multicalendar_g2j($date,$input_pattern='y-m-d',$switch_direction=false)
 {
  if($date=='')
  {
  return $date;
  }
  else
  {
        //FARDNIA 08/08/2010: multi calendar type
        //this function get a text in yyyy-mm-dd and convert to persian date
		
        switch($input_pattern){
        case 'y-m-d':
		
                $fardnia_date_fragmented=explode("-", $date);
                $fardnia_temp_date= gregorian_to_jalali ((int)$fardnia_date_fragmented[0], (int)$fardnia_date_fragmented[1], (int)$fardnia_date_fragmented[2]);
                
				if($switch_direction){
				$a= array();
				$a[0]=$fardnia_temp_date[2];
				$a[1]=$fardnia_temp_date[1];
				$a[2]=$fardnia_temp_date[0];
				
               return vsprintf('%02d-%02d-%04d',$a);
                }
				else{
				
				return vsprintf('%04d-%02d-%02d',$fardnia_temp_date);
				}
				break;
				
        case 'm/d/y':
                $fardnia_date_fragmented=explode("/", $date);
                $fardnia_temp_date= gregorian_to_jalali ((int)$fardnia_date_fragmented[2], (int)$fardnia_date_fragmented[0], (int)$fardnia_date_fragmented[1]);
                return vsprintf('%04d/%02d/%02d',$fardnia_temp_date);
                break;
                                }
								
		       
								
								
  }
 }
 
 function fardnia_multicalendar_date_g2other($date,$input_pattern='y-m-d')
 {
  //FARDNIA 08/08/2010: multi calendar type
  // this function select calendar for program and set too text box value
  switch ($GLOBALS['fardnia_calendar_type']){
        case 0 :
         break;
        case 1 :
                $date=fardnia_multicalendar_g2j($date,$input_pattern);
         break;
        case 2 :
               //FADNIA:Arabic calendar
        }
  return $date;
 }

 function fardnia_multicalendar_date_other2g($date,$input_pattern='y-m-d')
 {
  //FARDNIA 08/08/2010: multi calendar type
  // this function convert other type calender to gerigorian calendar
  switch ($GLOBALS['fardnia_calendar_type']){
        case 0 :
         break;
        case 1 :
                $date=fardnia_multicalendar_j2g($date,$input_pattern);
         break;
        case 2 :
               //FADNIA:Arabic calendar
        }
  return $date;
 }
 
 function fardnia_multicalendar_same_php_date($format, $utime)
 {
  //FARDNIA 08/12/2010: multi calendar type
  // this function simulate php date
  switch ($GLOBALS['fardnia_calendar_type']){
        case 0 :
                $date=date($format, $utime);
         break;
        case 1 :
                $date=jdate($format, $utime);
         break;
        case 2 :
               //FADNIA:Arabic calendar
        }
  return $date;
 }

 function fardnia_multicalendar_getdate(&$date)
 {
  //FARDNIA 08/12/2010: multi calendar type
  // this function get output of getdate and convert
  switch ($GLOBALS['fardnia_calendar_type']){
        case 0 :
         break;
        case 1 :
                $temp_date=gregorian_to_jalali ( $date['year'], $date['mon'], $date['mday']);
                $date['year']=$temp_date[0];
                $date['mon']=$temp_date[1];
                $date['mday']=$temp_date[2];
         break;
        case 2 :
               //FADNIA:Arabic calendar
        }
        // FARDNIA :  no returne , called by refrence
 }
 function fardnia_multicalendar_date_seperate_byref_other2g(&$year,&$month,&$day)
 {
  //FARDNIA 08/08/2010: multi calendar type
  // this function select calendar for program and set too text box value
  switch ($GLOBALS['fardnia_calendar_type']){
        case 0 :
         break;
        case 1 :
                $date=jalali_to_gregorian($year,$month,$day);
                $year= vsprintf('%04d',$date[0]);
                $month= vsprintf('%02d',$date[1]);
                $day= vsprintf('%02d',$date[2]);
         break;
        case 2 :
               //FADNIA:Arabic calendar
        }
        //called  byr refrence
 }

    
	function fardnia_multicalendar_date_number_to_shortname_of_day($number_of_short_day)
       {
	  //FARDNIA 13950314 a.f :added fro short day return by vall
      switch ($GLOBALS['fardnia_calendar_type']){
		case 0 :
            switch($number_of_short_day)
	         {
		    case 0 :return 'S';break;
			case 1 :return 'M';break;
			case 2 :return 'T';break;
			case 3 :return 'W';break;
			case 4 :return 'T';break;
			case 5 :return 'F';break;
			case 6 :return 'S';break;
			}
	      break;
        case 1 :
          switch($number_of_short_day)
	         {
		    case 0 :return _JDF_Sun_SHORT;break;
			case 1 :return _JDF_Mon_SHORT;break;
			case 2 :return _JDF_Tue_SHORT;break;
			case 3 :return _JDF_Wed_SHORT;break;
			case 4 :return _JDF_Thu_SHORT;break;
			case 5 :return _JDF_Fri_SHORT;break;
			case 6 :return _JDF_Sat_SHORT;break;
	        }
         break;
        case 2 :
               //FADNIA:Arabic calendar
        }
	return -1; 
}

**Comment by qomhmd** [comment]
Where do you put the code?
