### ISSUE TITLE
FHIR Metadata giving 401 error

### ISSUE THREAD

**Issue by vishnuyar** [openemr/openemr#4230]
### Describe the bug

fhir metadata shouldn't be part of authorisation scope. With recent change, the functionality of skipAuth for fhir/metadata is not working anymore.

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by bradymiller** [comment]
@vishnuyar , there are 2 more PR's that are about to come in related to fhir and i think the first will address this:
https://github.com/openemr/openemr/pull/4204
https://github.com/openemr/openemr/pull/4213

Code changes in the PR's are very significant, so would wait til those get into master before restesting/working on this bug (so you don't waste to much of your time).

**Comment by adunsulag** [comment]
@vishnuyar my PR fixes this problem.  I found the same issue and fixed it in the PR.

**Comment by adunsulag** [comment]
@vishnuyar is this problem now resolved from you?  I believe we can go ahead and close this issue now.
