### ISSUE TITLE
Dynamic Finder

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#425]
One of the features dropped in new interface is the patient search box from left_nav.  Few issues : 

1. The default columns in dynamic finder do not match left_nav options.
2. Dynamic finder is missing 'any' option.
3. This script uses a jQ [datatables plugin](https://datatables.net/download/index) and [an extension](https://datatables.net/extensions/colreorder/) in old directory. @bradymiller probably needs to do his magic to upgrade that.
3. Patient search is probably the most used function.  It currently lacks flexibility to make practices productive - e.g. almost all practices want deceased patients excluded from search unless user specifically asks for that.  Even in that case they want the search to be limited to deceased patients.

**Comment by bradymiller** [comment]
@mdsupport,
As I recall, in the past, I did try to upgrade that to the current version that is in assets, but I think it stumbled on the extension. That was awhile ago when learning how to do that stuff, so will try it again. Agree that we need to get the Finder up to par and at least provide the functionality that was removed when going from frames ui to tabs ui.
-brady

**Comment by bradymiller** [comment]
Here's a PR that consolidates/upgrades all the javascript datatables( and extensions) libraries:
https://github.com/openemr/openemr/pull/427

**Comment by bradymiller** [comment]
Just brought above PR into the codebase. Now that datatables has been updated, can move forward on improving the searching. Sounds like need to bring in the nuances from the frames patient search such as wildcards etc.

**Comment by mdsupport** [comment]
It may be better to use patient_select as a base.  By adding the patient box, we can restore the lost functionality.

![image](https://cloud.githubusercontent.com/assets/399047/21879969/16e84cfc-d851-11e6-9308-680a9c72931d.png)

Is there any practical benefit of datatables, column resizer, sort features?  Those would be good for regular reports.  For patient finders, staff hardly ever seem to use it.

Most important enhancements needed for patient_select will be dynamic update and ability to control layout and fields to be included in "all" searches.

**Comment by bradymiller** [comment]
@mdsupport , @sunsetsystems 
It will be good to get Rod's thoughts here since he developer the dynamic finder. I also didn't see much value to moving or resizing the columns especially since it gets lost on a page refresh(ie. I vote to remove the column move feature). The sorting can be very helpful though, especially when the list contains things like last encounter etc. Also could be helpful to search columns at same time. And helpful for it to be dynamic.  Also very helpful to have option of opening patient in another OpenEMR instance. Sounds like we are possibly headed towards a hybrid; the gui of the dynamic finder with the underlying guts of the patient_select.
Will be good to get others input on this.

**Comment by bradymiller** [comment]
Another option would be to offer both search pages in the menu for now and see where things go.
-brady

**Comment by sunsetsystems** [comment]
The Dynamic Finder was commissioned by David Eschelbacher who paid good money for it.  I'm pretty sure my clients are using it and couldn't imagine removing it.

Column reordering is just a feature built into the library.  Probably nobody uses it, but it's "free".

I agree the old search box is also a desirable feature.  I liked that it was always onscreen, but don't want to see anything that consumes more vertical space in the tabs layout.
