### ISSUE TITLE
LBF Groups Display Issue

### ISSUE THREAD

**Issue by dmuserallo** [openemr/openemr#4265]
With the newest version of OpenEMR, there were some formatting updates with LBFs that changed the user interface.  Prior to the most recent upgrade to version 6.0.0, groups within LBFs were displayed in a left-justified, single item, column format.  

With the upgrade, the groups are now being displayed horizontally in a row format with multiple groups listed in a single row.  The attached screenshot shows the current row display that appeared with the implementation of the updated 6.0.0 version.  

Would love to have the pre update display of left-justified, single item, column format back.  

@sjpadgett can you take a look?

Thanks so much!

**Comment by sunsetsystems** [comment]
I wonder if that change was intentional? Anyway I will soon have a bunch of layout-related updates for the master branch.

**Comment by sjpadgett** [comment]
My though as well. I'm not sure but, it's not really usable with groups on bottom.
I'm going to find where it went wrong and will let you know @sunsetsystems

**Comment by sjpadgett** [comment]
@sunsetsystems 
This is an easy fix. LBF/new.php L-820 
change
```<div class="row">```
to 
```<div class="flex-row">```

@dmuserallo you can make this minor change in your code and we'll ensure it will be included in our first patch.
The file reside in your openemr root dir tree at:  `interface/forms/LBF/new.php`

![image](https://user-images.githubusercontent.com/1859985/109561373-12e62100-7aab-11eb-83c8-3db4e25f84fc.png)

**Comment by dmuserallo** [comment]
Jerry,

Thanks for the fix!  We'll update our code.

Best,
Dava Muserallo, LCMHCS, LCAS, CCS, NCC
Clinical Director

New Leaf Behavioral Health | [map
<https://www.google.com/maps/preview/place/New+Leaf+Behavioral+Health/@35.8347547,-78.6667526,17z/data=!3m1!4b1!4m2!3m1!1s0x89acf62298be7ecd:0x1d703123bc45b8b4>
]
North Hampton Building
3725 National Drive | Suite 220
Raleigh, NC 27612-4879
P 919-781-8370 | F 919-781-2266
Website: nlbh.org

<https://www.facebook.com/pages/New-Leaf-Behavioral-Health/171395901710>
<http://www.linkedin.com/company/new-leaf-behavioral-health>
<https://plus.google.com/103201936265296957703/posts>
<https://twitter.com/NLBH_NC>

*Confidentiality Notice:* This message is being sent by or on behalf of a
behavioral health care provider. It is intended exclusively for the
individual or entity to which it is addressed. This communication may
contain information that is proprietary, privileged, confidential, or
otherwise legally prohibited from disclosure. If you are not the named
addressee, you are not authorized to read, print, retain, copy or
disseminate this message or any part of it. If you have received this
message in error, please notify the sender immediately by email or
telephone at 919-781-8370, and delete all copies of the message.

**Comment by dmuserallo** [comment]
Will do!  Thanks for the help!

**Comment by sjpadgett** [comment]
@sunsetsystems Are you going to add this to your PR or I could add to mine i'm getting ready to merge?

**Comment by sunsetsystems** [comment]
Jerry, please go ahead. Thanks!
