### ISSUE TITLE
v6.0.0 Billing Manager showing all dates

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#4271]
### Describe the bug
When opening the billing manager, the default is today. The billing manager pulls all dates. 

write a concise description of what the bug is.
see above

### To Reproduce

![image](https://user-images.githubusercontent.com/834958/110219000-a7c19380-7e8a-11eb-8d9e-e44e668c181b.png)

1. Go to demo
2. Log in demo
3. Open Billing manager
4. see all encounters loaded. 

### Expected behavior
Expected to not see any encounters in the list of encounters. And expected not to see encounters from January. 

### Client configuration

- Browser: Chrome
- OpenEMR version: 6.0.0
- Operating system:  Ubuntu

**Comment by stephenwaite** [comment]
@kchapple and @growlingflea fixed this with their overhaul in `master`

here's the [fix](https://github.com/openemr/openemr/blob/master/src/Billing/BillingReport.php#L74) which will put into 1st patch
