### ISSUE TITLE
Portal login does not work on v6.1.0-dev

### ISSUE THREAD

**Issue by benmarte** [openemr/openemr#4272]
### Describe the bug

Registration is fixed but logging in no longer works, the only way it works is if you reset credentials, change your password, and then login but after you log out you can no longer log in again.

I thought this might be an SSL issue but testing locally I can log in just fine after I reset the credentials, but as soon as I logout I can no longer log in.

### To Reproduce

1. git clone the repo
2. docker-compose up
3. enable the portal
3. Register a new patient in the portal
4. try to login with patient credentials
5. Oops something went wrong error message displays

![image](https://user-images.githubusercontent.com/693275/110220697-5b2f8580-7e95-11eb-9d7b-10e94c21d75c.png)
![image](https://user-images.githubusercontent.com/693275/110220706-6e425580-7e95-11eb-8a59-f02de29441b6.png)

### Expected behavior

I expect to be able to login with the users' credentials after registering and login in/out of the application.

### Client configuration

- Browser: Chrome
- OpenEMR version: v6.1.0-dev
- Operating system: docker/windows

**Comment by sjpadgett** [comment]
@benmarte 
This works for me. First, not sure how you ended up with a < 12 character username! Won't work...
Also, ya can't have any shared browser cache or sessions with openemr and portal. Many times in testing one may log in and out of openemr then log into portal etc and this can cause issues as well. Clear browser cache. Please report back if you still can't get to work as maybe your workflow is diff than mine...

@bradymiller This is not an issue I can do anything about as it's working for several I know about. Please don't hold patch...
