### ISSUE TITLE
Profile and Optimize Login.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4274]
### Describe the bug
Too me, login is too slow. Need to profile and see if anything we can do.

**Comment by stephenwaite** [comment]
![Screenshot from 2021-03-06 09-00-19](https://user-images.githubusercontent.com/5618372/110228471-76b78200-7ecf-11eb-8300-bb51880a8377.png)

**Comment by sjpadgett** [comment]
@stephenwaite I pulled master and can't recreate. I assume this is before globals require.
Is this from phpstorm?

**Comment by stephenwaite** [comment]
hi @sjpadgett , this is vscode, this is the globals require at line 28 of `interface/login/login.php` which creates that nested `$GLOBALS['GLOBALS']`

**Comment by sjpadgett** [comment]
@stephenwaite Yep, just not seeing it in phpStorm...

**Comment by stephenwaite** [comment]
Ok, see that, thanks @sjpadgett 

guess `GLOBALS` is a null array inside of `$GLOBALS` and vscode calls it `NaN` and just points it back at `$GLOBALS`

**Comment by sjpadgett** [comment]
Microsoft handles null and 0 terminated strings and arrays diff in their compiled languages. May just be a quirk with their PHP debug...

**Comment by stephenwaite** [comment]
![external-content duckduckgo com](https://user-images.githubusercontent.com/5618372/110244855-b6fa1d00-7f2e-11eb-8f49-2548079694b7.jpeg)

**Comment by sjpadgett** [comment]
yep, don't look a gif horse in the mouth!:)

**Comment by tywrenn** [comment]
This seems like a longshot but what about implementing opcache or some sort of php extension that optimizes loading times?
