### ISSUE TITLE
6.0.0 patch 1 progress

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#4275]
Just to keep folks appraised of status for patch 1.

 Below items are done. Just have some more testing to do. Am hoping to get out by **Saturday or Sunday**.

1. Security fixes (reported by Hagai Wechsler at https://www.whitesourcesoftware.com/)
2. Eye form fixes
3. Patient portal registration fix
4. WENO
5. UUID creation optimizations
5. Billing fixes
6. sql upgrade optimizations
7. Addition of Johnson & Johnson COVID-19 vaccine

**Comment by bradymiller** [comment]
Ok, all the fixes are now in rel-600. Now just gotta do some sanity testing and then will release patch (either will be tomorrow night or Saturday as long as testing goes well).

**Comment by stephenwaite** [comment]
![addams_family](https://user-images.githubusercontent.com/5618372/110930659-60f2f400-82f7-11eb-82b7-902d65f16b1c.gif)

**Comment by bradymiller** [comment]
testing showed break. just realized need to figure out a way to get the built css theme files into the patch. dang.

**Comment by bradymiller** [comment]
getting close. updated the patch builder script to have option of building themes/css stuff: https://gist.github.com/bradymiller/4f7817a7f2081891ccc93904914ea6f4
