### ISSUE TITLE
ONC 2015 C-CDA engine Phase 2.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4290]
This continues the C-CDA project with interop(HIE, Import/Export etc) and CCM fixes from issue #4131 .
Phase 3 will be testing and necessary template additions to meet final ONC testing criteria. 
We need phase 2 to support phase 3.
Help is always welcomed...

@vishnuyar and/or @rhausam I could really use the Document resource soon. Even if not finished, I'd help.

**Comment by rhausam** [comment]
@sjpadgett  I assume that likely you are referring to the DocumentReference resource?  There is also the ClinicalDocument profile which is a (relatively minor) constraint on the Composition resource, and is intended to correspond with CDA.  But I'm still thinking that you probably mean the former.

**Comment by sjpadgett** [comment]
yep the DocumentReference. Not so much for ccda but for all documents. Mainly pushing while Stephen is working on our search engine and I've still to decide whether to include ccda as binary, link or both.
Looking to get the resource in so we can start expanding it's workflow.

**Comment by sjpadgett** [comment]
For testing purposes here are some tools: 
- various: https://oncprojectracking.healthit.gov/wiki/pages/viewpage.action?pageId=58163335
- Edge and other: https://ett.healthit.gov/ett/#/home
- Validators: https://ett.healthit.gov/ett/#/validators

I believe we used Edge Protocol for SMTP for 2014. For previous CCD transport and generations, ZH provided a Mirth server that handled these tasks. The document generation was replaced by my ccda node service which is hooked from same place in CareCoordination module(CCM) previously routed to Mirth. 
The HIE appears to work by queueing up user selected Transition of Care/Referral/CCD etc from CCM export where at some point, Mirth handled interop transactions. Perhaps somebody can educate me on this.

Regardless of how previously done, my thinking is to support both transport options of which only one is necessary for ONC 2015. That is Edge Protocol for SMTP or Edge Protocol for XDR.

A good reason to support XDR/XDS is many states use for document(CCD/Immun) reporting e.g medicaid. Mainly via ADT/PIX feed and Provide and Register Document Set-b(PnR) to their document repository. This is in my mind a painful process considering the advent of FHIR and may not be worthwhile supporting however, I don't see many reporting agencies lining up to adopt the FHIR approach. Some input on this is wanted. I believe states also allow dropping via SFTP but unsure how many!
May have to do all three! First will be SMTP.

I have a jig for XDR I may convert to handle all document reporting disposition. Whether manual or by batch background service.
![image](https://user-images.githubusercontent.com/1859985/111707129-e3107a80-8819-11eb-839d-799655879450.png)

**Comment by stephenwaite** [comment]
bump

**Comment by sjpadgett** [comment]
All b1 requirements have been met and testing green against ONC sample scenarios. Will continue to build on warnings(generally should) as insurance. A long road no doubt!

scenario 1
![Message-Validators-ETT](https://user-images.githubusercontent.com/1859985/127757575-9ce76632-e2d4-4c19-9286-dfbcf0a5e96c.png)

scenario 2
![Message-Validators-ETT](https://user-images.githubusercontent.com/1859985/127757626-f78ad50d-784d-4775-baa4-a9a9ca323a2e.png)

scenario 3
![Message-Validators-ETT](https://user-images.githubusercontent.com/1859985/127757648-0fed927e-de4f-4da8-9681-ce10278e5964.png)
