### ISSUE TITLE
Insurance Module - Making Field Additions to Layout

### ISSUE THREAD

**Issue by dmuserallo** [openemr/openemr#4305]
I wanted to add a text area field in the insurance module under each insurance for Insurance Notes (we check specific insurance codes for behavioral health, and we keep track of the types of sessions covered). I’m familiar with updating layouts, including the demographics layout, but don’t see where I have access to the insurance module. Is this possible to update/add?

**Comment by sunsetsystems** [comment]
Insurance is not layout based so it would require some coding. See:
library/classes/InsuranceCompany.class.php
templates/insurance_companies/

**Comment by stephenwaite** [comment]
been in there a little bit too much lately, there's also the real time eligibility that @sjpadgett  added that sounds like might be a better fit for your search for tracking coverage

**Comment by dmuserallo** [comment]
Thanks for the information!  @spadgett, how might I be able to access the real time eligibility feature?  What I am looking to do is store information related to codes covered, benefit periods for insurance, OOPM.  Would love it if I could track/store that data along with eligibility!

**Comment by stephenwaite** [comment]
hi @dmuserallo , [here's a thread from the forum](https://community.open-emr.org/t/eligibility-checks-clearinghouses/9742/110?u=stephenwaite)
