### ISSUE TITLE
FHIR Diagnostic Report for Radiology, Cardiology, Pathology

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4307]
We need to implement the [FHIR Diagnostic Report resource](http://hl7.org/fhir/us/core/StructureDefinition-us-core-diagnosticreport-note.html) for radiology, cardiology, and pathology reports in the system.  Brady said the best person to get information in this area might be @sunsetsystems.  

In order to implement this we need to know the tables to search in for each of these categories and their corresponding LOINC codes.  I've pasted a screenshot of the FHIR attributes we need to populate for ONC. 

![image](https://user-images.githubusercontent.com/228117/112645075-7fd7a700-8e1c-11eb-986e-7e613dbb6eee.png)

The big thing is tracking down the records in the database and the corresponding LOINC code for the record.  Here is a sample from HL7 [http://hl7.org/fhir/us/core/ValueSet-us-core-diagnosticreport-report-and-note-codes.html](http://hl7.org/fhir/us/core/ValueSet-us-core-diagnosticreport-report-and-note-codes.html)

**Comment by stephenwaite** [comment]
hi @adunsulag , what about `procedure_result.result_code`?

**Comment by sjpadgett** [comment]
@adunsulag Are you going to write this resource?
I can give you the queries from either electronic reports or CCM that populates dataset for CDA results section.
The codes are part of the compendium(procedure configuration) so no look ups for those.

**Comment by adunsulag** [comment]
@sjpadgett We currently don't have the DiagnosticReference service so I planned on writing this resource as part of the work Brady asked me to do.  At least I'm providing an estimate on it, it will be up to y'all to decide if that makes sense or not. 

If you have the queries that would be wonderful as that will shave off a lot of time for me.

Supposedly there is intended to be a downloadable version of these diagnostic reports that the user agent requesting the report can then download.  The URL is supposed to be stored in the Attachment attribute of the DiagnosticReport resource.

**Comment by sjpadgett** [comment]
Okay, per our convo here's an example of various data have access to: LOINC are used in results.
![image](https://user-images.githubusercontent.com/1859985/112674732-a9082f80-8e3c-11eb-9e42-5822b12641e5.png)
