### ISSUE TITLE
merge patient bug

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#4308]
### Describe the bug

merge patients doesn't check for primary conflict in `lists_touch`
![Screenshot from 2021-03-26 15-01-39](https://user-images.githubusercontent.com/5618372/112680834-3e5af200-8e44-11eb-802a-c908ca8158c8.png)

### To Reproduce
add some meds to a couple of patients
merge patients

**Comment by sjpadgett** [comment]
https://www.mysqltutorial.org/mysql-replace.aspx/
always gets me out of these pickles....

**Comment by stephenwaite** [comment]
![PICKLE](https://user-images.githubusercontent.com/5618372/112692511-728ade80-8e55-11eb-8bcd-2877a3d431c8.gif)

**Comment by sjpadgett** [comment]
@stephenwaite 
I haven't set this up to try so maybe you can take a look.
[merge_patients.zip](https://github.com/openemr/openemr/files/6214449/merge_patients.zip)

**Comment by stephenwaite** [comment]
![zippy](https://user-images.githubusercontent.com/5618372/112696216-ca2c4880-8e5b-11eb-8ecf-483dfbd01792.gif)

**Comment by sjpadgett** [comment]
I just thought it might be a quick fix. git won't allow .php uploads....

**Comment by stephenwaite** [comment]
yeah, cool, but looks like this form of the replace statement doesn't support where clause so i'll go ahead and add a select statement and an if statement for `lists_touch` which may be the only prob right now with that unique key of pid

**Comment by stephenwaite** [comment]
darn, @adunsulag's cool `SqlQueryException` isn't in `rel-600`

**Comment by sjpadgett** [comment]
try/catch doesn't work on sql api!!!
prob need to have separate statement for this type of table because the index is setup on primary pid and type for uniqueness.

**Comment by stephenwaite** [comment]
stephen n added the `sqlStatementThrowException`
```
 try {
            $sql = "UPDATE " . escape_table_name($tblname) . " SET " . escape_sql_column_name($colname, array($tblname)) . " = ? WHERE " . escape_sql_column_name($colname, array($tblname)) . " = ?";
            echo "<br />$sql ($count)";
            if ($PRODUCTION) {
                sqlStatementThrowException($sql, array($target_pid, $source_pid));
            }
        } catch (\RuntimeException $msg) {
```
