### ISSUE TITLE
Bug FHIR Encounter API not returning results

### ISSUE THREAD

**Issue by benmarte** [openemr/openemr#4310]
### Describe the bug

The FHIR Encounter API endpoint does not work. I have a patient with a few encounters as you can see here:

![image](https://user-images.githubusercontent.com/693275/112756149-d1656a80-8fb1-11eb-9f49-fdec173396d8.png)

When I ping the endpoint with the user id it does not return anything besides `null`, apache log for reference.

```
[Sun Mar 28 14:32:59.289680 2021] [php7:notice] [pid 1024] [client 172.25.0.1:34218] [2021-03-28T14:32:59.289113+00:00] OpenEMR.DEBUG: dispatch.php authenticating user [] []
[Sun Mar 28 14:32:59.305994 2021] [php7:notice] [pid 1024] [client 172.25.0.1:34218] [2021-03-28T14:32:59.305948+00:00] OpenEMR.DEBUG: dispatch.php valid role and user has access to api/fhir resource {"resource":"/fhir/Encounter/930f2cae-d5d2-45f1-b024-e3dcf0a62f1a"} []
[Sun Mar 28 14:32:59.313592 2021] [php7:notice] [pid 1024] [client 172.25.0.1:34218] [2021-03-28T14:32:59.313533+00:00] OpenEMR.DEBUG: HttpRestRouteHandler::dispatch() start request {"resource":"","method":"GET","user":"","role":"users","client":"A4kh_OEHWBaRgvQAgjhY5Ljb2x-PQ4oBTpuKErFeWGI","apiType":"fhir","route":"/fhir/Encounter/930f2cae-d5d2-45f1-b024-e3dcf0a62f1a"} []
[Sun Mar 28 14:32:59.316839 2021] [php7:notice] [pid 1024] [client 172.25.0.1:34218] [2021-03-28T14:32:59.316785+00:00] OpenEMR.DEBUG: HttpRestParsedRoute->__construct() matched {"routePath":"GET /fhir/Encounter/:id","requestPath":"/fhir/Encounter/930f2cae-d5d2-45f1-b024-e3dcf0a62f1a","method":"GET","routeParams":["930f2cae-d5d2-45f1-b024-e3dcf0a62f1a"],"resource":"Encounter","operation":""} []
[Sun Mar 28 14:32:59.316922 2021] [php7:notice] [pid 1024] [client 172.25.0.1:34218] [2021-03-28T14:32:59.316886+00:00] OpenEMR.DEBUG: HttpRestRouteHandler->dispatch() dispatching route {"route":"GET /fhir/Encounter/:id"} []
[Sun Mar 28 14:32:59.384749 2021] [php7:notice] [pid 1024] [client 172.25.0.1:34218] [2021-03-28T14:32:59.384698+00:00] OpenEMR.DEBUG: Destroying api 
session cookie {"name":"apiOpenEMR","cookieParams":{"lifetime":"28000","path":"/apis/","domain":"","secure":"1","httponly":"1","samesite":"Strict"}} []
```

This is on the latest master.

### To Reproduce

- create a patient
- create a few visits for patient
- verify past encounters and documents tab to ensure encounters were created
- query the encounter endpoint with the user id
- null is returned
- tail the error log to see errors

### Expected behavior

The expected behavior is for the encounter list to match what is in Open EMR encounters

### Client configuration

- Browser: Chrome
- OpenEMR version:  v6.1.0-dev
- Operating system: docker in windows 10

**Comment by sjpadgett** [comment]
@benmarte 
`GET /fhir/Encounter/:id`
remove the colon before id..
`GET /fhir/Encounter/id`

**Comment by benmarte** [comment]
@sjpadgett I am not passing `:id`

This is the actual endpoint I'm hitting when getting the error:

`http://localhost:8300/apis/default/fhir/Encounter/930f2cae-d5d2-45f1-b024-e3dcf0a62f1a`

**Comment by sjpadgett** [comment]
okay  I believe the encounter resource itself returns only by encounter id so to get encounter for patient
http://localhost:8300/apis/default/fhir/Patient/:id/Encounter
check docs though.

**Comment by bradymiller** [comment]
@benmarte ,
Is that the uuid for an encounter or for a patient?
(as @sjpadgett points out, need to use encounter uuid for that endpoint; a patient search on encounters (if that is a patient uuid) would be `http://localhost:8300/apis/default/fhir/Encounter?patient=930f2cae-d5d2-45f1-b024-e3dcf0a62f1a`)
what happens with? (this should list all of the encounters of all patients):
```
http://localhost:8300/apis/default/fhir/Encounter
```

**Comment by benmarte** [comment]
Oh ok so this is in fact not a bug and just me misunderstanding how the api works, before using FHIR I was using the OEMR API which works differently, thanks for clearing this up guys.

The bug is me, I'm the bug 🙃 🤣
