### ISSUE TITLE
Document does not delete from controller after upgrade to 6.0.0

### ISSUE THREAD

**Issue by vrjula** [openemr/openemr#4311]
### Describe the bug

Since the upgrade, when I delete a file from the Documents List, the item is removed from the list (i.e., the database), but the actual file remains in the site’s Documents folder.

### To Reproduce

Pic below shows what happens when I delete an item from Documents List, after the upgrade:
![image](https://user-images.githubusercontent.com/60139689/112756362-69f7ec80-8faa-11eb-8e39-b92493736a60.png)

Here is a pic of the same action when I used a backup, on version 5.0.2 before the upgrade. When comparing, the “DELETE FROM documents…” seems to be missing, after the upgrade.
![image](https://user-images.githubusercontent.com/60139689/112756378-8136da00-8faa-11eb-8147-173f110474f1.png)

### Expected behavior

Upon deleting an item from the controller, the file should also be deleted from the Documents folder.  

### Client configuration

- Browser: Firefox 86.0
- OpenEMR version: 6.0.0 (1)
- Operating system: Debian Buster

**Comment by sjpadgett** [comment]
@vrjula 
I thought in the past we deleted the file but looking at code it looks like we only do a soft delete. Makes sense for HIPAA maybe. Still hard for file management.
@bradymiller @stephenwaite Do you recall if document delete is supposed to be only a soft delete?
