### ISSUE TITLE
Add Clinical Notes

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4312]
### Describe the problem
Need various notes:
• Consultation Note
• Discharge Summary Note
• History & Physical
• Imaging Narrative
• Laboratory Report Narrative
• Pathology Report Narrative
• Procedure Note
• Progress Note

My current thinking is to replicate the Care Plan encounter form to a Clinical Notes form. In this way more than one note can be added within one form for the encounter.

Let me know soon if anyone disagrees because, i'm on a mission....

**Comment by mdsupport** [comment]
When there is a need, [hl7 designs](http://hl7.org/fhir/us/core/2019Jan/clinical-notes-guidance.html) are a good resource. This takes us away from encounter based forms. As an example, an internist gets copy of lab report resulting from patient's visit to her  cardiologist. If the two MDs had a chat, where would the information be recorded?

I think it may be good to bring in the [Observation entity](https://www.hl7.org/fhir/observation.html) including their terminology. Then over period each entry point can add color to the stored records. At core observation.note is the basic data. Other things provide the context to that note. An example would when reviewing imaging document the observation record can reference document.id as basedon, referral.id as imagingstudy container (if available) etc. The same record if reviewed during an encounter can add encounter.id.

While implementing an full blown observation object will involve lot of work, a generic structure could be delivered as limited PR. That will let future developers build specialized features.

**Comment by sunsetsystems** [comment]
Surely layout-based would be easiest as well as flexible? Where there are multiple unrelated notes for a visit, multiple forms may be saved.

**Comment by dmuserallo** [comment]
I would love to see more narrative sections for static information that can be housed within a client record.  We could benefit from some additions to the insurance module that allows for a more narrative description of data (including benefit period, type of plan (PPO, POS, etc), cpt codes covered, OOPM and how much met, Deductible and how much met, exclusions to coverage.  All of this could be address with a data field text area.  Just some additional insurance info that might be helpful for more specialized practices, such as behavioral health!

**Comment by bradymiller** [comment]
From a provider perspective, 1 text box (aka description field in Care Plan) that takes up almost the whole view with a date and type field (don't know if need for a code field though) will suffice to both be clinically useful and fulfill ONC (although there will be as many opinions as providers, in the bigger EMRs, templating is generally happening now within one text field, so we can build on your current templating mechanism towards that end). Agree to avoid LBF here or else would open door to user customizing themselves out of ONC2015 certification, and we keep "control" over the back end container endpoints for fhir/ccda.

**Comment by bradymiller** [comment]
The Care Plan mechanism is also neat, because as you pointed out, a user can add another form (so gives flexibility to do multiple forms within one form). I wasn't aware of that functionality until now. neat stuff.

**Comment by sunsetsystems** [comment]
The topic of users screwing things up is a broad and interesting one. It could be addressed with a report (or other code block) that looks for such problems.

**Comment by mdsupport** [comment]
@sjpadgett Are you able to leverage your text templates feature into notes? One of the recurring feedback is reports from this emr are screen prints while others have features that will take a form and turn into a paragraph with minimal data entry by the clinicians. Operationally multiple copies of same form in an encounter causes reconciliation challenges unless it is multiple providers or observations at different times.

**Comment by sjpadgett** [comment]
Ageed. We need some sort of attribute we can attach to a item that prevents edits.
fyi here are types for notes.
![image](https://user-images.githubusercontent.com/1859985/113064741-a29fed80-9185-11eb-97e2-e0530c33d451.png)

although i'm thinking maybe should just add to Patient Note Types list however, makes for a long list.
![image](https://user-images.githubusercontent.com/1859985/113064860-d67b1300-9185-11eb-805b-bdd2d8084531.png)

@mdsupport 
I'm now setup that any encounter forms text or text area(by dbl click in text area) can use the Text Template engine. The context is preset to Encounters.
![image](https://user-images.githubusercontent.com/1859985/113066950-72f2e480-9189-11eb-85a3-09136b88480a.png)

**Comment by mdsupport** [comment]
If these notes are expected to be part of the source/referring object then note type can map to text template context. So lab order can have the textbox which when clicked will open laboratory report narrative, box on the encounter summary form can be progress note etc... just accept context from `data-context` attribute of the textbox/textarea.

**Comment by sjpadgett** [comment]
yep

**Comment by sjpadgett** [comment]
Got sidetracked but this is my Notes for encounter. I think this is workable and easy to manage all the encounter notes in one place. I took the form from care plan which I liked the design of very much. Just put some Jerry in it!:)
Adding note contexts for the text templating engine in now then will PR it unless there is push back or suggestions...

![image](https://user-images.githubusercontent.com/1859985/113234019-79a75780-926e-11eb-865c-a7270c2500ba.png)

Report
![image](https://user-images.githubusercontent.com/1859985/113234147-b96e3f00-926e-11eb-93c5-b3cd6adc097d.png)

**Comment by bradymiller** [comment]
nice stuff!
Would give more viewspace, if possible, to the textfield views (it feels confining when trying to work on notes and keep needing to scroll up/down and left/right). Maybe if stack the date/type/text fields vertically and then have the textfield get full width and otherwise full height (and if they add a note, then go to half height etc.). Note most of the time only one note will be entered in here, but is really nice to provide option to do more than one type of note.

**Comment by sjpadgett** [comment]
textareas are somewhat difficult to size responsive as such. these will word wrap and remember these also can be pulled for more height. changed to 14 row by 9 columns viewport. responsive stacked on tablets. is this better:

![image](https://user-images.githubusercontent.com/1859985/113241258-51265a00-927c-11eb-977c-65ddc7567b47.png)

**Comment by bradymiller** [comment]
![2DV (1)](https://user-images.githubusercontent.com/278968/113241462-a3a74c80-9263-11eb-9e5a-0c19d96c710f.gif)

**Comment by sjpadgett** [comment]
@mdsupport 
Add the data contextual attribute to any of the note types in this form. I'm not going to set any defaults to custom list as user is told to create context if not already.
![image](https://user-images.githubusercontent.com/1859985/113248111-4a9edf00-928a-11eb-80f0-2057a99e7113.png)
![image](https://user-images.githubusercontent.com/1859985/113248508-1c6dcf00-928b-11eb-9cf9-09f25c0076cb.png)

anyway, gotta move on...

**Comment by mdsupport** [comment]
Given that ONC is the priority, one deferred improvement would be to include user and allow only that user or the supervising md to edit a note. Effectively the notes would display as : 

**[Note type] by [full user name] on [create or modify date] {Edit Button/link]**

- Dolorem partiendo sea ut. 
- Et ius omnium efficiantur, his in aperiri honestatis. Ei per quando postea, no integre invidunt complectitur eos. Eos an utinam fierent partiendo. Delenit legimus concludaturque no cum, inani iudicabit consetetur ne his. Eum dicunt scripta ut, labores intellegat id ius.
 
- Eum elitr nostrum fierent ad
- Vim cu salutatus gubergren torquatos. Quaestio inciderint an quo, natum consetetur te vis. Ea vis quot minimum, minimum signiferumque ad mea, sea ut feugait inciderint. Eam id unum dicat inermis, ad sumo dicta has, labore commune periculis ad his.

**Comment by sjpadgett** [comment]
> Given that ONC is the priority, one deferred improvement would be to include user and allow only that user or the supervising md to edit a note. Effectively the notes would display as :

This is a good suggestion. At min adding user would help maintain provenance for the note. Maybe not for edits except for the last author. Somehow we need an audit trail that a user can't delete. Something like a who touched in most areas of chart but especially encounters.

**Comment by mdsupport** [comment]
If you copied or retained the care plan data structure, it does have a single user and single date. For audit/tracking that needs to be revisited. Both care plan and now your form are different than other encounter forms as these have multiple creator/updator chains. It may be good to suppress any reference to user/creator in report header for these forms.
Don't think certification cares about these operational details though so onwards...

**Comment by sjpadgett** [comment]
Right now I can get away with the note author for provenance which would be the logged in user.
Most likely the first note in encounter will be a Nurse Note then provider may add another for his purposes etc.
Edit audits will have to wait... Thanks @mdsupport

**Comment by sjpadgett** [comment]
@adunsulag 
Hi Stephen. Don't know if you've been following this but getting ready to bring in if any comment concerning FHIR....
