### ISSUE TITLE
Version of ADOdb specified in composer.json 5.20.18 is not compatible with PHP 8.  Need 5.20.20 or higher

### ISSUE THREAD

**Issue by RachelElli** [openemr/openemr#4315]
### Describe the bug

The issue is discussed here:
https://community.open-emr.org/t/cant-make-a-backup/16345/12

After updating to version 6.0 on the latest version of xampp user is not able to create a backup of the database.
Xampp version uses PHP 8....

Error message within the user interface states:
"The error says: Dumping OpenEMR database…
There was an error on the backup"

Inside the xampp PHP error log it prints:
"
Mohamed
4h
PHP Fatal error: Uncaught TypeError: mysqli_query(): Argument #1 ($mysql) must be of type mysqli, bool given in D:\xampp\htdocs\openemr\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php:788\nStack trace:\n#0 D:\xampp\htdocs\openemr\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php(788): mysqli_query(false, 'SET NAMES ‘utf8…’, 0)\n#1 D:\xampp\htdocs\openemr\vendor\adodb\adodb-php\adodb.inc.php(1263): ADODB_mysqli->_query('SET NAMES ‘utf8…’, false)\n#2 D:\xampp\htdocs\openemr\vendor\adodb\adodb-php\adodb.inc.php(1241): ADOConnection->_Execute('SET NAMES ‘utf8…’, false)\n#3 D:\xampp\htdocs\openemr\library\ADODB_mysqli_log.php(60): ADOConnection->Execute('SET NAMES ‘utf8…’, false)\n#4 D:\xampp\htdocs\openemr\library\sql.inc(58): ADODB_mysqli_log->ExecuteNoLog('SET NAMES ‘utf8…’)\n#5 D:\xampp\htdocs\openemr\interface\globals.php(268): require_once(‘D:\\xampp\\htdocs…’)\n#6 D:\xampp\htdocs\openemr\interface\login\login.php(28): require_once(‘D:\\xampp\\htdocs…’)\n#7 {main}\n thrown in D:\xampp\htdocs\openemr\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php on line 788"

complaining about this file
D:\xampp\htdocs\openemr\vendor\adodb\adodb-php\drivers\adodb-mysqli.inc.php

The error seemed consistent with behavior seen when old code tries to use depreciated capabilities.

Checked the vendor's PHP compatibility chart on their website and saw that the version installed with the composer.json file is not compatible with PHP8
https://adodb.org/dokuwiki/doku.php?id=v5:php_compatibility_status

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by stephenwaite** [comment]
nice report @RachelElli !

do you think the user wants to try to [run composer on windows](https://getcomposer.org/doc/00-intro.md#installation-windows) to test the approved version?

**Comment by RachelElli** [comment]
Sounds like he was planning on trying again on a version running PHP7.3

**Comment by stephenwaite** [comment]
be nice to test it out on windows if possible but sounds like it's the fix

**Comment by bradymiller** [comment]
I wonder if this is specific to windows since I didn't have this problem in the backup gui when testing on PHP8 (via the Alpine OS docker) in the past.

**Comment by bradymiller** [comment]
Just confirmed that backup is still working on the php8-fpm docker. Will be interesting to see if this users problem goes away with PHP 7.3. 
Either way, though, sounds like it is definitely time to update the packages in composer on master (note that we don't have a mechanism to get new packages via composer into patches, though, but we could sort something out if needed).
