### ISSUE TITLE
FHIR create patient API not working

### ISSUE THREAD

**Issue by ravi-gadhiya-think** [openemr/openemr#4316]
### Describe the bug
Tried the POST api for create patient as mention on documentation, but getting 400 Http response code.

### To Reproduce

1. Go to FHIR create patient documentation https://github.com/openemr/openemr/blob/master/FHIR_README.md#post-fhirpractitioner
2. Copy curl mention on Request and paste while importing curl into postman. (Our instance is running on 9000)
![image](https://user-images.githubusercontent.com/80255646/112999674-c9aded80-918c-11eb-94ca-3075edcc4eaf.png)

3. Add authorization token
![image](https://user-images.githubusercontent.com/80255646/113000167-31643880-918d-11eb-8241-7f265f9abbf1.png)

4. After clicking on send button, it showing following error
![image](https://user-images.githubusercontent.com/80255646/113000336-59ec3280-918d-11eb-9f87-9c17bf7e4b04.png)

### Expected behavior
It should return id of newly created patient.

### Client configuration

- Browser:
- OpenEMR version: v6.0.0
- Operating system:

**Comment by FergusInLondon** [comment]
This looks to be a documentation issue, and is actually the desired behaviour.

As per the FHIR specification, a `[HumanName](http://hl7.org/fhir/stu3/datatypes.html#HumanName)` type **must** contain a `use` property. The `use` attribute is checked on every name provided, and only the "official" one is accepted.

```
        if (isset($fhirResource['name'])) { // FhirPatientService.php:L394
            $name = [];
            foreach ($fhirResource['name'] as $sub_name) {
                if ($sub_name['use'] === 'official') {
                    $name = $sub_name;
                    break;
                }
            }
            // ... 
        }
```
If you try this payload it will work:

```
{
  "resourceType": "Patient",
  "identifier": [ { "system": "urn:oid:1.2.36.146.595.217.0.1", "value": "12345" } ],
  "name": [ {
			"use": "official",
      "family": "Chalmers",
      "given": [ "Peter", "James" ]
  } ],
  "gender": "male",
  "birthDate": "1974-12-25"
}
```
