### ISSUE TITLE
Care Plan ONC

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4317]
### Describe the problem
Additional items need to be recorded.
### Describe the solution you'd like
So far required:
- plan status
- plan intent
- activity status

Unsure if we'll need for usefulness
- goal
- reason code

Be helpful you anyone catches me missing something.

And yes I Love openemr?:)

**Comment by bradymiller** [comment]
@sjpadgett , here are some notes I made when discussing with @adunsulag on using the Care Plan form to contain this stuff to support the fhir us core (https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-careplan.html). Would consider this a super lazy way to go :) :
'text' (a narrative summary of the patient assessment and plan of treatment) from Description field (with status of 'additional')
'status' always 'unknown'
'intent' almost always 'plan' (except for when user chooses the Procedure or Test/Order type; then would use 'order')
'category' confuses me a bit. It looks like need to always use 'assess-plan', but not sure yet (sometimes gotta read these things multiple times to figure it out but am pretty sure just always fix this to assess-plan). If I am wrong on this and it is requiring another category, then could always use 'Outpatient care plan' (snomed code 736271009).

**Comment by sjpadgett** [comment]
@bradymiller 
If we go the lazy way then intent, status and category(not required) can be static in the fhir resource when populated.
All said and done, we could get by without touching care plan form as i've been doing in CCDA.
However, we still have Goals and Health Concerns which should be an encounter form in it's own right.
I've never understood why these are not already part of encounter along with recording diagnosis codes for the encounter. We leave that to billing which is okay but makes reporting encounter activity difficult if billing is not done yet.  Yes we have issues but, is that enough?
Some of the eventual needed care plan data can come from new clinical notes and/or existing encounter forms i.e. assessment(unsure if we have), ROS and so forth.
Still i'm trying to hit the sweet spots while i'm into this.

I think maybe i'll hold off on care plan for a minute till clinical notes are finished and i'll retest cda on test servers. This tells me if care plan is sufficient as is. Fhir requirements will be the same as cda.

I'm still debating if putting in the work on patient progress form up on PR now is worth the effort. I think it hits most all our requirements. Again:
![image](https://user-images.githubusercontent.com/1859985/113060392-92384480-917e-11eb-85cd-9b52034541b5.png)
![image](https://user-images.githubusercontent.com/1859985/113060515-bf84f280-917e-11eb-8112-8a38454a36bd.png)

**Comment by bradymiller** [comment]
For goals (https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-goal.html), these could be taken from the CDR engine (those items that end up in the Clinical Reminders section on the patient summary screen). There's already a function that grabs these in the appt report. In clinical realm, we usually don't create a note with explicit goals on it (although some specialties such as physical therapy do), but there is always a list of things (like cancer prevention measures, bp monitoring/control, dm management) that should be doing which are ideally captured in the cdr items.

**Comment by sjpadgett** [comment]
@bradymiller 
Thinking this over(Goals) I believe using reminders would not be specific enough to a stated plan of care for an encounter.
Will add goals to encounter plan of care unless you disagree.
Also need Health Concerns, Assessment and Mental Status all new cda templates(ho hum!).

**Comment by bradymiller** [comment]
hi @sjpadgett 
I do not disagree
Do whatever you must do to squash ccda into a finely tuned machine :)

**Comment by sjpadgett** [comment]
![image](https://user-images.githubusercontent.com/1859985/118372571-59163100-b580-11eb-8ae8-e799109b3ebd.png)

**Comment by adunsulag** [comment]
Hey @sjpadgett my apologies for not catching this earlier, or if you changed this around since you commited these issues, but when I go to get the  Care Plan form type for **goal** it doesn't appear to be in the Form Options.  Did you move this somewhere else?  I can see it in your screenshot you have above: 
![image](https://user-images.githubusercontent.com/228117/119713771-141bb580-be30-11eb-92f1-99f724c608b9.png)

But I don't see it in the List Options when I select the Care Plan Type dropdown.  I've got careplan now working and I'm ready to move onto goals.

**Comment by sjpadgett** [comment]
@adunsulag It's on my local and was going to commit my next PR which is for Goals that I'm working also.
I'll send you a query to import in a few.

**Comment by adunsulag** [comment]
@sjpadgett  That's ok, there's plenty of observation resources to do!  I keep avoiding tackling DiagnosticReports... I'll get to them eventually.  Goals was on my list, but I was just double checking with you.

**Comment by sjpadgett** [comment]
Reopen as needs more template work.
- correct observation moodcodes to better match plan type.
- add medication substances activity

Talking to some of the clinicians in my family, all seem to prefer doing this in SOAP notes though agree the care plan encounter form is just another form of a SOAP note so, in the end, I don't think this is making life any easier for our users!

**Comment by stephenwaite** [comment]
![external-content duckduckgo com](https://user-images.githubusercontent.com/5618372/121191348-e411e080-c839-11eb-9e98-cc568dce636e.gif)
