### ISSUE TITLE
ONotes Doctrine ORM Implementation

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#432]
This picks up from the pending-merge `MatthewVita:doctrine_and_other_moderization_work` branch.

ONotes (`/library/onotes.inc`, `/interface/main/onotes/office_comments.php`, `/interface/main/onotes/office_comments_full.php`) is the next entity to model with Doctrine. Doing so will also provide an example on how `JOIN`s work because this table can join on the `users` table.

**Comment by MatthewVita** [comment]
@bradymiller I've never actually noticed this feature. It seems like it would be useful for folks at the front desk, right?

I may improve the UX a bit if you don't mind. UPDATE: I just noticed that once you get over 10 notes, the `office_comments_full.php` code is used with pagination. Very nice. The only things that I can think of that may improve this feature are:

- Allow for newlines
- http://localhost/openemr/interface/main/onotes/office_comments_full.php?active=1 in the browser (i.e.: outside of the frames) will not allow the user to add a new note (Uncaught TypeError: top.restoreSession is not a function at <anonymous>:1:5). Perhaps I can use JavaScript to check for the existence of this function and if it's undefined just show a "read only view" heading.
- Rename "[Change Activity]" to "[Update Notes]"
- Places the notes in "cards" so they can breath a bit more and are more modern looking:

![image](https://cloud.githubusercontent.com/assets/1715206/21970970/216c654c-db7a-11e6-8630-a8a16dae0268.png)

...looks a lot better! Okay, I should probably get into the Doctrine side of this now :)

**Comment by bradymiller** [comment]
We'll always take any UI improvements :)
regarding top.restoreSession, this is a sign that something is wrong; it always needs to be available whether it be main app or in a popup/frame (this prevents session confusion when a browser has several different isntances of OpenEMR opened at the same time). Did it pop out into it's own frame or was this manually done via link copy?(if manually done, then can ignore, since this is meant to happen when application is used)

**Comment by MatthewVita** [comment]
Hmmm... I can't remember if the app itself opened in another tab or if I clicked it that way (middle click).

I will let you know if comes up again!

**Comment by MatthewVita** [comment]
merged :)
