### ISSUE TITLE
xml escaping

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#4325]
@sjpadgett , planning to incorporate a xmlEscape function in interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php ,
which will involve modifying most of the lines of code in that script. Just making sure you haven't modified this file yet in your ccda work. (btw, am going through ccda creation steps with plans to help out on it, which is why i noted that need to adjust the escaping a bit for the xml).

**Comment by sjpadgett** [comment]
@bradymiller No reason to escape xml going to socket i.e most. I'd bet it will break xml to json in ccdaservice. Besides, browser doesn't see..

**Comment by bradymiller** [comment]
@sjpadgett , They are already being escaped (characters for <, >, &, ", ') via an awkward function call. I just plan to shorten/centralize it.

**Comment by sjpadgett** [comment]
okay. ill test afterwards
