### ISSUE TITLE
reopen a fee sheet without void checkout

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#4334]
### Describe the problem

can't reopen a fee sheet in an encounter after correcting a billing error without dealing with some scariness and forced entry of a reason

![Screenshot from 2021-04-09 11-27-39](https://user-images.githubusercontent.com/5618372/114208238-44180380-992b-11eb-9d47-857e2cc1fa26.png)

![Screenshot from 2021-04-09 11-27-49](https://user-images.githubusercontent.com/5618372/114208231-41b5a980-992b-11eb-8ce8-22a3ffc02d48.png)

### Describe the solution you'd like

have a global for handling whether this is necessary and investigate scary msg "payment info will need to be re-entered"

ps also lost the "Claim was reopened note" in billing manager when expand the encounter there so might need to look at `billing_report.php`

![Screenshot from 2021-04-09 17-16-00](https://user-images.githubusercontent.com/5618372/114241547-4c863380-9957-11eb-8a98-eca855e84a13.png)

**Comment by sunsetsystems** [comment]
Re-opening deletes payments and adjustments for the visit, so is a pretty significant thing to do. The reason/notes dialog could certainly be made optional.

Not sure what you mean about the billing manager note.

**Comment by stephenwaite** [comment]
hi @sunsetsystems , just updated issue with that png as well, it used to say Claim reopened in that detail

**Comment by sunsetsystems** [comment]
OK I think "Re-opened" in the billing manager refers to the case of a claim being re-opened for secondary insurance billing. Re-opening a visit from the Fee Sheet is a whole other ball of wax and is not about insurance claims.

Perhaps the button should not be displayed if there is an entry in the claims table for the visit?

**Comment by stephenwaite** [comment]
Re-open from the billing manager will allow you to go back to the encounter and edit the fee sheet and isn't specific to primary/secondary/tertiary ins.

Voiding checkout and re-opening a visit in the fee sheet also accomplishes same task but warns about payment deletion.

So the workflow issue is like this
1. a claim is denied and something in the fee sheet needs to be changed, instinct says go to fee sheet
2. uh oh it's closed for editing
3. i'll just reopen it here, not sure about void checkout though
4. uh oh it will del payment entries?
5. but there aren't any so will do it anyway
6. uh oh was there a copay? prob shouldn't have done that
7. oh well will make needed changes to the fee sheet now and it will appear unbilled in billing manager so successfully  re-queued, yay

vs

1. go to billing manager and find the one claim by entering some search criteria
2. selecting the one claim
3. reopening claim
4. go back to encounter
5. open fee sheet
6. make changes

**Comment by sunsetsystems** [comment]
Yep re-opening from the Fee Sheet zaps payments without updating the claims table, and it seems to be that way (including the message) in 5.0.2 as well. Basically this logic is not catering to US insurance claims. I think it should either be updated to do so, or to hide the button when there is a claims table entry for the visit. Your thoughts?

**Comment by stephenwaite** [comment]
thinking void checkout should be left to the fees->checkout where payment deletion makes sense and this should just be to reopen the fee sheet and if saved would update the claims table (if that's where the billing manager looks to see if a claim is "unbilled")

**Comment by stephenwaite** [comment]
bump

**Comment by stephenwaite** [comment]
![grimace](https://user-images.githubusercontent.com/5618372/136641358-2bac344f-61b9-45ea-adfa-ac6754734038.gif)
