### ISSUE TITLE
FHIR US Core Search Implementation

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4347]
The current FHIR US Core Search Implementation is not working correctly.  Search currently does just the union of values rather than explicit intersection which FHIR requires.  Only string values with limited token value support is working.  Search with conditionals and modifiers is also mostly missing with encounters being the only thing that does date searching and that is incorrect.

I'm currently building a new search algorithm for US Core Search with FHIR.  The attempt is to continue to follow our 3 tier layer approach.  With the FHIR layer sitting on top of the OpenEMR business service layer which sits on top of the SQL data layer. 

I've gone ahead and implemented string, date, and a limited version of token.  All of the FHIR modifiers for string are now supported as well as all of the date/datetime comparators (gt,lt, etc) except for aproximate which I don't think is a good thing we want in the system right now.  

The algorithm is built so that hopefully only minimal work will need to be done in each of the FHIR and business service classes to do searching is required.  I've gone ahead and heavily modified the FhirPatientServiceQueryTest to show the robustness of the types of data values that can be searched on.

**Comment by adunsulag** [comment]
I'm opening this issue so we can track and tie code to the problems with FHIR searching until we've completed all of the search requirements for FHIR and US Core.  

With my next pull request this should implement all of the US Core required search fields for the Patient resource.  The only thing I'm not entirely sure on and will play with as I go is the identifier FHIR field.  Currently values are searched indiscriminately across the OpenEMR data model **pubpid** and the **ss** field for this token value.  I'm not sure yet if that will be a potential problem.

**Comment by adunsulag** [comment]
Guess I got a little trigger happy.  I ran the full OpenEMR test suite and there's a number of unit tests to fix so I'll have to push this out tomorrow :)

**Comment by bradymiller** [comment]
![2DV (1)](https://user-images.githubusercontent.com/278968/115618224-42452d00-a2a7-11eb-91b0-ea3d93a3253f.gif)

**Comment by stephenwaite** [comment]
![thecoffeecup_agadeaadkp2afq](https://user-images.githubusercontent.com/5618372/115620071-b6d99500-a2c2-11eb-96ae-e427eaf60169.gif)

**Comment by adunsulag** [comment]
Patient search + Single Patient API implementation is now working:
![image](https://user-images.githubusercontent.com/228117/117199077-c32c1a80-adb7-11eb-82eb-3e85be20c9a9.png)

So we have about 80% of the search implementation now complete and we are spec compliant with the Patient endpoint.  

I am seeing a warning about our language abbreviation codes.  It states:
```'http://hl7.org/fhir/us/core/ValueSet/simple-language|eng' is not in the declared CodeSystem' ```

I'm not sure why this is throwing an error as this is the same codeset as CCDA is using.  We may adjust this based upon whatever work @sjpadgett does with his CCDA.

My next step is to move onto the AllergyIntolerance endpoint as that uses I believe both a number and a reference search field.  That should hopefully get us 95%+ done with the requirements we have for US Core search.

**Comment by bradymiller** [comment]
The beautiful array of green check marks...

![tenor (67)](https://user-images.githubusercontent.com/278968/117404896-9cf1a200-aebf-11eb-81e1-cf2161520e89.gif)
