### ISSUE TITLE
Backup broken on Windows Server 2019

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4363]
### Describe the bug
Kind of weird. 
Server 2019 running on a AWS machine. Backup quietly fails with openemr error message and configuration export fails where export is not complete.
Previously worked after I fixed for Windows in general in 5.0.2. Strangely works on my Windows 10 on current versions.
I've tried v6 release version and current master. Most likely escaping where WIndows 10 and server 2019 may differ in that regard.
Jesh! Who knows! Really, anyone know.:)

Anyone running 2019 server can you verify?

**Comment by sunsetsystems** [comment]
No errors logged? All I can imagine is either a php.ini setting, or database corruption.

**Comment by sunsetsystems** [comment]
Also be sure to look for logged errors in whatever place mysqldump would log them.

**Comment by sjpadgett** [comment]
I figured out the backup issue. Either the mysql account or file permissions.
Retesting masters version though i've found that the layouts export is broken again. The same issue I last fixed in v5.0.2 for windows.
I guess i'll take a look at that escaping again though this will be the third time i've fixed this issue with layout export....

**Comment by sunsetsystems** [comment]
I see what happened. I "simplified" the code having no idea that Windows requires double quotes instead of single around arguments. You might add a comment about that while you're in there.

**Comment by sjpadgett** [comment]
Yep, that's what I ran into in the past. Good idea on the note.  How about 
// touch this block and we'll send the escape police
Which would prob be Brady!:)

**Comment by sjpadgett** [comment]
lol, I fully expected that @stephenwaite would have found and posted a gif of an ole timey cop holding a baton by now!:)

Anyway, I've fixed , tested and will include in my ccda/bug PR which I plan to cherry pick back to patch 2 when merged.

**Comment by stephenwaite** [comment]
![external-content duckduckgo com](https://user-images.githubusercontent.com/5618372/116483941-18b37500-a856-11eb-88ea-ff733f3a6121.gif)

**Comment by sjpadgett** [comment]
about time!!!

**Comment by sjpadgett** [comment]
Still can't get to work on AWS windows server.
ERROR 1045 (28000): Access denied for user
Thinking security issue but works from a command prompt!

**Comment by sjpadgett** [comment]
This is most likely a OS configuration problem with the access denied so, will close this.....
Works fine for me on windows 10
