### ISSUE TITLE
Database create fails with utf8mb4

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4368]
### Describe the bug
v6.0.0 master install fails on drug_templates. MariaDB 10.1.17 Perhaps newer version works but doubtful. Remember for indexes I believe byte count is doubled. @bradymiller what am I missing?

![image](https://user-images.githubusercontent.com/1859985/116750245-27be3280-a9d0-11eb-84e5-f1f964b24b21.png)

**Comment by sunsetsystems** [comment]
selector surely doesn't need to be that big. But the easy solution may be something like:
PRIMARY KEY (`drug_id`, `selector`(30))

**Comment by bradymiller** [comment]
hi @sjpadgett , i think related to this issue:
https://github.com/openemr/openemr/issues/532
(combination of an old mysql/mariadb version that also disables the innodb_large_prefix setting)
(MariaDB 10.1 is not on list of supported versions for OpenEMR 6.0.0 since it's life was ended on 10/2020)

**Comment by bradymiller** [comment]
dang it, when i was checking 10.1's end of life, I also saw that 10.6 mariadb docker is out. Just alpha, but now i am compulsed to work 10.6 into the github actions and insane docker environment :)

**Comment by sjpadgett** [comment]
Okay, thanks Brady and Rod. Rod, you are correct. In the past(and currently) we seem to have a bad habit of using 255 for varchar regardless of content. Be nice if someone went through and tuned all our indexes.

@bradymiller I'm creating a testing database for ONC. I have to create at least four testing scenarios based on criteria given by testing facility for CCDA testing so, I thought i'd kill two birds here. I've spoken with @adunsulag and will give to him for additional needs for or use by FHIR testing.

**Comment by sjpadgett** [comment]
Closing as non issue based on my laziness to update or read doc's. Someone please fire me!

**Comment by adunsulag** [comment]
@sjpadgett When key sizes used to be required to be smaller you could set the primary key or a foreign key to be a subset of a varchar if it was needed. 255 chars is pretty large for a primary key as even a UUID4 in string form is only 32 characters.  Glad you got it figured it out.

**Comment by sjpadgett** [comment]
yep, after reading the thread Brady pointed out it seemed he and I went through this back in 2017. But for me, longer than a day ago,  I'm befuddled.:)

**Comment by bradymiller** [comment]
hi @sjpadgett ,

Sounds great on the testing database for ONC. I'm working on a way to support testing databases (and patient documents etc.) on the demo farm by leveraging the snapshot/capsule mechanism used in the development docker environment; so can then test the ONC database on a online demo.

Sorry, we can't afford to fire you permanently, but we can do it for a couple seconds:
Your fired
(...couple seconds later)
Your rehired :)

![tenor (63)](https://user-images.githubusercontent.com/278968/116803812-61299780-aacf-11eb-9500-faeb192525eb.gif)
