### ISSUE TITLE
Login screen white screen of death in older php version (specifically the online development demo).

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#437]
Demo is here: http://www.open-emr.org/wiki/index.php/Development_Demo#Daily_Build_Development_Demo

Demo is giving white screen of death at login screen with following error in log:
[20-Jan-2017 09:48:32 UTC] PHP Fatal error:  Can't use method return value in write context in /var/www/openemr/interface/globals.php on line 420

Here is the line:
``````
    if ( ($version->getRealPatch() != '0') && (!(empty($version->getRealPatch()))) ) {
``````

On my research, it appears that older php versions throw this error when include a function directly within an empty clause, which is super weird. Any thoughts on best way to fix this to keep the development demo going?

**Comment by bradymiller** [comment]
On the php documentation, found the following:
> Note:
> Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, > the following will not work: empty(trim($name)). Instead, use trim($name) == false.

**Comment by bradymiller** [comment]
Brought in fixes into the codebase to deal with the above issues (there were 2 places), so that code won't break completely with php 5.4 and lower.

However, then noted an error in the doctrine library that breaks php completely for php 5.3, which is what is used by the demos. Definitely, no clear reason to fix this since 5.3 is outdated and would be ok to enforce 5.4 (note Zend requires 5.3.3 and phpmyadmin, which is optional, requires 5.5). Instead will need to make it a high priority to upgrade the demo appliances to a modern ubuntu server :)

We also need to figure out what is the current minimum version of php with the new doctrine related code(note it brought in a lot of dependencies also). @MatthewVita , was wondering if you had any ideas on this?

**Comment by bradymiller** [comment]
as an aside (more of a reminder for myself), if we end up requiring php version > 5.5, then I'll revert the code changes I made to make compatible with 5.4:
https://github.com/openemr/openemr/commit/d33f40c3b6cd1d50718f4e9ad2b3781375bbb86f
https://github.com/openemr/openemr/commit/ee1836638d4f01343c29a60425797a8088be2061

**Comment by MatthewVita** [comment]
I'm thinking that it is okay to enforce php version > 5.5. We can add a check for it and show an error to the user.

...speaking of minimum version support, I don't think OpenEMR has browser detection/feature detection checking. If this is useful (because we only support modern firefox and modern chrome to my understanding) we can introduce these checks in as well. Modernizr is great. Old school user agent sniffing libraries are great too.

**Comment by bradymiller** [comment]
Agreed on this and would be good to have a block of code to check php version and throw error if too low (would go in setup.php, sql upgrade script, sql patch script, acl upgrade script, admin.php, and globals.php scripts).

Just trying to figure out where we are in terms of absolute php minimum requirement after the addition of the orm stuff. It looks like doctrine/orm officially requires php 5.4 via it's composer entry, however, the symfony dependencies appear to require 5.5.9. Is your code using the symfony dependencies at all?

**Comment by MatthewVita** [comment]
> however, the symfony dependencies appear to require 5.5.9. Is your code using the symfony dependencies at all

Nope.

Please review https://github.com/openemr/openemr/pull/443 :)

**Comment by bradymiller** [comment]
Just brought in the code for this by @MatthewVita . Will confirm that the predicted error shows on the up for grabs demos and then will close this ticket after that.

**Comment by bradymiller** [comment]
Looks good on the development demo (php version there is 5.3.x, so it is showing the error). So, closing this ticket. thanks for the nice feature @MatthewVita !
