### ISSUE TITLE
Prescriptions not populating RXNORM code.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4373]
### Describe the bug
RXNORM codes are not being populated in prescription table from drug lookup. Web or drug table lookup.

Maybe in-house would work but couldn't get lookups to populate.

All SMARTY stuff so maybe someone will take a look or may know a trick to this.
We really should have option to lookup via rxcui! I though web lookup use to return rxnorm codes!

**Comment by stephenwaite** [comment]
![shocked_cat](https://user-images.githubusercontent.com/5618372/116877638-35500400-abec-11eb-83d1-9321563a563b.gif)

**Comment by stephenwaite** [comment]
should the dropdown for external list RxNorm?

![Screenshot from 2021-05-03 11-04-20](https://user-images.githubusercontent.com/5618372/116893751-52da9900-abff-11eb-9f51-4b71033ad123.png)

**Comment by sjpadgett** [comment]
Prescriptions come from
- Web search
- Drugs table
- Inventory
Selection from drug table only populates drug name best I can tell.
rxcui is only used for interactions lookup.

I could fix if I wanted to spend a couple days on but, ccda is making life hard especially every time I need something from core it's broken or non exist!

**Comment by sjpadgett** [comment]
Anyone know if Procedure Results ever populated result items from procedure configuration (compendium) or always had to manually enter for inhouse? If not, good grief why?:)

**Comment by stephenwaite** [comment]
`Procedures->Patient Results`?

**Comment by sjpadgett** [comment]
Yes I know however, it doesn't populate result items and codes from procedure configuration to manually enter results. Appears one has to enter the loinc code manually for each procedure.
Electronic results does this from the result hl7.

**Comment by sjpadgett** [comment]
I have to have rxnorm(FHIR and CCDA) so I guess i'll fix prescriptions. @stephenwaite Do you know if the drugs table was originally intended for prescriptions or inventory?
@bradymiller I wonder if worthwhile adding a rxcui lookup if available.

**Comment by stephenwaite** [comment]
not sure, am poking around in the smarty classes, for the nlm lookup it just isn't returning the [rxcui even though it's found ](https://github.com/openemr/openemr/blob/master/library/classes/RXList.class.php#L85)

**Comment by sjpadgett** [comment]
Check if interactions global in turned on!

**Comment by stephenwaite** [comment]
it was, don't think it matters here, it's just going to scrape that place, just have to spell out the whole search word, like aspirin

**Comment by stephenwaite** [comment]
basically it's not getting added to the return list array i think

**Comment by sunsetsystems** [comment]
> Anyone know if Procedure Results ever populated result items from procedure configuration (compendium) or always had to manually enter for inhouse? If not, good grief why?:)

In Procedure Configuration you can enter Discrete Result items under Order items, and that is supposed to give you corresponding entries when entering manual results.

**Comment by sunsetsystems** [comment]
> I have to have rxnorm(FHIR and CCDA) so I guess i'll fix prescriptions. @stephenwaite Do you know if the drugs table was originally intended for prescriptions or inventory?
> @bradymiller I wonder if worthwhile adding a rxcui lookup if available.

The drugs table was created to support the inventory system.

**Comment by sjpadgett** [comment]
Okay so where are we supposed to have drug lookups and stay out of the inventory module? Besides web lookup...

**Comment by sjpadgett** [comment]
I think we have some broken sql's!

**Comment by stephenwaite** [comment]
![squirrel](https://user-images.githubusercontent.com/5618372/116940908-a9b29380-ac3c-11eb-9088-3ad20939ff77.gif)

**Comment by sunsetsystems** [comment]
I think prescriptions needs a rewrite, to encompass immunizations as well.

**Comment by stephenwaite** [comment]
but they've always been separate widgets and aren't they disparate enough to coexist with some shared properties?

**Comment by sunsetsystems** [comment]
Visually separate is fine, but internally they have much in common including the need to integrate with inventory.

**Comment by sjpadgett** [comment]
> Visually separate is fine, but internally they have much in common including the need to integrate with inventory.

We talk about this some on sat call couple weeks back. My thought was immunizations would be the vaccine order/history and inventory would dispense at time of use. Therefore no need to do any inventory from immunization form.

**Comment by mdsupport** [comment]
Has anyone tried openFDA [drug endpoint](https://open.fda.gov/apis/drug/)? They are unified, realtime source for drugs, devices and more. A standard practice would want to deal with FDA approved drugs rather than nih or rxnorm. As a bonus drug events can be included in drug selection as well.

**Comment by bradymiller** [comment]
As I recall, the prescription rxcui codes came from either zh or newcrop or weno (@juggernautsei , does weno stuff do anything for rxcui codes) stuff and I don't think that there is a way to populate it in the prescription. For the Medications (in Issues), can populate it via the Coding selector there (if have imported the RXCUI internal code set). Some discussion sort of related to this is here: https://github.com/openemr/openemr/issues/2917

**Comment by juggernautsei** [comment]
@bradymiller ZH brought in the rxnorms. Weno no longer needs them since it is now using the iframe and the prescription is made on their site and not in the EHR. I thought the Rxnorms were brought in to support MU reporting.

**Comment by sjpadgett** [comment]
I truly appreciate everyone's input. My problem is not having access to the rxnorm codes(native and external avail) but instead the codes are not populating the prescription table on drug selection and save. The only drug source that will do this is from inventory drug selection.

The other two options are web search and drug table lookup. With these only the drug name is used.
I'd be nice if we could use the Medication list however it doesn't maintain usage details like instruction, quantity etc. I can't nullflavor these for ONC scenario testing.

From what I understand and what @mdsupport pointed out is that most practices prefer to not use rxcui for drug lookup and find something like FDA preferable.

While I could for ONC testing purposes, set the drug table up where I can trust the name for a back end lookup but, too me it's a hack and logical solution is to record the code in prescriptions.

I just don't have time to rewrite module as is needed and guess i'll need to fix in the smarty workflow and yuck....

**Comment by stephenwaite** [comment]
want me to take a stab at the smarty scrape from nlm? don't leave your study :)

![batphone](https://user-images.githubusercontent.com/5618372/117006960-0e123900-acb7-11eb-9ffb-a2290826e29a.gif)

**Comment by juggernautsei** [comment]
@stephenwaite what would the scraping produce?

**Comment by stephenwaite** [comment]
the ndc is in there just not getting added to the list array for insert into the `prescriptions` table

**Comment by sjpadgett** [comment]
Better to just populate rxnorm code from the drugs table lookup which is default. Prob need to do it on form submit based on drug table id.

**Comment by stephenwaite** [comment]
ok @sjpadgett, where do you see this default setting?

**Comment by sjpadgett** [comment]
It appears to be inherit to use drugs table if in house global is not set.
Prob in general_lookup template. I got lost tracking where the submit happens back to controller.
If you want to do the web search that'd be fine but really both should be done...

**Comment by stephenwaite** [comment]
the native install puts them in `codes`
the external install creates and puts them in these tables:
![Screenshot from 2021-05-04 13-21-56](https://user-images.githubusercontent.com/5618372/117043849-bd610700-acdb-11eb-9583-11a9fd8160e1.png)

**Comment by stephenwaite** [comment]
medications adds rxcui to lists from the native data load options from the codes table

**Comment by sjpadgett** [comment]
> to encompass immunizations as well.

Hi @sunsetsystems I don't understand how we'd need to support immunizations. Can you give me a clue while i'm messing around medications/prescriptions?

**Comment by sunsetsystems** [comment]
@sjpadgett You don't *need* to support immunizations, it's just that both concern the dispensing of drugs and possible depletion of inventory. Internally they seem very similar.

**Comment by sjpadgett** [comment]
I have the scraping parse reconfig'ed i'll send you shortly...

**Comment by stephenwaite** [comment]
![Uploading signal-2021-05-13-141944.gif…]()

**Comment by sjpadgett** [comment]
![image](https://user-images.githubusercontent.com/1859985/118400482-ce8d0a80-b62f-11eb-8167-72bd587435e0.png)

**Comment by sjpadgett** [comment]
I think I'll add a button to select drug from RxCUI if the codes are installed.
![image](https://user-images.githubusercontent.com/1859985/118407274-115ddb00-b64e-11eb-9a32-6e3238fb87c9.png)

Thoughts?

**Comment by bradymiller** [comment]
agreed

![image](https://user-images.githubusercontent.com/278968/118409054-7957f580-b63d-11eb-9ba9-e730e2e6409a.png)
