### ISSUE TITLE
How to conect OpenEMR to Orthanc?

### ISSUE THREAD

**Issue by mariagonz04** [openemr/openemr#4379]
Hi, I don´t know how to conect OpenEMR to Orthanc , so could someone who knows it help me? Thanks.

**Comment by thousifa1** [comment]
@mariagonz04 I would like to start my contribution journey to openEMR with this. I am a SWE with experience of 5 years.
can you please elaborate on the requirement about what do you mean by "Connect"?
For Ex : what is the API do you want to access in Orthanc? etc.

**Comment by bradymiller** [comment]
hi @thousifameerkhan ,
Welcome to the project!
Check out this thread for more details on this:
https://community.open-emr.org/t/project-pacs-server-integration/13706

**Comment by stephenwaite** [comment]
bump
