### ISSUE TITLE
Password is not obscured when resetting user password

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#4380]
OpenEMR 6.0.0 Patch 1
OpenEMR 5.0.2 Patch 3

When resetting a user password, "User`s New Password" is not obscured in the way that it is for "*Your Password*". The password is successfully obscured when creating a new user, this is only an issue when resetting a user's password.

**Comment by stephenwaite** [comment]
hi @pete-boyd , easy fix to obscure it by changing the [input type to password](https://github.com/openemr/openemr/blob/master/interface/usergroup/user_admin.php#L265-L279)

**Comment by sunsetsystems** [comment]
For what it's worth, I like password fields where you have an option to click something to view the password. Handy when you're by yourself and want to make sure you typed it in correctly.

**Comment by tywrenn** [comment]
There are 3rd party tools that allow you to have a hide/show password button. For the sake of security I would highly recommend researching those tools rather than leaving that area as permanently revealed as it can pose as a vulnerability.

**Comment by richcow2018** [comment]
no need 3rd party tools. A small JS can make it work. You can refer the modified code from my pull request.
