### ISSUE TITLE
FHIR R4 Create/Update/Delete Resources

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4393]
For ONC certification we are exclusively focusing on resource read operations (read/vread/search) and not on any of the update, create, or delete operations except where required by ONC 2015 certification.  This feature request is for anyone who wishes to go through and add those API endpoints can do some.  There are some resources that have some initial work done here (such as in Patient) but they are out of date as they currently don't support things like race and ethnicity to be specified.

Anyone who wants to can work on these resources endpoints.

**Comment by sjpadgett** [comment]
bumpety bump
