### ISSUE TITLE
Reorganize Portal using Twig

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4402]
### Describe the solution you'd like
Helps improve responsiveness small devices, mobile etc..

**Comment by sjpadgett** [comment]
Hi @benmarte ya can track your progress here or if any questions please ask.
Thanks

**Comment by benmarte** [comment]
Any idea why making changes to the Help.tpl file does not reflect my changes even after doing docker-compose down/up? I'm trying to make another branch with individual portal page fixes but running into this particular issue.

Thanks.

**Comment by sjpadgett** [comment]
Hi @benmarte 
I'm guessing it's because the template resides in the sites directory: sites/default/documents/onsite_portal_documents/templates/Help.tpl
Does docker see changes in that directory?

**Comment by stephenwaite** [comment]
right on @sjpadgett , easy docker ignores it

**Comment by benmarte** [comment]
Docker mounts the whole openemr directory as a volume AFAIK so it should not ignore it but I will take a look to ensure this is the case.

Thanks.

**Comment by bradymiller** [comment]
The easy docker dev environment uses black docker magic to not mangle the main git repository by basically dislocating some of the directories from reality (thus changes in the git repo will not actually get to the docker; the positive to that is that changes in the docker (ie. things that are added/modified while running openemr) do not get into the git repo). These are the directories that are positively (or negatively :) ) affected:
https://github.com/openemr/openemr/blob/master/docker/development-easy/docker-compose.yml#L25-L29

Actually, we can now point the /var/www/localhost/htdocs/openemr/ccdaservice to /node_modules now that the package lock file is in there, so can actually edit/test files there in the easy dev docker (this was the one directory that could not get true edit/test support). Will add that to following issue and get that done soon (this issue also gives an explanation of these environment limitations): 
https://github.com/openemr/openemr/issues/2899
