### ISSUE TITLE
Improve lookup_code_descriptions speed for SNOMED codes

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4403]
The lookup_code_description() function when dealing with SNOMED codes is very slow.  Queries (when cached) were taking a full second to do a lookup even if the result was negative, and 3.5 seconds when the query cache was empty.  As you can imagine running through dozens of code lookups in our unit tests or working with a large result set of FHIR resources slows the response times down to a crawl.

My suggestion is adding the following index to the sct2_description table. I know these tables are imported so I know this will slightly slow down the import process but the actual system execution should be a ton faster.  I'm thinking of adding this to the SQL upgrade table but I wanted to check with people (@sjpadgett @bradymiller, others?) on what the downsides if any of doing this would be.  Also I'm not familiar with any of the other lookup tables but they could probably appreciate some db table indexes as well.

CREATE INDEX sct2_desc_conceptId ON sct2_description(conceptId);

Adding this index drops my cached query resultset from 850ms down to 1ms on this table. The number of records examined drop from 1703934 to 1-2 records in the index.

This probably will also speed up ccda imports and anywhere else having to do lookup codes for descriptions by a lot.

**Comment by sunsetsystems** [comment]
Sounds like a great idea. I have added indexes as needed from time to time.

**Comment by bradymiller** [comment]
@adunsulag ,
Agreed on adding index. In addition to adding to the sql upgrade script, also rec adding to initial table creation in library/standard_tables_capture.inc. Would prob just label the index the name of the column (it's what we generally do in the database schema).

**Comment by sjpadgett** [comment]
did we ever do this?
