### ISSUE TITLE
Add care team status field to pass FHIR ONC CareTeam Status requirements

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4405]
CareTeam needs to have more than one status supported to be ONC compliant.  Currently we don't have a way of specifying status for a careteam and we've been assigning to be active.  However, this fails the ONC validator requires searching on at least two status's for the test case to pass.

We can see that ONC's inferno tool is checking for more than one status here:
![image](https://user-images.githubusercontent.com/228117/118873360-a9123200-b8b7-11eb-8969-e2e14328014f.png)

And our entire CareTeam status is marked as skipped because of this criteria
![image](https://user-images.githubusercontent.com/228117/118873285-913aae00-b8b7-11eb-96fb-ced2c70033e8.png)

The easiest option might be to add a CareTeam Status dropdown in the Patient's Choices screen that we could provide the status of the care team.
![image](https://user-images.githubusercontent.com/228117/118873719-132ad700-b8b8-11eb-83c9-db9e65422d44.png)

Possible statii are **proposed | active | suspended | inactive | entered-in-error** 

As far as where the data lives it could be another column in patient_data which would be the most backwards compatible, or we could extract the 3 care team columns into it's own table.  Long term this would seem to be the best outcome as we could then add over time a care team start / end date and other kinds of fields that the CareTeam resource cares about without cluttering up the patient_data table.

**Comment by bradymiller** [comment]
@adunsulag , so is inferno looking through all careteam resources to find more than one status then and then using this to test the multipleor search mechanism?
If that is case, would prob just make a Care Team Active toggle in patient_data layout (it would go before the selectors for Care Team (Provider) and Care Team (Facility)).
Agree it is a bit ugly, but it will get the job done :)

**Comment by adunsulag** [comment]
@bradymiller What are your thoughts on sticking that status flag in patient_data? One more column, quick and dirty, but care plan stuff in my view really should be extracted into its own table.  Maybe we can add the column for now and then put a github issue to extract it into its own table for anyone that wants to take it on.

**Comment by mdsupport** [comment]
[CareTeam FHIR structure](https://www.hl7.org/fhir/careteam.html) almost requires separate table(s). Since we are starting from scratch, it will be lot easier for future FHIR requirements to replicate the hl7 layout. It takes care of  many linkages that would be beneficial in future - e.g. careplan to providers/users, issues, messages, documents etc.. There is existing gprelations structure as a catchall but it gets confusing.  Maybe `plan ->> team ->> resource`?

**Comment by bradymiller** [comment]
note US core fhir is much more simple than full fhir:
http://hl7.org/fhir/us/core/stu1/StructureDefinition-us-core-careteam.html

I'd rec just adding the status column to patient_data for now to keep moving forward. Agree that in future will need a better data model and gui for this functionality, but not needed for MU3 :)
(agree on making it an issue to expand it; this is something that will be needed for future inpatient support)

**Comment by sjpadgett** [comment]
Care teams would make better sense if we had ACL to restrict major chart actions to care team members.
In reality, anyone who works with patient is the care team I guess!

**Comment by adunsulag** [comment]
We added the column.  Not my preference but it moved things forward.
