### ISSUE TITLE
Patient ID Missing

### ISSUE THREAD

**Issue by mosmartin** [openemr/openemr#4417]
### Describe the bug

The Patient ID is not displaying in the drop down menu.

### To Reproduce
Messages Tab -> Message Center -> Ad new -> Click to add patient

![image](https://user-images.githubusercontent.com/10962699/119529215-2fc88280-bd82-11eb-88d2-01c8057b26e4.png)

1. login
2. Click on Messages tab
3. Add New
4. Click to add patient
5. See error

### Expected behavior

Patient IDs should be visible

### Client configuration

- Browser: Google Chrome Version 90.0.4430.212 (Official Build) (x86_64)
- OpenEMR version: v6.0.0 (1)
- Operating system: macOS Big Sur v11.4

**Comment by stephenwaite** [comment]
hi @mosmartin , can't reproduce on the [demo](https://eight.openemr.io/c/openemr/interface/login/login.php?site=default)

![Screenshot from 2021-05-25 13-01-37](https://user-images.githubusercontent.com/5618372/119538782-72c23000-bd59-11eb-90e8-2c1d71d5b7a6.png)

**Comment by mosmartin** [comment]
Interesting... thanks @stephenwaite. Let me test on another browser.
