### ISSUE TITLE
Planning patch 2 for 6.0.0

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#4418]
Hi,
Planning to hopefully get patch 2 for 6.0.0 out over this weekend. Just making sure I don't need to wait on anything. If so, just let me know.
-brady

**Comment by stephenwaite** [comment]
maybe just 1 or 2 more billing fixes :) like #4421

**Comment by sunsetsystems** [comment]
#4435 would be good.

**Comment by bradymiller** [comment]
Planning to hopefully get patch out this weekend.
Delaying until get this PR in: https://github.com/openemr/openemr/pull/4461
Just let me know if need to wait for other work/PRs.

**Comment by bradymiller** [comment]
Pulling trigger on patch :)
Hopefully get it out by tomorrow or Wednesday.

**Comment by stephenwaite** [comment]
![chores](https://user-images.githubusercontent.com/5618372/122038193-58510480-cda3-11eb-80b8-3fbf16b8d7fb.gif)

**Comment by bradymiller** [comment]
list of planned fixed/improvements (now in process of creating and testing patch):
* Security fix (reported by Hagai Wechsler at https://www.whitesourcesoftware.com, fix by Brady Miller)
* WENO Exchange ePrescribing fixes (fixes by Sherwin Gaddis)
* Session and timeout fixes (fixes by Rod Roark, Stephen Waite, Jerry Padgett and Brady Miller)
* Patient portal improvements (by Jerry Padgett)
* Eye form fixes (fixes by Ray Magauran)
* Billing fixes (fixes by Stephen Waite)
* New GAD-7 form (by Ruth Moulton)
* Layout Based Form fix (fix by Rod Roark)
* Backup fixes (fixes by Rod Roark)
* Demographics fix (fix by Ken Chapple)
* Messaging improvement (by Stephen Waite)
* PHP 8 fixes (fixes by Stephen Waite)
* MySQL 8 fix (fix by Rod Roark)

**Comment by stephenwaite** [comment]
![excited_elephant](https://user-images.githubusercontent.com/5618372/122202035-a1b85700-ce6a-11eb-8b78-1a1856e7ba2d.gif)
