### ISSUE TITLE
"Site ID is missing from session data!" gives no clue to users as to what the situation is

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#4426]
If a session has expired, and a user goes to the site they will tend to see simply the text "Site ID is missing from session data!" and nothing else whatsoever on the screen. There's no option for them to click on anything to be taken to the login screen. I think that at the very least there should be a link for this. At best, users would be taken to the login page. As it is, users are confused by this very technical message and by the situation, and have to know to trim the URL to just the TLD in the location bar, or select the site from a bookmark, etc.

OpenEMR 6

**Comment by tywrenn** [comment]
lol I created this exact same issue request a year ago and nothing came of it -- this undoubtedly needs to be fixed. I did create a few PRs in the past with a way to do such a thing but they never got off the ground.

**Comment by sunsetsystems** [comment]
There are a couple of things wrong with the related code.
1. library/auth.inc is closing the session on a timeout even when called by the hidden iframe (interface/main/tabs/timeout_iframe.php) whose purpose is to support timeout checking. Thus when the user makes their next request the session is already closed and timeout cannot be detected.
2. Excessive server requests are being performed in the background. In particular library/ajax/execute_background_services.php and library/ajax/dated_reminders_counter.php are being invoked every minute, even after the session has timed out. These should probably be called from timeout_iframe.php instead.

I'll look into a fix for (1) at least.

**Comment by sunsetsystems** [comment]
Actually it looks like timeout_iframe.php can go away, and the ajax scripts are the remaining culprits. I'll put up a PR when time permits, in the next day or 2.
