### ISSUE TITLE
Session timeout should force immediate logout

### ISSUE THREAD

**Issue by sunsetsystems** [openemr/openemr#4438]
### Describe the problem

Wasn't sure whether to call this a feature request, bug or security vulnerability. When someone walks away from the computer their session will eventually time out, however whatever was on the screen remains visible until some action is taken. If that was sensitive information there's a problem.

### Describe the solution you'd like

My suggestion is that library/ajax/execute_background_services.php should notice when the user's session expires, and pass back a status code indicating such. The caller than can force a logout.

Even better, would be good to see a prominent notice (bright red?) somewhere at the top of the page when the session is close to expiring.

**Comment by bradymiller** [comment]
Good point and am pretty sure that the timeout frame previously did this (if there was a timeout, then it would automatically go to the login screen without any user input). Prob need to hold up patch 2 until this is fixed since placed those changes in rel-600 :)

**Comment by bradymiller** [comment]
btw, using background services would be a nice place for this since it runs every 60 seconds.

**Comment by bradymiller** [comment]
Let me know if you plan to work on this. Otherwise I may take a stab at it in near future.

**Comment by sunsetsystems** [comment]
As best I can tell the timeout frame that I recently removed didn't do anything useful at all. Long ago its purpose was to put indicators on the screen about new faxes and patient notes. Don't remember any code to force a logout.

**Comment by sunsetsystems** [comment]
Not sure how soon I can work on it, so just post here if you get to it first.

**Comment by bradymiller** [comment]
put a PR for this here:
https://github.com/openemr/openemr/pull/4439
