### ISSUE TITLE
Onsite Portal White Page of Death

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#444]
I am in the latest development version of openemr 5.0.1 on windows 10. Tried to log in with a patient ID and password into the onsite patient portal and it gives me a complete white page on the next screen. Searched for the error log in php - 

[24-Jan-2017 11:10:13 Asia/Kolkata] PHP Fatal error:  Call to undefined function sqlQuery() in C:\xampp\htdocs\openemr\library\translation.inc.php on line 242

kindly see to it please

**Comment by bradymiller** [comment]
Guessing this has to do with composer autoloader enhancements that were recently added. Will try to fix this in the current portal. This will be definitely be addressed by the new patient portal that will be in the codebase soon.

**Comment by arnabnaha** [comment]
Thanks Brady

**Comment by bradymiller** [comment]
Here is a proposed fix. Am pretty confident it will work(it's working on the new patient portal that is under development), but I will test it in the current portal before bringing the fix into the codebase.
https://github.com/openemr/openemr/pull/447

**Comment by bradymiller** [comment]
Above fix worked, so just brought it into the codebase. The patient portal should work now.
