### ISSUE TITLE
Open EMR Lab and pharmacy operation capabilities

### ISSUE THREAD

**Issue by niladrishekhar** [openemr/openemr#4448]
Hi, Like many am new to OpenEMR, struggling learning and using (supper happy  with the performance of Open EMR) - I need some clarity from the awesome community before I invest too much time (sorry for taking a short cut)
1. Can OpenEMR handle pharmacy ? I mean the doctor prescribes a few medicines - the patient takes it to the pharmacy, the pharmacist fills the order bills the patient - the entire cycle can we handle it via OpenEMR ?
2. Labs (blood test or imaging) - the doctor asks for a test - the patient goes to the lab - a test is done - the report is uploaded and the doctor can check it - the patient can go and collect the reports later - this entire cycle can this be handled in OpenEMR?
Is there a tutorial on cycles in OpenEMR ?
Many thanks in Advance

**Comment by stephenwaite** [comment]
hi @niladrishekhar, thank you and welcome. You'll probably get more detailed help in the forum.
1. Please see the [Add prescription to the encounter form](https://www.open-emr.org/wiki/index.php/Pharmacy_Dispensary_Module)
2. Please see [procedure configuration](https://www.open-emr.org/wiki/index.php/Procedure_configuration_%26_order_process)
