### ISSUE TITLE
Unexpected text in clinical report

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#4449]
OpenEMR 6.0.0 Patch 1

Reports > Clients > Clinical

When Option: Medical History is selected, all search results include the following text:
"active,category,type,plural,singular,abbreviation,style,force_show,ordering,aco_spec"

I get only 3 search results out of hundreds of patients.

**Comment by sunsetsystems** [comment]
Weird, those are the column names for the issue_types table.

**Comment by stephenwaite** [comment]
hi @pete-boyd, medical history is only looking in the `history_data` table and is focusing on just a few fields there currently. This is the data you can enter from the history tab in the dashboard, last commit in #4291 will suppress that strange result.
