### ISSUE TITLE
Referring provider not present in X12

### ISSUE THREAD

**Issue by msahasrabuddhe** [openemr/openemr#445]
In OpenEMR 4.2.2 (as well as the earlier 4.2.0 from which we upgraded), when we try to generate an X12 file for an encounter, the X12 file does not contain the Referring Provider added in the patient's demographics. As a result, MediCare is rejecting our claims (although for some reason, OfficeAlly does not intercept the issue).

Can anyone know what to fix? I checked the gen_x12_837.inc.php file, and the code for adding the referring provider seems to be right.

**Comment by stephenwaite** [comment]
this demo is producing the ref prov in the X12:
http://demo.open-emr.org:2102/openemr/interface/login/login_frame.php?site=default

they wouldn't happen to be rejecting the claim due to a missing npi?

**Comment by msahasrabuddhe** [comment]
This was indeed an issue of incorrect NPI. Thanks for the hint.
