### ISSUE TITLE
EasyUI

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#4453]
ZH implementation of zend modules feature brought in EasyUI component which is remarkably similar to jqUI. However unlike jqUI, their [freeware license terms](https://www.jeasyui.com/license_freeware.php) are not industry standard and unclear about use by for-profit clinics. [Commercial license](https://www.jeasyui.com/contact.php) is $449.

Apologies if this has been considered before.

**Comment by bradymiller** [comment]
According to the header, it lists either licensed as GPL or commercial.

https://github.com/openemr/openemr/blob/6552c4e897986417584491e994e77293ff4b3ab2/interface/modules/zend_modules/public/js/lib/jquery.easyui.min.js#L1-L9

**Comment by bradymiller** [comment]
here's the license on their new versions:
```
 * EasyUI for jQuery 1.9.15
 * 
 * Copyright (c) 2009-2021 www.jeasyui.com. All rights reserved.
 *
 * Licensed under the freeware license: http://www.jeasyui.com/license_freeware.php
 * To use it on other terms please contact us: info@jeasyui.com
 *
```

My take here is that in the old version 1.3.2 that we are using, if you state it is licensed under GPL (even with an or which means the software that uses should get to decide), then it is GPL. Unless I am missing something.

**Comment by mdsupport** [comment]
Clarifying the issue for unsuspecting developers - Like Fancybox switch between v1 and v2, this component can no longer be kept current.
