### ISSUE TITLE
Symfony EventDispatcher user deprecation

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4458]
### Describe the bug
Since v4.3, project creates an user_deprecated error in dispatch method for argument order i.e they flipped the event name and event object. I assume this came about because the Event class has been deprecated too. So here's the kicker
: instead of maintaining the existing method call and propagating the argument order through new workflow they decide to force all their users to refactor projects to make their lives easier.
Again, I caution us from updating existing dependencies unless fully aware of implementation ramifications. Still in this case, how could one foresee an issue especially since this comes from a non major Symfony release.

A look at offending code will give a better clue of potential problems it can cause. Note the call is handled in a way to swap args to complete call so, no harm to the progress of the event.
```
if (\is_object($event)) {
            $eventName = $eventName ?? \get_class($event);
        } elseif (\is_string($event) && (null === $eventName || $eventName instanceof ContractsEvent || $eventName instanceof Event)) {
            @trigger_error(sprintf('Calling the "%s::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead.', EventDispatcherInterface::class), \E_USER_DEPRECATED);
            $swap = $event;
            $event = $eventName ?? new Event();
            $eventName = $swap;
        } else {
            throw new \TypeError(sprintf('Argument 1 passed to "%s::dispatch()" must be an object, "%s" given.', EventDispatcherInterface::class, \is_object($event) ? \get_class($event) : \gettype($event)));
        }
```
Now as we always trigger error and though error is suppressed, appears a try/catch occasionally will rear its ugly and confusing nastiness.

 Possible Solutions:
- Force users to add `~E_USER_DEPRECATED` to php.ini error reporting.(I think I recm'ed this at one point and am unclear if we did add to documentation)
- Refactor our dispatch event calls.
- Possible interference by a portal class!
### To Reproduce
Already did that!:)

**Comment by bradymiller** [comment]
We should refactor the dispatch calls (goal is to deal with all warnings, especially deprecated warnings, since it could bite us in the end when it causes fatal error in the future); plus gotta get ready for symfony 5.4 (will be their next LTS version) in the future when it comes out :)

**Comment by stephenwaite** [comment]
![sneak-bite](https://user-images.githubusercontent.com/5618372/121401073-506a0e00-c926-11eb-9769-cf331debe560.gif)

**Comment by stephenwaite** [comment]
![Screenshot from 2021-06-09 13-36-06](https://user-images.githubusercontent.com/5618372/121402264-aa1f0800-c927-11eb-96c7-d7628d9419a7.png)

**Comment by sjpadgett** [comment]
lol, I guess the bird is making a statement or two like: "Dog you deserve a nip for wearing that sweater so proudly!" or "I told all the other birds I could do it!".  Then picture a group of birds in background passing a dollar to each other to satisfy their bets!
Sorry, can't help myself. Too many jokes. Thanks for that giggle Stephen however, E_DEPRECATED is different error type than E_USER_DEPRECATED and won't catch our issue if that is what you were pointing out. Though we should add for future.

**Comment by sjpadgett** [comment]
@bradymiller I think for now i'll do a temporary fix in globals by turning off the user_deprecated reporting for patch 2.
I don't think you or I want to do a refactor just now! An assumption begging for a response!:)

`error_reporting(error_reporting() & ~E_USER_DEPRECATED & ~E_USER_WARNING);`

**Comment by sjpadgett** [comment]
see: https://github.com/openemr/openemr/pull/4459

**Comment by sjpadgett** [comment]
will leave open as reminder.
