### ISSUE TITLE
Audit Logging of Merge Tool

### ISSUE THREAD

**Issue by kchapple** [openemr/openemr#4469]
### Describe the problem

The merge tool doesn't get used often, but when it does, we want to know who used it and what patients were involved with the merge.

### Describe the solution you'd like

I would like to implement audit logging of the merge tool actions.

I'm looking for feedback on:

- Where should log screen live? (should it be a type in the audit log, a new screen on the system log panel, or something that can be accessed from the merge tool?)
- What data should be logged? 
- Any other ideas? (store JSON representation of merge so it can be undone, ...)

**Comment by sunsetsystems** [comment]
The SQL updates performed would be logged, unless disabled, but an additional logged event for the merge as a whole would be good. A new type in the existing audit log seems logical. "Undo" is generally not supported in OpenEMR, but it would be nice to have a tool to import a patient from a backup or other site.

**Comment by kchapple** [comment]
Thanks for the feedback!

I wonder, since the logging occurs in the sql wrapper functions, and there’s currently no way to know where the sql function originated, that we should add some kind of “context” or “options” parameter to the sql wrapper so the logging system can know that the query originated from a merge. 

Or maybe it would be easier and make more sense if we can just add logging directly in the merge tool.

**Comment by sunsetsystems** [comment]
I would just log a "patient merge" event from the merge tool. That would be good for searching, and the related SQL update events can be recognized from having the same timestamp and user. But maybe I'm just lazy. :)

**Comment by kchapple** [comment]
This particular use case has 50+ users and a TON of insert and update queries (more than typical) so we want to be able to search for merge events in order to figure out the user that did the merge.

**Comment by kchapple** [comment]
I think we’re on the same page.
