### ISSUE TITLE
Clicking "Completed" on a message in patient dashboard is broken

### ISSUE THREAD

**Issue by kchapple** [openemr/openemr#4481]
### Describe the bug

There is a "Completed" button next to messages in the patient dashboard. Clicking it does nothing. No errors in console.

### To Reproduce
1. Log into demo.
2. Create a new message to yourself regarding a patient.
3. Click "send"
4. Browse to the patient regarding whom you just sent message.
5. Open Messages section and click "Complete"

<img width="1431" alt="Screen Shot 2021-06-25 at 10 47 31 AM" src="https://user-images.githubusercontent.com/271809/123442762-37f32800-d5a3-11eb-9938-b757ad2e8b60.png">

### Expected behavior

Message should disappear (marked inactive)

### Client configuration

- Browser: Chrome
- OpenEMR version: 6.0.0 Patch 2
- Operating system: Mac Big Sur

**Comment by sjpadgett** [comment]
click event is not being attached. prob need to move the event function.

**Comment by sjpadgett** [comment]
fixed in my next PR
![image](https://user-images.githubusercontent.com/1859985/123518651-df8c5b00-d674-11eb-9996-14bdcca845c2.png)

This bug is concerning. How many other events are we missing due to the way we load these fragments and/or widgets? i.e DOM is already init'ed.

**Comment by kchapple** [comment]
The patient dashboard (holistic view we like to call it) would be an excellent candidate to write a front end JS app that pulls data fell the internal rest api. I’d love to take that on, but wouldn’t be able to get to it for a while.

**Comment by sjpadgett** [comment]
> I’d love to take that on, but wouldn’t be able to get to it for a while.

lol, wish granted brother!
