### ISSUE TITLE
Failures running with PHP8

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4482]
### Describe the bug
Brady has spent hours going through core code and has identified and fixed many PHP8 requirements(thank you Brady!) however, we still are not PHP8 stable.
Currently CCM module is very broken and I see many other errors doing normal workflows.
Everyone should have PHP8 as their development environment and be testing, reporting and fixing PHP8 errors.

I look to vendors to jump in and help with this. Seriously guys, please help out so we can get ONC/MU3 done and a clean application.

**Comment by sjpadgett** [comment]
I'm still aggravated with PHP8 project. One of the better features of an interpreted scripting language is loose typing. Don't know how they got it in their heads to suddenly have early loose typing then enforce strong typing later in variables life forcing everyone to have to mostly type cast to correct type on refactors. Okay, I feel better ranting that.:)

@bradymiller Ran across the` Unsupported operand types: string + int`(edit_list) and after a quick search seems we have several places left to do. 
So folks, keep an eye out for the convenient + 0 trick to set typing.

**Comment by bradymiller** [comment]
yep, `null` is your best friend with PHP8 :)

**Comment by sjpadgett** [comment]
In this case you have to cast the var with (int)
