### ISSUE TITLE
Site Id missing from Session Data

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4483]
### Describe the bug
Either one of our timers is preventing going to log in landing page on a time out or time out is broken.

Instead, the next time after timeout the user tries to go to a page, globals throws the warning.

**Comment by sunsetsystems** [comment]
Can you reproduce on one of the demo sites? I just tried one of the daily development demos and it seemed OK with a 30-minute timeout.

**Comment by sjpadgett** [comment]
I'm on master so i'm ahead of demo server.  Plus i'm on windows so who knows.
Generally i've found that if you get site id missing then some how session got corrupted and timer is not involved to kick to landing page.
I've always believed the timers generate a conflict with each other where my testing has been to set timer to a long value like 6 hours and let run over night or while working.
I've not once been kicked to landing page but consistently get the globals trap when I use app again. This to me means the timer never got to the time out and session was corrupted before that point. Now with the timers as the only thing running in the case of over night test then my assumptions that timers are in involved seems valid. Though I should check to see what happens to timer if session gets corrupted.

I also believe that this issue can be related to and more likely to present on slower systems or could be specific to windows.
I've never taken the time to fully look into this theory but will now. Unless someone else can reason this differently.

lol, so no, I haven't reproduced on demo servers taking the long way to answer your question Rod...

**Comment by sunsetsystems** [comment]
Aren't the daily dev demos refreshed daily? Anyway try it with a 5 minute (300 secs) timeout. If that still fails it shouldn't be too hard to track down, given that it works on the dev demo. Or if it works then you can try different values and/or usage actions to get more information.

**Comment by sjpadgett** [comment]
I believe the dev demos may reset but not necessarily with the latest master. @bradymiller can confirm or not. Seems awhile back I tried to test a change I put in master but didn't show up after reset. Regardless the session change would be on demos as it's been a few weeks since changes were merged.

Still, I many times find bugs that don't necessarily show up on demos or visa versa. Windows especially tends to show different bugs. I'm 90% sure we still have a bug where I have to track down whether it's environment or something else.

**Comment by kchapple** [comment]
I see this behavior also, Jerry, but haven’t ever been able to figure out what causes it. When I see it, “Logout” link doesn’t work (I think a class not found error for SystemLog log it’s thrown). I have all my garbage collection and session stuff set up correctly.

**Comment by sjpadgett** [comment]
thanks @kchapple What is your timer set at and what OS i.e. is windows?

**Comment by kchapple** [comment]
Usually I add a 0 to the default. I develop on Mac, but also see it on Ubuntu.

**Comment by kchapple** [comment]
I’ll make a note, next time I run into it to put some context info here.

**Comment by sjpadgett** [comment]
Yep, I believe this is an issue with timers on long values. I'm trying to narrow and know it breaks on 6 hours so now testing 4 hours.
I think both timers call globals so could be a conflict between the two timers on rare occasions. Anyway this is what my gut tells me or it could just be something I ate.:)

**Comment by bradymiller** [comment]
to clarify the demos, they are built nightly (i think midnight but maybe 1 am pacific time) directly from the master branch on github.

**Comment by sjpadgett** [comment]
This worked at 4 hours last night. I also watched session_tracker all day yesterday where updates were as they should.
This is just weird. I think 4 hours is a reasonable time if consistent. However, I can't seem to let it go.:)

Please if others could just test at various timer settings and report i'd be great.

**Comment by stephenwaite** [comment]
sure @sjpadgett , just set rel-600 patch 2 in demoland, https://eight.openemr.io/c/openemr/index.php, to test 6 hours and can test others there too if you'd like.

**Comment by sjpadgett** [comment]
I appreciate it Stephen. I'll put a test up on dev demo as well. I was hoping this was just a windows issue but Ken reports differently.

**Comment by sjpadgett** [comment]
Btw: I'm going to change the timer on dated reminders to maybe a 15 sec difference from background tasks firing so they don't fire at the same time. I believe this is the issue and will test again tonight on my system.

**Comment by sjpadgett** [comment]
This is interesting but from my v6 where I was just running a quick php8 test yesterday and maybe only had v6 up for an hour.
May just be a fluke where weno is not enabled on my other tests.
```
[27-Jun-2021 22:45:34 America/New_York] PHP Fatal error:  Uncaught Error: Failed opening required '../interface/globals.php' (include_path='C:\xampp\htdocs\openemr-6.0.0\vendor/pear/archive_tar;C:\xampp\htdocs\openemr-6.0.0\vendor/pear/console_getopt;C:\xampp\htdocs\openemr-6.0.0\vendor/pear/pear-core-minimal/src;C:\xampp\htdocs\openemr-6.0.0\vendor/pear/pear_exception;C:\xampp\php\PEAR') in C:\xampp\htdocs\openemr-6.0.0\library\weno_log_sync.php:11
Stack trace:
#0 C:\xampp\htdocs\openemr-6.0.0\library\ajax\execute_background_services.php(140): require_once()
#1 C:\xampp\htdocs\openemr-6.0.0\library\ajax\execute_background_services.php(177): execute_background_service_calls()
#2 {main}
  thrown in C:\xampp\htdocs\openemr-6.0.0\library\weno_log_sync.php on line 11
```

**Comment by juggernautsei** [comment]
@sjpadgett We see this all the time. I have been working on this since v6 was released and there are people not using weno that get this error message.

**Comment by sjpadgett** [comment]
Probably should open an issue so others will know and possibly help.

**Comment by juggernautsei** [comment]
The weno log sync was addressed in my last repo update

**Comment by sjpadgett** [comment]
> The weno log sync was addressed in my last repo update

so @juggernautsei is/can it come back to v6(3). Should/can I do it and what is PR?

**Comment by sjpadgett** [comment]
Put up a fix, I think, and will test further. Will be on dev demo tomorrow.

**Comment by stephenwaite** [comment]
@juggernautsei's [fix](https://github.com/openemr/openemr/commit/97d090c1d08c4df0348a9ded1afd5e03dd49991d) was brought in just before patch 2 was formed

**Comment by sjpadgett** [comment]
hmm why am I seeing the error. I need to make sure I have it I guess, though I patched up v6(2).

**Comment by juggernautsei** [comment]
the correction is not in the patch. Fixing the log sync function https://github.com/openemr/openemr/pull/4480

**Comment by sjpadgett** [comment]
Okay thanks i'll look into if you say okay to bring back

**Comment by sjpadgett** [comment]
This is frustrating. My gut is wrong as my 6 hour test failed with no recorded errors. Still separating those timers is better than before.

Also had it fail on my dev machine where I did some encounter views and demographics/picker stuff then left for, I guess, 1 or 2 hours and received the error when I came back to refresh patient. I did get an error that I think may just be a product of what caused site id error. Or globals failing at site id error and loading classes didn't happen. Still I'll report it here:
```
[29-Jun-2021 12:20:56 America/New_York] PHP Fatal error:  Uncaught Error: Class "OpenEMR\Common\Logging\SystemLogger" not found in C:\xampp\htdocs\openemr\src\Common\Session\SessionUtil.php:133
Stack trace:
#0 C:\xampp\htdocs\openemr\library\auth.inc(128): OpenEMR\Common\Session\SessionUtil::coreSessionDestroy()
#1 C:\xampp\htdocs\openemr\library\auth.inc(93): authCloseSession()
#2 C:\xampp\htdocs\openemr\interface\globals.php(132): require_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\openemr\interface\logout.php(23): require_once('C:\\xampp\\htdocs...')
#4 {main}
```

I have a routine I wrote for profiling and watching globals session start in globals that I'm going to leverage to log. It's exception based so we get the trace. 
I'm also going to log everything I can think of at the point of the site id trap.

**Comment by sjpadgett** [comment]
It's interesting dated_reiminder_counter is still trudging along.

**Comment by sjpadgett** [comment]
Ubuntu 20 dev demo failed but instead of a site id error it took me to login.
Here is logged errors:
```
start log
[29-Jun-2021 11:54:07 UTC] SQL Error with statement:insert failed: INSERT INTO `log_comment_encrypt` (`log_id`, `encrypt`, `checksum`, `checksum_api`, `version`) VALUES (?, ?, ?, ?, &#039;4&#039;)--Unknown column &#039;checksum_api&#039; in &#039;field list&#039;==&gt;/var/www/html/a/openemr/src/Common/Logging/EventAuditLogger.php at 814:sqlInsertClean_audit
[29-Jun-2021 11:54:09 UTC] OpenEMR WARNING: Unable to resolve hashing preference, so using PHP Default
[29-Jun-2021 11:54:10 UTC] SQL Error with statement:insert failed: INSERT INTO `log_comment_encrypt` (`log_id`, `encrypt`, `checksum`, `checksum_api`, `version`) VALUES (?, ?, ?, ?, &#039;4&#039;)--Unknown column &#039;checksum_api&#039; in &#039;field list&#039;==&gt;/var/www/html/a/openemr/src/Common/Logging/EventAuditLogger.php at 814:sqlInsertClean_audit
[29-Jun-2021 21:07:06 UTC] PHP Warning:  session_destroy(): Trying to destroy uninitialized session in /var/www/html/openemr/src/Common/Session/SessionUtil.php on line 243
```

I keep seeing this so may be our issue. dated reminders call globals.php then globals calls config.inc that does some encryption stuff so that may be what sets the site id error off on an idle openemr.
@adunsulag We talked a little about this. You have any thoughts?

**Comment by adunsulag** [comment]
@sjpadgett I don't right now, I can look into this deeper tomorrow though.  Session timing bugs are always really hard to track down.  I don't know really much about the timer code at all but I can familiarize myself in it if that would be helpful.  We talked about the autoloader failing during session_start which is a common source of errors I've seen in other systems.  Often I've seen these errors come from a bug or problem in a overloaded session_save_handler.

Are we overloading the [session save handler](https://www.php.net/manual/en/function.session-set-save-handler.php) in OpenEMR? I would want to look at what is going on in the save handler.   I did some search in the codebase and I can see how adodb has a session write handler but I don't know if we are using that or not.

**Comment by sjpadgett** [comment]
Don't worry about too much. I think I know why but need more info from testing. Going to set up some traps for testing.

**Comment by sjpadgett** [comment]
Ran 4 test last night. 2 on dev demo farm(chrome) and 2 local windows 10 machine(FF and Edge). Demos worked, windows failed.
Looking into session.gc_maxlifetime and how perhaps windows and linux garbage collection etc may be different. Still my local is at default value of 24 mins but I was under the impression the session cookie ttl is overriding.
@stephenwaite Didn't you look into this and do you know what dev demos are set at?

I hope it is just my brain lapse and that session.gc_maxlifetime really does need to be set at a value greater than timeout.

**Comment by stephenwaite** [comment]
@bradymiller helped explain it to me
https://github.com/openemr/openemr/pull/4439#issuecomment-860014749

2 hours on dev demos

**Comment by bradymiller** [comment]
Wonder if it may be session.cookie_lifetime setting in windows php.ini

can see quick description of both here:
https://blogs.oracle.com/oswald/php:-sessiongcmaxlifetime-vs-sessioncookielifetime

Note appears session.gc_maxlifetime is relative (ie. activity resets it, and since the timer script is going every 60 seconds, in theory, any setting above 60 should suffice for OpenEMR).

Note session.cookie_lifetime is absolute (ie. it will die after that many seconds no matter what); also looks like a difference between client time and server time may cause issues with this if set.

**Comment by bradymiller** [comment]
clarification on session.gc_maxlifetime, OpenEMR does override this to 14400 (again, though, in theory anything above 60 would work in OpenEMR core :) )

**Comment by sjpadgett** [comment]
Thanks Brady and Steve. I think the issue is tangled in there somewhere. We may want to set these values in core code. Maybe session.gc_maxlifetime to timeout plus a fudge factor still Brady, my thoughts on how this works is the same as yours.

I'm not sure but could the stored session file get cleaned up and the cookie live on.
I don't have a  session.cookie_lifetime in my php8.ini.

**Comment by bradymiller** [comment]
Does the session get removed in /tmp (or whatever location your php is storing sessions) when you see this error?

**Comment by sjpadgett** [comment]
I didn't think to look. I know the cookie is still active as I did look at that.

**Comment by bradymiller** [comment]
you may of already done this, but would put debug stuff here that dumps all possible info (or xdebug block) to capture if openemr is killing the session/cookie:
https://github.com/openemr/openemr/blob/master/src/Common/Session/SessionUtil.php#L227

**Comment by bradymiller** [comment]
actually, better place is here:
https://github.com/openemr/openemr/blob/master/src/Common/Session/SessionUtil.php#L136
(turning on Stephen's logger will also provide some basic info there)

**Comment by sjpadgett** [comment]
I finally figured it out. Now I can have peace of mind....

**Comment by stephenwaite** [comment]
![peace_of_mind](https://user-images.githubusercontent.com/5618372/124041395-c832d200-d9d4-11eb-861e-5a733e2dd9a2.gif)

**Comment by bradymiller** [comment]
![tenor (26)](https://user-images.githubusercontent.com/278968/124041672-2b643a80-d9bc-11eb-956d-000727159934.gif)

**Comment by sjpadgett** [comment]
Did you know:
- PHP GC (garbage collector) doesn't delete the session file but empties the content. (Assumes the OS will delete on boot)
- PHP8 default session.gc_divisor=1000 (use to be 100 and is a better setting for our use) i.e. a 0.01% chance GC runs on session_start.
- A session_start doesn't update the session file modified time. (Makes sense)
- Regardless of the session cookie TTL, GC will invalidate the session file.

So knowing this it's clear why we see this intermittently across systems, OS and instances. It really depends when the GC fires and if our timeout is > than the session.gc_maxlifetime directive.

For a fix I think rather than implementing any directive changes like ```ini_set('session.gc_maxlifetime', 'timeout');``` in core somewhere, we simply add a date stamp/or write to session from our dated_reminder_counter or session tracker. This will update the session file access time saving us from having to worry about various system differences.

**Comment by juggernautsei** [comment]
![image](https://user-images.githubusercontent.com/834958/124044274-1054f300-d9db-11eb-9e9e-efbee40f2088.png)

**Comment by sjpadgett** [comment]
Testing a fix where I write a date stamp to session when dated reminder counter fires works well.
I think this is the way to go so will put up a PR unless anyone see a problem with this.

If anyone wants to test using my method add to globals before the session start:
```
ini_set('session.gc_maxlifetime', '90'); // why wait
ini_set('session.gc_divisor', '1'); // ensures GC fires on every globals call(session_write)
```
Then watch the session file for cookie id.

**Comment by stephenwaite** [comment]
![cookie](https://user-images.githubusercontent.com/5618372/124052917-4ac78b80-d9ed-11eb-8982-48a4104b5c50.gif)

**Comment by sjpadgett** [comment]
I'm happy to report that I woke up this morning to three log in screens(three different browsers). It was as though my computer was eager for me to see!(My computer is such a suck up!):)

I think that between all of us, we finally have the session, cookie and timer stuff nailed. Nice work everybody!

Closing issue.

**Comment by stephenwaite** [comment]
![crowd-cheering](https://user-images.githubusercontent.com/5618372/124123626-84c47c00-da45-11eb-849b-a2c040dd101a.gif)
