### ISSUE TITLE
Dev Demos with data Down with Error

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4489]
```
ERROR: insert failed: INSERT INTO `log_comment_encrypt` (`log_id`, `encrypt`, `checksum`, `checksum_api`, `version`) VALUES (?, ?, ?, ?, '4')

Error: Unknown column 'checksum_api' in 'field list'
```

I don't think it has anything to do with my commits yesterday.

**Comment by stephenwaite** [comment]
think there's something broken in the upgrade script since the demos with no data are fine

**Comment by stephenwaite** [comment]
it's like it's skipping over the `5.0.2 to 6.0.0` script

**Comment by sjpadgett** [comment]
yep the upgrade scripts failed so that's where we need to look

I just wanted to run a timer test. Also realized I forgot about the reminder counter fetch so hope what I have now works otherwise will need to look into that.

**Comment by stephenwaite** [comment]
in the [sql/5_0_2-to-6_0_0_upgrade.sql script](https://github.com/openemr/openemr/blob/master/sql/5_0_2-to-6_0_0_upgrade.sql#L584-L585), the new manner of creating uuids expects the field `table_vertical` to already exist in `uuid_registry`

would it be ok to reorder that script so any uuid need updates are at the end?

**Comment by sjpadgett** [comment]
@stephenwaite fixed so closing.
