### ISSUE TITLE
Support POST _search operation for FHIR 

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4497]
So did some digging.  US Core 3.1.1 requires a POST for searching as well as GET requests.  ONC 2015 certification is against the 3.1.1 spec.  The newest spec coming out for US Core is 3.2.0.  Apparently Inferno misunderstood in their implementation (a ton of people did as the R4 specification documentation is poorly worded).  [Read a pretty long thread on the FHIR forum over this.](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Search.20via.20POST)

I'll go ahead and map the $_POST requests to $_GET.  One reason listed on the forum for why the FHIR spec requires search on POST is that the URL has a limitation on the length for some user agents.  I guess some search parameters used can far exceed the URL length and so POST must be required.  Not sure OpenEMR will ever hit that limitation.

**Comment by stephenwaite** [comment]
![smaller](https://user-images.githubusercontent.com/5618372/124325742-32718100-db53-11eb-82f0-34901af207f7.gif)
