### ISSUE TITLE
Setting up using CONTRIBUTING.md fails

### ISSUE THREAD

**Issue by ajung202** [openemr/openemr#4501]
Hello, I wanted to contribute to this project and tried to follow all the steps listed in CONTRIBUTING.md doc, but it fails with the following error: 
openemr_1     |
openemr_1     | Love OpenEMR? You can now support the project via the open collective:
openemr_1     |  > https://opencollective.com/openemr/donate
openemr_1     |
openemr_1     | Starting cron daemon!
openemr_1     | Starting apache!
openemr_1     | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.21.0.6. Set the 'ServerName' directive globally to suppress this message

I made sure I had the most recent dockers using these commands: 
docker pull openemr/openemr:flex
docker pull mariadb:10.5
docker pull phpmyadmin/phpmyadmin
docker pull couchdb
docker pull openemr/dev-ldap:easy
but it still repros the same issue. 

Is there anything I can do to troubleshoot this?

**Comment by stephenwaite** [comment]
hi @ajung202 , that's just an apache warning, you should be able to login at localhost:8300 in your browswer.

**Comment by ajung202** [comment]
Thanks!
