### ISSUE TITLE
Odd menu items showing up in Reports

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#4520]
![image](https://user-images.githubusercontent.com/278968/125223837-49b21c00-e281-11eb-9729-98ed96da43ce.png)

**Comment by bradymiller** [comment]
The following items are showing in the menu above on default installations (with broken links):
Peachtree Export
Visit Voids and Changes
Visit Voids and Changes

**Comment by sunsetsystems** [comment]
Oops, somehow they got in there prematurely. I'll remove them.
