### ISSUE TITLE
Add various CCDA document type exports CCM

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4523]
### Describe the problem
Need to Send several different CDA's. CCD, ToC, Referral or other clinical note document types e.g. Consultation etc..
CCM only selects latest encounter where latest encounter may note be the encounter to base the CDA on. 
Unsure currently if I'll expand CCM export or send from encounter or both.

ONC updated their testing jig on 6/20/2021 so had to add so fixes but we'll see how long that lasts!:)

![image](https://user-images.githubusercontent.com/1859985/125371366-9b74a800-e34e-11eb-9539-ea8ed7bfd60b.png)

**Comment by stephenwaite** [comment]
![sisyphus](https://user-images.githubusercontent.com/5618372/125459715-ea6c1b7c-6e66-4e60-871f-c9d2a33b7364.gif)
