### ISSUE TITLE
Add FHIR R4 Interpretation to Vitals Observation

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4527]
Users have requested that we implement the interpretation property of the FHIR Vital Signs Observation in FHIR R4.  To do that we need to add an interpretation dropdown similar to what is found in our lab procedure results that lists whether the vital observation is normal, above average, below average, etc.

**Comment by adunsulag** [comment]
This issue is now complete

**Comment by sjpadgett** [comment]
At least 10 Atta Boys!
![giphy-downsized](https://user-images.githubusercontent.com/1859985/128528593-c25282c7-8836-48fb-b3cb-bef8e68de34b.gif)

**Comment by sjpadgett** [comment]
Stephen W. and Brady have now got me started with the gif files!

**Comment by bradymiller** [comment]
![2DV-2](https://user-images.githubusercontent.com/278968/128532191-f67cbb59-e5ea-4032-b982-1068f8527204.gif)
