### ISSUE TITLE
Logging of documents

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#4533]
Just noticed that add/change/delete of documents to patient is not logged. 

Is there specific reason for this?

**Comment by stephenwaite** [comment]
looks like it's logged

![Screenshot from 2021-07-18 15-18-14](https://user-images.githubusercontent.com/5618372/126079581-05289fd0-b0ec-40d5-adb0-ee80b7fa075d.png)

**Comment by mdsupport** [comment]
Ah. As seen, is the bug then log entries do not set patient ID from foreign_id field in documents?
