### ISSUE TITLE
ios 10.2.1

### ISSUE THREAD

**Issue by robertogagliotta** [openemr/openemr#456]
openemr is not working with the  ios 10.2.1 in my iphone, I think this is the most updated ios version; it works perfect with ios 10.0.2

**Comment by bradymiller** [comment]
What is happening(for example, white screen of death?). Also will be helpful to look at the javascript log while you try it to see if any errors there.

**Comment by robertogagliotta** [comment]
I just try it using the openemr demo and works 100% . The problem is on my server them. You can close the issue, Thanks
Roberto
