### ISSUE TITLE
Support multiple CareTeam records per patient

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4560]
I implemented and connected the FHIR CareTeam status property inside patient_data.  However, I discovered that the FHIR test suite requires that you support at least two care team records with different status (active, proposed, suspended, etc) for a single patient.

What I am thinking we do to resolve this issue is to create a patient_careteam_history table and anytime the careteam data changes in patient_data save off the record into the patient_careteam_history table.  Anything in the table will be treated as 'inactive'.  

Long term I think the best thing would be to 'normalize' the CareTeam and have it be a separate table since there are a lot of care team properties that could be reported back via FHIR that people may want to add in the long term. That will be a lot of engineering work, creating this table at least will allow us to track careteam changes over time and handle the need for at least two status elements (inactive, and whatever is currently set for the main careteam) per patient.

**Comment by sjpadgett** [comment]
I'm creating a linked table now for just this type of data for previous patient names. Can also add care team members if tell me what is needed for columns in your opinion/needs.

**Comment by adunsulag** [comment]
@sjpadgett I've actually already implemented this and plan on pushing the PR very soon.

**Comment by sjpadgett** [comment]
@adunsulag can we just call it patient_history so it can be generalized for other history?

**Comment by adunsulag** [comment]
@sjpadgett So I'm hesitant to generalize the table because CareTeam at some point needs to support fields such as time period of the care team, name of the care team, primary contact number, as well as the many to many relationship between providers and facilities.  We could generalize the table right now to work in a patient_history context but I worry that it will be more work to extract the care team data out of it at a later date.

I can definitely see how this would work though for previous name as the save logic would be very similar to what I'm doing with CarePlan right now.
