### ISSUE TITLE
List showing duplicates in the display of the list

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#4577]
### Describe the bug
In the demographics we noticed that the list of referrals shows the same entry two and three times. 
![image](https://user-images.githubusercontent.com/834958/129103701-a1adf538-94dd-4f0c-a6fe-decf8a3f6dbb.png)

### To Reproduce
Hard to reproduce. 

1. Created new list with add
2. Opened Demographic
3. Added to list
4. Entry shows 3 times

### Expected behavior
One item in list per entry.

### Client configuration

- Browser: Firefox and Chrome
- OpenEMR version: 6.0.0. (2)
- Operating system: Ubuntu 20.04

**Comment by juggernautsei** [comment]
I checked the demo and this happens there two. I will look into fixing this. I know the issue most likely will be in the options.inc function generate_select_list.

My first thoughts are to slap a distinct on all of the select statements.
But hmmmm

**Comment by mdsupport** [comment]
Since only specific options are repeating it is probably related to SQL left joins being used for translation. Correct SQL will generate the list and then translate.
Interesting that it took this long to be noticed.  @juggernautsei is leaving no box untested!
