### ISSUE TITLE
Better Living through chemistry (Better drugs for the system)

### ISSUE THREAD

**Issue by Thuetar** [openemr/openemr#458]
Greetings All -
I've been exploring the project, kicking around the idea of enhancing the drug section, and decided that I would.

The first big thing I did was to explore the available free datasets out there, looking to find a complete one, that is free to non-commercial use and supported. It also had to cover interactions. I found Drugbank and started exploring it, and toying with the data. I'm going to side step the online API with the initial crack at this due to the need for speed, but hey - maybe later. 

Considered design highpoints -
I'm a huge fan of entity factory models, and my concept is the following -
- Drug Entity Factory (Responsible for generating a factory based on the data set)
-- Drugbank Entity 
--- Search Feature
--- Basic Drug info (name, who makes it, etc)
--- Dosage 
--- Drug Ingredients
----- Drug Interactions
----- Food Interactions
(Yes - this will be heavily object-centric)

Tables and Data Schema
I initially thought 'This would be awesome for a json store' and then thought 'lets not' and I'll stay traditional. This is what I'm targeting for my MVP,
- Drug
-- IID (pk internal id), EID (supplied by vendor), Name, Desc, indication
- Interaction 
-- Drug EID 
-- Interaction Type (food, drug),  
-- Name
-- Description

UI 
- Essentially  
-- a simple, or complex (customizable to some degree based on user desires) overlay for the clinicians rx that would display drug info. 
-- driven by pt info, a possible drug interaction warning would display
-- ability to print drug info for PT

Anyway - I'm working out the core modules now. A few questions since I'm new -
How best to communicate with the group about the models? 
I LOVE AXURE for both UI and flow modeling, does this work with the group to communicate?
I am also comfortable with EA.... 

Thoughts?

**Comment by bradymiller** [comment]
Hi @Thuetar ,

Welcome to OpenEMR!

Drugbank looks very interesting. The license seems odd with the non-commercial clause there; is there a way to allow commercial use of this(since a common scenario would be a professional offering OpenEMR with this installed which would then be commercial use)?

Regarding models, anything in this realm would be really cool to see. The community has not used this, but I am guessing many folks (including myself) would like to learn this. Guessing @MatthewVita may have input on this.

-brady

**Comment by MatthewVita** [comment]
Hi @Thuetar,

> Drug Entity Factory (Responsible for generating a factory based on the data set)

Is there a webpage on this? Can't find anything on it. Seems interesting!

> I initially thought 'This would be awesome for a json store' and then thought 'lets not' and I'll stay traditional. This is what I'm targeting for my MVP,

OpenEMR uses MySQL and I would bet most users won't be on 5.7 with the native JSON support.

> How best to communicate with the group about the models?

There are a few ways. I would recommend putting together a PR and using `markdown` comments. If you need to visualize things, maybe try out the FOSS http://pencil.evolus.vn/

Thanks,
Matthew Vita

**Comment by Thuetar** [comment]
Hey @bradymiller 
Apologize for the delay responding. Drugbank DOES indeed have a lic model for commercial usage. https://www.drugbankplus.com has the lic details and contact info. I have no idea what the cost would be... (Disclaimer: I have nothing to do with them, nor am I a lawyer). What I do really like is the data :) which in healthcare IT is somewhat spendy (as you may well know)! 

One downside - the data is provided in an enormous XML file, 580+MB. Each drug's data is heavily nested... Let's just say that multi-threading the load isn't planned.

Another idea I had while reviewing the data was to provide the Provider (odd phrase, please forgive me) the ability to print out a PT usage sheet since that is also doable.

Modeling -
I love the UML, but nothing close to the extreme. One thing I really value is the code generation part :) 

@MatthewVita 

> Is there a webpage on this? Can't find anything on it. Seems interesting!
I could have better stated the concept. The more proper term is factory pattern and in my world the concrete implementation is the entity, but this isn't canonical in the development world. It was proposed by the GoF way back in the day in the hallowed tome of 'Design Patterns' for some light reading. I usually follow the abstract factory pattern (https://en.wikipedia.org/wiki/Abstract_factory_pattern) for something like this. The basic idea is to provide the ability to (in the abstract) support multiple datasets through a single common interface. So - drugbank initially since it's free, and whatever next. From the end user perspective to get the entity ou just say something like 
`Drug drug = new DrugFactory("drugbank"); // or whatever
ArrayList<String> searchResults = drug.searchByName('Haldol'); //flexible and fun!
`
 And the factory supplies you the concrete class. With drug, I can use the same methods as with any other concrete drug class - and expect the same results. The key being here is that Drug is an interface which forms the contract - it outlines the public methods the concrete class supply as well as the return. The concrete class implements the interface and no troubles no bubbles. I'll stop here....

> OpenEMR uses MySQL and I would bet most users won't be on 5.7 with the native JSON support.
Excellent point. It would make the UI a little more fun. I was thinking we could chuck back JSON to the UI and then use data binding, yet after thinking more about that it opens a can of worms.

>There are a few ways. I would recommend putting together a PR and using markdown comments. If you need to visualize things, maybe try out the FOSS http://pencil.evolus.vn/
I'll check out Pencil.... I'm very visual, and also lazy I hope it can generate code ;)

Lastly,
-- Progress, I've been getting up to speed on doctrine. I like it alot! This however introduces a problem with the massive data load, this load isn't viable in browser and will need to be CLI. I couldn't get this functional with the existing framework and rigged up the loader. I'm not sure if this creates a technical debt. 
--- I have something approaching a working MVP now regarding initial drug load into a set of tables I'm calling 'KB_Drug_(DOMAIN)' 
--- Not that this has to be addressed now, but does anyone have any thoughts on isolating the KB tables into a separate database, schema, or just throw it all together? 
-- I'll post my crummy schema and with luck some use cases/domain concepts for comment later today/tonight.

**Comment by MatthewVita** [comment]
> One downside - the data is provided in an enormous XML file, 580+MB. Each drug's data is heavily nested... Let's just say that multi-threading the load isn't planned.

Is the idea that we will introduce this data into OpenEMR with new tables / features, leaving Drug Bank Plus out of the equation? I'm assuming that Drug Bank Plus performs most of the interactions checks? If so, is this better than the current Allscripts solution: http://open-emr.org/wiki/index.php/OpenEMR_ePrescribe ?

> abstract factory pattern

Got it. I am familiar with this pattern.

> Doctrine [...] I'm not sure if this creates a technical debt.

I'm actually running a project with Brady now that introduces Doctrine into the codebase. Won't be an issue if you use it with this project.

> a separate database

If I'm understanding this correctly, we can use the same database, but the data will have to be loaded in by the user (similar to the ICD codes, which have to be "opted" in). Don't think this will be an issue.

Thanks,
Matthew Vita

**Comment by Thuetar** [comment]
It is always great to have an SME. While reviewing the data with my local SME (Wife) she pointed out the doing guidelines and protocols appear to be missing in the data supplied by DrugBank. This is a problem. I have a question out to them now and I'm now considering other options.

> Is the idea that we will introduce this data into OpenEMR with new tables / features, leaving Drug Bank Plus out of the equation? I'm assuming that Drug Bank Plus performs most of the interaction checks? 

It will and can. 

##Storage
My goal is to be able to store the data vendor neutral to avoid lock in. How that happens is very much open. This will be fairly complex and there are many distinct domains in any potential imp -
- Drug Surface Details (name, desc, etc)
-- Drug Equivalents ( generic trade names)
-- Drug Contraindications (Amphetimine and CHF don't mix well)
-- Drug Interactions
-- Supplied Strengths (20mg, 40mg, etc) and formulary
..

Modeling the data I can see 2 primary ways to approach this - 
- Key / Value Table
- Traditional transactional table layout for more complex sorts

Key / Value garbage tables (aka Kimball) are awesome for simple records (source, metric types) etc
but this would be very complex to query. 

> If so, is this better than the current Allscripts solution: http://open-emr.org/wiki/index.php/OpenEMR_ePrescribe ?

I really appreciate you pointing this out to me, and after considering it here are a few thoughts.  
In my experience Doctors (generally speaking) are careful and considered in their approach to patients as well mundane things like their toothpaste. I've been working in the industry for many years, there would be misgivings about the module for a variety of reasons.
**Pro**
-- It does appear to functional and useful - that is awesome

**Con**:
-- The installation indicates some level of backdooring with Greesemonkey and scripts
--- I would imagine any actual legal review would go rather poorly. 
I asked AllScripts about OpenEMR integrations and the response was they do not integrate or support OpenEMR. While I haven't reviewed their T&C's this response coupled with the litigious nature of the industry is immediately problematic.  
-- No offline mode (No INET, No Drugs). Providers already dislike these systems. There is even a clinic who's primary recruitment hook was 'NO EMR - We use paper charts'. True.
-- Users would be down should AllScripts make changes to the page structures 'compatibility issues' appear to have occurred in the past. Providers would find this unpleasant. 

I think any workable solution should be able to run native, and not come with the above. My end goal is a solution that meets the target market, and without a dependency on a stable INET connection. In the African nation I visit routinely in the walls are poured concrete due to cyclones. Good luck getting a WiFi connection in the next room, or INET post-cyclone while repair crews fix things. Stable INET is very much a 1st world luxury. 

Just my thoughts and experience. 

@bradymiller @MatthewVita If any of you have some more suggestions on an open Drug Guidline dataset please let me know.

**Comment by bradymiller** [comment]
This all sounds good. 1 pitfall to avoid is to always user lower case on your sql table names.

Check out the external data loader at Administration->Other->External Data Load (I think that is the name)

This is a good way to bring in data like this and can see the other mechanisms(ICD9/10/SNOMED) for inspiration. This is where you can create the sql tables and then the mechanism to import the data to your sql tables. Recommend that the starting point be the exact file you downloaded from Drugbank.

**Comment by MatthewVita** [comment]
> -- The installation indicates some level of backdooring with Greesemonkey and scripts

Good point. A more robust solution such as this would be great.
