### ISSUE TITLE
Date is ignored when searching on a date range in Patient List Creation > Demographic

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#4581]
Reports > Clients > Patient List Creation

From:
To:
Option: Demographics

"When searching on Demographics, the date field is not taken into account, unfortunately. The date field works with other parameters."

See:
"Patient List Creation Reports Issues
https://community.open-emr.org/t/patient-list-creation-reports-issues/13540/8

OpenEMR 5.0.2 and 6.0.0 Patch 2

**Comment by stephenwaite** [comment]
hi @pete-boyd , thanks for the bug report, wish it was as cool as [weather report](https://duckduckgo.com/?t=ffab&q=weather+report+seminal+band&iax=videos&ia=videos&iai=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D-7hIPu0Cusg)

going to add this to a pr soon as the first `case` in the `switch` [statement](https://github.com/openemr/openemr/blob/master/interface/reports/patient_list_creation.php#L435)

```php
                case "Demographics":
                    $whr_stmt = $whr_stmt . " AND pd.date >= ? AND pd.date < DATE_ADD(?, INTERVAL 1 DAY) AND pd.date <= ?";
                    array_push($sqlBindArray, $sql_date_from, $sql_date_to, date("Y-m-d H:i:s"));
                    break;
```

**Comment by kchapple** [comment]
@stephenwaite Dude, that is amazing.
