### ISSUE TITLE
MU3 Demo Site Setup for FHIR Inferno Testing

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4585]
We need to make sure we have the MU3 Demo site setup for fhir inferno testing.  I am going to document the setup instructions and what is passing / not passing using the publicly accessible [ONC Inferno testing tool](https://inferno.healthit.gov/inferno/).

I will be using the **edu** demo available [here](https://edu.openemr.io/openemr/).

For our initial setup we are going to enter in the FHIR base url for the installation: **https://edu.openemr.io/openemr/apis/default/fhir**
![image](https://user-images.githubusercontent.com/228117/129585622-22b2969b-72e3-46a8-a9f1-59268984a73e.png)

We then need to register our OAuth2 Client application which we'll need to grab 3 URLs from Inferno to do so:
Hit the run tests in the Standalone Application test suite and grab the **Redirect URI** and the **Launch URI**:
![image](https://user-images.githubusercontent.com/228117/129585947-1158caab-31f6-49b1-8bc4-678d91251252.png)

Then go to the multi-patient testing tab
![image](https://user-images.githubusercontent.com/228117/129586050-70af8436-74bf-4d19-b0f0-f9e4251c4bba.png)

Hit **run tests** and grab the **JWK Set URL**
![image](https://user-images.githubusercontent.com/228117/129586157-332453ca-389e-4930-a5cd-25738e951098.png)

We can now register a client that can be used for all of our tests (this values can change but I've pasted them here for reference):
- Redirect URI: https://inferno.healthit.gov/inferno/oauth2/static/redirect
- Launch URI: https://inferno.healthit.gov/inferno/oauth2/static/launch
- JWK Set URL: https://inferno.healthit.gov/inferno/.well-known/jwks.json

The registration page is found at <site url>/smart/register-app.php  for our example it is here: https://edu.openemr.io/openemr/interface/smart/register-app.php

![image](https://user-images.githubusercontent.com/228117/129586752-a9648304-76ae-4983-a5cf-b1ee99ac6ea9.png)
**Leave all the scopes selected so you can test patient,user, and system context.**
![image](https://user-images.githubusercontent.com/228117/129586935-1905f4d3-64bc-4b66-ad48-f23efe35c81b.png)

Now hit **submit** and your **client_id** and **client_secret** will be displayed.  Note the MU3 demos are reset every 24 hours so these screenshots are an example and these values cannot be re-used:
![image](https://user-images.githubusercontent.com/228117/129587137-8eedc800-0367-4d09-9928-67f406803901.png)

Note you won't have a client_secret if you test out a public client instead of confidential.

From there you can test out the standalone patient launch and each of the other inferno test scenarios:
![image](https://user-images.githubusercontent.com/228117/129587595-e623bc7d-7d82-4350-ace5-4e7d03c14256.png)

I will paste as comments the current results as we work through setting the demo up and fixing issues as we find them.

**Comment by adunsulag** [comment]
@bradymiller Looks like we need to update the apache ssl configuration on the MU3 demos to reject any TLS 1.2 connections.  It seems to pass on my local box but I also turn off the SSL certification validation which might be impacting the inferno test server.
![image](https://user-images.githubusercontent.com/228117/129597028-5499e37b-02f0-4770-a660-a62587129742.png)

**Comment by adunsulag** [comment]
Everything else passes for the Standalone launch except for the TLS 1.2 check:
![image](https://user-images.githubusercontent.com/228117/129597166-588c316c-4578-49ee-bf44-6728c2e9586e.png)

**Comment by bradymiller** [comment]
@adunsulag ,
Fixed this on the demo farm nginx server: https://github.com/openemr/demo_farm_openemr/blob/master/docker/nginx/nginx.conf#L17

Should work now.

![image](https://user-images.githubusercontent.com/278968/129673572-778c7611-d592-42d4-877e-4bcffa2d4f5d.png)

**Comment by adunsulag** [comment]
@bradymiller I need to add some data changes to the MU3 demos.  You mentioned you can take a snapshot of the system and have the mu3 builds off that updated snapshot.  I'm keeping a list of the changes I need to make so we don't have to repeat this step too frequently.  When would be a good day this week to get those changes in and have you take the snapshot?

**Comment by bradymiller** [comment]
@adunsulag , happy to do this (pretty minimal work on my end). Can do anytime except for during the day on Thursday/Friday.

**Comment by adunsulag** [comment]
@bradymiller Can you do another snapshot of the MU3 tonight?  I've entered a bunch of data I'd rather not lose.  I thought I'd get all the data in today, but I'm still working through some wierdness with procedures right now.  If I need another snapshot would you be able to do it in the evening on Thursday?  I think the demos reset at Midnight so you could do it whenever you're available.

**Comment by bradymiller** [comment]
hi @adunsulag ,
I can stop the demo from getting reset (just let me know which one of the four you are using). I never thought of doing a snapshot directly from the demo, but that's a good idea, and will try to get that mechanism up and working this evening.

**Comment by adunsulag** [comment]
@bradymiller I'm using the https://edu.openemr.io/openemr/ demo.  I thought you were doing the snapshots from the demo.  Is there a better way to update the data?

**Comment by bradymiller** [comment]
@adunsulag , I turned off the reset in that specific demo, so it won't restart at midnight (will buy me some time to get a save snapshot mechanism in the demo farm, which will be really cool to have). In this case, the best way is definitely using the demo to update the demo (i created the initial snapshot in the easy dev docker environment).

**Comment by bradymiller** [comment]
@adunsulag ,
Got a snapshot mechanism going and just made a snapshot. For now (just to test the demo snapshot creation mechanism over next day) am doing the following
- https://edu.openemr.io/openemr/ will not be reset, so will keep your changes
- https://edu.openemr.io/a/openemr/ and https://edu.openemr.io/b/openemr/ will use the snapshot that I just created (should be the same as the above demo where your changes are)
- https://edu.openemr.io/c/openemr/ will keep using the original snapshot

**Comment by bradymiller** [comment]
@adunsulag ,
Above snapshot demo testing looked good, so have done the following:
1. Just took another snapshot of https://edu.openemr.io/openemr/
2. Set all 4 MU3 demos to now reset daily (next in 2 hours :) ) with this new snapshot

**Comment by adunsulag** [comment]
@bradymiller Thanks Brady!

**Comment by sjpadgett** [comment]
@adunsulag I just verified that previous names is now working on this server. Surprised nobody called me out on not working.

**Comment by adunsulag** [comment]
@sjpadgett Not sure I understand, it was working on my machine.  I know I added it to the FHIR output but not sure what you mean by it not working.

**Comment by sjpadgett** [comment]
When I pulled master to test I was missing the library/layout.inc.php that set new data type. So looked back and didn't see it in my PR for previous names so, assumed I didn't include so, who knows. Works now anyway.

**Comment by adunsulag** [comment]
@bradymiller I'm not sure what has happened to the  MU3 demos on the edu demo it is failing.  The a, b, and c systems load fine but the MU3 one is failing.  From looking at the PHP logs it looks like there is a file permission issue in getting to the oauth2 filesystem keys..   Did something change there, or could it be breaking with my most recent code changes?
```
start log
[23-Aug-2021 12:54:52 UTC] PHP Fatal error:  Uncaught LogicException: Key path "file:///var/www/localhost/htdocs/openemr/sites/default/documents/certificates/oapublic.key" does not exist or is not readable in /var/www/localhost/htdocs/openemr/vendor/league/oauth2-server/src/CryptKey.php:52
Stack trace:
#0 /var/www/localhost/htdocs/openemr/vendor/league/oauth2-server/src/ResourceServer.php(50): League\OAuth2\Server\CryptKey->__construct('file:///var/www...')
#1 /var/www/localhost/htdocs/openemr/_rest_config.php(201): League\OAuth2\Server\ResourceServer->__construct(Object(OpenEMR\Common\Auth\OpenIDConnect\Repositories\AccessTokenRepository), '/var/www/localh...')
#2 /var/www/localhost/htdocs/openemr/apis/dispatch.php(59): RestConfig::verifyAccessToken()
#3 {main}
  thrown in /var/www/localhost/htdocs/openemr/vendor/league/oauth2-server/src/CryptKey.php on line 52
[23-Aug-2021 12:54:59 UTC] PHP Fatal error:  Uncaught LogicException: Key path "file:///var/www/localhost/htdocs/openemr/sites/default/documents/certificates/oapublic.key" does not exist or is not readable in /var/www/localhost/htdocs/openemr/vendor/league/oauth2-server/src/CryptKey.php:52
Stack trace:
#0 /var/www/localhost/htdocs/openemr/vendor/league/oauth2-server/src/ResourceServer.php(50): League\OAuth2\Server\CryptKey->__construct('file:///var/www...')
#1 /var/www/localhost/htdocs/openemr/_rest_config.php(201): League\OAuth2\Server\ResourceServer->__construct(Object(OpenEMR\Common\Auth\OpenIDConnect\Repositories\AccessTokenRepository), '/var/www/localh...')
#2 /var/www/localhost/htdocs/openemr/apis/dispatch.php(59): RestConfig::verifyAccessToken()
#3 {main}
  thrown in /var/www/localhost/htdocs/openemr/vendor/league/oauth2-server/src/CryptKey.php on line 52
```

**Comment by bradymiller** [comment]
Super odd since the a, b, and c systems are the same exact demos (they can
all be used for MU3 demos). The nice thing about the demo farm is it does
illustrate bugs in webroot and some other potential pathing issues, so
perhaps that is what is happening here. I'll check out that broken demo
this evening and see if there's anything wrong with that
file/path/permission.

**Comment by bradymiller** [comment]
@adunsulag , I just made these changes on the demo farm, which will hopefully fix this:
https://github.com/openemr/demo_farm_openemr/commit/d33c72976ce1fb13b5574ffee443eb4587631177

After the demos reset tonight (1:00 am), then it should hopefully work. Let me know how it goes.

**Comment by adunsulag** [comment]
For multi patient validation you need to provide the system export scopes (which are not listed by default in the Inferno test tool), the group id, and the patients that will be exported for that group.  I've chosen Albert Davis's patient list as the group. Here's a screenshot as well as the individual data that will go in the test cases:
![image](https://user-images.githubusercontent.com/228117/130689173-f110f490-4d0a-4938-a72b-d6988c423374.png)

*Scopes*
```
system/Patient.$export system/Group.$export system/*.$bulkdata-status system/*.$export system/Patient.read system/Document.read system/Group.read system/Medication.read system/AllergyIntolerance.read system/CarePlan.read system/CareTeam.read system/Condition.read system/Device.read system/DiagnosticReport.read system/DocumentReference.read system/Encounter.read system/Goal.read system/Immunization.read system/Location.read system/MedicationRequest.read system/Observation.read system/Organization.read system/Practitioner.read system/Procedure.read system/Provenance.read
```

*Group ID*
```
943b362d-e278-4b7b-8c34-fa359a3559d3
```

*Patient Ids exported*
```
9353b8f5-0a87-4e2a-afd4-25341fdb0fbc,94047b5c-39bd-4f10-bbcd-f04e87a8c9bb
```

Note we add system/Patient.$export, system/Group.$export, system/*.$export and system/*.$bulkdata-status scopes to provide permissions for patient compartment exporting (only exports data that are in the patient compartment), group exporting (only exports data that are in the patient compartment that are filtered to return only data for patients that exist in the group), and system wide exporting which is intended for a system wide backup.  system/*.bulkdata-status is used for monitoring progress of the export.  Currently data is exported in a single synchronous transaction but follows the SMART on FHIR specification to support async operations and this scope is needed to check on status for the bulk export.

system/Document.read scope is used to retrieve the binary exports that are generated in the system.  system/Patient.read is not included by default in Inferno which I don't understand why but in order to get patient data you need that scope to be included.  We add system/Group.read because we are dealing with group data but I don't believe inferno needs that scope.  I've used it when I need to debug hitting the /Group list endpoint as its only available to system level scopes.  You can use the inferno test token to hit the api endpoints using the access token as needed (its only valid for 3 minutes).

Using these settings give us full validation for multi-patient:
![image](https://user-images.githubusercontent.com/228117/130690020-b10ae566-4976-4e30-a875-18486fb11471.png)

**Comment by adunsulag** [comment]
For the last *Other* area of tests you have to register a public client, and invalidate some tokens.  I'll explain that below:

First off we need to register a public client by going to our registration page and choosing the public client option.  This hides system,user, and jwk registration information.
![image](https://user-images.githubusercontent.com/228117/130690359-17ca6a71-e37c-4780-9f23-ae6e73f83f3f.png)
 
 Registering will give you a client ID but will NOT give you a client secret.
![image](https://user-images.githubusercontent.com/228117/130690532-629810ff-6af0-4a21-8e03-3a409e5b77f8.png)

We login with the alice@gmail.com patient and can then the tests execute.
![image](https://user-images.githubusercontent.com/228117/130690735-880d44df-692f-49f9-b50c-a64080bf4cc4.png)

To run the token revocation tests make sure to run this test after you have completed the prior tests as Inferno grabs the bearer and refresh tokens to revoke from the previous test sequences.  Now hit the launch button
![image](https://user-images.githubusercontent.com/228117/130690834-6d8b06ac-153f-41c1-bc14-4c7083076fe6.png)

Copy the bearer token
![image](https://user-images.githubusercontent.com/228117/130691032-8580ae5f-d97c-4ffb-bc39-31427f56916e.png)

Login as an administrator and go to the API Clients page -> Token Tools.
![image](https://user-images.githubusercontent.com/228117/130691202-91959ed4-f70a-47f2-8c7b-f42a07d573ae.png)

Enter in the bearer token you copied and hit parse token.
![image](https://user-images.githubusercontent.com/228117/130691291-3b5c5891-34c1-4ff7-8f5e-8567d6a1376b.png)

Now hit the revoke token button.
![image](https://user-images.githubusercontent.com/228117/130691354-ed75a62c-8ea8-479f-a4c4-5d1957a09c69.png)

(Note on this page it lists the token expiration periods, you can use this to attest to the testing facility that the tokens do indeed have a 3 month expiration date for refresh token).
Now do the same thing for the refresh token.

Now go back to inferno and run the revocation test.

**Comment by adunsulag** [comment]
For the Invalid AUD and Launch tests you essentially have to mark that an error screen showed up and you were not taken to the login authentication page.  For the Launch test you will need to launch the smart app from a patient's dashboard.  You'll see an error page like this for these tests when you attempt to launch them:
![image](https://user-images.githubusercontent.com/228117/130691817-3afbce94-7ab9-4528-b79b-aa3e1398f142.png)

**Comment by adunsulag** [comment]
For the final tests you have to demonstrate the following areas.  I'll explain how we meet each requirement:
![image](https://user-images.githubusercontent.com/228117/130692049-05ab6cae-41b6-468a-8504-5e833af3162f.png)

![image](https://user-images.githubusercontent.com/228117/130693478-f0223ce7-e4eb-4cd6-a45c-98b473123ed5.png)
![image](https://user-images.githubusercontent.com/228117/130693519-56186f11-d637-4617-a115-7faab8998e5a.png)
![image](https://user-images.githubusercontent.com/228117/130693547-e27d38c7-fb02-42de-89b0-a0631bd4d02f.png)

**Comment by adunsulag** [comment]
So based on my testing it looks we completely pass all of the FHIR Inferno test cases which means we are code complete for the FHIR's ONC requirements of g(10) except for the documentation piece.

![image](https://user-images.githubusercontent.com/228117/130695255-28756695-d83e-4234-a2cf-da42fa811a32.png)

**Comment by adunsulag** [comment]
We got the MU3 demos setup so closing this issue.

**Comment by adunsulag** [comment]
Every practitioner has their own group id.  Its generated at the time the user is created or saved if one does not already exist.  The group is comprised of all of the patients that the practitioner is assigned as the PCP.  Hitting the groups endpoint will give you a list of the groups.

**Comment by rosilyg** [comment]
Thanks for the quick response, we may need more help. we are short of time
