### ISSUE TITLE
Facility Taxonomy Column Size truncates data

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4590]
So the facility taxonomy column [varchar(15)] is not large enough to hold an actual code value.  If you enter in a code value for the taxonomy such as:
**SNOMED-CT:223366009**
The value is truncated to:
**SNOMED-CT:22336**

We need to expand this column so we can hold full SCT codes.  This is needed for FHIR and I imagine CCDA as well.

**Comment by stephenwaite** [comment]
Ok but [taxonomy codes](https://www.cms.gov/Medicare/Provider-Enrollment-and-Certification/Find-Your-Taxonomy-Code) are actual code values.

**Comment by adunsulag** [comment]
@stephenwaite I thought that the taxonomy could either be a NUCC code or it could be a SNOMED-CT.  I thought @sjpadgett  told me that and its why Jerry's test data set has the SNOMED-CT prefix in it.

If its always a NUCC code then I can just hard-code what code system it comes from on the backend.

**Comment by sjpadgett** [comment]
Pretty sure I was talking about provider descriptions where the provider in ccda can be described with a taxomony or a snomed and referred by a NPI.
E.g. care teams.
Sorry if I mislead you!

**Comment by adunsulag** [comment]
@sjpadgett So your test database has a snomed code for the facility taxonomy.  Is that a mistake then?

**Comment by sjpadgett** [comment]
Huh, you're right. I have no clue how that got there! I don't believe I use taxonomy for facilities. Still, no clue but a mistake.

**Comment by adunsulag** [comment]
Sounds good.  I will make FHIR use the NUCC system for facilities and we can close this issue.

**Comment by sjpadgett** [comment]
thanks @stephenwaite
