### ISSUE TITLE
Eliminate all user* fields in new installations

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#4598]
Since the layouts have permitted addition (and problematically the deletion) of fields for a while, the user* fields are no longer useful. To make matters worse, they increase max size of the record computed by db engines without any apparent benefit and cause schema issues. These generic fields are purely bad practice to encourage and propagate in future installations.

Eliminating these from existing installations will be a challenge that should be left to respective admins. Did notice use by IPPF and @ophthal code. If project have to have these in current form, they should be included as sql patches for those specific modules but not for installations that are not IPPF or ophthalmologist specialty - guessing that would be 99%.

**Comment by mdsupport** [comment]
On a related note, also suggest Eye Exam form should require normal optional form steps starting with DB install of the eye related tables. It should also include document categories that currently need to be deleted by most installations as not relevant.

**Comment by sunsetsystems** [comment]
Agree user* can be removed from database.sql. Would be possible to also remove most from existing sites with a bit of programming... i.e. test if not active in any layouts and not containing any non-empty data.

**Comment by mdsupport** [comment]
For some reason project brought in eye forms as standard and not as addon with its own sql. That has meant portal and other modules have references to user* fields without any apparent business logic. No idea how @sjpadgett, @adunsulag will handle these fields in external interfaces. 

Highly recommend to converting eye forms optional with a db install step and fixing the logic for portal mappings to account for these type of patient_data fields that are added in the field.

Closing the issue until that occurs as merely deleting user* fields for future/new installations will break a standard install.
