### ISSUE TITLE
Need instructions on installing extensions for ADLDAP

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#460]
![image](https://cloud.githubusercontent.com/assets/1715206/22493767/19717656-e800-11e6-8357-8f7f5273e8ee.png)

...noticed this when rebasing against master. Do we need to update the *nix and Windows install instructions with how to install this extension?

**Comment by MatthewVita** [comment]
@bradymiller the following will work in the Debian installer: `sudo apt-get install -y php7.0-ldap` - just tested in Linux Mint 18 ✔️

**Comment by bradymiller** [comment]
updated following related wiki page:
http://www.open-emr.org/wiki/index.php/OpenEMR_System_Architecture#OpenEMR_Dependencies

I noted it breaks on 'composer install' if missing this(ie. developer issue). I assumed this won't be needed by the OpenEMR user if they don't use the ldap feature/package, but will ensure that this is tested to confirm this.
