### ISSUE TITLE
ONC/MU3 eCQM Reporting

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4616]
### Describe the problem
A required feature to be implemented in several phases. 

### Describe the solution you'd like
This first phase is the development, testing and integration of necessary tools to 
- develop dynamically import, parse and ready CMS CQMs.(Ruby) using project Tacoma(MITRE) tools.
- develop measures model generation(PHP) and testing tool(module).
- CQM population/patient calculations (module service).

The above is mostly completed by @kchapple where I'll be integrating and setting up the necessary repositories and modules in OpenEMR space.

Next phases will be new issues to help track project more cleanly.

Coming phases will be to populate patients models, calculate and validate (Cypress https://site.healthit.gov/sandbox-qrm-cqm) develop reporting then the 'e' part of eCQM.

Cypress user guide. A UMLS account and API key is needed to use Cypress.
https://www.healthit.gov/cypress/documents/Cypress-User-Guide-v6-1-06242021.pdf

CQM test
https://www.healthit.gov/test-method/clinical-quality-measures-cqms-record-and-export

For those interested here is the complete ONC 2015 test method including test item removals:
https://www.healthit.gov/topic/certification-ehrs/2015-edition-test-method

**Comment by sjpadgett** [comment]
@bradymiller Is your recent CCM CCDA import changes in master? I may need to modify.

**Comment by bradymiller** [comment]
@sjpadgett , yep, all changes so far are in master. Feel free to modify.

**Comment by sjpadgett** [comment]
If anyone is interested in how this all works please let me know and I'll do a write up here but generally, nobody cares at this point so I'll save some typing.:)

**Comment by mdsupport** [comment]
@sjpadgett eCQM is key element for primary care practices that sign up for CMS's Primary Care First payment model. Since the incentives are tied to these measurements, I hope all US primary care practices should be very interested. A few lines about how you envision this to work would be greatly appreciated.

**Comment by sjpadgett** [comment]
Okay. I'll do a write up tomorrow as to tired tonight. Thanks for your interest @mdsupport and look forward to your insights moving forward.

**Comment by sjpadgett** [comment]
I'm sorry but I forgot to write this up. Will soon...
