### ISSUE TITLE
Open PatientReport event dispatches to all modules

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4630]
@juggernautsei [pointed out ](https://github.com/openemr/openemr/pull/4569#discussion_r710107860)that that [patient_report.php](https://github.com/openemr/openemr/blob/6a6397d56af40818f792e3ff4af598c7ab04edda/interface/patient_file/report/patient_report.php#L272) only allows dispatch events to be fired for just the fax module.  As we want other module writers to be able to tie into those events we need to go through and remove all of the if statements that treat it just for the fax module.  This will likely require updating the fax module to check on its end whether the fax module has been enabled or not.

**Comment by juggernautsei** [comment]
@adunsulag If the fax module is not there how can it check if it is installed. It seems to me that I am concerned about the wrong thing. There is not an issue with the dispatcher being loaded with events that there are no listeners for. I will work back through my dispatchers and pass data that is needed to determine if that dispatch is valid for my listener to act.

**Comment by adunsulag** [comment]
@juggernautsei So the fax module has a global setting that you still have to enable in globals even if you install the module.  That checking of the global flag should be changed so that it can  be done in the module, not in the code.  You're correct that the dispatchers should just fire off events.  If there's no one listening its essentially a no-op.  Its up to the listener to determine how it wants to act.  Here is an example from a module I am writing.

```php
class PatientCreateStrategy implements IEventNotificationStrategy
{
  // ....
    public function canProcessEvent(Event $event, string $eventName): bool
    {
        if ($event instanceof PatientCreatedEvent && $eventName == PatientCreatedEvent::EVENT_HANDLE) {
            return true;
        }
        return false;
    }
// ....
}
```

Here is another example where I get the generic ServiceSaveEvent and I check specifically to know if I'm dealing with the VitalsService so I can fire off internally two events to handle a vitals create request versus a vitals save request.
```php
public function dispatchVitalSaveEvents(ServiceSaveEvent $serviceSaveEvent, string $eventName)
    {
        if ($serviceSaveEvent->getService() instanceof VitalsService) {
            $pid = $serviceSaveEvent->getSaveData()['pid'] ?? null;

            if ($eventName == ServiceSaveEvent::EVENT_PRE_SAVE) {
                if (!empty($pid)) {
                    $this->vitalRecordByPid[$pid] = $serviceSaveEvent->getSaveData();
                }
                return;
            } else if (ServiceSaveEvent::EVENT_POST_SAVE) {
                $preSaveData = $this->vitalRecordByPid[$pid];
                unset($this->vitalRecordByPid[$pid]); // clear out any old data that we may have.
                $isNewRecord = empty($preSaveData['id']);
                $postSaveData = $serviceSaveEvent->getSaveData();
                
                if ($isNewRecord) {
                    $event = new PatientVitalsCreatedEvent();
                    $event->setVitalsData($postSaveData);
                    $event->setPid($pid);
                    $this->eventDispatcher->dispatch($event, PatientVitalsCreatedEvent::EVENT_HANDLE);
                } else {
                    $event = new PatientVitalsUpdatedEvent($preSaveData, $postSaveData);
                    $event->setPid($pid);
                    $this->eventDispatcher->dispatch($event, PatientVitalsUpdatedEvent::EVENT_HANDLE);
                }
            }
        }
```

**Comment by juggernautsei** [comment]
I do understand the design elements. Thanks!
