### ISSUE TITLE
calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html: HTML format

### ISSUE THREAD

**Issue by chiWahWong** [openemr/openemr#464]
The open and close form tag does not seem right.
I am new to OpenEMR. I looked at the #pc_username element, I try to understand the logic from said element. I find that the open tag of the form is inside #functions, and the close tag of the form is at another location, seems it breaks the HTML structure. If the form is intended to actually enclose all input elements within the frame should the HTML structure be corrected?

**Comment by bradymiller** [comment]
Hi @chiWahWong ,

Thanks for the report.

To clarify, do you mean the following code:
https://github.com/openemr/openemr/blob/master/interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html#L144-L361

There only appear to be 2 input elements in that script which are right below the <form>

Let me know if I'm missing something.

-brady

**Comment by chiWahWong** [comment]
Hi Brady,

It is those lines.
Problem 1: The open form tag is inside #functions, but the close tag is outside.
Problem 2: #pc_username is another input (select) element. There seem to be another one.

**Comment by tywrenn** [comment]
@bradymiller Is this still an issue?

**Comment by bradymiller** [comment]
don't see this issue anymore so closing
