### ISSUE TITLE
New styles breaks light compact menu dropdowns

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4640]
### Describe the bug

Can't select dropdown item from top menu.

### To Reproduce
- Select light theme
- Select compact for Tabs Layout Theme
- Try to select a menu item.

### Client configuration

- Browser: All latest
- OpenEMR version: master
- Operating system: windows 10

**Comment by sjpadgett** [comment]
Tried manila and dark theme compact and works okay. Appears to be light only and probably a missing or errant BS class in css.
Verified on dev demo.
Of course this would be the theme setup I use and like the most!:)

**Comment by bradymiller** [comment]
Agree it's likely something simple. Hopefully @robertdown can fix this up.

**Comment by sjpadgett** [comment]
Found issue in tabs_style_compact.scss where dropdowns had a margin-top of 4px causing hover to lose scope on item selects.
Also fixed issue with manila theme:
![OpenEMR(manila)](https://user-images.githubusercontent.com/1859985/134557206-35af8f81-ea52-48ab-9c94-b3e91b7919ae.png)

Will fix in next PR
