### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by zidingz** [openemr/openemr#4648]
Hey there!

I belong to an open source security research community, and a member (@thelabda) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by stephenwaite** [comment]
hi @zidingz , please email it to @bradymiller at brady.g.miller@gmail.com and encrypt it with his [public key](https://keybase.io/bradymiller/pgp_keys.asc?fingerprint=8a93ddec0e320d5eb8a7994827def05b1a8a6d4f) please

will take a look at best practice, thank you!

**Comment by adunsulag** [comment]
I believe we addressed this was fixed here [https://github.com/openemr/openemr/pull/4650](https://github.com/openemr/openemr/pull/4650)
