### ISSUE TITLE
Installation, MySQL openemr user

### ISSUE THREAD

**Issue by chiWahWong** [openemr/openemr#465]
The issue is probably at this step:
![v4 0_5](https://cloud.githubusercontent.com/assets/10159172/22525354/da8e5112-e894-11e6-8058-eb5cea5d17ba.png)

And an error may occur:
https://sourceforge.net/p/openemr/discussion/202506/thread/30e71f7a/

**Comment by MatthewVita** [comment]
Hello @chiWahWong, 

What exactly is the issue?

Thanks,
Matthew

**Comment by chiWahWong** [comment]
Hi Matthew,

The installation cannot be completed with new MySQL user. There are more info in the link.

**Comment by MatthewVita** [comment]
>  I kind of get around the bug by using my root user instead of a new DB user

I have `root` and `openemr` users. You can check this with the following query:

![image](https://cloud.githubusercontent.com/assets/1715206/22574540/75168fa4-e97d-11e6-8b7c-792e2d154bd1.png)

How did you install OpenEMR? You will get `openemr` user "for free" if you install OpenEMR in a Debian environment. If you don't wish to use an installer, you'll need to create this user yourself.

Thanks,
Matthew

**Comment by chiWahWong** [comment]
It does create the new user, but it couldn't complete the install, I also need to go back to the "I have already created a database" option and then use my root user to replace the new user.

**Comment by MatthewVita** [comment]
@chiWahWong,

I see. Just to be clear, the error is "Reconnecting as new user… ERROR. Check your login credentials. unable to connect to database as user: 'openemr' " ?

**Comment by chiWahWong** [comment]
Yep :) :+1:

**Comment by MatthewVita** [comment]
Okay. Next question: what's your OS, PHP, and MySQL version? I would like to attempt to recreate the issue.

**Comment by chiWahWong** [comment]
I'm using Amazon Linux, I guess it is similar to CentOS, PHP is 5.6, MySQL I'm not sure, I guess it should be about 5.7.
I assume the problem is the user authority of the new MySQL user, I have not look deep into the issue, I've only check the user table and I remember that basically all the authority is N. Plus it doesn't seem like a new issue because seem like the same error already happened in 2011.

**Comment by MatthewVita** [comment]
Are you using RDS MySQL on AWS?

**Comment by MatthewVita** [comment]
> I assume the problem is the user authority of the new MySQL user

This is probably it. Please post the results of 

```
mysql> SHOW GRANTS FOR 'root'@'localhost';
```

**Comment by ryannix123** [comment]
Hey Matthew - I'm having the same issue: I'd like to install OpenEMR in a shared hosting environment where I don't have root access. Can we make the installer more generic so that it doesn't either require root or the openemr MySQL user?

**Comment by ryannix123** [comment]
Also - if I was going to "pre-populate" the database during the install, what .sql file in the installer should I use?

**Comment by bradymiller** [comment]
@ryannix123,

**Comment by bradymiller** [comment]
sorry about the above blank post,
@ryannix123 ,

In the installer script, you have option to create the empty openemr database prior to the installation and then choose in Step 1 of installation:
"I have already created the database"

This should bypass the need for mysql root access during the installation. Let us know if that works for you. -brady

**Comment by MatthewVita** [comment]
@chiWahWong Just bumping this issue. Can you run `mysql> SHOW GRANTS FOR 'root'@'localhost';` and post the output?

Thanks,
Matthew

**Comment by willingtone** [comment]
i have such issue it stops at step 3 with

OpenEMR Setup

Step 3

Configuring OpenEMR...

Connecting to MySQL Server... OK.
Creating database... OK.
Creating user with permissions for database... OK.
Reconnecting as new user... OK.

**Comment by willingtone** [comment]
ohh my solution was to increase max_execution_time in php.in file

**Comment by ram94638** [comment]
Reconnecting as new user... ERROR. Check your login credentials. unable to connect to database as user: 

I am facing this issue when openemr working on EC2 and database on RDS MySQL. Please help. What may issue?
