### ISSUE TITLE
Patient Merge SQL 

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#4653]
### Describe the bug
When we try to do a merge this error occur on our system

write concise description of what the bug is.
ERROR: query failed: UPDATE onsite_activity_view SET patient_id = ? WHERE patient_id =?
ERROR: The target table onsite_activity_view of the UPDATE is not updatable.

### To Reproduce

![Resized_20210927_172212](https://user-images.githubusercontent.com/834958/135095208-ed50d0cf-eaa9-42ed-b033-d0cc9b14050f.jpeg)

Try to merge any patient record

### Expected behavior
Record merge

### Client configuration

- Browser: Firefox
- OpenEMR version: 6.0.0 (2)
- Operating system: Ubuntu 20.04 .2
- MySQL : 8.0.26-0

**Comment by juggernautsei** [comment]
I am doing my research on this issue. I watched the video on youtube about views. These are the things that can't be done with a view.
![image](https://user-images.githubusercontent.com/834958/135098449-18eadddc-4cf6-4e6e-afae-e1e3ab618e42.png)
https://www.youtube.com/watch?v=DCp0oFVG_fk

Clearly, in our case, the merge feature is trying to alter the view. The view needs to be excluded. I am trying to figure out how.

**Comment by adunsulag** [comment]
Odd, when did we start trying to update the onsite_activity_view?  We should definitely remove that from the merge code and update the underlying table data.

**Comment by stephenwaite** [comment]
add another `elseif` to [the block](https://github.com/openemr/openemr/blob/master/interface/patient_file/merge_patients.php#L416-L448)

**Comment by juggernautsei** [comment]
I added  

            } elseif ( $tblname == 'onsite_activity_view') {
                //Don't mess with views
            }

We will test and let you know. Thanks!

**Comment by mdsupport** [comment]
If the code is using SHOW, mySQL will include views as tables. Adodb library already provides a filtering mechanism for [metaTables](https://adodb.org/dokuwiki/doku.php?id=v5:dictionary:metatables).

**Comment by juggernautsei** [comment]
this could be changed to 

      $tres = sqlStatement("SHOW TABLES WHERE table_type = 'TABLE'");

This would eliminate and views in the database.

**Comment by juggernautsei** [comment]
> Odd, when did we start trying to update the onsite_activity_view? We should definitely remove that from the merge code and update the underlying table data.

I think this is a side effect of the patient portal being active. If the patient portal is not active then the view would not exist. That leads me to believe that when the merge_patient was developed. It was developed without the portal being active.
