### ISSUE TITLE
OpenEMR Github Topics

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#466]
Topics are here: https://github.com/blog/2309-introducing-topics

I don't have access to do this on the main repo, but here's an example of the topics we could assign to the main repo (this was done on my fork):

![image](https://cloud.githubusercontent.com/assets/1715206/22534513/a1a59328-e8c2-11e6-9017-8df37a1dfb28.png)

**Comment by MatthewVita** [comment]
paging @sunsetsystems and @bradymiller :)

**Comment by sunsetsystems** [comment]
This is like tagging?  Looks reasonable to me.  Let's see what Brady thinks.

**Comment by bradymiller** [comment]
Just placed some tags there. Just let me know if you want me to add something or remove any of them.

**Comment by MatthewVita** [comment]
Thanks guys.
