### ISSUE TITLE
Tracking external providers!

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4662]
### Describe the bug
We create them in imports however, don't give any permissions so new imports can be included in charting, reporting etc. Why?
This may be okay for CCD's where imported data is generally viewed but, not so for QRDA where imported data needs to be available for data manipulations and export.

In realities IMO on a CDA type import the responsible party and responsible organization should be create as external user with associated default facility(responsible organization) and the provider flag set.

Anything wrong with me putting users in view to charting by setting the user provider and active flag on external providers?

@bradymiller @sunsetsystems Would appreciate some guidance here.

Also need to add the 2021 and 2022 reporting period CQM value sets to external loads table.

**Comment by sjpadgett** [comment]
Could a clinician please tell me how a ToC Transition(Transfer) of Care CCDA import should be handled from the charting stand point?
Should the newly created external encounters populate the encounter with the external provider? Currently the user id is correct in form_encounter however, the pull down doesn't populate. Is this important to the clinician? And etc......

Perhaps @robertdown you've dealt with this process in other EHR's. I'd really like to get this right and not only what is useful for ONC.

**Comment by robertdown** [comment]
Don't have much to offer as my experience is the inpatient world where we generate nearly all of our data internally. However, I like the train of thought here and it makes sense. I'd say there is value in understanding the external provider. Sometimes when discussing treatment options with the patient this could come in handy

**Comment by sjpadgett** [comment]
Thanks @robertdown I think I have it sorted. Hopefully my deductive reasoning is still intact.:) Who knows, maybe I'll start  whole new trend in the industry:)

**Comment by sjpadgett** [comment]
FYI, decided to assign a username to external providers w/o password. This allows a natural presence within openemr charting.
Unsure why this was omitted in CCM import so if there is a good reason for the exclusion, now'd be the time to correct me.

**Comment by sjpadgett** [comment]
Decided to import external providers this way as it doesn't aggravated me as much and seems to make sense for user looking at in the future charting. Closing!!

![image](https://user-images.githubusercontent.com/1859985/136598725-95adcc0c-1a6c-44c9-8f9a-41da0468192b.png)

![image](https://user-images.githubusercontent.com/1859985/136598640-561b26fa-d130-4de0-8fb0-5597f932bdcb.png)

**Comment by sjpadgett** [comment]
Yep, an authorized provider has to change the encounter provider(one of the reasons I allowed changing encounters provider awhile back) if mods or extending the encounter.
One of the next items for user changes is to break out change audits for a better reportable audit trail. Something @robertdown brought up to me a couple years ago. lol, I forget my dogs name every other day but somehow remember Robert's comment!!!
