### ISSUE TITLE
Primary billing location bug

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr#4663]
### Describe the bug

Until v6 the default of "Billing Facility" in the new encounter form was the current user facility.
Now the default is always the last facility in the facilities table.

The bug is caused because that all the facilities in our installation are set as billing location (and there isn't  primary business entity) and the query to the database in the Facility service is -  
```
   public function getPrimaryBillingLocation()
    {
        return $this->get(array(
            "order" => "ORDER BY FAC.billing_location DESC, FAC.id DESC",
            "limit" => 1
        ));
    }
```
This function always returns the last record from the table.

### To Reproduce

1. turn on "billing location" in several facilities 
2. validate you don't have a primary business entity in the table
3. you will found the last facility  set as default in the billing facility in the new encounter form for all the users

### Expected behavior
the facility of the user needs to be set as default.

we will be happy to the right and  safe solution as soon as possible, this bug has already been found in the production server and we looks for a safe solution for the situation. 

Thank you!

Amiel

**Comment by adunsulag** [comment]
@matrix-amiel If you want to change it in the encounter form to use the user's facility go ahead and create a pull request and I'll review it.

**Comment by sjpadgett** [comment]
If the default user facility for the encounter provider is a billing facility then yes it should be selected as default billing facility.
However, if not a billing facility but a service location then there is no way to guess what is an appropriate billing facility w/o business entity.

Still in this case with all facilities being set billing then it's a bug however, this did work in v6. Looking at master version it's broken even worst where no facility is being selected on provider change as it should(at least on my test set up).

I don't understand why we don't set a default billing facility in users and avoid these weird queries to guess billing facility and besides, doesn't the billing folks determine where to bill at billing time.
And while I have your attention @matrix-amiel , why did you guys put in the follow up encounters some time back? Do you have reporting on same?

**Comment by matrix-amiel** [comment]
@sjpadgett 
Ok, so for fix in the current version I will add logic that show the default user facility in the case is billing facility.
Agree?

**Comment by sjpadgett** [comment]
@matrix-amiel 
Agreed and should be first choice in the hierarchy of billing facilities IMO. Will you do this from master where I can port back to patch 3?
