### ISSUE TITLE
White page in Firefox & HTTP 500 error on installing fresh openemr in windows

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#4668]
Hi..
I am on windows 11 and I installed fresh xampp with php 8.0.11 and tried installing the most recent dev tip from openemr github account. I have installed the composer and npm and all running fine. Now when I try to run the setup, it gives a white page on firefox and on chrome a http 500 error. php error log shows this:

[Sat Oct 09 22:53:57.662635 2021] [php:error] [pid 11160:tid 1892] [client 127.0.0.1:49721] PHP Fatal error:  Uncaught Error: Failed opening required 'C:\\xampp\\htdocs\\openemr/vendor/autoload.php' (include_path='C:\\xampp\\php\\PEAR') in C:\\xampp\\htdocs\\openemr\\setup.php:98\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\openemr\\setup.php on line 98

please help with this

**Comment by sjpadgett** [comment]
Check your vendor directory permissions and more importantly ensure user acct and group are correct.
If per chance  you've installed composer under root your vendor directory will reflect so check accounts home composer user and/or group permissions.

**Comment by ralflukner** [comment]
Did you check the file permissions and ownership?


----------------------------------
Ralf B Lukner MD PhD
Cell/text 832-248-0780

**Comment by arnabnaha** [comment]
All fixed now...I installed composer in a different directory and after installing it in the main openemr directory and building the dependencies, all is fine. Thank you so much
