### ISSUE TITLE
Modern date(time) picker

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#469]
Been looking for a modern date(time) picker that will support translations within OpenEMR translation engine along with RTL support. Placed a possible solution here:
https://github.com/openemr/openemr/pull/468

If this passes review, then we can begin to convert all old date(time) pickers to this mechanism.

**Comment by bradymiller** [comment]
Just brought in above PR that brings in main files and conversion to new datepicker on most reports. This will an ongoing project which will track here as walk through the entire codebase and convert to the new datepicker.

**Comment by MatthewVita** [comment]
Looks nice! Just added this to the Modernization board: https://github.com/openemr/openemr/projects/2

**Comment by bradymiller** [comment]
Just committed another batch. Reports are done. Now plan to update it in all the other scripts (guessing about 50 or so).

**Comment by bradymiller** [comment]
Just updating this code walk through is still happening. Here is most recent change:
https://github.com/openemr/openemr/commit/68ea6489dea41c6f4b86202b51b157ad49cf8654

**Comment by bradymiller** [comment]
Just completed this project. Last commit for this is here:
https://github.com/openemr/openemr/pull/990
