### ISSUE TITLE
Federal Drug ID

### ISSUE THREAD

**Issue by chiWahWong** [openemr/openemr#470]
There is Federal Drug ID for user, and I see Federal Drug ID appears else where in the app. Is the Federal Drug ID for user actually DEA number instead of Federal Drug Identification Number?

**Comment by bradymiller** [comment]
Hi @chiWahWong 
Yes, this is the DEA number(if this is turned on in Administration->Globals->, then it will be included on the Rx as the DEA number).
-brady

**Comment by chiWahWong** [comment]
Hi Brady,

Should we change "Federal Drug ID" to "DEA number"? Like the add user form, it has Federal Drug ID, it took me some time to figure out what it actually is.

**Comment by bradymiller** [comment]
Sounds reasonable. Will need to be changed on the User Add and User Edit forms. Are you able to place a PR for this? (if not, I can make this change)

**Comment by chiWahWong** [comment]
I am sorry I couldn't help this time. I sincerely apologize.

**Comment by bradymiller** [comment]
fixed by @kacyw , so closing this issue
