### ISSUE TITLE
Add split claims to billing.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4707]
### Describe the problem
New feature.
A billing scenario: An encounter being billed has several procedures that needs to be billed to one insurance company with others to another, say primary for one set and secondary for another.

While for openemr billing, one encounter, one claim so, this needs to be more granular.

### Describe the solution you'd like
To start, current plan would be to allow procedure destination for claim from fee sheet. Next step would be to combine multi encounters in claims etc...

I'm still deciding best path but thought I'd put it out there for comments.

**Comment by stephenwaite** [comment]
thank you @sjpadgett, one of the common scenarios is one or a few of the line items (procedure codes) in a claim are denied and the biller only needs to submit one or a few of them instead of the entire claim or a corrected claim.

**Comment by sjpadgett** [comment]
That'd be on reconciliation side. So it'd be a resubmit as new claim to differ insurance, correct?

**Comment by stephenwaite** [comment]
ok, it'd be in the billing manager
