### ISSUE TITLE
Layout Editor save broken

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4720]
### Describe the bug
When saving any layout the result changes label column and data columns to 1 0 respectively. Unknown at this time if over writes in tables or just a display issue. Perhaps something to do with new additions on code(s). Also we need to address breaking up the single row edit line into a view that is more user friendly.

Before save

![image](https://user-images.githubusercontent.com/1859985/140631956-e497b32d-ed35-421c-b754-52c5ee1e3177.png)

After:

![image](https://user-images.githubusercontent.com/1859985/140632182-f196c220-56c4-425e-8e5f-7e123950f6fd.png)

### To Reproduce
Edit any layout and save.

Fails on dev demo which is a couple weeks behind master.

**Comment by sjpadgett** [comment]
yep, overwrites layout_options. upgrading issue to blocking

**Comment by bradymiller** [comment]
whoa! confirmed bug. Hope it wasn't from me adding the Code(s) column.

**Comment by bradymiller** [comment]
btw, here's what the new patient demographics form looks like after save the layouts:
![image](https://user-images.githubusercontent.com/278968/140633651-891760d0-bc58-40c0-b909-fd8f218685dd.png)

**Comment by sunsetsystems** [comment]
Make sure max_input_vars is a big number. Like 10,000 or so.
Otherwise my last change to the layout editor was back in May....

**Comment by sjpadgett** [comment]
It's the new codes field. @bradymiller ya forgot to change the name attribute from datacols to something unique.
`echo "<input type='text' name='fld[" . attr($fld_line_no) . "][datacols]' id='codes_fld[" . attr($fld_line_no) . "][datacols]'`

So is overwriting previous datacols on post. easy fix.
`echo "<input type='text' name='fld[" . attr($fld_line_no) . "][codes]' id='codes_fld[" . attr($fld_line_no) . "][codes]' `

**Comment by sunsetsystems** [comment]
Jerry, nice catch!

**Comment by sjpadgett** [comment]
Thanks Rod. Brady you want me to add a PR or do you want to fix in you bug fixes PR?

**Comment by bradymiller** [comment]
thanks @sjpadgett ! I'll bring the fix in with my PR.
