### ISSUE TITLE
Broken Scrolling

### ISSUE THREAD

**Issue by kchapple** [openemr/openemr#4732]
### Describe the bug
Some point recently, OpenEMR's ability to scale within a browser window was broken.

When scaling the browser window between break-points, the content renders off screen, and there is no way to scroll to the right to see the hidden content. Previously, if the main menu (top menu) had many elements, it would stretch the content window beyond the field of view of the browser, but the user was able to scroll to the right to view hidden content.

### To Reproduce

Old EMR (ability to scroll right)

![Screen Shot 2021-11-10 at 9 32 07 AM](https://user-images.githubusercontent.com/271809/141132289-b45012e9-5a16-4d0e-a58c-410844619296.png)

New EMR (cannot scroll, content not visible and cannot access User's "logout" button)

<img width="1314" alt="Screen Shot 2021-11-10 at 9 24 46 AM" src="https://user-images.githubusercontent.com/271809/141132334-4a547839-48ad-45de-a883-9e849df6452d.png">
### Expected behavior

User should be able to scroll to see hidden content

### Client configuration

- Browser: FF
- OpenEMR version: Master
- Operating system: Mac Big Sur

**Comment by sjpadgett** [comment]
@kchapple Top nav needs to be cleaned up again as too many items and for some reason causes scroll-x regardless of viewport width.
So I turned scroll x off until 992 breakpoint.
interface/main/tabs/main.php L-280

I can put back but really top nav needs to be looked over again.

**Comment by sjpadgett** [comment]
@robertdown Any thoughts on this. In reality we should never need scroll x I think. Top nav does break to button at break point md I believe but still will hide right widgets when most all menu items are fully enabled on full screen.

**Comment by sjpadgett** [comment]
I can get to around 1280 viewport then scroll or move search back to where it was. I like it in nav bar so user can search with patient bar collapsed.
![image](https://user-images.githubusercontent.com/1859985/141175017-3d835553-e0e2-4cdf-9206-3d056167a72e.png)

**Comment by robertdown** [comment]
I agree, we should not be x-scrolling, however, that means we address the actual issue.

Couple of options I see here:
1. Add back x-scroll (a bandaid)
2. Remove the infinity circle logo from the menu (I actually have a PR with that as a global option coming soon)
3. Have the search box start hidden and be exposes on hover or on button click or on keyboard shortcut. I know I moved the search bar from the Patient Banner Bar to the menu but I still do not like it's placement.
4. Drop the About page from the menu
5. Translate Miscellaneous to "Misc."
6. Translate Administration to "Admin"

Of note, this is the worst-case scenario, an admin with every possible menu item is running into this problem. What does this look like to clinical users who maybe don't have the Amin option.

**Comment by sjpadgett** [comment]
Yep also the padding for menu items is 10px so I trimmed to 2. Big help. The Admin User drop has a ml-5 so I removed. I'll go ahead and finish since I started already.
I'll move About to Administration or Misc
Rename Miscellaneous to Other stuff we didn't know where to put:) or Tools or Misc
Rename Patient/Client to just Patient
Will look into hover

and on. Thanks Robert.

**Comment by bradymiller** [comment]
Wouldn't assume we have control over menu label lengths (internationalization) or number of items (custom menus), so would shoot for something that works for the worst case scenario times three.

**Comment by sjpadgett** [comment]
True. Then we really need to move search back to where it was. I have that done so I'll test with other changes for padding and margins

**Comment by robertdown** [comment]
I agree we don't have total control, but at some point it's out of our hands

**Comment by bradymiller** [comment]
David brought this up on one of the recent calls. Is there a way to allow the menu to go to multiline or is that not possible?

**Comment by sjpadgett** [comment]
It'd require moving from using flex rows and columns to a grid I think.

**Comment by robertdown** [comment]
The actual solution here would be javascript logic that does some math to determine the viewport width and then to see if the menu is exceeding that. If so, the menu item container gets max-width'd to a spot where everything fits and the overflowe'd content gets a right chevron which slides the menu to the left (within the container) allowing infinite scrolling

**Comment by sjpadgett** [comment]
Nav works fine when we hit breakpoints it's these weird viewport sizes that gets use I think

**Comment by robertdown** [comment]
Very similar to what FF and Chrome do on their tabs - go try it in the browser, open a bunch of tabs and then make the window smaller and you'll see a little arrow appear.

**Comment by sjpadgett** [comment]
I've never had good luck calculating viewport across different browsers.

**Comment by sjpadgett** [comment]
This fixes fairly well and will now collapse correctly at breakpoints. so it's as far as I want to take for now! This is 1228 width any smaller will collapse.

![image](https://user-images.githubusercontent.com/1859985/141189683-690599a3-0485-45d3-944d-64bdd2d7b5f6.png)

**Comment by sjpadgett** [comment]
I'm holding unto this to give more thought. May do some demo edit styling fixes also.

**Comment by kchapple** [comment]
My 2 cents, I think x-scroll is a reasonable solution.

**Comment by robertdown** [comment]
x-scroll kicks the problem down the road. Would be better to solve now... Says the guy not actually solving the problem :)

**Comment by sjpadgett** [comment]
Actually, one should never see x-scroll if page is responsive. Problem was on some viewport sizes between breakpoints, we'd get x-scroll. We now will collapse correctly so shouldn't see a x-scroll. Exception on light on initial load sometimes Patient Finder shows a scroll but stops on a refresh. Might need to look at Patient Finder a little closer.
Next time I look at will make our topnav across all themes the same pad and margins styles.
