### ISSUE TITLE
Layout Based Form Validation Failure

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#4735]
### Describe the bug

An LBF that requires a Text-date field will save with an empty field

### To Reproduce

1. Create a new LBF Layout
2. Add a Group
3. Add a new field
4. Set UOR to Required
5. Set Data Type to Text-date
6. Save form
7. Open form
8. Leave text field blank
9. Save form

### Expected behavior
Form is not submitted

### Client configuration

- Browser: Firefox
- OpenEMR version: Master
- Operating system: Flex Docker

**Comment by sjpadgett** [comment]
Yep. Though it may fail the validation there is a timer that closes the form before the error is reported. It's a bug.
