### ISSUE TITLE
LBF Description as Placeholder instead of actual Text

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#4737]
One of the options in the Layout Builder is "Description is Default Text" which injects the description as the text of the input field. What is the collective thought on changing that functionality to injecting the description as the _placeholder_ instead of the actual text. 

If the consensus is static default text should remain I'll just add another option, either "Use Label as Placeholder" or "User Description as Placeholder" and go from there.

I'm leaning towards adding another option, I just worry about option bloat.

@bradymiller @sjpadgett @sunsetsystems

**Comment by sjpadgett** [comment]
I'd just use the description for placeholder as title is done.

**Comment by sunsetsystems** [comment]
Another option please. We have cases where saving the data matters.

**Comment by robertdown** [comment]
Pulling in #4738 which introduces another option
