### ISSUE TITLE
New User Created By Administrator with default Administrator group does not get group added

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4760]
When adding a new user as an Administrator it default selects Administrators as the default group.  If you save the new user without selecting the 'Administrators' group or any other group it will add the user without any groups attached (even though the Administrator) group was selected by default.

The new user will not be able to login until a group is added.

**Comment by stephenwaite** [comment]
Thanks for the bug report @adunsulag , you mean that when you somehow are crafty enought to deselect any choice in the `Access Control` dropdown from Administration->Users->Add User? Like in this snippet of the screen: 
![Screenshot from 2021-12-25 13-00-49](https://user-images.githubusercontent.com/5618372/147390928-ab37e1b7-6be8-4a7b-9cb1-62b3ce254c8a.png)

Maybe this is possible in the installation as well...
