### ISSUE TITLE
edit acl admin user memberships 

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#477]
this fails for usernames with special characters, like the space in the attached file, can't edit dr test :(

![untitled](https://cloud.githubusercontent.com/assets/5618372/22708841/c9fc3ff2-ed45-11e6-82d2-3208763c5399.png)

guessing this jquery can't handle the special characters:
https://github.com/openemr/openemr/blob/master/interface/usergroup/adminacl.php#L216

**Comment by mdsupport** [comment]
Better to use numeric 'id'.  If not, here is relevant [jQ documentation](http://api.jquery.com/category/selectors/) to handle meta-characters.

**Comment by bradymiller** [comment]
Fix for this has been posted here: https://github.com/openemr/openemr/pull/1448

**Comment by bradymiller** [comment]
Above fix was brought into codebase so closing this issue.
