### ISSUE TITLE
installing after customization

### ISSUE THREAD

**Issue by rahulteja526** [openemr/openemr#479]
Hi,
I installed OpenEMR on my localhost and customised in code level according to my clinic. Now I want to install this onto a hosted server along with my database. What are the steps do I have to follow to install and run on my production server.

Thanks in advance.

**Comment by mdsupport** [comment]
1. Follow standard/generic install on new server - preferably using same zip/tar file.  Make sure to use same web directory structure and os+mysql user+passwords. Test to make sure install works by adding a patient or any other functions.
2. Use backup menu option to create a complete database backup.
3. Copy entire web directory from local to hosted.
4. Overwrite db by backup from step 2.
5. Test data and your changes.

**Comment by rahulteja536** [comment]
Thanks for the reply. But, I followed another procedure. 
1. I have changed config value to '0' in sqlconfig located in sites/default.
2. I put that zip file on my server and when that folder is accessed, I got the same installation procedure.
3. I uploaded the BackUp DataBase to DataBase( which is created at time of installation).

**Comment by mdsupport** [comment]
Good for you.  Enjoy.
