### ISSUE TITLE
Occasional Globals corruption on save.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4804]
### Describe the bug
@adunsulag first saw this a month or so ago when I then encountered a couple days later.
I believe has something to do with session timeout/corruption.
The result appears that data is deleted but never written and seems to happen somewhere in the globals save. 
The symptom after is user can't log in causing user to embark on a mission to overwrite secure password. A frustrating adventure no doubt!
The only solution to issue is import globals from backup or anew from default database.

My solution will be to a least prevent the corruption to table by wrapping global save in a transaction to revert.
This of course relies on an exception, redirect or fatal error that breaks out of the save routine.

**Comment by mdsupport** [comment]
What kind of issues do we expect if globals are saved by ajax call on field change?

**Comment by sjpadgett** [comment]
@mdsupport None I can think of...
