### ISSUE TITLE
Make the name fields more clear in demographics new/edit patient layout

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#4835]
In master can be confusing what all the name fields are (ie. which is fname etc)

**Comment by stephenwaite** [comment]
at least hover will reveals the field name

![Screenshot from 2022-01-15 15-32-03](https://user-images.githubusercontent.com/5618372/149636835-cf202468-c0ed-4c96-89f2-c75e0db9a2e9.png)

**Comment by sjpadgett** [comment]
see https://github.com/openemr/openemr/pull/4839

**Comment by sjpadgett** [comment]
done
