### ISSUE TITLE
"RA for Patient, Encounter, or Trace" option not working in EDI History module

### ISSUE THREAD

**Issue by msahasrabuddhe** [openemr/openemr#485]
I am trying to use the 'ERA Files' section of 'EDI History' module and here is what happens:

1. I upload an ERA file in the 'View an x12-835 ERA file' field, and the file is displayed correctly.
2. I upload ERA files into the /tmp/edihist directory and try to search with Patient ID and Encounter in the 'RA for Patient, Encounter, or Trace' filed, and I always get a 'Did not find <pid>in data' error.

Is #2 some defect or is this something I am doing wrong in the setup?

**Comment by bradymiller** [comment]
oops, didn't mean to close this. just re-opened it.

**Comment by stephenwaite** [comment]
did you click on process new files?
![untitled](https://cloud.githubusercontent.com/assets/5618372/23687532/e7cdfb7c-037c-11e7-939a-3ce9f3481764.png)

see this thread for more info:
https://sourceforge.net/p/openemr/discussion/202504/thread/e5d89705/?limit=25#4ed9/faa0

**Comment by msahasrabuddhe** [comment]
Thanks. That made sense!
