### ISSUE TITLE
Logout from expired session

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#4855]
The (in)famous 'Site ID' message was addressed in #1534. 

To reproduce, let session expire or get closed. Then try to use 'Logout' dropdown option from menu.

Noticed that logout.php does get called but user gets no response possibly because changes to auth library resulting in login.php never getting called.

This was a decent compromise to users having to enter emr link in address bar.

**Comment by mdsupport** [comment]
Thought composer/PSR-4 autoloader corruption was the issue. But looks like it is not.

To reproduce in demo setup:
1. Without prior logins, go to : https://one.openemr.io/a/openemr/interface/logout.php
2. You will get no response (because of `PHP Fatal error:  Uncaught Error: Class 'OpenEMR\Common\Logging\SystemLogger' not found in /src/Common/Session/SessionUtil.php:133`)
3. Now login to demo installation
4. Enter exact browser request from Step 1 : https://one.openemr.io/a/openemr/interface/logout.php
5. Logout will be processed and you will get login screen.
6. Now enter same request : https://one.openemr.io/a/openemr/interface/logout.php
7. Again login screen is presented.

Problem with cookie management part of SessionUtil?

Changes in #4938 do resolve the issue although as pointed out by @adunsulag they do not make sense since autoloader does have the class entry.

**Comment by mdsupport** [comment]
Just a suggestion in case someone wants to address this.

Root cause is in this specific situation, SessionUtil is getting called before/without globals including the autoloader.

In our experience autoloader has no preconditions and is almost always the first statement.

Here is the start of our globals.php that resolved this issue.

```
 * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 */

/**
 * mdsupport - Customization
 * 
 * 1. Centralize standard directory structure pointers based on this __FILE__
 * 2. Make directory variables that are friendly for new developers.
 */
$osProjRoot = dirname(__FILE__, 2);
// Project Directory structure
$osProjInterfaceDir = "$osProjRoot/interface";
$osProjLibraryDir = "$osProjRoot/library";
$osProjPublicDir = "$osProjRoot/public";
$osProjSitesDir = "$osProjRoot/sites";
$osProjPSR4Dir = "$osProjRoot/src";
$osProjVendorDir = "$osProjRoot/vendor";

// Pull in autoloader
require_once ("$osProjVendorDir/autoload.php");

// if (strpos($_SERVER['REQUEST_URI'], 'dated_reminders_counter')) {
```

Hope this helps someone.

**Comment by bradymiller** [comment]
@mdsupport ,
Thanks for bringing this up. SessionUtil needs to be called prior to globals to work out sessions in scripts that use both the portal and core openemr. So, it really needs to be self-sufficient. I think  best thing to do would be to remove the SystemLogger use in that class. @adunsulag , thoughts on this; it is nice to have those debug statements, but in this case seems simpler to remove and not figure out how to bring in these classes outside the autoloader to support just the SessionUtil class.
