### ISSUE TITLE
form_bronchitis

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#4864]
Recently a database restore terminated when creating 'form_bronchitis'. While checking the root cause and status in latest codebase, it appears every element in the table is 'text' or 'longtext' - something probably done just to make the install work. Most of the fields in the included form are checkboxes being stored as text. There is a list of ICD9 codes hard coded in the form as well.

It looks like this is a 'contrib' form that moved to standard forms directory and clearly needs work on multiple fronts to match other forms.

**Comment by sjpadgett** [comment]
Anyone know why we moved this form?

**Comment by mdsupport** [comment]
Stand corrected. [Initial commit](https://github.com/openemr/openemr/commit/8fd94aedc83d3c861e2705779e86ae5749802ebc#diff-752fd7b827f247b84f217a10f501342d6842eb476137810c79f479be4471f09a) is from 2005. 

Wonder why all these years after rollout of ICD10, no complaints about the ICD9s in this form!
