### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#4868]
```
OK: 932 MiB in 271 packages
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/openemr/oe-cqm-parsers.git
npm ERR! ssh -oStrictHostKeyChecking=accept-new: line 1: ssh: not found
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-01T22_20_24_660Z-debug.log
Running quick setup!
```

@sjpadgett @kchapple , looks like related to cqm stuff

**Comment by bradymiller** [comment]
looks like related to build now requiring ssh to be installed. is there a way to avoid that dependency on the build machine?

**Comment by bradymiller** [comment]
currently both the docker dev environments and the dev demos will not work :)

**Comment by sjpadgett** [comment]
didn't have issue with build before or after PR. Will look at in a min...

**Comment by adunsulag** [comment]
So I'm confused, can't we just switch this line https://github.com/openemr/openemr/blob/6c018f4d9a60e1c069163374d2b677f641394a09/composer.json#L89

To be vcs instead of git?  I'm also not sure why the repository is in composer but we don't reference the package at all in our dependencies, or maybe I'm missing something in the composer.json.

**Comment by bradymiller** [comment]
Looks like is an npm issue where it needs ssh when grabbing the oe-cqm-parsers.git package directly from github.

**Comment by sjpadgett** [comment]
hmm unsure why we need parser. thought was removed and brought in with service. i'm looking at.

**Comment by stephenwaite** [comment]
thought we're using napa to handle these remotes if it's not an npm package

**Comment by adunsulag** [comment]
I think we can change this line here: https://github.com/openemr/openemr/blob/6c018f4d9a60e1c069163374d2b677f641394a09/package.json#L101

and change it to this:
```
oe-cqm-service": "git+https://github.com/openemr/oe-cqm-service"
```
To force it to use https instead of ssl.  Another option is to set the git config on the build machines to force https instead of ssl/git protocol.

**Comment by stephenwaite** [comment]
maybe we can try that with some of the napa's since that's throwing errors in the build too

**Comment by sjpadgett** [comment]
umm I don't have issue with build on windows or apparently mac.
napa has been throwing errors for awhile now. and these would not pertain to napa and they are pulled in as project via npm.


> To be vcs instead of git? I'm also not sure why the repository is in composer but we don't reference the package at all in our dependencies, or maybe I'm missing something in the composer.json.

This is in composer as a repository pointer for admins to composer require when needed to build new patient models. 
vcs vs git, possibly. i've always used vcs however, shouldn't matter in the end.

If there is an issue then would be with the oe-cqm-service install with is where the oe-cqm-parser dependency is required.
https://github.com/openemr/oe-cqm-service/blob/main/package.json

**Comment by sjpadgett** [comment]
It's kind of fun to see stuff working on windows and you docker guys get to be bewildered a bit!:)

**Comment by sjpadgett** [comment]
Let me know what I need to fix as I will test and bring in with my current PR.

**Comment by bradymiller** [comment]
git+https://github.com/openemr/oe-cqm-service didn't work, possibly since github:openemr/oe-cqm-parsers is in the composer.json of oe-cqm-service .
(supporting ssh in all the dev dockers and demos will be a heavy lift and would rather not bring in ssh in the dockers anyways)
Can we make these standard npm packages?

**Comment by bradymiller** [comment]
btw, looks like i have a npm account with oe-blue-button in it (guessing Jerry set that up). I can figure out how to add these packages to npm and then this issue will resolve.

**Comment by sjpadgett** [comment]
I'll can add the package @bradymiller . Though unsure if will work as it is a pointer to our repository.
give me a minute to remember my password:)
However composer should not be at issue at all. parser if brought in via a oe-cqm-service, a package
Let me look into a minute.

**Comment by sjpadgett** [comment]
@bradymiller can you try replacing 
`
"oe-cqm-service": "github:openemr/oe-cqm-service"`
with
`
"oe-cqm-service": "openemr/oe-cqm-service"
`
in package.json

**Comment by bradymiller** [comment]
@sjpadgett , tried that and still having same issue (ie. trying to use ssh, which is not supported)

**Comment by sjpadgett** [comment]
Okay let me modify the service package

**Comment by sjpadgett** [comment]
@bradymiller I modified service. This should fix if not i'll add package to npm

**Comment by bradymiller** [comment]
@sjpadgett , still having the missing ssh issue, could try `git+https://github.com/openemr/oe-cqm-service` in the service, may get lucky

**Comment by bradymiller** [comment]
oops, meant to try `git+https://github.com/openemr/openemr/oe-cqm-parsers` in the service

**Comment by sjpadgett** [comment]
where at? in the dependencies because I removed the repository reference as it should not be needed for npm.current json
```
{
  "dependencies": {
    "compression": "^1.7.3",
    "cqm-execution": "^3.0.3",
    "express": "^4.16.3",
    "winston": "^3.0.0",
    "oe-cqm-parsers": "openemr/oe-cqm-parsers"
  },
  "deprecated": false,
  "license": "MIT",
  "main": "server.js",
  "name": "oe-cqm-service",
  "scripts": {
    "start": "node server.js"
  },
  "version": "1.0.0"
}

```

**Comment by bradymiller** [comment]
could try a hail mary by changing above `openemr/oe-cqm-parsers` to `git+https://github.com/openemr/openemr/oe-cqm-parsers`

**Comment by sjpadgett** [comment]
okay. give a minute..

**Comment by bradymiller** [comment]
good catch, bad link on my part, crossing fingers :)

**Comment by sjpadgett** [comment]
okay @bradymiller

**Comment by bradymiller** [comment]
hail mary failed. on a positive note, the packages now get to be promoted to npm packages and we all get to learn how to use npm package repo :)

**Comment by sjpadgett** [comment]
I'll go setup the package on npm and fix the service. give me a bit...

**Comment by sjpadgett** [comment]
bare with me almost there..

**Comment by sjpadgett** [comment]
@bradymiller I'm still testing but add `"oe-cqm-service": "1.0.0"` to package.json and try. I also added service oe-cqm-parser to npm published and the service package.json. 
We may need to setup diff authentication if this doesn't work.

**Comment by sjpadgett** [comment]
Okay moving service and parser to published npm is working for me on windows.
I hope works for you @bradymiller  as I'm wiped out and want to eat my one cookie allowed per day (rather be a beer) then go to bed!:)
Don't want to leave you hanging though if this doesn't work....

**Comment by bradymiller** [comment]
Still getting ssh error, and the packages on npm are a bit odd. If I can have access to them on npm (like the blue button one, I can try some things out)
```
[20:28][brady2@pop-os:/var/www/openemr]$ npm show oe-cqm-service

oe-cqm-service@1.0.0 | MIT | deps: 5 | versions: 1

dist
.tarball: https://registry.npmjs.org/oe-cqm-service/-/oe-cqm-service-1.0.0.tgz
.shasum: f61f864d8e9fad0483a68ee92a41706c5e4a8c76
.integrity: sha512-7hfAH4Z3f5bZfUcU8cpEL81i3LUq8XrYO1MrfwqWIBzQ/0Hk7ylcQbXw7wnldxLV81d+B4dlxW9Qi/kzc6Pd+A==
.unpackedSize: 7.0 kB

dependencies:
compression: ^1.7.3                                               oe-cqm-parsers: git+https://github.com/openemr/oe-cqm-parsers.git 
cqm-execution: ^3.0.3                                             winston: ^3.0.0                                                   
express: ^4.16.3                                                  

maintainers:
- sjpadgett <sjpadgett@gmail.com>

dist-tags:
latest: 1.0.0  

published 55 minutes ago by sjpadgett <sjpadgett@gmail.com>
```

```
[20:28][brady2@pop-os:/var/www/openemr]$ npm show oe-cqm-parsers

oe-cqm-parsers@5.5.0 | Proprietary | deps: none | versions: 1
git clone https://github.com/openemr/oe-cqm-parsers

dist
.tarball: https://registry.npmjs.org/oe-cqm-parsers/-/oe-cqm-parsers-5.5.0.tgz
.shasum: bb5175965e3b3e5a8287749dc2dbc521c068d093
.integrity: sha512-JOVEFkh4WUlpKb584nATLlIZWeA4mjfntnjNZtchyE13KcFFsRg1Sa65xDYJWs9H3E8xhuq9sHuuCwIpvvmrZA==
.unpackedSize: 40.6 MB

maintainers:
- sjpadgett <sjpadgett@gmail.com>

dist-tags:
latest: 5.5.0  

published 52 minutes ago by sjpadgett <sjpadgett@gmail.com>
```

**Comment by sjpadgett** [comment]
I sent an invite. I don't see a way to add you any other way until I move packages to organization.

**Comment by bradymiller** [comment]
cool, i can see them on npm. Always wanted to see how the npm stuff worked. i'll try not to break anything :)

**Comment by sjpadgett** [comment]
actually, I just don't think we need parser in service for calculator but for gen'ing model in our tool module. I need to re figure this out!
Also Brady if need to republish need to delete packages in npm and publish from command line.

**Comment by bradymiller** [comment]
got it fixed to build
Didn't want to delete the npm package since worried may lose the namespace (now that npm is being more secure would hate to lose the namespace and dig a deeper hole), so:
1. incremented oe-cqm-service to 1.0.1
2. pointed the oe-cqm-service dependency oe-cqm-parsers to 5.5.0 (for some reason this is the version is it on npm)
3. in oe-cqm-service repo, added 1.0.0 and 1.0.1 tags to keep with the npm versions

**Comment by sjpadgett** [comment]
cool Brady. I see what happen now with parser version. seems a quirk to me but I'm going to bed. thanks...

**Comment by bradymiller** [comment]
night and thanks for helping out us docker folks :)
