### ISSUE TITLE
FacilityService Fatal Error

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#4869]
FacilityService getById dies with empty id  

### To Reproduce
Go to demo
Modify demographics
Pick one of the user fields
set type to Facilities
Save
Select a patient
Dashboard is not displayed.

### To Fix
Line 144 of facilityservice can log the error but should return null.

**Comment by sjpadgett** [comment]
thanks @mdsupport i'll see if I can't get in my current PR

**Comment by sjpadgett** [comment]
Works on current master.
