### ISSUE TITLE
OpenEMR Demo does not work

### ISSUE THREAD

**Issue by Davis965** [openemr/openemr#4871]
OpenEMR online does not work;

https://demo.openemr.io/openemr/interface/login/login.php?site=default

This seems like a server error.

Would you please report this issue to the technical team.

Best regards,

02.02.2022, 12:50 PM EST

**Comment by stephenwaite** [comment]
hi @Davis965 , repair in progress...

**Comment by stephenwaite** [comment]
Demos are restored!
