### ISSUE TITLE
Refactor all Symfony dispatched events.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4872]
### Describe the bug

`Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3`

Need to flip the first two arguments in EventDispatcherInterface::dispatch().

**Comment by robertdown** [comment]
Had an issue when I attempted this on a small scale. @adunsulag might remember more details - I think it had to do with a version mismatch on the new EventDispatcher

**Comment by sjpadgett** [comment]
If I remember right from when I looked into this a year or so ago, Symfony dispatch will show the deprecated error and continue by flipping the args so downstream will work. The two I've refactored by flipping worked so I figure all should work by doing the same.

**Comment by robertdown** [comment]
Bump

**Comment by robertdown** [comment]
@sjpadgett So are we a go on this now? Probably easy enough to knock this out.

**Comment by sjpadgett** [comment]
Sure if you want to tackle.

**Comment by bradymiller** [comment]
was forced to fix this :)
https://github.com/openemr/openemr/pull/6012
