### ISSUE TITLE
Restyle new install demographics and current Insurance

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4883]
### Describe the bug
Title says it all.
Both required change for better UX.

**Comment by stephenwaite** [comment]
![popeye](https://user-images.githubusercontent.com/5618372/152819984-76a9d350-90ff-41f9-97ec-c93debf899ef.gif)

**Comment by sjpadgett** [comment]
man, new comprehensive insurance would require a complete restyle. may wait for @robertdown to twigify.

**Comment by robertdown** [comment]
Agree, the demographics is a high priority UI fix on my list.

**Comment by sjpadgett** [comment]
@robertdown I have demographics LBFs looking the best I can until we attack following through with the scheme Rod started.
The new patient comprehensive input is LBF and looks good. It's the new comprehensive insurance that are BS forms that would be my choice to be twigified next if possible. The demographic insurance form looks pretty good where I think Tyler spent time to get that one right. One of the students did the comprehensive insurance form.

I just don't want to spend two days restyling comprehensive when I know you want to twigify those.
What you have done so far has been a 100% improvement and the more I test, the more I'm excited by next release. Again, another great release by our team.....

**Comment by bradymiller** [comment]
little late to the party, but:

![signal-2020-11-19-220815](https://user-images.githubusercontent.com/278968/152944759-a8e19d99-4bb2-4cda-83fd-16ad76ec443e.gif)
