### ISSUE TITLE
Secure Direct Messaging fails due to Document whitelisting when a document is transmitted.

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4888]
Currently there is a bug in the EMRDirect receive process which fails if an unknown mime type is found for a Direct document.  Default OpenEMR installations by default have a restricted set of mime types allowed that is contained in the Administration -> Forms -> Lists -> Files type white list.  However, for receiving Summary of Care documents and other referral type documents (ccr, ccda, xdm, etc) via Direct these files automatically fail as they are not in the allowed mime types.  There is no error reported and the entire direct receive fails using EMRDirect with no ability for a user to diagnose why they are not getting their direct secure emails.

There are a couple ways we can fix this:

- Skip the mime type checking when a file is received via EMRDirect.  @matrix-amiel added the white list code into here so perhaps they can chime into the security ramifications of pursuing this route.  This option assumes that a file received by EMRDirect is safe and can be used inside the EMR.
- Allow the files to be received but put them into some kind of quarantine until they've been reviewed / approved by a user or admin.  This would be necessary if we think that the EMR could be compromised by a file received by a direct user.  OpenEMR doesn't do any virus / file scan checking anyways so going solely off the mimetype can be decieving as a file's mime type can be masked if an attacker so chose to do so.
- Another option is to add specifically the mime types that are required for ONC ETT testing (xml, xdm zip file, etc) to the approved list but that doesn't solve the problem of EMRDirect failing when the mime type is not known.
- Reject the Direct message and send a message to the user or site admin that the file is not in the accepted white list and to review the file in their EMRDirect web portal and if appropriate add the correct mime type to the mime type white list.

The easiest approach will likely be to just skip the mime type filter for EMRDirect and trust that the file is allowed by the EMR which is the approach we are pursuing for certification.  If this is a problem, @matrix-amiel or others please chime in.

**Comment by bradymiller** [comment]
Would lean towards first option for now. Note the files will be encrypted on the drive, which will prevent shell script shananigans. Since this seems like email on steroids is there potential for spam via Direct? May make sense to make it visually apparent which documents were collected via Direct on the Document gui.

**Comment by adunsulag** [comment]
@bradymiller I think there could be the potential for SPAM but there's a pretty high barrier to entry as senders are directly connected to an NPI and have to go through a HISP approved network.  I imagine if people start sending spam they would get blocked pretty quickly.  I do like the suggestion of marking documents in some way to indicate it came from direct.

**Comment by adunsulag** [comment]
@bradymiller So my latest PR fixes the document whitelisting issue.  I didn't touch the labeling files as a Direct documents.  I noticed that Direct already prefixes documents with a 'dm-' in front of them when they are stored inside of OpenEMR.  Do you think this is good enough? I could store them into their own category but I wasn't sure if that would be confusing for people.

**Comment by bradymiller** [comment]
If the names are prefixed with `dm-` then we are good to go in that regard :)
(agree a category would be confusing since those are meant for categorizing document material rather than where they came from)

**Comment by adunsulag** [comment]
I discovered that the document white listing fails if the local operating system's mime type detection on the document is different than the mime type received via direct.  This was discovered with a CCDA xml file.  EMRDirect was sending a mime type of application/xml mime type and the local OS detected it as text/xml.  This breaks our current solution as we temporarily allow the EMRDirect mime type if it matches the document mime type and then we remove the temporary bypass.

Since we don't want to build a file quarantine process we will just go with our original approach and bypass the mime type check altogether during the document storage process. The files are protected on the drive as is.
