### ISSUE TITLE
Embed EMRDirect public certificates into the EMR at the time of installation

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4889]
Currently users wanting to use EMRDirect for Secure Direct Messaging have to download a certificate and store it in the sites directory of the OpenEMR installation which is cumbersome for less technically savvy users.  In order to make it easier for installation we should download the public & testing certificate at the time of installation.  We should have a global flag to set Direct to use test mode or the production flag.

**Comment by bradymiller** [comment]
Would it make sense to include these in the codebase at something like `public/certs` directory or something like that. Then no compromise can happen during download process of the certs.

**Comment by adunsulag** [comment]
@bradymiller I'm fine with doing that, just was thinking that it might be best to grab whatever is the latest copy.  However, if we bundle it we mitigate any supply chain attack.  The downside is if they issue a new certificate in between our release cycle.  Users are having to manage this themselves anyway so its definitely simpler if we just bundle it into the cert folder.
