### ISSUE TITLE
Continuous Integration First Steps

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#489]
While the Modernization project is ongoing, it seems like a good idea to start to work on setting up CI.

> Continuous Integration (CI) is a development practice that requires developers to integrate code into a shared repository several times a day. Each check-in is then verified by an automated build, allowing teams to detect problems early.

> Continuous Integration doesn’t get rid of bugs, but it does make them dramatically easier to find and remove.

(Stolen from ThoughtWorks)

One of the VERY nice things with CI is that with each PR, you'll instantly see if you're introducing any buggy code:

![img](http://cdn.macoscope.com/blog/wp-content/uploads/2015/12/github-pr-tests-running.png)

...perhaps a good start will be with setting up a free CI (Travis is good) that simply runs:

- `phplint controllers/**/*.php` 
- `phplint interface/**/*.php` 
- `phplint common/**/*.php` 
- `phplint services/**/*.php` 
- `phplint entities/**/*.php` 
- `phplint library/**/*.php` 
- `phplint repositories/**/*.php` 

...more tasks can be added later (naming convention checks, style checks, tests, etc)

**Comment by MatthewVita** [comment]
@robertdown Hi Robert. I bet you'll have some guidance here. Let me know if phplint + TravisCI is a good start.

**Comment by bradymiller** [comment]
Sounds like a great idea.

**Comment by MatthewVita** [comment]
https://gist.githubusercontent.com/MatthewVita/ce841e6f05b35cc9c9861bd0439b0547/raw/2db720fd18abf64619e1f927c1242c08912e2787/gistfile1.txt
