### ISSUE TITLE
Patient demographics header

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#4928]
Demographics header currently takes more than 20-30% of tablet view and offers no additional/usable information for experienced users. While looking at some reorganization, noticed the following:

https://github.com/openemr/openemr/blob/efa882d5cdd7aacfe61afe85bd08a4bf1616fb6f/interface/patient_file/summary/demographics.php#L903

But the class constructor takes no arguments
https://github.com/openemr/openemr/blob/efa882d5cdd7aacfe61afe85bd08a4bf1616fb6f/src/Menu/PatientMenuRole.php#L33

Not sure about the benefits of Twig which is a template engine and this project seems to be adding "templates" that are and can be used only once. It would be great if developers can pass different data to a template and are spared of writing the verbose bootstrap code or having to translate every literal. But hard coding page specific content in a twig or smarty template does not help anyone.

**Comment by robertdown** [comment]
There is inherent benefit in using Twig if for nothing more than separation of business logic from display logic. However, Twig conversion is still relatively early on and as infrastructure continues to improve, a more flexible scheme will unfold, abstracting away a lot of the redundant code.
