### ISSUE TITLE
weno_log_sync.php

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#4930]
@juggernautsei ,
One of the installations has this error. Are you sure globals is required in a library with just a function? Caller of your function should already have globals called.

`require_once(../interface/globals.php): failed to open stream: No such file or directory in xxx/library/weno_log_sync.php on line 11`

**Comment by sjpadgett** [comment]
yep I noticed this also. Plan to fix in my current open PR.

**Comment by sjpadgett** [comment]
@juggernautsei 
Most definitely this functionality wasn't working however even after fatal fix, I have doubts this is working the way you'd expect.
Suggest you carefully test and fix.

**Comment by juggernautsei** [comment]
Ok, I am remembering why I put that there and it was to be called by the background services.

**Comment by sjpadgett** [comment]
I believe you have some closure issues instantiating some of your classes! Probably why you added globals thinking classes weren't auto loading. I may be wrong but again, suggest you fire up and test.

**Comment by juggernautsei** [comment]
You are right.

**Comment by sjpadgett** [comment]
Maybe take a look at your constructors!

**Comment by juggernautsei** [comment]
Thanks for the hint but I have parted ways with this particular project. If anyone would like to pick up the work on this project. Be my guest.

**Comment by sjpadgett** [comment]
huh, that opens up a ton of questions. But, not me for sure. Issue is solved and will close when I bring in my PR. Thanks @mdsupport for taking the time to bring this up.
