### ISSUE TITLE
Portal available for deceased

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#4934]
Portal access should be automatically curtailed if

1. Patient is marked deceased - Would be very interested in the use cases where remote access  is to be kept open.
2. Patient is inactive for n months/years - CMS considers 3 years as a reasonable period to mark end of provider-patient relationship. We could probably use that to start.

**Comment by sjpadgett** [comment]
I plan soon to implement a patient archival scheme similar to delete patient workflow except a soft delete that can be retrieved from patient finder etc.
This would put the responsibility on users.
