### ISSUE TITLE
Patient Demographics Warnings/Info are cards

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#4949]
Few of the warnings or informational display elements such as `Portal access not authorized` are rendered as BS cards. These are easily implemented as BS Alerts with auto-dismiss option.

Even better will be to evaluate if knowing Portal access setting or for that matter anything at all is so critical for all users so as to be omnipresent on patient record summary.

**Comment by robertdown** [comment]
This was a very conscious design decision. On my long roadmap is introducing flexible dashboards where cards and alerts can be customized based on ACLs, User roles, and other criteria.

With regards to the portal section. Yes, if the user has not authorized the portal, the card is essentially just informational. However, once the patient does authorize the portal, that card holds actions.

Every alert we add increases alarm fatigue to the end user. The portal not being authorized is definitely not something the user should be alerted to. That info should just sit in a card where the end user is not drawn to.
