### ISSUE TITLE
ToC CCD send broken in encounters

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4950]
### Describe the bug
I had this working but it looks like since conversion to twig the URI is corrupted. Suspect a double escape.
It's also broken in demographic Send To HIE which should be converted to send to direct.

I don't know if this is a feature that ONC requires us to attest or test.
![OpenEMR-v6-1-0(1)](https://user-images.githubusercontent.com/1859985/155361537-3d48377a-5af8-4430-809b-ad7a92741d31.png)

**Comment by adunsulag** [comment]
The (b)(1) SLI certification test script shows verification of a TOC CCDA.  However, I think CareCoordination module lets you select specific patients & encounters so I'm not sure it has to be done within the encounter screen.  We should still fix the bug though.

**Comment by sjpadgett** [comment]
Agreed @adunsulag However, I've fixed this twice in the past. I get the new one with twig refactor but It's also broken in production again!
This is so frustrating for me!

**Comment by sjpadgett** [comment]
Has anyone been able to setup phpstorm to debug twig. Appears storm requires cache to debug anyway @robertdown do you use?

**Comment by robertdown** [comment]
So it's not actually just an escaping problem, here is the relevant template code:

```twig
 <div class="dropdown-menu" aria-labelledby="category_{{ category|attr }}">
      {% for item in details.children %}
          {% if item.onclick is defined %}
              {% set onclick = item.onclick %}
          {% else %}
              {% set formURL = rootdir ~ "/patient_file/encounter/load_form.php?formname=" ~ item.directory|url_encode %}
              {% set onclick = "openNewForm(" ~ formURL|attr_js ~ "," ~ item.displayText|xlFormTitle|attr_js ~ ")" %}
          {% endif %}
          <a href="#" class="dropdown-item" onclick="{{ onclick }}">{{ item.displayText|xlFormTitle|text }}</a>
      {% endfor %}
  </div>
```

However, if I dump the content of details.children for the Carecoordination shows:

```php
["id"]=>
  string(1) "8"
  ["mod_id"]=>
  string(1) "5"
  ["enabled_hooks"]=>
  string(11) "send_to_hie"
  ["attached_to"]=>
  string(9) "encounter"
  ["menu_name"]=>
  string(11) "Send To HIE"
  ["path"]=>
  string(16) "encountermanager"
  ["mod_ui_name"]=>
  string(16) "Carecoordination"
  ["type"]=>
  string(1) "1"
  ["href"]=>
  string(50) "../../modules/zend_modules/public/encountermanager"
}
```

And that array doesn't line up with the the above template. Let me see if I can get a quick fix for this

**Comment by sjpadgett** [comment]
The click event should look like
`openNewForm("..\/..\/modules\/zend_modules\/public\/encountermanager", "Send To HIE")`

Relevant code in v6
```
$relative_link = "../../modules/" . $modulePath . "/public/" . $modulerow['path'];
$nickname = $modulerow['menu_name'] ?: 'Noname';
```

**Comment by robertdown** [comment]
Ok, I updated the Encounter menu as well as the Dashboard menu. Feel free to look at #4951 but both of those links go to the care coordination module now
