### ISSUE TITLE
Automated Measures Calculation 2015 EHR Certification § 170.315 (g)(2) 2015 ONC

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4956]
For (g)(2) certification of the Automated Measures Calculation we need to implement the following Required Tests:

- Required Test 2a,2b,2c - Providing Patient Access, View Download Transmit
- Required Test 7 - Support Electronic Referral Loops by Sending Health Information (formerly Transitions of Care)

This satisfies the Promoting Interoperability (PI) requirements for **Patient Access** and **Electronic Referral Loops by Sending Health Information**.  This does not satisfy the PI requirements for **E-Prescribe**  and **Reconciliation and Incorporation** which we hope to get to in the second half of the year.

This is a container issue that will link out to specific individual issues for each of the Required Tests and modifications needed for OpenEMR.  The relevant issue list is:

- #4958
- #4959 
- #5003
Note much of this information is documented in our wiki here: https://www.open-emr.org/wiki/index.php/Automated_measure_calculation_(MU3))

**Comment by adunsulag** [comment]
Successfully passing all of the baseline individual and group calculation test cases on this issue, but I discovered that on the individual calculation report there is no indication of what provider the calculation is based on during the printout.  I'll need to add that so we can aggregate it with the group report.
![image](https://user-images.githubusercontent.com/228117/161362250-d48ca0c6-b392-4274-b024-b73c0fed510a.png)

**Comment by adunsulag** [comment]
Found out that I was passing the baseline but in the patient details ended up with duplicate patient names for the referral counts.  Had to overhaul how the patient data is aggregated so here is an updated version of what that looks like.
![image](https://user-images.githubusercontent.com/228117/161407177-71a45457-0aa0-49b1-8032-4a2550546aea.png)

**Comment by adunsulag** [comment]
Got rid of all of the duplicates and reworked the Numerator/Denominator/Actions display to match more ONC's report (and it was easier to depulicate that way).  I've gone through 3 scenarios now.  99.5% confident we will pass the last 2 scenarios which I'll enter in the data and do that on Monday.  I've created docker snapshots for each of the 5 scenarios in case we need to re-run the reports for ONC.  I'll do some minor code cleanup and write up documentation on the AMC report but I would say we are pretty much code complete with AMC.  Hooray.  

Future improvements would be: cleaning up the AMC report generation screen, at this point I'd just drop all of the extraneous functions and generating old reports (still make it so the old reports will display, just can't create new ones against 2011/2014 codesets).  Batch processing / optimization so we don't kill the server when AMC generates.

Here is the Scenario 3 report.  It looks way better in the browser but the table breaks and stuff leave a lot of gapped whitespace.  I'm not sure the ATL will care, but if so we'll work on prettying up the report.
[Scenario3.pdf](https://github.com/openemr/openemr/files/8403741/Scenario3.pdf)

**Comment by adunsulag** [comment]
![image](https://user-images.githubusercontent.com/228117/161599085-5be7aa9e-c849-4940-a045-84f97395447c.png)

So we successfully pass all 5 scenarios but there are bugs on the print display for the individual calculation report due to the way our table headers are structured.  I'm going to see if there's something I can do to fix this.

**Comment by adunsulag** [comment]
With the last pull request we are now code complete on this feature.  Hooray!

**Comment by stephenwaite** [comment]
![southpark_cheering](https://user-images.githubusercontent.com/5618372/161747668-62e16b7c-f182-4e35-aa40-d6e321b15fe3.gif)
