### ISSUE TITLE
AMC ONC 2015 Support Electronic Referral Loops by Sending Health Information

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4959]
Implement the QPP **Support Electronic Referral Loops by Sending Health Information**(PI_HIE_1) category as specified here: https://www.open-emr.org/wiki/images/e/ee/2022_MIPS_PI_Measures_Support_Electronic_Referral_Loops_by_Sending_Health_Info.pdf

For this feature we are going to need an amc_code_2015 column and an amc_2015_flag to the clinical_rules table. The code column would contain the referenced ONC criteria text and the flag would be to include that specific code class into the calculations.

It looks like the text descriptions are contained in the clinical_rules' list (stored in list_options). The option_id must match the specific rule id column in the clinical_rules table for that AMC measure.

It looks like the currently implemented clinical rule id send_sum_1_stage2_amc or send_sum_stage2_amc is the AMC measures that need to be modified here. This corresponds with class files:
[AMC_304i_STG1](https://github.com/openemr/openemr/blob/master/library/classes/rulesets/Amc/reports/AMC_304i_STG1.php)
[AMC_304i_STG2](https://github.com/openemr/openemr/blob/master/library/classes/rulesets/Amc/reports/AMC_304i_STG2.php)

This is a sub-issue underneath #4956.

We decided we need to calculate whether the CCDA had the relevant data (problems, allergies, medications, prescriptions) at the time the ccda was sent rather than after the fact. Old MU2 implementation inaccurately used current issues list for this.
We also need to support some kind of confirmation that the referral was received.

**Comment by adunsulag** [comment]
So I ran into a problem running through the ONC / SLI test scripts for (g)(2).  The data set specifically has the scenario where a provider creates a referral / transition of care without there being any associated encounter / visit from that provider.  That pretty much breaks my group calculation logic as patients are excluded from even being processed by AMC if they haven't seen the provider (using the encounter group calculation method).

I may need to make the buildPatientArray more complicated for the group calculation (IE include a patient using the 'encounter' method if the patient has an encounter OR a referral initiated by a provider).  

Anyone have any other suggestions (@stephenwaite @bradymiller @sjpadgett)?  I'll sleep on it tonight and see if there's a better approach tomorrow.

I could hack it by creating duplicate reports for each of the test scenarios so that I create encounters for this rule so that it passes correctly.  The downside is that the report includes the other rule (2c) and those patient encounter numbers will be off so the tester would have to ignore those numbers.  Another option would be to add a rule filter to the AMC reports so you can run the reports for a single rule.  We'd just have a lot of extra reports.

I thought I was nearly at the finish line but I guess its not meant to be easy lol.

**Comment by sjpadgett** [comment]
@adunsulag We'll talk.

**Comment by stephenwaite** [comment]
dang it, ok, so Jerry's right, should've been facility :crying_cat_face:

**Comment by adunsulag** [comment]
I got the baseline report to work correctly by putting default billing facility on the transaction form (referral form).  I've started to generate the reports and its going to take a very long time to collate the reports together printing off each individual numerator/denominator/pass/fail as separate pdfs and collate them. I'm going to see if I can whip up a code solution to generate the entire data report we need in one go since we have to submit the report as a single file.

**Comment by adunsulag** [comment]
Here is the sample of what I've done here for the report:

[GroupCalculation_BaselineSummaryDetailsWithActions.pdf](https://github.com/openemr/openemr/files/8393284/GroupCalculation_BaselineSummaryDetailsWithActions.pdf)

Added a new Button "AMC Detailed Report"
![image](https://user-images.githubusercontent.com/228117/161156038-e5fdc07b-ddf4-4d96-b984-81ebdab3fecb.png)

That takes you to the advanced detailed report.  It cycles through a LOT of data as it will display each individual patient as well as all of the individual measurement items for each measurement rule that passed / failed.  Since its intended to have every single patient in it, it will take a long time to generate the report if this is done over thousands of patients.
