### ISSUE TITLE
ONC § 170.315(b)(1) testing issues and results

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4964]
### Describe the problem

A place to track b(1) testing.
SMTP Test 8, 14 and 18 Send pass.

**Comment by sjpadgett** [comment]
Appears CCM auto Import from Direct export is working for CCD.
![image](https://user-images.githubusercontent.com/1859985/155860884-3f9c3393-471b-4294-a383-255f7ddae907.png)

**Comment by sjpadgett** [comment]
Yeah! Good work @adunsulag for a Georgia boy!:)

![image](https://user-images.githubusercontent.com/1859985/155906497-e11b6ab1-a316-481e-8ea4-15e0b2fa9343.png)

**Comment by sjpadgett** [comment]
Send test working except we're not giving the exported CCDA xml a name it appears. I have a couple IG conformance errors dealing with name prefix and suffix data types.

![image](https://user-images.githubusercontent.com/1859985/155910866-fe2e4710-b198-41d7-acf8-190b3516ecc9.png)

@bradymiller and @adunsulag , I say we can call b(1) complete. I'm going to do a quick run at h(1) since we've changed some things with our Direct account since Stephen tested.

**Comment by sjpadgett** [comment]
@adunsulag 
Looks like we do have to use two different usernames for testing.
b(1) testing uses openemr-edge2015@directtest.interopengine.com the  where h(1) requires us to use openemr@test.directproject.net sandbox username.

![image](https://user-images.githubusercontent.com/1859985/155912991-2662e9d0-d706-4fdb-a5ca-b0ae31c45853.png)

I'll leave to you if we want to add additional globals for usernames and hook in code if Direct is in dev mode. Otherwise we'll need to change as we test. However, I did a few of the same testing you've done with good results.

**Comment by bradymiller** [comment]
@sjpadgett , @adunsulag ; Hopefully can make the globals more centric towards productions users, who will likely just need to turn the service on and provide a username and password.
Would probably turn off the test mode by default.
And is the phiMail Server Address needed (ie. is there a separate one for production and testing that can be hard-coded or does it need to be flexible where need to enter it in like we have it?)

**Comment by sjpadgett** [comment]
We're leaving globals alone. b(1) and h(1) are green. Closing this.
