### ISSUE TITLE
only variable references should be returned by reference

### ISSUE THREAD

**Issue by Jopchumba** [openemr/openemr#4966]
### Describe the bug
Only variable references should be returned by reference.
seems to be having this errors everywhere 
### To Reproduce

1. Add a '....'
4. See an error

### Client configuration

- Browser:
- OpenEMR version:current 
- Operating system:windows

**Comment by stephenwaite** [comment]
hi @Jopchumba , if you compare your php settings with [recommended settings](https://www.open-emr.org/wiki/index.php/FAQ#What_are_the_correct_PHP_settings_.28can_be_found_in_the_php.ini_file.29.3F) and restart your webserver does it fix your issue? Specifically the `display_errors` setting...

**Comment by Jopchumba** [comment]
@stephenwaite where are the files located trying to search cant find it

**Comment by stephenwaite** [comment]
hi @Jopchumba , a quick [web search](https://stackoverflow.com/questions/6185319/how-to-locate-the-php-ini-file-xampp)
