### ISSUE TITLE
Direct Send with empty message body fails with M7 Error

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4970]
For ONC certification on (b)(1) we need to be able to handle a Direct message that has a subject but an empty body with attachments.  Right now it just returns an M7 error message (which @lcmaas) introduced for better error reporting.

**Comment by lcmaas** [comment]
The root issue is that the Document constructor indirectly called by phimail_store rejects documents of zero length. Note this could also result in an M11 error. I'll drop a suggestion on how this might be addressed in a branch in my repo shortly but unfortunately I will not be able to test...

**Comment by lcmaas** [comment]
It's both. The tests don't send you an empty attachment, but if they did, the system would fail the same way.
Take a look here for an idea of how to bypass the document creation in this case -- this is untested so I did not create a pull request; it should also address the empty html message body:
https://github.com/lcmaas/openemr/commit/53fbb33006aa0a50522e870b4728cc187b2a69d0
Also, the b.1 tests shouldn't be sending you html bodies; it seems like perhaps the wrong attachment was selected from the edge testing tool, but nonetheless this did bring this limitation (empty documents) to light...

**Comment by sjpadgett** [comment]
> wrong attachment was selected from the edge testing tool

I did this on purpose because likely someone could send html versions of CCDAs or CQM Cat III reports. 
I'll pull your solution down tomorrow and test or Stephen will. As long as the empty body doesn't prevent completion of the transaction and user gets notified that the empty message is expected, I'm happy. Thanks.
