### ISSUE TITLE
Top level menu font too small

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#4973]
### Describe the bug
IMO or maybe not. Opinions?
@robertdown 
![image](https://user-images.githubusercontent.com/1859985/156026464-ba4ea812-2a3b-41e0-9c17-4f92b1eaf775.png)

**Comment by robertdown** [comment]
I personally don't think it's too small, however, it should definitely be User-defined. I have a PR in draft for a Config Service which will allow modules to provide user-level modifications (will help our $GLOBALS bloat).

The solution is a user-level option that defines a font size. That gets picked up as a CSS variable.

I'm 60% done with the Config Service. So we can either add this into $GLOBALS or wait and leverage the config.

**Comment by sjpadgett** [comment]
Okay and I like the user defined solution. Thanks!
