### ISSUE TITLE
Title tag missing 

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#4975]
https://github.com/openemr/openemr/blob/6745c839f2d9532551d03e1e4ca4804d126be67d/interface/forms/procedure_order/common.php#L480

The title tag is missing. I just happen to be working on this form and noticed it not there.
Should I put in a PR?

**Comment by sjpadgett** [comment]
you could add one but I don't think it's needed except maybe for aria or crawlers. the tab in encounter doesn't need for naming the tab like in our top level tabs. if important, i'll try to remember my next PR.

**Comment by adunsulag** [comment]
Did this get fixed? Or should we close the issue?

**Comment by bradymiller** [comment]
don't think it needs fixing since title is not used in that script (generally used to populate the tab name, but is not needed in that script), so will close this
