### ISSUE TITLE
Patient Portal Registration Email Address Plus Sign

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#4996]
So, I don't know if we want to fix this but I wanted to put this in just in case this wasn't intentional.  In the patient portal registration if an email address is used with a plus sign such as address+label1@gmail.com is used the email is never sent nor is any error registered on the backend system.  I often use emails with plus signs for testing purposes and this should be spec compliant.  Now if we made a decision to reject these kinds of emails we should probably let the user know that the email is rejected.

Way to reproduce this:
Enable patient portal registration and enter in a V2 google captcha from Globals.
Go to patient portal registration.
Hit the register button.
Enter in first name, last name, and email address with plus sign (+) for an email account you own.  Verify email is not received.
Try the same process with an email address without a plus sign.  Verify email is received.

**Comment by bradymiller** [comment]
Looks like the validEmail() function is overly strict. Notably that function is defined in 3 separate scripts. Would prob migrate it to library/sanitize.inc.php (this file is always included with globals.php) and make it much less strict.
