### ISSUE TITLE
Issues tracking for QRDA CAT I Cypress testing.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5012]
I thought I'd open a thread for us to record testing progress both good and bad. I'm looking forward to mostly good!:)

I have turned up a Cypress Tool on my local server. Hope to share access soon.

**Comment by sjpadgett** [comment]
see this PR on test outcomes: https://github.com/openemr/openemr/pull/5155

**Comment by sjpadgett** [comment]
All cat1 testing green and shown in PRs except these three which I'll show here.

![image](https://user-images.githubusercontent.com/1859985/164114031-b6844163-0da6-42f5-9073-befe92927a0f.png)

![image](https://user-images.githubusercontent.com/1859985/164114871-b231acf4-26e0-45d2-8080-81103db569ed.png)

![image](https://user-images.githubusercontent.com/1859985/164115984-be27c718-d6a3-400e-aefb-48d8c39530aa.png)

And finally:

![image](https://user-images.githubusercontent.com/1859985/164116194-dc060ce5-9383-4b7f-8963-8805a5412cce.png)

This ends the Cat1 saga that is CQM. Onwards....

**Comment by sjpadgett** [comment]
Closed as completed.

**Comment by bradymiller** [comment]
![tenor (26)](https://user-images.githubusercontent.com/278968/164118796-b51fdd80-98e5-4e2f-a420-c4ef863fb423.gif)

**Comment by adunsulag** [comment]
We certified the QRDA Cat 1 criteria so closing this issue.
