### ISSUE TITLE
Clearinghouse ETIN gets printed when submitting to clearing house.  Also, in the NM41 (5th line) of X12 file, when submitting to clearing house there is a missing field.

### ISSUE THREAD

**Issue by growlingflea** [openemr/openemr#5025]
In branch master, started with commit Commit 077a35c5

### Describe the bug
When submitting to a clearing house, the clearing house ETIN prints where the billing provider ETIN should print. If we are submitting directly to an ins co, and "submit directly to ins co" is selected in globals, having the clearing house ETIN print will work since the practice is acting as their own clearing house.  

![image](https://user-images.githubusercontent.com/8116478/159767689-a840b1a9-95ed-4e35-9fe3-69905f771f21.png)

There is also a missing field in the NM*41 field (specifically after the "2") which throws errors about NM108 and NM109 since NM109 does not exist and NM108 does.  
![image](https://user-images.githubusercontent.com/8116478/159768417-849de1b4-a6af-4793-82dd-49494b67f1e8.png)

The other issue is that in Practice Settings, submitter name should only be filled out if someone is acting as a third part submitter or if they are submitting directly to an ins. company. Probably the best way to handle this is to make $claim->x12_submitter_name() always false if "bill directly to ins co" is not selected.  

These fixes were made in a pending pull request.

 

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by stephenwaite** [comment]
> If we are submitting directly to an ins co, and "submit directly to ins co" is selected in globals, having the clearing house ETIN print will work since the practice is acting as their own clearing house.

did you mean have the practice's ETIN go in there?

**Comment by growlingflea** [comment]
Yes.  In order to be able to submit claims directly to insurance companies, they need to register as an X12 partner with the ins co to get the X12 partner ID.   So essentially they are their own clearing house.

**Comment by growlingflea** [comment]
Sorry.  I think I got my words confused.  

The particular bug prints the Clearing House ETIN where the practice ETIN should go, when we are not billing directly to an ins co.  This is specifically the segment  NM1*41 9th position (NM109).

If we are submitting directly yo the ins company, we sent the **x12 partner ID** that the practice gets when they request being an X12 partner with the ins co.

**Comment by stephenwaite** [comment]
closed via #5022
