### ISSUE TITLE
Growth Charts for children between birth and 24 months use CDC and not WHO data, charts for %tiles go every 6 months which is inaccurte

### ISSUE THREAD

**Issue by growlingflea** [openemr/openemr#5035]
### Describe the bug
This is more of a design flaw than a bug.  Growth charts for children between 0 and 24 months use data from the CDC which is incorrect, they should be pulling data from the WHO.  Also, the current charts use intervals of 6 months which is useless when it comes to children between the ages of 0 and 5.  

The display for the most recent vitals can use improvement as well.  As you see there is limited information
![image](https://user-images.githubusercontent.com/8116478/160026164-968ff387-c4b2-4caa-bd1e-0977feb67bad.png)

The method of using tables to display data is archaic and the new method of CSS grid is recommended.  

Color sheet are now available for growth charts

Growth charts for children with Down Syndrome are available too.

###Solution
I am in the midst of improving the encounter report and also the last Vitals taken.  For children between birth and 5 years I used the WHO expanded tables for head circumference, height, weight, and BMI.  The CDC values are ignored for children under 24 months.  For 24 months to 20 years old the CDC values print.  Here is an example of the Last Vitals taken.  

  
![image](https://user-images.githubusercontent.com/8116478/160026530-94c01efa-1511-470f-9db3-81638e983fd3.png)
 

I have removed the B&W growth charts and replaced them with color.  For children under 24 months the WHO charts are used.  

Charts will print patient DS stats for those that have it recorded in OpenEMR.  Currently, only the CDC offers growth charts so those will be used for patients with DS.  

I expect to have this complete in the next few days.  

Ciao!
:

**Comment by sjpadgett** [comment]
Who says the CDC is incorrect? Maybe for Africa WHO but, for US and MU2/3 they point to CDC. @adunsulag didn't you have to update the recently?

**Comment by growlingflea** [comment]
It states this on the CDC website.  

https://www.cdc.gov/nccdphp/dnpa/growthcharts/resources/growthchart.pdf

**Comment by sjpadgett** [comment]
Sounds okay to me Daniel. Brady may need to way in or someone who remembers what was required for MU. I seem to remember us changing this recently.

**Comment by growlingflea** [comment]
I went ahead and submitted a pull request to master, correcting all the PHP styling issues.
