### ISSUE TITLE
EyeExam does not load

### ISSUE THREAD

**Issue by jl1dvg** [openemr/openemr#5039]
The EyeExam form works fine if it is created for the first time, if an EyeExam has been created in a previous encounter the EyeExam form does not load in any encounter

![Captura de Pantalla 2022-03-25 a la(s) 19 21 39](https://user-images.githubusercontent.com/59968051/160217479-2c1510b4-cb2a-4b25-99f0-43f7050b1a13.png)

This error also exists in the DEMO of the web page

**Comment by stephenwaite** [comment]
hi @jl1dvg , not able to reproduce on the demos.

**Comment by jl1dvg** [comment]
hello @ stephenwaite, I updated the EyeExam files with the latest revision that you did yesterday, the form loaded very well, but there are problems in the priors_select and display_QP functions, I decided to delete some lines and it worked better, but the problem still persists that I can not enter the DX in the plan

these are the lines I deleted

https://github.com/openemr/openemr/blob/3b56fed34017c0853dbc2cb1270832b2f4519582/interface/forms/eye_mag/php/eye_mag_functions.php#L100
https://github.com/openemr/openemr/blob/3b56fed34017c0853dbc2cb1270832b2f4519582/interface/forms/eye_mag/php/eye_mag_functions.php#L102
https://github.com/openemr/openemr/blob/3b56fed34017c0853dbc2cb1270832b2f4519582/interface/forms/eye_mag/php/eye_mag_functions.php#L3008
https://github.com/openemr/openemr/blob/3b56fed34017c0853dbc2cb1270832b2f4519582/interface/forms/eye_mag/php/eye_mag_functions.php#L3010

**Comment by stephenwaite** [comment]
hi @jl1dvg, hopefully #5041 will fix these and other remaining issues.
