### ISSUE TITLE
Remove lines 3008 and 3010 to appreciate 2 columns of the QP List

### ISSUE THREAD

**Issue by jl1dvg** [openemr/openemr#5040]
https://github.com/openemr/openemr/blob/3b56fed34017c0853dbc2cb1270832b2f4519582/interface/forms/eye_mag/php/eye_mag_functions.php#L3008

https://github.com/openemr/openemr/blob/3b56fed34017c0853dbc2cb1270832b2f4519582/interface/forms/eye_mag/php/eye_mag_functions.php#L3010

Hello, with the new update of the file, new errors appeared, one of them was that the QP List appeared incomplete, I preferred to delete these lines and the two columns were appreciated again.
Another mistake is that the DX do not appear when they are dragged into the plan box, in addition, past stories are not seen in the QP List.

**Comment by stephenwaite** [comment]
also looking into [this issue](https://community.open-emr.org/t/find-code-pop-up/18126) and [this one](https://community.open-emr.org/t/impplan-eye-form-error/18125)
