### ISSUE TITLE
LBF/LBT Patient Encounter List Selector Option

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5048]
In the Transition of Care / Referral screen (what OpenEMR calls transaction forms) I need to be able to connect a referral form to the encounter that the referral is based upon for AMC calculations (and presumably people would like to know this for billing purposes as well). To do that I need a new Layout Options selector for encounters which this feature will track.

**Comment by adunsulag** [comment]
This feature is required for #4959.  Here is a screenshot of what is being implemented.

![image](https://user-images.githubusercontent.com/228117/160430237-c92e67b3-1302-49a8-8607-59be45fc4aad.png)
If a clinic has their own custom LBT form for referrals it will append the encounter_id field to the end of their LBT form when they upgrade to 7.0.

Here it is in the LBT referral form (look at the bottom field).
![image](https://user-images.githubusercontent.com/228117/160430413-f3c9ecbd-7adc-4c05-8511-281b20e5fa07.png)

**Comment by sjpadgett** [comment]
@adunsulag Referrals are not attached to encounters that I know. They are attached to a patient.
This goes back to why CCM ask reason for referral on Direct. In CCDA I have to do some assumptions!

**Comment by adunsulag** [comment]
@sjpadgett I had this discussion with @stephenwaite.  Referrals in OpenEMR are attached to the patient but I have to be able to tie them to a billing facility for MIPS reporting.  I was going to have a facility selector, but Stephen Waite recommended we use the encounter instead.  Stephen Waite assured me that pretty much all transitions of care / referrals are traced back to an encounter with the doctor for insurance / billing purposes.  I made the field optional so providers not dealing with MIPS don't have to fill the field out but for MIPS reporting we have to be able to trace the relationship.
