### ISSUE TITLE
Error with multisite upgrade v6.0.0-v6.1.0

### ISSUE THREAD

**Issue by gutiersa** [openemr/openemr#5066]
### Describe the bug

Decryption and Key creation issues (Blank Screen) with subsequent site upgrade in multisite

### To Reproduce
Upgrade an additional site after upgrading default.
This problem comes up with the newly upgraded site, which causes a blank screen upon login in if the site's database has data. The problem is similar to the one in this forum issue.

https://community.open-emr.org/t/decryption-and-key-creation-issues-blank-screen-is-not-file-permissions/16059

Deleting sites/siteid/documents/logs_and_misc/methods/sixa and sixb then clearing browser fixes the problem.

I understand why this occurs, one solution would be to create a site-template directory elsewhere (in a location such as src) which contains the contents of the current default directory without the sixa and sixb files. From there, the sites directory can be populated when the site is created via the setup process.

### Client configuration

- Browser: Firefox
- OpenEMR version: 6.1.0
- Operating system: windows 10

**Comment by gutiersa** [comment]
So this also needs to be done with upgrading. Meaning after running the database upgrade, sixa and sixb also need to be deleted. I will be happy to upgrade the wiki, but first wanted to make sure it is ok
BTW I ended up having to run the upgrade, because patch 4 broke printing of custom reports in my system.

**Comment by bradymiller** [comment]
Note that removing those keys means that anything encrypted in the database with them will be lost forever, so recommend being careful when doing this.
Note that multisite has 2 scenarios.
1. Create a new multisite and a completely new database (in this case will remove the keys)
2. Create a new multisite with a clone of the originating site (in this case will keep the keys)

And for an upgrade should never need to remove keys if the upgrade is done correctly. Important to stress that if delete those keys anything that is encrypted in the database with them will be lost forever (at this point that can include stored credentials in globals in best case scenario and in worst case scenario all the log entries).

**Comment by bradymiller** [comment]
Regarding removing keys in scenario 1 above, @stephenwaite is working on doing this automatically during setup of the multisite, so would rec not placing any instructions to remove keys on the wiki. Or then somebody may ask something like "How can I see encrypted log entries for the last year after I deleted my keys?" on the forum to which we may need to respond that it is possible in theory although it may take several thousand years to guess the decryption key :)

**Comment by bradymiller** [comment]
Sorry for all the posts here. For a good discussion/explanation on the keys (there is a set on the drive and a set in the database), check out this post:
https://community.open-emr.org/t/getting-a-white-screen-when-saving-demographics-in-502/15277/6

**Comment by gutiersa** [comment]
I did follow all the steps. Should I open a forum thread then? I have
questions, for example, what is the correct solution? Also, now that I have
created new keys, what is the next step?

My old keys are saved in the backup directory

**Comment by stephenwaite** [comment]
Hi @gutiersa , when a new site is created from the multisite then the keys that were copied over from the source site can be deleted after installation unless the site was a clone. This PR will fix this going forward after I address the clone option.

**Comment by gutiersa** [comment]
Goodness, I realize that I did not articulate my problem correctly. The issue came up with upgrade, not new site creation. I will edit my messages above.

**Comment by bradymiller** [comment]
hi @gutiersa 
Wasn't able to confirm this on an upgrade.
There are currently 2 keysets in OpenEMR, with one in the database and one on the drive (sites/siteid/documents/logs_and_misc/methods/). And these 2 keysets are a "pair" meaning if one is changed, then the other will break and vice versa. This then means that the database and drive of an installation are "pairs", which needs to be considered during any upgrade or other devops work with an installation.
The error you are seeing happens when either of the keys are changed or if do not have read access to keys in sites/siteid/documents/logs_and_misc/methods/ .
What error are you seeing in the php error log after the white screen?
And are you sure that you are copying the sites directory from the correct old version of your instance during the upgrade proces?

**Comment by gutiersa** [comment]
I am sorry I have not followed up yet. I do have the error logs saved. I have not forgotten!
