### ISSUE TITLE
<!-- Warning: The suggested title contains the alert rule name. This can expose security information. -->

### ISSUE THREAD

**Issue by shannonmae999** [openemr/openemr#5075]
Tracking issue for:
- [ ] https://github.com/shannonmae999/openemr/security/code-scanning/336

__Originally posted by @shannonmae999 in https://github.com/shannonmae999/openemr/issues/4__

**Comment by adunsulag** [comment]
Your link doesn't work and the issue doesn't make sense.  Closing this.
