### ISSUE TITLE
Carecoordination EMRDirect uses email not email_direct field

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5076]
When using the Carecoordination module auto suggest for sending with EMR Direct the autosuggest lookup for the Address Book uses the email column field instead of the email_direct.  So if a user has a different direct address than their regular email address the auto suggest will grab the wrong address.  

To reproduce create a new user in the Address Book with the type set to EMR Direct.  Set the Trusted Email address to be different than the Email address.  In CareCoordination Send To -> EMR Direct type in the name of your user and select them.  It will populate the regular Email, not the Trusted Email.

**Comment by sjpadgett** [comment]
I thought we discussed this awhile back. Really trusted should be the only address searched and should have direct flag set for type. Right?
Should I fix or are you in that code?

**Comment by adunsulag** [comment]
I've got it fixed already, just going to put it into a separate PR once I'm done with some tweaks to the amc collection in ccda.
