### ISSUE TITLE
Carecoordination timing issue sends to EMRDirect out of order before CCDA generation

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5078]
The CCDA generation and EMR Direct ajax post requests in Care Coordination get fired off at the exact same time.  If the send to EMR data depends on the prior CCDA request (which one would assume it would) it will fail (or happily send an earlier generated CCDA).  The code flow needs to be structured so that ajax requests are serial rather than concurrent.

**Comment by sjpadgett** [comment]
I saw this and fixed I'm pretty sure back when I was testing for Direct! It appears to be timing but not. I'll have to refresh my memory and look code over again. It was a simple thing in the end.
