### ISSUE TITLE
Adopt FHIR Units of Measure codes

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#5083]
Not sure if this is already implemented or in the works. But is it possible to make [standard units of measure codes](https://build.fhir.org/valueset-ucum-units.html) available for use in a central location?

Unfortunately there does not seem to be a PHP library to provide supporting service like [this java version](https://github.com/FHIR/Ucum-java).

**Comment by adunsulag** [comment]
I don't think we really have something that comprehensive.  The closest thing I know that we have is in the VitalsService->createResultRecordFromDatabaseResult() and FhirObservationVitalsService->getFHIRQuantityForColumn().
