### ISSUE TITLE
No way to register new patients

### ISSUE THREAD

**Issue by ajmeese7** [openemr/openemr#5084]
### Describe the bug

When I enable the Patient Portal from Global Settings, I am able to access the patient portal at `http://ip-address/portal/`, as is expected. But once I am there, there is no register button for new patients.

![No register button](https://user-images.githubusercontent.com/17814535/161453893-994199dd-d69a-4da5-b645-cf213b5e3f21.png)

The option to allow "New Patient Registration" is enabled, but that has no effect on the portal, as you can see above.

![Correct settings](https://user-images.githubusercontent.com/17814535/161453929-1da24c68-a180-4252-bc88-4498e99b8aa9.png)

### Expected behavior

I expect to be able to sign up new patients once the option is enabled.

### Client configuration

- Browser: Brave
- OpenEMR version: 6.1.0
- Operating system: "OpenEMR Express Plus v6.0.0 cloud deployment"

**Comment by stephenwaite** [comment]
hi @ajmeese7 , pretty sure the clinic registers the person and produces the credentials that are then used on that page.

**Comment by ajmeese7** [comment]
![Self Registration](https://user-images.githubusercontent.com/17814535/161454220-9a0c9b19-3441-4598-abe4-d2a11b8f28ad.png)

@stephenwaite if that is the case then this tooltip is incredibly misleading. Is it not possible for a user to register themselves for an account?

**Comment by stephenwaite** [comment]
oh, good point, the google recaptcha global was just added so maybe needs to be added to the tool tip.

**Comment by ajmeese7** [comment]
I'm not sure I understand, is it possible for patients to register themselves with this software? The clinic I am contracting for is entirely online and patients need to be able to create accounts without having yet interacted with a provider

**Comment by bradymiller** [comment]
yes, it is. for it to work, need to turn it on in globals and set up the google recaptcha:
```
If you are using Password Reset or Patient Registration features in the patient portal, then you will need to set up Google reCAPTCHA (version 2) and then place the key and secret in the following globals respectively:
Administration->Globals->Portal->Google reCAPTCHA V2 site key
Administration->Globals->Portal->Google reCAPTCHA V2 secret key
```

**Comment by ajmeese7** [comment]
Awesome, thanks for the info! I'll go try this out and come back with an update before I head to bed. If you don't mind, can you tell me where that info is located? I must've missed it somehow.

**Comment by bradymiller** [comment]
at this point, is a link in the new features wiki page that goes here:
https://www.open-emr.org/wiki/index.php/6-0-0-4_Patch_Special_Instructions
(in the overview section; this stuff was recently added to address security issues and it still needs to get into the main wiki portal documentation)

**Comment by bradymiller** [comment]
Do note the registration is meant for completely new patients (do not yet have a patient file in the emr). If the patient already exists, then the staff can create the portal account with a couple clicks in the patient summary screen (an email is sent to patient with the credentials in this case).

**Comment by ajmeese7** [comment]
@bradymiller it works, you're the man! Additional thanks to @stephenwaite, I appreciate you guys a ton. Thanks for the help! Closing this out now.
