### ISSUE TITLE
The onsite_activity_view view is breaking database restore

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#5096]
The onsite_activity_view view is breaking database restore when backup database and then restore with another database name since mysqldump of views included the database name, thus either will break on import or even worse will do a view with another database on the server (think multisite) if it happens to have the same database name as the mysqldump script:
  - link describing issue: https://jira.mariadb.org/browse/MDEV-22282
  - example of what a mysqldump looks like for view (note the `edu` database name is hardcoded):
```
/*!50001 VIEW `onsite_activity_view` AS select `edu`.`onsite_portal_activity`.`status` AS `status`,`edu`.`onsite_portal_activity`.`narrative` AS `narrative`,`edu`.`onsite_portal_activity`.`table_action` AS `table_action`,`edu`.`onsite_portal_activity`.`table_args` AS `table_args`,`edu`.`onsite_portal_activity`.`action_user` AS `action_user`,`edu`.`onsite_portal_activity`.`action_taken_time` AS `action_taken_time`,`edu`.`onsite_portal_activity`.`checksum` AS `checksum`,`edu`.`patient_data`.`title` AS `title`,`edu`.`patient_data`.`fname` AS `fname`,`edu`.`patient_data`.`lname` AS `lname`,`edu`.`patient_data`.`mname` AS `mname`,`edu`.`patient_data`.`DOB` AS `DOB`,`edu`.`patient_data`.`ss` AS `ss`,`edu`.`patient_data`.`street` AS `street`,`edu`.`patient_data`.`postal_code` AS `postal_code`,`edu`.`patient_data`.`city` AS `city`,`edu`.`patient_data`.`state` AS `state`,`edu`.`patient_data`.`referrerID` AS `referrerID`,`edu`.`patient_data`.`providerID` AS `providerID`,`edu`.`patient_data`.`ref_providerID` AS `ref_providerID`,`edu`.`patient_data`.`pubpid` AS `pubpid`,`edu`.`patient_data`.`care_team_provider` AS `care_team_provider`,`edu`.`users`.`username` AS `username`,`edu`.`users`.`authorized` AS `authorized`,`edu`.`users`.`fname` AS `ufname`,`edu`.`users`.`mname` AS `umname`,`edu`.`users`.`lname` AS `ulname`,`edu`.`users`.`facility` AS `facility`,`edu`.`users`.`active` AS `active`,`edu`.`users`.`title` AS `utitle`,`edu`.`users`.`physician_type` AS `physician_type`,`edu`.`onsite_portal_activity`.`date` AS `date`,`edu`.`onsite_portal_activity`.`require_audit` AS `require_audit`,`edu`.`onsite_portal_activity`.`pending_action` AS `pending_action`,`edu`.`onsite_portal_activity`.`action_taken` AS `action_taken`,`edu`.`onsite_portal_activity`.`id` AS `id`,`edu`.`onsite_portal_activity`.`activity` AS `activity`,`edu`.`onsite_portal_activity`.`patient_id` AS `patient_id` from ((`onsite_portal_activity` left join `patient_data` on(`edu`.`onsite_portal_activity`.`patient_id` = `edu`.`patient_data`.`pid`)) left join `users` on(`edu`.`patient_data`.`providerID` = `edu`.`users`.`id`)) */;
```

**Comment by bradymiller** [comment]
The onsite_activity_view view is built in real time, so plan to avoid this via mysqldump --ignore-table when do backups

**Comment by stephenwaite** [comment]
![excited_elephant](https://user-images.githubusercontent.com/5618372/162202800-52ff5b09-fbdb-4ee1-a2ff-ca046cd6282a.gif)

**Comment by sjpadgett** [comment]
For some reason on backups the view is converted to a table. This blows up the restore. A bug with engine as far as i'm concerned or backup flags are set incorrectly. Should set back up to not export views.
I'm no longer really need the view after last major portal shakeup and will finish removing it's need in audit once I get back to portal.
Still, there will be views in openemrs future as the are very useful if used correctly.

**Comment by bradymiller** [comment]
Figured out mechanism for this "bug" issue at:
https://github.com/openemr/openemr/issues/5096

The database backup does back it up as a view. The issue is that when it does a backup of the view, it also includes the database name in the column names. For example, this is taken from a database name `edu`:
```
/*!50001 VIEW `onsite_activity_view` AS select `edu`.`onsite_portal_activity`.`status` AS `status`,`edu`.`onsite_portal_activity`.`narrative` AS `narrative`,`edu`.`onsite_portal_activity`.`table_action` AS `table_action`,`edu`.`onsite_portal_activity`.`table_args` AS `table_args`,`edu`.`onsite_portal_activity`.`action_user` AS `action_user`,`edu`.`onsite_portal_activity`.`action_taken_time` AS `action_taken_time`,`edu`.`onsite_portal_activity`.`checksum` AS `checksum`,`edu`.`patient_data`.`title` AS `title`,`edu`.`patient_data`.`fname` AS `fname`,`edu`.`patient_data`.`lname` AS `lname`,`edu`.`patient_data`.`mname` AS `mname`,`edu`.`patient_data`.`DOB` AS `DOB`,`edu`.`patient_data`.`ss` AS `ss`,`edu`.`patient_data`.`street` AS `street`,`edu`.`patient_data`.`postal_code` AS `postal_code`,`edu`.`patient_data`.`city` AS `city`,`edu`.`patient_data`.`state` AS `state`,`edu`.`patient_data`.`referrerID` AS `referrerID`,`edu`.`patient_data`.`providerID` AS `providerID`,`edu`.`patient_data`.`ref_providerID` AS `ref_providerID`,`edu`.`patient_data`.`pubpid` AS `pubpid`,`edu`.`patient_data`.`care_team_provider` AS `care_team_provider`,`edu`.`users`.`username` AS `username`,`edu`.`users`.`authorized` AS `authorized`,`edu`.`users`.`fname` AS `ufname`,`edu`.`users`.`mname` AS `umname`,`edu`.`users`.`lname` AS `ulname`,`edu`.`users`.`facility` AS `facility`,`edu`.`users`.`active` AS `active`,`edu`.`users`.`title` AS `utitle`,`edu`.`users`.`physician_type` AS `physician_type`,`edu`.`onsite_portal_activity`.`date` AS `date`,`edu`.`onsite_portal_activity`.`require_audit` AS `require_audit`,`edu`.`onsite_portal_activity`.`pending_action` AS `pending_action`,`edu`.`onsite_portal_activity`.`action_taken` AS `action_taken`,`edu`.`onsite_portal_activity`.`id` AS `id`,`edu`.`onsite_portal_activity`.`activity` AS `activity`,`edu`.`onsite_portal_activity`.`patient_id` AS `patient_id` from ((`onsite_portal_activity` left join `patient_data` on(`edu`.`onsite_portal_activity`.`patient_id` = `edu`.`patient_data`.`pid`)) left join `users` on(`edu`.`patient_data`.`providerID` = `edu`.`users`.`id`)) */;
```
The bug has been posted here for mariadb and looks to me like will never be addressed: https://jira.mariadb.org/browse/MDEV-22282
So it will work just fine when doing a backup/restore into same database name, but will do two possibly bad things when try to restore into a different database name:
1. Most of the time, it will just break since the database `one` will not exists.
2. Some times it may work if there is a database on the mysql server with the same name, and in that case the view will actually be referencing data from a completely different database! (some may say this is rare, but this situation could actually arise in the multisite cloning feature)

Note the current workaround basically has to list each view separately so it is not saved in the mysql backup, which would not be feasible for either a view that needed to be persistent during backup/restore or if there more than several views. At this point (with needing to update several infrastructure points and knowing that folks will consistently do mysqlsump without the --ignore-table parameter leading to broken restores), my vote would be avoiding any more views until mysql and mariadb fix this bug.

**Comment by bradymiller** [comment]
lol, I thought this was the PR and just referenced my own issue and basically repeated things. Need more coffee :)

**Comment by sjpadgett** [comment]
> Need more coffee :)

who are we kidding Brady! all the coffee in the world doesn't turn back time. trust me, I've tried.:)
