### ISSUE TITLE
New FHIR Vitals Observations not retrievable due to missing UUID Registry records

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5127]
When we refactored the UUID mapping logic we broke retrieving new FHIR vitals observations as the mappings are generated but the uuid_registry value is not inserted into the database. This was discovered in the inferno api specifically because it attempted to retrieve a specfic observation with a data absent reason. 

We need to make it so we populate all of these missing values in the database as well as fixing the mapping uuid generation process.

Original Ticket Description:
When a vitals form is created UUIDMapping records are generated for every single column in the vitals form.  If the vitals property has a 0 value for columns such as blood pressure, etc, its supposed to generate a uuid for it. These empty values are then reported as missing with a Data Absent Reason (DAR).  However, we have a number of DAR being reported in inferno but when the resource is attempted to be fetched it returns as not found.

**Comment by sjpadgett** [comment]
@adunsulag where are you storing the DAR or how would that get entered via UI. 
I just ran into negated template for physical exam observation where I must store reason for negate.

**Comment by adunsulag** [comment]
[FhirObservationVitalsService](https://github.com/openemr/openemr/blob/81b2f41066daf34350b5fd5467e1198d0400f096/src/Services/FHIR/Observation/FhirObservationVitalsService.php#L654-L659)

We use a 0 value in vitals.

**Comment by sjpadgett** [comment]
FHIR may let you get away with UNK however in most all cases in QRDA and CDA a reason shall be given.
For FHIR https://build.fhir.org/valueset-procedure-not-performed-reason.html

Instead of modifying vitals I may be able to get away with creating an observation form entry. I wonder how this gets entered by clinicians! Or maybe add to vital_details

**Comment by adunsulag** [comment]
@sjpadgett I think form_vital_details would be the optimum place to store the reason code.  How to present it on the GUI... that I don't know.

**Comment by sjpadgett** [comment]
ho hum is all I have to say!:)
