### ISSUE TITLE
[APIs] Insurance_Company endpoint is returning an empty list even though it has records

### ISSUE THREAD

**Issue by 1antares1** [openemr/openemr#5144]
### Describe the bug

I'm trying to request the records from the endpoint: **Insurance_Company**:

And there are still records (the frontend displays them without problems, records with all fields filled, others mostly empty) and it returns an empty list from dispatch.php, on line: 371

$apiCallOutput = ob_get_clean();

### To Reproduce
`curl -X 'GET' \
   'https://eleven.openemr.io/a/openemr/apis/default/api/insurance_company' \
   -H 'accept: application/json'`

1. Exec the next script (request) with your current access_token with the app running from development-easy (docker-compose up) from the current API Swagger page.

`let bearer = "Bearer " + "eyuyeXAiOiJKV1QiLCJhbGciOiJSUzI1N219.eyJhdWQiOiJNVjVCdVJJOG1vNCo98a3NGTmNocm5NRGJxdFVic1lOVy1mS0E2cVgwUUljIiwianRpIjoiYjIwNzMzNTJmZDdkODVkNmJiYThjMzEwOWQ4YjgzNTIwYTNiNTk1ZTE0MTg2NWIyMzkzMDc4ZGRlYmRkMDNkZTkwYjQyOTU1OWUwNWEyZDIiLCJpYXQiOjE2NDk3MzI3MjcuNjcwMzY0LCJuYmYiOjE2NDk3MzI3MjcuNjcwMzY4LCJleHAiOjE2NDk3MzYzMjcuNjQ3NzE0LCJzdWIiOiI5NWZjMGJhMS1hY2Y4LTQwZjUtODhkNy02MjViM2E3NThhMxMiLCJzY29wZXMiOlsib3BlbmlkIiwiYXBpOm9lbXIiLCJhczk69mhpciIsImFwaTpwb3J0IiwidXNlci9pbnN1cmFuY2UucmVhZCIsInVzZXIvaW5zdXJhbmNlLndyaXRlIiwidXNlci9pbnN1cmFuY2VfY29tcGFueS5yZWFkIiwidXNlci9pbnN1cmFuY2VfY29tcGFueS53cml0ZSIsInVzZXIvaW5zdXJhbmNlX3R5cGUucmVhZCIsInVzZXIvcGF0aWVudC5yZWFkIiwidXNlci9wYXRpZW50LndyaXRlIiwidXNlci9QYXRpZW50LnJlYWQiLCJ1c2VyL1BhdGllbnQud3JpdGUiLCJ1c2VyL2xpc3QucmVhZCIsInBhdGllbnQvcGF0aWVudC5yZWFkIiwicGF0aWVudC9QYXRpZW50LnJlYWQiLCJzaXRlOmRlZmF1bHQiXX0.rfgHAyTMxsBSEvju0Qwn1kHpGd3Yw2NXZ7A2GGruul5AxL5uGMOKnWeC4f_sFhEWUerE9Dn7ROmMNTl1oQarDnMwKAJAZ8TloD1Qj6K9R50WWpWMfp0LHy8NEuVC_RVxQZyvTQl2fICWtCVnF-mY3PTeCbZ1IE4TovUuroGCnntFTfWg0SU4dmokBU-pjBnamazdAclkqh9mat08OGwMrDVIA101q0RIQw2NDwC7m7kedqEnOKKfv-u5wD5yPcEOE70V5YcxigTxVKDXvSdDykS2BIABiDUdt-hT_mHgctu5i8rFusloqKxvIjQWYn4dL2wbibnsnpQZAlj9Zf9ymw";
fetch("https://localhost:9300/apis/default/api/insurance_company", {
        method: 'GET',
        withCredentials: true,
        credentials: 'include',
        headers: {
            'Authorization': bearer,
            'Content-Type': 'application/json'
        }
    }).then(function(response) {
        return response.json();
    }).then(function(data) {
        console.log(data);
    })
    .catch(function(error) {
        console.log(error);
    });`
5. See error

### Expected behavior
`{
    data: [{...insuranceCompany0}, {...insuranceCompany1}, {...insuranceCompany2}],
    internalErrors: [],
    validationErrors: []
}`

![image](https://user-images.githubusercontent.com/14783925/162873087-1b79618f-84f2-446e-a685-45ef98870f15.png)

### Result received
`"{}"`

![image](https://user-images.githubusercontent.com/14783925/162873124-8190d00f-5f49-4742-8b12-1bb76f97d4d5.png)

### Client configuration

- Browser: Any browser and REST Clients: Postman, JavaScript raw, Hoppscotch,
- OpenEMR version: Current.
- Operating system: Windows.

**Comment by 1antares1** [comment]
For some reason the `json_encode()` function from the file: **HttpRestRouteHandler.php** was failing if these properties from the **ProcessingResult** file:

https://github.com/openemr/openemr/blob/ce7beaabf791185302c6204509616d440208dde5/src/Validators/ProcessingResult.php#L23)

These are marked as private. What I don't know is because with another Patient endpoint, it works but with Insurance_Company it doesn't.

I changed them to public and that's it. Any reason why this happens?

**Comment by adunsulag** [comment]
@1antares1 So it looks like when whoever originally wrote the ProcessingResult class and introduced it into all of the standard apis did not put in the appropriate handling code for the Insurance route.  Compare InsuranceCompanyRestController::getOne() with ImmunizationRestController::getOne().  There is supposed to be a call to RestControllerHelper::handleProcessingResult which handles the JSON serialization of ProcessingResult.  Since ProcessingResult does not implement the JsonSerializable the JSON encode fails as there are no public properties for the encoder to grab.  

So the correct step that needs to be done is change up InsuranceCompanyRestController to call the handleProcessingResult function for the getOne and getAll functions.  Sounds like a great pull request if you want to code it up.

**Comment by 1antares1** [comment]
@adunsulag Thanks for your prompt reply, Mr.

Exactly, that's what happened and now I understood it better.

Also, coincidentally the `getOne();` of **InsuranceCompanyRestController** and `getAll();` of I**nsuranceCompanyService();** it was also necessary to refactor similar to Immunization Logic with search by **UUID** and not IID (id), I was throwing 500 Internal Server Error the InsuranceCompanyById.

The results would look like this:

![image](https://user-images.githubusercontent.com/14783925/162999869-46ace4eb-0c37-4392-bcf7-f45bbf5fd255.png)
