### ISSUE TITLE
Documentation/INSTALL needs updating and correcting

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#5148]
The following quotations are from Documentation/INSTALL, which I suggest needs updating in various ways.

"Alternatively a Debian package may be available as a file named
openemr-<version>.deb.  This may work with some other Debian-like
Linux distributions such as Ubuntu."

As far as I know there is no longer Debian packages provided.

"To run OpenEMR, MySQL and Apache or another PHP-capable webserver must be configured.
To download Apache, visit www.apache.org
For information on how to install MySQL, visit www.mysql.com
PHP may be downloaded from www.php.net"

Add that instead, when using Linux it may be preferable to instead get these via your distribution's package repository.

"Reading openemr/sites/default/config.php is a good idea. This file contains some
options to choose from including themes."

There is no mention of "themes" in that file.

"To create custom encounter forms, see the files
  openemr/Documentation/3rd Party Form API.txt"

This file doesn't exist.

  "openemr/interface/forms/OpenEMR_form_example-rev2.tar.gz"

This file doesn't exist.

"and read the included documentation and online documentation at www.openemr.org."

WRONG URL

"Other configuration settings are stored under includes/config.php."

There is no "includes" folder.

"IV. Setting Up Access Control

Since OpenEMR version 2.9.0.3, phpGACL access controls are installed and
configured automatically during OpenEMR setup.  It can be administered
within OpenEMR in the admin->acl menu."

Does it need mentioning how long this has been present in OpenEMR if it has been included for so long?

It is instead available at Administration > ACL.

"V. Upgrading

The following directories should be copied from the old version to the
new version:

  openemr/sites/default/documents
  openemr/sites/default/era
  openemr/sites/default/edi
  openemr/sites/default/letter_templates"

These are instead at:
openemr/sites/default/documents/era
openemr/sites/default/documents/edi
openemr/sites/default/documents/letter_templates

**Comment by pete-boyd** [comment]
@stephenwaite I tried creating a pull request, it said to create a pull requestr I needed to compare 2 branches, which I did. Now my pull request contains numerous historic commits. I'm confused. And there appears to be no option to delete the pull request. The Github documentation appears to say that I need to first create a topic branch, before creating a pull request, but I see no option to create a topic branch.

**Comment by stephenwaite** [comment]
ok, checkout the [wiki](https://www.open-emr.org/wiki/index.php/Using_Git_with_OpenEMR) for tips with git.

You'll basically clone the official openemr repo and then make your own branch and push your changes. That will trigger github to help create your PR.

**Comment by stephenwaite** [comment]
You prob can edit the files in your browser on your clone of the repo and achieve the same result.

**Comment by stephenwaite** [comment]
*fork, right, thanks @adunsulag

**Comment by pete-boyd** [comment]
I'm on my way now, thanks.

**Comment by pete-boyd** [comment]
"The first screen of the setup script will ensure that the webserver user
(in Linux, often is "apache", "www-data", or "nobody") has write privileges on
certain files and directories.  The file is openemr/sites/default/sqlconf.php.
In Linux, this can be set by "chmod a+w filename" command to grant global write
permissions to the file."

We shouldn't be recommending a+w for openemr/sites/default/sqlconf.php.

**Comment by mdsupport** [comment]
> We shouldn't be recommending a+w for openemr/sites/default/sqlconf.php.
Setup uses root database user to create EMR database with full grants to specified user. Those database name and user details are written to sqlconf. After setup is complete that file can/should not be writable.
