### ISSUE TITLE
FHIR Goal Resources dueDate has an invalid date format

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5169]
The public version of inferno using our live MU3 demos are failing on the Single Patient API tests for Goals. Not sure what has changed here or if the public inferno is doing something different than the locally hosted version.

The error that is occurring is:
> Invalid Goal: Goal.target[0].due.ofType(date): Not a valid date (Invalid date/time format: "2021-05-14 00:00:00": Expected character 'T' at index 10 but found ) * Goal.target[1].due.ofType(date): Not a valid date (Invalid date/time format: "2021-05-26 00:00:00": Expected character 'T' at index 10 but found ) * Goal.target[0].due.ofType(date): Not a valid date ({0}) * Goal.target[1].due.ofType(date): Not a valid date ({0})

**Comment by adunsulag** [comment]
Looks like this happened when @sjpadgett brought in #5143.  I'll need to check and see if FHIR's Goal takes a Y-m-d or has a timestamp involved as well.

**Comment by sjpadgett** [comment]
it should

**Comment by adunsulag** [comment]
@sjpadgett 
![image](https://user-images.githubusercontent.com/228117/163653715-4aa59ee7-2093-41e6-9b62-a0173d409908.png)

![image](https://user-images.githubusercontent.com/228117/163653879-0304374f-3f6b-41fa-9865-ee3d72e31da8.png)

I can use a Duration but that's a single value express in seconds, minutes,hours, etc.  

What I will do in FHIR is just take the datetime value and just grab the Date.  Not sure why CCDA and QRDA use a DateTime for Goals and FHIR is a datetime.  Maybe FHIR R5 will fix it.

**Comment by sjpadgett** [comment]
where you getting duration. as far as I know we only allow for a goal type and code. The code may have I timeframe otherwise, that's it.

**Comment by adunsulag** [comment]
@sjpadgett yea, not going to go the duration route, will just stick with the Goal's datetime and grab just the date field in FHIR (which will leave it alone for what y'all need).

**Comment by mdsupport** [comment]
Seems like all datetimes should follow [ISO_INSTANT](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_INSTANT) specified by java formatter unless we are including zone offsets as well.

**Comment by adunsulag** [comment]
@mdsupport We use ISO8601 for most of our DateTimes reported via FHIR.  However, some fields in FHIR are reported as dates where as CCDA/QRDA report times differently.  I don't know what format they use but I would guess its ISO8601 as well (hopefully).
