### ISSUE TITLE
FHIR Refresh Token set patient context

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5191]
Inferno is giving a warning saying that refresh token is missing context.  Need to populate session context for the refresh token even if the user provides no scopes or a subset of the scopes.

We were keying off the launch/patient scope in the access token to renew scopes in the refresh token.  However, if a refresh token is requested and its missing the launch/patient scope apparently per inferno we still need to bind up the context values into the access token.

**Comment by sjpadgett** [comment]
Test are not supposed to fail on warnings. CQM or CCDA do not. I fear if you try to chase down all warnings, you'll quit in frustration!

**Comment by adunsulag** [comment]
@sjpadgett Hopefully CQM/CCDA are different but the inferno and HL7 spec writers on their fhir chat server are stating that if inferno throws a warning its up to the testing authority to determine whether to fail the test or not based upon the warning. This one seems pretty odd so I'm not sure I'll fix this, but the others uncovered some major problems (such as what we ran into with the language codes this morning).

**Comment by adunsulag** [comment]
@sjpadgett Fortunately I have this one and the document codes and I believe those are the last two!  (At least for my local box, we'll see what happens on the demo machines).

**Comment by sjpadgett** [comment]
Cool, good work.
