### ISSUE TITLE
Patient portal self-registration problem

### ISSUE THREAD

**Issue by gutiersa** [openemr/openemr#5214]
### Describe the bug
Enabling Patient portal self registration in globals does not seem to be working.

write concise description of what the bug is.

### To Reproduce
Admin -> globals -> portal -> tick enable self registration
I tried it in the demo also.

### Expected behavior
The register button should be enabled on the patient portal login page.

### Client configuration

- Browser: chrome and firefox
- OpenEMR version: 6.1.0
- Operating system: client windows, server both windows and freebsd

**Comment by stephenwaite** [comment]
does this [recent issue](https://github.com/openemr/openemr/issues/5084#issuecomment-1086984298) help @gutiersa ?

**Comment by gutiersa** [comment]
Hmm, I do have re-captcha enabled in my FreeBSD server OpenEMR, but can you get Recaptcha for localhost (test server)? I have to look into that.

**Comment by gutiersa** [comment]
So, I went back and ran an sql_upgrade.php on my system. I went back all the way to version 5.0.0
That fixed the problem, and of course, I added the re-captcha
