### ISSUE TITLE
Direct Message Send with uploaded document

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5220]
Just discovered that we need to be able to send an uploaded document via the (h)(1) process.  Originally I thought this was just sending a ccda we generated via Direct.  Instead we have to download a document from the Edge Testing Tool (ETT) and then send that via the EMR interface.  

In order to make it so we can send user uploaded documents we should add a button or a dropdown type to the Messages interface to 'Send Trusted Message'  that allows you to select an uploaded file.  In the interest of time for our certification I make it so you can only select CCDA documents as that's one of the available files from the ETT that we can test against.  Its less useful but we can expand it in the future.

**Comment by adunsulag** [comment]
So what I've put together to make this work is  the following.  In the messages screen there is a button now to compose a new trusted direct message.
![image](https://user-images.githubusercontent.com/228117/164789017-4ac85b75-7a93-427a-9262-fc4c0b0c1392.png)

That button opens up the following screen:
![image](https://user-images.githubusercontent.com/228117/164789092-ecf5055a-9e36-49c4-8bd4-5a24d2bec5aa.png)

If there is a patient selected already in context it will populate it in the patient field.  Clicking the patient field opens up the patient finder to choose a patient.  The way EMRDirect's message sending is done you HAVE to have a patient to send a message.  

The system will validate the fields before sending to make sure the data is filled out properly.  In order to send a trusted message you have to include  something in the message body OR have a document attached. 
![image](https://user-images.githubusercontent.com/228117/164789360-6821cb95-7c23-4fdc-a801-5720769b3ed8.png)

If you attempt to send a message to an invalid trusted address (as validated by EMRDirect) it will display an error message:
![image](https://user-images.githubusercontent.com/228117/164789610-485ac8e6-295f-4864-9fbc-193ab72f3ddb.png)

If you send an email to a valid trusted email address it will display a success message and reset the form.
![image](https://user-images.githubusercontent.com/228117/164789714-50c4fc36-db82-46cd-b65e-a1b5677083fe.png)

As part of this project I built a document selector widget based on the patient finder popup. 
![image](https://user-images.githubusercontent.com/228117/164789841-3def8678-4d79-4fde-9e69-26e9c5753082.png)

It retrieves up to 25 documents at a time.  Anything more has to use the search functionality to narrow the search down.  It searches documents for the currently selected patient.  Note it also checks all of the ACLs for the documents to make sure that the currently logged in user only sees documents for which they have permission to access as per their ACLs.

**Comment by sjpadgett** [comment]
> It retrieves up to 25 documents at a time

I think it should be 26! I pretty sure that's in a spec somewhere! lol

**Comment by adunsulag** [comment]
@sjpadgett I actually grab 26 records and use that to determine if I hit my 25 max :)

**Comment by sjpadgett** [comment]
Well then I happy!

**Comment by bradymiller** [comment]
![118382341-53d9d600-b5c2-11eb-8b7e-220bbab8468a](https://user-images.githubusercontent.com/278968/164890382-251fe49a-d88a-48a1-8585-aecc9792e699.gif)
