### ISSUE TITLE
Incorrect Display of LBF Used by Demographics

### ISSUE THREAD

**Issue by psoas** [openemr/openemr#5240]
### Describe the bug
For the demographics LBF layout, in a field:
If you set label columns to 0 and it is in the first column, the label still uses the first column and the data starts in the second column.  

However, this only occurs if you display the demographics.  If you edit demographics, it is displayed properly.

### To Reproduce
–insert a field of datatype textbox into demographics layout
–leave label blank
–label cols = 0
–data cols = 4
–options = “Jump to next row”
-save changes
–go to demographics, enter info into new textbox, and click save.

In display mode, the textbox data is in column 2 instead of column 1. (wrong)
In edit mode, the textbox is in column 1. (correct)

I also, recreated the problem on the development demo, changing the layout of social security number to label cols = 0 and adding option jump to next row.

### Expected behavior
In display mode, the textbox data should be in column 1, not column 2.

### Client configuration
- Browser:  Firefox
- OpenEMR version:  Latest Development Version

The problem is with the display of LBF used by demographics, likely in the function "display_layout_tabs_data" in the file /library/options.inc.

**Comment by sjpadgett** [comment]
Not a bug IMO. Doubtful I'll work on and something perhaps your team can address(get it address:))

**Comment by sjpadgett** [comment]
@psoas 
Try changing L-70 to this: `$BS_COL_CLASS = 'col-12 col-md-auto col-sm';`

**Comment by psoas** [comment]
Unfortunately, that change makes it worse.
After the change, display mode is the same (not displaying correctly).  
However, edit mode now indents it (when before, edit mode displayed it correctly.)

**Comment by sjpadgett** [comment]
try col-sm to col-md

**Comment by psoas** [comment]
I think I have an idea of the problem but I cannot get my php debugger using VS Code working (using VS Code) to see what is going on.
Label columns in layout admin is same as $titlecols in the code.
When layout columns is set to 0, it should not echo a <td> for the label, but it is.  Somehow, $titlecols is being changed from 0 to 1.
The only place in the code where that happens is line 3622:
if ($item_count == 0 && $titlecols == 0) {
             $titlecols = 1;
}
BUT, this should not be happenning, because $item_count should not be 0.
Without getting my debugger to work, I can't see what is really happening.

**Comment by psoas** [comment]
Since I have been adding code, my line numbers are different.
Deleting the following fixes my problem:

if ($item_count == 0 && $titlecols == 0) {
$titlecols = 1;
}

However, it causes a blank line at the top.  So, those lines serve a purpose.  Therefore, it needs to be changed, not deleted.  I just need to figure out the purpose.  Don't have time right now, need to do my day job.

**Comment by psoas** [comment]
I fixed the bug and now it works correctly!  My first bug fix!

Now, I need to figure out how to contribute it.
