### ISSUE TITLE
MSIE fails with tabs layout

### ISSUE THREAD

**Issue by sunsetsystems** [openemr/openemr#525]
Testing with MSIE in Windows 10, I see the Tabs layout occupies the left 1/5 or so of the page, with the remainder blank. See attached image.
![msie_tabs](https://cloud.githubusercontent.com/assets/386879/23682271/bdcc1550-0347-11e7-81b7-30df8dc661d0.jpg)

**Comment by MatthewVita** [comment]
To be fair: https://github.com/openemr/openemr/blob/master/setup.php#L187-L188

**Comment by sunsetsystems** [comment]
Well I get that, but MSIE still has close to 20% market share. If one little bug makes it unusable it should be fixed.

**Comment by bradymiller** [comment]
I vote for a fix :)

**Comment by sjpadgett** [comment]
Will most likely need to wrap iframe in div.

**Comment by sjpadgett** [comment]
Here is a fix that works for me in Edge. Add a width to frame in tabs_style_???.css
#framesDisplay > div > iframe
{
    flex: 1 0 auto;
    border: 0px solid black;
    **width: 100%**
}

**Comment by sunsetsystems** [comment]
Awesome. That works for me too.

**Comment by sunsetsystems** [comment]
Jerry why don't you make a PR so you'll get credit for it.

**Comment by sjpadgett** [comment]
okay, just going to test in chrome then I'll put it up.

**Comment by MatthewVita** [comment]
Nice fix! Btw, I am for a fix, I was just noting the supported browsers so one doesn't spend too much time on this (I'm sure at least 1/4th of my craziness comes from trying to support IE in my relatively short career so far :) )

**Comment by robertdown** [comment]
@sjpadgett have you had a chance to submit a PR for this?

@MatthewVita Would be great to drop support for MSIE (It's a dead browser ((would still have to support Edge))) but I imagine that's a losing battle :)

**Comment by bradymiller** [comment]
Sorry, we forgot to close this. The PR for this was submitted and accepted.
