### ISSUE TITLE
CQM Observation Form need reason and reason status fields

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5255]
Observation form needs fields for entering in a reason status and reason code for the observation in order to support the Clinical Quality Measures (CQM) work for observations.

**Comment by adunsulag** [comment]
@stephenwaite @sjpadgett 

Sample of the reason code and status selector.
![image](https://user-images.githubusercontent.com/228117/166072606-28e41f0b-4f7b-4860-a040-ca2b169ff005.png)

Was a bit tricky to figure out how to support two different code selectors for different kinds of post data, but I got that worked out I believe.

Here is what the vitals form looks like.
![image](https://user-images.githubusercontent.com/228117/166074097-0eabfffe-2da9-4c51-817d-5ef47880e629.png)

**Comment by sjpadgett** [comment]
This is fine however, negation is not the only time a reason code would be provided. Plus, most clinicians probably wouldn't know what a negation is.
I'd pull the negation verbiage and let negate be a status. 

Still, I'm not sure how to apply negation to a reason unless told by test. I'll see if I can't find a reson with and without negation to show an example for you.

**Comment by adunsulag** [comment]
K, if we can find the right terminology here, that would be ideal.  I thought the reason codes were exclusively for negation.  We could just call it Reason Code, Reason Status, and the title would be **BP Systolic Reason Information** or for Observations, **Observation Reason Information**.

**Comment by sjpadgett** [comment]
Sounds good. I thought I stressed reason could be possible w/o negation so, sorry. My brain is not ideally working these days!:)
Here is an example of reason w/o being negated.
```
<entry>
              <act classCode="ACT" moodCode="EVN" >
                <!-- Consolidation CDA: Procedure Activity Act template -->
                <templateId root="2.16.840.1.113883.10.20.22.4.12" extension="2014-06-09"/>
                <!-- Intervention Performed Template -->
                <templateId root="2.16.840.1.113883.10.20.24.3.32" extension="2019-12-01"/>
                <id root="1.3.6.1.4.1.115" extension="625789d563623902ea79a95a"/>
                  <code code="386464006" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMEDCT"/>
                <text>Follow Up for Above Normal BMI</text>
                <statusCode code="completed"/>
                <effectiveTime value='20201213080000'/>
                  <!-- QDM Attribute: Reason -->
                  <entryRelationship typeCode="RSON">
                    <observation classCode="OBS" moodCode="EVN">
                      <templateId root="2.16.840.1.113883.10.20.24.3.88" extension="2017-08-01"/>
                      <code code="77301-0" codeSystem="2.16.840.1.113883.6.1" displayName="reason" codeSystemName="LOINC"/>
                      <value code="248342006" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMEDCT" xsi:type="CD"/>
                    </observation>
                  </entryRelationship>              </act>
            </entry>
```

We can speak more offline if you want.

**Comment by adunsulag** [comment]
Sounds good, I'll update the terminology.  I guess I'll have to figure out a different icon lol. 

In that example you pasted are there two different codes we need to be collecting?
```
<code code="77301-0" codeSystem="2.16.840.1.113883.6.1" displayName="reason" codeSystemName="LOINC"/>
                      <value code="248342006" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMEDCT" xsi:type="CD"/>
```

**Comment by sjpadgett** [comment]
> <code code="77301-0"

Generally with all template you will have a code that describes the template, Reason care action performed or not, in this case and then a value code to describe the actual event,  value code="248342006" (Underweight) in this case.

**Comment by adunsulag** [comment]
@sjpadgett Better?
![image](https://user-images.githubusercontent.com/228117/166078032-1ee2dc28-b89e-4958-a39a-2cfb352b1856.png)

![image](https://user-images.githubusercontent.com/228117/166078313-68dfc3ee-2425-4614-b3d7-56e81c3655a3.png)

**Comment by sjpadgett** [comment]
Looks okay to me. Don't forget datetime change. Should just have to replace date with datetime in tagged location class(depending if that's the way it was named) and widget.

**Comment by adunsulag** [comment]
@sjpadgett My latest PR fixes the datetime issue.  I'll move on next to adding in the support for the careplan fields.
