### ISSUE TITLE
CQM Encounter Form needs the encounter_type code selector

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5260]
### Describe the problem
User can enter the proper value for the `QDM::EncounterPerformed` so that the QRDA export can include this required value for reporting.

### Describe the solution you'd like

Expose a selector in the encounter form for the already existing field in `form_encounter` like the other items in that form:

![Screenshot from 2022-04-27 22-06-43](https://user-images.githubusercontent.com/5618372/165661947-b3373862-757a-4985-8aa5-3d5eeb614f74.png)

**Comment by stephenwaite** [comment]
easiest approach will probably be to follow what you did for `Class` and the [value set codes for office visit](https://vsac.nlm.nih.gov/valueset/2.16.840.1.113883.3.464.1003.101.12.1001/expansion/eCQM%20Update%202021-05-06) to `list_options` table unless we can somehow parse them from the value_sets.json in `node_modules/oe-cqm-parsers/json_measures/CMS124v10/value_sets.json` for example

**Comment by adunsulag** [comment]
Looks like we still have a broken issue with cpt4 codes breaking.  Re-opening this issue.
