### ISSUE TITLE
QRDA I Report shows all measure

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5270]
### Describe the bug
@kchapple 
Can you look into when generating a cat1 report for single patient with all measures the report returns all the measures in Measures(Section two) regardless if patient meets each measure?

![QRDA-Incidence-Report](https://user-images.githubusercontent.com/1859985/166340782-6eabfa60-af36-4e80-ba0a-a1f5e01b8f59.png)

**Comment by sjpadgett** [comment]
I don't think this will be required for testing however, will be for MIPS/CMS reporting.

**Comment by adunsulag** [comment]
This worked and was necessary for testing.
