### ISSUE TITLE
Trouble matching dual and hyphenated 

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#5282]
### Describe the bug
We have a lot of patients with dual and hyphenated last names.
 
write concise description of what the bug is.
This is causing a lot of orphan file requests when parsing lab results. 

### To Reproduce

1. Add a patient with two last names both with a space and with a hyphen
2. receive a lab result for that patient 
3. See orphan file request pop up because no exact match for the patient was found
4. Then match the patient and watch the system ask again for the same patient to be matched. 

### Expected behavior
This was really an exercise in improving the query that is used to match the patient to the result.
The query is a more modern approach using the power of MySQL to do the matching. 

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by stephenwaite** [comment]
> 4\. Then match the patient and watch the system ask again for the same patient to be matched.

is it asking again after already selecting or are you saying when another result comes in later?
