### ISSUE TITLE
ONC (G)(9) generate ccda operation in FHIR

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5284]
We need an operation to generate a ccda with a patient uuid and a date range added to our FHIR.  Perhaps something like $generate-ccda or $export-ccda.  We will need to add it to our FHIR documentation as well.  This meets the criteria for our (g)(9) data export for generating a Continuity of Care document.  

-- Edited on June 18th
Outstanding Sub Issues
- #5506 
- #5508

**Comment by adunsulag** [comment]
Looks like this is already supported with the $docref operation in US-Core.  http://hl7.org/fhir/us/core/StructureDefinition-us-core-documentreference.html#mandatory-operation

http://hl7.org/fhir/us/core/OperationDefinition-docref.html   What we will do is return an empty data set for any search parameter other than our CCD for now as this operation is intended to generate/create new documents.  We can add additional documents that are needed to be generated as future needs require.

For CCDA we will use the LOINC code of  34133-9 (Summary of episode note) for a C-CDA Clinical Summary of Care (CCD).  If no code is provided we need to return the most current CCD that exists for the patient.

The operation takes a start and end date so it works fine for (g)(9).

**Comment by adunsulag** [comment]
I created a new sample module that people can use to play with both the SMART on FHIR apis and export a ccda using the apis.

Here is the link available on composer https://packagist.org/packages/adunsulag/oe-module-g9-ccda-exporter
So a ```composer require adunsulag/oe-module-g9-ccda-exporter``` will install the module.

Here are some sample screenshots of what this module does:

Adds menu options to set the registered client id and client secret key.  (Eventually I'd like this to auto-register an app, but for now in the interest of time, you have to do this step manually).
![image](https://user-images.githubusercontent.com/228117/169623460-b67f1cde-d517-41e1-b283-5345eed9f5f5.png)

Next it adds a menu item under the Modules table that takes you to this index page (instructions for redirect_uri and launch_uri are in the Registration Instructions link).
![image](https://user-images.githubusercontent.com/228117/169623491-7379d942-4127-49bb-9822-b67cb0363ea5.png)

Clicking on launch CCDA exporter takes you to the oauth2 authentication screen. 
![image](https://user-images.githubusercontent.com/228117/169623530-a79d9338-a251-4e8f-a510-1f6652f08024.png)

It's using the launch/patient permissions so once you authenticate you need to select a patient.
![image](https://user-images.githubusercontent.com/228117/169623560-96198c7a-a444-4704-aba7-dd281625421b.png)

Once a patient is selected you authorize your permissions.  note under the DocumentReference permissions it shows the $docref permission to generate a CCD document.
![image](https://user-images.githubusercontent.com/228117/169623586-5c2526a8-0ea2-4826-90b6-166b921b9f4f.png)

Next is shows an example of retrieving and display the patient resource and gives you the ccda generate options.
![image](https://user-images.githubusercontent.com/228117/169623613-c7cbb57c-9341-49a1-b958-d92671b572c1.png)

See the generated CCDA here:
![image](https://user-images.githubusercontent.com/228117/169623717-1672a022-2e79-4a69-8d4e-59c5f5a26e97.png)

Hit the download button to get the generated file:
![image](https://user-images.githubusercontent.com/228117/169623741-c6d9b3ce-88c5-4d86-9bd2-358071ff56e0.png)

Snippet of downloaded xml file.
![image](https://user-images.githubusercontent.com/228117/169623787-e4cd1dde-a5f8-4928-8cec-99ed09cd8528.png)

**Comment by adunsulag** [comment]
Here is the same thing that can be done with swagger, first register a client
![image](https://user-images.githubusercontent.com/228117/173677568-41946aa9-2b6d-4a20-a6c3-555dd1d68fe2.png)

provide the patient scopes and launch selector
![image](https://user-images.githubusercontent.com/228117/173677693-02edb516-e647-4a2d-b153-53c6cb988960.png)

Make sure we can grab the patient information, DocumentReference, and Document scopes.
![image](https://user-images.githubusercontent.com/228117/173677754-756d116b-702e-4f0c-ba17-b6de19e9e88b.png)


Now go to authorize in swagger.  Make sure to request the same scopes that was done in registration
![image](https://user-images.githubusercontent.com/228117/173678196-fbe03749-f2db-4e49-881e-c6ad8f1154b2.png)

Login with an openemr user and then select a patient (this is what launch/patient) scope does.

![image](https://user-images.githubusercontent.com/228117/173680921-872768ab-3378-40a5-a1f4-025d808950db.png)

Now authorize the scopes
![image](https://user-images.githubusercontent.com/228117/173678389-29a0d82d-c66d-440b-b723-07032383890a.png)


Now we need to get our patient id as swagger doesn't show this.  We'll do this by just hitting the patient endpoint.  Since we selected a patient with launch/patient our fhir/Patient endpoint will return just the patient we want.
![image](https://user-images.githubusercontent.com/228117/173681249-96728b25-86ab-44c3-b933-af38019b2db4.png)

At that point we grab the patient uuid and plug it into our $docref endpoint to generate a new ccda.  Dates can be specified here as part of the test
![image](https://user-images.githubusercontent.com/228117/173680519-6f1e7886-ad1e-4bf5-9125-b3e539328091.png)

When we run the test we get back a generated DocumentReference.  The URL to download the CCDA is in the entry.content.attachment.url field as highlighted in this screen shot.
![image](https://user-images.githubusercontent.com/228117/173681705-494e2434-14c8-4394-b9ba-f4a96c975a4e.png)

We copy the uuid for the Document and then hit the swagger /fhir/Document/{id}/binary endpoint to grab the URL.
![image](https://user-images.githubusercontent.com/228117/173681834-f3e337c1-78a6-4ab3-b669-7a099ae9e411.png)

When you hit the execute button on the endpoint swagger will fetch the file and give you a download link to download the file:
![image](https://user-images.githubusercontent.com/228117/173681970-abba4cc9-2c47-4a71-b6c5-adec7a7a6f41.png)

**Comment by adunsulag** [comment]
@bradymiller with my changes in #5488 you should be able to run through swagger to do the $docref operation to generate a ccda for g9.

**Comment by sjpadgett** [comment]
Is this running off the ccda generate event or the generate() method?

**Comment by adunsulag** [comment]
We completed this issue.
