### ISSUE TITLE
CMS eCQMs testing C1 record entry, export and import into Cypress for testing

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5286]
As a user of OpenEMR, I want to chart a visit into the EMR by entering the required data criteria and then use the Care Coordination Module to export a QRDA I for the electronic Clinical Quality Measure `eCQM` of my choosing so that Cypress will mark my `eCQM` as successfully passing validation.

**Comment by sjpadgett** [comment]
@stephenwaite Are you needing to know how to do this or is this just issue tracking?

**Comment by stephenwaite** [comment]
everything is passing, thank you @sjpadgett @adunsulag @bradymiller !
![jumping](https://user-images.githubusercontent.com/5618372/170781587-32202324-9e56-440a-ac47-5c76d6dcc870.gif)

**Comment by sjpadgett** [comment]
> @sjpadgett, is there another `.xsl` so we can view all of the data from the QRDA I export in a browser? Here's the one that comes bundled (renamed to .txt so could upload) [qrda.txt](https://github.com/openemr/openemr/files/8632030/qrda.txt)
> 
> the `.xml` also doesn't have this associated with it so just opens as raw xml

@stephenwaite so you know I do include the xsl and create a html file. it just doesn't work and the style sheet given with qrda is a cda style sheet. interface/modules/zend_modules/public/xsl/qrda.xsl
