### ISSUE TITLE
QRDA I export of eCQM uses CPT4 instead of CPT for codeSystemName

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5287]
### Describe the bug

QRDA I export of eCQM uses CPT4 instead of CPT for `codeSystemName`
child of #5286 

### To Reproduce
![Screenshot from 2022-05-04 21-40-56](https://user-images.githubusercontent.com/5618372/166852556-79682c78-1ea2-4704-867a-189cd05ed88e.png)

**Comment by sjpadgett** [comment]
it's the codesystem that is looked at and not the codesystemname.
I don't see an issue. oid 2.16.840.1.113883.6.12 is ama cpt4
