### ISSUE TITLE
Need to add subtype(category) to medical problems

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5303]
Need a way to classify medical problems with subtypes. e.g. concern, assessment etc.
I've added to existing list concern and assessment. So far those are all needed thus far but I suspect more will be needed.
I will add the subtype to issues GUI

**Comment by sjpadgett** [comment]
![image](https://user-images.githubusercontent.com/1859985/167324071-a48f0291-31f3-43a1-9e65-799b2759a853.png)

**Comment by stephenwaite** [comment]
thanks @sjpadgett , will close #2826
