### ISSUE TITLE
code selector for procedure order field Identifying Code

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5304]
think we can get away with prefixing the code with `SNOMED CT:` for procedure orders but maybe we should add the `find_code_popup`?
![Screenshot from 2022-05-08 21-28-48](https://user-images.githubusercontent.com/5618372/167325764-747f66f3-d450-4ffe-8e98-23871c10e051.png)

child of #5286

**Comment by adunsulag** [comment]
@stephenwaite Is the QRDA requiring it to be a SNOMED code?  I'm guessing so.  I wonder how this all is supposed to work with FHIR reporting as FHIR observations are required to only report back data that uses LOINC codes (its why we added the Standard Code).  

I would have thought Identifying Code already had a popup, if not I do think we should add it.
