### ISSUE TITLE
Install mechanism for our Node Services

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5317]
Our latest development cycle has sort of forced us into having to develop a post install for our ever growing number of node services.

Currently for production needs we have:
- oe-cqm-service used by our QRDA III calculator.
- ccda service used to generate various ToC C-CDA documents
- oe-schematron-service a new service I'm currently working on.

For the future I'd expect this list will grow. For oe-cqm-service note it is currently called in following. Also note that even though we do copy the service to public on build, all the other dependencies to support are not:
```
class CqmServiceManager
{
    public static function makeCqmClient()
    {
        $servicePath = $GLOBALS['fileroot'] . DIRECTORY_SEPARATOR .
            'node_modules' . DIRECTORY_SEPARATOR .
            'oe-cqm-service' . DIRECTORY_SEPARATOR .
            'server.js';
        $client = new CqmClient(
            new System(),
            $servicePath,
            'http://localhost', // should be 127.0.0.1 loopback
            '6660' // ccda service runs on 6661
        );

        return $client;
    }
}
```

**Comment by mdsupport** [comment]
Any downside to using node server on another host on local network?

**Comment by sjpadgett** [comment]
maybe security. I've used VPN before. I prefer sockets.
