### ISSUE TITLE
Insurance Company Api bug

### ISSUE THREAD

**Issue by reymondko** [openemr/openemr#5324]
### Describe the bug

I am getting a 500 error when adding an insurance company through api. other api are working but the api/insurance_company keeps  returning 500 error

### To Reproduce

![image](https://user-images.githubusercontent.com/2532369/168205403-dc76cb02-8c8a-435f-b090-57d74a52178c.png)

### Expected behavior

returns the data and response 200

### Client configuration

- Browser: brave
- OpenEMR version: 6.1.0
- Operating system: linux

**Comment by stephenwaite** [comment]
Fixed by #5357
