### ISSUE TITLE
Add to our documentation a mapping table for USCDI elements

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5348]
It would be a really awesome feature if we had a mapping table that shows in OpenEMR where the United States Core Data for Interoperability elements against OpenEMRs implementation of CCDA,FHIR, and QRDA.

If people could see the various data elements for USCDI and what tables they correspond to in OpenEMR for the various elements, that would be very helpful to both developers and clinicians wanting to use and enter the data in the EMR.

**Comment by sjpadgett** [comment]
This was attempted in CCM as you may know. Unsure how well it works but could be a start if someone wanted to update.

![image](https://user-images.githubusercontent.com/1859985/168904875-c50c30f7-e720-4c77-89d5-40fa0bdc1b41.png)

**Comment by adunsulag** [comment]
@sjpadgett I'm thinking more in terms of just documenting the fields and data elements, rather than trying to do it in code which is a much bigger endeavor.

**Comment by sjpadgett** [comment]
Oh yeah. Probably help if I read the title more closely! lol But my brain immediately went how could we do that!
