### ISSUE TITLE
Support for Jasig CAS authentication 

### ISSUE THREAD

**Issue by jlutz42** [openemr/openemr#536]
I have a need to use this software, but I need to authenticate user from a CAS authentication server. How difficult would it be to support CAS authentication?

**Comment by bradymiller** [comment]
There was just code added to support Active Directory:
https://github.com/openemr/openemr/commit/2bd238906d9dbe6512e08e08d5f213ca065e43f3

This code nicely illustrates where code would need to be modified to support other authentication methods.

**Comment by jlutz42** [comment]
Ok I can try to take a look.

Thanks,
John
