### ISSUE TITLE
All tables with primary key and auto increment with default 0 fail on create

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5365]
### Describe the bug
Currently on MariaDB 10.4.22 on drop and create or create table(new and import backup) that has a default set to 0 on primary key, auto increment fails to be created.

I've been chasing this for months and comes down to how we use NO_AUTO_VALUE_ON_ZERO. Unsure solution except changing defaults.

@bradymiller I'm going to let you sort this if you would sir.

**Comment by mdsupport** [comment]
Sorry, this dumb guy does not understand the issue.
Would be a major issue if db generated dump and load sequence fails to restore tables.
What is specific sequence to recreate this? 
Is it specific to Maria or also happens with mysql?
