### ISSUE TITLE
Deleted codes show on patient billing report

### ISSUE THREAD

**Issue by surfacehazard** [openemr/openemr#5373]
### Describe the bug

write concise description of what the bug is.

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by stephenwaite** [comment]
here's a link to the forum thread, thanks @surfacehazard 
https://community.open-emr.org/t/deleted-codes-showing-in-patient-report-billing-information/18508
