### ISSUE TITLE
Add carecoordination search by patient creation date, provider id, billing facility id

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5386]
To facilitate both Clinical Quality Measure exporting and MIPS reporting we want to be able to be able to search on the care coordination screen by additional fields.

- The first field is the date a patient was created.  We need this so we can grab just the patients we just recently imported, or export patients that were created during a specific time frame.  
- The next is the provider id.  For MIPS reporting we often need to group patient QRDA documents (Category 1 and Category 3 aggregate counts) by the provider they are connected to if the provider has not assigned billing to another TIN.
- Finally we need the billing facility id.  Again for MIPS reporting we want to be able to group the patient QRDA documents by the billing facility in the case where providers have all assigned their medicare/medicaid billing payments to their employer, or another group with a Tax ID Number (TIN).

**Comment by sjpadgett** [comment]
Now that I'm not stressing out over CQM, I don't know what to do with myself.
I guess I could go and try to find someone to pick on!:)
