### ISSUE TITLE
LBF Diagnosis section fails

### ISSUE THREAD

**Issue by gutiersa** [openemr/openemr#5390]
### Describe the bug

If “Show services section” and “Show diagnosis section” are ticked in Layout Based Form properties, the diagnosis section does not open, if “Show services section” is unticked, but the “Show diagnosis section” is ticked, the diagnosis section does open.

### To Reproduce
Admin -> Forms -> Layouts, select desired form, then click on "Layout properties"

If both “Show services section” and “Show diagnosis section” are ticked:

![services ticked](https://user-images.githubusercontent.com/11306638/170605882-be88be9b-a2d2-4256-8b3d-32e7285aaf74.png)

If only "Show diagnosis section" is ticked:

![services unticked](https://user-images.githubusercontent.com/11306638/170605861-227340df-0048-4263-a0fd-6c8988c41d75.png)

### Expected behavior

Both services and diagnosis sections should open if desired. This is also the behavior in the openemr demo.

### Client configuration

- Browser: Both chrome and firefox
- OpenEMR version: 6.1
- Operating system: Unix based

**Comment by sjpadgett** [comment]
@gutiersa This was an easy one character fix if you just want to patch your production.
The fix is in forms/LBF/new.php. See my PR

**Comment by gutiersa** [comment]
Beautiful, you are a genius.
Ok, will do!
