### ISSUE TITLE
Need to create HTML reports for QRDA I and III

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5393]
### Describe the bug
The current XSL provided with QRDA does not style the patient data section.

The best I can tell, cypress generates reports using Ruby ERB templating.
It may be possible to port to underscore/twig or ???

I'm not sure I can do this so need help!

I do create a HTML from QRDA detail view button with this result.

![image](https://user-images.githubusercontent.com/1859985/170788722-5d68e975-d2f7-4772-8f57-69476e3ac478.png)

**Comment by adunsulag** [comment]
Is this a requirement for certification?  I didn't realize it was one.

**Comment by sjpadgett** [comment]
I noticed that the downloads for c1 includes a directory of xml and a directory of html. so, I'm guessing yes. if anything so users can look at results!

**Comment by adunsulag** [comment]
@sjpadgett That's the c1 checklist stuff.  I do think its something we should have for end users, but I don't know if we need it by Tuesday.  @stephenwaite ?

**Comment by adunsulag** [comment]
Removed the 2015 ONC as we didn't need it for certification.
