### ISSUE TITLE
CdaValidateDocuments throws fatal exception if schematron validate doesn't return anything 

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5398]
Experienced on the demo farm a fatal exception if the CdaValidateDocument->validateSchematron() returns nothing (such as when an exception is thrown).  

If there is an error we should either propogate the exception and handle it in the calling class, or have it return an empty array instead of fatally dying.

There is a separate issue of why the schematron process is not running on the demo farm which I'll investigate as well.

**Comment by adunsulag** [comment]
Here is the fatal error that is thrown:

TypeError
File:
/var/www/localhost/htdocs/openemr/src/Services/Cda/CdaValidateDocuments.php:35
Message:
array_merge(): Argument #2 must be of type array, null given
Stack trace:
#0 /var/www/localhost/htdocs/openemr/src/Services/Cda/CdaValidateDocuments.php(35): array_merge(Array, NULL)
#1 /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php(200): OpenEMR\Services\Cda\CdaValidateDocuments->validateDocument('<?xml version="...', 'qrda1')
#2 /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php(922): Carecoordination\Model\CarecoordinationTable->importCore('<?xml version="...', '65')
#3 /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php(270): Carecoordination\Model\CarecoordinationTable->import('65')
#4 /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php(135): Carecoordination\Controller\CarecoordinationController->importAction()
#5 /var/www/localhost/htdocs/openemr/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Carecoordination\Controller\CarecoordinationController->uploadAction()
#6 /var/www/localhost/htdocs/openemr/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#7 /var/www/localhost/htdocs/openemr/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#8 /var/www/localhost/htdocs/openemr/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#9 /var/www/localhost/htdocs/openemr/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#10 /var/www/localhost/htdocs/openemr/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#11 /var/www/localhost/htdocs/openemr/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#12 /var/www/localhost/htdocs/openemr/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#13 /var/www/localhost/htdocs/openemr/src/Core/ModulesApplication.php(116): Laminas\Mvc\Application->run()
#14 /var/www/localhost/htdocs/openemr/interface/modules/zend_modules/public/index.php(73): OpenEMR\Core\ModulesApplication->run()
#15 {main}

**Comment by sjpadgett** [comment]
@adunsulag Are you going to fix or me?

**Comment by adunsulag** [comment]
@sjpadgett I've already got a fix so it doesn't fail, but the core error is in the oe-schematron-service logs directory location.  Going to open another issue in that repo for the problem and I'll give more details there on what is going on.

**Comment by sjpadgett** [comment]
Probably need to change the log location or get rid of it entirely. I didn't think about write permissions in node_modules but still that log is really not that useful and may as well be removed.

**Comment by adunsulag** [comment]
Here is the open issue: https://github.com/openemr/oe-schematron-service/issues/1
If we want to get rid of the logging mechanism all together that is fine.  Or maybe have a debug flag that turns it on for when someone is running the service standalone and not inside node_modules.
