### ISSUE TITLE
Programmatically Generate Doctrine Entities

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#542]
There are two items in this ticket.

### Write a program that takes the raw schema and generates a corresponding Doctrine entity.

Write a program that takes the raw schema and generates a corresponding Doctrine entity. Some code from the current (basic) approach can be reused: https://github.com/openemr/openemr/issues/472#issuecomment-277575267

Make sure the data types are correctly mapped per http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#mapping-matrix

### Determine where the 25 tables that are not referenced in initialization script

Determine where the 25 tables that are not referenced in https://github.com/openemr/openemr/blob/master/sql/database.sql are specified. Here's some more information on this:

When once runs the following query:

```
SELECT count(*) AS total 
  FROM INFORMATION_SCHEMA.TABLES
 WHERE TABLE_SCHEMA = 'openemr';
```

The result is 219.

When one runs the following code:

```
wget https://raw.githubusercontent.com/openemr/openemr/master/sql/database.sql
```

...and `node index.js` for:

```
var FileSystem = require('fs');
var OperatingSystem = require('os');

function countTables(contents) {
  var contentsAsArray = contents.split(OperatingSystem.EOL);

  var count = 0;

  contentsAsArray.forEach(function(line) {
    if (line.indexOf('CREATE TABLE') > -1) {
      count++;
    }
  });

  return count;
}

function construct(command) {
  var result = countTables(FileSystem.readFileSync('database.sql', 'utf8'));
  console.log('There are ' + result + ' tables');
}

construct();
```

The result is 194 :/

**Comment by MatthewVita** [comment]
elwillis1@gmail.com will be working on this (can't find him on Github) :)

**Comment by MatthewVita** [comment]
Also of note: http://stackoverflow.com/a/10614792/1525534

...when we make some progress on this ticket, http://doctrine-orm.readthedocs.io/en/latest/reference/caching.html _must_ be set up. Right now, we don't care about caching because there's only a few tables that are mapped by Doctrine (isn't a performance hit in the slightest). However, 200+ tables will definitely be burdensome.

**Comment by stephenwaite** [comment]
sounds wise Matthew, i've enjoyed following your work and am willing to take a crack at bringing in the standardized_tables_track table?
`-- Table structure for table `standardized_tables_track`
--

DROP TABLE IF EXISTS `standardized_tables_track`;
CREATE TABLE `standardized_tables_track` (
  `id` int(11) NOT NULL auto_increment,
  `imported_date` datetime default NULL,
  `name` varchar(255) NOT NULL default '' COMMENT 'name of standardized tables such as RXNORM',
  `revision_version` varchar(255) NOT NULL default '' COMMENT 'revision of standardized tables that were imported',
  `revision_date` datetime default NULL COMMENT 'revision of standardized tables that were imported',
  `file_checksum` varchar(32) NOT NULL DEFAULT '',
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 ;`

**Comment by stephenwaite** [comment]
on the diff btw 219 and 194, are those the tables without primary keys?

**Comment by MatthewVita** [comment]
> sounds wise Matthew, i've enjoyed following your work and am willing to take a crack at bringing in the standardized_tables_track table

Glad you've enjoyed following along. Things have been a tad slow lately for this project though. Oops.

> i'll start a ticket if that's cool

Go for it.

> on the diff btw 219 and 194, are those the tables without primary keys?

Hmmm, don't think that's it.

**Comment by juggernautsei** [comment]
Where are we on this part of the project? I think I would like to pick this task to do. 
I have been manually creating entities but do create a program to generate the entities sounds great. However, I don't agree with one thing I read in this thread. Depending on the database to called 'openemr'. I rarely name a database openemr. I try to avoid it like the plague as a possible security precaution.   The database name would have to obtained from the installation process and not assumed. @stephenwaite

**Comment by stephenwaite** [comment]
hi @juggernautsei , looks like we're right where we left off 3 yrs ago :)

be glad to assign it to you

**Comment by juggernautsei** [comment]
Yes, but I may be 3 years wiser and a developer in the making. Can you shares with me the thinking behind the desire to create the entities programmatically? Also, would this be for the entire database?

**Comment by stephenwaite** [comment]
looks like @MatthewVita [was getting tricky with it](https://github.com/openemr/openemr/issues/472#issuecomment-277575267) :)

**Comment by zerai** [comment]
hi @juggernautsei ,
The effort for writing your custom tool is time consuming,  expansive, try to integrate the available official tool ([Doctrine Console](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/tools.html#doctrine-console)) could be a better choice. IMHO

**Comment by juggernautsei** [comment]
@zerai I agree with you. I don't see the need to generate entities before they are being used. I tried to donate the entities that I had created in another project and they were not accepted. How can this be any different? I do know that the yaml can be used to generate the entities. No need to invent something.
