### ISSUE TITLE
Direct Message Attachments - Display Validation Report 

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5435]
When we receive a direct message that contains a CCDA/CDA document we need to be able to run the Schematron Validator that @sjpadgett built to show the validation errors in the document.  This feature could be accomplished by sending users to the Carecoordination module and importing the document into the audit tables since the validation functionality is already built.

If we can embed the validation report directly into when the attachment is being viewed in the Messages screen that would be ideal.  We'll need to profile this for performance to make sure this doesn't break things down.

We also need to be able to grab a zip file received via direct and check if it is an XDM file with an embedded CCDA.  If so, we need to run the validator on the inner document and display any validation errors there as well.  We also need to check for malformed XHTML if it is an XDM document and display that as a validation error also.

**Comment by sjpadgett** [comment]
![image](https://user-images.githubusercontent.com/1859985/172720939-f0beffe9-b784-4d86-bd1d-f2e28322685c.png)

**Comment by adunsulag** [comment]
@sjpadgett Is this with the new ett validation service you are using?

**Comment by sjpadgett** [comment]
Yes but currently via UI. I'm getting ready to interface the api but I wanted to show the java project running. I have both a tomcat and a vagrant setup for grins.

I will create a new project for tomcat version that will include all the various setups that are required after the war is deployed then turn over to you for a linux test run.

**Comment by sjpadgett** [comment]
@adunsulag 
How do you want validation results returned for your purposes i.e array or formatted html etc..
Do you want to include scenarios in request to test against(I don't think we need)?
example call 
`$schema_results = $this->ettValidateCcda($document, "raw");`

also @bradymiller Are we planning the min PHP version to be 8.0.0+ for release v7.0.0?
example array:
```
Array
(
    [resultsMetaData] => Array
        (
            [ccdaDocumentType] => CCD
            [ccdaVersion] => R1.1
            [objectiveProvided] => C-CDA_IG_Plus_Vocab
            [serviceError] => 
            [serviceErrorMessage] => 
            [ccdaFileName] => ccda.xml
            [ccdaFileContents] => <?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="CDA.xsl"?>

	Title: US_Realm_Header_Template

	XML Content Truncated for brevity ...

	[resultMetaData] => Array
		(
			[0] => Array
				(
					[type] => C-CDA MDHT Conformance Error
					[count] => 3
				)

			[1] => Array
				(
					[type] => C-CDA MDHT Conformance Warning
					[count] => 0
				)

			[2] => Array
				(
					[type] => C-CDA MDHT Conformance Info
					[count] => 0
				)

			[3] => Array
				(
					[type] => ONC 2015 S&CC Vocabulary Validation Conformance Error
					[count] => 0
				)

			[4] => Array
				(
					[type] => ONC 2015 S&CC Vocabulary Validation Conformance Warning
					[count] => 0
				)

			[5] => Array
				(
					[type] => ONC 2015 S&CC Vocabulary Validation Conformance Info
					[count] => 0
				)

			[6] => Array
				(
					[type] => ONC 2015 S&CC Reference C-CDA Validation Error
					[count] => 0
				)

			[7] => Array
				(
					[type] => ONC 2015 S&CC Reference C-CDA Validation Warning
					[count] => 0
				)

			[8] => Array
				(
					[type] => ONC 2015 S&CC Reference C-CDA Validation Info
					[count] => 0
				)

		)

	[vocabularyValidationConfigurationsCount] => 120
	[vocabularyValidationConfigurationsErrorCount] => 121
	[severityLevel] => ERROR
	[totalConformanceErrorChecks] => 5527
	)

    [ccdaValidationResults] => Array
        (
            [0] => Array
                (
                    [description] => Consol Allergy Problem Act SHALL contain exactly one [1..1] code (CONF:NEW) code /@code SHALL="CONC" Concern (CodeSystem: HL7ActClass 2.16.840.1.113883.5.6) or code/@code SHALL="48765-2" Allergies, adverse reactions, alerts (CodeSystem: LOINC 2.16.840.1.113883.6.1 STATIC) (CONF:NEW)
                    [type] => C-CDA MDHT Conformance Error
                    [xPath] => /ClinicalDocument/component/structuredBody/component/section/entry[2]/act/code
                    [validatorConfiguredXpath] => 
                    [documentLineNumber] => 879
                    [actualCode] => 
                    [actualCodeSystem] => 
                    [actualCodeSystemName] => 
                    [actualDisplayName] => 
                    [dataTypeSchemaError] => 
                    [schemaError] => 
                    [igissue] => 1
                    [ds4PIssue] => 
                    [muissue] => 
                )

            [1] => Array
                (
                    [description] => Consol Allergy Problem Act SHALL contain exactly one [1..1] code (CONF:NEW) code /@code SHALL="CONC" Concern (CodeSystem: HL7ActClass 2.16.840.1.113883.5.6) or code/@code SHALL="48765-2" Allergies, adverse reactions, alerts (CodeSystem: LOINC 2.16.840.1.113883.6.1 STATIC) (CONF:NEW)
                    [type] => C-CDA MDHT Conformance Error
                    [xPath] => /ClinicalDocument/component/structuredBody/component/section/entry[3]/act/code
                    [validatorConfiguredXpath] => 
                    [documentLineNumber] => 1039
                    [actualCode] => 
                    [actualCodeSystem] => 
                    [actualCodeSystemName] => 
                    [actualDisplayName] => 
                    [dataTypeSchemaError] => 
                    [schemaError] => 
                    [igissue] => 1
                    [ds4PIssue] => 
                    [muissue] => 
                )

            [2] => Array
                (
                    [description] => Consol Allergy Problem Act SHALL contain exactly one [1..1] code (CONF:NEW) code /@code SHALL="CONC" Concern (CodeSystem: HL7ActClass 2.16.840.1.113883.5.6) or code/@code SHALL="48765-2" Allergies, adverse reactions, alerts (CodeSystem: LOINC 2.16.840.1.113883.6.1 STATIC) (CONF:NEW)
                    [type] => C-CDA MDHT Conformance Error
                    [xPath] => /ClinicalDocument/component/structuredBody/component/section/entry[4]/act/code
                    [validatorConfiguredXpath] => 
                    [documentLineNumber] => 1198
                    [actualCode] => 
                    [actualCodeSystem] => 
                    [actualCodeSystemName] => 
                    [actualDisplayName] => 
                    [dataTypeSchemaError] => 
                    [schemaError] => 
                    [igissue] => 1
                    [ds4PIssue] => 
                    [muissue] => 
                )

        )

)

```

**Comment by adunsulag** [comment]
@sjpadgett array is best for me, I'll format the html the way it needs to work.

**Comment by adunsulag** [comment]
@sjpadgett I don't understand what you mean by scenarios.  I can call and talk to you about it tomorrow.

**Comment by sjpadgett** [comment]
@adunsulag 
I wonder why we can't just use the public SITE url `http://ccda.healthit.gov/referenceccdaservice/`
It works!

**Comment by bradymiller** [comment]
hi @sjpadgett , plan minimum php version for OpenEMR 7.0.0 to be PHP 7.4 (since it will be support by PHP until 11/22).

**Comment by adunsulag** [comment]
@sjpadgett I'm fine if we use the public URL, I'm not sure why I didn't think of just doing that!  It should be a configurable global option though so if people want to use their own servers they can.  I guess one concern would be if for some reason it went down during testing.  However, I think if that were the case then the ETT tools would break as well!

**Comment by sjpadgett** [comment]
yep I'll set up a global url input that defaults to SITE ett. I'll also have my server up running on validator.myserver in case it is needed or you can use during testing.
I'm going to return the results using the same array format that the schematron is using so all our renderers don't have to adjust.

**Comment by sjpadgett** [comment]
okay here goes:

![image](https://user-images.githubusercontent.com/1859985/172912084-a0c3bfc9-b184-47a1-a8b9-83b9074dc7b4.png)

 and for request fails:

![image](https://user-images.githubusercontent.com/1859985/172912402-7d71906c-8264-49b9-b8ef-2c0b89ea5cf8.png)

and the returned array:
```
array (
  'errorCount' => 3,
  'warningCount' => 0,
  'ignoredCount' => 0,
  'errors' => 
  array (
    0 => 
    array (
      'type' => 'error',
      'test' => 'C-CDA MDHT Conformance Error',
      'description' => 'Consol Allergy Problem Act SHALL contain exactly one [1..1] code (CONF:NEW) code /@code SHALL="CONC" Concern (CodeSystem: HL7ActClass 2.16.840.1.113883.5.6) or code/@code SHALL="48765-2" Allergies, adverse reactions, alerts (CodeSystem: LOINC 2.16.840.1.113883.6.1 STATIC) (CONF:NEW)',
      'line' => '879',
      'path' => '/ClinicalDocument/component/structuredBody/component/section/entry[2]/act/code',
      'context' => '',
      'xml' => '',
    ),
    1 => 
    array (
      'type' => 'error',
      'test' => 'C-CDA MDHT Conformance Error',
      'description' => 'Consol Allergy Problem Act SHALL contain exactly one [1..1] code (CONF:NEW) code /@code SHALL="CONC" Concern (CodeSystem: HL7ActClass 2.16.840.1.113883.5.6) or code/@code SHALL="48765-2" Allergies, adverse reactions, alerts (CodeSystem: LOINC 2.16.840.1.113883.6.1 STATIC) (CONF:NEW)',
      'line' => '1039',
      'path' => '/ClinicalDocument/component/structuredBody/component/section/entry[3]/act/code',
      'context' => '',
      'xml' => '',
    ),
    2 => 
    array (
      'type' => 'error',
      'test' => 'C-CDA MDHT Conformance Error',
      'description' => 'Consol Allergy Problem Act SHALL contain exactly one [1..1] code (CONF:NEW) code /@code SHALL="CONC" Concern (CodeSystem: HL7ActClass 2.16.840.1.113883.5.6) or code/@code SHALL="48765-2" Allergies, adverse reactions, alerts (CodeSystem: LOINC 2.16.840.1.113883.6.1 STATIC) (CONF:NEW)',
      'line' => '1198',
      'path' => '/ClinicalDocument/component/structuredBody/component/section/entry[4]/act/code',
      'context' => '',
      'xml' => '',
    ),
  ),
)
```
For a schematron validation the `context` and `xml` will be populated with `test` being the actual assert test performed(ett doesn't return this info).

P.R going up in a few minutes.

**Comment by adunsulag** [comment]
Screenshots of validation in the messages.  Successful document received.
![image](https://user-images.githubusercontent.com/228117/173138069-13325099-561f-445e-a698-3f61b4c51f2d.png)

Validation spinner that validates each document in the messages asynchronously to avoid tying up the main rendering thread for the user.  Documents can't be previewed / clicked on until validation is complete.  This could eventually be hooked into if people wanted to virus scan documents, etc.
![image](https://user-images.githubusercontent.com/228117/173138311-571e996e-ab10-4c0b-a3cd-21ee6e6b6ed8.png)

Multiple documents no validation:
![image](https://user-images.githubusercontent.com/228117/173138439-0f782b1b-a32c-438d-89c1-51995e8b5f34.png)

Multiple documents with error counts displayed:
![image](https://user-images.githubusercontent.com/228117/173138558-e761c8c0-665b-4962-bc62-8eb44e48d6a7.png)
