### ISSUE TITLE
Remove ccd/ccr import tabs in Carecoordination module

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5460]
The ccda / qrda import tab handles ccd imports for both version 2.1 and 1.1 of the CCD-A specification.  CCR is no longer even used for ONC.  

From my testing the tabs don't even function properly to import so its recommended we remove them.  If someone needs that functionality they can use an older version of OpenEMR and then upgrade.

**Comment by adunsulag** [comment]
@sjpadgett Do you see any reason why we need to keep these tabs?  Its not urgent so we can remove them whenever, but it seems a good idea to do so.

**Comment by sjpadgett** [comment]
I don't see a reason to keep. I'd just disable for now though.

**Comment by bradymiller** [comment]
I'd recommend one of the following 4 options :)

option 1:
![destroy-wall](https://user-images.githubusercontent.com/278968/173168703-7d651832-0b19-41b7-8635-18a20cbc90b3.gif)

option 2:
![king-kong-vs-godzilla-smash](https://user-images.githubusercontent.com/278968/173168718-baa55565-8afd-4c99-9924-163a2e3147e8.gif)

option 3:
![dwight-schrute-the-office (1)](https://user-images.githubusercontent.com/278968/173168739-f691007d-0d30-4e4d-92a1-6d3ca5872bba.gif)

option 4:
![working-from-home-explosion](https://user-images.githubusercontent.com/278968/173168749-fe8c44be-e8da-454c-9bb4-1c6533954844.gif)
