### ISSUE TITLE
Any hook system & pluginable !!!

### ISSUE THREAD

**Issue by A1Gard** [openemr/openemr#548]
The most important necessary facilities in app system is pluginablity.
Now I have some Idea for Persian Date & calendar but I cant found any hook system for important functions for exm:

- oeFormatShortDate
- oeFormatTime
- DateFormatRead
- DateToYYYYMMDD
- and etc.

Because we want openemr work with all supported language together perfect concurrent ! right?

I worked with wordpress, IpBoard , or other systems and write plugin for them some years ago since now. 

Question: What is the openemr  approach about pluginable system and hook for some functions??

Sorry , my poor English . 

Thanks : )

**Comment by A1Gard** [comment]
@bradymiller  I'm waiting for your answer!

**Comment by bradymiller** [comment]
@A1Gard ,
Regarding hooks for above functions, can you provide a quick example, so we're on the same page :)
Is the Zend module loader an example of this (in OpenEMR, go to Modules), which also has several hooks throughout the codebase?
thanks, -brady

**Comment by robertdown** [comment]
My suggestion for hooks (Have been thinking/researching for a while now) is to use Symfony's `EventDispatcher` to handle all hooks.

There is definitely no reason to create a hook system from the ground up, these systems already exist, just a matter of implementing one. It's on my list (After the install redo)
