### ISSUE TITLE
CCDA - Change hardcoded granular race code into a selection in the demographics gui

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5483]
I have to be able to visually show the granular race codes for the ONC scenarios.  Right now we hard code the granular race codes for CCDA based upon the topmost race level in the ccda service which I won't be able to visually show.  

We need to be able to either choose multiple race codes (IE White & European, and treat the White / African as top most codes with the others being more granular), or we need to have another dropdown selector in the demographics for granular race code.

I'm open to other suggestions as well.

The hard coded line is here:
https://github.com/openemr/openemr/blob/00e8aac93640c4957a64f90f9667f20591e72ea4/ccdaservice/serveccda.js#L133

**Comment by bradymiller** [comment]
Pretty sure this from a time in distant past where the ethnicity and race were combined in one layout entry.  Looks like in 3.2 to 4.0 upgrade is where it was then separated into 2 separate layout entries (and database fields).

**Comment by sjpadgett** [comment]
Since this passes conformance for our test scenario's, I'd leave it be.

**Comment by stephenwaite** [comment]
wouldn't they all have to be presented to the user?

**Comment by sjpadgett** [comment]
the granular race code is sub category of race code so two codes are involved. I've narrowed them down so thanks

**Comment by stephenwaite** [comment]
ok nice

**Comment by stephenwaite** [comment]
where's our label for `select2 wizardry needed`?
