### ISSUE TITLE
Show LOINC codes on vitals form for vital observations

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5484]
For ONC requirements we need to visually display the LOINC codes for the vitals data we are entering in on the vitals form panel.  This is helpful both for people wanting to work with vitals data on the APIs as well as documenting the coded entries of the vitals we are entering in.

**Comment by adunsulag** [comment]
Here is a screenshot of what I'm proposing: 
![image](https://user-images.githubusercontent.com/228117/173454710-9aa7f503-6853-4cee-8ce3-56deb06a6eed.png)

**Comment by bradymiller** [comment]
![2DV](https://user-images.githubusercontent.com/278968/173545804-347b9063-5a19-4f00-b7f3-f276a7c572b9.gif)
