### ISSUE TITLE
b1 ccd/referral form generated with carecoordination missing CareTeam information

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5486]
In the ccd/referral form generated via carecoordination for our ONC scenario 3 we are not getting care team information. It shows up as a warning but we will fail the xml visual inspection without the populated care team information.

![image](https://user-images.githubusercontent.com/228117/173489406-2e54290a-6ab0-4601-8889-04b331293517.png)

This is the populated care team for that sample patient  **Happy Kid**
![image](https://user-images.githubusercontent.com/228117/173489548-62b7aba2-5e5c-439f-ad74-29ac8a3baf7a.png)

This is the information that is supposed to be populated for the scenario:
![image](https://user-images.githubusercontent.com/228117/173489595-5b1a766b-4759-45bf-8c13-7570cbc754b2.png)

I need to dive deeper into the xml and see what's going on.  I suspect that perhaps the warning is being triggered due to us not populating the Primary Care Physician Date for the careteam.  Currently we use the creation date for that and it looks like that needs to be configurable at least to pass the visual inspection.

**Comment by sjpadgett** [comment]
don't understand. careteam works
```
<documentationOf typeCode="DOC">
    <serviceEvent classCode="PCPR">
      <effectiveTime>
        <low value="20220614"/>
        <high value="20220614"/>
      </effectiveTime>
      <performer typeCode="PRF">
        <functionCode code="PP" displayName="Primary Performer" codeSystem="2.16.840.1.113883.12.443" codeSystemName="Provider Role">
          <originalText>Primary Care Provider</originalText>
        </functionCode>
        <assignedEntity>
          <id root="2.16.840.1.113883.4.6" extension="123456789"/>
          <code code="207Q00000X" displayName="Family Medicine" codeSystem="2.16.840.1.113883.6.101" codeSystemName="NUCC Health Care Provider Taxonomy">
            <originalText>Care Team Member</originalText>
          </code>
          <addr>
            <country>USA</country>
            <state>OR</state>
            <city>Beaverton</city>
            <postalCode>97006</postalCode>
            <streetAddressLine>2472 Rocky Place</streetAddressLine>
          </addr>
          <telecom use="WP" value="555-555-1002"/>
          <assignedPerson>
            <name>
              <given>Albert</given>
              <family>Davis</family>
            </name>
          </assignedPerson>
        </assignedEntity>
      </performer>
    </serviceEvent>
  </documentationOf>
```

**Comment by sjpadgett** [comment]
I see, I think you need to add the care team facility in Choices!

**Comment by sjpadgett** [comment]
This passes and meets spec and is not visually inspected. About the only thing we might do is add a nullFlavor to time component. Again, this is a warning and not an error.
```
<time>
    <low nullFlavor="UNK"/>
</time>
```

If you really want to be 100% on this Stephen then maybe add a new layout item for Demographic->Choices->Provider named Since Date with date field.
