### ISSUE TITLE
Possibility of creating duplicate SSN

### ISSUE THREAD

**Issue by priya-anand** [openemr/openemr#549]
When I create a new patient info, for example - Steve Tapper with SSN 123456789, and then create another patient info with same SSN (123456789), pop-up window shows no previous record of the same SSN existing in the database, On clicking confirm button, a new patient with same SSN is accepted. 

When searching for patient information using SSN as search term, both the patient information is displayed.

**Comment by sharonco-matrix** [comment]
You can use the PatientValidation Zend module to prevent that with any rules that you want

**Comment by bradymiller** [comment]
@priya-anand 
The PatientValidation Zend is a cool option.

Also should be able to get this working in the base form by placing D in Administration->Layouts->Demographics->S.S. Label row->Options column

D is duplication checking

**Comment by priya-anand** [comment]
@bradymiller , @sharonco-matrix 

Thanks for the reply, and yes, it works.
- Priya
