### ISSUE TITLE
several vital form bugs

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#5496]
hi @adunsulag , was testing this and noted several bugs

1. After adding vitals with all entries filled out, the encounter screen does not show it with following php error in log:
```
PHP Fatal error:  Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /var/www/localhost/htdocs/openemr/interface/forms/vitals/report.php:106\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/interface/forms/vitals/report.php(106): round()\n#1 /var/www/localhost/htdocs/openemr/interface/patient_file/encounter/forms.php(987): vitals_report()\n#2 {main}\n  thrown in /var/www/localhost/htdocs/openemr/interface/forms/vitals/report.php on line 106, referer: http://localhost:8300/interface/patient_file/encounter/forms.php
```

2. And then if try to edit that form, it breaks here (pasted log under the screenshot):
![image](https://user-images.githubusercontent.com/278968/174024056-9d274862-8212-4cee-9e4c-9f04170c483f.png)
```
[Thu Jun 16 08:08:37.969430 2022] [php:error] [pid 1057] [client 172.27.0.1:39880] PHP Fatal error:  Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /var/www/localhost/htdocs/openemr/src/Common/Utils/MeasurementUtils.php:32\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/src/Common/Utils/MeasurementUtils.php(32): round()\n#1 /var/www/localhost/htdocs/openemr/src/Common/Forms/FormVitals.php(250): OpenEMR\\Common\\Utils\\MeasurementUtils::inchesToCm()\n#2 /var/www/localhost/htdocs/openemr/sites/default/documents/smarty/main/%%F0^F06^F068F682%%vitals_textbox_conversion.tpl.php(116): OpenEMR\\Common\\Forms\\FormVitals->get_height_metric()\n#3 /var/www/localhost/htdocs/openemr/vendor/smarty/smarty/libs/Smarty.class.php(1875): include('...')\n#4 /var/www/localhost/htdocs/openemr/sites/default/documents/smarty/main/%%E5^E50^E50519AD%%general_new.html.php(113): Smarty->_smarty_include()\n#5 /var/www/localhost/htdocs/openemr/vendor/smarty/smarty/libs/Smarty.class.php(1269): include('...')\n#6 /var/www/localhost/htdocs/openemr/interface/forms/vitals/C_FormVitals.class.php(128): Smarty->fetch()\n#7 /var/www/localhost/htdocs/openemr/interface/forms/vitals/view.php(19): C_FormVitals->default_action()\n#8 /var/www/localhost/htdocs/openemr/interface/patient_file/encounter/view_form.php(26): include_once('...')\n#9 {main}\n  thrown in /var/www/localhost/htdocs/openemr/src/Common/Utils/MeasurementUtils.php on line 32, referer: http://localhost:8300/interface/patient_file/encounter/encounter_top.php
```

3. Looks like vitals are being saved in metric form rather than imperial form:
![image](https://user-images.githubusercontent.com/278968/174024472-65b51e34-6f27-4235-ad33-a957038cb222.png)
![image](https://user-images.githubusercontent.com/278968/174024524-4fb1211d-8a9c-4369-b9dc-e73b9de5ea53.png)
![image](https://user-images.githubusercontent.com/278968/174024725-8cf1266f-4fb0-44d5-a4d9-89e1e526dd80.png)
(above form save is the last row of the screenshot)

4. javascript error when type in weight in lb (and the kg is not populated):
![image](https://user-images.githubusercontent.com/278968/174022823-ef9ae5fd-7cfd-42e1-b155-26990c997652.png)

**Comment by adunsulag** [comment]
@bradymiller I was able to reproduce the javascript error and the metric saving problems (if you have us inputs first it was saving data as metric).  But I can't seem to reproduce the fatal display error.  What version of PHP are you on?  Also what is your global vitals save locale set to (Show both metric and US, main unit is US)?

**Comment by stephenwaite** [comment]
I wasn't able to reproduce fatal error either.

**Comment by bradymiller** [comment]
the fatal display error went away with your new PR (also started up a new easy dev docker environment with some new random patients, so perhaps was related to an issue on the random patients in my prior testing)

**Comment by bradymiller** [comment]
also, for the above testing was using (Show both metric and US, main unit is US) setting.
