### ISSUE TITLE
Implement Span Entire Row edit option in layouts

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5503]
### Describe the problem
Awhile back I added this option but never followed through.
There are cases in layouts when a title is not wanted and the entire rendered row(or what is left over in column count) needs to be consumed by the data.
### Describe the solution you'd like
Option will ignore the title column count and expand the data column to fill out the row.
Add a Prepend Row or Jump to new Row option to fill entire row.

![image](https://user-images.githubusercontent.com/1859985/174448975-9adfc27c-c57f-4043-9b4a-61aa44ed0635.png)

**Comment by adunsulag** [comment]
@sjpadgett This will be nice for the patient additional addresses field!

**Comment by sjpadgett** [comment]
@adunsulag Once you merge your PR I'll add this to mine and merge.
