### ISSUE TITLE
Additional Addresses shows on all patients

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5510]
### Describe the bug
Adding an additional address to any patient will show on all patients. The same for delete.
Unclear if a pid issue.

![image](https://user-images.githubusercontent.com/1859985/174492465-69e7ed34-6920-4d85-8ef4-41076238ab76.png)

![image](https://user-images.githubusercontent.com/1859985/174492500-8b0f89e4-36b4-4858-a787-aebcbb6d501e.png)

![image](https://user-images.githubusercontent.com/1859985/174492530-c3d91bfb-84b8-4b5f-ac43-9e98a60be708.png)

**Comment by stephenwaite** [comment]
![Screenshot from 2022-06-19 13-19-26](https://user-images.githubusercontent.com/5618372/174492883-13c1df30-6be5-4a7c-bc30-50c90a54cabb.png)

**Comment by adunsulag** [comment]
Well that was embarrassing!   Sorry about that, good catch @sjpadgett and thanks @stephenwaite for the fix!

**Comment by stephenwaite** [comment]
I just happened to have a trivial fix for a PR about to be pushed and added the global while Jerry had the actual fix and deserves the credit :)
