### ISSUE TITLE
form_id not always getting populated

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#5514]
noted on several forms (such as SOAP, Review of Systems; guessing all the forms using the ODDataObject stuff) that the form_id are not getting populated (set as NULL). Check out the rows near the bottom in following screenshot:
![image](https://user-images.githubusercontent.com/278968/174520353-924d3c19-a5e2-4d71-9a34-4aa4b5e1d9b9.png)

**Comment by bradymiller** [comment]
this appears to be a critical bug (having no form_id appears to breaks lots of stuff), so prioritizing to `priority:Blocking`

**Comment by stephenwaite** [comment]
nice find, it looks like the constructor isn't called when saving a soap form so $_isObjectModified doesn't get set to true by default.

**Comment by adunsulag** [comment]
@bradymiller oh... I didn't realize that the other classes don't call the constructor... typically that's a big no-no when inheriting from classes.  We could fix this by default setting the $_isObjectModified to true in the object property instead of in the constructor.  I'll do a PR for it.
