### ISSUE TITLE
ESign data integrity failing for tables that have new columns

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5531]
### Describe the bug
when upgrading a site that was esigning it became obvious that something was amiss
![Screenshot from 2022-06-22 14-26-35](https://user-images.githubusercontent.com/5618372/175110068-bb444e68-1764-408b-935f-fe3348ef95f7.png)

### To Reproduce
for the above example, `form_encounter`, since new fields have been added now the prior hash can't equal the new hash [since we're grabbing all fields to make a hash comparison](https://github.com/openemr/openemr/blob/master/library/ESign/Form/Signable.php#L130-L137)

**Comment by sjpadgett** [comment]
hmm, I didn't think of that. We prob need to add a version check and calculate hash based on version!

**Comment by bradymiller** [comment]
To deal with this in the future (won't fix prior versions but will fix from now to future), could consider:
1. when save the hash, also save the list of columns that is used to calculate the hash
2. then when verify the hash, use the list of columns in step 1 to calculate the hash
