### ISSUE TITLE
Active Directory integration documentation

### ISSUE THREAD

**Issue by ryannix123** [openemr/openemr#554]
Hello,

I'm having difficulty finding how to make OpenEMR authenticate against LDAP or Active Directory. Could someone please point me in the right direction?

Thanks,

Ryan

**Comment by ryannix123** [comment]
Nevermind, I think I found it, however when I go to "Setting of global clinic settings can be done at Administration->Globals (these settings are all described below)." The page displays the following in OpenEMR 5.0

ERROR: query failed: SELECT * FROM lang_definitions JOIN lang_constants ON lang_definitions.cons_id = lang_constants.cons_id WHERE lang_id=? AND constant_name = ? LIMIT 1

Error: Illegal mix of collations (latin1_bin,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='


/home/emr/public_html/library/translation.inc.php at 36:sqlStatementNoLog
/home/emr/public_html/library/globals.inc.php at 2732:xl(Māori)
/home/emr/public_html/interface/super/edit_globals.php at 32:require_once(/home/emr/public_html/library/globals.inc.php)

**Comment by bradymiller** [comment]
The quick bug fix for this is here:
https://github.com/openemr/openemr/commit/05e95677dcf92454e2ee9a0019104e53b1c13785
(plan to bring this into the next 5.0.0 patch)

Note this likely means you have some issues with your database encoding, though. See here for more details:
https://community.open-emr.org/t/regarding-error-on-the-settings-page/8198/5

**Comment by ryannix123** [comment]
Thanks, Brady. The new globals file didn't fix it, however, I simply dumped the database then recreated it using character-set-server=utf and collation-server=utf8_general_ci. Problem solved.
