### ISSUE TITLE
Demographics Display Readability

### ISSUE THREAD

**Issue by psoas** [openemr/openemr#5548]
No offense to anyone:
The demographics display looks like crap & has readability issues.

One simple fix makes a significant improvement to both readability & appearance:
Make the labels align right.

BEFORE:
<img width="739" alt="Screenshot - Demographics -  Who - Display - Align Left 2022-06-25" src="https://user-images.githubusercontent.com/121007/175793257-ce74849f-33a0-44c9-ba13-c6a86f7b2496.png">

<img width="739" alt="Screenshot - Demographics -  Contact - Display - Align Left 2022-06-25" src="https://user-images.githubusercontent.com/121007/175793263-c63d2fc0-ee0b-477e-9be7-f522a8fb1ca6.png">

AFTER:
<img width="739" alt="Screenshot - Demographics -  Who - Display - Align Right 2022-06-25" src="https://user-images.githubusercontent.com/121007/175793267-99859b3b-2bf9-4c1f-a743-fefe5add7429.png">

<img width="741" alt="Screenshot - Demographics -  Contact - Display - Align Right 2022-06-25" src="https://user-images.githubusercontent.com/121007/175793270-9d38963c-f0a6-4d36-b613-f8915a604608.png">

I know there is resistance to change, 
but can I please please please contribute this change to the code.

By the way:
If you look closely at my screenshots you will see that:
I fixed the issue of the labels not being displayed using the rules defined in CSS.
All that I had to do was add ID="DEM" to the body tag in demographics.php.

**Comment by mdsupport** [comment]
Layouts mix model/data and html/view in a way that makes it hard to have modern and consistent user interface.

We did provide an option in #4905. Obviously that did not go anywhere.

**Comment by psoas** [comment]
@mdsupport
My proposal is a lot simpler and I feel it makes the current display a little more readable.

However, I do really like the function you proposed adding in #4905 and I feel that the pull request should be approved.  

It looks like Jerry was planning to refactor and incorporate the pull request but did not have time to work on it, perhaps he got overloaded with MU-3.

Additionally, I would like for you to do another pull request with the custom demographic display that you created with that function.  There can be an option created to display demographics in different ways.

I would vote for re-opening  your pull request!

**Comment by sjpadgett** [comment]
I reopened @mdsupport PR

**Comment by stephenwaite** [comment]
looks good @psoas, where's the associated pull request with your changes?
