### ISSUE TITLE
Bug in Display of "Previous Names" and "Additional Addresses"

### ISSUE THREAD

**Issue by psoas** [openemr/openemr#5558]
When you are in a window where a patient is associated with the window,
i.e. a patient name is in the upper left of the window,
AND you select from the menu Patient -> New/Search:

All of the input fields SHOULD BE EMPTY.

However, if the selected patient has "Previous Names" and "Additional Addresses",
the input fields shown after selecting Patient -> New/Search will show the "Previous Names" and "Additional Addresses" for the patient associated with the window.

**Comment by sjpadgett** [comment]
@psoas I fixed save and the service for this a couple weeks ago. Unsure if it address this issue but looks doubtful. Have you pulled master lately?
