### ISSUE TITLE
Medical Problems status column needs to show as Completed instead of Inactive

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5569]
Just noticed that our medical problems column needs to have a status value of 'Completed' instead of 'Inactive' for the visual inspection for ONC b1 certification. 
![image](https://user-images.githubusercontent.com/228117/176050055-6ebe40ad-7fb9-49d7-9b31-2954194e83bc.png)

**Comment by stephenwaite** [comment]
nice catch!
