### ISSUE TITLE
adding amendment from dashboard bug

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5581]
### Describe the bug

https://community.open-emr.org/t/adding-amendment-no-longer-works-in-v6-1/18701/2

### To Reproduce

1. Open a chart
2. Click on Amendments from Dashboard
![Screenshot from 2022-07-13 11-16-51](https://user-images.githubusercontent.com/5618372/178769566-76e41fd9-3a14-4929-8139-96ae7123bc3b.png)
3. Click add amendment
![Screenshot from 2022-07-13 11-15-59](https://user-images.githubusercontent.com/5618372/178769705-a24b0a37-afbe-4386-8656-5c3255da2196.png)

5. See error

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by stephenwaite** [comment]
hey @sjpadgett can you take a look at this error please? I can't figure out why dlgopen isn't setting the iframe window name, big surprise :)

**Comment by sjpadgett** [comment]
Didn't get a chance today. Will look at in a.m. Looks like dialog isn't being called from demographics rx_modal class href

**Comment by sjpadgett** [comment]
This was broken in one of our patches
