### ISSUE TITLE
Portal encounter form audit chart form locks up page

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5582]
### Describe the bug
save.php?mode=update&id=4:21 Uncaught TypeError: parent.closeTab is not a function
    at save.php?mode=update&id=4:21:8
(anonymous) @ save.php?mode=update&id=4:21

Not only page but entire session. Windows FF and Chrome and can not recover.

**Comment by sjpadgett** [comment]
@bradymiller Looks like when you chart save encounter form it treats the save as if a save from core and not dashboard for portal.
So form close tries to close the tab. Looks like flag for isDashboard is not set or passed.

**Comment by bradymiller** [comment]
@sjpadgett , not freezing on my testing, but definitely seeing the javascript error. Working on a fix now.
