### ISSUE TITLE
Fatal Error: Argument 1 passed to getPatientFullNameAsString

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#5597]
### Describe the bug

 I was looking through my error log and noticed this fatal error in the system. 

      [Tue Jul 12 09:01:29.303679 2022] [php7:error] [pid 14487] [client 17.1.2.18:55055] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to getPatientFullNameAsString() must be of the type int, null given, called in /var/www/html/hb600/src/OeUI/OemrUI.php on line 76 and defined in /var/www/html/hb600/library/patient.inc:785\nStack trace:\n#0 /var/www/html/hb600/src/OeUI/OemrUI.php(76): getPatientFullNameAsString()\n#1 /var/www/html/hb600/interface/patient_file/transaction/add_transaction.php(466): OpenEMR\\OeUI\\OemrUI->__construct()\n#2 {main}\n  thrown in /var/www/html/hb600/library/patient.inc on line 785, referer: https://e.healthbrigade.org/interface/main/messages/messages.php?showall=no&sortby=pnotes.date&sortorder=desc&begin=0&task=edit&noteid=124740&form_active=1

### To Reproduce
don't know how to reproduce the error

1. Add a '....'

### Client configuration

- Browser: Firefox
- OpenEMR version: 6.1.1
- Operating system: ubuntu 20.04LTS

**Comment by sjpadgett** [comment]
@juggernautsei Trying to cast null will results in null. Real issue is for some reason patient.inc getPatientFullNameAsString(int $pid) function is requiring an integer! Why?

Remove the int

**Comment by stephenwaite** [comment]
int casting null results in 0 but like your fix better :)

**Comment by sjpadgett** [comment]
nope if that were the case then wouldn't get the error by deductive reasoning! though could be PHP version dependent.
Note from error:
Uncaught TypeError: Argument 1 passed to getPatientFullNameAsString() must be of the type int, null given

**Comment by sjpadgett** [comment]
This is actually interesting! What version PHP Sherwin?

**Comment by juggernautsei** [comment]
PHP Version 7.4.28. I am slowly migrating/merging code into a heavily modified instance which started out life as 6.0.0. I am merging in 6.1.0 code section by section. 
Do you think I need to update my php version at this point?

**Comment by bradymiller** [comment]
would changing the typing to `?int` work?

**Comment by bradymiller** [comment]
and then to be safe at top of that function would put block
```
if (empty($pid)) {
    return "";
}
```

**Comment by juggernautsei** [comment]
> @juggernautsei Trying to cast null will results in null. Real issue is for some reason patient.inc getPatientFullNameAsString(int $pid) function is requiring an integer! Why?
> 
> Remove the int

I had thought about removing the int but I don't know why it was placed there to begin with. I will upgrade to PHP 8.1 on a test site to see what happens. This will be fun.

**Comment by bradymiller** [comment]
If $_SESSION['pid'] is not set, then would expect this to error out on all php versions.

The typing to int meant the function assumed it would always get a actual value. But appears there is a use case where it does not. So would expand the typing to `?int` (this allows int and null) and then add the block of code at the top of the function to properly deal with an empty $pid.
