### ISSUE TITLE
Layout editor and render engine rework.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5614]
### Describe the problem
Since the first introduction of our beloved layout based forms there have been many changes and new concepts introduced to openemr.
The capability of LBF has expanded greatly to the point that management is becoming difficult. 
Thus IMO it's time to start a refactor project to break down the current source having separation of concerns forefront. We need to streamline and make it less difficult for current and future developers to improve and/or add new functionality to the feature.

Generally speaking this means creating new classes and separating the building from the rendering and consolidating where possible. My first thought is to start with breaking out our data types and treating them as templates/plug-ins.

I'm sure many will have an opinion concerning this where I'm all ears and look forward to any discussion.

**Comment by tsimonq2** [comment]
I would be interested in helping with this if a clear path forward could be decided. I agree though, it does need some love.
