### ISSUE TITLE
Patient Finder Appearance

### ISSUE THREAD

**Issue by psoas** [openemr/openemr#5616]
I am working on improving the appearance of the patient finder.

Attached is a screenshot of what I have done thus far.  I would like to get people's thoughts and feedback.  I feel that it is an improvement but other people may not.  

If there is a change that people don't like, I might be able to make it an "option" so both can be done.

Changes completed:
--Changed color to match color of demographic tab. 
--Decreased the height of each row so that more patients can fit on one screen.
--Got rid of the heading at the top the says "Patient Finder".  I felt that this was redundant because the name Patient Finder is in the tab.  Also, the heading used up real estate that could show more useful information, i.e. more patient names.  I brought up this issue at weekly meeting, relating to many pages.
--Minor adjustments to padding and input box sizes.

Changes planned:
--In Patient Lists where you list the columns displayed, also specify column width, so that different columns will have different widths.  For example, colunn for DOB does not need to be as wide as Full Name.
--More custom column labels/content.  Full name is custom (it puts two fields together).  I would like to add more custom items.  Such as full addresses, city/state, etc.  Since patient lists does not support dropdown menus, I'm not sure how people would be aware of the custom items without looking at the code.  Any suggestions?

Please give me more suggestions/changes to improve patient finder appearance/function.

<img width="883" alt="Screenshot 2022-07-19 Patient Finder Improvement" src="https://user-images.githubusercontent.com/121007/179846647-293f3009-8773-4ff8-b78a-8407dca1be92.png">

**Comment by bradymiller** [comment]
@psoas , looks great. another very nice improvement would be the searching mechanism itself (especially from the search in the top frame that is a text box for all searches). For example, on search, things like 'fname lname' or 'lname, fname', or 'name dob' and consider tooltip for possible formats)
