### ISSUE TITLE
Facing issue with docker installation

### ISSUE THREAD

**Issue by AkshayraviC09YC47** [openemr/openemr#5620]
Hello maintainer, im unable to run openemr via docker this is the errors:

<img width="1165" alt="Screenshot 2022-07-20 at 4 53 40 PM" src="https://user-images.githubusercontent.com/58636452/179970823-52818c81-f4f0-4446-976c-d8729dc11235.png">

# Steps i have done
1. Cloned the repo and in the folder **/openemr/docker/production** executed the command **docker-compose up**, **How to solve this issue?**

**Comment by bradymiller** [comment]
@AkshayraviC09YC47 , Looks like you already have a openemr database installed (and getting error since trying to install again over a database that already exists). Would ensure no shared volumes from prior install exist prior to the docker-compose up command.
