### ISSUE TITLE
Show dosage information for a medication

### ISSUE THREAD

**Issue by tsimonq2** [openemr/openemr#5621]
### Describe the problem

*(As a quick note to start, this work is being driven by my employer, [Altispeed Technologies](https://altispeed.com/). I'm actively working on this issue. Any screenshots shown are using test data, and are not associated with any real patient.)*

Currently you can add dosage information to a medication, but that doesn't show up anywhere in reports or in patient summaries. Here's two examples of this:

![image](https://user-images.githubusercontent.com/3689821/180123526-f18d5886-315b-4cac-a347-1b2cee7cb4c8.png) ![image](https://user-images.githubusercontent.com/3689821/180123556-cc3eff59-59c3-4d6e-b137-82d517ba6dc9.png)

### Describe the solution you'd like

That dosage information should translate over. Here are some prototype screenshots of those same outputs:
![image](https://user-images.githubusercontent.com/3689821/180123758-982bc547-874b-4959-9419-0a449c984869.png) ![image](https://user-images.githubusercontent.com/3689821/180123775-2d5f3907-ee91-457a-accb-bab818f8a5a3.png)

A user alerted me that this information should also transfer when adding a prescription to the med list, as that's their primary workflow. That's my last step here.

**Comment by mainethor** [comment]
I feel like there should be another two fields in the Medication Entry window, one for the dosage number (e.g. 25) and one as a dropdown for the units (mg, mcg, ml, etc.) which can then be shown in other places. This helps prevent med errors especially when the order is for 25 mg tablets, but the total dose is 100 mg, the total dose can be entered in the dosage information, while leaving the free-text field for "take 4 tab 25 mg BID" Ideally the total dosage should always be checked when administering medications, but both the total dosage and the instructions should come up while administering the medications or printing a medication list. 

Thanks for all you do!

**Comment by tsimonq2** [comment]
> I feel like there should be another two fields in the Medication Entry window, one for the dosage number (e.g. 25) and one as a dropdown for the units (mg, mcg, ml, etc.) which can then be shown in other places. This helps prevent med errors especially when the order is for 25 mg tablets, but the total dose is 100 mg, the total dose can be entered in the dosage information, while leaving the free-text field for "take 4 tab 25 mg BID" Ideally the total dosage should always be checked when administering medications, but both the total dosage and the instructions should come up while administering the medications or printing a medication list.
> 
> Thanks for all you do!

Hi! Thank you for your consideration on this issue.

I agree with your initial line of thought, that it could be confusing when the information transfers over. However, take a look at the Prescription view here (*please remember my initial disclaimer where I state this is test data*):

![image](https://user-images.githubusercontent.com/3689821/180903774-a659dde5-5897-4817-94b4-4e8a263c8b06.png)

If the dosage *and* the unit is transferred over from prescriptions and seeds an empty dosage box with that information, I don't understand the concern about dosage showing confusing amounts. Assuming that, for sake of example (I hold zero medical credentials), someone is prescribed 100 mg of Aspirin. It would say "take 4 25 mg tablets orally" (translated into the format used in the screenshot).

I will also pass this along to the user I have been interacting with to get her thoughts. Thank you!
