### ISSUE TITLE
Improve user experience of the  "Maximum Failed Login Attempts (0 for no maximum)." setting

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#5627]
Considering expanding upon the maximum failed login attempts to also offer an option where it automatically resets (ie. will work again automatically rather than require manual intervention by admin) after a certain time. Thus if for example, there a 3 failed requests and it shuts down account, it won't be shut out indefinitely if the user sets this new setting to a time interval (ie. after that time interval, the user can then login).

**Comment by sunsetsystems** [comment]
Sounds like an improvement. Don't want to invite DOS attacks against the legitimate user.

**Comment by sjpadgett** [comment]
Exactly, however on my clinic website(wordpress) I track the offending
source ip through a hook in wordpress, deny and allow a day allowing return
access after three denial. I then start a DOS attack back to source ip!:)
You'd be amazed at how quiet my server has become from these attacks.
Mostly any longer I don't see DOS as much but seek access to scripts
which I also track.
