### ISSUE TITLE
EASIPRO missing in portal menu

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5631]
### Describe the bug
I have no clue as I don't know how to enter credentials or at least don't know if a credential issue. What is username and password i.e 
My sandbox:
```
Registration Information
RegistrationOID	F645206F-35FE-40E1-B698-C2A436F52705
Email	sjpadgett@gmail.com
Token	DCF0D53F-5835-4151-88E1-F1C01791C44E
JWT	eydSZWdpc3RyYXRpb25PSUQnOidmNjQ1MjA2Zi0zNWZlLTQwZTEtYjY5OC1jMmE0MzZmNTI3MDUnLCdUb2tlbic6J2RjZjBkNTNmLTU4MzUtNDE1MS04OGUxLWYxYzAxNzkxYzQ0ZSd9
--------------------------------------------------------
```
Same error when trying to list forms via online tool.
@bradymiller or anyone can you give a try. Use my sandbox

![image](https://user-images.githubusercontent.com/1859985/180827301-721f33ad-1c57-4f73-ac19-7065f4417dbf.png)

### Client configuration

- Browser:
- OpenEMR version: v7-dev
- Operating system: windows 11 xampp

**Comment by stephenwaite** [comment]
hey Jerry, I found this @ https://www.assessmentcenter.net/ac_api
> Note that sandbox tokens will deactivate 6 months after registration. For extension past 6 months, please email api@assessmentcenter.net with a reason for your continued use and requested extension period.

**Comment by sjpadgett** [comment]
I reregistered and listed is new. Maybe you could register and give a try. https://www.assessmentcenter.net/ac_api
I hope project is not dead!!!

**Comment by stephenwaite** [comment]
page loaded for me with
```
server = https://www.assessmentcenter.net/ac_api
username = RegistrationOID
password = Token

**Comment by sjpadgett** [comment]
Thanks a lot Stephen, That worked however, IRT just sent me a new set of credentials. HoHummmm:)
So I kicked the dog, blamed my neighbor and convinced myself, it's not my fault!:)

**Comment by sjpadgett** [comment]
Closing as working with correct credentials. thanks @stephenwaite

**Comment by sjpadgett** [comment]
Portal is missing menu item for rendering form.

**Comment by sjpadgett** [comment]
Found some escaping issues but still can't get questions to render!

![image](https://user-images.githubusercontent.com/1859985/180894295-e3b970f7-122d-4efb-91aa-484dded61bd8.png)

**Comment by sjpadgett** [comment]
Okay so I've been able to fix and also restyle the feature. I wasn't planning on spending so much time adding to feature but, couldn't help myself.

![image](https://user-images.githubusercontent.com/1859985/180923276-cc0a89d2-5104-45fa-bd4c-fb1975a628ec.png)
Will collapse table view and show just form

![image](https://user-images.githubusercontent.com/1859985/180923434-28a61ab0-a22f-404d-aab3-71d94545a826.png)

Or toggle table
![image](https://user-images.githubusercontent.com/1859985/180923602-e5e6ecca-21ae-41d8-95a7-f9d161c463e5.png)
And finish
![image](https://user-images.githubusercontent.com/1859985/180923802-8e8c6cbc-0f9c-411a-b787-3ce4a68a6469.png)

Responsive
![image](https://user-images.githubusercontent.com/1859985/180925133-3f70d58a-2984-49a7-bb4e-da3741af983d.png)
![image](https://user-images.githubusercontent.com/1859985/180925330-9414f686-7c4c-4175-a60a-2011a6ab7f43.png)
