### ISSUE TITLE
Real time Flow board 

### ISSUE THREAD

**Issue by usama-kabel** [openemr/openemr#5639]
### Describe the problem

when we have a large number of  appointments on the flow board, it is making a high load on the server to make the flow board show as a real-time mode

### Describe the solution you'd like

Is it possible to use Socket.io to help the flow board to act as a real-time and make the the server working smooth without acting in heavey load access?

**Comment by sjpadgett** [comment]
@usama-kabel There would be several ways to tune flow board. I'd recommend profiling to get a definitive idea of slow downs then if you're a developer we'd be more than happy to look over a PR if you were so incline to develop a solution.

**Comment by usama-kabel** [comment]
Need to apply some new technology to get only the updated data instead of
send Ajax evey x of second
