### ISSUE TITLE
Implement Questionnaire results management.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5661]
### Describe the problem
This is the second phase of the FHIR Questionnaire and assessments feature. Need to add the resulting answers resource save and retrieve generic across all possible use cases i.e. from API Questionnaire/QuestionnaireResponse, SMART or other rendered forms.

I'm going to do this part at the same time I'm developing an encounter form implementation of questionnaires retrieved through API lookup by LOINC codes or description or from inputted FHIR server URL.

I think this will be a very nice feature. I also wonder if there is a clinical need to render questionnaires from demographic? Perhaps integrate with the Easipro workflow in demographics to allow doing questionnaires from there.

I'm taking suggestions for some default questionnaires/assessments to offer as core items in OpenEMR too.

Wish me luck!:)

**Comment by sjpadgett** [comment]
example encounter form(what I have so far) from a gad search and getting the GAD-7. This is an auto scoring form.

![image](https://user-images.githubusercontent.com/1859985/182683560-4129d89a-2b2e-4eb5-9e2d-dda849c6dbb1.png)

**Comment by adunsulag** [comment]
Hooray @sjpadgett.  That was a LOT of work.  Thank you and it looks amazing!
