### ISSUE TITLE
record patient nationality

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5666]
### Describe the problem

no defined field in `patient_data` as discussed https://community.open-emr.org/t/recording-patient-nationality/18752/6

### Describe the solution you'd like

add a text field for now and down the road can link to a dataset per uscdi

**Comment by ruthkonyn** [comment]
the following sql statement adds 'nationality' into a patient's demographics - i'm not sure how to add this as a PR

it does need a table 'nationalities' to be set up as well

INSERT INTO `layout_options` (`form_id`, `field_id`, `group_id`, `title`, `seq`, `data_type`, `uor`, `fld_length`, `max_length`, `list_id`, `titlecols`, `datacols`, `default_value`, `edit_options`, `description`, `fld_rows`, `list_backup_id`, `source`, `conditions`, `validation`, `codes`) VALUES ('DEM', 'nationality', '1', 'Nationality', '250', '1', '1', '15', '30', 'Nationalities', '1', '3', '', '', NULL, '0', '', 'F', NULL, NULL, '');
