### ISSUE TITLE
Rework prescriptions

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5678]
### Describe the bug
Prescriptions can be confusing even for experienced users. The problem is the action buttons are disjointed meaning, save action is not grouped with the other actions requiring hunting.

Some solutions are to have all action buttons in the same place. Either in the iframe or the dialog footer.

Also I'm going back and forth on removing dialog and rendering in a tab. My thoughts are that dialogs can be a nuisance on small devices and we should remove from openemr when it makes sense in workflow. This may be a good example of such a use case.

Other Admins input is needed here because I'm leaning towards using new tab and removing dialog making for a major change IMO.

![image](https://user-images.githubusercontent.com/1859985/184004073-2c7ff4e8-391f-4cf1-97fa-9485b895fbce.png)

**Comment by sjpadgett** [comment]
I can't decide if using a tab is better than a dialog:
![image](https://user-images.githubusercontent.com/1859985/184198125-dd338426-0ba9-4917-882d-af6e5f933769.png)

![image](https://user-images.githubusercontent.com/1859985/184198433-943ec397-2b2c-4890-a3a5-45b036a59fd6.png)

@stephenwaite @bradymiller @robertdown @adunsulag 
Any opinion please! Or I could regroup actions in dialog.

**Comment by robertdown** [comment]
I think removing dialogs entirely is a path we shouldn't go down. The majority of the EMR use-case is _not_ on a mobile device and that is a drastic change to accommodate just mobile uses.

I think there are two things to consider. First, is the content of the dialog directly related to the current tab? Second, once the user hits that Save button, what happens next? If the answer is "The tab automatically closes and returns back to the previous tab" then we should definitely be using a dialog.

An alternative path would be redesigning the actual form. I know we follow a couple of built-in bootstrap patterns for our forms, but we really should be evaluating the design on a form-by-form basis (setting aside any dynamically-built form, those are an entirely different conversation). For instance, Does the starting date field need to be full width? No. Nor does several of the fields. In fact, quantity and med units should probably be on the same line.

I've been eyes-deep in infrastructure work for the last several weeks and haven't been working on actual codebase. But, I see the light at the end of the tunnel on my infrastructure stuff and when I can get back to the codebase I would like to refactor some of the styling - we, by inheriting a lot of Bootstrap's design, are very padding-friendly throughout the UI and I think we would reduce down the padding a lot. I'm thinking a solution similar to Gmail or Microsoft Office products that allow something like "Normal" "Tight" and "Dense" as options for each user.

**Comment by sjpadgett** [comment]
> nuisance on small devices and we should remove from openemr when it makes sense in workflow.



> I think removing dialogs entirely is a path we shouldn't go down

There are forms that are more likely to be used on small devices than others. Prescriptions is one and calendar another IMO.
Also prescription is a very busy form and dialogs should be reserved for the quicker actions and not actions that could be left and then came back to by the user. e.g start a script go make a note then come back etc.
Still I agree, openemr is primarily a desktop app however appears more and more user are using tablets.

We have a condensed theme version but I agree with the padding and having three options would be great and would solve many "how used" dilemmas for responsiveness.

I do look forward to seeing your work with theming and render styling.

**Comment by tywrenn** [comment]
Just throwing some things here like I know nothing...prescriptions seem like something that needs to be importable from a database very easily or have options to integrate with third-party platforms that provide lists of prescriptions.

**Comment by robertdown** [comment]
> Just throwing some things here like I know nothing...prescriptions seem like something that needs to be importable from a database very easily or have options to integrate with third-party platforms that provide lists of prescriptions.

We handle that via the Medication List, not Prescriptions.

A medication list is any/all a patient has taken or currently takes. A prescription is the order from the provider to administer a specific medication.

A provider writes a prescription leading to a new entry in the Medication List.

We should definitely be taking to Rx clearinghouses for interoperability's sake. Meds on the Med List can be self-reported by the patient or brought in via an API (which should then be verified by clinical staff at the next encounter)

**Comment by CENSONtechnology** [comment]
> We should definitely be taking to Rx clearinghouses for interoperability's sake. Meds on the Med List can be self-reported by the patient or brought in via an API (which should then be verified by clinical staff at the next encounter)

We have been trying to bring in medications via API, but it appears to be restricted to medication name, and begin/end date.  Am I missing something, or is that really the extent of the capability.  Like [tywrenn](https://github.com/tywrenn) we have a need to bring medication (and/or prescription details) from third part apps.

**Comment by CloCkWeRX** [comment]
For prescribing, there's both the usabilty aspects [make it easy for me to prescribe] and the patient safety concerns, some of which are regulated [make it easy for me not to make mistakes that result in harm].

For australian prescribing systems, there is a very detailed set of guidance available, covering prescribing/ePrescribing use cases:
https://developer.digitalhealth.gov.au/specifications/ehealth-foundations/ep-3733-2022/dh-3734-2022

From your screenshots vs that conformance profile; I would suggest things like:

* Capture when you are prescribing unusual doses or for unusual uses [particularly for controlled substances]
* Capturing clinical indications as to why you are prescribing (beyond just 'notes'); possibly as coded values, at least as free text
* Consider an area for warnings or interactions display; if you do not have one already. A number of datasets; such as https://www.mims.com.au/ provide decision support and warnings. Alternatively, at the very least showing any alerts/allegies/etc.

**Comment by sjpadgett** [comment]
I wish I knew a percentage of users using this as opposed to other forms of prescribing. Regulations are making it difficult for use of printed scripts.

**Comment by CloCkWeRX** [comment]
Sorry, what? If regulations - aimed at clinical safety - are presenting an obstacle that is difficult to overcome, that seems concerning.
Reason for prescribe, alerts for interactions, or flagging "yes, I know this is unusual" are not particularly an imposition, because the prescriber no doubt has a lot of that in mind when prescribing.
It can't be that hard to provide optional inputs and partial automation for users doing this kind of thing

**Comment by sjpadgett** [comment]
@CloCkWeRX 
Thanks for taking the time to comment here! I agree It shouldn't be too difficult to add the additional functionality to prescriptions. Maybe you're up to taking this on as a contribution to the community.

**Comment by sjpadgett** [comment]
close as @adunsulag has pretty much finished this up.
