### ISSUE TITLE
Provide event hooks to add javascript or styles to anywhere the Header class is used

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5681]
Instead of adding event hooks for specific pages across OpenEMR to inject javascript or stylesheets in from a module we should add event listeners to the main Header class that can add additional Javascript / Stylesheet assets as part of our header asset bundling process.  The event hooks should pass in the name of the currently executing script so that module writers can add / inject assets conditionally based upon the page they are on or inject them on every single page where the Header class is utilized.

**Comment by juggernautsei** [comment]
how is the header event going to handle when a script needs to be at the bottom of a page? Because sometimes a script needs to run after the page loads.

**Comment by adunsulag** [comment]
@juggernautsei This doesn't handle that use case.  We currently only have the Header class at the top of the majority of OpenEMR pages.  If we had a Footer class I would have added those events as well.  So while this doesn't cover everything, it increases the number of places people can inject scripts into OpenEMR dramatically.  A workaround would be to listen to the header event and then generate an script element with the javascript src or raw JS that you need to execute and insert it into the DOM at the end of the body tag.

The only other solution would be to go and add some kind of footer class to every page where the Header class is.

**Comment by adunsulag** [comment]
Another suggestion would be to follow the pattern of adding an event listener on window for DOMContentLoaded and that will make sure your script runs at the end.  

I know the technique used to be to append a lot of scripts at the end of the body to prevent page/download blocking but with modern browsers having async scripts, defer, and HTTP/2 with pipelining I'm not sure that matters too much anymore.
