### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ugintl** [openemr/openemr#5696]
I just saw the demo. Very good work. I am logged in as admin. I can see clinics and patients, but where is doctors' list? Would not it be better and more cleaner if there is a doctors page just like clinics and patients? Thank you

Is the version 7_0_0_1 stable?

**Comment by adunsulag** [comment]
The doctor's list is in the Admin -> Users screen.  Can you use 7.0.0.1 in production? Yes. Are there some outstanding bugs? Yes.

**Comment by ugintl** [comment]
Is there any specific reason to do that? Having doctors under users screen. I think it would be better to have a separate page just like patients or clinics.

Are there mobile apps for openemr?
