### ISSUE TITLE
Change OAuth2 approval settings to Auto Approve patient standalone apps

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5705]
I discovered that ONC does NOT allow any vetting of a patient's chosen 3rd party app as long as the app is restricted to soley being a patient standalone app and meets the security requirements of all OpenEMR patient standalone apps.  As an admin has to pretty much auto-approve these applications we should simplify the administrative burden on OpenEMR administrators and change our Oauth2 3rd party app approval process to be auto approved for patient standalone apps.

Currently a public app is auto-approved in OpenEMR, whereas all confidential apps are required to be manually approved.  We should change up the logic so that if a confidential app requests ONLY patient/* scopes and not user/* or system/* scopes the app is auto approved.  

We should also add a global setting if a user wishes to change the logic to require manual approval of all apps.  Note that if a user goes this route and they must comply with US healthcare laws then they MUST approve the app within 48 hours according to a lecture I attended from the SMART on FHIR group.  I'm still trying to track down the specific requirement as it looks like it might be a MIPS thing but I'm still waiting on details for that.

As part of this change we should allow public apps to have the offline_access scope if it is a Patient Standalone scope.  A public app must have a way of securely storing the refresh token in their application in a secure enclave if the public app is a native mobile application.  Patients will be notified that the app is requesting offline access and should be careful in granting this permission.

I will be posting a preliminary PR but I'd love any feedback from the community on any security issues they see with this approach.

**Comment by sjpadgett** [comment]
If memory serves me I believe the patient access (production of records) with in 48 hours come from HIPAA and is not new.
Before API and portals the patient would make a request and practice would print the requested records thus the time period.

IMO as long as the practice can meet this requirement in one form or another i.e. API, portal or print then the EMR is covered.

Still, I don't have a problem with auto auth but would limit scopes to patient/read.

I'm also still a little concerned with how I implemented trusted user and at the time thought it deserved a revisit in the future.

**Comment by sjpadgett** [comment]
To be clear, I'm happy we are doing the things to ease patient access and I'm not trying to squeak around the issue!

**Comment by adunsulag** [comment]
We need to look at making sure that PKCE is handled with swagger.

**Comment by sjpadgett** [comment]
Gee thanks!

**Comment by sjpadgett** [comment]
I gotta say @adunsulag, you did a great job with swagger and client admin in Administration. First time I've try to use either so while old news, I just wanted to say thanks!

**Comment by adunsulag** [comment]
@sjpadgett I was being cheeky two days ago and should have mentioned that.  Didn't intend to have you go and have to implement the swagger thing.

**Comment by adunsulag** [comment]
@sjpadgett It looks like there is an outstanding bug in Swagger that turning on PKCE will break confidential apps as it removes the client_secret parameter https://github.com/swagger-api/swagger-ui/issues/7913 .  Not sure how to handle this as we are going to force public apps to use PKCE which means public apps will no longer be able to use swagger unless we turn on PKCE.  However, if we turn it on, then confidential apps will break as swagger removes the secret field.

I think until swagger fixes the issue we should leave PKCE off in swagger and people will just have to use confidential apps for any testing.  Or we could get into swagger's code and develop a PR but I'm not really interested in doing that right now.

**Comment by bradymiller** [comment]
I wonder if there is a swagger-ui version sweet spot where pkce works prior to that bad commit that hides the secret field. Gonna look into this. May get lucky.

**Comment by bradymiller** [comment]
Actually, I think we can just modify the swagger-ui code directly since the code is in the openemr codebase. Gonna see if can figure that out.

**Comment by bradymiller** [comment]
here's pr that will get swagger to work with PKCE for both public and private apps:
https://github.com/openemr/openemr/pull/5713
