### ISSUE TITLE
Standard Api Scope Handling for patient portal breaks on list endpoints.

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5707]
If you add a portal list api without the accompanying single get api, the scopes are not handled properly due to how we handle scope resolution in our capability statement.

For example a rest api endpoint of **/portal/patient/appointment** will fail if you do not have a **/portal/patient/appointment/:uuid** endpoint as well.  That is because our capability statement completely ignores the list endpoint.  The broken logic is in RestControllerHelper in the following lines:
```php
} else {
                // API routes do not always have the resource at $items[2]
                if (count($items) < 5) {
                    $resource = $items[2];
                } elseif (count($items) < 7) {
                    $resource = $items[4];
                    if (substr($resource, 0, 1) === ':') {
                        // special behavior needed for the API portal route
                        $resource = $items[3];
                    }
                } else { // count($items) < 9
                    $resource = $items[6];
                }
            }
```
This works for a standard api endpoints, but breaks with the /portal/ prefix.

**Comment by sjpadgett** [comment]
I think we ought to take that portal developer out behind the woodshed!

**Comment by adunsulag** [comment]
@sjpadgett Pretty sure I was the one that wrote the Capability logic above haha, so I'm going to be avoiding any areas that involve woodsheds for the near future.
