### ISSUE TITLE
Consolidate writable directories to one directory

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#572]
Currently we require several folders be writable:

* openemr/sites/default/documents
* openemr/sites/default/edi
* openemr/sites/default/era
* openemr/sites/default/letter_templates
* openemr/gacl/admin/templates_c
* openemr/interface/main/calendar/modules/PostCalendar/pntemplates/compiled
* openemr/interface/main/calendar/modules/PostCalendar/pntemplates/cache

Would like to consolidate this to just `sites/*/documents`

**Comment by sunsetsystems** [comment]
Perhaps better to make the location configurable per site? Leaving the option of putting it outside the web directory or on a different volume.

**Comment by bradymiller** [comment]
I think consolidation would be a first good step(which would be a good project for a new developer on the project). Then the second step would be making it configurable.

**Comment by bradymiller** [comment]
Another thing to add to this project is also migrating things that are created by OpenEMR when needed, for example, the sites/*/procedure_results directory when using hl7 labs module. There are big benefits to placing these things within the documents directory, most importantly security since we recommend to secure that directory with apache. So, this project could be considered to have 3 distinct steps:
1. Migrate the stuff @robertdown discussed above
2. Seek out and migrate the "hidden" items (such as procedure_results directory)
3. Make the actual location of the site directory to be configurable

This would be a good project(especially for newer developers to learn the structure of OpenEMR) if there are any interested developers.

**Comment by MatthewVita** [comment]
Kind of related: `openemr/sites/default/documents` is the only one of these directories that can be dealt with via CouchDB, right?

**Comment by bradymiller** [comment]
CouchDB only deals with patient documents.
Note that there are also features in the codebase that open up a new directory in openemr/sites/documents and write to it (for example, logs, templates etc.); these are the ones that behave nicely. There are also some features that do not behave nicely that open a new directory in openemr/sites , for example the hl7 lab import stuff; the reason these do not behave nicely is they won't be secured by apache and don't automatically get incorporated into folks backup/restore/upgrade schemes.

**Comment by MatthewVita** [comment]
Right but isn't `openemr/sites/default/documents` exclusive to patient documents?

**Comment by MatthewVita** [comment]
Dumb question: there is no 100% centralized CouchDB-for-everything solution out there at the moment, right?

**Comment by MatthewVita** [comment]
(note, I'm asking these questions because of https://github.com/openemr/openemr/issues/606#issuecomment-294343921)

...I wonder if `rsync` would be a good solution for this kind of stuff...

**Comment by bradymiller** [comment]
No, other features also use and leverage openemr/sites/default/documents/ directory (since it will be secured by apache, writable, and then get incorporated into folks backup/restor/upgrade schemes).

Correct, couchdb only does the patient documents.

rsync for backup?

**Comment by bradymiller** [comment]
I'm not to knowledgable at the aws stuff, but if could get everything into the sites/*/ directories (for example, the smarty cache and and letter templates), then should be able to do the elastic beanstalk thing with the sites directory on storage (s3 etc.).

**Comment by bradymiller** [comment]
@sjpadgett brought in a nice strategy for bringing directories into documents:
 https://github.com/openemr/openemr/blob/master/interface/globals.php#L194-L205

I'm thinking about using this same strategy to migrate all the above writable directories to documents. Then would only need to deal with permissions for documents directory on the install. thoughts?

**Comment by MatthewVita** [comment]
BTW, my team is set on Amazon EFS for this.

**Comment by MatthewVita** [comment]
Didn't mean to hijack the thread too much here lol

**Comment by bradymiller** [comment]
Working on this issue here:
https://github.com/openemr/openemr/pull/673

**Comment by bradymiller** [comment]
completed:
https://github.com/openemr/openemr/commit/5b051518518a5818d3d92d49316aa181f49d6457
