### ISSUE TITLE
str_starts_with() use of function that require php 8

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#5728]
While figuring out how to get smarty to work, I noted this issue in the Controller class where the php function str_starts_with() is being used in what appears to be at a very critical part of the code:
https://github.com/openemr/openemr/blob/master/library/classes/Controller.class.php#L52

This function (https://www.php.net/manual/en/function.str-starts-with.php) is only in php8 and above, so in theory, this should break horribly on anybody using 7.4, although I haven't confirmed this.

the str_starts_with() function is being called in 5 places in the codebase

**Comment by bradymiller** [comment]
str_contains() also is being used in 8 places which also need php8

**Comment by bradymiller** [comment]
str_ends_with() is being used in 2 places in the codebase which also needs php8

**Comment by bradymiller** [comment]
btw, here's an article on those 3 new functions:
https://www.amitmerchant.com/new-string-functions-php8/

**Comment by tywrenn** [comment]
If you are trying to make a compatibility layer for php 7 to exist, a function like this would detect if the user is running php 8 or higher:
`if (version_compare(PHP_VERSION, '8.0.0') >= 0) {  }`

PHP 7 is expected to not exist around 2024 so we will have to remove code like this around that time.

**Comment by tywrenn** [comment]
Here's where the offending code lives:

str_contains()
- src/Rx/RxList.php - lines 150, 157, 165
- src/PatientPortal/Chat/ChatController.php - lines 85, 90
- library/options.inc.php - lines 3893
- interface/super/edit_layout.php - lines 895
- interface/modules/zend_modules/public/index.php - lines 51

str_ends_with()
- src/Services/Cda/CdaValidateDocuments.php - line 37
- src/Common/Http/HttpRestRequest.php - lines 544

str_starts_with()
- interface/orders/receive_hl7_results.inc.php - lines 1602, 1726
- interface/patient_file/summary/demographics_save.php - lines 65
- library/classes/Controller.class.php - lines 52
- src/Services/Qdm/Services/ImmunizationAdministeredService.php - lines 63

**Comment by bradymiller** [comment]
agreed.
don't even need to modify master since 7.4 eol is this 11/2022 (was planning to drop 7.4 support from master in near future).
for next patch though for 7.0.0 (rel-700 branch), we should incorporate the fixes via your suggested if statement

**Comment by stephenwaite** [comment]
![southpark_cheering](https://user-images.githubusercontent.com/5618372/190401485-36e087f5-2050-4937-8892-de367274a86e.gif)
