### ISSUE TITLE
Improved Install Screen

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#573]
Already working on this but wanted to put it online so people are aware. Restyling the installation guide. Screenshots attached.
![screen shot 2017-03-18 at 16 34 48](https://cloud.githubusercontent.com/assets/1381170/24075806/ded52ca0-0bf8-11e7-9d8a-9c56dd645791.png)
![screen shot 2017-03-18 at 16 34 59](https://cloud.githubusercontent.com/assets/1381170/24075807/ded74c60-0bf8-11e7-9701-9076fb693379.png)

**Comment by MatthewVita** [comment]
Looks awesome!

**Comment by georgetye** [comment]
Wow, this looks awesome! Great job Robert.

**Comment by bradymiller** [comment]
Completed by zbig recently, so closing this issue.
