### ISSUE TITLE
Current FHIR R4 classes missing properties and methods

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#5737]
### Describe the bug
Current build was Generated on FHIR v4.0.0 schema.
Current released spec is FHIR v4.3.0 however v4.0.1 is the last version we can build until the builder project is updated to reflect newer schema changes.
For current and near term development we need min FHIR v4.0.1.
I've also noted there are several undefined namespaces and class paths in several places on existing code. Unclear how these would present but need to resolve them while I'm in this code.

Plan:
- Build library for FHIR v4.0.1 using the Oct 2019 schema.
- Remove FHIR directory tree.
- Replace with new v4.0.1 using the same OpenEMR\FHIR namespace
- Refactor all FHIR services and REST Controllers for class path changes.
- Optimize

@bradymiller Once I get the PR up maybe you can help me test. Mainly for PHP 8+ warnings which for some reason I miss many on my Windows PHP compile.

Because we've recently introduced PKCE @adunsulag will need to rerun all the inferno tests anyway.

Besides a change in project size (40mb vs 14mb v4.0.0) and new properties/getters, class paths have also changed with new backbone and data requirement element paths. the domain class was moved under FHIRResource path.

**Comment by bradymiller** [comment]
![2DV](https://user-images.githubusercontent.com/278968/189541916-79736f8b-22a0-43a9-9daf-42204e3fea20.gif)
