### ISSUE TITLE
String-based route types do not save

### ISSUE THREAD

**Issue by tsimonq2** [openemr/openemr#5743]
### Describe the bug

*(As a quick note to start, this work is being driven by my employer, [Altispeed Technologies](https://altispeed.com/). I'm actively working on this issue. Any screenshots shown use test data, and are not associated with any real patient.)*

When setting any of the following options to an existing prescription, they do not save:
 - Intradermal
 - Other/Miscellaneous
 - Transdermal
 - Intramuscular
 - Inhale
 - By Mouth

### Client configuration

- **Browser**: Firefox Nightly
- **OpenEMR version:** 7.0.0.1, tip of master
- **Operating system:** Ubuntu 22.04 LTS, Kinetic (development release)

**Comment by tywrenn** [comment]
Seems like someone didn't build out the SQL function for that. Should be pretty easy to fix.

**Comment by stephenwaite** [comment]
also the setter in prescription class only looks for numeric values

**Comment by tsimonq2** [comment]
On it. Thanks!

**Comment by tsimonq2** [comment]
While those two items needed to be addressed, something is doing data validation in the user interface causing the string values to be set to null in the database. I'll be spending my work day today trying to find this, but if anyone knows where the function exists off the top of their head, please let me know.

**Comment by tsimonq2** [comment]
@stephenwaite I'll be happy to submit a WIP PR if you'd like to take a look, but after removing the `is_numeric()` check in addition to updating the type of the `route` column in `prescriptions` to `varchar(25)`, it is still not working as intended. There isn't any additional function validating that it's a string, correct? e.g. around `504 in `interface/eRxStore.php`, the type of `$routeOptionId` is an integer. This makes me think I'm missing something else.

Let me know your thoughts. I appreciate your time.

**Comment by tsimonq2** [comment]
(Oh, before I forget, I can set e.g. `other` as a type in the relevant `prescriptions` entry from the database CLI, but the UI doesn't display the correct value. Setting it to a string-based ID causes `route` to become `NULL`. Interesting behavior, I'm more asking if you know where that code may live.)

**Comment by sjpadgett** [comment]
@tsimonq2 @stephenwaite 
In 7.0.0 to 7.0.1 upgrade sql this is wrong
```

#IfNotRow2D list_options list_id drug_route option_id bymouth
INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `notes`, `codes`) VALUES ('drug_route', 'bymouth', 'By Mouth', 1, 0, 'PO', 'NCI-CONCEPT-ID:C38288');
#EndIf

```

id 'bymouth' needs to be numeric i.e 25

**Comment by tsimonq2** [comment]
@sjpadgett If I may ask, how does that explain the other values which are strings instead of integers? I originally did add that as an integer in my PR but was recommended to use a string

**Comment by stephenwaite** [comment]
> id 'bymouth' needs to be numeric i.e 25

https://github.com/openemr/openemr/pull/5715#discussion_r960066528

**Comment by stephenwaite** [comment]
@tsimonq2 was able to test saving non-numeric entries for route after I changed the field to be `varchar` and removed `is_numeric()`

**Comment by tsimonq2** [comment]
@stephenwaite @sjpadgett No worries, I finally have some working code on my end. PR incoming :)

**Comment by tsimonq2** [comment]
@bradymiller @sjpadgett @stephenwaite I feel like I'm being pulled in two different directions, so I'm going to hold off for comment from Brady, if possible, before continuing on the PR.

It seems like this bug was first introduced in commit 81d00d00b96e00146a0ddbb40ad85fd308ea38d8, so I would be pretty surprised if we need to suddenly revert all of them back to integer values.

I'm not particular on the route we go, I just need a consistent answer on what to do.

**Comment by sjpadgett** [comment]
See my solution in PR
