### ISSUE TITLE
Many empty checkboxes in reports make things cluttered

### ISSUE THREAD

**Issue by tsimonq2** [openemr/openemr#5744]
### Describe the problem

*(As a quick note to start, this work is being driven by my employer, [Altispeed Technologies](https://altispeed.com/). I'm actively working on this issue. Any screenshots shown use test data, and are not associated with any real patient.)*

When printing a report, this leaves much to be desired:

![image](https://user-images.githubusercontent.com/3689821/189740929-6bf93c21-635a-42f2-bc88-637aafbab5a0.png)

### Describe the solution you'd like

This looks much cleaner:

![image](https://user-images.githubusercontent.com/3689821/189741032-469ee975-a135-4d4f-8ea7-65202be13ae0.png)

The only question I have is, should this be toggleable, or should all forms now look like the latter? That slightly changes my approach.

Thanks.

**Comment by tywrenn** [comment]
I'd probably make it togglable -- not sure if people prefer the other option or not -- @sjpadgett ?

**Comment by sjpadgett** [comment]
> I'd probably make it togglable

I don't think it is necessary in a report.
Many of our encounter reports will only show answered values and I believe LBF does the same except here.

**Comment by sjpadgett** [comment]
@sunsetsystems Will this effect you?

**Comment by mdsupport** [comment]
@tsimonq2, If you have time consider this type of reporting
![image](https://user-images.githubusercontent.com/399047/190832112-4575ee63-24a3-48f5-b939-d22f9d51efc5.png)

**Comment by tsimonq2** [comment]
@mdsupport Apologies for the belated response on this - I wouldn't see an issue with this, given that a) you can turn the option off and b) the only thing it does in particular is it hides the non-checked box. Let me know if you have issues with this once merged and I'll be happy to assist where I can.
