### ISSUE TITLE
innodb error on upgrade of openemr v5.0.1 to v7.0.0

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5752]
### Describe the bug
running the upgrade script in the easy dev docker on an older version results in

```
Row size too large (> 8126). Changing some columns to TEXT or BLOB may help. In current row format, BLOB prefix of 0 bytes is stored inline.
```
this is on the old `form_eye_mag` that was converted to other tables and then dropped in the `5_0_1-to-5_0_2_upgrade.sql`

### Expected behavior
`mariadb` should be able to handle the upgrade with some other settings passed in at initialization

### old mariadb configuration in `docker-compose.yml`
```
mysql:
    restart: always
    image: mariadb:10.6
    command: ['mysqld','--character-set-server=utf8mb4','--ssl-ca=/etc/ssl/ca.pem','--ssl_cert=/etc/ssl/server-cert.pem','--ssl_key=/etc/ssl/server-key.pem']
    ports:
    - 8320:3306
    volumes:
    - ../library/sql-ssl-certs-keys/easy/ca.pem:/etc/ssl/ca.pem:ro
    - ../library/sql-ssl-certs-keys/easy/server-cert.pem:/etc/ssl/server-cert.pem:ro
    - ../library/sql-ssl-certs-keys/easy/server-key.pem:/etc/ssl/server-key.pem:ro
    - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

**Comment by bradymiller** [comment]
Is this related to this mariadb bug:
https://community.open-emr.org/t/error-installing-version-5-0-2/12806
