### ISSUE TITLE
Absolute path to documents stored in database, rather than a path relative to the site root

### ISSUE THREAD

**Issue by tsimonq2** [openemr/openemr#5758]
*(As a quick note to start, this work is being driven by my employer, [Altispeed Technologies](https://altispeed.com/). I'm actively working on this issue. Any screenshots shown use test data, and are not associated with any real patient.)*

I was writing a script to verify that all documents present in the database are also present on the filesystem. When we migrated to using a Git-based workflow, we re-deployed it from `/var/www/openemr` to `/var/www/emr.DOMAIN.TLD`, a use case I would not consider to be rare.

However, querying the `url` column from the `documents` table, I'm finding an entry like such: `file:///var/www/openemr/sites/default/documents/12/MY_ID_HERE`. Ideally, this would be shortened to `file:///OE_SITE_WEBROOT/sites/default/documents/12/MY_ID_HERE` or similar.

I'd like to remove the hackiness from my script while benefitting upstream. I also know that the multi-site module may need to be taken into consideration, and since we don't have such a setup, advice would be appreciated. 

Here's part of my script: `SELECT REGEXP_REPLACE(url, '(.+)/sites/default/documents', '/sites/default/documents') AS url FROM documents WHERE deleted = 0` - is there a global variable or database value I could use to substitute `default`?

Thanks.

**Comment by sjpadgett** [comment]
$_SESSION['site_id'] will always have the current site.

To verify you could do something such as
file_exists($GLOBALS['OE_SITES_BASE'] . '/' . $_SESSION['site_id'])

**Comment by tsimonq2** [comment]
What would be the implications of an upstream database modification to make these paths consistent?

**Comment by stephenwaite** [comment]
from what I remember the logic is built in to find the document so that it's irrelevant what's stored in that field in the table

https://github.com/openemr/openemr/blob/master/library/classes/Document.class.php#L622

**Comment by tywrenn** [comment]
This actually is an enhancement that is well needed -- the documents folder could move to different locations on a file system like a separate drive or different folder location. The only way to fix all documents after changing the folder is to do an SQL change that only an experienced developer could do.

Another idea I just thought of -- what if we created something in the EMR config where you can change the folder location independently of everything else?

**Comment by bradymiller** [comment]
That absolute path that is stored in the database is basically mostly ignored. OpenEMR (check out @stephenwaite link above to code) basically just uses the stuff on the right side of the path to find where the file is located.

**Comment by tywrenn** [comment]
If it's ignored then why does it exist 😂 makes me confused.

**Comment by bradymiller** [comment]
Historically the full path was used. But this was a bug since it broke when migrating to another server (ie. with a absolute path change of openemr). So to fix the bug, basically just used the right side of the path and a added sql column to store the path_depth to know how deep the dir structure is of the document. And I guess we figured might as well leave the whole path there just to confuse folks way into the future :)

**Comment by sjpadgett** [comment]
I think Simon @tsimonq2 is looking into this
