### ISSUE TITLE
Considering visibility of middle name and suffix in the UI

### ISSUE THREAD

**Issue by tsimonq2** [openemr/openemr#5767]
### Describe the problem

*(As a quick note to start, this work is being driven by my employer, [Altispeed Technologies](https://altispeed.com/). I'm actively working on this issue. Any screenshots shown use test data, and are not associated with any real patient.)*

Currently, in patient reports (at minimum), the middle name and suffix for a user is not displayed. This would personally affect me if my healthcare provider used OpenEMR, since my full name is T. Simon Quigley II (thus my username). I would want the full name at least somewhere on the report for reference, especially for billing.

Can we figure out where exactly middle names and suffixes are left out? In what cases would it be useful to include a full name in an obvious manner?

I'll get some tenative code for patient reports, seeking feedback on the rest of EMR.

**Comment by stephenwaite** [comment]
It's included in the `Name:` area of the report when the demographics checkbox is checked:

![Screenshot from 2022-09-20 13-28-18](https://user-images.githubusercontent.com/5618372/191324991-6ebfb9d9-5569-45a1-8d08-e4adba57a0d1.png)
