### ISSUE TITLE
Patient Self-Registration on Patient Portal Broken in Current and Prior Versions 

### ISSUE THREAD

**Issue by tywrenn** [openemr/openemr#5768]
### Describe the bug

It's sad that I keep running into issues into the EMR on version 7.0.0. I just came across a bug on the patient portal where if a patient self-registers, the page 500 errors with the following error in console:
`PHP Fatal error:  Uncaught Error: Class "SystemLogger" not found in /var/www/localhost/htdocs/openemr/portal/account/register.php:20\nStack trace:\n#0 {main}\n  thrown in /var/www/localhost/htdocs/openemr/portal/account/register.php on line 20`

Unless we have a different way that we log this, the best way to deal with this is probably to use syslog() to log it as debugging info. @sjpadgett any ideas?

### Client configuration

- Browser: Google Chrome 105.0.5195.127 x64
- OpenEMR version: 7.0.0 running in Docker
- Operating system: Windows 11 x64, running Amazon Linux 2 t2 Docker Server

**Comment by bradymiller** [comment]
Does this address your issue:
https://community.open-emr.org/t/portal-register-php-showing-error-500/17964

**Comment by bradymiller** [comment]
(btw, guessing that addresses issue since no error and no need to use the SystemLogger call; making this not break should be a quick fix and guessing just need a use statement in that script so the class exists)

**Comment by tywrenn** [comment]
Requiring captcha can be a slippery slope when it comes to people just testing it out. Probably would just make it an option to have it rather than a requirement.

**Comment by tywrenn** [comment]
If it's required, it should be required to set the key and secret upon turning on the feature in the config rather than digging and realizing you had to set the values to begin with.

**Comment by tywrenn** [comment]
It also should disable itself in prior versions if the fields aren't filled in.
