### ISSUE TITLE
Unable to see insurance card image from dashboard with upgrade to 7.0.0

### ISSUE THREAD

**Issue by gutiersa** [openemr/openemr#5802]
### Describe the bug
Unable to see insurance card image from dashboard with upgrade to 7.0.0. I can see patient image, but not insurance card image.

### Expected behavior
Ability to see insurance image from the patient dashboard

### Client configuration

- Browser: Firefox and chrome
- OpenEMR version: 7.0.0
- Operating system: Windows client, UNIX server

**Comment by sjpadgett** [comment]
Sorry @stephenwaite Didn't realize you had assigned this as I had already fixed. See PR

**Comment by stephenwaite** [comment]
no prob @sjpadgett , you beat me to it, nice fix

**Comment by gutiersa** [comment]
Thanks

**Comment by sjpadgett** [comment]
@gutiersa While I fixed id not rendering I also added instead of only one id in the past to allow up to three id's. I think 3 is reasonable enough.
