### ISSUE TITLE
isInitiallyCollapsed() user settings on the dashboard aren't working

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5804]
### Describe the bug

write concise description of what the bug is.
when loading the dashboard it should remember which widgets are collapsed or not

### To Reproduce
collapse a widget or expand if default is closed and then refresh the dashboard or choose another person with finder

### Expected behavior
should remember the user's preference

### Client configuration

n/a

**Comment by sjpadgett** [comment]
Demographic JS function that appears to catch click events of card titles
L-760 async function updateUserVisibilitySetting(e)

I'd bet we are missing some from query selector cardTitleButtonClickListener() to set up event.
Appears none of the events are being attached!
@stephenwaite are you looking into this?

**Comment by sjpadgett** [comment]
see PR for fix
