### ISSUE TITLE
css styling fail interface/forms/questionnaire_assessments/lforms/webcomponent/styles.css

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5813]
### Describe the bug

write concise description of what the bug is.
@sjpadgett noticed this failing test on questionnaire commit

![Screenshot from 2022-10-04 14-42-00](https://user-images.githubusercontent.com/5618372/193900175-d7e433fb-f267-4f9a-a461-ba5328ddda9b.png)

should it be added to `stylelintrc.json` `"ignoreFiles"` array or be un-minified?

**Comment by sjpadgett** [comment]
Should be ignored. Thsi file is temporary for patch and until next release.
