### ISSUE TITLE
Migrate graphing away from Open Flash Chart

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#583]
Due to several minor security issues, we need to migrate away from using open flash chart. A potential option is dygraphs .

**Comment by kevinelong** [comment]
We ave been using jqplot on some projects.

**Comment by sunsetsystems** [comment]
Here's a fairly recent list:

https://speckyboy.com/open-source-javascript-data-chart-libraries/

Definitely want to consider how active these projects are.

**Comment by robertdown** [comment]
Similar list to @sunsetsystems but from Github: https://github.com/showcases/data-visualization

**Comment by sunsetsystems** [comment]
Wow, we all have profile pics. :)

**Comment by bradymiller** [comment]
yep, it's profile pic galore (5 for 5 participants on this issue) :)

George and myself are planning on tackling this issue; first step will be finding a package and will start looking through the lists above.

**Comment by bradymiller** [comment]
chart.js looks feature rich, active, and can be brought in via bower (which is a plus).
Can see examples here: http://www.chartjs.org/

**Comment by georgetye** [comment]
Just checked out dygraphs. I really like how you can see the values for each data point as you hover over the chart, and how you can easily zoom in on specific areas. I'm not sure if that's a common feature for all charting libraries. Chart.js looks really elegant, too. It would be great if it also allowed for easily zooming in on specific areas.

**Comment by bradymiller** [comment]
@georgetye , that's a very nice analysis of the options.

My ranking so far is:
1. dygraphs. The panning, zoom stuff is really cool. it's ok on project activity. also has ways to working translations into date elements. only minus is can't bring in via bower, but no biggie since just 2 files.
2. chart.js. If only it had the panning,zoom stuff that dygraphs has. project activity is very high.

jqplot is tied to jquery and no development activity since 10/16. would be concerned that this package may be a drag on jquery version upgrading in the future. so, would consider removing this from the list.

d3 appears that it would take quite a bit of effort to produce simple line plots (correct me if I'm wrong on this) and doesn't offer the panning, zoom. so, would consider removing this from the list.

**Comment by robertdown** [comment]
Vote no on jqplot r/t jquery and lack of devel.

Like the activity and popularity of D3 and it does seem to have zooming (not sure on panning)

dygraphs is nice, but not as enticing as the activity/use of D3

**Comment by bradymiller** [comment]
To update on this, @georgetye has gone with dygraphs for now. The ability to pan and zoom in on the graphs is simply a killer feature when tracking vitals,labs etc which it does out of the box for the line charts (note it's not a simple pinch zoom or anything; can select a part of the graph and then it zooms in on it with x graph labels(ie. date/time) becoming more granular as it's done).

**Comment by georgetye** [comment]
I implemented my own version of the dygraphs example, where the test.html file is in the same folder as dygraph.js and dygraph.css. Seems to work fine in Firefox, but not in Chrome (not sure why, because on their website the examples work fine in both Chrome and Firefox).

Now I'm working on trying to implement the example found on the dygraphs website into `openemr/interface/patient_file/encounter/trend_form.php` It's not working, and I think it may be because I'm not referencing the dygraph.js and .css files properly.

I saw that the old flash charts used `../../../library/openflashchart/js/json/json2.js` as a reference. I followed suit and referenced `/../../../library/dygraphs/dygraph.js`, which should be the location of where I saved the dygraph.js and .css files.

Then again, the old flash charts haven't been working for me either, so I'm not sure what's up with that. I remember them working for me about a week or so ago.

**Comment by sunsetsystems** [comment]
I remember having to install the Shockwave Flash plugin into the browser before charting would work for the Vitals and LBF forms.

**Comment by georgetye** [comment]
Oh yeah, that could be it. I'll see.

**Comment by bradymiller** [comment]
Even if it's broken, feel free to post code on github and point to it here. Then will be easier to provide feedback.

**Comment by kevinelong** [comment]
From the field I can say that printing a graph is important to many clinics
so graphs must be printable first as well as optionally dynamic in my
experience. A graphs dynamism is not always obvious or dicoverable by the
average clinic manager and they are likely to orint and review data on
paper.

**Comment by bradymiller** [comment]
@kevinelong 
This is a very good point. Looks like doing a print screen on the dygraphs online examples works well.

**Comment by bradymiller** [comment]
Getting near a security deadline, so I am going to pick this up. Upon looking at this, it's going to be a bit complicated :) @georgetye , this may not of been a good project to start learning OpenEMR on :)

**Comment by bradymiller** [comment]
Just placed this upgrade into 5.0.1 codebase and plan to also get this into next patch (this fixes a security vulnerability).
Also plan couple more changes specific to 5.0.1 to make the styling a bit cleaner.
