### ISSUE TITLE
Clicking past encounter button on the EOB Invoice 

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#5837]
### Describe the bug
The past encounter button in the on the EOB Invoice page does not go show the past encounter listing

### To Reproduce

![image](https://user-images.githubusercontent.com/834958/195451757-25c0ee8b-8319-4090-abeb-185955c6f4e2.png)

1. Select Posting Payments from the main menu
2. Search for a patient
3. On the result screen select any invoice
4. On popover window select Past Encounter button.

### Expected behavior
Open past encounter history

### Client configuration

- Browser:  Firefox Chrome
- OpenEMR version: 7.0.0(1)
- Operating system: Ubuntu 20.04.5

**Comment by stephenwaite** [comment]
hi @juggernautsei , there's a few `toencounter()` functions like in the `encounters_report.php` and you might want to try testing that out and see if it works okay coming from the posting screen. Hopefully it doesn't interrupt the workflow like by switching out a tab that was needed.

**Comment by juggernautsei** [comment]
These are some of the changes that I made. 

https://github.com/openemr/openemr/blob/fba7a9fb4df8329b06f7c218af48d59ae9272206/interface/billing/sl_eob_invoice.php#L72

        function goEncounterSummary(e, pid) {
            if(pid) {
                if(typeof opener.toEncSummary  === 'function') {
                    opener.toEncSummary(e, pid);
                }
            }
            doClose();
        }

                        <button type='button' class="btn btn-secondary btn-view float-right" name='form_goto' id="btn-goto"
                            onclick="goEncounterSummary(e, <?php echo attr_js($patient_id) ?>)"><?php echo xlt("Past Encounters"); ?></button>

Now I am down to this error message.

![image](https://user-images.githubusercontent.com/834958/195469842-0c37c006-d5b1-43ed-ac8e-76ac80517f37.png)
