### ISSUE TITLE
no prompt for registration after login dev tip install

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#584]
PHP Fatal error:  Uncaught Error: Call to a member function getRegistrationId() on null in /var/www/html/emr/services/product_registration_service.php:55\nStack trace:\n#0 /var/www/html/emr/interface/product_registration/product_registration_controller.php(47): services\\ProductRegistrationService->getProductStatus()\n#1 /var/www/html/emr/interface/product_registration/product_registration_controller.php(41): ProductRegistrationController->get()\n#2 /var/www/html/emr/interface/product_registration/product_registration_controller.php(75): ProductRegistrationController->__construct()\n#3 {main}\n  thrown in /var/www/html/emr/services/product_registration_service.php on line 55, referer: http://23.30.162.115/emr/interface/main/about_page.php

**Comment by MatthewVita** [comment]
My bad!

A new modernization volunteer named Victor will be fixing this!

**Comment by kofiav** [comment]
Thanks Matthew. I will take a look at this.

**Comment by MatthewVita** [comment]
@kofiav has a fix for this. I've asked him to create a PR and we will see what the CI says...
