### ISSUE TITLE
Expose OpenEMR document categories heirarchy via FHIR api

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5853]
We'd like to make it possible for API consumers via FHIR to get a list of the document categories that are managed inside OpenEMR.  Currently people can put in a LOINC code into the document categories and this is the best option to be interoperable with other OpenEMR systems.  That said, if people don't do that or create their own custom categories that site outside of the what is available via LOINC, we still need to have an option to get a list of the categories (and their heirarchy structure).

Investigating what tools we can use in FHIR to do this it looks like we can expose the following endpoints in FHIR to accomplish this goal:

- **/fhir/ValueSet** 
- -  list of the ValueSets in the current OpenEMR instance.  For now would just have the doc categories in it
- **/fhir/ValueSet/openemr-document-categories** 
- -  A flattened list of all of the document category codes and their display names
- **/fhir/CodeSystem** 
- -  list of ALL of CodeSystems in OpenEMR with the codeable concepts specific to the OpenEMR installation.  For now just the document categories but eventually could hold things such as the values in our list_options table that can be used by api consumers
- **/fhir/CodeSystem/openemr-concepts** 
- -  the default OpenEMR codesystem that holds the codes specific to this instance.  
 
It may make sense to have an OpenEMR hosted terminology server that has the master value set and code system that OpenEMR instances inherit from and extend / modify... but right now where there is no versioning and people can add / remove doc categories and other concepts willy nilly this can be complicated.  My initial thought is to push this out with a status of **draft** as we collect feedback on whether this is going to work for the general users of OpenEMR.

My initial thoughts are to make the endpoints publicly accessible (no access token required) so that api consumers can download the code systems or lookup values without having to get into the mess of dealing with required scopes etc.  My only concern is if OpenEMR admins are creating any categories that contain patient PHI, such as a category that is the name of the patient.  If that is the case, then exposing those as categories in the CodeSystem will be a problem.  I'm hoping that's not the case...

**Comment by stephenwaite** [comment]
![Screenshot from 2022-10-18 10-19-38](https://user-images.githubusercontent.com/5618372/196456863-3171d423-1869-4e59-b019-dd80fa781520.png)

**Comment by adunsulag** [comment]
So after a number of discussions about security and exposing the categories.  We decided that we wouldn't fix this for the time being. I'm going to close this issue as well as the attached PR with the proposed fix until we have a way of addressing the custom ACLs for the documents as well as making sure categories can be hidden from exposure if the document access control list restricts this.
