### ISSUE TITLE
Enabling the CAMOS form is slightly broken

### ISSUE THREAD

**Issue by tsimonq2** [openemr/openemr#5901]
### Describe the bug

*(As a quick note to start, this work is being driven by my employer, [Altispeed Technologies](https://altispeed.com/). I'm actively working on this issue. Any screenshots shown use test data, and are not associated with any real patient.)*

### To Reproduce

 1. Install the CAMOS form using the expected workflow
 2. Import a database dump from another EMR instance that does not have CAMOS enabled or installed in the DB
 3. Repeat step 1

![image](https://user-images.githubusercontent.com/3689821/199593141-11a4b85e-962f-4947-a09a-0cce4235665e.png)

### Client configuration

- Browser: Firefox Nightly
- OpenEMR version: tip of master
- Operating system: Ubuntu Devel (currently 23.04)

**Comment by tsimonq2** [comment]
These tables already seem to exist in the database:

```
| form_CAMOS                            |
| form_CAMOS_category                   |
| form_CAMOS_item                       |
| form_CAMOS_subcategory                |
```

The next question I come to is, why does it show as "not installed in the db"?

**Comment by bradymiller** [comment]
hi @tsimonq2 , The registry table keeps track of when forms are registered/databased/on/off . I'm thrown off by how the data in registry table would not match up with which forms have been installed into the database.

**Comment by tsimonq2** [comment]
Sounds good, will be digging into this the week of the 13th, I'm at the Ubuntu Summit this week :)

I appreciate your feedback, @bradymiller.

**Comment by sjpadgett** [comment]
> I'm thrown off by how the data in registry table would not match up with which forms have been installed into the database.

Me too!

**Comment by mdsupport** [comment]
@ tsimonq2 Not a emr bug. By manually import of db tables you put autoincrement counter out of sync. Move that counter to max(+1?).
