### ISSUE TITLE
Add database comment explaining what procedure_order_title does in procedure_order_code table

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5918]
Ran into this problem again one year later where I couldn't figure out the difference between procedure_order.procedure_order_type and the procedure_order_code.procedure_order_title.  We need to add comments to these fields in the database schema to clarify their intent and purpose.

procedure_order is the original provider/staff order for a 1...* procedures to be ordered.  It is the starting point / holding structure for what shows up in the encounter forms -> Procedure Order form.  The individual items that are ordered as part of the procedure_order are contained in the procedure_order_code table.  Once an order has been created the the type of the overall procedure order is populated in the procedure_order.procedure_order_type.  A record for each item in the order is created in the procedure_order_code table and the procedure_order_title is populated with the same value as what is in the procedure_order.procedure_order_type field.

This field is used in FHIR for populating the type of procedure order.  The procedure order type must be laboratory_test if you are wanting FHIR Diagnostic Report LAB results to be returned.  

I ran into this problem a year ago and so I thought I'd document here and put an issue to remind myself or others to come back and either rename the procedure_order_title field to be more appropriate or add a comment to the DB schema explaining what it does and how its used.

**Comment by sjpadgett** [comment]
The only reason title is used as we use it now was to distinguish it for document typing(image, lab_result etc) from patient documents.
It was an existing column that appeared at the time to have no use so I coopted it for FHIR API reasons.

**Comment by morg0n** [comment]
Hey all, is adding that comment in the DB schema still something we are interested in?
