### ISSUE TITLE
FHIR DateTime search with timezone component fails to adjust to local server time

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#5919]
The DateTime search using a timezone component fails if the server and the requestor are on a different timezone.  We need to make sure we adjust the search queries to use the local server time instead of the requestor timezone.

For example a query such as this: 
```
/apis/default/fhir/DiagnosticReport?category=LAB&date=2015-06-22T04:00:00%2B00:00
```
Will fail to return any data if the local server timezone is set to **America/New York** and the database procedure order dates are saved as **2015-06-22 00:00**.  

We need to parse the timezone information on the incoming request and we need to adjust the timezone at the time we generate the FHIR search queries.

**Comment by sjpadgett** [comment]
Hmm why would a date request from distant insist on including TZ?

**Comment by sjpadgett** [comment]
looks like a recommend so yeah!

Where possible, the system should correct for time zones when performing queries. Dates do not have time zones, and time zones should not be considered. Where both search parameters and resource element date times do not have time zones, the servers local time zone should be assumed.

**Comment by adunsulag** [comment]
@sjpadgett FHIR datetime search queries can include time zone information.  FHIR inferno is using them in their latest update so I have to handle the use case. I do take care of the situation where the OpenEMR records only track dates and not times.

**Comment by adunsulag** [comment]
Going to open this issue again because I'm not handling Daylight Savings Time timezone correctly.  This is pretty tricky since we don't save dates internally in OpenEMR in UTC time.  Also of note, it looks like we've been converting all of the dates reported as being in the UTC timezone instead of a UTC timestamp with **the timezone adjusted for the local time**.  That's a big problem and hard to believe I missed it.  Going to put a PR out with the fix.  Again because we don't save UTC internally it means we have to change this in a lot of places for FHIR, hopefully we get them all.
