### ISSUE TITLE
Patient Context Image Enhancement

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#593]
@Jeffrey-P-McAteer and I were on a Google Hangout the other day and Jeffrey mentioned that it would be neat to show the patient's picture in in the "context box". While this image is viewable in the main patient page via the "ID/Card Photos" toggle, it can be argued that showing a small version of the patient image across the app is a better user experience because the user may be on the other pages (billing, labs, documents, encounter, etc).

In terms of implementation, we can use the `$GLOBALS['patient_photo_category_name'])` and the existing query:

```
select documents.id from documents join categories_to_documents " .
                 "on documents.id = categories_to_documents.document_id " .
                 "join categories on categories.id = categories_to_documents.category_id " .
                 "where categories.name like ? and documents.foreign_id = ?";
```

We also need to make sure this works when we grab the image from Couch.

In terms of design, we can put it next to the existing content (kind of sloppy, in my eyes): 

![simple](https://cloud.githubusercontent.com/assets/1715206/24334238/1b30f3ae-1235-11e7-9a33-265fa924ef53.PNG)

Or we can redesign the context box to be a "card" (WARNING: I am terrible at sketching):

![webcam-toy-photo5](https://cloud.githubusercontent.com/assets/1715206/24334239/1b320f32-1235-11e7-81fe-67a1a983b519.jpg)

Matthew

**Comment by MatthewVita** [comment]
@robertdown would like your thoughts here, Mr. Designer :)

**Comment by bradymiller** [comment]
Hi @MatthewVita and @Jeffrey-P-McAteer ,

This is a great idea and looks nice on your screenshot (that patient also looks great for being 102 years old :) ). Would be nice for it to get bigger if click on it also. Agree getting @robertdown eyes for this would be good.

I'm going to link in a related project where somebody else may be working on placing images in the calendar appt, since there was a discussion there of how to get images and pitfalls to avoid.
https://github.com/openemr/openemr/issues/568

-brady

**Comment by Jeffrey-P-McAteer** [comment]
I like the card design approach, I imagine the same code could be re-used in other areas (possibly calendar) wherever we display patient data.

One thing to remember when building is that not all patients will have images associated with them - when this happens we should either make a random image a la GitHub's "identicon" or use initials like Apple's contacts design.
(Or be lazy bums & have a default image, but this perpetuates the original problem of mistaking which patient one is managing)

Another pitfall is aspect ratio - I'm all for forcing 1x1 squares about 2.5 lines of text high, which means we'd need a UI for cropping images (No idea if this already exists).

**Comment by MatthewVita** [comment]
@Jeffrey-P-McAteer good thoughts. Let's go with the "card" approach and let our resident designer Robert tweak it as needed. Do you want to be assigned to this task? Do you mind putting this logic in a centralized service (don't need to do Doctrine for now)... perhaps `services/PatientInformationService.php`?

Some thoughts/feedback (Robert's directions should be taken over mine, of course):

- When a patient doesn't have an image, don't show anything
- I'm not worried about aspect ratio... we can set a height and let CSS/HTML figure out the width. In fact, we can set a max width and call it a day.

Thanks,
Matthew

**Comment by Jeffrey-P-McAteer** [comment]
Sure, I'd love to start there.

**Comment by MatthewVita** [comment]
Labeling this as `Modernization Project` because we agreed to put the logic in a service :)

**Comment by robertdown** [comment]
If I remember correctly, I had a nice big pic of the patient on the main demo view. Let me find it and post a screenshot....

**Comment by robertdown** [comment]
From a usability standpoint, do you think the size of this image would be effective? I fear it'd be too small for to be used effectively and then it only clutters an already crowded part of the UI.

On the other hand, the avatars on the side of this convo are likely smaller than what you're suggesting and they do the job. They help jog my memory of who is saying what.

Overall I think it's good functionality to have as it seems we have at least 1 other place this needs to be used.

I am a fan of consistency, so if the setting is on I suggest displaying the first and last initials like Apple does (I'd personally opt for the Github solution but that may be a bit too techy)

I'm all for forcing a 1:1 aspect ratio.

As this gets closer to the UI stage I'll start really tweaking - @MatthewVita and @Jeffrey-P-McAteer just let me know. The user context bar is really an eye sore in my opinion, but it was a trade off for getting tabs into v5. This very well may force me to actually get it in tip top shape

**Comment by MatthewVita** [comment]
Hey Robert, thanks for your thoughts!

@Jeffrey-P-McAteer has an early screengrab of his work. Jeffrey, please feel free to share!

Also, I've seen other EMRs with the small patient image in context, so we should be okay.

**Comment by Jeffrey-P-McAteer** [comment]
Here's the one from my email, it isn't anything definitive. I was just playing with /interface/main/tabs/templates/patient_data_template.php. I'm still not 100% certain how to go about linking a service to the client-side knockout setup, but I'm poking around when I get the time. ![scrot_991x417](https://cloud.githubusercontent.com/assets/15269507/24683680/ab5f8068-196e-11e7-81c5-7e1b1e966dcd.png)

**Comment by MatthewVita** [comment]
@robertdown my only comments were to add some white background to the box so it doesn't bleed with the background of the webapp and make the width of the box only as wide as the text itself. If you agree with that, can @Jeffrey-P-McAteer move forward with this?

**Comment by MatthewVita** [comment]
UPDATE:

@Jeffrey-P-McAteer is working on a `PatientInfoService.php` to centralized this business logic :)

**Comment by robertdown** [comment]
I'd not put a background on the box or a border around it

**Comment by Jeffrey-P-McAteer** [comment]
But keep a shadow?

**Comment by robertdown** [comment]
I would not style the box at all as we write it, add some abstract class names to stuff but let each style.css handle styling the box. For example, the Light and Radiant themes are heavily influenced by flat designs and adding a box shadow would really break the UX.

Assign some class names and I'll get the default theme updated to match it. Also, I really think we need to keep the image display as a square, not a circle -- in my opinion the pic is too small to use a circle.

**Comment by Jeffrey-P-McAteer** [comment]
Will do. Currently learning knockout & looking at existing code.

**Comment by MatthewVita** [comment]
@Jeffrey-P-McAteer did you need a hand with this? I realize you're doing cloud stuff, but it would be cool to get this in at some point.

**Comment by Jeffrey-P-McAteer** [comment]
I need to work on time management; so while one good answer is "yes I'd love help" it solves time management by removing pressure instead of optimizing workflow. I'd prefer to have something I'm responsible for to help me focus, but I also don't want to encumber the rest of the team. For this particular item my biggest hurdle is learning how your frontend javascript talks to the database.

**Comment by MatthewVita** [comment]
@Jeffrey-P-McAteer Fair enough. Let's do a Google Hangout session to do some problem-solving. Will send you an email.

**Comment by MatthewVita** [comment]
@Jeffrey-P-McAteer I know I threw a good amount of info at you in our last call, but did you need any more guidance on this ticket? No pressure (I know you are busy, of course) just wanted to check in!

-m

**Comment by Jeffrey-P-McAteer** [comment]
No, thanks for doing that. I have the query setup & it's using a static url (http://site.com/sites/default/documents/1/profile-here.jpg), but I haven't gotten to the point where the image will refresh as soon as it is changed - you need to manually reload the entire UI. Should I submit a pull request & make incremental improvements?

**Comment by MatthewVita** [comment]
Hi Jeffrey,

It doesn't need to update when it is changed because that won't happen that often. However, it does need to paint once an image is uploaded. You'll probably want a special JavaScript hook to fire at that point. Look me know if you need help in this regard.

I would say that a pull request would be a great step.

Quick questions:

- If there's no picture, is there a default shown?
- Have you tested your solution with the CouchDB file mode on?

**Comment by Jeffrey-P-McAteer** [comment]
1) Yup, it's ./public/images/def-profile.png
2) No, is that this http://www.open-emr.org/wiki/index.php/CouchDB_Documents_Module?
Screenshots:

![scrot_938x425](https://user-images.githubusercontent.com/15269507/27106045-c393b370-505f-11e7-8cf9-fdb59c45401b.png)
![scrot_1054x415](https://user-images.githubusercontent.com/15269507/27106044-c3929e54-505f-11e7-864e-a005a820476b.png)
![scrot_1268x323](https://user-images.githubusercontent.com/15269507/27106046-c3962c2c-505f-11e7-9888-d153b81c50a4.png)

**Comment by MatthewVita** [comment]
Looking good!!!

Did you get the JS code in place to paint (or repaint) once an image is uploaded?

Yup, that is the CouchDB module. It is easy to setup and I'm thinking that your code will work just fine with it enabled, but there's only one way to know!

Thanks,
Matthew

**Comment by Jeffrey-P-McAteer** [comment]
Haven't written code to handle repaints yet, but I'll do that & test with CouchDB, then submit a pull request? Sorry this has taken me forever. Summer got super busy.

**Comment by MatthewVita** [comment]
Sounds good! It's okay if it's takes a while because in the end you are getting the work done and the feature will delight the users (anything that makes healthcare more personable is best!)

**Comment by MatthewVita** [comment]
BTW, please check out `interface/forms/eye_mag/php/eye_mg_functions.php` starting at line 3551

**Comment by MatthewVita** [comment]
Hey @Jeffrey-P-McAteer, is there anything I can to help ?

**Comment by Jeffrey-P-McAteer** [comment]
No idea. I think I'm becoming far to busy to be helping out here, but I also don't want what ~20 lines of code I've written to go to waste. If i can learn how to hook some javascript in whenever a new patient is selected I could probably make things look nice & submit a pull request, but at the soonest it would be sometime next week.

**Comment by MatthewVita** [comment]
Okay @Jeffrey-P-McAteer, I will get back to you with some code snippets for the JavaScript on Saturday!

**Comment by MatthewVita** [comment]
@Jeffrey-P-McAteer,

Here is how you can go about handling the JavaScript stuff when the image is uploaded or changed.

1. C_Document.class.php `upload_action_process` function should check to see if the file being uploaded has a category that matches `$GLOBALS['patient_photo_category_name'])`.

2. If so, set `$this->assign("should_refresh_patient_image", true)`;

3. In general_upload.html, check value of `$should_refresh_patient_image`

4. If true, call `top.window.parent.top_area.setPatientImage()` (make sure this is loaded in main_screen.php... you'll have to create the JS file and function. Basically you'll want to swap out the source... see http://www.designchemical.com/blog/index.php/jquery/jquery-image-swap-gallery/)

Does this make sense?

**Comment by MatthewVita** [comment]
The `top_area` may confuse you. This needs to be exposed from a higher DOM context because it will be called from a child iframe. This iframe (the area where documents are uploaded) has NO idea about the rest of the screen (left nav, top menu bar, etc).

**Comment by MatthewVita** [comment]
Hi @Jeffrey-P-McAteer, just want to let you know that I just put in a PR with the base work done for this. The PR is here: https://github.com/openemr/openemr/pull/926

I know your time has been limited with this, so I wanted to provide a solution so you can see an approach. With this said, I left some work for you. The -5px margin is not a good idea and the JavaScript hook is not in place.

Please spend some time studying the code and then you can pick up with the remaining work!

- m

**Comment by MatthewVita** [comment]
Hey @Jeffrey-P-McAteer, just wanted to bug you again to see if you wanted to tackle the remaining work for this? If not, feel free to close the issue and we'll find something else for you to jump into. I'm here to make sure you're

a) engaged and happy 
b) have tasks that are light on timing because I know of your busy schedule

That said, hit me up here or schedule a Google Hangouts with me.

**Comment by Jeffrey-P-McAteer** [comment]
Thanks for bugging me, I spent the evening kludging together a working solution. The only thing that isn't handled at the moment is deleting a profile image - the old one persists until the page is reloaded.

https://github.com/openemr/openemr/compare/master...Jeffrey-P-McAteer:master
Let me know exactly how what I did differs from what was in your mind - half the technologies in this are completely new to me (knockout & smarty templates?) and I'd like to learn the proper way to use them.

**Comment by MatthewVita** [comment]
@Jeffrey-P-McAteer, great stuff! Please see https://github.com/MatthewVita/openemr/tree/patient_picture_enhancements_jeffrey

This is a branch that incorporates your changes with a few tweaks to make things a tad more concise. Please add to this to handle deletion and we'll get it merged in.

Great work!

**Comment by MatthewVita** [comment]
Note that we'll amend the commit to have your authorship. I just threw together this branch so you can pull it down. Have a feeling it will be a good base for your remaining work with the deletion stuff.

**Comment by MatthewVita** [comment]
Hopefully the KO changes I made make sense. Let me know if not and we'll have a call

**Comment by MatthewVita** [comment]
Hi @Jeffrey-P-McAteer ,

This post is in response to the PR you put on my OpenEMR fork. I think you are on the right track, but it may be best to do the following as "homework" and I'll definitely be free to do as many Google Hangouts as you need during the week if you need help. You are certainly a Linux and Docker guru, time to be a PHP guru (this project will thank you for it!).

There are a lot of unrelated commits in the PR making it hard to focus on your changes. This is not a big deal. It's very easy to remedy and I will explain below!
- You submitted the PR on my OpenEMR fork. While this flow can work, it is problematic because my fork isn't up to date with the upstream OpenEMR repo. Here is what you'll want to do instead:

```
$ # click "Fork" button at https://github.com/openemr/openemr
$ git clone git@github.com:Jeffrey-P-McAteer/openemr.git
$ cd openemr
$ git remote add upstream https://github.com/openemr/openemr.git
```

At this point, you now have a fork repo of OpenEMR and it's totally even (for now at least...). Let's take a step back to make sure we're on the same page with the patient picture stuff.

- I committed in (to `master` from my fork as a PR) https://github.com/openemr/openemr/commit/882060bd5976e8046f229c16f75459fb85e7ca91 to get the base foundation of the feature out of the way because I realize I threw a lot at you. Please study the code here and ask questions!

- I'm not very smart and Robert pointed out some issues with my base commit, so I committed those fixes (to `master` from my fork as a PR) here: https://github.com/openemr/openemr/commit/40f4c504f55ed7d4f08fef59b973c47c18eeab54 Again, please study. Not much going on in this one.

- As for where you can pick up on the base work, there is a need to auto refresh the image on certain actions (when it's changed/added/deleted, for instance). I put this commit on a throwaway branch on my fork for you to use as inspiration: https://github.com/MatthewVita/openemr/commit/86810592f634f1ce73be7ea634c8dfac429adb3a

At this stage, here is a good roadmap for you to follow:

```
$ # (cd into your fork)
$ git pull upstream master
$ git checkout -b patient_picture_event_handlers
$ # do your work here by manually copying in ideas from the commit above (note you will need the change in  contrib/util/docker/Dockerfile for this to work... need to open up documents area)
$ git add ... git commit ...
$ git checkout master
$ git pull upstream master
$ git checkout -
$ git merge upstream/master # Creates a new commit on patient_picture_event_handlers, that contains all changes from master - resolve merges here using git mergetool
$ git reset --soft upstream/master # Generates a set of staged changes of everything that was done
$ git add -A
$ git commit -m 'Patient picture event handlers'
$ # open app and ensure all is well
$ git push origin patient_picture_event_handlers
$ # visit https://github.com/openemr/openemr and you should see a yellow bar for pull requests, do that and make sure the base is right
$ # assign me to the PR and I'll test it out and into `master` on the formal repo it will go
```

**Comment by MatthewVita** [comment]
@Jeffrey-P-McAteer how does this sound :)
