### ISSUE TITLE
uuid not defined in class array

### ISSUE THREAD

**Issue by rgenandt** [openemr/openemr#5940]
### Describe the bug
json encoding bug with FHIR when there are surgeries on file

write concise description of what the bug is.
line 40 of src/Services/SurgeryService.php needs the recorder_uuid added to the defined array of uuids

### To Reproduce
Try a FHIR Procedure call with a patient that has surgeries in lists

**Comment by adunsulag** [comment]
It looks like this bug shows up only if the recorder has an NPI number.  If the person who added the surgery was a staff or administrator but not an actual licensed clinician the bug doesn't trigger which it looks like is the case with our ONC test data set.  We'll get it fixed.  Thanks for the bug report!
