### ISSUE TITLE
The system was finding any previous insurances for a specific type (primary, secondary, etc)

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#5955]
### Describe the bug

The system was finding any previous insurances for a specific type (primary, secondary, etc). However, if a patient had 2 insurances before and now has 1 or none (self-pay), this would not work and would give wrong info. My fix actually looks for current insurances on that specific date.

### To Reproduce

Go to front payment for any patient and add a pre-payment for $100. Then see if you can locate it anywhere. Anywhere at all… It’s hard to locate and no one will know that the patient made a pre-payment. With my fix, it will be in the billing card for the patient as soon as the chart is pulled up.

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by adunsulag** [comment]
@juggernautsei Is this issue fixed?

**Comment by juggernautsei** [comment]
Yes, this has been addressed and is no longer an issue since 7.0.0 (1)
