### ISSUE TITLE
PHP 8 Exception in C_Document.class.php

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5970]
### Describe the bug

![Screenshot from 2022-11-19 14-41-04](https://user-images.githubusercontent.com/5618372/202868551-91216ab3-b2c4-43ed-855c-41f5b00471f8.png)

### To Reproduce
it's only a `Notice` but is interfering with vscode debugging 

try to step through a person's documents

![Screenshot from 2022-11-19 14-43-19](https://user-images.githubusercontent.com/5618372/202868638-c4dbb1d9-8ee7-4d85-a609-15093363765a.png)

**Comment by sjpadgett** [comment]
@stephenwaite 
Looks like your nemesis is in library/classes/TreeMenu.php
Remove the reference for node parameter. It's already passed as a reference so why reference a reference? 
```
function &addItem($node)
    {
        $node->parent  = &$this;
        $this->items[] = &$node;

        /**
        * If the subnode has ensureVisible set it needs
        * to be handled, and all parents set accordingly.
        */
        if ($node->ensureVisible) {
            $this->_ensureVisible();
        }

        return $this->items[count($this->items) - 1];
    }
```
