### ISSUE TITLE
Site ID is missing from session data! after clicking Open button for pdfs in documents with chome browser

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5971]
### Describe the bug
![Screenshot from 2022-11-19 14-48-15](https://user-images.githubusercontent.com/5618372/202868803-5cfa1b87-b9a1-4ff6-b862-4387684d3544.png)

clicking `Open` button results in:

![Screenshot from 2022-11-19 14-48-41](https://user-images.githubusercontent.com/5618372/202868819-237b9a06-155c-4347-b943-5522b344aa3b.png)

**Comment by sjpadgett** [comment]
@stephenwaite 
I can't find where the Open button is sourced to render. Do you know?
Also this workflow scenario doesn't make sense i.e. essentially a download and frame target prob shouldn't be _blank(new window)!
