### ISSUE TITLE
csv export for appt report

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#5973]
### Describe the problem

currently there's no button to export appointments as a csv

### Describe the solution you'd like

add a button that will export some fields from the submitted appt report

**Comment by stephenwaite** [comment]
hi @gutiersa, here's the issue and #5974 which is testing well, only exports 3 fields for now but easy to add more

**Comment by mdsupport** [comment]
You can also leverage this [PHPOffice sample script](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Basic/01_Simple_download_xls.php) to get file that will not need extra step of importing/converting in end applications.

Better yet, implement a generic class that uses given recordset to populate table with keys as title row and download as a method.

**Comment by gutiersa** [comment]
So cool, thanks. I am going to install and text now.

**Comment by gutiersa** [comment]
So, would it be very hard to get the DOB included? I notice that is not part of the appointment report.

**Comment by stephenwaite** [comment]
for now if someone just wants a `csv` there's no extra step of importing @mdsupport 

however if the use case is to open up in a spreadsheet then can follow your advice, thank you

**Comment by mdsupport** [comment]
The iofactory is very useful as you can specify the file type as a parameter. This includes even PDF is mpdf or other supported libraries are available.

Best.

**Comment by gutiersa** [comment]
This feature has been a game-changer for me. It is now a breeze to download 15 patients' worth of PMPs.
The only thing I have not been able to figure out is that once I download the file, if I want to resubmit, say I change dates, for example, clicking the submit button behaves as the download button. What I mean, is that after downloading once, "submit" continues to download rather than refreshing the page.

I am not sure how this is fixed.

**Comment by gutiersa** [comment]
I have made a few changes. My next goal would be to conquer github so I can contribute changes to the project.
One of the changes is that I added today's date to the downloaded file.

Finally, I would love to add checkboxes to different areas so people can select what to include in their download. This is a little involved, right? It would require a function that takes the checkmarks and generates the printout, wouldn't it?

**Comment by stephenwaite** [comment]
> if I want to resubmit, say I change dates, for example, clicking the submit button behaves as the download button. What I mean, is that after downloading once, "submit" continues to download rather than refreshing the page.

hi @gutiersa , can add something that will reset that `POST` variable and today's date too beyond that it's going to be too much for me right now.
