### ISSUE TITLE
MRD Cards not honoring collapse/expand setting

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#5989]
### Describe the bug

The MRD Cards are not respecting the collapse/expand setting, cards are closed by default. I have no doubt that I broke this feature during the MRD UI enhancements - assigning to myself.

### To Reproduce

1. Open a patient
2. Expand Demographics
3. Close patient
4. Open patient

### Expected behavior

1. Demographics should be open (If following above steps)

### Client configuration

- Browser: FF 107
- OpenEMR version: 7.0.0
- Operating system: Win 11

**Comment by sjpadgett** [comment]
I believe I fixed this in patch 2

**Comment by robertdown** [comment]
Noted - I'll confirm in a bit

**Comment by robertdown** [comment]
Confirmed - resolved in master branch, closing. Thanks for cleaning up my mess, @sjpadgett
