### ISSUE TITLE
angular no longer supported

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#6008]
Not sure what this means (don't know where we are using this package in OpenEMR), but noted this as updating the npm packages (looks like may need to migrate to @angular/core, although have not researched this).
https://docs.angularjs.org/misc/version-support-status

**Comment by adunsulag** [comment]
Where did you hit this problem?  It looks like the messaging and chat stuff in the portal is the only place I could find this was impacted.

**Comment by sjpadgett** [comment]
Just leave package version on last release. It will get archived and repo will be maintained indefinitely.
I have plans to remove the chat app as I don't think it was or is used!
The secure messaging app is a required feature and when time permits I will rewrite.
