### ISSUE TITLE
Need a way to add custom navigation to the patient dashboard

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#6013]
### Describe the problem

We want to add a button to the patient navigation bar. 

### Describe the solution you'd like

The idea would be to create a module that injects java script into the demographics page. That would allow us to populate a div with whatever button or custom logic we see fit.

**Comment by robertdown** [comment]
I'm surprised there isn't a hook for this

**Comment by juggernautsei** [comment]
Well, that is what my trial and error came up with. I feel a little defensive. 
If there is another way to do this. Let me know. I know you understand the point of the code.
This goes with the other eventDispatch that I submitted. The dispatch of the post page load allows for the java script to render the button that I am injecting into the page looking for the div with the the custompatientnav id. That renders the button in my scenario. Of course other can use it to do other things if they so choose. I tried setting a dispatch event inside the </nav>. 
I could not get it to work. I hope I have over explained this enough. =^)8

**Comment by robertdown** [comment]
Apologies if I have made you feel defensive.

I see #6014 modifies [`displayHorizNavBarMenu()`](https://github.com/openemr/openemr/blob/9dc161d8d5b3fa71508b3e9f23b7c3e4aea49b97/src/Menu/PatientMenuRole.php#L100) adding an empty `div` element with a hard-coded ID which I assume your javascript is manipulating to render the button.

If we look in the same PatientMenuRole.php file at [`getMenu()`](https://github.com/openemr/openemr/blob/9dc161d8d5b3fa71508b3e9f23b7c3e4aea49b97/src/Menu/PatientMenuRole.php#L49) it looks like the event you want to interact with is [`PatientMenuEvent::MENU_UPDATE`](https://github.com/openemr/openemr/blob/9dc161d8d5b3fa71508b3e9f23b7c3e4aea49b97/src/Menu/PatientMenuEvent.php#L19) which will give you access to the menu where you can inject your custom menu item.

There is an opportunity here to make that nav bar a bit more robust. The [`displayHorizNavBarMenu()`](https://github.com/openemr/openemr/blob/9dc161d8d5b3fa71508b3e9f23b7c3e4aea49b97/src/Menu/PatientMenuRole.php#L100) function hard codes a lot of the templating to render the nav bar. That logic could be migrated over to a twig template and refactored a bit to be a bit more robust.

**Comment by juggernautsei** [comment]
I don't want to change the menu. I am injecting a new menu already which adds the Authorizations to the menu. This button is not a menu item. To me it is outside of the menu and behaves differently than a menu item. 

It is not you that makes me feel defensive. But it is in me.

**Comment by robertdown** [comment]
Perhaps there is a difference, but you still have control of the button through the menu event as you can assign an ID to the button. From there you could use JS to inject particular styling classes to the element.

Since you are already using javascript to inject the button into `#custompatientnav` I would recommend using JS to get the nav element directly and append to it. I imagine your current code is something like
```javascript
let custom_nav = document.getElementById('#custompatientnav');
custom_nav.append(); // Append the button
```
Instead you could do:
```javascript
let navbar = document.querySelector('nav.navbar:first-of-type');
custom_nav.append(); // Append <div id="custompatientnav"></div> here and anything else you need
```

This gets you to your goal (I think) and does not introduce a placeholder `<div>` into the codebase.

**Comment by juggernautsei** [comment]
I will work on this.

**Comment by juggernautsei** [comment]
@robertdown 
This is what I ended up with after working this out.

    <script>
        let navbar = document.querySelector('nav.navbar:first-of-type');
        let ele = document.createElement("div");
            ele.id = "customepatientnav";
            ele.innerHTML = '<button class="btn btn-success" id="addButton">Mark Active</button>';
        navbar.appendChild(ele);
    </script>

Code base change averted. I will remember this for the future.
