### ISSUE TITLE
Demo Down

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#6015]
[Demo System](https://one.openemr.io/a/openemr/setup.php?site=default) is currently reporting `PHP version needs to be at least 8.0.0`.

Guess there should be a better way to show this obituary.

**Comment by bradymiller** [comment]
Will plan some "demo tetris" after get the new alpine release incorporated. In the end, will likely just have 1 dev demo that uses an outdated php 7.4 to ensure see that message (since we have actually broken that feature/message in the past).
