### ISSUE TITLE
Merge Patients usability improvements

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#6024]
OpenEMR 7.0 Patch 1.

I periodically do a lot of merging using Admin > Patients > Merge Patients.

I begin by copy and pasting the ID into the "for:" box. When I open the merge dialog the field to paste my search query in, tantalisingly has the cursor in but only momentarily then it goes and I have to click on the "for:" box. If the cursor could be in that box automatically then that would be a time saver.

If there were a means for me to set "ID" be the default option in "Search by:" then that would also be helpful.

And, after merging, there's a button to go to Manage Duplicates, but to get back to the Merge Patients, the closest option is the tiny 'refresh' icon, which, being so small, is more effort to click on (when you're trying to get through lots of these with minimal effort) than if there were instead a button as equally large as that for Manage Duplicates.

If Source Patient could be above Target Patient in Merge Patients then that would be more intuitive for me. Though I appreciate this might not be the case for everyone.

Thank you

**Comment by sjpadgett** [comment]
> If Source Patient could be above Target Patient in Merge Patients

I agree however lets see if @sunsetsystems has an issue with a restructure since he brought this in I believe.
