### ISSUE TITLE
Layout-based Form Validation Isn't Implemented on the Backend

### ISSUE THREAD

**Issue by tsimonq2** [openemr/openemr#6027]
### Describe the bug

When editing an LBF form (`Admin -> Forms -> Layouts -> LBFfoobar`), the option exists for data validation given a specific row (using `?`). The data validation portion of this simply does nothing. I can preview this form and create a new one under a test patient, in both cases, with alphanumeric values. No error is presented and the form is saved as if these rules are not even being considered.

I see no usage of the validate.js library under `interface/forms/LBF`. I would be willing to implement this, given some guidance on "where to put it." I was also able to confirm this bug on the demo OpenEMR instance.

### Client configuration

- Browser: Firefox Nightly
- OpenEMR version: tip of master
- Operating system: Ubuntu Lunar Lobster (what will become 23.04)

**Comment by sjpadgett** [comment]
Demo at: [Dev Demo Login](https://three.openemr.io/a/openemr/interface/login/login.php?site=default) 


- To view and/or register questionnaires select New Questionnaire from Questionnaires menu.
- Search for existing imported questionnaire from repository.
- Select one and viewer will render so you can test or view.
- Then either do a one time Save or Register the form where it becomes available in menu for any encounter.
