### ISSUE TITLE
Somewhat broken conditional parameters for LBF

### ISSUE THREAD

**Issue by tsimonq2** [openemr/openemr#6028]
### Describe the bug

When trying to use the data conditionals feature (`Admin -> Forms -> Layouts -> LBFfoobar` -> `?` [under a specific row]), the exact opposite functionality occurs. Here's an example:

![image](https://user-images.githubusercontent.com/3689821/207973666-7c7e9d1f-9f0d-4bc5-bed6-96b402100893.png)
will, in reality, produce:
![image](https://user-images.githubusercontent.com/3689821/207973797-b099290a-ba26-498e-a7aa-04177100a084.png)
when `leftatriummeasure` is blank, or any value. What is particularly confusing is, if `leftatriummeasure` actually does equal `5`, that value does not disappear or change. There is no default value for `la_summary`.

Here is another case which does not work as intended (and still displays the text box with "yay" despite `la_summary != 5`):
![image](https://user-images.githubusercontent.com/3689821/207974895-cfad881b-d45e-4606-a0e9-7d54b7b17d75.png)

These are the only working parameters to display "yay" iff `la_summary == 5`:
![image](https://user-images.githubusercontent.com/3689821/207975133-c5528c69-9b7f-40ed-a1b0-1fdc46ab2700.png)

I can confirm this functionality on the demo 7.0.0.2 instance.

Is this intended functionality? At the very least, it's quite non-intuitive.

### Client configuration

- Browser: Firefox Nightly
- OpenEMR version: tip of master
- Operating system: Ubuntu Lunar Lobster (what will become 23.04)

**Comment by sjpadgett** [comment]
While not wanting to get into how intuitive skip logic and conditionals are implemented(not disagreeing in general Simon), last I looked it was working in v7 however, I'll take a look when I have time.
