### ISSUE TITLE
LBF conditionals not designed for checkboxes

### ISSUE THREAD

**Issue by tsimonq2** [openemr/openemr#6029]
### Describe the bug

I have the following row in a form:
![image](https://user-images.githubusercontent.com/3689821/207975936-7de0a914-dfc9-43d7-b234-f0855ec6996c.png)

When selecting `?` and defining any conditional value (as shown here:)
![image](https://user-images.githubusercontent.com/3689821/207976113-701e58c1-4295-4bf1-a4a0-eec46be717e4.png)
I'm presented with the following message:
![image](https://user-images.githubusercontent.com/3689821/207976265-f7e1c141-3462-4a4d-b7de-9f3a14c9bbd0.png)

This bug exists in `library/options.js.php` on line `241`. This is because there is no one, specific value for checkboxes. Here's some simplified structural code showing this bug:
```
<div id="value_id_la_summary">
    <table>
        <tbody>
            <tr><td><input type="checkbox" name="form_la_summary[la-normal]" id="form_la_summary[la-normal]" class="form-check-inline" value="1" onchange="checkSkipConditions();">Left atrium is normal in size</td></tr>
            <tr><td><input type="checkbox" name="form_la_summary[la-abnormal]" id="form_la_summary[la-abnormal]" class="form-check-inline" value="1" onchange="checkSkipConditions();">Left atrium is abnormal in size</td></tr>
        </tbody>
    </table>
</div>
```

There isn't exactly wildcard support for something like `form_la_summary[*]`. What's a good solution for checkboxes?

### Client configuration

- Browser: Firefox Nightly
- OpenEMR version: tip of master
- Operating system: Ubuntu Lunar Lobster (what will become 23.04)

**Comment by sjpadgett** [comment]
Whatever LBF you're trying to implement I'd think could be done with Questionnaire feature.
That feature has great plans for the future.

**Comment by tsimonq2** [comment]
@sjpadgett If you'd like to know exactly what I'm trying to do, in short I'd like a given numerical value (e.g. an integer range) to control which sentence is displayed in another part of the form. If that's possible with questionnaires, that would be great, and I'd appreciate some brief instructions for that functionality specifically.

**Comment by sjpadgett** [comment]
@tsimonq2 
suggested reading:
https://community.open-emr.org/t/questionnaire-assessment-feature-implementation-instructions/18870/1
https://community.open-emr.org/t/implement-fhir-questionnaires-in-portal-via-portal-templating/18833/1
Using LHC Form builder import the PHQ if want example of scoring

In builder use conditions for skip logic.

**Comment by sjpadgett** [comment]
@tsimonq2 
I'm curious if you have tried the questionnaire feature out?
