### ISSUE TITLE
Fix Portal Templates purifying removing images and style tag

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#6031]
### Describe the bug
Forum issue https://community.open-emr.org/t/adding-patient-portal-document-templates-to-openemr-patient-documents/12141/17?u=sjpadgett

HTMP Purifier prevents images by default so have yo add directive to allow.
Also signature drawing pen needs to be darker.
I think it should be blue ink and not black. thoughts anyone?

**Comment by sjpadgett** [comment]
new pen style. looks better to me. from pdf
![image](https://user-images.githubusercontent.com/1859985/208280187-d2d419de-2c9e-4d9a-8f2c-623e4ace3cbe.png)

**Comment by stephenwaite** [comment]
![southpark_cheering](https://user-images.githubusercontent.com/5618372/208432000-c2d419cd-5a9c-4e27-a44c-e0c84d225a10.gif)
