### ISSUE TITLE
Procedure Statistics Report - SQL Escaping error of additional_addresses

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#6048]
OpenEMR 7.0 Patch 2

Procedure Statistics Report: Reports > Procedures > Statistics

With "Screen" selected I get the following on multiple instances:

"There was an OpenEMR SQL Escaping ERROR of the following string additional_addresses"

"[php7:notice] [pid 1866] ERROR: OpenEMR SQL Escaping ERROR of the following string: additional_addresses, referer: .../interface/orders/procedure_stats.php"

With "Export File" selected, service_statistics_report.csv is generated that contains:
"<br /><span style='color:red;font-weight:bold;'>There was an OpenEMR SQL Escaping ERROR of the following string additional_addresses</span><br />"

**Comment by stephenwaite** [comment]
fixed in #6290
