### ISSUE TITLE
Dev Demos down

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#6049]
### Describe the bug
Gateway error!

**Comment by sjpadgett** [comment]
never mind up now although https://two.openemr.io/a/openemr/interface/login/login.php?site=default
is using v6.0.0 (4) for unknown reasons. That's one with PHP 8.2

**Comment by bradymiller** [comment]
@sjpadgett , just fixed and that demo is now doing what it should (PHP 8.2). (demo farm had a rough night last night, so several of the dev demos didn't make it)
