### ISSUE TITLE
Server for live demo prints "Bad gateway error"

### ISSUE THREAD

**Issue by djibe** [openemr/openemr#6062]
Hi,

In the documentation, when clicking for live demo <https://demo.openemr.io/openemr/index.php>, server responds with Bad gateway error.

Thanks

**Comment by stephenwaite** [comment]
hi @djibe , the demos are rebuilt nightly at 12 am Pacific Time and then are restored in about an hour.

**Comment by djibe** [comment]
Oups I'm sorry.
