### ISSUE TITLE
bug: Messages SMS Zone Combobox width

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#6070]
### Describe the bug

IN  /interface/main/messages.php

`<span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="true" tabindex="0" aria-disabled="false" aria-labelledby="select2-SMS_patient-container" aria-owns="select2-SMS_patient-results"><span class="select2-selection__rendered" id="select2-SMS_patient-container" role="textbox" aria-readonly="true"></span><span class="" role="presentation"><b role="presentation"></b></span></span>`

### To Reproduce

This SMSM Box is only visible to MedEx users so here is a screen shot of how it appears in the OpenEMR Docker:latest

![image](https://user-images.githubusercontent.com/60580695/210149390-5f3c231e-2896-471f-83b0-3553a6f1835d.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/60580695/210149296-5153bbcf-b18d-4c98-a1e0-760253bb2135.png)

need to add width:200px or something else to expand this "combobox" so it is visible.
I am not sure which class or css file can handle this but somewhere width:200px would work.

**Comment by robertdown** [comment]
Just a note, we can't hard code a width in like this, it will break responsiveness.
