### ISSUE TITLE
Ability to upload images in Portal

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#6127]
### Describe the problem

There are times a patient will want to share an image with their clinician.

### Describe the solution you'd like
Currently patients may drag an image into a secure message and then send making the image available to the recipient.
This is also available in chat.
I suppose though to be more permanent we need to allow upload to make document part of the patient chart.

I still think this is an iffy requirement. Need some clinicians to speak to their experiences with other EHR's.

**Comment by robertdown** [comment]
Upvote - hospital at home, telehealth, and other remote-work need mechanisms to upload to the portal.

**Comment by sjpadgett** [comment]
added in 7.0.2
