### ISSUE TITLE
bug: prior auth module fatal error on create table

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#6129]
### Describe the bug
![Screenshot from 2023-01-22 16-47-45](https://user-images.githubusercontent.com/5618372/213942154-33c811b9-1f9d-4a58-8047-b34183c9c13f.png)

**Comment by bradymiller** [comment]
looks like the dates are missing their data types
@juggernautsei , what are these supposed to be (ie. date, datetime, timestamp, etc.) ?

**Comment by juggernautsei** [comment]
They are the start and end dates for the authorizations. That table should be for tracking when authorizations have expired.
