### ISSUE TITLE
chore: Implement a CHANGELOG

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#6141]
It's time....

To out @openemr/admins we already have a Squash and Merge approach to accepting Pull Requests leading to essentially 1 commit to master per feature or fix. As we Squash and Merge I recommend we ensure the resulting commit begin with the one of the following prefixes found in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
* feat
* fix
* BREAKING CHANGE
* refactor
* chore

followed by a present tense describing the impact of the commit (Generally starts with a verb, i.e. "feat: allow configuration of login pages through configuration")

This will help us write the actual CHANGELOG.

Changelog structure will follow https://keepachangelog.com/en/1.0.0/

**Comment by stephenwaite** [comment]
we could update the issue templates to suggest a prefix
