### ISSUE TITLE
bug: Logo service throwing fatal error when images_static_absolute/logos/$type is not found

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#6147]
When the changes made for PR #6135 were brought it appears to break existing docker installations.  Supposedly the public folder is set in our docker-compose to be read/write but when I pulled down the latest codebase on an existing docker launched from our development-easy environment I'm getting the following fatal errors:

PHP Fatal error:  Uncaught Symfony\\Component\\Finder\\Exception\\DirectoryNotFoundException: The "/var/www/localhost/htdocs/openemr/public/images/logos/core/login/primary/" directory does not exist. in /var/www/localhost/htdocs/openemr/vendor/symfony/finder/Finder.php:592\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/src/Services/LogoService.php(100): Symfony\\Component\\Finder\\Finder->in()\n#1 /var/www/localhost/htdocs/openemr/src/Services/LogoService.php(75): OpenEMR\\Services\\LogoService->findLogo()\n#2 /var/www/localhost/htdocs/openemr/interface/login/login.php(47): OpenEMR\\Services\\LogoService->getLogo()\n#3 {main}\n  thrown in /var/www/localhost/htdocs/openemr/vendor/symfony/finder/Finder.php on line 592

I can see that the directory /var/www/localhost/htdocs/openemr/public/images/logos/core/login/primary/ does not exist in my docker image, but it does exist in the mapped underlying OS /home/ubuntu/openemr/public/images/logos/core/login/primary/

I haven't tested this on the production docker images but I think we should probably figure out what is going on here before the changes @robertdown made for the logos get pulled into a release patch.

@bradymiller If you have any ideas here on whether this is something oddly configured in my environment, or if this is something we need to fix in code or with the dockers that'd be great.

**Comment by ruthkonyn** [comment]
i had a similar problem logging in, having updated my code-  been talking to stephen waite in the forum  ( https://community.open-emr.org/t/help-failure-to-connect-to-server-after-git-pull-upstream-master/19901)  i tried this and that, and finally got up an instance of openemr but was unable to log in - it turns out my db has been wiped out in the process (not to worry i've got backup) . So i think the code  is in a bit of a dangerous state. !

**Comment by robertdown** [comment]
@adunsulag how did you go about upgrading the docker instance? I want to make sure I can replicate as I work on a fix.

Ideally, we should be able to manage the structure of `public` without issue. I can resolve the fatal error by moving the updated files to a pre-existing folder under public, but I'd like to have the `public` structure match the `sites` structure for the logo paths, if possible.

**Comment by adunsulag** [comment]
@robertdown I did a ```git pull origin master``` from outside the docker container in the root openemr directory.  I then ran the sql_upgrade.php script.  The code had last been updated from master in November of 2022. 

I took the docker image down without destroying the volumes, updated the docker images and using docker pull openemr/openemr and restarted.  I think that may have fixed the problem but updating the docker images appears to have blown away my snapshots so I'm in the process of doing a restore to see if the problem still persists.

**Comment by stephenwaite** [comment]
was able to reproduce this issue by checking out an older branch and firing up the dev-easy then checking out master and running the upgrade script

**Comment by adunsulag** [comment]
So looking more closely, the docker-compose.yml for the development demos treats the public folder as an independent volume just like the database volumes.
see here https://github.com/openemr/openemr/blob/c6d92d6e03b4e31187e3ff1bf1559dcc8cd4e693/docker/development-easy/docker-compose.yml#L25

The production docker's as far as I can see don't have this separate volume mapping so this is only going to impact developers which sucks but isn't as big as a catastrophe as I was worried about.

**Comment by adunsulag** [comment]
I suppose the question should be whether its appropriate to really throw a fatal error if the logo isn't there.  In reality it might be better to log the error and not fatally die.

**Comment by robertdown** [comment]
If this is a developer convenience issue, I feel rebuilding the docket from scratch is a reasonable solution.

I agree that not catching the Fatal Error is too alarming. I will fix this today.

Algo will look like:
- Logo in `sites`? Yes, render it. No? Move on
- logo in `public`? Yes, render it. No? Move on
- Log the lack of a logo file, return an empty string.

**Comment by bradymiller** [comment]
Crux of this issue is this line:
https://github.com/openemr/openemr/blob/master/docker/development-easy/docker-compose.yml#L25

ie. we are treating the entire public directory as something that can only be seen/modified within the docker. We need to make it more granular (ie. just the directories in public that need this, although then those directories will always exist during the install process in the docker which may throw things off, although not sure)

**Comment by bradymiller** [comment]
To better explain. If you move to a github branch (which is outside the docker) that has changes in public folder, the docker will not see those changes. This is one of the pitfalls of being able to test and code from the same place:

**Comment by sjpadgett** [comment]
I haven't been tracking this much but what about multisite, is it covered?

**Comment by sjpadgett** [comment]
> This is one of the pitfalls of being able to test and code from the same place.

Yes but convenience outweighs a little more effort on start.
