### ISSUE TITLE
xss security

### ISSUE THREAD

**Issue by Christynorl** [openemr/openemr#6152]
hi,@bradymiller 👋
I submitted an xss vulnerability about this project in the huntr community, and it has been fixed by you now. I hope you can submit the relevant commit(fix) in the huntr community and make that report public. The link is [link](https://huntr.dev/bounties/47d6fc2a-989a-44eb-9cb7-ab4f8bd44496/)https://huntr.dev/bounties/47d6fc2a-989a-44eb-9cb7-ab4f8bd44496/
You can also check this image first.![img](https://github.com/Christynorl/hunt_imgs/blob/main/20230201094637.png)
If possible, I hope you can assign for a cve number.Thanks a lot.

**Comment by Christynorl** [comment]
hi,@stephen waite,@bradymiller.Excuse me,I hope you can assign for a cve number for this vulnerability through the huntr community.It is very helpful for my work, thanks again

**Comment by bradymiller** [comment]
hi @Christynorl ,
Posted message on huntr.dev. In future better to directly email us via security@open-emr.org (rather than public posting) on any topics that are security related.
thanks for the report!
