### ISSUE TITLE
Patients with future DoB

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#616]
Is there any case why OpenEMR allows future DoB during add and change process?

**Comment by sunsetsystems** [comment]
Would certainly be good to do more date validation to avoid typos.

**Comment by robertdown** [comment]
Just thinking out loud, what about OB/GYN settings where a pregnancy is involved? Could there be any reason for the future date in this type of instance?

**Comment by mdsupport** [comment]
That would be "planned" parenthood world of OB!  
I am more inclined to think of this as a bug that does not catch typos.  The date widget probably has a setting to prevent selection of future dates.

**Comment by bradymiller** [comment]
Matrix added a nice validator in the layouts engine(also being used in other non layout forms) which could add support for 2 options(if these are not already there):
1. validate date format
2. only allow current or prior dates

**Comment by mdsupport** [comment]
Not sure if datetimepicker also validates manual input but documentation shows this **minDate and maxDate Example** - rather strange notation that needs further exploring
```
jQuery('#datetimepicker7').datetimepicker({
 timepicker:false,
 formatDate:'Y/m/d',
 minDate:'-1970/01/02',//yesterday is minimum date(for today use 0 or -1970/01/01)
 maxDate:'+1970/01/02'//tomorrow is maximum date calendar
}); 
```

**Comment by robertdown** [comment]
Just a reminder, validation needs to happen on both client and server side.
