### ISSUE TITLE
feat: Allow portal logo to be managed like core login page

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#6162]

**Comment by sjpadgett** [comment]
nice thanks

**Comment by robertdown** [comment]
Resolved with #6163 - follows the same structure as the login page, just drop your logo in `/sites/<site id>/images/logos/portal/login/primary` and you're all set!

Leveraging the LogoService so upgrading users will gracefully fall back to the `public/images` folder with the default logo.
