### ISSUE TITLE
Possible bugs in source code (CWE-480)

### ISSUE THREAD

**Issue by AppChecker** [openemr/openemr#619]
Hello!

We've checked your code with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php) and found possible bugs:

1)
https://github.com/openemr/openemr/blob/ee0945a30dbb17ceee82b9b553d7dcb177710ca8/interface/orders/orders_results.php#L613

```
    echo "  <td>" .
      "<input type='text' size='16' name='form_result_text[$lino]'" .
      " class='celltext' value='" . attr($result_text) . "' />";
      "</td>\n";
```
`</td>\n` doesn't refer to echo

2)
https://github.com/openemr/openemr/blob/ee0945a30dbb17ceee82b9b553d7dcb177710ca8/interface/batchcom/settingsnotification.php#L89

```
<INPUT TYPE="password" NAME="SMS_gateway_username" size="40" value="<?php $SMS_gateway_username?>">
...
<INPUT TYPE="password" NAME="SMS_gateway_password" size="40" value="<?php $SMS_gateway_password?>">
...
<INPUT TYPE="text" NAME="SMS_gateway_apikey" size="40" value="<?php $SMS_gateway_apikey?>">
```
$SMS_gateway_username, $SMS_gateway_password and $SMS_gateway_apikey are not displayed

3)
https://github.com/openemr/openemr/blob/ee0945a30dbb17ceee82b9b553d7dcb177710ca8/interface/main/calendar/find_patient.php#L205

```
<body class="body_bottom" <?php $body_code;?>>
```
$body_code  is not displayed

Possible defects were found by Echelon Team with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by MatthewVita** [comment]
@robertdown, 2 and 3 are actual issues, right?

If you agree, I will create a PR

**Comment by bradymiller** [comment]
agreed :)

**Comment by robertdown** [comment]
Yep, I actually think all 3 are bugs. Definitely need to be fixed. I can do it if need be, easy enough, just let me know.

**Comment by MatthewVita** [comment]
Thanks @bradymiller and @robertdown. I'd actually like to tackle this :) Will do it tomorrow

**Comment by MatthewVita** [comment]
Okay. So I've been working on bug number 1. I am also using it as an excuse to become more familiar with the procedure/lab functionality of the system. In doing so, I updated http://open-emr.org/wiki/index.php/Procedure_configuration_%26_order_process to point at more complete documentation resources from v4.x.x and @juggernautsei's very helpful YouTube tutorials.

With that said, I have 2 questions. One is relevant to being able to reproduce the bug and the other is for my learning:

1) It looks like I need to a lab to show up in the "Procedures > Patient Results" to reproduce the issue. Is there an easy way to simulate an inbound request of procedure results from an LIS?

2) https://community.open-emr.org/t/lab-requisition-form/8367

Thanks,
Matthew

**Comment by MatthewVita** [comment]
...I may have not made too much progress with this ticket today, but I at least tackle this bug that I found while looking at this ticket: https://github.com/openemr/openemr/pull/627

woot!

**Comment by bradymiller** [comment]
@stephenwaite (aka live chat master) can also be helpful in bringing in labs via hl7 (we even recently made changes in the online demo to make showing this feature easier).

**Comment by stephenwaite** [comment]
here's some test files that should do the trick though the procedures->electronic reports interface
you have to setup a procedure -> provider with the applicable settings to grab the files and run them through rod's slick system

[hl7_test.zip](https://github.com/openemr/openemr/files/910011/hl7_test.zip)

**Comment by MatthewVita** [comment]
Thanks @stephenwaite! I will test this out and report back soon.

**Comment by MatthewVita** [comment]
Hi @stephenwaite. As I said before "[...] I am also using it as an excuse to become more familiar with the procedure/lab functionality of the system."

With this said, I can't figure out how to set up the provider to "listen" for inbound HL7 messages. Is there wiki documentation on this?

**Comment by stephenwaite** [comment]
hi Matthew, probably not.  You can choose results only and then filesystem and stash the hl7 files in that folder.

**Comment by MatthewVita** [comment]
@stephenwaite, sorry I'm not really following. Is there a folder that will process HL7 files when dropped in?

**Comment by stephenwaite** [comment]
yes, it's configurable in procedure->providers and then activated when go to procedures->electronic reports

**Comment by stephenwaite** [comment]
ok, brought in the above samples into v5.0.0(1) after the above and then clicking on the date to sign the results (this has to be enabled through the acl even for the administrator)  

plan to put together a wiki on this results only interface soon

**Comment by bobinson** [comment]
#652  is dealing on similar issues.

**Comment by tywrenn** [comment]
@bradymiller This looks like it can be closed
