### ISSUE TITLE
max_input_time

### ISSUE THREAD

**Issue by sunsetsystems** [openemr/openemr#622]
I had an odd problem with backups failing without any error being logged. It turned out that setting max_input_time to -1 in php.ini fixed this. Makes no sense but there it is. Happened with both Debian Jessie and Mint 18.

So I'm thinking that in our setup instructions we should recommend -1 for this instead of "at least 90". This will cause it to default to max_execution_time which is better documented, and which the patch and upgrade scripts already set to 0 (backup.php should do this as well).

**Comment by bradymiller** [comment]
Agreed. Any other settings that you think should be "modernized"?
http://www.open-emr.org/wiki/index.php/FAQ#What_are_the_correct_PHP_settings_.28can_be_found_in_the_php.ini_file.29.3F

**Comment by sunsetsystems** [comment]
I would say 512M or 1024M for memory_limit, depending on the amount of RAM installed in the server. Some reports can eat a lot of memory.

**Comment by sunsetsystems** [comment]
Also with a lot of users, max_connections will need to be more. I don't have a specific recommendation for that, it's a matter of monitoring the log.

**Comment by bradymiller** [comment]
Just updated the wiki and these settings will also be in the future 5.0.1 ubuntu/xampp packages (except for max_connections which is a mysql/mariadb thing and will make sense to make a optimize sql database wiki page that includes this issue along with the other innodb issues).
