### ISSUE TITLE
Portal email message missing portal site address 

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#6227]
Looks like when we refactored the create_portallogin.php file to twig we left out the portal_onsite_two_enable global variable which is what triggered the portal address to show.  Kinda crazy that its been in the system that long, but we'll get this fixed.

**Comment by sjpadgett** [comment]
@adunsulag 
could you also fix dupl email check for registering patient. There is every likelihood dupl emails can exist in database.

portal/account/account.lib.php around L-119
```
if (!empty($sql['pid'])) {
        $templateData = ['email' => $email];
        (new SystemLogger())->debug("verifyEmail function: the email is already in use, so can not use");
        $emailPrepSend = true;
    } else {
```

**Comment by adunsulag** [comment]
@bradymiller can you let us know what you were fixing in this commit here: 14444c341bea183b0ac3283a60392d2ddd2d887a where you put in the code to prevent the duplicate email.

Jerry and I were talking about this, and the code to preventing the duplicate email on registration breaks the use where a guardian registers an account with a duplicate email address (different account) for their children.   Jerry had designed all of this so that multiple email addresses could be used and the account name was the unique piece here.  

I'd like to understand the security fix you were addressing here so we can make sure to keep the fix while also addressing the use case Jerry brings up.
