### ISSUE TITLE
Printing support

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#623]
Throughout the codebase printable pages use individual/script specific style elements.  This problem is more acute with patient reports where different forms are pulled in - each with its own layouts.  Since many of these reports go out to other practices / companies, it is important to present a professional appearance - browsers are terrible when rendering screen output.

It would be good if a standard template can be established.  Typically practices look for practice details on top and consistent font families and sizes.

Do others have similar concerns?

**Comment by stephenwaite** [comment]
sure, it'd be nice to emulate what's being done in Globals->billing->statement appearance

**Comment by bradymiller** [comment]
Agreed that a standard template should be established for printing.
