### ISSUE TITLE
Error Creating New Encounter if "Facility" is hidden

### ISSUE THREAD

**Issue by dcvidigal** [openemr/openemr#6230]
If you try to create/save a new encounter and we have the "Facility" field hidden, we'll get a sql Insert error, saying that the facility_id can't be null.
I've tested it in the online demo on 7.0.0 (2) version.

 To Reproduce this behavior  we simply have to:
         1. Go to Global Settings -> Encounter Form
         2. Set "Show Facility option on Encounters" to "Hide on New and Edit Form" and Save
         3. Select a Patient
         4. New Encounter and fill the fields
         5. Save

![1 - Global Settings](https://user-images.githubusercontent.com/7562412/220684832-bb74f2dc-5a1a-4aec-8849-d4f35eb65b39.png)
![2 - New Encounter](https://user-images.githubusercontent.com/7562412/220684836-1eb64a76-ce88-47ed-ba01-b5374d813572.png)
![3 - Error saving](https://user-images.githubusercontent.com/7562412/220684838-41161276-034f-4778-9e3f-c41d3f6f72db.png)

What we should expected is a successful creation, but instead the sql error will appear.

I check that the value of the field is always with a default value, so this shouldn't happen. 
But has I analyzed it the problem is that if there are fields (or div parents) hidden through 'd-none' class those fields on submit will not passthrough, that's because the 'd-none' class sets the 'display' property to 'none'. 

I think we can use the "visibility:hidden" property instead, but I didn't tested it out.

### Client configuration
- Browser: Edge
- OpenEMR version: 7.0.0(2)
It was on the online demo

**Comment by dcvidigal** [comment]
I tested, we can use the 'd-none', but it has to be on the input, and not on the parent div.

**Comment by robertdown** [comment]
Confirmed on master branch

**Comment by robertdown** [comment]
> I tested, we can use the 'd-none', but it has to be on the input, and not on the parent div.

This may have the effect of keeping the Facility ID but it will break the overall grid as the parent `div.col-sm` must be hidden to keep the fluid grid working. Approach to fixing this a javascript conditional check to see if the facility ID is visible and if not, injecting a hidden form element with the current facility.

**Comment by mdsupport** [comment]
Instead of class d-none use input type=hidden.
