### ISSUE TITLE
POST /api/patient/{pid}/appointment standard api endpoint throws an error

### ISSUE THREAD

**Issue by dirkhekhuisascendtek** [openemr/openemr#6238]
### Describe the bug

When the POST /api/patient/{pid}/appointment standard api endpoint is called it returns the following error:
<p>
	<font color='red'>ERROR:</font> insert failed: INSERT INTO openemr_postcalendar_events SET uuid=? pc_pid=?,
	pc_catid=?, pc_title=?, pc_duration=?, pc_hometext=?, pc_eventDate=?, pc_apptstatus=?, pc_startTime=?, pc_endTime=?,
	pc_facility=?, pc_billing_location=?, pc_informant=1, pc_eventstatus=1, pc_sharing=1, pc_aid=?
</p>
<p>Error: <font color='red'>You have an error in your SQL syntax; check the manual that corresponds to your MariaDB
		server version for the right syntax to use near 'pc_pid='1', pc_catid='5', pc_title='Office Visit',
		pc_duration='9...' at line 1</font>
</p>
/var/www/localhost/htdocs/openemr/src/Services/AppointmentService.php at 297:sqlInsert<br />/var/www/localhost/htdocs/openemr/src/RestControllers/AppointmentRestController.php at 78:insert(1,Array)<br />/var/www/localhost/htdocs/openemr/_rest_routes.inc.php at 5161:post(1,Array)<br />/var/www/localhost/htdocs/openemr/src/Common/Http/HttpRestRouteHandler.php at 91:{closure}<br/>
<br/>

Looking at the source it looks like there is a comma missing after the question mark on the uuid param in the insert function on line 277 of AppointmentService.php.
<img width="682" alt="image" src="https://user-images.githubusercontent.com/93535234/221639713-f97e33e2-a46c-4ed3-bfb7-5c9b37fde3c5.png">

### To Reproduce
Call the POST /api/patient/{pid}/appointment standard api endpoint with a valid pid and the following body contents:

`{
  "pc_catid": "5",
  "pc_title": "Office Visit",
  "pc_duration": "900",
  "pc_hometext": "Test",
  "pc_apptstatus": "-",
  "pc_eventDate": "2018-10-19",
  "pc_startTime": "09:00",
  "pc_facility": "9",
  "pc_billing_location": "10",
  "pc_aid": "1"
}`

### Expected behavior

Creates a new appointment for the patient.

### Client configuration

- Browser: Postman 10.8.8
- OpenEMR version: 7.0.0.2
- Operating system: openemr/openemr:latest docker image

**Comment by stephenwaite** [comment]
thanks @dirkhekhuisascendtek , would you like to submit a pull request for the fix?

**Comment by dirkhekhuisascendtek** [comment]
Here is the pull request: https://github.com/openemr/openemr/pull/6239
