### ISSUE TITLE
Standard API /api/allergy and /api/allergy/{auuid} routes returning 500 error

### ISSUE THREAD

**Issue by dirkhekhuisascendtek** [openemr/openemr#6241]
### Describe the bug
When calling the /api/allergy and /api/allergy/{auuid} endpoints in Postman it returns a 500 internal server error.

### To Reproduce
<img width="970" alt="image" src="https://user-images.githubusercontent.com/93535234/221924408-f95ae634-0283-420f-b7a1-2174c723c832.png">
<img width="970" alt="image" src="https://user-images.githubusercontent.com/93535234/221926073-ebd8ca5f-9519-45d9-89cb-4dac4cb0c021.png">

* Call the /api/allergy endpoint with no get params or body
* Call the /api/allergy/{auuid} endpoint with an allergy auuid in the path

### Expected behavior
It returns a 200 status code and returns the allergy data.

### Client configuration
- Browser: Postman 10.8.8
- OpenEMR version: 7.0.0.2
- Operating system: Docker openemr/openemr:latest

**Comment by stephenwaite** [comment]
maybe this is better:

![Screenshot from 2023-03-01 15-06-41](https://user-images.githubusercontent.com/5618372/222253900-4dd49972-7e0b-4f67-bfd9-2f3f53b26913.png)
