### ISSUE TITLE
Test PHP 8.2 - Apache - MariaDB 10.6 Broken

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#6249]
The test for PHP 8.2 on Apache with MariaDB 10.6 is broken due to an upstream issue with the bcrypt test. This is causing a CI failure on every push to a PR.

**Comment by bradymiller** [comment]
At this time, will ignore the unit testing, so the rest of the ci testing in this environment still runs. Will intermittently retry the unit testing in future.
