### ISSUE TITLE
feat: Lock down php script access in module directories to ONLY enabled modules

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#6254]
To decrease the attack surface for OpenEMR installations we want to restrict script access to module files to only enabled modules.  
To resolve this issue we should look at doing the following:

- Core module script files should ALL include globals.php, most do this anyway since the session security check is handled here and access to all of the global settings.
- Add a security check in globals.php that determines if the currently called script file is inside the modules directory
- If the script is in a modules directory, check if the module is enabled
- If the module is not enabled, return a 401 response code to the caller and log the error.

**Comment by bradymiller** [comment]
very nice plan!

**Comment by stephenwaite** [comment]
![freedom-roadtrip](https://user-images.githubusercontent.com/5618372/222803526-9e2d0820-f87a-4c65-8b8c-bf11a8383852.gif)
