### ISSUE TITLE
Bunch of PHP 8.2 warnings at Admin->Clinic->Calendar->Categories

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#6281]
Bunch of PHP 8.2 warnings at Admin->Clinic->Calendar->Categories

Do not worry about the deprecated messages. I have fixed those in my ongoing PHP 8.2 sweep :)

**Comment by stephenwaite** [comment]
do you think we need to make a smarty plugin for legacy calendar that would null coalesce?

**Comment by stephenwaite** [comment]
found the main issue at https://github.com/openemr/openemr/blob/master/interface/main/calendar/modules/PostCalendar/pntemplates/default/admin/submit_category.html#L102-L106

`$cat` isn't defined until a lower foreach
