### ISSUE TITLE
Vitals form metric conversion fails for non-english languages

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#6292]
There is a bug in the vitals form for non-english languages when calculating the conversion values.  If a language translation for the unit exists, the translated unit used in the metric conversion does not match the english value in the codebase and the conversion fails.  

The code should have a separate value for the unit and the translated unit name to fix this problem.

**Comment by adunsulag** [comment]
I think this is a blocking issue for our 7.1.0 release as it breaks the vitals form for any non-english use.

**Comment by bradymiller** [comment]
agreed on blocking issue :)
