### ISSUE TITLE
Remove Password Composition Requirements

### ISSUE THREAD

**Issue by henrycrain** [openemr/openemr#6299]
### Describe the problem

Currently, passwords are required to have a number, lowercase letter, uppercase letter, and special character. However, many security standards, such as [NIST](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf) (section 5.1.1.1) and [ASVS](https://raw.githubusercontent.com/OWASP/ASVS/v4.0.3/4.0/OWASP%20Application%20Security%20Verification%20Standard%204.0.3-en.pdf) (standard 2.1.9) recommend against password composition requirements because they do not significantly increase the strength of passwords.

### Describe the solution you'd like

Do not require passwords to contain numbers, special characters, etc.

**Comment by bradymiller** [comment]
hi @henrycrain ,
These requirements can be turned off via the setting at:
Security->Globals/Config->Security->Require Strong Passwords

**Comment by henrycrain** [comment]
Ah, thanks for pointing that out, makes sense to let admins decide their own security settings.
