### ISSUE TITLE
clinical_rules_log table

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#6309]
Can anyone explain the design requirement(s) behind keeping the clinical_rules_log records in perpetuity? We have instances where it is about 20% of database size (and growing). It also seems to take the view that results of clinical rules calculations are different for each user. So it creates 10s of records related to a single 15 minute encounter.

**Comment by bradymiller** [comment]
This was forced during MU2 certification of CDR certification item. Had to log new reminders (the code basically logs only reminders that are new) that can be viewed in the Report->Clinic->Alerts Log.
Could potentially make that function/report a global that can turn off (note only used in several placed in codebase and would likely also get a performance bump if not looking for and recording new reminders)

**Comment by mdsupport** [comment]
My bad... Need to make a note to set `$GLOBALS['enable_alert_log']` off as default.

Thx @bradymiller.
