### ISSUE TITLE
Open in New Window opens in new tab instead of new window

### ISSUE THREAD

**Issue by stevenpjohnso** [openemr/openemr#6314]
### Describe the bug

The open in new window checkbox opens patient information in a new tab. Not sure if both options should be shown as a checkbox instead or dropdown menu with both choices should be in user settings. I like it in new tab format but the wording should be honest.

### To Reproduce

1. Go to Patent Finder tab.
2. Scroll down to bottom.
3. Click the 'Open in New Window' checkbox.
4. Click on a patient name.

### Expected behavior

The patient info opens in a new browser window. 

### Client configuration

- Browser: Microsoft Edge: Version 111.0.1661.54 (Official build) (64-bit) & Brave: Version 1.49.132 Chromium: 111.0.5563.147 (Official Build) (64-bit)
- OpenEMR version: 7.0.0 (2)
- Operating system: Windows 10 Pro 22H2

**Comment by stephenwaite** [comment]
thanks @stevenpjohnso , we should prob fix the verbiage.

@bradymiller, not seeing `$popup` get set anymore, is the above comment still valid?
https://github.com/openemr/openemr/blob/master/interface/main/finder/dynamic_finder_ajax.php#L31

**Comment by sjpadgett** [comment]
@bradymiller @stephenwaite 
How do you guys feel about this? The way it works now it is up to the user agent how to handle i.e generally browsers open in tab these days.

I can force a new window and I think this is preferable from user POV.

**Comment by sjpadgett** [comment]
never mind not so easy.
