### ISSUE TITLE
Navigation issue: Patient button not working as expected

### ISSUE THREAD

**Issue by spj98** [openemr/openemr#6317]
### Describe the bug

The "Patient" button in the navigation menu does not navigate to the patient finder. Instead, it goes to a search or add patient page, which does not look clean. Additionally, the "Patient > Dashboard" option is greyed out and it is unclear whether this is intended behavior.

### To Reproduce
![image](https://user-images.githubusercontent.com/38847165/228639844-2b7bb7e1-e22d-47ea-937a-c9ed9752a78a.png)

1. Log in to OpenEMR.
2. Navigate to menu near the top part of the screen.
3. Click on the "Patient" button.

### Expected behavior

Clicking on the "Patient" button should navigate to the patient finder. The "Patient > Dashboard" option should be clickable and not greyed out. Generally, the patient menu/new patient page should have a cleaner design and possibly include an option for advanced search instead of the hybrid search/new patient form imo. Thanks!

### Client configuration

- Browser: Microsoft Edge: Version 111.0.1661.54 (Official build) (64-bit) & Brave: Version 1.49.132 Chromium: 111.0.5563.147 (Official Build) (64-bit)
- OpenEMR version: 7.0.0 (2)
- Operating system: Windows 10 Pro 22H2

<!-- Love openemr? Please consider supporting our collective:
👉  https://opencollective.com/openemr/donate --

**Comment by stephenwaite** [comment]
hi @stevenpjohnso , this was discussed on Saturday's call so look for some improvments in this area soon, thanks for noticing.

ps once you select a person, dashboard won't be greyed out.
