### ISSUE TITLE
Forms Created with XML Formgen donot have the new datetime pickup widget

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#634]
Hi 

I need to bring to your notice that the forms created with XML formgen donot have the new date time picker. It still shows the old calendar widget. I would request developers here to fix this to maintain unity in the project. Functionality is not lost, but aesthetics are.

Thanks and regards
Arnab

**Comment by bradymiller** [comment]
Hi @arnabnaha ,
I am super glad you brought this up. I was going to make this change in the codebase soon and was hoping you could test it.
-brady

**Comment by arnabnaha** [comment]
Hi @bradymiller 
Sure I will test it Brady.

**Comment by bradymiller** [comment]
@arnabnaha ,
I just committed the code to the codebase that should make the new datepicker work in xmlformgen. Let me know how the testing goes.
-brady

**Comment by arnabnaha** [comment]
Hi @bradymiller 
It works fine Brady. Thanks a lot
