### ISSUE TITLE
tracking standard header code walk through

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#635]
Project to standardize headers of assets and bring in bootstrap.

More details can be found on this PR:
https://github.com/openemr/openemr/pull/587

Some more work from above commit on the patient_list.php report:
https://github.com/openemr/openemr/commit/d606eb8cdecea6963ea870635ee3831953ff415d

Note added fontawesome ti it here:
https://github.com/openemr/openemr/commit/97b2670f15dcb438c9692dea05df2a69bf01d780

And here is example using it in procedure order form:
https://github.com/openemr/openemr/commit/434e449893e126ce9e9aef8a1f96775ff4c42472

Planning to walk through the codebase with this template (have completed the reports and now working on others)

**Comment by bradymiller** [comment]
Reports->Visits->Superbill will take extra effort, so will skip this for now.

**Comment by bradymiller** [comment]
Reports->Visits->Eligibility Response was skipped since only an upload element there and unable to test.

**Comment by bradymiller** [comment]
wooohooo, @robertdown added a full bootstrap conversion example to the following PR:
https://github.com/openemr/openemr/pull/718

**Comment by bradymiller** [comment]
Reports->Procedures->Statistics was skipped since will require more extensive work..

**Comment by robertogagliotta** [comment]
Hi Brady, Robert
I would like to do the bootstrap update And unit testing in a program. Can you point me to one of them?

**Comment by robertdown** [comment]
Hi @robertogagliotta - I'll write up some documentation later tonight so you can get started. Looking forward to your help!

**Comment by bradymiller** [comment]
@robertogagliotta , And I'll look through openemr this evening to find a good script to start with. -brady

**Comment by bradymiller** [comment]
Hi @robertogagliotta ,

2 good simple scripts to learn bootstrap suppoer are on:
Popups->Export
(custom/export_xml.php starting at line 253)
Popups->Import
(custom/import_xml.php starting at line 191)
(not need to have a patient selected to open these)

See the SOAP conversion to get an idea of what we are doing in conversion (note this was in a smarty code):
https://github.com/openemr/openemr/pull/741/files

I do the following steps when convert:

1. bring in the standard asset header template:
``````
require "{$GLOBALS['srcdir']}/templates/standard_header_template.php";
``````
(this is a nifty script that brings in all the standard assets including the css_header and sets up bootstrap; so can remove the include of the css_header in these scripts)

2. deconstruct the html styling element. In this case, remove the 'p' and 'center' html tags.

3. then use bootstrap classes and div (basically try to mimick the class/div structure in the above SOAP form link); and when you are doing this google search the bootstrap classes and divs to begin to get an idea of what it all means(this was very helpful for me to begin to learn this stuff).

4. Bring in the new button style (this is really neat and I'll point out how to do this on the first review; note can try to mimick what is done in SOAP here also)

5. convert script to new security model (this will just be a couple line changes, which I will point out on the review)

I warn you. Converting to bootstrap is addictive because it's super cool to watch a gui go from legacy to modern and responsive (responsive meaning that as the web browser gets smaller, the positioning of the elements respond; as an example, see what happens on both the SOAP form and the Encounter->procedure order form when you wake the browser width smaller).

There is a bit of a learning curve and I still am trying to climb it also (and this is why we have @robertdown :) )

-brady

**Comment by robertogagliotta** [comment]
First review on
https://github.com/robertogagliotta/openemr/commit/6989b55aea7674524d39de8a133b812a41b986cb#diff-8b9035807842a4e4dbe009f3f1478127

@robertdown

**Comment by bradymiller** [comment]
Can close this since this is being taken care of in the bootstrap update PR.
