### ISSUE TITLE
bug: pid and pubpid reversed in patient search popup

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#6351]
### Describe the bug

[via forum](https://community.open-emr.org/t/preparing-for-7-0-1-release/20135/4?u=stephenwaite) from @luisuriarte

**Comment by stephenwaite** [comment]
hi @luisuriarte, thanks to @sjpadgett pointing out that `ID` is for `pubpid` here

**Comment by stephenwaite** [comment]
it's a tad confusing :)

**Comment by luisuriarte** [comment]
Maybe the tag can be replaced by PUBPID

**Comment by sjpadgett** [comment]
enlarge the dialog width
