### ISSUE TITLE
Logo doesn't display windows

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#6355]
### Describe the bug
First I don't understand an image src of `C:\xampp\htdocs\openemr-master\sites\default\images\logos\core\menu\primary\logo.png?t=1675349480` Why the timestamp?
Also the path included in the call to logo service causes double slashes in path. Windows doesn't understand this. Though shouldn't break because of using realpath.
```
$menuLogo = $logoService->getLogo('core/menu/primary/'); should be $menuLogo = $logoService->getLogo('core/menu/primary');
```
None of the logos show in core or portal. I'm using the png version logo but that shouldn't matter.

Someone else on windows can track this down. This happened after pulling master and doing rebuild and sql upgrade.

**Comment by bradymiller** [comment]
i think the t thing is for cache busting

**Comment by bradymiller** [comment]
@robertdown , looks like logos are not working in windows per this thread: https://community.open-emr.org/t/preparing-for-7-0-1-release/20135/30

**Comment by sjpadgett** [comment]
The method to convert a file path to a web path doesn't take into consideration the difference in path separators i.e windows `\` and unix style `/` str_replace won't match.
```
private function convertToWebPath(string $path): string
    {
        $paths = [
            $GLOBALS['OE_SITE_DIR'] => $GLOBALS['OE_SITE_WEBROOT'],
            $GLOBALS['images_static_absolute'] => $GLOBALS['images_static_relative'],
        ];
        return str_replace(array_keys($paths), array_values($paths), $path);
    }
```
