### ISSUE TITLE
Product Registration Issue

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#636]
Hi..

The product registration window opens asking for an email address to register. Whenever I give my email address and press submit, it says Server error:Please try again. Is the registration system not ready yet??

Thanks and regards
Arnab

**Comment by bradymiller** [comment]
Hi @arnabnaha ,
I think this may be a windows issue since somebody else using windows has reported this. Any errors in the php error log?
-brady

**Comment by arnabnaha** [comment]
Hi @bradymiller 

I checked the error log. No Help. Nothing is there which points to registration issue

**Comment by bradymiller** [comment]
Hi @arnabnaha ,
The next thing to check is the js log in the browser (Firefox->Developer->Web Console).

**Comment by arnabnaha** [comment]
Hi @bradymiller 
It shows a 500 internal server error. I dont know whether I was able to access the JS Log or not..it would be helpful if you can tell me how to get the js log. I was able to enter the web console.

**Comment by arnabnaha** [comment]
![error_log_js](https://cloud.githubusercontent.com/assets/1074948/24899525/40433c52-1ebe-11e7-8699-5943323b38e0.jpg)

**Comment by bradymiller** [comment]
@MatthewVita , any thoughts on this? Is it possible that windows may block outward connection?

**Comment by MatthewVita** [comment]
@arnabnaha Hello. This feature is ready (have almost 200 registered users!). As Brady mentioned, there was a similar issue posted by a Windows user. Before I start to look at Windows, I must ask if you have a firewall (this could block an outbound request to AWS)?

@bradymiller The AWS account user/pass in my Keepass isn't getting me in. Can you log into AWS and see if matthewvita48@gmail.com is a valid user entry? If so, I will reset the password (unless you have to do that through the admin console). I would like to check the server logs to see if there was a request sent to the server per Dr. Arnab's screenshot time. My guess is that the request didn't make it to the server, but I need to prove that!

**Comment by bradymiller** [comment]
@MatthewVita , Will send you a message on rocketchat regarding aws credentials.

**Comment by arnabnaha** [comment]
I have a kaspersky antivirus internet protection present. I have switched
it off and tried the product registration. It gave me the same error.

**Comment by sjpadgett** [comment]
@arnabnaha Have you per chance cleared your browser cookies and cache? I would even delete cookies on server as well then test from there.

**Comment by MatthewVita** [comment]
@arnabnaha do you have a firewall or antivirus present on your network and not your local computer?

**Comment by arnabnaha** [comment]
@MatthewVita I donot have a firewall on my network. The antivirus is actually on my server computer. I have shut it down and then tried..but no use

**Comment by arnabnaha** [comment]
@sjpadgett I have cleared my browser cookies and tried.. No help

**Comment by sjpadgett** [comment]
@arnabnaha My experience with 500 server errors are generally malformed links or exceptions that are handled by the controller and don't peculate to browser or error doesn't gets logged to php error log. A link error may show up in the Apache access log and easiest way to solve other would be to set break point in the controller error handler and see what exception is being thrown.
This has happened to me when I registered on windows after an upgrade but I simply can't remember the details. I may have re-saved globals as that was an issue for me.

**Comment by MatthewVita** [comment]
Hi @arnabnaha, I have some bad news. I just downloaded all logs from AWS for the product registration service server and searched for `arnab` (is that in your email?) and it wasn't found. Looks like the request isn't making it outside of your network :(

**Comment by MatthewVita** [comment]
(there are logs for each email address attempting to register)

**Comment by bradymiller** [comment]
Isn't it odd for a network to block this though, since it's using standard https port?

**Comment by MatthewVita** [comment]
I'm wondering if it has to do with PHP curl. @arnabnaha how do you install OpenEMR, through the official XAMPP package?

**Comment by bradymiller** [comment]
Good call: http://stackoverflow.com/questions/3020049/how-to-enable-curl-in-xampp
If that is the issue, then will fix that when do the next build (plan to do this soon to address the super slow innodb settings).

**Comment by MatthewVita** [comment]
Hmm, we have to prove it though. I wonder why this wouldn't be a default with XAMPP...

**Comment by bradymiller** [comment]
Agreed especially since that stackoverflow link is really old. Will hold off on the XAMPP rebuild, though, until this is sorted out(in case there is a fix).

**Comment by MatthewVita** [comment]
@arnabnaha with all of this said, can you follow this post at least up to the point where you see if `extension=php_curl.dll` has a `;` in front of it? http://stackoverflow.com/a/9683555/1525534

**Comment by sjpadgett** [comment]
If cURL was issue would it not throw up a 404? Also, I'd expect a php error.

**Comment by arnabnaha** [comment]
Hii..
I have already enabled curl since inception as xmlformgen required it. My
php.ini has curl enabled.

Thanks and regard
Arnab

On 14-Apr-2017 9:13 AM, "JerryP" <notifications@github.com> wrote:

If cURL was issue would it not throw up a 404? Also, I'd expect a php error.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openemr/openemr/issues/636#issuecomment-294078821>, or mute
the thread

**Comment by bradymiller** [comment]
Sounds like back to @sjpadgett above thoughts on the 500 error. @MatthewVita, would blocking of the connection by local network/firewall be able to produce that 500 error?

**Comment by sjpadgett** [comment]
One nasty problem with windows is if you download zip or files, windows marks the files as blocked. With zip file, if you right click, then in properties you can unblock the zip before unzipping. You may have a blocked permission script somewhere.

**Comment by arnabnaha** [comment]
How to find out which file is blocked? Have never checked on that..never
had any problem like that.

Thanks and regards
Arnab

**Comment by sjpadgett** [comment]
Right click the file, select properties and see if unblock appears in bottom right corner of dialog. Some files in question are in the interface/product_registration and openemr/services folders.

**Comment by arnabnaha** [comment]
Hii..
Checked it..there is no such option. Even gave full permissions to all the
files in those folder for all users. Still.no luck..it shows server error
on trying to register

Thanks
Arnab

**Comment by sjpadgett** [comment]
And I guess you checked all logs like apache access and error logs. These darn 500/server errors are hard to track as it is such a general error. Do you use a debugger?

**Comment by arnabnaha** [comment]
Hii JerryP

I have checked all logs...no entry anywhere. I donot use a debugger. Do i
need to install one?? Then please tell me which one to install?

Thanks
Arnab

**Comment by sjpadgett** [comment]
No sir, I don't want to put you through that. Give me a minute to look at code.

**Comment by sjpadgett** [comment]
I'm guessing you can move on to OpenEMR without registering

**Comment by arnabnaha** [comment]
Sure Jerry..i can use openemr without registering..but as i was testing
it..so found out its not working...might be a bug..thats why posted it in
github

**Comment by sjpadgett** [comment]
Sorry, I did not realize there is another bug besides registration. I'll look for it.

**Comment by sjpadgett** [comment]
I may be able to help with your pdf issue later but for now I can think of only two things to do: 1) I could patch the controller with some die traps to see if we see an exception or if we even make it to controller or 2) get @MatthewVita to null my registration and I will try to recreate. Which version of OpenEMR are you testing? If from master branch when?

**Comment by arnabnaha** [comment]
I am using the recent dev tip..5.0.1..

**Comment by sjpadgett** [comment]
Since doing the changes to cookie handling I had several 500 errors with my portal I had to address. I found, even if cookies were deleted from browser cache, if I did not delete old cookies on server I still had issue. Just for my peace of mind, can you go to xampp/tmp and delete all cookies then maybe use private browser session and try again?

**Comment by arnabnaha** [comment]
Hi JerryP
No luck sir, deleted everything in xampp/tmp folder. fired firefox and used
localhost/openemr...registration popup appeared..entered my email:
superarnab@gmail.com but it gives same error - Server error: try again


*          Dr. Arnab Naha*
*          MBBS (Cal)*

**Comment by sjpadgett** [comment]
Okay, I guess I'll send you a patched script to see if I can trap the error. Just be sure to back up file I'll over write when I do. Give me a minute or two.

**Comment by sjpadgett** [comment]
This will go into interface/product_registration folder. I add die with message to exception handler.
[product_registration_controller.zip](https://github.com/openemr/openemr/files/922037/product_registration_controller.zip)

 I notice that this code sets the default status for the header to 500 so I hope to see the exception with this...

Also, right click->properties zip file after download and tic unblock if it is there.

**Comment by arnabnaha** [comment]
Its giving me error: try again


*          Dr. Arnab Naha*
*          MBBS (Cal)*

**Comment by arnabnaha** [comment]
No entry in apache error log and also I am not finding anything in the web
console of firefox/chrome..like the 500 internal server error is not
there..but the thing doesnt work


*          Dr. Arnab Naha*
*          MBBS (Cal)*

**Comment by sjpadgett** [comment]
Okay, progress. Give me a second

**Comment by sjpadgett** [comment]
Because the controller sets a default status of 500 in the header that returns the exception json info, that error never makes it to the browser and server 500 is thrown.  I'll leave that to Matt.
I setup the response error from cURL (if it is an error) to print and also die with message in hopes we see what external call returns so, this script goes to openemr/services. Restore the original script product_register_controller.php you previously backup'ed before testing. I'm never certain if echoing from a class will make it to browser but finger's crossed.

[product_registration_service.zip](https://github.com/openemr/openemr/files/922284/product_registration_service.zip)

**Comment by sjpadgett** [comment]
Nevermind @arnabnaha  It won't send error to browser. I forced error and won''t display so I'll get back to you. Sorry, I should know this wouldn't from a class but gave it a shot.

**Comment by sjpadgett** [comment]
@arnabnaha I am able to re-create so maybe my waffling is paying off:) Let me see where it goes.

**Comment by sjpadgett** [comment]
Okay, Found the problem. The registration server is ssl, so default cURL options look to verify certificate unless specifically set not. @MatthewVita @bradymiller do we want to only run this ssl or is it okay to ignore verifying server certificate?

**Comment by sjpadgett** [comment]
@arnabnaha Here is my PR for this: Product registration fix #644.

**Comment by arnabnaha** [comment]
Thanks Jerry..thank u so much..dont mind..i was late in replying..i am
currently in hospital duty..

Thanks and regards
Arnab

On 14-Apr-2017 10:42 PM, "JerryP" <notifications@github.com> wrote:

@arnabnaha <https://github.com/arnabnaha> Here is my PR for this: Product
registration fix #644 <https://github.com/openemr/openemr/pull/644>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openemr/openemr/issues/636#issuecomment-294193757>, or mute
the thread

**Comment by sjpadgett** [comment]
You're welcome. We took the backdoor but finally made it.:)

**Comment by arnabnaha** [comment]
All kudos to you!

**Comment by MatthewVita** [comment]
Wow, a lot of activity on this ticket! @sjpadgett, you are awesome! What a very specific fix!

Can we close the issue?

**Comment by arnabnaha** [comment]
Thanks everyone for actively fixing it. Thanks @MatthewVita for bringing in this feature. Thanks @sjpadgett for the awesome fix and Thanks @bradymiller  for everything
