### ISSUE TITLE
Telehealth Verify Settings button

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#6363]
Add a Telehealth Verify Settings button that checks both the provisioning and the video communication bridge settings.  

Right now there isn't a way for someone to verify the telehealth is setting up properly without creating appointments, users, and going through a full telehealth session.  We need more information that helps users to know if the telehealth is configured properly and an option to check that the settings are properly configured.  This ideally should be on the same screen as the telehealth settings configuration.

**Comment by sjpadgett** [comment]
Excellent!

**Comment by adunsulag** [comment]
Here is what the settings looks like expanded
![image](https://user-images.githubusercontent.com/228117/231807906-04fb86f8-6d64-4ad4-854c-56b2ee35aa32.png)


By default the settings check is collapsed.  Users can expand by clicking on it.
![image](https://user-images.githubusercontent.com/228117/231807209-b27b6d11-b553-46ab-8b6a-81792b783f58.png)
