### ISSUE TITLE
library/overlib_mini.js ??

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#637]
I've noted this file is included in about 23 scripts and is really old. Anybody have any insight into what this is for?
https://github.com/openemr/openemr/blob/master/library/overlib_mini.js

**Comment by bradymiller** [comment]
Sounds like a removal trial is in order :)

**Comment by robertdown** [comment]
holy crap.....

**Comment by bradymiller** [comment]
:)
currently testing removal of this and the calendar.js library

**Comment by bradymiller** [comment]
as promised:
https://github.com/openemr/openemr/pull/640

**Comment by bradymiller** [comment]
done
