### ISSUE TITLE
Dockerfile 7.0.2 openemr.sh not executable

### ISSUE THREAD

**Issue by harmonwood** [openemr/openemr#6420]
### Describe the bug
When launching openemr/openemr:7.0.2 the container fails to start with:
`starting container process caused: exec: "./openemr.sh": permission denied: unknown`

It would appear that that file would need to have the executable flag set after the COPY line in the Dockerfile file.

### To Reproduce

1. Run 'docker run openemr/openemr:7.0.2'
2. See error:
`starting container process caused: exec: "./openemr.sh": permission denied: unknown`

### Expected behavior
Container starts

### Client configuration

- Browser: none
- OpenEMR version: latest/7.0.2
- Operating system: Windows 11/MacOs Catalina

**Comment by bradymiller** [comment]
@harmonwood ,

Note that there are a couple required environment variables with the docker (note this page has links to example docker-compose.yml scripts): https://hub.docker.com/r/openemr/openemr

To clarify, are you trying to use most recent production version of OpenEMR, which is in the 7.0.1/latest docker or are you meaning to use the development version of OpenEMR, which is in the 7.0.2/next/dev docker (this is built daily from the development codebase).

With above info, can provide more specific guidance.
