### ISSUE TITLE
Eye Module not working in v7.0.1

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#6426]
### Describe the bug
![image](https://user-images.githubusercontent.com/834958/235674129-46fba5d1-54f6-402e-8aac-9d993fb5133e.png)

v7.0.0 (2) is on the left and v7.0.1 (demo site) is on the right.

### To Reproduce

Open demo site.
Open new an encounter or existing
Attempt to open eye exam form.

### Expected behavior
View in the left image up top.

### Client configuration
Demo site info.
- Browser: Chrome
- OpenEMR version: 7.0.1
- Operating system: unknown but maybe Ubuntu

**Comment by stephenwaite** [comment]
hi @juggernautsei , does the php error log have anything helpful? thanks
