### ISSUE TITLE
Slight main interface redesign & 7.0.2+ mobile friendly changes

### ISSUE THREAD

**Issue by stevenpjohnso** [openemr/openemr#6460]
### a potential problem

I have to zoom out on the main interface to fit my phone screen while using the demo.

### a possible solution

A more mobile friendly main interface.

I made a wireframe using Figma. 

![image](https://github.com/openemr/openemr/assets/38847165/50d94f36-213a-466f-a2cd-89855cb25956)
left to right: simplified wireframe of 7.0.2 and possible variations.

Feel free to edit the file with this link:

[https://www.figma.com/file/EU3OwlCBbR3y4hKhLotEE0/Mobile-Friendly-Main-Interface?type=design&node-id=0%3A1&t=WN0ZTINy1uDI2jGr-1](https://www.figma.com/file/EU3OwlCBbR3y4hKhLotEE0/Mobile-Friendly-Main-Interface?type=design&node-id=0%3A1&t=WN0ZTINy1uDI2jGr-1)

Team invite link:
[https://www.figma.com/team_invite/redeem/vOQ8xdmKgLNbxkMbTSSqdL](https://www.figma.com/team_invite/redeem/vOQ8xdmKgLNbxkMbTSSqdL)

**Comment by adunsulag** [comment]
Is this for the patient portal, or are you talking about the provider view?
