### ISSUE TITLE
inteface/billing/sl_eob_invoice.php saves to white screen

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#647]
scenario:  running v5.0.0 
clicking on a cpt code in the billing view of past encounters (interface/patient_file/history/encounters.php) a new browser tab opens sl_eob_invoice, enter some payment info, click save, left with white screen

however, clicking on an invoice from reports->finanicial->collection opens new browser tab, enter payment info, click save, and voila, returns to parent window

**Comment by bradymiller** [comment]
Just brought @stephenwaite fix into codebase. thanks for the fix!
