### ISSUE TITLE
drop pma* tables

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#651]
Now that have removed phpmyadmin, going to look into dropping the pma* tables. Looks like pma_bookmark (at least) is being used in a report script; it's quite possible, though this can be removed after more analysis.

**Comment by bradymiller** [comment]
These tables are ready to be removed. Will just need to grep them to remove any leftovers.
pma_bookmark
pma_column_info
pma_history
pma_pdf_pages
pma_relation
pma_table_coords
pma_table_info

**Comment by morg0n** [comment]
I can start on this today!

**Comment by morg0n** [comment]
Okay, this *should* be good now.  Thanks!

**Comment by bradymiller** [comment]
thanks @morg0n for the great contribution! -brady
