### ISSUE TITLE
Portal remove custom theme

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#6523]
### Describe the bug
Step one to remove original custom theme based on Bootstrap 2 and essentially refactored out over the years.
Will remove from all header calls and replace with selectable light or dark openemr theme which for now will be selected from portal Config options.
I'll add to portal patient selectable once I get around to adding a patient account setup profile page so patient has better control over what is important to them.

I'm heading towards a new configurable landing dashboard to allow including custom modules/portal apps/plugins. Stephen is close to our first SMART app for portal and we will be adding some portal api endpoints. Good stuff.

Essentially what I'm after is to open the portal up for app developers and better vendor support which hopefully will incentivize folks to contribute back.

We need notifications for such things as when clinician sends secure message to patient the patient will get an email and/or SMS alert. Or send SMS/Email from dashboard to alert for patient to complete pending forms, launch a questionnaire or send onetime token for a specific task.

Also as we are making portal more app centric, included native components within portal tree should stay framework free and those apps wanting to use frameworks such as angular/react etc should be as custom modules. This will make it easier to manage the various dependencies I see flooding in.
 Unsure what I'll do about the AngularJS apps(secure messaging, secure chat) since that is a dead framework.

### Client configuration

- Browser: All
- OpenEMR version: v7.0.1
- Operating system: All

**Comment by sjpadgett** [comment]
[Home-OpenEMR-Portal.webm](https://github.com/openemr/openemr/assets/1859985/14de04c2-6534-4501-a27f-d138ec1329ac)

**Comment by mdsupport** [comment]
Have you considered the possibility of moving embedded portal code to a module? The product as it stands today has one data only and two graphical interfaces. That will make it possible for you to put a wrapper over presentation layer and dedicated business logic if necessary.

**Comment by sjpadgett** [comment]
@mdsupport I'm working towards a module but to keep legacy going I'm doing in phases. 

@robertdown I didn't get the logo stuff in. Since I've moved documents from under top level, branding that menu will be easier IMO.
Also I think placing an About, with branding, in the new quick start page with also a link to the about clinic website would be ideal.
