### ISSUE TITLE
Head Circumference is missing from the vitals. 

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#6527]
### Describe the bug
This is what was shared with me after we installed v7.0.1 (1)
We have 3 graph that are always checking by the Dr. Chen

1.       The height is plotted properly now
2.       The weight red dots need to be fixed to a bigger size like the dots in height graph
3.       **The head circumference is does not plot on the graph ,** this stature graph only seems to show on the old patients ( eli yates 8 yrs old) but not with new borns.

### To Reproduce

![Untitled](https://github.com/openemr/openemr/assets/834958/0b437e80-ca11-490b-9012-b7fecfb3dca9)

![Untitled](https://github.com/openemr/openemr/assets/834958/61ec56e4-7b43-4366-9ebf-a3c96a4270fb)

![Untitled](https://github.com/openemr/openemr/assets/834958/8b07f0f2-79a4-41fe-baf7-fd617f7fcc2d)

1. Add a '....'

### Expected behavior

show readings on the chart. 
I have tested this in the demo site and the readings don't show on the chart their either. 

### Client configuration

- Browser: All
- OpenEMR version: 7.0.1 (1)
- Operating system: Ubuntu 22.04

**Comment by stephenwaite** [comment]
hi @juggernautsei , pretty likely it's because the [birth section of chart.php](https://github.com/openemr/openemr/blob/7a9bfe7be4c99f6bc8c98903e44b00e89332ec99/interface/forms/vitals/growthchart/chart.php#L495)  wasn't refactored for the metric locale.
