### ISSUE TITLE
feature: use patient filter to assist remote chart review

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#6553]
### Describe the problem

Need to be able to limit the view for a remote user assigned to an insurance company for a chart review.

### Describe the solution you'd like

Use the neat patient filter mechanism originally contributed by @kchapple to create a blacklist of pids  of those people who have insurance based on that payer id.

**Comment by bradymiller** [comment]
If testing well, then looks good to me. Unclear how this works (looks like there is a cli script that is used, but also a custom menu), so very brief documentation would be helpful.

**Comment by bradymiller** [comment]
oops, meant to send above in the PR. will do it again there.

**Comment by stephenwaite** [comment]
https://www.open-emr.org/wiki/index.php/OpenEMR_Modules#Patient_Filter_Module
