### ISSUE TITLE
Selecting Demographics always keeps 1st page blank in pdf

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#659]
Hi..
Yes, its me again with another PDF issue :) 
This time if we select the demographics to be printed in PDF from Patient Reports, it always skips the 1st page of the pdf and the demographics data starts from the 2nd page of pdf keeping 1st page blank. Please see the attached pdf file. 
[demogrpahic_pdf_issue.pdf](https://github.com/openemr/openemr/files/927397/demogrpahic_pdf_issue.pdf)

Thanks and regards
Arnab

**Comment by bradymiller** [comment]
This category deserves it's own label :)
Just created label 'PDF Patient Report' to track these.

**Comment by sjpadgett** [comment]
Another span replacement with div was introduced to custom_report for RTL which may be this issue. Also, including broken vitals in report will cause unpredictable pdf output.

**Comment by sjpadgett** [comment]
@arnabnaha Over time the patient demographics available options have grown but the reporting was formatted for a single page report based on number of options available several years back. Meaning the report has outgrown a single page output when all available options are selected. Because of this and the fact pdf generation is setup for auto paging, tcpdf will predict best it can to center report on one page causing the first page in report. That explains it, now what to do!

**Comment by arnabnaha** [comment]
@sjpadgett 
I understood what you tried to say..but really i dont have a solution for the issue. Its upto you and Brady to help solve this thing.

**Comment by sjpadgett** [comment]
Until I figure out where we might document little tidbits hints, I'll just put here. These are the only css attributes supported by TCPDF: `getHtmlDomArray($html)` in tcpdf.php
`font-family,font-size,font-weight,font-style,color,background-color,text-decoration,width,height,text-align`

**Comment by sjpadgett** [comment]
@bradymiller Was not mPDF in codebase at one time? Could have sworn I did some work in mPDF in 2015.

**Comment by sjpadgett** [comment]
@bradymiller @arnabnaha I just finished replacing html2pdf in custom reports with mPDF with very satisfactory results. Foremost is speed. Using select all, I'm generating pdf's in 10 seconds or less! More so, div's with inline-block property works, meaning, vitals can remain as is. I haven't tested rtl yet but my research assures me this will work as well. Documents inclusion works too. This really surprised me how seamless this works out.

**Comment by bradymiller** [comment]
@sjpadgett 
Very nice!

Just for some background and nighttime reading material :)

Here's the PDF packages OpenEMR story:
http://www.open-emr.org/wiki/index.php/PDF

Here's the more specific html2pdf package OpenEMR story:
http://www.open-emr.org/wiki/index.php/Html2pdf

Sounds like you have likely solved OpenEMR's pdf conundrum!!!
(definitely looks like mPDF will support urf8/rtl/locale really nicely on my quick research)

To confirm, when you mean "Documents inclusions", you mean that it will append the native pdf docs to the pdf?(I assume that's what you meant, but I didn't want to start dancing until confirming this)

Just say the word, and I'll bring this package into OpenEMR via composer to make things easier(and of course update OpenEMR's PDF story wiki page :) ).

-brady

**Comment by sjpadgett** [comment]
@bradymiller Found out why pdf import from patient documents did not work with html2pdf. The syntax for the all the import methods are wrong! Example: `$pdf->pdf->setSourceFile($from_file);` 
where it should be:  `pdf->setSourceFile($from_file);`. Talk about throwing someone off their game!
Anyway, works now with mPDF so if you want to bring in mPDF with composer(worked fine for me) and trim the fat from it, I'm confident I can have the custom report done tomorrow. Just need to know where you put it.

**Comment by bradymiller** [comment]
@sjpadgett,
Will bring it in now. It will be autoloaded, so will be able to use the classes anywhere :)
-brady

**Comment by bradymiller** [comment]
@sjpadgett Just brought mPDF into the codebase and the classes are autoloaded. Looking forward to seeing the magic.

**Comment by sjpadgett** [comment]
@bradymiller I wish I had your energy! Thanks.

**Comment by arnabnaha** [comment]
Hi @bradymiller @sjpadgett I am so sorry, I could not test these as I was in hospital doing my duties. Will test these today and review the changes. I am so thankful to both of you for bringing these changes.

**Comment by sjpadgett** [comment]
@arnabnaha Let's see, saving lives or testing software! I'm pretty sure you have you priorities correct.

**Comment by arnabnaha** [comment]
This issue remains @bradymiller @sjpadgett . Still the 1st page is blank

**Comment by arnabnaha** [comment]
@sjpadgett @bradymiller Introduced the changes of the recent commit in my codebase. Works very well. No more 1st page blank. can happily close this issue.
