### ISSUE TITLE
Deceased or not??

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#6608]
### Describe the bug
There is nothing to do. The chart shows up as deceased today.

### To Reproduce
![image](https://github.com/openemr/openemr/assets/834958/ae32d0fa-0d53-49fb-b342-734edd08a5e1)

Open a chart this is automatic.

### Expected behavior
Not to show deceased unless a date is in the chart.

![thumbnail_image](https://github.com/openemr/openemr/assets/834958/f9fc0ee9-6cb8-445c-b2a4-607bd1ab9f08)

### Client configuration

- Browser: ALL
- OpenEMR version: 7.0.1
- Operating system:

**Comment by robertdown** [comment]
So the deceased card is showing on all patients? Having trouble reproducing this

**Comment by juggernautsei** [comment]
No, it is random. Sometimes it shows sometimes it does not. But in all cases that it does show the patient is not marked deceased.

**Comment by juggernautsei** [comment]
@robertdown @bradymiller and @stephenwaite pointed out that the database did not update. The data type is incorrect in the database. You won't be able to reproduce in the production system unless you were upgrading a database from 5.x. @stephenwaite pointed out the field data type changed in v4. The v5.x was installed clean. So, n v5.x the data type was still set to varchar.

**Comment by juggernautsei** [comment]
Done
