### ISSUE TITLE
Portal documents corrupted on save.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#6617]
Looks like the signature image tag attributes are being corrupted. Possibly due to escaping.
This problem shows itself By getting a 414 status on document load Or HTML shows in rendered form.

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by stephenwaite** [comment]
hi @sjpadgett , not able to reproduce on https://two.openemr.io/a/openemr/portal/home.php

**Comment by sjpadgett** [comment]
![image](https://github.com/openemr/openemr/assets/1859985/3189637f-e349-4ab5-8caf-241f2a142af5)

**Comment by sjpadgett** [comment]
@stephenwaite I've verified this is not due to the changes you did for save security.

**Comment by sjpadgett** [comment]
@stephenwaite 
Shouldn't make any changes to document especially escaping because form may have already been escaped and we are dealing with a copy of original form that may have already been escaped.
```
private function htmlDiff($old, $new): string
    {
        $ret = '';
        $diff = $this->diff(preg_split("/[\s]+/", $old), preg_split("/[\s]+/", $new));
        foreach ($diff as $k) {
            if (is_array($k)) {
                $ret .= (!empty($k['i']) ? attr(implode(' ', $k['i'])) : '');
            } else {
                $ret .= $k . ' ';
            }
        }
        return $ret;
    }
```

I'll fix by removing attr()
