### ISSUE TITLE
Is there a payroll module available?

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#6637]
### Describe the problem

We need a way to calculate a providers pay. 

### Describe the solution you'd like

We would like something that gathered the visits that a provider had and calculate how much that provider is owed for their services.

**Comment by mdsupport** [comment]
Why???

If someone wants to use data from EMR database for whatever purpose, create a standalone repo (e.g. look at our public components in [mdsupport/mdpub](https://github.com/mdsupport/mdpub)) and do whatever with it. 

If you make repo public, community will have option to use it by adding it to composer. You will find development to be faster and more relevant to your needs. You will also save the need for "module" code testing+maintenance by developers!!

**Comment by mdsupport** [comment]
On a side note, payroll data - specially pay rates - are toxic. A simple excel/openoffice calc should meet this requirement and will be more secure.

**Comment by juggernautsei** [comment]
@
