### ISSUE TITLE
Improve pdf output of forms

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#665]
Considering this strategy in all the forms to improve the pdf output:
https://github.com/openemr/openemr/pull/660

thoughts?

**Comment by sjpadgett** [comment]
@bradymiller The mPDF composer load works fine except mPDF needs two writable directories tmp and ttfontdata. The default locations are` vendor/mpdf/mpdf/`. If moved then will need to define in bootstrap or code. If code I need to know where they will be. Maybe something like:
`define("_MPDF_TEMP_PATH", __DIR__.'/../mpdf/mpdf/tmp/');
define("_MPDF_TTFONTDATAPATH", __DIR__.'/../mpdf/mpdf/ttfontdata/');`(I think path is right) in the loader.

**Comment by bradymiller** [comment]
To help out with figuring out the best strategy:
Can these paths be modified without touching the library in vendor directory?(ie. place them in interface/globals.php)
If so, then will make sense to place them in the sites/*/documents/mpdf/tmp and sites/*/documents/mpdf/ttfontdata dirs

**Comment by sjpadgett** [comment]
Sure. I prefer to leave globals alone because of the potential troubles with permissions. I'll put in sites/*/documents/mpdf/ and define in scripts unless you prefer globals.

**Comment by bradymiller** [comment]
Just put them in the scripts for now. We can figure out how to centralize it to globals.php (guessing will need to go after the composer autoload happens) later.

**Comment by sjpadgett** [comment]
oh thought you meant paths. Nope, I can mod the globals and be done with it.
