### ISSUE TITLE
bug: "Show Title on Login" not working in OpenEMR 7.0.1 Patch 1

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#6650]
Admin > Config > Login Page > "Show Title on Login" no longer does anything, no text is displayed. It is supposed to show the contents of Admin > Config > Branding > "Application Title" in the login banner. It worked in OpenEMR 7.0.0 Patch 2.

Admin > Config > Branding > "Application Title" is on and working fine, with its text used in the HTML "title".

OpenEMR 7.0.1 Patch 1 on Linux

**Comment by sjpadgett** [comment]
Verified on demo. Perhaps @robertdown can take a look when he's free.

![image](https://github.com/openemr/openemr/assets/1859985/979688e6-e5e8-47d0-b169-a21791e51256)

**Comment by robertdown** [comment]
Acknowledged, will address this. Definitely won't be today. Can probably patch it tomorrow.
