### ISSUE TITLE
bug: MRD Portal Card does not respect global setting

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#6653]
1. Turn the portal off in Admin > Config
2. Open a Patient's MRD
3. Portal Card still renders

**Comment by sjpadgett** [comment]
Thats prob because of the Assign profiles feature.
Still user can still get to portal dashboard from menu.
the Assign in portal card is really just a convivence function so imo okay to hide card if portal is off.

**Comment by stephenwaite** [comment]
I think @adunsulag wanted this displayed always due to the api I think.

**Comment by bradymiller** [comment]
yep, pretty sure @stephenwaite is correct that this was needed by @adunsulag to show up for the api

**Comment by sjpadgett** [comment]
As I recall the API needs to know if the patient has opted out of allowing API calls to his portal.
Along with that the only thing I can think of is that there is a disclaimer that accompanies the email for portal Credentials required by ONC.
Stephen will need to correct me but I don’t see a reason he would need that the card is turned on and there’s no links inside that card that patient can use for API privileges.

**Comment by robertdown** [comment]
It looks like it's the ability to create credentials, which I assume would be for the API.

I suppose I could further expand the check to see if the API is enabled. If there's no Portal and no API, the card should be fine to hide.
