### ISSUE TITLE
bug: Questionnaire source_url breaks if oauth2 fhir url does not end in a slash

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#6672]
Have an issue where I imported a couple of questionnaires and the source_url was invalid because my oauth fhir url wasn't setup with a slash at the end.  Need to just fix it in the questionnaire service so it adds a slash if one is missing, just so we have valid urls.

**Comment by sjpadgett** [comment]
Normally parts of URL especially domain should not end in a slash
This makes it easier for code that is building URLs to include the proper slashes. This is the norm for OpenEMR

**Comment by adunsulag** [comment]
@sjpadgett Yea its not a problem in the globals config, its when we concatenate the urls with the full path the questionnaire.  Fixing it in the QuestionnaireService is where this should be done instead of changing up any globals value.

**Comment by sjpadgett** [comment]
Yeah you're probably right either way. Between what is the norm and what the spec says can be troublesome.
I didn't realize how browsers are allowing us to be lazy by eval'ing terminating slash either way.
Looks like urls should terminate with a slash.
You see how openemr has taught me bad habits! shame oh for shame!:)
