### ISSUE TITLE
A little Question regarding PDF output

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#670]
Hi @sjpadgett @bradymiller 
A small question. I use a logo in my pdf output for patient report. Previously it was in line with the facility name. Now, after mPDF update, the logo is shown on the top and the facility name below the logo. Can it be fixed or this is inherit property of mPDF?

Thanks and regards

**Comment by sjpadgett** [comment]
@arnabnaha Created a PR to address this issue. Hope it is what you were looking for.

**Comment by arnabnaha** [comment]
Thanks @sjpadgett for bringing this in. Works great and report looks really good. Thanks @bradymiller  for merging.
