### ISSUE TITLE
Duplicated "extends" key in stylelint configuration file

### ISSUE THREAD

**Issue by raskolnikov-rodion** [openemr/openemr#6700]
### Describe the bug

The key "extends" is duplicated in the stylelint configuration file:
![image](https://github.com/openemr/openemr/assets/22417165/ef4d0963-51e3-4cbd-9790-c6e56284bc56)

In the [stylelint docs](https://stylelint.io/user-guide/configure/#extends), multiple configurations are included using array notation:
![image](https://github.com/openemr/openemr/assets/22417165/6e402cee-800c-4abb-95ba-d4bc7c9e602c)

**Comment by raskolnikov-rodion** [comment]
I believe this error is preventing stylelint from applying the rules included in the standard config. If I run the stylelint command to check .scss files in the master branch, I get no errors:

![image](https://github.com/openemr/openemr/assets/22417165/276580df-7b4b-44c8-bf48-ed02d1b29718)

But if I move to the branch with the changes from https://github.com/openemr/openemr/pull/6701, I get this:

![image](https://github.com/openemr/openemr/assets/22417165/ed527749-a372-43df-a504-476e07f41fbf)

**Comment by raskolnikov-rodion** [comment]
To properly fix this without breaking the checks in the pipeline, I can think of two strategies:

- disable the rules that are currently generating errors; or
- include folders in the .stylelintignore

and then incrementally fix issues. First, using the autofix tool provided by Stylelint, and later fixing the remaining files folder by folder until everything is ok.

Having worked on the same issue in a previous project with thousands of errors, I believe the folders strategy is better. It allows us to create small, focused fixes for each file or folder while still maintaining the benefits of the full checks for the rest of the project.

**Comment by bradymiller** [comment]
hi @raskolnikov-rodion , Are there lots of rules that are being broken or just one/couple rules?

**Comment by raskolnikov-rodion** [comment]
> hi @raskolnikov-rodion , Are there lots of rules that are being broken or just one/couple rules?

Hi @bradymiller! That's a good question. Running the check for all the areas we want to target eventually (all the ones above the comment on the .stylelintignore), the list of violations is quite extensive! I stopped counting when I listed 10 different rules 😅
