### ISSUE TITLE
bug: Encounter list in Patient Banner will pull deleted encounters

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#6710]
The Encounter Selection drop down on the patient banner bar will return all encounters associated with a patient, even if the encounter has been deleted.

This list should only return non-deleted encounters.

**Comment by stephenwaite** [comment]
can't reproduce

**Comment by robertdown** [comment]
Yeah, I think I cornered myself into testing a situation that is unlikely to ever happen.

**Comment by stephenwaite** [comment]
![angry-mad](https://github.com/openemr/openemr/assets/5618372/9ebe937d-f0ef-4a28-ba0d-0081b8a6e783)
