### ISSUE TITLE
alert on batch payments screen flashes off 

### ISSUE THREAD

**Issue by robertlight** [openemr/openemr#6717]
[newMods.zip](https://github.com/openemr/openemr/files/12294427/newMods.zip)
### Describe the bug
When you click "Allocate" on the "batch payments" screen, the alert "Please Fill the Date" appears and then quickly disappears and the page reloads

see attached 7.0.1 based modifications to library/payment_jav.inc.php and interface/billing/payment_master.inc.php

**Comment by stephenwaite** [comment]
thanks for issue report @robertlight , would you like to submit a pull request with your code changes?

**Comment by robertlight** [comment]
I have no idea how to submit a "pull request" that's why I put my fixes in the zip file (see attached)

**Comment by stephenwaite** [comment]
there's a nice getting started contributing video series that outlines how to submit a pr if you're interested?
