### ISSUE TITLE
feat: globals setting allow address book data type

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#6752]
Our globals setting should support entering / selecting an address book user id value from the settings.  In my use case I want to select a user to contact for a particular type of notifications.  The user is defined in the address book.  Therefore I want to be able to pop open the address book dialog and select a user that will get saved in the global settings.

**Comment by adunsulag** [comment]
![image](https://github.com/openemr/openemr/assets/228117/8e21e0e4-378f-4b34-9421-d719bf61f8b9)

Clicking on the address book button pops open the address book in a dialog:

![image](https://github.com/openemr/openemr/assets/228117/4c9f17a5-1457-4dc0-af27-f9a07fa1ee4b)

**Comment by sjpadgett** [comment]
@adunsulag 
Did you see where I put in a flag/hook for pop up Address Book a couple years ago?
I do this in Fax and SMS if you want to look at.

**Comment by adunsulag** [comment]
@sjpadgett yep, I saw it and its what I used to help build this feature out.  Still working out a few bugs but your code was very helpful!
