### ISSUE TITLE
bug: Allergies not rendering on MRD

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#6756]
Allergies card is empty

**Comment by Tudor44** [comment]
Hello @robertdown , I have explored this issued maybe linked with the last commit:
https://github.com/openemr/openemr/commit/95f97f40d022a7ce7c33fd51dd73747de6b0f89f

Is it fair at the moment revert this commit?

**Comment by adunsulag** [comment]
Fixed with PR's #6864 #6931 #7008
