### ISSUE TITLE
possible SQL injection vulnerability - setup.php

### ISSUE THREAD

**Issue by bobinson** [openemr/openemr#680]
Test procedure:

1. used OWASP ZAP 2.6 

http://localhost/openemr/setup.php?site=default

2. it seems its possible to manipulate and inject SQL into "site" parameter

result:

    The query time is controllable using parameter value [openemr AND (SELECT * FROM (SELECT(SLEEP(5)))lLYA)], which caused the request to take [77,953] milliseconds, when the original unmodified query with value [openemr] took on average [16.614] milliseconds.

sqlmap is also able to report the same.

**Comment by bradymiller** [comment]
This seems odd, because I don't think the site parameter ever gets used in a sql query.(now cross-scripting attacks are a whole other matter). Does it identify the vulnerable sql query?

**Comment by bobinson** [comment]
> Does it identify the vulnerable sql query?

I am not sure of the SQL query as such. From the reports, it seems there is a Blind SQL query injection bug.  ref: https://www.owasp.org/index.php/Blind_SQL_Injection

The trouble is I am not able to recreate the URL. ie I tried passing on multiple possible blind sql query injection "culprits" but they are not valid and I am getting the following error.

`Site ID '[openemr AND (SELECT * FROM (SELECT(SLEEP(5)))lLYA)]' contains invalid characters.
`

In general the error report means we will be able to pass on queries of the above nature as arguments to site parameter and measure whether there is a delay. Let me look into the access logs to find out the exact query that OWASP and sqlmap is using.

**Comment by bobinson** [comment]
@bradymiller - found the query:
```

POST http://localhost/openemr/setup.php?site=default HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
Pragma: no-cache
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Content-Length: 302
Referer: http://localhost/openemr/setup.php?site=default
X-ZAP-Scan-ID: 90018
Connection: Close
Host: localhost

state=3&site=default&inst=1&server=localhost&port=3306&dbname=openemr+AND+%28SELECT+*+FROM+%28SELECT%28SLEEP%285%29%29%29lLYA%29&login=openemr&pass=ZAP&root=root&rootpass=ZAP&loginhost=localhost&collate=utf8_general_ci&iuser=admin&iuserpass=ZAP&iufname=Administrator&iuname=Administrator&igroup=Default
```

**Comment by bradymiller** [comment]
@bobinson 
Looks like its the dbname parameter, which is not surprising, since this variable is used in sql query to create the initial database and also another query to set the permissions.

The setup.php script has no protection from sql injection. It's also a special case and uses native mysqli functions (rather than the rest of openemr which uses standard sql wrappers in library/sql.inc). To fix this issue, would need to incorporate mysqli_real_escape_string() into library/classes/Installer.class.php.

**Comment by bobinson** [comment]
@bradymiller thank you. I am looking into this.

I have a doubt : After the installation, is there a check which prevents setup.php from called again ? on my test install its still available and tried finding few random installs with Google dorks and they also seem to have the setup.php present.

**Comment by bobinson** [comment]
config value in sqlconf.php is zero.

```
[09:01 PM]@[/usr/local/var]: find . -name sqlconf.php
./www/htdocs/openemr/library/sqlconf.php
./www/htdocs/openemr/sites/default/sqlconf.php
```

**Comment by bradymiller** [comment]
@bobinson ,
To further complicate things :)

The setup.php script is also used to set up multisites (ie. 1 codebase footprint can support numerous openemr instances by placing them in sites/<name>/ ; the sites/default/ is an example of this).

Some information on this here:
http://www.open-emr.org/wiki/index.php/OpenEMR_Multiple_Sites_Module

And note it is recommended to secure/remove setup.php after install:
http://www.open-emr.org/wiki/index.php/Securing_OpenEMR#OpenEMR

**Comment by bradymiller** [comment]
Working on this here:
https://github.com/openemr/openemr/pull/1204

**Comment by bradymiller** [comment]
fixed
