### ISSUE TITLE
encounters history randomly shows "Patient" in red 

### ISSUE THREAD

**Issue by robertlight** [openemr/openemr#6838]
The encounters history randomly shows "Patient" in red (ie: --danger) when the balance is zero.

This is caused by line 252 src/Billing/INvoiceSummary.php
     if( $balance > 0 ) {

it should be:
    if( $balance > 0.009 ) {
    
 Sometimes the balance has a value of E-14  which, while > 0, is arithmetically "zero" and should be treated as such.

**Comment by stephenwaite** [comment]
thanks for the report @robertlight!
