### ISSUE TITLE
bug: Generate Demographic Widget/Cards from Modules - No custom function call in "btnLink"

### ISSUE THREAD

**Issue by dcvidigal** [openemr/openemr#6840]
I'm developing a module to openemr and one of the functionalities is a widget. 
This widget will have the edit button active with a custom function call. The problem is never called due to a possible bug on demographics.php.

In the block of code that generates the widgtes/cards from the modules, lines [1621](https://github.com/openemr/openemr/blob/d25d771cc211874d02ff9052c84807ffd7ea7f15/interface/patient_file/summary/demographics.php#L1621)-[1650](https://github.com/openemr/openemr/blob/d25d771cc211874d02ff9052c84807ffd7ea7f15/interface/patient_file/summary/demographics.php#L1650), in the line [1646 ](https://github.com/openemr/openemr/blob/d25d771cc211874d02ff9052c84807ffd7ea7f15/interface/patient_file/summary/demographics.php#L1646)there is the code 

`'btnLink' => "javascript:$('#patient_portal').collapse('toggle')"`

shouldn't this line receive a custom btnLink property? 
and btw the btnLabels the same?

**Comment by dcvidigal** [comment]
I think I "jumped the gun" with this. 
I analyze it a little more, and notice the array_merge. 
That's suppose to merge the properties from $card->getTemplateVariables() with the $viewArgs.

But, here's the catch, if i have this array on templateVariables()
`array (
  'linkMethod' => 'javascript',
  'btnLabel' => 'Edit',
  'btnLink' => 'customFuncCal()'
  ),
)`

The properties will never be replace because when you use the array_merge, the common keys (e.g., 'linkMethod', 'btnLabel', 'btnLink') from the second array will overwrite the values in the first array with the same keys.

Therefore the line
`echo $t->render($card->getTemplateFile(), array_merge($card->getTemplateVariables(), $viewArgs));`
should be replaced by
`echo $t->render($card->getTemplateFile(), array_merge($viewArgs,$card->getTemplateVariables()));`

**Comment by adunsulag** [comment]
@dcvidigal sounds like a good fix.  Did you want to submit a Pull Request (PR) for this?

**Comment by dcvidigal** [comment]
Sure! :) I'll do it :)
