### ISSUE TITLE
reopening encounter through void on fee sheet fails

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#685]
ERROR: query failed: INSERT INTO voids SET patient_id = ?, encounter_id = ?, what_voided = ?, date_voided = NOW(), user_id = ?, amount1 = ?, amount2 = ?, other_info = ?, date_original = ?
    Error: Column amount1 cannot be null
    /var/www/openemr/library/billing.inc at 370:sqlStatement
    /var/www/openemr/interface/forms/fee_sheet/new.php at 479:doVoid(37,214,1)

**Comment by bradymiller** [comment]
Looks like could make this variable 0 if it's null here:
https://github.com/openemr/openemr/blob/5220b634e2f1e28c8ce8204d766ba1cd5cad37ba/library/billing.inc#L363

**Comment by bradymiller** [comment]
Could use a quick ternary in the same line to do that. maybe something like:
``````
(empty($row['payments'])) ? 0 : $row['payments'], $old_invoice_refno);
``````

**Comment by bradymiller** [comment]
doh, above line is for amount2. should instead do for the amount1 variable ( $row['adjustments'] ) .

**Comment by bradymiller** [comment]
Actually, looking through that script, should just be able to substitute $row['adjustments'] with $adjustments in the query and then should be good.

**Comment by stephenwaite** [comment]
nice, thanks, i'll patch it up for us - btw that php dx would have taken me much longer :)

**Comment by bradymiller** [comment]
Would also clean that up by changing the $row['payments'] to $payments in that query :)
(to avoid null errors on amount2)

**Comment by stephenwaite** [comment]
ok, thanks for the tip

**Comment by stephenwaite** [comment]
on initial test with above changes, same error :(
i'll write some debug info to the error log and see why there's bad values in the query

**Comment by bradymiller** [comment]
that is really odd, the function defaults the $adjustments and $payments to zero but then there are some if stuff that queries them from places that shouldn't be able to return a null. sounds like there may be another bug in there; error_log madness sounds like a good idea (it's also my debugging engine of choice :) ).

**Comment by stephenwaite** [comment]
Yeah, it's not handling if nothing is returned from ar_activity, which leads to another issue, why aren't copays stored in ar_activity...

**Comment by bradymiller** [comment]
@stephenwaite ,
Just checking if this issue was addressed (I think it was, but don't clearly recall).
thanks, -brady

**Comment by stephenwaite** [comment]
hmm, think it wasn't :(

**Comment by stephenwaite** [comment]
update, dovoid in fee_sheet/new.php isn't passing time so query fails

**Comment by stephenwaite** [comment]
update :) bill_time isn't matching post_time in the minutes and seconds

**Comment by stephenwaite** [comment]
hi @sunsetsystems , aka Rod :) 

https://github.com/openemr/openemr/blob/master/library/billing.inc#L423-L424
and
https://github.com/openemr/openemr/blob/master/library/billing.inc#L444

would it make sense for the query to match on YYYY-MM-DD vs +HH-MM?

**Comment by sunsetsystems** [comment]
No. The timestamp is important to distinguish between multiple checkouts in the same encounter.
Do we have steps to reproduce this problem?

**Comment by stephenwaite** [comment]
ok, thanks. yes, create a fee sheet, add an item and a copay and then do void.

**Comment by sunsetsystems** [comment]
Thanks Stephen, I'll find some time to look at this.

**Comment by sunsetsystems** [comment]
See fix here: https://github.com/openemr/openemr/pull/1322

**Comment by sunsetsystems** [comment]
By the way, the mismatch between the timestamps in billing and ar_activity is a problem that will be fixed in some upcoming major updates to fee sheet and checkout code.

**Comment by stephenwaite** [comment]
nice simple fix for now and thanks for the update
