### ISSUE TITLE
Medical record dashboard - recurring appointments labels are not translated

### ISSUE THREAD

**Issue by macomeza** [openemr/openemr#6857]
### Describe the bug

I am translating medical record dashboard to spanish (latin america), on medical record dashboard I want to setup recurring appointments translation. I have set spanish translation to "cita recurrente", but it still shows "recurring appointments", also when no recurring appointment has been scheduled it also says "No Recurring Appointments".

### To Reproduce
I have tried to translate it to spanish and italian (admin > system > language)

### Expected behavior
I hope to see my label translated, but it doesn´t work.

![image](https://github.com/openemr/openemr/assets/77448377/d92aeadf-8c5e-43bf-8f9d-de9fd6bc336c)

### Client configuration

- Browser: Chrome
- OpenEMR version: 7.0.1
- Operating system: Windows (server is running in Ubuntu 22.04

**Comment by bradymiller** [comment]
For `No Recurring Appointments`, create a constant called "No Recurring Appointments{{Appointments}}" and then create a definition for that.
For `Recurring Appointments`, ensure you have a constant called "Recurring Appointments" (with correct caps) with your definition assigned to that.

**Comment by macomeza** [comment]
This works! Thanks you so much!
