### ISSUE TITLE
lose modifier on line item in fee sheet 

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#686]
if don't save before add dx it's lost so have to always add dx then modifier

**Comment by stephenwaite** [comment]
hi @sjpadgett , could you clue me in on where to look for the javascript modifier thief?

**Comment by sjpadgett** [comment]
Hi @stephenwaite Is this on new feesheets, existing add dx or?? I haven't been able to recreate on master. In the end will prob have something to do with refresh. Last I looked at this form it can be a little tricky on saves.

**Comment by stephenwaite** [comment]
just reproduced on https://six.openemr.io/c/openemr/interface/login/login.php?site=default, choose Phil, go to his 2014 encounter and put mod 59 in the modifier field and then go and choose a new dx to justify and update and the modifier will go poof

**Comment by sjpadgett** [comment]
lol, I've tried every which way and this works for me.
- goto feesheet
- add modifier to cpt 99214
- search/add Z00.00 ICD10
- save
Tried on new feesheets as well on my local. Maybe Phil has something against you......

**Comment by stephenwaite** [comment]
you're not updating the dx (justifying) though, right? (you have to scroll down on the too small modal :)

**Comment by stephenwaite** [comment]
it also wipes out changes to price or units or note codes

to recap it's the Update button inside the justify popup modal that is not checking for current values in these fields before it

**Comment by sjpadgett** [comment]
okay, I see 😎. First, this needs to be restyled to be useful. one or two lines don't get it. hopefully a z-index may work but sadly, the container will need to grow.
I'll go thru the code and see what I see...

**Comment by stephenwaite** [comment]
:disappointed_relieved:

**Comment by sjpadgett** [comment]
Hopefully you're crying with me and not for me!.....

**Comment by stephenwaite** [comment]
funny, yeah, looking at http://learn.knockoutjs.com/#/?tutorial=loadingsaving to get a feel for what Kevin was up to

**Comment by sjpadgett** [comment]
Okay, found issue however, I don't think this has worked for a very long time. Can't see how. Update is not a submit but looks like it was meant to be at some point so on update all that happens is a reload of last save plus any new dx that were save exclusive by update.

This may take something clever to fix.(by clever, I mean a hack :))

**Comment by sjpadgett** [comment]
Okay, i'm going to call PR #2678 a fix for this issue. Until next time :)

**Comment by stephenwaite** [comment]
thanks @sjpadgett
