### ISSUE TITLE
Line breaks of text are not exporting as is when generating a document

### ISSUE THREAD

**Issue by macomeza** [openemr/openemr#6868]
### Describe the bug

If you have a textarea field on any form (standard and LBF / LBT), which has line breaks (like a numbered list) and you use it in one document template (odt) your text will shows as a single line.

### To Reproduce
Use a textarea field, like additional history (history | other) as a numbered list, like:
1- first
2- second

1. Add a numbered list to additional history
2. Click on patient name
3. Scroll down to documents > medical record > select a patient document template forms, then fetch-

1- first 2- second

### Expected behavior

1- first
2- second

### Client configuration

- Browser: Chrome
- OpenEMR version: 7.0.1
- Operating system: Ubuntu 22.04

**Comment by macomeza** [comment]
@bradymiller @stephenwaite could you please review this micro enhancement? Thanks

**Comment by sjpadgett** [comment]
I don't think this is a good idea. This is specific to xml/word doc type files. I believe will break in plain text.
data fixup is making universal assumption that line break works across all mime types.
You'll need to test mime and add conditional.
