### ISSUE TITLE
ClaimRev Module problem in adding issues to encounter

### ISSUE THREAD

**Issue by claimrevolution** [openemr/openemr#6894]
### Describe the bug

for some reason when the module is enabled, the system displays  a blank model window when adding issues to a patient encounter.

### To Reproduce
enable module
then go to a patient encounter and add an issue.  A blank modal window will pop up.

### Expected behavior

A model window will pop up with a form to enter some data.

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by sjpadgett** [comment]
I have my modules installed and on but I don't see a problem.
Are you listening for encounter events for some reason? It could be an event implementation.

**Comment by claimrevolution** [comment]
It was weird and I didn't believe it. And Robert helped figure it out. If you want we can do a teams meeting later and I can show you.

Brad Sharp
CTO
Mobile: 1-405-410-4438
www.claimrev.com<http://www.claimrev.com/>

Sent from mobile device, please excuse typos and brevity.

________________________________

**Comment by sjpadgett** [comment]
No need if you have it figured out. Though was it in your module or the event in encounters?

**Comment by claimrevolution** [comment]
it was in my modules bootstrap file. 

require_once $GLOBALS["srcdir"] . "/options.inc.php";

I'm not even sure why it was there, it appeared after I moved it to core. all weirdness went away after that was deleted.
