### ISSUE TITLE
Fixing IDE red lines 

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#6898]
### Describe the bug

PHPStorm was giving a red line under this file every time I opened it. So, here are the fixes.

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by sjpadgett** [comment]
Sorry  @juggernautsei  I didn't realize you was talking about IDE. Just turn off the error check in settings.
