### ISSUE TITLE
XMLFormGen not working in 5.0.1

### ISSUE THREAD

**Issue by mrpenelope** [openemr/openemr#691]
In my quest to make better forms for distribution, I came across the XMLFormGen, and decided to use it, only to find it was broken in 5.0.0, after upgrading to 5.0.1, same effect.

**Comment by bradymiller** [comment]
hi @mrpenelope  ,
This has recently been tested to work. When you mean broken, do you mean creation of the forms? or do you mean the created forms do not work? Also, seeing any errors?
thanks, -brady

**Comment by mrpenelope** [comment]
Brady -- I apologize for not responding earlier, in our area, we had a large-scale power-outage.

Creation of the forms does not appear to be broken.

Included are screenshots of my error log, OpenEmr interface upon launching the form, and the form code itself, which is directly ripped from the Wiki page on this function.
![capture](https://cloud.githubusercontent.com/assets/18219280/25591226/565dca6e-2e79-11e7-8409-5c09f5ec7ad9.JPG)
![capture1](https://cloud.githubusercontent.com/assets/18219280/25591225/565c7a92-2e79-11e7-8bf0-ff77664f7fa3.JPG)
![capture2](https://cloud.githubusercontent.com/assets/18219280/25591227/565e05e2-2e79-11e7-8625-a2f7d3caed76.JPG)

**Comment by mrpenelope** [comment]
Please bare in mind this is with 5.0.1, fresh git clone, with old db loaded in

**Comment by mrpenelope** [comment]
I would also not be opposed to giving you access to the Development node.

**Comment by mrpenelope** [comment]
upon further investigation, I do not see repeating errors when pulling up the form. it's as if the form itself is blank. This is of course, referring to the code inspection on Chrome.

**Comment by mrpenelope** [comment]
With a fresh install / fresh db, form generation appears to be working. Could it be broken by upgrading incrementally from 4.2.0 onward?

**Comment by mrpenelope** [comment]
Interesting. The form I originally generated was broken. This was copied word-for-word from the Wiki as a test.

**Comment by mrpenelope** [comment]
![capture3](https://cloud.githubusercontent.com/assets/18219280/25676055/4832fd90-3006-11e7-8508-526621e31dfa.JPG)

**Comment by sjpadgett** [comment]
Have you tried making your safe name testfield instead of testfields?

**Comment by mrpenelope** [comment]
Just tried, Recompiled form and re-registered with db. Other ideas are welcome.

**Comment by sjpadgett** [comment]
Can you send me your generated form? sjpadgett@gmail.com

**Comment by mrpenelope** [comment]
Just sent, please feel free to email back for any questions.

**Comment by sjpadgett** [comment]
Your table field array is not being generated although the table is! Try adding ` <manual>` before first section in xml script, then generated.

**Comment by mrpenelope** [comment]
That worked, thank you so much for your help.

**Comment by sjpadgett** [comment]
Glad I could help.
