### ISSUE TITLE
feat: put request urls from x12 clearinghouse screens into globals for versatility

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#6913]
### Describe the problem

TODO put request urls in x12 partner's for versatility

### Describe the solution you'd like

TODO put request urls in x12 partner's for versatility

**Comment by adunsulag** [comment]
This was completed in PR #6914

**Comment by juggernautsei** [comment]
I found where another commit has moved the URL to the x12 partner screen.  I just did not take the time to delete this commit. It is not needed.
