### ISSUE TITLE
bug: results only electronic procedure results create multiple encounters for same datetime

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#6933]
### Describe the bug

encounter feature not looking for datetime of existing encounter

after encounter date was updated to datetime a downstream select statement needed to be updated

### Expected behavior

if an encounter has been created for an incoming result then catch that encounter to prevent multiple encounters from being created

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by adunsulag** [comment]
Per @stephenwaite this has been fixed.

**Comment by stephenwaite** [comment]
Thanks @adunsulag. Fixed in https://github.com/openemr/openemr/commit/8d5dc6ef9499da7ee3994a78672118b561b2f30c
