### ISSUE TITLE
Delete patient not working (EMR 5.0)

### ISSUE THREAD

**Issue by etls** [openemr/openemr#694]
/interface/patient_file/summary/demographics.php

line 506            href='../deleter.php?patient="
Changed to      href='../deleter.php?patient=

**Comment by bradymiller** [comment]
Hi @etls ,
Thanks for reporting bugs and fixes! This bug was already fixed in the most recent 5.0.0 patch:
http://www.open-emr.org/wiki/index.php/OpenEMR_Patches
