### ISSUE TITLE
Encounter does not insert default POS from facility

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#6952]
### Describe the bug

The default POS type is stored in the facility information. 
When an encounter is saved, that POS is not stored with the encounter. It is null unless the select POS in the encounter is activated in the config. 

### To Reproduce

1. Add new encounter.
2. Save encounter
3. Check the form encounter table column pos_code. 
4. It will be null/empty

### Expected behavior

The POS code should be gotten from the facilities table when saving the encounter.

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by adunsulag** [comment]
Closing as this was fixed in PR #6953
