### ISSUE TITLE
Authorization Code Grant Madness

### ISSUE THREAD

**Issue by sharansudheer** [openemr/openemr#6998]
### Describe the bug

After enabling everything needed for accessing the APIs with the Authorization Code Grant through a separate client app, like going to Admin > Config > Connectors > Enable OpenEMR Standard FHIR REST API, Enable OpenEMR Standard REST API 
and Enable OAuth2 Password Grant. 

Register a new Multipurpose Confidential Application with all the scopes except the system scopes enabled through the Web interface, I am getting an Auth failure 401 in Postman and in my client app FOR STANDARD APIs, NOT FHIR.

Funny thing is when I created a custom function to register an app through a POST request according to the payload enlisted in the API documentation, the code grant/access token and refresh tokens are Working perfectly. I spent a month on this issue.

I don't know what have I missed out @bradymiller @adunsulag. 
No idea why the web based way of Registering a Client app has this issue.

### Client configuration

- Browser:
- OpenEMR version: 7.0.1
- Operating system: AWS Machine Image and Docker env in Ubuntu 22.04

**Comment by adunsulag** [comment]
I'm not sure I'm understanding your reported bug.  You're saying that when you do a POST request with your requested scopes the request works fine, but when you do a registration through the web GUI it fails?

If you actually look at the network console in your dev tools you'll see that the ajax request does the exact same post request in the GUI to the registration endpoint.  You can compare what scopes you are requesting vs getting back in the payload with what you are seeing in your POST.  What scopes are you requesting differently in your POST request vs what is in the gui?

**Comment by sharansudheer** [comment]
I am requesting all the available Standard and FHIR scopes, just to understand why is it acting differently when I go with the  OpenEMR's GUI approach. I just need the GET requests to authenticate properly to prove that all the registration has been executed successfully.

**Comment by adunsulag** [comment]
@sharansudheer So you are getting a 401 error for registration, or for your access token request?

This is happening on both your local environment and one of the demo environments? FYI, the demo environments can be found here: https://www.open-emr.org/wiki/index.php/Development_7.0.1_Demo

**Comment by sharansudheer** [comment]
The FHIR endpoints are working fine in both cases. But, the Standard APIs are buggering me. I have tried to find out if it was an API endpoint - user specific problem, like if it was a problem related to the user being and admin or practitioner, etc. No chance.

I am getting a 401, when I am trying to access an Endpoint belonging to the Standard API, registered through the OpenEMR's GUI.

I had set up a local environment and I had set up an AWS instance as well. That instance has crashed and self disintegrated for reasons unknown while I was trying to fetch patient information, thats an issue for an another day 😂.

**Comment by adunsulag** [comment]
@sharansudheer I went and did a registration on the demo and I think I understand the problem you may be running into.

The only resources listed on the GUI side are FHIR apis for the scopes you can register for.  Standard APIs use lowercase names for the scopes, which I understand is confusing in hindsight but the standard scopes in OpenEMR were setup before FHIR was built and had to be maintained for backwards compatability.  I'm guessing this is likely the problem you are running into as that would indeed create a problem for you as you won't be able to access standard APIs registering your app through the GUI interface.

The GUI app was built specifically for registering SMART on FHIR apps using FHIR apis.  It hasn't been updated to register apps for non-FHIR apis, but probably should be in the future.

**Comment by adunsulag** [comment]
For example standard api uses patient/patient.read and FHIR uses patient/Patient.read (notice the uppercase resource name).  In the GUI you can only register patient/Patient.read whereas a post request will allow you to register patient/patient.read AND patient/Patient.read.

**Comment by sharansudheer** [comment]
Ohhh ok. I get it now.

**Comment by sharansudheer** [comment]
So it is an issue with the GUI, isn't it?

**Comment by adunsulag** [comment]
If you intend to use the GUI to register standard API clients then yes, it doesn't work for that use case.  This is more a feature request than broken behavior as the GUI wasn't built to register standard clients.  The documentation on the page and OpenEMR should probably be updated to reflect that, or the feature built to support the standard apps.
