### ISSUE TITLE
bug: Bulk Patient FHIR Export fails w/ 500 error when OpenEMR has insurance company provider in the system.

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#7000]
There is a bug in all of the fhir bulk $export calls if there exists an insurance company in the EMR.  For example a call to:

```/apis/default/fhir/Patient/$export``` will trigger a 500 error with the following in the PHP error logs:

PHP Fatal error:  Uncaught Error: Call to a member function setLastUpdated() on null in /var/www/localhost/htdocs/openemr/src/Services/FHIR/Organization/FhirOrganizationInsuranceService.php:96\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/src/Services/FHIR/FhirServiceBase.php(232): OpenEMR\\Services\\FHIR\\Organization\\FhirOrganizationInsuranceService->parseOpenEMRRecord()\n#1 /var/www/localhost/htdocs/openemr/src/Services/FHIR/Traits/MappedServiceTrait.php(87): OpenEMR\\Services\\FHIR\\FhirServiceBase->getAll()\n#2 /var/www/localhost/htdocs/openemr/src/Services/FHIR/FhirOrganizationService.php(97): OpenEMR\\Services\\FHIR\\FhirOrganizationService->searchAllServicesWithSupportedFields()\n#3 /var/www/localhost/htdocs/openemr/src/Services/FHIR/Traits/FhirBulkExportDomainResourceTrait.php(73): OpenEMR\\Services\\FHIR\\FhirOrganizationService->getAll()\n#4 /var/www/localhost/htdocs/openemr/src/RestControllers/FHIR/Operations/FhirOperationExportRestController.php(333): OpenEMR\\Services\\FHIR\\FhirOrganizationService->export()\n#5 /var/www/localhost/htdocs/openemr/src/RestControllers/FHIR/Operations/FhirOperationExportRestController.php(147): OpenEMR\\RestControllers\\FHIR\\Operations\\FhirOperationExportRestController->processResourceExportForJob()\n#6 /var/www/localhost/htdocs/openemr/_rest_routes.inc.php(11565): OpenEMR\\RestControllers\\FHIR\\Operations\\FhirOperationExportRestController->processExport()\n#7 /var/www/localhost/htdocs/openemr/src/Common/Http/HttpRestRouteHandler.php(103): {closure}()\n#8 /var/www/localhost/htdocs/openemr/apis/dispatch.php(389): OpenEMR\\Common\\Http\\HttpRestRouteHandler::dispatch()\n#9 {main}\n  thrown in /var/www/localhost/htdocs/openemr/src/Services/FHIR/Organization/FhirOrganizationInsuranceService.php on line 96

Looking at line 96 in FhirOrganizationInsuranceService.php a refactor of the metadata setLastUpdated broke the bulk export.  Our Inferno snapshots did not have insurance companies in the data set so this error slipped by our testing.  The stock demo datasets do have insurance companies.  Thanks to @eva-val for helping us to discover this issue.

**Comment by bradymiller** [comment]
I just brought this into the rel-702 branch
(plan to bring in commits from master to rel-702 quickly (and in order of master) prior to release to avoid missing anything and avoiding merging issues)
