### ISSUE TITLE
Demographic summary themes broken

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#7011]
### Describe the bug
Screenshot says it all.
![image](https://github.com/openemr/openemr/assets/1859985/766195bb-55ac-45cb-82fe-7fb321065a22)

### To Reproduce
Turn on dark theme

**Comment by sjpadgett** [comment]
This is weird because works fine on demo ten. I don't trust my environment so will close.

**Comment by sjpadgett** [comment]
I can't clear this on windows on latest master. Will test demo again after reset.

**Comment by sjpadgett** [comment]
We're missing our expand icon that got me involved with this in first place. Have we changed our mind?
Demo ten and windows.
![image](https://github.com/openemr/openemr/assets/1859985/3bcd9cbc-cf69-4fc3-a474-fbc751fd00fc)

**Comment by sjpadgett** [comment]
I hope last comment didn't sound snotty!

**Comment by bradymiller** [comment]
yep, not sure why gone. The bug that was there with the icons was:
1. The expand/collapse of widget are not persistent when click on the icon and throw javascript promise error when click on the icon
2.  Show contract icon when has been expanded

I guess the fix was to remove them to get rid of both issues :)
https://github.com/openemr/openemr/commit/084d17b3ade4ca326e709bc112b0c78578674a99
(guessing was just a mistake to remove the icon)

**Comment by bradymiller** [comment]
Also noted those widget labels now have much smaller font size and are no longer bold
(and if add back the icon still have same issue where when click on the icon it throws a promise error is is not persistent)

**Comment by bradymiller** [comment]
fix here: https://github.com/openemr/openemr/pull/7013
(for the persistence with the icon click, had to add the data-target into the i tag)

**Comment by bradymiller** [comment]
while working on above, also noted following bug (which put in the pending release but tracker at https://www.open-emr.org/wiki/index.php/QA_and_Release_Process#Tickets_Pending ):
All widgets in patient summary screen that derive from stats.php script do not maintain persistence (PENDING)

**Comment by sjpadgett** [comment]
All of this is just weird! I haven't yet found anything any of us have done to cause styling issues. I still can't get rid of white bg.
I know where just not why yet.

**Comment by sjpadgett** [comment]
Re pulled master and this is fixed. Windows file system is horrible sometimes. I see weird stuff like this all the time anymore but somebody has to test windows I guess otherwise this would be my last PC to move to linux!!!
