### ISSUE TITLE
Procedure order form issue in chrome

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#702]
Hi...
The procedure order form looks great in bootstrap. Thanks for the awesome look. The issue in chrome is, the text on the Add procedure buttons are not visible clearly. The top part of the forms are also getting cropped out. This is happening for all the forms.

![issue3](https://cloud.githubusercontent.com/assets/1074948/25671709/9a7167ac-304e-11e7-9236-1320d92dc478.jpg)

**Comment by bradymiller** [comment]
Regarding the button issue, ensure you delete the browser cache.

**Comment by arnabnaha** [comment]
Thanks @bradymiller. This worked. closing this issue

**Comment by robertdown** [comment]
Reopening as the menu bar is still a bug

**Comment by arnabnaha** [comment]
@robertdown  I have that covered in a seperate issue here - https://github.com/openemr/openemr/issues/701
