### ISSUE TITLE
Recent Patient tab in finder not displaying patient date of birth.

### ISSUE THREAD

**Issue by DrBassman** [openemr/openemr#7035]
### Describe the bug
OpenEMR version 7.0.2 running from the production docker does not show patient date of birth for any of the patients in the "Recent Patients" tab / list.

write concise description of what the bug is.
7.0.2 added a "Recent Patient" tab to the finder.  Looking through previous issues, this is to keep the last 10 (or 20?) patients for the user in a list that persists through logout/login cycles.

### To Reproduce

0)  Browser does not matter -- same behavior with either Firefox, Chrome, Vivaldi, .
1)  Search for a patient & go into their dashboard.
2)  Click the (x) button to close the patient.
3)  Go into patient finder -> Recent Patients
4)  See the recent patient's last name, first name, but not their date of birth.

Viewing the Admin->Forms->Lists->Recent Patient Columns it appears there is a typo for the ID.  The default has "dob".  The column in patient_data table is "DOB" (note lower -vs- upper case).

I Tried changing the ID from "dob" to "DOB" and re-loading the patient finder -> Recent Patients.

Now, for each patient THE CURRENT DATE AND TIME are displayed (not the patient's date of birth).  I have tried to locate the code that produces this error -- I cannot find it...Please help.
### Expected behavior
Patient's date of birth should be displayed in that column...

### Client configuration

- Browser:  doesn't matter
- OpenEMR version: openEMR 7.0.2
- Operating system:  Production Docker version 7.0.2

**Comment by DrBassman** [comment]
In fact, NONE of the other columns in the patient_data appear to be displayed if I enter their name in the ID column on Admin->Forms->Lists->Recent Patient Columns.  Only fname, mname, and lname appear to be displayed on the "Recent Patients" tab / list.

**Comment by stephenwaite** [comment]
hi @DrBassman , thanks for the report!

It looks like a simple typo fix for the DOB. The other columns are magically loading so can't confirm that. Just make sure you're saving the recent patient list in the list editor which is easy to forget to do.

**Comment by DrBassman** [comment]
Thank you for the reply, @stephenwaite 

It is more than the typo.

When you correct the typo, it shows the current date & time in that column:
<img width="1230" alt="2023-11-19 14_24_53-ludicrous rtl lan - PuTTY" src="https://github.com/openemr/openemr/assets/7832037/ce6fc463-ccc5-4082-94c9-07671d9590d2">

If you change and have another column from patient_data, it doesn't show anything:
<img width="816" alt="2023-11-19 14_27_29-OpenEMR - Vivaldi" src="https://github.com/openemr/openemr/assets/7832037/77202c61-d939-430f-81ae-c57a5bd2bb5b">

<img width="1230" alt="2023-11-19 14_26_30-ludicrous rtl lan - PuTTY" src="https://github.com/openemr/openemr/assets/7832037/b0e0da0c-69f9-4acf-90f4-f7af889c85e7">

<img width="1173" alt="2023-11-19 14_30_01-OpenEMR - Vivaldi" src="https://github.com/openemr/openemr/assets/7832037/6a16fb7c-0370-45bd-9e87-6dc8cb082536">

<img width="1230" alt="2023-11-19 14_30_30-ludicrous rtl lan - PuTTY" src="https://github.com/openemr/openemr/assets/7832037/f9f9b659-1f42-4461-8118-33785772171a">

Images from official open-emr demo #1.

**Comment by stephenwaite** [comment]
may have to log out and back in to have the dynamic finder script refresh

![Screenshot from 2023-11-19 18-45-08](https://github.com/openemr/openemr/assets/5618372/2d093af3-0931-426d-aa8f-a2435dc4a8b5)

**Comment by DrBassman** [comment]
Odd -- I don't have to log out & back in when I change the "Patient List Columns" for the "Patient List" tab...

Looking at the structure of the recent_patients table, however, may give a clue why this is.  Apparently it stores the columns for that recent patient using the list of columns from the "Recent Patient Columns" list AT THE TIME when that patient is stored in the Recent Patient List?  I would think it would make more sense to only store an array of the patient_data.id (which appears as pid at the end of the data shown in the photo)...

<img width="803" alt="2023-11-19 21_15_28-dcdocker losh lan_8310 _ mysql _ openemr _ recent_patients _ phpMyAdmin 5 2 1 - " src="https://github.com/openemr/openemr/assets/7832037/e88c1999-7f0d-4f94-9f2f-146d5d2cafb2">
