### ISSUE TITLE
ALL demo installations are down

### ISSUE THREAD

**Issue by viniciuscb** [openemr/openemr#7045]
I have tried the three installations in the official page and all  installations in the development page.

I want  to test openEMR and also show it to a potential customer.

**Comment by stephenwaite** [comment]
thanks for the report @viniciuscb , just restarted the demos, the main demos will be back up in about an hour hopefully

**Comment by stephenwaite** [comment]
https://demo.openemr.io/openemr/interface/login/login.php?site=default is back up
