### ISSUE TITLE
bug: Billing Manager Date of Service selector not working

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#7069]
### Describe the bug

Date of Service selector not working in the demo.

console error
![image](https://github.com/openemr/openemr/assets/834958/151126d9-89f5-4709-994b-9b5b3ca3e756)

### To Reproduce
Select the date of service selector and select one of the preselects.
![image](https://github.com/openemr/openemr/assets/834958/63ca4080-75c3-4d63-ab35-ddfc3fa80593)

### Expected behavior
If the last year is selected set the dates for the previous year as before.

### Client configuration

- Browser: both chrome an firefox
- OpenEMR version: 7.0.2
- Operating system: Ubuntu or ...

**Comment by juggernautsei** [comment]
After some poking around, we found that there have been major renovations to the generate_select_list. Suppose we replace the function with the previous version. The system works like it is supposed to. Now the task is debugging the function.

**Comment by stephenwaite** [comment]
hi @juggernautsei , looks like need to `attr_js('=')` in https://github.com/openemr/openemr/blob/master/interface/reports/criteria.tab.php#L101

```
'this.options[this.selectedIndex].value,' . attr_js('=') . ',' . attr_js('master_from_date_' . $DateNamePart) . ',' . attr_js('master_to_date_' . $DateNamePart) . ',
