### ISSUE TITLE
[CKEDITOR] Error code: invalid-lts-license-key.

### ISSUE THREAD

**Issue by Vijay-Nirmal** [openemr/openemr#7097]
### Describe the bug

CKEditor is not loading, its just shows an empty test area without any button and other functionality in the page is also not working like "Question Mark", "New Paragraph" buttons.

<img width="871" alt="image" src="https://github.com/openemr/openemr/assets/24755596/5734ae90-0c1a-4937-9889-607b85a46518">

When I checked the console, I could see "[CKEDITOR] Error code: invalid-lts-license-key." error.

<img width="669" alt="image" src="https://github.com/openemr/openemr/assets/24755596/3994b6ee-40d1-4051-874b-76631a5f4c7c">

### To Reproduce
I was also able to reproduce it in a demo instance provided by OpenEMR itself

1. Open/click a field where the data type is "NationNotes"
2. In the dialog/popup, We can only see a plan text area without CKEditor getting loaded
3. Check the browser console to see the error message

### Expected behavior

CKEditor loading properly and showing the format buttons in UI

### Client configuration
Note: I was also able to reproduce it in a demo instance provided by OpenEMR itself

- Browser: Microsoft Edge (Latest version) and Google chrome
- OpenEMR version: 7.0.2
- Operating system: Windows 11 23H2

**Comment by sjpadgett** [comment]
Unfortunately the last stable release of package is v4.22.1 which was EOL version. The normal updating would follow that v4.23.0 would error on install however the editor project administrators know that the free version update to v5.0 is a major effort so decided to capitalize and charge to support ongoing security updates.

For those of you that are capable of running in the command line you may do a simple fix:
- Edit the openemr/package.json and change the `"ckeditor4": "4.23.0",` L-79 to `"ckeditor4": "4.22.1",`
- from command line and inside openemr root run `npm install`
- Delete your browsers cache.
- Log in and enjoy:)

Putting out an update in a patch is doable and unsure when.

**Comment by Vijay-Nirmal** [comment]
@sjpadgett Thanks, it fixed it, I will leave this issue open till the fix rolls out. But feel free to close the issue if you feel otherwise. Again, thanks a lot.

**Comment by sjpadgett** [comment]
@Vijay-Nirmal You're welcome. Thanks for the issue report and we'll leave open for patch reference.

**Comment by stephenwaite** [comment]
keeping open so we don't forget in patch as Jerry recommended

**Comment by bradymiller** [comment]
Good place to place "reminder" on needing to join the zip for this with the patch when we build it would be at:
https://www.open-emr.org/wiki/index.php/Ongoing_7.0.2_Patch_Trail

**Comment by bradymiller** [comment]
btw, a nice way for getting this to work in rel-702 branch (and next patch) without needing to muck with the actual patch would be placing the ckeditor 4.22.1 package in the public/assets/modified/ folder and then redirecting the `ckeditor` token to it in the /config/config.yaml
