### ISSUE TITLE
Twigify Portal Quick Start landing page. Prep for plugin support.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#7116]
Since I'm planning to support various dependency injections, view events and/or various hooks, converting from a PHP template will allow for cleaner implementation and will expose dashboard to existing twig resources.
I plan to use this as an example case for injecting one or two canned plugins until a plugin registration process can be implemented.
Will develop the initial controller, services and location tree as initial backbone to build out.

I think it would be prudent to have a simpler plugin option for items where a full module is overkill.

**Comment by mdsupport** [comment]
> simpler plugin option for items where a full module is overkill

If you want to keep existing code mostly untouched, you can explore approach similar to one posted [here](https://github.com/mdsupport/mdpub/tree/master/oemods/apps). Basic idea is to use globals.php as a proxy for the controller that gets parent-child relationships stored in the dictionary tables for a given script. Component (or plugin in your case) actions on the standard script output are performed in a specific order by plugin object methods before final result is sent to the browser.

Best.

**Comment by sjpadgett** [comment]
Closed per PR. Added events to plugin new dashboard cards.
