### ISSUE TITLE
bug: Unable to share templates in nations note

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#7129]
### Describe the bug

In the nation's note, there used to be the ability to share templates with other users. That feature is broken,
In the first step of sharing the templates, the desired template would be selected and moved from left to right on the screen.
The screen shows a failure in this step.

### To Reproduce

![image](https://github.com/openemr/openemr/assets/834958/fb84bb9c-e626-47e1-aa20-b339a1f2c185)

### Expected behavior

The selected list is to move left to right. 

### Client configuration

- Browser: All
- OpenEMR version: 7.0.2
- Operating system:

**Comment by sjpadgett** [comment]
Wow, NN is almost useless. We need to spend more time testing when making upgrades! There are tens of warnings and several errors.
@juggernautsei Can you give me an ABC of how you're producing this issue?
