### ISSUE TITLE
Some Encounter Menu Items Not Working

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#713]
Splitting #701 to better track

few forms like the history form and the followup form created with xmlformgen are not opening but other forms of xmlformgen are opening well. This might be because, I have grouped the other forms under a category called Examination whereas the history form is sole form under category "history" and followup form is sole form under category "follow Up". Even the Track Anything form kept under category "Track Form" is not opening. See Pic

![Example](https://cloud.githubusercontent.com/assets/1074948/25671448/b692e56a-304d-11e7-9b1e-4fb158cb5a33.jpg)

**Comment by robertdown** [comment]
Hi @arnabnaha, how did you create the top level menu items that are not currently working? Are they all from the xmlformgen?

**Comment by arnabnaha** [comment]
No not all are xmlformgen created. History form, investigation form, follow up form and communication are xmlformgen created. scanned notes, track anything are others. I created these menu items by going to Administration->others-> Forms and then in the forms administration page, by entering the categories.

**Comment by bradymiller** [comment]
hi @arnabnaha ,
Are you still having this issue in most recent codebase?
thanks, -brady

**Comment by bradymiller** [comment]
@arnabnaha ,
Disregard my prior post. I realized this is from code/feature that we reverted from the codebase.
