### ISSUE TITLE
Clinical Rules - required/optional radio buttons, labels and database comment are inverted from logic

### ISSUE THREAD

**Issue by hanksterr7** [openemr/openemr#7158]
When editing a rule filter or target, radiobuttons allow specifying whether the clause is required or optional. The yes/no choices are opposite from what rule logic executes. Similarly, the labels on the Rule Detail page show the same inverted lables. And the field comment in rule_filter table likewise indicates 0 for required and 1 for optional. This too is backwards. I am fixing these labels. No change to saved data or rule logic is needed. Functioning of existing rules will not be affected. This is a purely cosmetic change to the UI. Required touching:
-- interface\super\rules\library\RuleCriteria.php
-- interface\super\rules\controllers\edit\helper\common.php
-- sql\database.sql

Also fixes a bug in interface\super\rules\controllers\edit\view\diagnosis.php which referenced $v_js_includes instead of $GLOBALS['v_js_includes'] in a script tag

**Comment by bradymiller** [comment]
hi @hanksterr7 , Agree with your analysis and plan. If possible, would make this work a separate PR, since likely would get into the codebase very fast.

**Comment by hanksterr7** [comment]
Ok. I removed my changes to clinical_rules.php from the existing PR. The PR now contains just the fixes described in this issue. I have run phpcbf on the files, so I think they will pass the tests and should be ready for merging into the main branch. I will create a new branch for edits to clinical_rules.php. Hope this approach works.
