### ISSUE TITLE
Authentication Error when opening a patient with Open in New Browser Tab checked.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#7167]
### Describe the bug
When you go into the Patient finder, and check the “Open in new browser tab” and click on a patient, you get authentication error in the new tab window. I have tested it this out on the official online demo as well and it happens there too.

Reported on forum.
### Client configuration

- Browser: all
- OpenEMR version: 7.0.2
- Operating system: all

**Comment by stephenwaite** [comment]
nice fix @sjpadgett :cheese: 

thought it used to open the person's dashboard when it's clicked
