### ISSUE TITLE
feat: Hide cards in the patient dashboard

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#7191]
### Describe the problem

Every practice that use OpenEMR is not a primary care physician. It would be nice to be able to turn off the cards that are not needed. 

### Describe the solution you'd like

The ability to turn off these cards
Allergies,
Amendments,
Disclosures,
Labs,
Medical Problems,
Prescriptions,
Vitals

This would clean up the dashboard of cards that are not being used by clinics.

**Comment by mdsupport** [comment]
@juggernautsei For your PR it may be cleaner to have list as 'Dashboard Cards' that uses active status to let you turn on/off a card.

Another simpler approach may be to include a 'X' or 'Hide' option in the common card generation code of the cards. Save the preference in user options to let every user have their customized dashboard. A bonus will be the screen may load faster. As a fallback, include a reset link to revert to standard display.
