### ISSUE TITLE
Move encounter menu to sidebar #711 Bugs

### ISSUE THREAD

**Issue by sharonco-matrix** [openemr/openemr#721]
@bradymiller @robertdown 
This feature brought some bugs into the product:

1. It doesn't support RTL
2. Whenever we are inside a form, clicking on the "delete encounter" displays an error

Thanks
This kind of changes should be taken carefully because they change the way the system looks and it doesn;t work ok with the old layout and all the themes

Maybe use it as an optional change would be better

**Comment by bradymiller** [comment]
@sharonco-matrix ,
Sorry about that. The problem was that the new horizontal menu caused a bug to menu to break the encounter/form in users with too many menu items which was not figured out until it was in the codebase. then Robert scrambled to fix that by moving the menu to the side to fix that issue, however as you have noted, this has also brought with it some bugs. planned to put rtl support in it like we did with the sidebar menu in the Administration->Practice gui.

**Comment by bradymiller** [comment]
@sharonco-matrix ,
1. Brought in your group's rtl fixes. thanks!.
2. I just brought in changes into the other themes to make it look better on them.

**Comment by bradymiller** [comment]
@sharonco-matrix ,
This is going to take awhile to straighten out, so planning to likely revert the encounter gui to its prior form in the official codebase (while we perfect the bootstrap mechanism on a separate branch):
https://github.com/openemr/openemr/pull/724

**Comment by bradymiller** [comment]
I brought in the revert commit(so encounter gui is now back to original gui). It turns out that bringing in bootstrap into the code here is going to be difficult because of huge potential of heterogenous forms that may get touched.

**Comment by sjpadgett** [comment]
@bradymiller If the encounter top nav was wrapped in a container class and the encounter summary is wrapped in a container responsive class then I would think this would solve the nav issue.

**Comment by bradymiller** [comment]
@sjpadgett ,
Main issues for me became:
In the new_form.php, it then brings boostrap into all form edits, which makes all the form styling unpredictable(some are ok and some are messed up and of course there are numerous custom forms used not in the codebase).
In the forms.php, it then brings bootstrap into all the form reports, which is also unpredictable (for example, nation notes, camos and other custom modules not in the codebase).

I don't think a container can "contain" the bootstrap library, but let me know if there is a way to do this (I suppose an iframe would, but avoiding this).

Waiting for some magic by @robertdown

**Comment by robertdown** [comment]
@sjpadgett The biggest issue with the horizontal top nav was some users have many, many top-level menu items and this is causing a serious UX issue. Moving to the vertical menu on the left side is something I should have done from the beginning.

I'm working on a fix for this, unfortunately it is going to take more than an hour or so and we don't want users who deploy production servers off of `master` to lose functionality.

**Comment by sjpadgett** [comment]
@robertdown @bradymiller I haven't looked too closely at the new styling you guys have been doing but I heavily use bootstraps grid and or table styling in all my occupational encounter forms and mostly have been able to get myself out of trouble co-existing with html5 css by overlaying critical styles over top of bootstrap.
Anyway, sounds more complicated than I originally thought. Still, I think I would try if possible to keep the top nav.

**Comment by robertdown** [comment]
@sjpadgett Have you given the new sidebar menu a try? At this point there's no plans on bringing the horizontal nav back (It's currently there until we fix the other issues [hopefully this week])

![screen shot 2017-05-08 at 21 55 35](https://cloud.githubusercontent.com/assets/1381170/25832530/194f2a9e-3439-11e7-89cd-d58b9e453e56.png)

**Comment by sjpadgett** [comment]
@bradymiller Nope, This is the way to go for sure but my concern is for those using left nav. I love the full screen tab and as far as I'm concerned that is the only option that should be available.

**Comment by robertdown** [comment]
I agree that we should eventually drop the left nav menu, but that's a major UI change and needs lots of time to get people comfortable. I think the left nav on the encounter still works with the left nav (Not as good as the tabs view, but it works)

![screen shot 2017-05-09 at 00 04 41](https://cloud.githubusercontent.com/assets/1381170/25835266/536519ca-344b-11e7-872d-912b7fe76a4c.png)

**Comment by robertdown** [comment]
So I came up with a stop gap for now. I've placed an `iframe` in the forms.php page so it is completely separate from the bootstrap stuff. It's not elegant, but it works and it solves the UI issues. @bradymiller I'm working on the `encounter-menu-2` branch, is the RTL stuff on the branch?

Also, if anyone is curious, I screen recorded myself trying to solve the issue. If you're bored and want to waste an hour watching type away check out https://www.youtube.com/watch?v=b3RrpHN2-NI

**Comment by bradymiller** [comment]
nice video!

Placed a review on this here:
https://github.com/openemr/openemr/pull/728

On my testing, I kept wishing to get rid of the side menu when editing forms since there wasn't any useful information there while entering in patient information. But I also agree that this seems the way to go to support infinite form categories; perhaps something simple like minimizing it by default when editing a form would be helpful.

**Comment by sharonco-matrix** [comment]
nice video!
maybe it can be an optional feature like the frames/tabs
