### ISSUE TITLE
bug: 837P service location details are not created when service facility and billing facility differ

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#7213]
### Describe the bug

When creating an encounter with a service facility and a different billing facility. The service facility is not being saved. The facility column in the database is filled with the billing facility number. This causes the incorrect billing. 

### To Reproduce

1. Add a facility and a billing facility
2. Create an encounter
3. Save encounter then look in the forms encounter table. 
4. facility_id_sel is not stored in the facility_id column of the form_encounter table. 

### Expected behavior

Facility to be filled with the service facility number.

![image](https://github.com/openemr/openemr/assets/834958/b9df03b0-c1cf-4b71-aa92-bc5c5186e6cd)

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by stephenwaite** [comment]
hi @juggernautsei , can't reproduce on master, what version are you testing?

**Comment by juggernautsei** [comment]
v7.0.2. I reported it because in the codebase it is the same code. I know that in master things can be fixed that has not made it git.
https://github.com/openemr/openemr/blob/f4f46f287587333a9b60c174f6fcef591eeeef6c/interface/forms/newpatient/save.php#L47

I posted this issue hoping this has been fixed already. I did search for this issue. You tell me.

**Comment by stephenwaite** [comment]
Did you know it's Phil Belford's bday?

![bday](https://github.com/openemr/openemr/assets/5618372/edaa4c6b-821f-4ada-8c5f-274893e95d08)

**Comment by stephenwaite** [comment]
main demo looks okay
![Screenshot from 2024-02-09 14-53-55](https://github.com/openemr/openemr/assets/5618372/41cd9474-7b07-4465-8b8f-2a4396551480)

**Comment by juggernautsei** [comment]
So, why is the code on github wrong? Pull down the release code and it is wrong.

**Comment by stephenwaite** [comment]
hi @juggernautsei , check out this line, https://github.com/openemr/openemr/blob/master/src/Billing/X125010837P.php#L990

it's not very good logic and needs to be improved in master when you get a chance, thank you

**Comment by juggernautsei** [comment]
Thanks @stephenwaite
