### ISSUE TITLE
feat: Allow module writers to add commands to the bin/console command runner

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#7237]
We should allow module writers to add commands to the bin/console command runner by dispatching an event when the command runner grabs the lists of commands to run.  

As part of this work we should deprecate the old command runner since new commands are now leveraging the Symfony console project.  Since we brought in that dependency we should deprecate the old commands since they were built under the assumption of having a primitive command runner framework so we didn't rely on dependencies.

**Comment by sjpadgett** [comment]
May I have an example of a use case please?

**Comment by adunsulag** [comment]
I have a module that needs to run a number of command line scripts.  Instead of having to go into the module directory and run the scripts from inside the directory, it would be better to tie into the existing command line runner in openemr/bin/console.  So you can run something like this:
```
php bin/console billing-cmd:process-import import-filename.txt
```
