### ISSUE TITLE
Billing manager will not pull encounters by insurance company

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#7251]
### Describe the bug

Video done in the demo system.
[Watch a concise reenactment of what the bug here.](https://youtu.be/1rS1Aa7UMSU)

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by stephenwaite** [comment]
Hi @juggernautsei , pretty sure it only works on already billed claims

**Comment by juggernautsei** [comment]
Ok, that is good to know. Then this becomes a feature request and not a bug. I will test. You are right. It works on billed only. Now this is a feature request.
