### ISSUE TITLE
Standardize Buttons

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#727]
Long running issue to standardize all buttons in OpenEMR.

Currently buttons are `<a>` `<button>` and (from what I can see most commonly) `<input>` types.

Goal is to standardize this to `button` (Or `<a>` if there's a good reason)

**Comment by robertdown** [comment]
#730

**Comment by robertdown** [comment]
Breaking up the main PR into more manageable pieces

Areas to do:
- [ ] Calendar
- [ ] Main tabs
- [ ] Deleter
- [ ] Patient file: History
- [ ] Patient file: Transaction
- [ ] Patient file: Summary
- [ ] Usergroup admin
- [ ] Options.inc
- [ ] New Patient: Common
- [ ] Add/Edit Event

**Comment by bradymiller** [comment]
Lets get the opions.inc.php code into codebase now since it won't break anything (at least it shouldn't) and is needed for all the layout(demo,history,transactions,lbf) stuff.

**Comment by bradymiller** [comment]
actually, the one thing to adjust in your options.inc.php is lines 3012/3015. Leave the bootstrap classes there, but also add the css_button_small classes back for now (which can then removed as part of the demographics summary page conversion).

**Comment by bradymiller** [comment]
btw, once you bring in options.inc.php, then the transactions stuff should be ready to come in.

**Comment by bradymiller** [comment]
once you get add/event events, this should be ready with following changes:
bring in assets on line 94 and 991 with the standard header call (place them in array with datetimepicker) since these are now offered as options in the standard header script.

**Comment by robertdown** [comment]
I think leaving `css_button` will have adverse effects. See #785 for the options

**Comment by mdsupport** [comment]
User feedback so far has been less than enthusiastic.  Concerns mainly relate to using layouts designed for narrow, vertical displays used in tabbed, wider settings.  This causes columns appearing to be cramped on left side while showing lot of white space on right side.  For local layout forms it is possible to expand sizes to utilize space more effectively.  Sadly the design precludes that option for built-in forms like Referral.

We also have form titles getting repeated as tab name (in small font) and as huge header directly underneath making the forms look less appealing.

**Comment by robertdown** [comment]
Thanks for the feedback. We are trying to solve the whitespace issue by adding responsive bootstrap classes but it's a tedious process that will take a while to complete.

Also aware of the form titles getting repeated - the form name will be the tab title and we'll likely remove the form title in the actual page
