### ISSUE TITLE
bug: In Visit History, print, or save as PDF, a multi-page list of encounters doesn't print or save all results.

### ISSUE THREAD

**Issue by pete-boyd** [openemr/openemr#7270]
In OpenEMR 7.0.1 (1), in Visit History, for a patient where there are numerous pages of results, Ctrl+P and then either printing, or saving as PDF, in any web browser on Windows or Linux, gives inconsistent results, and never successfully prints or saves the full list of encounters for the patient.

### To Reproduce

Use either "Visit History" icon in the toolbar / banner area or the "Visit History" tab open when a user logs in.

Results per page: ALL

Ctrl+P
Pages: All

A multi-page web page on other web sites works as expected with Ctrl+P.  So it appears to us to be an OpenEMR issue.

**Comment by ruthkonyn** [comment]
I have fixed this problem: i have added a 'print page' button which correctly prints the currently displayed page (which might include documents as well as encounters). 
at the same time i've added the patient's name and dob at the top of the page.
i'm also working on fixing issue #7275 - and so plan to do a PR for both issues at the same time.
