### ISSUE TITLE
billing_note duplication

### ISSUE THREAD

**Issue by surfacehazard** [openemr/openemr#7287]
### Describe the bug

[This PR](https://github.com/openemr/openemr/pull/5843), adds the ability to edit the encounter billing note. However, since the textarea contains both the patient billing note and the encounter billing note, the encounter billing note will be incorrectly appended to and will continue to be duplicated each time the invoice form is saved, due to [this line](https://github.com/openemr/openemr/blob/00aebcde951ccbc13744b97341fe4c012c4eafa8/interface/billing/sl_eob_invoice.php#L435).

**Comment by stephenwaite** [comment]
thanks @surfacehazard !
