### ISSUE TITLE
appointments report total incorrect

### ISSUE THREAD

**Issue by surfacehazard** [openemr/openemr#7289]
### Describe the bug

[This enhancement](https://github.com/openemr/openemr/pull/6547) affects which appointments are included in the appointments report, but does not adjust the total number of appointments reported. While the line item label is "Total number of appointments" and that technically does not change, it is bad form to print a report with e.g. 5 appointments listed and right after that "Total number of appointments: 10".  

Suggest either updating the total depending on the status of "With Cancelled Appointments" or adjusting the label to acknowledge that not all appointments are included.

**Comment by stephenwaite** [comment]
thanks for another bug report @surfacehazard !
