### ISSUE TITLE
HTMLPurifier not able to handle signature in portal documents

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#7299]
### Describe the bug

Adding a signature to a portal document will cause the HTMLPurifier to fail. 

### To Reproduce

![image](https://github.com/openemr/openemr/assets/834958/31820971-12b4-4b69-a6bb-96e030c0eb55)
without signature the document saves.
https://youtu.be/md7YHRD8yg0

1. Create a portal document with a signature
2. Open the document in the portal, sign, and save
3. Open portal review of document and try to save to portal documents.

### Expected behavior
save the document to document portal.

### Client configuration

- Browser: Chrome latest, 
- OpenEMR version: 7.0.2
- Operating system:  Ubuntu 22.04

**Comment by juggernautsei** [comment]
Found this:
https://stackoverflow.com/questions/3837828/how-do-i-allow-images-in-the-htmlpurifier

**Comment by juggernautsei** [comment]
$config->set('HTML.AllowedAttributes', 'src, height, width, alt');

This fixed the error message.

**Comment by adunsulag** [comment]
@bradymiller Are there risks of javascript execution / attacks by allowing the src attribute here? I don't recall if HtmlPurifier will do a strict URL validation on the src attribute or not as the img src tag typically will allow javascript execution and we wouldn't want to allow that attack vector if I'm following this change correctly.

**Comment by juggernautsei** [comment]
HtmlPurifier is a library used to filter and sanitize HTML input to prevent XSS attacks and other security vulnerabilities. While HtmlPurifier can help mitigate some risks associated with allowing JavaScript execution via the `src` attribute, its effectiveness depends on how it's configured and used in the application.

Here's how HtmlPurifier can help mitigate risks:

1. **XSS Attacks**: HtmlPurifier can sanitize HTML input to remove or neutralize potentially malicious JavaScript code, including code injected via the `src` attribute. It can parse and validate URLs to ensure they conform to expected formats and protocols, helping to prevent XSS attacks.

2. **Dynamic Script Loading**: HtmlPurifier can be configured to allow only specific attributes and elements, including whitelisting trusted sources for the `src` attribute. By enforcing strict rules on what HTML elements and attributes are allowed, HtmlPurifier can mitigate the risk of dynamic script loading vulnerabilities.

3. **Script Injection via Data URIs**: HtmlPurifier can be configured to disallow certain types of URI schemes, including data URIs, which can help prevent script injection attacks via data URIs.

4. **Content Spoofing**: HtmlPurifier can detect and neutralize attempts to disguise malicious content as legitimate scripts. By sanitizing and validating HTML input, HtmlPurifier helps ensure that only safe and trusted content is allowed.

5. **CDN Vulnerabilities**: HtmlPurifier does not directly address vulnerabilities related to loading scripts from CDNs. However, it can be used in conjunction with other security measures, such as Content Security Policy (CSP), to mitigate risks associated with CDNs.

While HtmlPurifier can be an effective tool for mitigating many HTML-related security risks, it's essential to use it correctly and keep it updated to address new vulnerabilities and attack vectors. Additionally, HtmlPurifier should be just one component of a comprehensive security strategy that includes other measures like input validation, output encoding, and secure coding practices.

**Comment by juggernautsei** [comment]
To ensure that only trusted sources are allowed for attributes like `src` in HTML elements, you can configure HTMLPurifier to whitelist specific domains or URLs while disallowing others. This helps prevent potentially malicious scripts from being executed from untrusted sources. Here's how you can do it:

```php
require_once '/path/to/HTMLPurifier.auto.php';

$config = HTMLPurifier_Config::createDefault();
$config->set('HTML.Allowed', 'img[src], a[href], iframe[src|width|height], script[src]');

// Allow only specific domains for src attributes
$config->set('URI.HostAllowed', array('trusteddomain.com', 'subdomain.trusteddomain.com'));

$purifier = new HTMLPurifier($config);

$clean_html = $purifier->purify($untrusted_html);
```

In this example:

- We create a default configuration for HTMLPurifier.
- We specify allowed elements and attributes using the `HTML.Allowed` directive, including `src` attributes for various elements.
- We set the `URI.HostAllowed` configuration option to specify a whitelist of trusted domains. Only URLs from these domains will be allowed in `src` attributes. Replace `'trusteddomain.com'` and `'subdomain.trusteddomain.com'` with the domains you trust.

With this configuration, HTMLPurifier will only allow `src` attributes from the specified trusted domains. Any attempts to use `src` attributes pointing to other domains will be sanitized or removed from the output HTML.

Make sure to adjust the list of trusted domains according to your specific requirements and trust relationships. Additionally, keep in mind that while this approach helps mitigate the risk of XSS attacks from untrusted sources, it's essential to use other security measures in conjunction, such as input validation, output encoding, and secure coding practices, for comprehensive security.

**Comment by adunsulag** [comment]
@juggernautsei thanks for the background info (if you are sourcing this stuff from somewhere I'd appreciate the source attribution).  So the question now becomes do we want a hard-coded list of URLs to whitelist against, or is this something we pull from list options or a global setting (with the attendant risks of that being a possible attack vector).  Without the whitelist we wouldn't want to bring the change in.

**Comment by juggernautsei** [comment]
Source is ChatGPT 3.5.

      So the question now becomes do we want a hard-coded list of URLs to whitelist against

I was thinking of dynamically getting the URL of the server and putting it in the 

      // Allow only specific domains for src attributes
      $config->set('URI.HostAllowed', array($_SERVER['REQUEST_URI']));

If there is a sub domain, it should be reflected in the URI. But what do I know. I am just guessing and testing. I am still wet behind the ears.

**Comment by juggernautsei** [comment]
@adunsulag 
What are you thoughts on this bug fix? Where you able to figure something out? This line of code is working well.
 
      $config->set('HTML.Allowed', 'img[src], a[href], iframe[src|width|height], script[src]');

My focus was just on the patient portal. But I see where this HTMLPurifier is used in other places in the system. But I don't know the impact on those areas. Would this fix need to be applied to all uses in the system?

**Comment by sjpadgett** [comment]
Sherwin, If you can actually get this to work, in my experience this purifier is crap, it is a good fix as it must be so we can support signatures! Last time I tried to allow exceptions for style tags purifier was broken.

Only place I know of purifier is used is portal. IMO purifier should only be used for save.

**Comment by juggernautsei** [comment]
@sjpadgett I will test this out this week and update you all here. When you say get this to work. Could you share with me what do you mean by get it to work.

**Comment by sjpadgett** [comment]
> But what do I know. I am just guessing and testing. I am still wet behind the ears.

If I remember correctly signature image src should always be a base64 encoded data URL which purifier should allow by default or has purifier broke it along the way my way of version change. Or Sherwin are you using signature feature in a custom way?

I'll try to look at soon and Sherwin, quit putting yourself down. I think you are doing a fine job my friend!

**Comment by sjpadgett** [comment]
lol you can dry behind one ear if you need permission!

**Comment by juggernautsei** [comment]
@sjpadgett the signatures are not being used in a custom way. This was fresh installation where the error was happening. That is why as @stephenwaite  has taught me to go to the demo site to see if I can reproduce the error. And when I did. I posted this issue page. 
The system was broken by you my friend. Thanks for the vote of confidence in the work produced. I will dry my ears forever more. 
I can tell you that the changes applied are working. The document saves with no issues and no errors are popping up.
Do you want me to post a PR or wait for you to post a PR.

**Comment by sjpadgett** [comment]
> The system was broken by you my friend

I didn't implement purifier.
Put up PR and i'll test...

**Comment by bradymiller** [comment]
> I didn't implement purifier.
That would be me :)
That is odd though. I thought I already broke this feature in past by implementing the purifier, which @sjpadgett then graciously fixed it up to work. Purifier trials and tribulations never ends I guess :)

**Comment by juggernautsei** [comment]
Thanks @bradymiller. I understand the purpose of the purifier. I will get the PR posted as soon as I can today.

**Comment by juggernautsei** [comment]
Outdated???
