### ISSUE TITLE
bug: Typecasting: Uncaught TypeError: Unsupported operand types: string + int.

### ISSUE THREAD

**Issue by growlingflea** [openemr/openemr#7304]
### Describe the bug
There are over 103+ occurrences of incorrect type casting where code like $var = $_POST['var'] + 0 exists. This poses an
issue because if a blank string is passed or if by accident a number is passed as a string is added to the integer 0 it will throw a fatal error. This has mostly gone unnoticed because a lot of the times this is happening, only integers are used.  This is a problem because its sloppy coding and can cause fatal errors in some occasions. 

### To Reproduce
Examples of code:
![image](https://github.com/openemr/openemr/assets/8116478/d0f04518-f19b-478a-8614-bd6d45f6d3aa)

PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string + int

Solution: remove the + 0 and typecast the variables

**Comment by growlingflea** [comment]
If a new developer who wants to make a contribution want to fix this, here is a recommended fix.  If i don't see any activity on this in 48 hours I'll go ahead and fix all the occurrences myself.  An example of the proposed fix is below:

![image](https://github.com/openemr/openemr/assets/8116478/67cdf700-6dd0-41fe-9c38-8e4621e95174)

**Comment by gsvn32** [comment]
Hey,  I'm new here and want to take a shot at this issue. I see that most of the variables with this issue are ended with a '+ 0'. 
is this redundant addition necessary?
