### ISSUE TITLE
Select list default selection of generated item

### ISSUE THREAD

**Issue by surfacehazard** [openemr/openemr#7308]
### Describe the bug

[This PR](https://github.com/openemr/openemr/pull/6659), specifically [this line](https://github.com/openemr/openemr/blob/328c15608c3c84fcd9e7d1ac7a3973ff9b311466/library/options.inc.php#L183) changes prior behavior by selecting the first item in a list by default. This creates havoc with multiple-select lists where a generated "Unassigned" option should not be selected by default.

### To Reproduce
1. Edit Demographics->Choices
2. Select a different Patient Categories option, e.g. "Group III"
3. Save
4. Edit Demographics->Choices
5. Check which Patient Categories option(s) are selected.

**Comment by adunsulag** [comment]
Just ran into this same problem while attempting to run Inferno API testing.  Here some screenshots
![image](https://github.com/user-attachments/assets/28c42b85-c208-422a-b09b-d0fcea2bf928)

Here is the read view of the data showing that Unassigned should not be selected.
![image](https://github.com/user-attachments/assets/6e469520-39a3-4251-becc-819640ad6b1f)

Thought it was a new issue but seeing that @surfacehazard reported this in March!
