### ISSUE TITLE
bug: saving existing insurance with no country in address

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#7331]
### Describe the bug

should be able to save an insurance without choosing the country of the subscriber
country is not required for billing in the u.s.

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/openemr) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/openemr/openemr/issues/7331">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/openemr/openemr/issues/7331/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/openemr/openemr/issues/7331/pledge.svg">
</picture>
</a>

**Comment by adunsulag** [comment]
You can pledge behind and help support this effort using Polar.sh


<a href="https://polar.sh/openemr/openemr/issues/7331">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/openemr/openemr/issues/7331/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/openemr/openemr/issues/7331/pledge.svg">
</picture>
</a>

**Comment by adunsulag** [comment]
Thank you @stephenwaite for contributing to close this issue! ⭐

The rewards from this issue, totalling $20, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._
