### ISSUE TITLE
bug: Inadequate time format in logs

### ISSUE THREAD

**Issue by manoj-ayyappan** [openemr/openemr#7335]
### Describe the bug
ASVS 7.1.4 (Verify that each log event includes necessary information that would allow for a detailed investigation of the timeline when an event happens)
The OpenEMR logs events into the system which are sorted in order by date and time. The time is displayed in the format Hours:Minutes which is insufficient for tracking the timeline in which events happen. It should be changed to Hours:Minutes:Seconds

### To Reproduce
1. Login to OpenEMR using correct credentials
2. Navigate to Admin --> System --> Logs
3. Click on Submit button

![image](https://github.com/openemr/openemr/assets/55644854/4ba7eee0-400b-46ce-aa76-5d3ffa1a326c)

### Expected behavior
The Logs are displayed in the format Hours:Minutes

### Client configuration

- Browser: Arc Version 1.37.0 (48361) Chromium Engine Version 123.0.6312.106
- OpenEMR version: v7.0.2
- Operating system: MacOS

**Comment by stephenwaite** [comment]
nice @manoj-ayyappan ! 

can you edit the issue title to be `bug: Inadequate time format in logs` please?

**Comment by manoj-ayyappan** [comment]
The issue and fix titles are now changed as suggested.
