### ISSUE TITLE
Negative Amount Allowed in Batch Payment Section

### ISSUE THREAD

**Issue by sagar110599** [openemr/openemr#7363]
### Describe the bug
As a admin we are able to create batch payment record having negative amount value.

### To Reproduce

1) Open the openemr website and login as admin
2) Hover over the "patient" tab at top and select the "new/search" option.
3) Once the new tab opens, create a new patient by specifying the required details.
4) Once the patient is created, schedule a visit for him by going to patients tab > visits >
create visit. Enter the necessary details in the form.
5) Now go to the fees tab and select payment and a new tab will open asking for payment
details.
6) Select any method for payment method.
7) Scrolling down the page there is an input box asking for payment amount.
8) Entering a negative amount is possible in this input box and later when it is submitted
the invoice reflects that the user has paid a negative amount

### Expected behavior

Negative amount check should be done both on UI and Backend

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by sunsetsystems** [comment]
A negative payment might be a refund or otherwise needed as a correction. I'm pretty sure it is allowed on purpose.

**Comment by adunsulag** [comment]
@sunsetsystems Good to hear from you :) I agree, closing this issue.
