### ISSUE TITLE
Password strength meter missing

### ISSUE THREAD

**Issue by Kashika08** [openemr/openemr#7366]
### Describe the problem

According to ASVS 2.1.8 there should be a password strength meter provided to help users set a stronger password which is missing in the application. This may be a security threat.

### Describe the solution you'd like

According to the ASVS, when a user is setting their password, a password strength meter should be provided.

**Comment by adunsulag** [comment]
@Kashika08 are you planning on building this feature?  Its useful but its not currently on our development roadmap.

**Comment by Kashika08** [comment]
> @Kashika08 are you planning on building this feature? Its useful but its not currently on our development roadmap.

I have already raised a pull request with this feature implemented. Here's a link to the same: https://github.com/openemr/openemr/pull/7367
