### ISSUE TITLE
Move local storage to CouchDB

### ISSUE THREAD

**Issue by usama-kabel** [openemr/openemr#7381]
My responsibility involves bolstering stability and eliminating any potential single points of failure. Upon identifying that the primary issue lies in storing documents on local hard disks during redundancy or high availability setups, I began exploring whether CouchDB could facilitate achieving stability and reliability. Now, I'm seeking guidance on migrating all local documents to CouchDB.

**Comment by adunsulag** [comment]
You can search or post your question on our community forum here: https://community.open-emr.org/  We don't use our issues tracker for general questions.
