### ISSUE TITLE
bug: User Admin screen 	Google Email for Login does not save when creating new user

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#7393]
### Describe the bug
If you navigate to the Admin Users screen and attempt to add a new user with an email address and save the user, the email address does not display when you go back to edit the user.  If you edit an existing user the email address saves.

- Browser:
- OpenEMR version: development release (7.0.2+)
- Operating system: Ubuntu Linux 22.04

**Comment by sjpadgett** [comment]
@AlceaDev Sure just make sure to recreate first or check change log as this could have been fix and issue not closed.
I'll assign to you and be sure to reference this issue in your PR if you do one.
