### ISSUE TITLE
Fatal error C_Document.class.php 

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#7401]
@juggernautsei Need to address!

### Describe the bug
[23-Apr-2024 14:38:39 America/New_York] PHP Fatal error:  Uncaught Error: Call to a member function dispatch() on null in C:\xampp\htdocs\openemr\controllers\C_Document.class.php:807
Stack trace:
#0 C:\xampp\htdocs\openemr\library\classes\Controller.class.php(157): C_Document->retrieve_action('2', -1, false, true, false, true, 'patient_picture')
#1 C:\xampp\htdocs\openemr\controller.php(6): Controller->act(Array)
#2 {main}
  thrown in C:\xampp\htdocs\openemr\controllers\C_Document.class.php on line 807

### To Reproduce
Any document retrieve that fires retrieve offsite event.

**Comment by juggernautsei** [comment]
@sjpadgett when @adunsulag changed this section. It took away the protection that was built. 
I questioned Stephen about !empty($updatedOffsiteDocumentEvent). Why is it needed. 
Change this
 
     if (!empty($updatedOffsiteDocumentEvent) && $updatedOffsiteDocumentEvent->getOffsiteUrl())

to this

     if (!empty($updatedOffsiteDocumentEvent->getOffsiteUrl())) <- This should be a string value

If no URL is returned, the system has a locally stored document.  Then the remoted document call will be skipped.

**Comment by sjpadgett** [comment]
> if (!empty($updatedOffsiteDocumentEvent) && $updatedOffsiteDocumentEvent->getOffsiteUrl())

No clue where you got this.
Error occurs in this section
```
//fire a remote call to see if the file is stored somewhere else
      $s3Key = explode("//", $temp_url); //split the url to get the s3 key
      $retrieveOffsiteDocument = new PatientRetrieveOffsiteDocument("/" . $s3Key[1]);
      ** offender => ** $this->eventDispatcher->dispatch($retrieveOffsiteDocument, PatientRetrieveOffsiteDocument::REMOTE_DOCUMENT_LOCATION);
      //this is for the s3 bucket module. If the file is not found locally, it will be found remotely
      if ($retrieveOffsiteDocument->getOffsiteUrl() != null) {
          header('Content-Description: File Transfer');
          header("Location: " . $retrieveOffsiteDocument->getOffsiteUrl());
          exit;
      }

```

**Comment by juggernautsei** [comment]
@sjpadgett that code got removed by @adunsulag.

**Comment by sjpadgett** [comment]
addressed by others
