### ISSUE TITLE
Encounter Report not working properly

### ISSUE THREAD

**Issue by vasc0x** [openemr/openemr#742]
When using the reports from Reports->Visits->Encounters (/interface/reports/encounters_report.php), it does not find, or at least it doesn't show, any e-signed form or encounter. All possible combinations tried. Multiple forms are e-signed. Tried also a wide date range, in-and-out of an encounter, to no avail.
Also just found that it shows both e-signed and not e-signed forms when searching for "Not E-signed".

Version Number: v5.0.1-dev

See pictures. 

I echoed the query trying to make sense of it.

![image](https://cloud.githubusercontent.com/assets/4543801/26027490/9f7e7402-37dc-11e7-895b-76f2dad01197.png)

![image](https://cloud.githubusercontent.com/assets/4543801/26027499/ceeda03c-37dc-11e7-9a9e-87456d4e1d7d.png)

![image](https://cloud.githubusercontent.com/assets/4543801/26027524/5011a640-37dd-11e7-8159-45236df705f1.png)

**Comment by bradymiller** [comment]
Hi @vasc0x ,

Thanks for the detailed report.

I was unable to confirm this bug. I created an encounter, then a SOAP form note, which I then esigned. In the encounter report, I was then(toggled on Detailed for all tests):
1. Able to see it if not toggled anything
2. Not able to see if it toggled on 'Not esigned'
3. Able to see it if toggled on 'Forms esigned'

Couple quick things:
try change to date to 2017-05-14
ensure esign is turned on in Administration->Globals->Esign->Allows E-Signing Individual Forms

First, can you try it out on the online development demo to see if can reproduce your issue?
http://www.open-emr.org/wiki/index.php/Development_Demo#Daily_Build_Development_Demo

**Comment by vasc0x** [comment]
Good day Brady.

Thanks for your reply.

I tried your suggestions both on my local and the daily demo server and they still don't work. At least as I think they should, which might be wrong of course. See the images below from the daily demo as you suggested. You can see that there are two forms e-signed and locked, and two other plus the encounter not signed.

When I select on the report the e-signed forms, it shows all the forms except the encounter, even the not signed ones.

When I select not e-signed, nothing shows.

I've been tampering on my local copy with the SQL statements for the queries but haven't had much luck yet. However, if I run my own queries directly on the db, I can get the result expected. I'm not sure if this would help at all, but here it is:

This is the query I can run on phpmyadmin that shows me the signed forms:

`SELECT forms.form_name, forms.user FROM esign_signatures LEFT JOIN forms ON esign_signatures.tid = forms.tid`

The following gives me the unsigned forms:

`SELECT forms.form_name, forms.user FROM forms WHERE forms.id NOT IN (SELECT tid FROM esign_signatures)`

Please note that I'm only selecting a few fields just to proof the concept. I think that a LEFT JOIN would not work when finding the unsigned forms, but again, I know very little SQL.

I'll keep working on it.

Thanks again!

![image](https://cloud.githubusercontent.com/assets/4543801/26034511/be5206be-388b-11e7-9d3b-e6960c369dfe.png)

![image](https://cloud.githubusercontent.com/assets/4543801/26034515/d996a560-388b-11e7-88d4-123f476de83f.png)

![image](https://cloud.githubusercontent.com/assets/4543801/26034526/efc7c53a-388b-11e7-87de-30a3e4fa489b.png)

![image](https://cloud.githubusercontent.com/assets/4543801/26034536/0185c9d4-388c-11e7-9052-23dba57cb28e.png)

![image](https://cloud.githubusercontent.com/assets/4543801/26034544/3441459c-388c-11e7-8457-53860cda7e48.png)

**Comment by bradymiller** [comment]
Hi @vasc0x ,

I think the issue here is that this is at the Encounter level(Meaning there is just a row for each encounter and does not create a row for specific forms) and is all or nothing.

So it only shows Forms Esigned if ALL of the forms in the encounter are signed.

And it shows Not Esigned if there is AT LEAST 1 form that is not signed in an encounter.

And the listing in the Form columns shows all the forms in an encounter (it doesn't care whether they are signed or not).

-brady

**Comment by vasc0x** [comment]
Ok.

So I guess that what I want is pretty much a customization.

Thanks again Brady.

**Comment by bradymiller** [comment]
@vasc0x ,

It seems like what you are expecting would make more sense on this report(if select Forms Esigned, then show all encounters with at least 1 esigned formed and show them in the Forms; and vice versa for the Not Esigned); would also be nice, if were able to click on the encounter in the report which would then open up the selected patient/encounter.

For folks that are used to the old way it reports, could change 'Forms Esigned' to 'All Forms Esigned'
and change 'Not Esigned' to 'All Forms Not Esigned' and keep the old options then. And then could add the more granular options to be 'Forms Esigned' and 'Forms Not Esigned' options.

If your willing to work on any of this stuff, it would be nice to get it into the codebase :)
-brady

**Comment by vasc0x** [comment]
Great ideas! Sounds like a plan then.
