### ISSUE TITLE
bug: Prior Authorizations Report Error.

### ISSUE THREAD

**Issue by luisuriarte** [openemr/openemr#7461]
Fatal error: Uncaught Error: Failed opening required '/var/www/localhost/htdocs/openemr/interface/modules/custom_modules/oe-module-prior-authorizations/public/vendor/autoload.php' (include_path='/var/www/localhost/htdocs/openemr/vendor/pear/archive_tar:/var/www/localhost/htdocs/openemr/vendor/pear/console_getopt:/var/www/localhost/htdocs/openemr/vendor/pear/pear-core-minimal/src:/var/www/localhost/htdocs/openemr/vendor/pear/pear_exception:.:') in /var/www/localhost/htdocs/openemr/interface/modules/custom_modules/oe-module-prior-authorizations/public/reports/list_report.php:14 Stack trace: #0 {main} thrown in /var/www/localhost/htdocs/openemr/interface/modules/custom_modules/oe-module-prior-authorizations/public/reports/list_report.php on line 14.
This is at https://demo.openemr.io/openemr/ (module enabled).
To solve the error, you must change the line in openemr/interface/modules/custom_modules/oe-module-prior-authorizations/public/reports/list_report.php: require_once dirname(__FILE__, 2) . '/vendor/autoload.php'; to __FILE__,3.
After correcting that error on my server, another table does not exist (the module is installed and active):
Prior Auths
SQL Statement failed on preparation: SELECT `ps`.`status` FROM `patient_status` ps WHERE `ps`.`pid` = ? ORDER BY `ps`.`statusId` DESC'
Query Error
ERROR: query failed: SELECT `ps`.`status` FROM `patient_status` ps WHERE `ps`.`pid` = ? ORDER BY `ps`.`statusId` DESC

Error: Table 'openemr.patient_status' doesn't exist

Openemr Version 7.0.2 (1)

**Comment by adunsulag** [comment]
@juggernautsei when you get a chance can you investigate this?  Thank you.

**Comment by juggernautsei** [comment]
@adunsulag I will today
