### ISSUE TITLE
Demo site is down!

### ISSUE THREAD

**Issue by jujes** [openemr/openemr#748]
OpenEMR 5.0.0 Demo Links

Main Demo:
OpenEMR: http://demo.open-emr.org:2105/openemr
Wordpress Patient Portal: http://demo.open-emr.org:2105/wordpress
Onsite Patient Portal: http://demo.open-emr.org:2105/openemr/patients
PHP log file: http://demo.open-emr.org:2105/log/logPhp.txt
Setup log file: http://demo.open-emr.org:2105/log/logSetup.txt

**Comment by robertdown** [comment]
Interesting, I see some errors in the log but I'm able to reach all of the demo links

**Comment by bradymiller** [comment]
The demo likely did a reset an hour or so after @jujes  post, which is why it is now working.
@jujes , can you confirm that the demo is now working for you?
thanks, -brady

**Comment by jujes** [comment]
Yes, it's working for me.
Thanks
