### ISSUE TITLE
Fax: 400 bad request response from 

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#7508]
### Describe the bug

Trying to send fax to ether fax. 

### To Reproduce

![thumbnail_image](https://github.com/openemr/openemr/assets/834958/2f4f441a-a06d-4863-8be4-3f1ba2adb8e3)

1. Add a '....'

### Expected behavior
Sending an encrypted fax.

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

**Comment by adunsulag** [comment]
@juggernautsei Are you planning on fixing this because otherwise there is not enough details here in the bug report to have any idea of how to fix / reproduce this problem.
