### ISSUE TITLE
Editing Facility Breaks Out of Tabs

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#752]
Upon editing a facility, clicking save correctly returns to the Facility list page, but it doesn't apply it to the iframe, it changes the entire window.

Occurs on the `bootstrap-facility-page` branch, not on master.

This is a fancybox issue - I'll fix it.

**Comment by bradymiller** [comment]
Where's the bootstrap-facility-page branch?

**Comment by robertdown** [comment]
https://github.com/robertdown/openemr/tree/bootstrap-facility-page

**Comment by stephenwaite** [comment]
looks like this has been fixed since unable to reproduce

**Comment by bradymiller** [comment]
I don't think this code every got into the codebase?? @robertdown , do we need to keep this issue open?

**Comment by robertdown** [comment]
Hmmm, I'll look into it
