### ISSUE TITLE
bug: Lab Core Procedure Manual eReq breaks due to PHP8 date issue if date_collected is not filled in

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#7526]
If you attempt to use the manual eReq button when doing a labcorp procedure order the pdf fails to generate if you don't put in a date_collected.  Since the date_collected are an empty string the php date functions blow up.

![image](https://github.com/openemr/openemr/assets/228117/ce107d0e-2086-4c84-9038-c2be14d66405)

**Comment by sjpadgett** [comment]
Why aren't we a busy bee today, my goodness!
Recommend add directory creation for all the hl7 generators. I think we're up to three of them.
I started this but you beat me to it!

**Comment by adunsulag** [comment]
@sjpadgett Just have a backlog of issues that we fixed for Pete's group that I'm bringing back into core.

**Comment by sjpadgett** [comment]
Yeah for use mere mortals!:) Kidding of course but yeah for openemr core....
