### ISSUE TITLE
CKEditor4 now throwing security popup

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#7540]
### Describe the bug
Very annoying! 
From forum see https://community.open-emr.org/t/ckeditor-security-warning/22891
![c4fe0c5b09951566e915f1b4a28070d36fe27841](https://github.com/openemr/openemr/assets/1859985/26ec5352-eec1-4d7e-b61f-7a8ec0c25f27)

**Comment by bradymiller** [comment]
![angry-villagers](https://github.com/openemr/openemr/assets/278968/7804f700-6111-45b0-8411-8f916ee8d764)
