### ISSUE TITLE
Billing Manager showing unassigned

### ISSUE THREAD

**Issue by juggernautsei** [openemr/openemr#7553]
### Describe the bug

The billing manager is randomly showing unassigned for the x12 partner. 

### To Reproduce
![image](https://github.com/openemr/openemr/assets/834958/a2040170-62bc-42e5-b308-53a3d996130f)

1. Select any date range
2. Update list
3. Review list
4. Find randomly unassigned partners

### Expected behavior
We have made sure that all of the insurance companies have assigned partners. It was that way before adding patch 1 and the addendum after adding those two patches. The system randomly shows unassigned. Inspecting the code, It looks like the display should be Partner not configured rather than Unassigned. 
![image](https://github.com/openemr/openemr/assets/834958/a66667d2-88fa-41e5-ab80-8574e20778de)

### Client configuration

- Browser: Firefox
- OpenEMR version: 7.0.2 (1)
- Operating system: Ubuntu 22.04

**Comment by stephenwaite** [comment]
Hi @juggernautsei, the hot patch on the forum has a bug. Grab the latest script for interface/billing/billing_report.php
