### ISSUE TITLE
bug: Update API_README.md - change documentation everywhere it says Globals to use the word Config

### ISSUE THREAD

**Issue by AshutoshBhawasinka** [openemr/openemr#7631]
### Describe the bug

The documentations state to enable API from "Administration->Globals->Connectors->"Enable OpenEMR Standard REST API", but there is no such menu option. 

### To Reproduce
![image](https://github.com/user-attachments/assets/4c55623a-5217-4c11-a25f-e9d58a1b8b2d)

### Expected behavior

Documentation stating how and where to enable the APIs

### Client configuration

- Browser:
- OpenEMR version: 7.0.2 (1)
- Operating system: Running in Docker container

**Comment by adunsulag** [comment]
Documentation needs to be updated.  Globals was changed to be 'Config'

**Comment by LeoSantich** [comment]
Does this issue still need worked on?  I'd love to help if so.

**Comment by LeoSantich** [comment]
Hello, does this issue still need worked on?  Does the documentation still need to be updated.
