### ISSUE TITLE
Update FHIR LForms to latest version v36.3.3 and restyle form rendering.

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#7666]
### Describe the problem
It's time to update. Fixed issue with race condition on some forms
Form render styling update for font style and size and add theme for dark and light.

**Comment by sjpadgett** [comment]
Still needs some work
Dark:

![image](https://github.com/user-attachments/assets/68f6eefa-f72d-4bb2-a644-6f691fe7fa82)

Light:

![image](https://github.com/user-attachments/assets/9f464e30-d19a-4659-9f62-086121211c6c)

combo:

![image](https://github.com/user-attachments/assets/892e850d-b503-46ab-a86f-741c683c27d7)

![image](https://github.com/user-attachments/assets/afc7e05a-4eb5-4b6f-96f6-9068b6f0d440)

**Comment by sjpadgett** [comment]
Final on theme for questionnaires. Currently I have an auto select dark or light in both portal and encounters. 
I've restyled the forms to be easier to read not to mention updating lforms project version to latest 36.3.3 that includes numerous performance fixes.
I plan to turn on that questionnaire must be complete before submit for review but allow save a draft  in any state.
I'm considering expanding the forms to be fluid 100 percent width in encounters. I could use some feedback on this.
For example: current container-xl

![image](https://github.com/user-attachments/assets/1727f1ee-0f39-4a3f-9303-cdc5cd2b1507)

New: container-fluid

![image](https://github.com/user-attachments/assets/66d95f8b-9fee-49be-9ba1-a071ac06837a)

Dark full: kind of nice for us that like dark

![image](https://github.com/user-attachments/assets/adc7bd1d-5961-4356-9f12-8f1b699a550a)

@ruthkonyn Do you want to add anything or test for me after my PR goes up.

**Comment by ruthkonyn** [comment]
hi @sjpadgett  - our team are looking at this to give you any feedback on the proposed changes, but meanwhile i'm happy to help you test. I see you've done the PR, so do let me know how i can help with the testing...

**Comment by ruthkonyn** [comment]
hi @sjpadgett - yes, the new formatting looks great!! 

Can i just check one thing - i notice the questions are all in bold - one can set that via the NLM form builder/the json file - and I assume that's what you've done here rather than set it in the rendering code?

**Comment by sjpadgett** [comment]
@ruthkonyn You can pull this branch from my openemr repo https://github.com/sjpadgett/openemr/tree/Questionnairs_and_LForms
and treat it the same as you do the openemr repo or I have this branch on the GAMMA dev demo where you can test https://four.openemr.io/b/openemr/interface/login/login.php?site=default . Be aware it resets every night for updates. You'll most likely have to import a questionnaire to test with unless I've already imported one for that day.

I'm using the styles.css in lforms webcomponents directory if you want to play with it. I override any stylings concerning fonts in styles to keep all forms consistent regardless of SDC or builder style requirement. Of course we can debate this if you feel strongly about.
My eyesight is getting very poor and I need others feedback to keep me honest so thanks for taking the time.

**Comment by ruthkonyn** [comment]
thanks, have started to play... - i'm starting by comparing one of our more complex questionnaires with how it looks on the dev demo... Is this the best forum for feeding back?

at some point yes, lets debate the styles issue - i understand the merits of keeping all forms consistent - but i also understand why we have designed questionnaires to our own specs - so my position would be to allow questionnaire developers to specify styles if they wish - perhaps yet another configuration option? - or would this be very difficult to code? 

yes - my eyesight's also getting worse and worse!! - so very happy to help :-) .

**Comment by ruthkonyn** [comment]
ah, good stuff on the syle issue. probably best place to have the flag is where one is importing the questionnaire - seems logical to me - in the template management section.

the first thing that strikes me is that where a question has 'boolean' format, currently this is a slider but in the new one it's displaying as a set of choices (yes, no,  not answered)  In the questionnaire i'm testing (CRISP)  I've used this to open up a set of questions, so if it's not going to be a slider then i'd probably set up choices with my own text.

are the overall formats configurable yet - i.e. light/dark - fluid/full, i do like the look of these - and if so which tab of config?
I haven't unearthed any bugs per se as yet, but a few more things to try out..

the questionnaire i'm playing with at the moment is in the following json file, it lacks compulsary questions, so i'll have to add those... 
[CRISP.R4.json](https://github.com/user-attachments/files/16616891/CRISP.R4.json)

'fraid i need some supper - so may not do much more testing today...

**Comment by ruthkonyn** [comment]
i started to edit CIRSP, then pressed 'summary' and in the summary clicked to edit the same questionnaire again. A second one appeared 
![Screenshot from 2024-08-14 19-37-29](https://github.com/user-attachments/assets/58f4e69f-ecd1-4170-a5bd-5912be8b4d6e)

which ever one i 'saved' overwrote what was there already, and left the other one to be saved and overwrite.

this behaviour is there in 7.0.3-dev, so it's not something introduced in this PR, but it strikes me as poor behaviour, if not a downright bug - too easy to loose a whole set of questions. Is it possible to refuse to open a questionnair for editting if it's already  open?

**Comment by ruthkonyn** [comment]
this is on GAMMA - the Peer INitial Assessment form - i filled in the first section to see how the score would work, and the summary appeared with the score in the wrong place - have tested in 7.0.3-dev
![Screenshot from 2024-08-14 19-59-40](https://github.com/user-attachments/assets/efb515f7-6baa-4bd9-ab45-8bfdffce3e6c)

**Comment by ruthkonyn** [comment]
another  thing that strikes me with that very long questionnaire, is that one has to scroll a long way down to reach the 'save/cancel' buttons - this is purely wish list - but would it be possible to have those buttons at the top as well, possibly configurable. I know our users like this, and i think it's been implemented for some forms  - in the config -> appearance there's now a selection 'Form ActionBar (save, cancel, etc) position' which can be 'top' or 'bottom' - but i'm not sure which places it's used. And for such a long form i'd prefer an extra option of 'both'

**Comment by sjpadgett** [comment]
It used to be normal encounter behavior to only allow one instant of a form. I know because I introduced it a couple years ago. Then and again, my memory may fail me!:) I'm not sure I want to start down the road of fixing other items as I'm on mission here.
The reason I want to get the overall questionnaire feature running solid is my ultimate plan has always been to integrate with CDR and add some smarts to help diagnose and/or plan care.  Otherwise too me the feature is somewhat useless to the patient in the end. Afterall, isn't that why we donate our time?

This has been a long road for me to get to this point and have found a few folks like yourself along the way that have embraced and made useful the feature despite it's limited features.
So to achieve a useful integration with CDR and AI ML we must ensure the forms are spot on so users and patients will complete the forms. To this end, I'm going to implement in the portal only that the forms must be completed before patient is allowed to submit for review. However the patient will still be allowed to save as a draft if wanting to complete later. While I have improved form status there are some further improvements coming.

While I'm extremely pleased with all the useability improvements @adunsulag made to the portal, we need to follow up with portal core feature fixes and improvements for useability. So this is the reason I'm giving you a small rant here so you know and can be thinking about my direction and thus this PR to start.

Concerning the reports; I saw it has been broken or does not present well and I will be rewriting that code. I think somehow I may have broken it because I though it was working well and was acceptable to a professor in pain studies. Either way I will address.

I believe Stephen put the action items positioning in config and agree with why it's needed. I'm unsure how I'll address in our use case but address it I will.

I don't understand what my style changes has to do with breaking your form but it must be addressed and is top on my list.

For theme changes between light and dark, it is automatic where if the dark theme is selected as the overall app theme then so will the lforms. Otherwise light is default for all other themes. I don't see a need for an option.

Speaking of options, I plan to have a button to turn on guidelines in the forms. While I think they are ugly they are useful for some forms that have nesting. This will be something the patient can toggle if it aids them in completing the form.

In my new module for CDR, CDS, assessments and questionnaires in general I plan to have a config form. I thought about creating one for the portal that can be more extensive than globals config. We still need to config when, who and how providers interact with portal and adjust our workflows. Normally an LPN, RN or PA would look at any secure messages or other portal items and address ones that they can or forward to the provider the stuff requiring them to intervene. We're somewhat there as I've put in, in the past things like are they a portal provider in Users. At any rate you can see how important I feel patient templates, scheduling and form follow-ups are to me.

Hopefully you are able to pull my branch so you don't have to wait for GAMMA reset every day to see my changes but I will try to get some of your concerns done today so they are available tomorrow.

Again thanks for the help as not only does it help me to have another opinion, it also make the work more enjoyable, for me at least.

**Comment by sjpadgett** [comment]
@ruthkonyn Unfortunately in version 33.3.0(next version from current!) they changed the boolean actions, for what in my mine is senseless to support a no answer concept. From change log:


## [33.3.0] 2023-01-23
### Changed
- Changed the design of the boolean component. It's now rendered as 3 radio buttons
  to support the concept of "no answer".
### Added
- Added the support of enableWhen on string, integer, date and time typed items that
  have an answer list.


Now I could maintain a separate repo for this angular app and customize to openemrs needs but that is just another project we'd(admins) have to compile and maintain. While other admins are perfectly capable of doing this, it wouldn't be right for me to force it on them and I'd need their permission if they'd want to maintain throughout it's lifecycle.
I think it is a bummer where they simply could have just added an additional data type instead of breaking legacy.

**Comment by sjpadgett** [comment]
Hi ruth,
I added some more styles and setup style sheets to be selectable on form entry once I add flag to dashboard import.
I toned down bold use.
I added a button to toggle form guidelines and added save to top of form. I still have work to do here but you'll get the idea.
Changes should be on GAMMA.

**Comment by ruthkonyn** [comment]
hi jerry,
thank you for all your explanations, and rants, i have much better idea of where  you are coming from.

wrt boolean rendering, i agree that it's better to go with what the standard now does, even though i think we both agree it's not so useful, rather than have something customised for OpenEMR that then has to be maintained - i'll look at other options for our forms. 

thanks for the changes - i'm really sorry to say i don't think i'm going to be able to look at them until i get back from my holiday (on the lovely north Norfolk coast) next wednesday - i had a busy morning and then had a tooth extracted and it's left me feeling a bit tired and achey and not able to concentrate- _and_ I still have to pack!!

having written that, curiosity got to me and I have tried out CRISP and a new health status form (below), on GAMMA (it was easier than getting my head round running your code as a branch on my machine - not done that before - do i just make a new branch locally and then replace all the (master) code in that branch with your downloaded branch? or, as i use docker, should i set up a new set of containers with your code? or is there a simpler way) 

this new one has mandatory fields, and i like the hint that the field is mandatory. When i tried out 'Toggle Guides' i got an error message:
![Screenshot from 2024-08-15 17-40-22](https://github.com/user-attachments/assets/a2bb2fcc-77e3-44df-ad33-58841480c0b2)
having said this, i don't know what guidelines are, or how to set them up?

Thanks for save buttons at top and bottom, that'll be useful

i presume you haven't added the flag to the dashboard input yet, for styles - or if so i wasn't sure where to look. 

with the new  'health status questionnaire' that I tried - because it has mandatory fields -  i'd added a field at the foot of the form that simply contains the version of the form, in small orange characters. This line is intended as information only, and should not have a data entry box, so not sure what's caused this change. This questionnaire is in the following file
[IPO-HSQ.test.R4.json](https://github.com/user-attachments/files/16627719/IPO-HSQ.test.R4.json)

also when i tried out the hints, aka instruction, with the CRISP form, the formatting isn't quite right - it's gone black on grey which is a little difficult to read
![Screenshot from 2024-08-15 18-00-06](https://github.com/user-attachments/assets/97a69469-aa1b-45d3-970c-4eecf5d08264)

but it's looking good, and thanks for all your work on this. And i'm enjoying working with you on this as well!! That's it till next week now i'm afraid -i'll be checking emails sporadically but i'm not taking a computer with me, so won't be able to use any systems.

**Comment by sjpadgett** [comment]
@ruthkonyn I fixed guides this morning. here is screenshot from portal note tree line guides on left of form
![image](https://github.com/user-attachments/assets/9359b775-0e19-4952-9fff-58b8f52d379b)

**Comment by sjpadgett** [comment]
yeah!

![image](https://github.com/user-attachments/assets/c599409b-ae49-43b3-a1c7-6ae6013fb92a)

**Comment by sjpadgett** [comment]
@ruthkonyn I was finally able to get your crisp form to render all the nesting and those difficult multi answers.
New report should be good for most forms we run across. I may need to add a fourth level of nesting.
I didn't fully populate.

![image](https://github.com/user-attachments/assets/da700e5d-c076-4d7e-8adf-de1d6f76cb2f)

**Comment by ruthkonyn** [comment]
looks really good. thanks. look forward to trying it some more when I get back.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sjpadgett** [comment]
@ruthkonyn Note that I've completed the ckeditor replacement for all of portal. I also fix editor image and video dialogs to allow selecting from file system or drag and drop.
![image](https://github.com/user-attachments/assets/4a6840c1-95db-4071-a78c-f0e55acf9336)

fix help dialogs

![image](https://github.com/user-attachments/assets/a45fc5c3-80d8-4eea-b6d3-22e6dd2c3800)

**Comment by ruthkonyn** [comment]
thanks. look great. 

On 17 August 2024 02:07:02 BST, Jerry Padgett ***@***.***> wrote:
>@ruthkonyn Note that I've completed the ckeditor replacement for all of portal. I also fix editor image and video dialogs to allow selecting from file system or drag and drop.
>![image](https://github.com/user-attachments/assets/4a6840c1-95db-4071-a78c-f0e55acf9336)
>
>fix help dialogs
>
>![image](https://github.com/user-attachments/assets/a45fc5c3-80d8-4eea-b6d3-22e6dd2c3800)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/openemr/openemr/issues/7666#issuecomment-2294509801
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sjpadgett** [comment]
Created a new Config and Users section for Questionnaires. There will be more config items down the road.
A side note: I think we could move Patient Banner Bars' one item to Appearance to reduce left pane.

Ruth, I decided to turn on or off styles in globals because I couldn't find a good place to add a flag per import unless I modified a table and I'm just too lazy for that! lol

Besides take note that styles included in the SDC or FHIR questionnaires are implemented as inline and will almost always override current theme rule.

Feel free, and I encourage you, to continue adding to my custom style sheet as I've reorganized the directory tree to separate our maintained styles.
The sheet include conditional is in interface/forms/questionnaire_assessments/lform_webcomponents.php
I'm getting to the point I need to move on with developing evaluation of questionnaire results because I have a quick job coming up. But I do hope with a little guidance perhaps you will continue with improvements.
If not already you should checkout the newest builder that appears to have been fix and from my few minutes testing is more up to date and easier. https://formbuilder.nlm.nih.gov/
I'm considering adding it to my module for convenience.

![image](https://github.com/user-attachments/assets/2e5c7bcf-625d-4205-8cbc-d2ed6a9d4834)

**Comment by sjpadgett** [comment]
![image](https://github.com/user-attachments/assets/c53d3969-c42d-4b43-819c-f82e4924347a)

**Comment by ruthkonyn** [comment]
personally I prefer config- then there's just one place to look for configuration options. 

looking forward to continuing with playing with this next week. I did see the new nlh builder, looks good. 

I hope you are relaxing today (sunday)!! 

On 17 August 2024 22:14:02 BST, Jerry Padgett ***@***.***> wrote:
>Created a new Config and Users section for Questionnaires. There will be more config items down the road.
>A side note: I think we could move Patient Banner Bars' one item to Appearance to reduce left pane.
>
>Ruth, I decided to turn on or off styles in globals because I couldn't find a good place to add a flag per import unless I modified a table and I'm just too lazy for that! lol
>
>Besides take note that styles included in the SDC or FHIR questionnaires are implemented as inline and will almost always override current theme rule.
>
>Feel free, and I encourage you, to continue adding to my custom style sheet as I've reorganized the directory tree to separate our maintained styles.
>The sheet include conditional is in interface/forms/questionnaire_assessments/lform_webcomponents.php
>I'm getting to the point I need to move on with developing evaluation of questionnaire results because I have a quick job coming up. But I do hope with a little guidance perhaps you will continue with improvements.
>If not already you should checkout the newest builder that appears to have been fix and from my few minutes testing is more up to date and easier. https://formbuilder.nlm.nih.gov/
>I'm considering adding it to my module for convenience.
>
>![image](https://github.com/user-attachments/assets/2e5c7bcf-625d-4205-8cbc-d2ed6a9d4834)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/openemr/openemr/issues/7666#issuecomment-2294987371
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ruthkonyn** [comment]
@sjpadgett - it would make  more sense to me to move the LOINC terms message display configuration (top, bottom or both) from 'appearance' to 'questionnaire' - but it seems to have disappeared altogether - i'll take a look and submit a fix for this
