### ISSUE TITLE
Procedure Relations

### ISSUE THREAD

**Issue by A1Gard** [openemr/openemr#769]
Hello dears

when we try to add a procedure in openemr , it is added under one provider's position.
for example we have one common procedure which presents more than one provider and we want to use that procedure for more than one provider so this way we have to repeat the procedure more than one time in database . [The relation between the provider's & procedure's table is one 2 many ]

We need many 2 many relation.
Dose openemr has default solution for this issue or not? (And if I have to change the codes?)

**Comment by bradymiller** [comment]
@A1Gard ,

To clarify, what is a "provider" in Procedures->Providers. I've always been a bit confused by this. Is this the place that Provides the labs, or is this the actual medical provider that orders the labs?
(I could look this up if needed, but just figured you may know)

-brady

**Comment by MatthewVita** [comment]
@bradymiller,

I've been helping folks via support email about this subject so I can say with confidence that this is the lab system.

- m

**Comment by A1Gard** [comment]
@bradymiller 

The provider in Procedures->Providers section is the place that Provides a medical service such as laboratory center or imaging center etc.  

however in other sections of openemr such as calendar, the provider means a doctor who treats the patient.

**Comment by bradymiller** [comment]
Closing this since no discussion for > 6 months.
