### ISSUE TITLE
bug: js_xl not found in register-app.php scope

### ISSUE THREAD

**Issue by adunsulag** [openemr/openemr#7701]
I'm scratching my head on what changed, but the register-app.php file throws an error now saying js_xl is not found in the scope.  Not sure why that would be but I changed it up to use window.top.xl instead of js_xl.

**Comment by vnugent** [comment]
I'm seeing this same error in 7.02 when registering a new app.

<img width="753" alt="Image" src="https://github.com/user-attachments/assets/c081cabb-5745-4f61-b966-28b24265bd48" />

**Comment by sjpadgett** [comment]
Not sure when this went in production. Might just be in v7.0.3.
Checking repo the best I can tell and since we didn't track milestones till recent looks like didn't make any 7.0.2. patches.
Sorry this doesn't happen too often.
