### ISSUE TITLE
questionnaire alert displays white characters on white background

### ISSUE THREAD

**Issue by ruthkonyn** [openemr/openemr#7792]
when a questionnaire is being used with white characters on black background but mandatory fields have not been filled in, then when saving an alert is generated about the missing mandatory fields, however the question being mentioned is displayed with the white characters and the alert has a white background, so one cannot see the problem

![Screenshot from 2024-10-31 10-12-01](https://github.com/user-attachments/assets/4618c4c8-32f5-4047-8af0-8ea2592d3cf7)

1. open a questionnaire with formatting as white characters on black background
2. save the questionnaire having not filled in a mandatory field
 

### Expected behavior
the alert should either have a black background, or redisplay the characters in black

### Client configuration

- Browser: firefox
- OpenEMR version: 7.0.3-dev
- Operating system: ubuntu linux

**Comment by sjpadgett** [comment]
I'll look at soon @ruthkonyn

**Comment by sjpadgett** [comment]
@ruthkonyn can you send me this questionnaire? I don't have any with required set up and i'm lazy don't ya know!:)

**Comment by sjpadgett** [comment]
Never mind Ruth I found your forms. I have a fix but want to make more universal so stay tune!

![image](https://github.com/user-attachments/assets/f02536fb-9a6a-495d-8874-b3faed231dc0)

**Comment by ruthkonyn** [comment]
many thanks jerry! -
