### ISSUE TITLE
Where to submit demo bugs

### ISSUE THREAD

**Issue by mgifford** [openemr/openemr#7870]
I submitted the bug here:
 https://github.com/openemr/demo_farm_openemr/issues/59
 
 I can't access your demos.
 
 Just not sure where was the right place to see it was addressed.

**Comment by stephenwaite** [comment]
thanks @mgifford , you can post here or to the [forum](https://community.open-emr.org/t/online-demos-not-working/23932).

Main demos in the body of this page should be up in about 20 mins.
