### ISSUE TITLE
Core Advanced Prior Auth module custom patient menu broken

### ISSUE THREAD

**Issue by sjpadgett** [openemr/openemr#7871]
### Describe the bug

URL's are absolute but need to be relative.

### To Reproduce
![image](https://github.com/user-attachments/assets/bd847e13-0a89-4211-b613-fe34d885ccc2)

- turn on module.
- open a patient.
- try to use any of the patient menu links.

@juggernautsei I don't think I'm off base here but let me know. I don't understand why this hasn't come up!

### Client configuration

- Browser:
- OpenEMR version: 7.0.2.3 and dev
- Operating system:

**Comment by sjpadgett** [comment]
@juggernautsei Should we not offer code finder and rename from CPT's to Coding as SNOMEDS and LOINC could be used here.

![image](https://github.com/user-attachments/assets/36d7d030-ca4f-4168-8418-849f8d5a94d9)

**Comment by juggernautsei** [comment]
Ok, I will fix all this. I've run into this already

**Comment by sjpadgett** [comment]
Okay thanks but I already have PR up and I may go ahead and add code finder while here if okay with you.

**Comment by juggernautsei** [comment]
I didn't understand what finder has to do with the patient menu.

**Comment by juggernautsei** [comment]
Sure go ahead and repair.

**Comment by sjpadgett** [comment]
> I didn't understand what finder has to do with the patient menu.

To pick codes using Codes picker for authorization instead of adding by hand cpt4 codes. May not be needed so I'll add request for Clinicians input.

**Comment by juggernautsei** [comment]
The original people that requested the feature. They usually know what the
codes are and the received them with the authorization. No need to look
them up or use a code picker in my experience.

Sherwin
757-328-2736
Juggernaut Systems Express

       The most powerful EHR on the planet
<https://www.affordablecustomehr.com>

OpenEMR Simplicity at its best in cloud-based EMRs
“For those who believe, no proof is necessary. For those who don't believe,
no proof is possible <http://beingsaved.org/innercoc.va>.”

**Comment by sjpadgett** [comment]
Oh okay Sherwin agreed and will leave as it is. Thanks
