### ISSUE TITLE
Determine best practice to avoid "double escaping" in Doctrine

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#793]
## Context

The current working practice for Doctrine SQL injection prevention is to use the standard OpenEMR escaping functions before feeding data into Doctrine. However, @bradymiller has noted that this approach may not be sustainable.

## Problem

Per http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/security.html, we need to look out for "double escaping", which can lead to data corruption

## Actionables

1. Determine how to avoid the dreaded "double escapes".
2. Document how to properly escape for Doctrine in the Wiki. If the solution turns out to require the programmer to be aware of leaky abstractions in Doctrine, create a facade utility to avoid this.

**Comment by robertdown** [comment]
My two cents..... maybe it's time we migrate away from the old SQL functions and allow Doctrine to do all the work? I know Doctrine can handle SQL injection

**Comment by MatthewVita** [comment]
I agree @robertdown, but Brady and I are finding that there is some work on the user's side for escaping in some cases.
