### ISSUE TITLE
Adding a Provider to schedule alerts user "Provider is not available"

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#795]
When adding a provider to the calendar the user will be alerted that the "Provider is not available." This is misleading, that prompt should be exclusive to _patients_, not providers.

Currently you can just select and you get the correct results, it's just a misleading prompt.

**Comment by aalmangour** [comment]
40cecd443c3ad7b3c4539b1987d2e7e124ec5939

**Comment by bradymiller** [comment]
brought in @aalmangour 's nice fix:
https://github.com/openemr/openemr/pull/805
