### ISSUE TITLE
Determine Ideal Usages of an NLP Engine

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr#801]
## PROJECT

The Chart Summarization Research project is an effort led by Dr. André Millet. Dr. Millet has put forth an idea of using an algorithm to summarize the most vital parts of a patient's timeline. This research project will look into the technological, regulatory, and verification requirements for the development of such a module.

## ISSUE DESCRIPTION

This research issue involves identifying key usages of Natural Language Processing (NLP) in OpenEMR. The Open Health Natural Language Processing Consortium has put together a list of use cases for one to consider here: http://www.ohnlp.org/index.php/Main_Page (see _"What are the NLP use cases in the clinical domain?"_)

## TASKS
- [x] Determine key use cases for the typical OpenEMR user.
- [x] Consider the data at hand. For example, which encounter forms will be best for running the algorithm against.

**Comment by MatthewVita** [comment]
This can be closed. Dr. Millet and I have been talking about this in chat for weeks now. Basically we want to run cTAKES on all non-structured data for a giving patient and show the important bits as a "timeline" on the main patient page. The structured data can be summarized there as well.

Another great usage of the solution is with billing/insurance... basically codes can be determined by cTAKES.

Not sure how we want to distribute the solution because Docker will be needed and that's not the easiest to step up. Perhaps we can advertise it as an "add on" to OpenEMR and have a switch in globals that is defaulted to `false`.

**Comment by bradymiller** [comment]
agree with the:
Perhaps we can advertise it as an "add on" to OpenEMR in the Wiki and the website with a switch in globals that is defaulted to false.
