### ISSUE TITLE
Create Timeline View of Patient

### ISSUE THREAD

**Issue by robertdown** [openemr/openemr#808]
Create a view inside of patient file that collects all patient forms regardless of encounter to allow for better tracking of chronic health. Related to #800

**Comment by MatthewVita** [comment]
Thanks for entering this in. I believe the issues are separate enough and who knows what our research will turn up in ticket 800!

**Comment by robertdown** [comment]
it's a good feature, like Brady said, surprised we haven't implemented this before.
