### ISSUE TITLE
using bootstrap class form-control

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#817]
While reviewing bootstrap examples, it appears that only input text, textarea and select form controls require **form-control** class.  Is there any specific reason to assign form-control class to generated checkbox code in options.inc.php?
```
echo "<td width='$tdpct%'>";
echo "<input type='checkbox' name='form_{$field_id_esc}[$option_id_esc]'" .
"id='form_{$field_id_esc}[$option_id_esc]' class='form-control' value='1' $lbfonchange";
```
It may be better to use **checkbox** class for the parent and include a **_label_** tag around checkbox as shown in bootstrap documentation.
```
echo "<td class='checkbox' width='$tdpct%'>";
```

**Comment by bradymiller** [comment]
@mdsupport ,

This is something I also noted when partially converted all the reports to bootstrap. In that code, used the class checkbox in most places as is in the online example.

Although it's not documented, the direct use of the form-control class does give them the appearance of bootstrap checkboxes. The code in options.inc.php was the first run to get things working. Agree that will make sense to work in more standard use of bootstrap, especially after we get the following places in codebase layouts using the bootstrap:
Demographics, LBF, Facility Users thing
(note bootstrap is currently used in the history and transactions layout views)

**Comment by mdsupport** [comment]
Here is basic explanation regarding checkbox and radio button control from [bootstrap 4](https://v4-alpha.getbootstrap.com/components/forms/#checkboxes-and-radios-1).  Key change to current practice is adding label tag for bootstrap to do its own thing.  

Note the _indeterminate_ property offered by bootstrap that will be of tremendous help in situations where initial Yes/No state is not specified and currently developers are forced to use radio boxes to allow users to "uncheck" a box.

**Comment by robertdown** [comment]
We should stick with the bootstrap defined examples. Something I've noted throughout the program is radio and checkbox labels aren't associated with the input element which means you can't click on the label and have the element change.

Also, you mentioned bootstrap 4, we have to stay on v3 (the reason is somewhere in the forums, I just have to dig it up).

**Comment by mdsupport** [comment]
As the [Bootstrap 3](http://getbootstrap.com/components/#input-groups-checkboxes-radios) example shows, form-control does not apply to radio and checkbox.  Guess it needs bit more elaborate div & span combination vs simple label tag.

**Comment by bradymiller** [comment]
Agree with @mdsupport on readio/checkbox. Here are a couple examples of use in current codebase:
https://github.com/openemr/openemr/blob/master/interface/reports/services_by_category.php#L109-L112
https://github.com/openemr/openemr/blob/master/interface/reports/sales_by_item.php#L397-L400
