### ISSUE TITLE
fancybox position in demographics -> insurance search/add

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#819]
Has anyone had issue with fancybox popup position in demographics -> insurance search/add on smaller devices (12")?  The box is positioned such that the buttons (including Cancel which seems to be only way to close the box) are out of view.  Would it make sense to move the box to top?

Another issue related to same area, the select dropdown for insurance cos. is usually wide since it includes address.  This has the effect of pushing other elements to right.  

![emr](https://cloud.githubusercontent.com/assets/399047/26706520/f79e3b2a-46f2-11e7-9e40-606bc74fa299.png)

**Comment by robertdown** [comment]
Interesting. Good news though, fancybox is on it's way out and will be replaced with bootstrap-based modals. I'll put this script on the top of the conversion schedule.

**Comment by mdsupport** [comment]
Also consider qTip2 with an updated version as an alternative.  Very flexible and consistent so far.

**Comment by robertdown** [comment]
Bootstrap seems like the better path, we are  already committed to it for all other aspects of the UI, doesn't make much sense to use a different solution for just one aspect.
