### ISSUE TITLE
Prescription fields not necessary / 5.0.1

### ISSUE THREAD

**Issue by mrpenelope** [openemr/openemr#840]
In my quest for building a makeshift MAR for fun, I came across a problem, running certain queries, I noticed that when filling out a prescription, the fields are not mandatory, and as a result, I'm getting nonequivalent rows returned. This being said, is this an issue that needs to be addressed? Or is something like the Route on a prescription order not necessary in this case?

**Comment by mrpenelope** [comment]
For the record, I'm aware I can change the query to not show the Route, it was merely something I had put on there, and noticed this bug.

**Comment by robertdown** [comment]
Hi @mrpenelope, we're actually in the early phases of writing a MAR for OpenEMR! You can see some info [on the project wiki](https://github.com/openemr/openemr/wiki/MAR-Exploratory-Roadmap). Still early on and both @juggernautsei and I are fairly invested in other projects at the moment, but just wanted to make you aware, if you were interested in contributing

**Comment by mrpenelope** [comment]
@robertdown I may actually be interested, I already knew the project had been started, but I had seen no growth, so I didn't really know what direction to go in. I have a basic outside-the-application working publicly, but it's by no means complete.

**Comment by mrpenelope** [comment]
This still does not change the initial problem, though.

**Comment by mrpenelope** [comment]
@bradymiller What say you?

**Comment by juggernautsei** [comment]
@mrpenelope to your original request the default of the prescription form is all fields are optional but if you look at the JavaScripting in the add_edit there is code to turn on which fields you want to make mandatory.  My opinion is that the default should be mandatory to fill all fields and we should have a Global so that those users that don't want fields mandatory can turn them off.

**Comment by mrpenelope** [comment]
@juggernautsei I agree, it should be default, absolutely.

**Comment by mrpenelope** [comment]
@juggernautsei looking at the JS now

**Comment by mrpenelope** [comment]
@juggernautsei I'm looking at /templates/prescription/general_edit.html 
Is that correct?

**Comment by mrpenelope** [comment]
@bradymiller @juggernautsei @robertdown Can we get a resolution to this?

**Comment by mrpenelope** [comment]
Used file referenced, code is near the end. It's been enabled. Closing.
