### ISSUE TITLE
jquery version leaning

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#842]
Updated this summary on 11/28/19:

jquery versions to be removed:
DONE

Strategy given by @sjpadgett:
Recommend running a compatibility version in report dev mode which will log to the console incompatibilities. Would need to run a version to get to 2.2 then one to get to 3+.

Which breaks down to the 2 steps (note also need ```<!DOCTYPE html>``` at top of page for migrate script to work)
```
<script src="http://code.jquery.com/jquery-2.2.4.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.4.1.js"></script>
```
(note this reports it in theory only goes from version 1.6.4 so lesser versions will likely require some more testing)
```
<script src="https://code.jquery.com/jquery-3.1.1.js"></script>
<script src="https://code.jquery.com/jquery-migrate-3.0.1.js"></script>
```

Then can update main jquery to most recent version (not sure if can use the migrate-plugin for this???):
https://jquery.com/upgrade-guide/3.0/#jquery-migrate-plugin

To get to our goal, also a couple things:
-jquery-ui versions will also need to be integrate to just 1 (DONE)
-qtip2 will need to be converted to modern tooltip method (DONE) (https://github.com/openemr/openemr/issues/2083)

**Comment by bradymiller** [comment]
some background on jquery versions:
Main limitation I have noted regarding jquery is that fancybox is stuck at jquery 1.7.2; so option in those cases is to go to 1.7.2 if wish to get rid of 1.6.4. Also, if the script has other old jquery plugins (like the Administration->ACL), then may be sticky issues. Otherwise, recommend pushing it up and testing it (there are some things that break occasionally). As we bring the standard header class which brings in jquery 3.1.1 and bootstrap throughout the codebase, these old jquery versions will start dropping off :)
(another thing to note is that bootstrap requires jquery 1.9.1)

**Comment by robertdown** [comment]
Bootstrap requires a minimum of 1.9.1, can go all the way up to 3.

https://github.com/twbs/bootstrap/blob/v3.3.7/bower.json#L32

**Comment by bradymiller** [comment]
agreed. my above comment was confusing and just fixed it.

**Comment by bradymiller** [comment]
Need to confirm, but it appears the eye module may have bug from the  jquery-min-1-11-1 to  jquery-min-1-11-3 migration.

**Comment by girauch** [comment]
Hello- Do you need a tech writer to help you with documentation? I'm entering the field of tech writing, coming from a user experience background. It would be great to get a few projects under my belt to start a portfolio. Let me know! I'm on LinkedIn (https://www.linkedin.com/in/christinefgiraud/) and my website with resume: www.christinefgiraud.com.

**Comment by MatthewVita** [comment]
Hi @girauch,

We'd love to have you!

Our Wiki is the main channel for technical documentation. There are many opportunities for improvement there.

Let's get started by coming up with a plan over at https://community.open-emr.org/c/openemr-development. Creating an account is very easy. We can follow up there because this thread we're in now is for technical integrations.

My email is matthewvita48@gmail.com if you want to reach me directly.

Thanks,
Matthew

**Comment by MatthewVita** [comment]
@girauch I have specifically made https://community.open-emr.org/t/technical-writer-opportunities/8726 for you so we can list down and track the areas of the technical documentation that can be worked on!

**Comment by girauch** [comment]
Great, thanks!

CG

**Comment by bradymiller** [comment]
An example of a common issue when upgrading to modern version of jquery:
https://github.com/openemr/openemr/commit/35b2d50854b30d0aed6cbaee27bb4eabc6fd39c2

**Comment by robertdown** [comment]
This is why we should start separating from jQuery as a whole and move to a better, more modern JS framework. Yes, this is a shameless plug for Angular

**Comment by bradymiller** [comment]
Issue by eye form was fixed here: https://github.com/openemr/openemr/issues/1161
(Note it required used of jquery-min-1-10-2 and will break if go higher until fix the underlying issues in the code)

**Comment by sjpadgett** [comment]
Recommend running a compatibility version in report dev mode which will log to the console incompatibilities. Would need to run a version to get to 2.2 then one to get to 3+.

**Comment by bradymiller** [comment]
https://github.com/openemr/openemr/pull/2028

**Comment by bradymiller** [comment]
Gonna try to finish this up in very near future since likely necessary for the ongoing bootstrap v4 updates.

**Comment by bradymiller** [comment]
Completed, so closing this issue
