### ISSUE TITLE
lose past encounters and documents tab after selection

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#854]
basically have to clear the active patient and start again

i attached the screenshot of the tab affected
![untitled](https://user-images.githubusercontent.com/5618372/27054447-e127641c-4f8e-11e7-9e4b-1252a29f1517.png)

**Comment by bradymiller** [comment]
Can get to it in menu Patient/Client->Visits->Visit History. But agree, need to have way to get to this screen. Should have a "View Encounter Listing" selection on the pull down to get to this screen.

**Comment by stephenwaite** [comment]
thanks @bradymiller , be glad to add that option, i'll take a look and check back with you if i have questions

**Comment by sjpadgett** [comment]
Here is PR
https://github.com/openemr/openemr/pull/1150

**Comment by stephenwaite** [comment]
thanks @sjpadgett
