### ISSUE TITLE
ACL admin error

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#855]
Is the 'Standard' ACL interface being modified?  
In 5.0 no information is displayed when the check boxes for user or group are clicked.  Confirmed the same on demo.  Link to 'Advanced' works in demo.

**Comment by bradymiller** [comment]
That's a bummer. I was pretty sure I tested that on the jquery update from 1.2.1 to 1.2.2. Guessing that I broke that with that upgrade. I'll see if I can fix it with 1.2.2. Otherwise will need to bring back 1.2.1:
https://github.com/openemr/openemr/commit/410a5e146c41c2f2b1201afc35cb665d41427bf3

**Comment by bradymiller** [comment]
Just brought in fix into codebase for this (and dropped another legacy js library along the way :) ):
https://github.com/openemr/openemr/commit/9e20a99a33c46d75d474a9a58c76d530163a7c04

Tested very well. Let me know if it fixes things on your end,

**Comment by mdsupport** [comment]
Perfect. Thx.
