### ISSUE TITLE
past encounters enhancement

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#860]
Include the following code in your CSS to stop forcing users to click on the 'Past Encounters' box : 

```
.btn-group.dropdown:hover > ul.dropdown-menu {
  display: block;    
}
```

It also may be worth considering to make this box more intelligent.  Some of the suggestions are: 

- Filter by encounter type, issues etc
- Include age calculation in addition to the date display (nn days ago or n years ago ...)
- Limit number of encounters shown with paging mechanism
- Intelligent search

**Comment by robertdown** [comment]
Your CSS will have global impact on every btn-group with a dropdown menu. I don't think we have many right now, but just something to note.
