### ISSUE TITLE
ACL bugs

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#865]
There has been some nice ACL work(new acos and more granular) in OpenEMR over the last couple months. With this comes bugs though. Will use this to track the bug/fixes.
First bug:
Physicians ACL and Emergency Login ACL needs to have 'encounters'->'notes', or else is not able to open clinical notes/forms.

**Comment by bradymiller** [comment]
Second bug:
Physicians ACL and Emergency Login ACL needs to have 'write' for 'encounter'->'coding', or else is not able to open fee sheet.

**Comment by bradymiller** [comment]
Third bug:
see comment in this commit:
https://github.com/openemr/openemr/pull/839/files

**Comment by mdsupport** [comment]
Here is an approach we have taken for our custom development.  We encapsulate access control in globals as integral part of every script .  Before require for globals, the script specifies which entities / classes it plans to invoke and the type of operation it would perform for each.  An example would be:
```
$grants = array( "patient" => "view", "encounter"=>"create,delete,update");
```
globals.php will use this array/object and current user to transform this for use in the script.  It can also apply some global dependencies such as if patient access is not permitted then encounters, issues etc are not permitted as well -
```
$grants = array(
  "patient" => array ( "view"=>true ),
  "encounter" => array ("create"=>true,"delete"=>false,"update"=>true)
);

```
Now rest of the script can use $grants directly like `if($grants['encounter']['create']) {...}`.

Even better approach would be to create a grant class and let other classes inherit it in background.  Then `$objEncounter->delete()` will return error if code misses to check for permission.

**Comment by robertdown** [comment]
If this truly is blocking/critical, @bradymiller @sunsetsystems @MatthewVita and @stephenwaite we all need to stop all other development and fix this.

**Comment by bradymiller** [comment]
In the queue. Things work great for the admin user, but just need to do some reshuffling of the acos to ensure the other roles see what they are supposed. This is meant to say Blocking next release, not Blocking sleep/food/bathroom :)

**Comment by robertdown** [comment]
Understood. In my experience, "Blocking" has referred to a bug that is above Critical, as in it is blocking actual use of the app.

**Comment by bradymiller** [comment]
Main fix of this bug will be following:
If a acl role has access to an aco item with "any encounters" in it, also need to add the aco item with "my encounters" to their role.(appear to only be acos in Encounters category that have this issue).

**Comment by bradymiller** [comment]
TODO for me:
add an admin->menu for the menu editor

**Comment by bradymiller** [comment]
fixes just committed to codebase
