### ISSUE TITLE
prevent creation of another misc billing form for encounter

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#878]
am i looking in the right place?

https://github.com/openemr/openemr/blob/master/interface/patient_file/encounter/load_form.php

**Comment by stephenwaite** [comment]
guess i could put something in https://github.com/openemr/openemr/blob/master/interface/forms/misc_billing_options/new.php that checks if one is present for this encounter?

**Comment by bradymiller** [comment]
Agree that this is a very good idea (when I was testing this, I created 5 of them and kept wondering why my selections were not staying (ie. I assumed it was like the fee sheet and would just allow 1 form per encounter).
Recommend seeing how the fee sheet does this and using that mechanism, if possible.

**Comment by stephenwaite** [comment]
not sure how the fee sheet does this yet, don't see anything obvious in library/FeeSheet.class.php or library/FeeSheetHtml.class.php
one difference btw misc billing and fee sheet forms is that the fee sheet is not displayed in the encounter summary

my head starts to spin when i see the javascript openNewForm function, last nights cheap wine isn't helping either :)

**Comment by bradymiller** [comment]
yep, that wasn't good advice on my end. It appears fee_sheet is a very different animal than the other forms.

I think your original thought of using load_form.php is a good thought, however, upon thinking about it, your second thought of doing this in new.php sounds even better. basically if $_GET['id'] does not exist (which would then be a new form), then check (and collect if exists) the id of that form in the encounter and use that.

**Comment by stephenwaite** [comment]
how's this? https://github.com/stephenwaite/openemr/tree/more_misc_billing

**Comment by bradymiller** [comment]
Very close. check out my comment here:
https://github.com/stephenwaite/openemr/commit/0fdb52314fd03bd9841b941c28389dcb4416d68b

**Comment by bradymiller** [comment]
Stephens's following code fixed this, which is in the codebase.
https://github.com/openemr/openemr/pull/890
