### ISSUE TITLE
Failed upgrading Database

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#898]
Hi..
Got an error whileupgrading database after getting the most recent dev-tip from github. Its giving this error - 

Query Error

ERROR: query failed: UPDATE `list_options` SET `option_id` = 'DK', `title` = 'Ordering Provider' WHERE `list_id` = 'provider_qualifier_code' AND `option_id` = 'dk'UPDATE `list_options` SET `option_id` = 'DN', `title` = 'Referring Provider', `is_default` = '1' WHERE `list_id` = 'provider_qualifier_code' AND `option_id` = 'dn'INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`) VALUES ('provider_qualifier_code', 'DQ', 'Supervising Provider', '30', '0')

Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UPDATE `list_options` SET `option_id` = 'DN', `title` = 'Referring Provider', `i' at line 1

C:\xampp\htdocs\openemr\library\sql_upgrade_fx.php at 675:sqlStatement
C:\xampp\htdocs\openemr\sql_upgrade.php at 77:upgradeFromSqlFile(5_0_0-to-5_0_1_upgrade.sql)

**Comment by bradymiller** [comment]
thanks for the report. I just committed a fix for this.
-brady

**Comment by arnabnaha** [comment]
Thanks @bradymiller . It works great..closing this issue
