### ISSUE TITLE
Changing up some class namespaces

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#911]
Was considering changing the following namespaces from composer.json:
``````
            "common\\": "common",
            "common\\database\\": "common/database",
            "common\\logging\\": "common/logging",
            "common\\http\\": "common/http",
            "common\\utils\\": "common/utils",
            "entities\\": "entities",
            "services\\": "services",
            "repositories\\": "repositories",
            "OpenEMR\\Encounter\\Services\\": "interface/patient_file/encounter/Services",
            "OpenEMR\\Core\\": "library/core/src",
            "OpenEMR\\Menu\\": "library/menu"
``````
to the following:
``````
            "OpenEMR\\Common\\": "common",
            "OpenEMR\\Common\\Database\\": "common/database",
            "OpenEMR\\Common\\Logging\\": "common/logging",
            "OpenEMR\\Common\\Http\\": "common/http",
            "OpenEMR\\Common\\Utils\\": "common/utils",
            "OpenEMR\\Entities\\": "entities",
            "OpenEMR\\Services\\": "services",
            "OpenEMR\\Repositories\\": "repositories",
            "OpenEMR\\Encounter\\Services\\": "interface/patient_file/encounter/Services",
            "OpenEMR\\Core\\": "library/core/src",
            "OpenEMR\\Menu\\": "library/menu"
``````

Note just changing namespace and not paths (that can be done at a later date as accumulate more classes). Obviously I'd also adjust the current codebase to work with these new namespaces. thoughts?

**Comment by robertdown** [comment]
You have may blessing, but a lot of those are @MatthewVita's classes, so suggest his approval as well

**Comment by robertdown** [comment]
Also, It seems you could just do `OpenEMR\\Common\\": "common" and it _should_ pick up everything under the Common namespace

**Comment by bradymiller** [comment]
hi @MatthewVita ,
Just checking to make sure you're ok with me making the above class namespace changes.
thanks, -brady

**Comment by MatthewVita** [comment]
Oops, I missed the notification from 29 days ago. I feel silly.

I am very happy with these changes.

**Comment by bradymiller** [comment]
First PR for this is here:
https://github.com/openemr/openemr/pull/1054

**Comment by bradymiller** [comment]
this project is done :)
closing
