### ISSUE TITLE
Surfing projects through recent mega-commit for psr2 styling changes of entire codebase

### ISSUE THREAD

**Issue by bradymiller** [openemr/openemr#933]
Steps:
First, copy the most recent phpcs.xml script to use further below:
1. `git checkout upstream/master`
2. `cp ci/phpcs.xml ../`
3. `git checkout master`

Second, create a "transition" branch that will be used further below:
1. `git checkout 0d00c1c`
2. `git checkout -b phpcbf-filter-1`
2. `cp ../phpcs.xml ci/phpcs.xml`
3. `php ~/git/PHP_CodeSniffer/bin/phpcbf -n --extensions=php,inc --standard=ci/phpcs.xml .`
4. `rm ci/phpcs.xml`
5. `git commit -a -m "filter 1 for phpcbf"`

Third, now can start to update projects (using weno rx code as example):
1. `git checkout new_erx_2`
2. rebase all the commits into 1 commit
3. `git rebase 0d00c1c`  (basically rebasing it to code base before the megacommit was brought in)
4. `cp ../phpcs.xml ci/phpcs.xml`
5. `php ~/git/PHP_CodeSniffer/bin/phpcbf -n --extensions=php,inc --standard=ci/phpcs.xml .`
6. `rm ci/phpcs.xml`
7. `git commit -a -m "temp phpcbf run"`
8. `git rebase -i HEAD~2` (and combine these 2 commits into 1 commit)
9. `git rebase phpcbf-filter-1`
10. `git checkout upstream/master`
11. `git checkout -b new_erx_3`
12. `git cherry-pick  <sha1 from the top commit that was created in step 9 above>`
DONE :)

**Comment by sunsetsystems** [comment]
This is to upgrade work in progress that started before July 13?

**Comment by bradymiller** [comment]
Hi @sunsetsystems ,

yes,
The reason need to so part 2 is that the phpcbf run seems to be a bit environment specific. And, it works much better when the the phpcbf runs are identical (because then step 7 of third part then basically cancels out the phpcbf run stuff and should just be left with your code). This will also cover any additional codebase wide changes we do in the future (which is why grab phppcs from master before running the phpcbf).

(I'm glad to do this on code that needs to come in; just point me to it)

-brady

**Comment by bradymiller** [comment]
No longer pertinent, so closing this.
