### ISSUE TITLE
Open

### ISSUE THREAD

**Issue by nkduodu** [openemr/openemr#934]
Hello.how do I join this group? Interested in using openemr in the cloud for some developing country projects. Rookie question..why do I need openvpn when this is already accessible via aws.?

**Comment by bradymiller** [comment]
Hi @nkduodu ,

Welcome to the project!

Check out the project website here, which has links for a forum, chat, and also documentation on wiki.

Is your openvpn question referring to using OpenEMR in the cloud?
https://github.com/openemr/openemr/tree/master/cloud/v1-Beta-AWS-Guide

-brady

**Comment by bradymiller** [comment]
forgot to post the website link above, here it is:
http://www.open-emr.org/

**Comment by nkduodu** [comment]
thank you. Is Openemr getting an inpatient module soon?

**Comment by MatthewVita** [comment]
Hi @nkduodu,

OpenVPN is only needed for the Cloud Deployment of OpenEMR so you can access the private system resources as an admin. The resources are fully locked down in a private Amazon cloud.

The inpatient project just started. Do you have any programming, design, QA, medical hardware, or clinical experience? We can use more volunteers!

Thanks,
Matthew Vita

**Comment by nkduodu** [comment]
Hi Matthew,

thanks for the reply. Unfortunately i'm neither a programmer or designer.
I'm trying to run a pilot project for a clinic in West Africa and they need
an application that has In-Patient features and Drug Administration.
My role is to buy the IT hardware, install the app either on-site or in the
cloud and then train the staff on how to use OpenEMR.

based on this, do let me know how i can be of help. this is a wonderful
project.

Regards,

Nana

**Comment by robertdown** [comment]
Hi @nkduodu 

We've seen clinics successfully use OpenEMR as-is for inpatient use. What are your specific requirements? We may be able to find a solution in the short term. Feel free to send me a private message on the forums (username is robert.down)

**Comment by MatthewVita** [comment]
Hi @nkduodu,

The OpenEMR cloud solution is ready. Would you like me to show you how to get started?

Thanks,

Matthew Vita

**Comment by nkduodu** [comment]
Yes please

⁣Sent from TypeApp ​

**Comment by MatthewVita** [comment]
@nkduodu: please follow this guide along: https://github.com/GoTeamEpsilon/OpenEMR-Cloud

Let me know if you have any questions!

**Comment by bradymiller** [comment]
Closing his issue since no discussion for more than 6 months
