### ISSUE TITLE
ORDataObject

### ISSUE THREAD

**Issue by mdsupport** [openemr/openemr#974]
@MatthewVita - Are ORDataObject based classes in library/classes included in Doctrine scope?

**Comment by MatthewVita** [comment]
ORData and Doctrine are two separate things, but the patterns are similar.

**Comment by MatthewVita** [comment]
I encourage the use of Doctrine, but really they both are cleaner than the old school way.

**Comment by mdsupport** [comment]
We understand that ORData and Doctrine are two separate things. ORDataObject based classes, specifically relating to Documents have been used in existing code base in unusal way with significant business logic.  Was making sure there are no parallel development activities that will cause avoidable rework.  Thx.

**Comment by MatthewVita** [comment]
Okay, I see what your question is now.

Looks like you have a plan though.

Thanks!
